from .dsl import P, N, added, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *
from .saga_gen import B, C

CHAPTER = chapter(
    6, "Descent into the Blood Moon",
    "Guided by the masked wanderer, who was once one of them, you descend into the Blood Moon Abyss. "
    "Obelisks drink the blood of caged cultivators, Han Xue is taken, and at the Altar of Blood the traitor feeds the seal to its prisoner.",
    "ch06_intro", "blood_abyss",
    [
        # ---------------------------------------------------------------- q051
        quest("An Unlikely Guide",
              "The Sect Master sends you and Han Xue after the traitor. A masked stranger waits at the gate with an offer.",
              "sect", [
                  talk(YUN, "Receive your orders from the Sect Master",
                       (YUN, "The Abyss is a wound in the world. A sect army would be seen for a hundred miles. Two disciples might not."),
                       (YUN, "Find Gu. Find the captives. Do not face the Patriarch's servants alone if you can help it."),
                       (YUN, "And {player}... come back. That is not a request.")),
                  talk(YE, "Meet the masked wanderer at the sect gate",
                       (YE, "You'll need a guide. The Abyss eats people who don't know where to step."),
                       (HAN, "Why should we trust you?"),
                       (YE, "You shouldn't. But I know the Abyss. I was born to it. I'll show you the way down, and you decide the rest."), at="SectGate"),
                  cinematic("ch06_intro", "Descend into the Blood Moon Abyss"),
                  reach("CanyonEntrance", "Enter the crimson canyon",
                        (N, "The air is warm and wet, and tastes of copper. Somewhere far below, a drum beats slowly, like a heart."),
                        (HAN, "That's not a drum.")),
              ], xp=400),
        # ---------------------------------------------------------------- q052
        quest("The Field of Bones",
              "Cross the plain of bones, where the Blood Moon's sentries hunt.",
              "blood_abyss", [
                  reach("BoneField", "Cross onto the field of bones",
                        (N, "Bones crunch underfoot, bleached white under the red moon. Dead trees claw at the sky."),
                        (YE, "Walk softly. The sentries listen for the crack of bone.")),
                  defeat("demon_cultivator", 4, "BoneField", "Clear the sentries on the field of bones"),
                  collect("demon_core", 3, "BoneField", "Collect the sentries' demon cores"),
                  talk(YE, "Talk with Ye Wuming at the canyon mouth",
                       (YE, "You fight well. You hesitate before the killing blow. That will get you killed here."),
                       (P, "They were people once, weren't they?"),
                       (YE, "Children stolen from villages. Raised on blood and fear. I was one. The Patriarch took my name when I was six."),
                       (YE, "Ye Wuming. It means nameless night. I chose it myself. It is the only thing here I ever chose."),
                       added(HAN, "A name you chose yourself. That's worth more than most names, Ye Wuming."), at="CanyonEntrance"),
              ], xp=420, items={"demon_core": 1}),
        # ---------------------------------------------------------------- q053
        quest("The Blood Pools",
              "The miasma from the blood pools eats at your qi. Blood lotus growing there can neutralise it, if you can stand the smell.",
              "blood_abyss", [
                  collect("blood_lotus", 4, "BloodPools", "Harvest blood lotus from the steaming pools"),
                  defeat("corrupted_wolf", 3, "BloodPools", "Drive off the blood-fed wolves drinking at the pools"),
                  meditate("BloodPools", 6, "Purify the lotus and steady your qi",
                           (N, "The lotus hisses in your palm. You draw on the Heart Sutra. Mud, root, blossom. The red fades to a clean, pale pink.")),
                  reach("BoneField", "Share the purified lotus with Han Xue",
                       (HAN, "It tastes like rust and flowers. Thank you."),
                       (HAN, "I don't trust him. But he hasn't led us into a trap yet. That's either honesty or patience."),
                       (P, "Or both. People can be both."),
                       added(YE, "I can hear you, Han Xue. Patience. I've had a great deal of practice at it.")),
              ], xp=420, items={"blood_lotus": 1}),
        # ---------------------------------------------------------------- q054
        quest("Ambush at the Obelisks",
              "A ring of obelisks pulses with stolen blood. Investigate it, carefully.",
              "blood_abyss", [
                  interact("demon_obelisk", "ObeliskRing", "Examine the demonic obelisk",
                           (N, "Runes crawl across the black stone like beetles. Thin threads of blood run from the obelisks down into the dark."),
                           (YE, "They pull the life out of the prisoners and pour it into the altar. Every drop weakens your seal.")),
                  defeat("blood_guard", 4, "ObeliskRing", "Fight off the Blood Guard ambush",
                         (XUEMEI, "Little lambs from the Azure Cloud. And one lost puppy, come home at last. Hello, Wuming."),
                         (YE, "Xue Mei. Crimson Elder. Stay close to me."),
                         added(HAN, "Crimson Elder or not, she bleeds like anyone. {player}, watch the left!"),
                         added(P, "I see them. Back to back!"),
                         (XUEMEI, "I'll take the pretty ice sword for the cages. Kill the rest.")),
                  reach("BloodPools", "Regroup with Ye Wuming by the blood pools",
                       (YE, "They took Han Xue. Xue Mei wanted her alive. Her blood is pure. They'll put her in the cages."),
                       (P, "Then we go to the cages. Now."),
                       (YE, "Not now. The obelisks will sense you. Break them first, or the cages will drain her before we arrive.")),
              ], xp=460, items={"medicine": 2}),
        # ---------------------------------------------------------------- q055
        quest("Shattering the Obelisks",
              "Ye Wuming knows a counter-rune. Gather the rune fragments and break the obelisk ring.",
              "blood_abyss", [
                  collect("rune_fragment", 3, "ObeliskRing", "Collect rune fragments around the obelisks"),
                  interact("demon_obelisk", "ObeliskRing", "Shatter the heart obelisk with the counter-rune",
                           (N, "You press the fragments to the obelisk in Ye Wuming's pattern. Your pendant blazes. The black stone cracks like ice."),
                           (N, "One by one, the obelisks crumble. Far off, in the dark, many voices gasp at once, like people breathing for the first time in days.")),
                  defeat("demon_cultivator", 3, "BoneField", "Deal with the guards drawn by the noise",
                         added(XUEMEI, "You broke my ring, little lamb. Your ice-sword friend screams so prettily for you. Kill them, my dears."),
                         added(YE, "She won't fight us herself. Not yet. She likes to watch. Break the guards."),
                         added(P, "Where is Han Xue, Xue Mei? Where is she?")),
                  reach("CanyonEntrance", "Confer with Ye Wuming",
                       (YE, "The cages are past the war camp. They'll be expecting us now. Good. Expecting and ready are different things."),
                       (YE, "You could have left me at your sect gate. Why didn't you?"),
                       (P, "Because you've never lied to me. Not once. That's rare.")),
              ], xp=460, items={"rune_fragment": 1}),
        # ---------------------------------------------------------------- q056
        quest("The War Camp",
              "The Blood Moon war camp stands between you and the cages. Its command tent may hold answers.",
              "blood_abyss", [
                  reach("DemonCamp", "Approach the war camp",
                        (N, "Crimson banners, black tents, and drums. Hundreds of warriors drill in silent rows."),
                        (YE, "The command tent is at the centre. Where there are orders, there are answers.")),
                  defeat("blood_guard", 5, "DemonCamp", "Break through the Blood Moon war camp",
                         added(TIE, "The sect brat? Here? Don't look at me like that. They have our families in those cages."),
                         added(YE, "Iron-Fang. So the Abyss owns you too. Stand aside, or stand with them."),
                         added(P, "Then help us free them, Tie Hu."),
                         added(TIE, "Not today. Today I didn't see you. Run, before I remember that I did.")),
                  collect("letter", 2, "DemonCamp", "Seize the sealed letters from the command tent"),
                  reach("BloodPools", "Read the letters with Ye Wuming",
                       (YE, "This one is orders. A siege on Qingshi Town, with Iron-Fang's bandits, before the next blood moon."),
                       (YE, "This one is in Gu's hand. To the Patriarch. The diagram is delivered. Remember your promise. Remember Lan."),
                       (P, "Lan? Gu Lan was his daughter. She died twenty years ago."),
                       (YE, "The Patriarch makes many promises to grieving fathers. He keeps very few.")),
              ], xp=480, items={"letter": 1}),
        # ---------------------------------------------------------------- q057
        quest("The Iron Cages",
              "The prison cages hold every missing soul from Qingshi, and Han Xue.",
              "blood_abyss", [
                  reach("PrisonCages", "Reach the prison cages",
                        (N, "Iron cages hang over a pit, each one crowded with pale, silent people. Somewhere a man is singing a lullaby, badly."),
                        (YE, "The guards change at the red hour. That's now. Go.")),
                  defeat("blood_guard", 4, "PrisonCages", "Defeat the cage wardens"),
                  interact("prison_cage", "PrisonCages", "Break open the cages",
                           (HAN, "About time. I was starting to compose my death poem. It was very good. Nobody will ever hear it."),
                           added(P, "Senior Sister! Can you stand?"),
                           added(YE, "She can stand. She can also complain, which is better."),
                           (N, "Farmers, fishermen, disciples of three sects. A young man with Xiao Man's eyes. And a boy who says his name is Liu Er.")),
              ], xp=500, items={"spirit_stone": 5}),
        # ---------------------------------------------------------------- q058
        quest("What the Prisoners Saw",
              "The prisoners are free, but weak. Some of them have seen the altar.",
              "blood_abyss", [
                  talk(SHI, "Speak with Xiao Shi",
                       (SHI, "You're from the sect? My sister... is Xiao Man all right? Is she eating? She forgets to eat."),
                       (SHI, "I followed the lanterns from the river. They caught me at the graves. They've been bleeding us for weeks."),
                       (SHI, "An elder from our sect was here. Gu. He stood by the altar and talked to the blood like it was a person."),
                       added(HAN, "Gu. At the altar. Then he's already there."),
                       added(P, "Your sister is well, Xiao Shi. She'll be better when she sees you."), at="PrisonCages"),
                  collect("medicine", 4, "DemonCamp", "Recover stolen medicine for the prisoners"),
                  talk(HAN, "Send the prisoners home with Han Xue",
                       (HAN, "I'll lead them out. Ye Wuming marked the path. You two go to the altar."),
                       (HAN, "And {player}? If Gu is there... don't hesitate. He won't."),
                       (P, "Get them home safe, Senior Sister. We'll be right behind you."), at="CanyonEntrance"),
              ], xp=460, items={"medicine": 2}),
        # ---------------------------------------------------------------- q059
        quest("The Altar of Blood",
              "At the great altar, the stolen blood flows into the seal. The traitor is there, and he is not alone.",
              "blood_abyss", [
                  cinematic("ch06_altar", "Witness the ritual at the Altar of Blood"),
                  defeat("demon_elder", 1, "AltarOfBlood", "Defeat Crimson Elder Xue Mei",
                         (XUEMEI, "You broke my obelisks and stole my lambs. I'll wear your skin to the Patriarch's awakening."),
                         (P, "You'll have to catch me first."),
                         (XUEMEI, "Oh, I love it when they run."),
                         added(YE, "Nameless remembers you, Xue Mei. He remembers everything you ever did to him.")),
                  interact("blood_altar", "AltarOfBlood", "Disrupt the blood ritual",
                           (N, "You drive the Lotus Key against the altar. Green light floods the channels of blood, and the ritual chokes and dies."),
                           (N, "Far below, something vast roars in frustration. The whole abyss shudders."),
                           (YE, "Gu is gone. Fled deeper. But you've bought the seal time. Months, maybe.")),
              ], xp=700, items={"demon_core": 2, "spirit_stone": 5}),
        # ---------------------------------------------------------------- q060
        quest("Core Formation",
              "The battle has pushed your qi to its limit. In the deepest part of the abyss, forge your golden core, then bring the news home.",
              "blood_abyss", [
                  talk(YE, "Decide the fate of the captured acolytes with Ye Wuming",
                       (YE, "These three surrendered. Children, really. Blood Moon trained. The sect would execute them."),
                       (P, "They were stolen, like you. Take them. Teach them their own names."),
                       (YE, "...You are a strange cultivator, {player}. Very well. I will try."), at="BoneField"),
                  meditate("AbyssDepths", 12, "Form your golden core in the abyss depths",
                           (N, "Killing intent presses from every side. Your foundation cracks, and from the crack rises light."),
                           (N, "Your qi spins, tightens, and condenses into a golden core, bright as a small sun in the dark of the abyss."),
                           (P, "The darkness can't touch it. I can feel it burning.")),
                  talk(MAN, "Return Xiao Shi to his sister",
                       (MAN, "Brother! Brother, you idiot, you absolute idiot, you never wrote!"),
                       (SHI, "There were no brushes in the cage, Man Man."),
                       (MAN, "{player}, I... thank you. I'll pick herbs for you for a hundred years. I'll only drop some of them."),
                       added(P, "He counted the bars every night, Xiao Man. He never stopped thinking of you."), map="sect"),
                  talk(YUN, "Report to the Sect Master",
                       (YUN, "A golden core, the captives freed, and the ritual broken. You went down a disciple and came back a pillar."),
                       (YUN, "But Qingshi is next. If the letters are true, the Blood Moon marches before the next blood moon."),
                       (YUN, "Rest one night. Then we defend the town. We will not let it bleed a second time.")),
              ], xp=900, items={"spirit_stone": 8}, realm="Core Formation"),
    ])

# The ritual is broken and Gu has fled deeper, but the Abyss is not done with
# you yet. Spliced in between "The Altar of Blood" and "Core Formation".
EXTRA = C(
    "Descent into the Blood Moon", "blood_abyss",
    "The ritual is broken and the traitor has fled deeper into the Abyss, but freed prisoners still need guiding out, "
    "Ye Wuming's own ghosts still walk here, and the seal's reprieve is not the same as safety.",
    cast=[YE],
    foes=["blood_guard", "demon_cultivator"],
    items=["demon_core", "rune_fragment", "medicine"],
    props=["demon_obelisk", "prison_cage"],
    beats=[
        B("rescue", "Stragglers From the Cages",
          "A few prisoners, too weak to walk with Han Xue's group, were left behind in the confusion of the ritual's collapse.",
          (YE, "Not everyone made it out with your senior sister. Some couldn't stand. We go back for them."),
          v=0),
        B("hunt", "Xue Mei's Remaining Guard",
          "Word of the Crimson Elder's defeat hasn't reached every corner of the Abyss. Some of her guards still hold their posts.",
          foe="blood_guard", v=0),
        B("gather", "What the Altar Left Behind",
          "The broken altar's chamber holds fragments worth recovering before the Abyss reclaims them.",
          item="demon_core", v=0),
        B("probe", "Ye Wuming's Old Cell",
          "Deeper in the war camp, Ye Wuming finds the cell where he was raised, and stops walking for a long moment.",
          (YE, "I haven't seen this door in thirty years. I thought it would be smaller."),
          v=0),
        B("social", "What Xue Mei Called Him",
          "Ye Wuming says little about being called 'lost puppy,' but it clearly cost him something to hear.",
          (P, "She knew your name. Your real one."),
          (YE, "She gave it to me. Before I chose Wuming, I had a name she picked. I don't use it. I don't remember why she did."),
          v=0),
        B("hunt", "The Last Sentries",
          "A final knot of demonic cultivators, cut off from orders, still guards the road back toward the canyon entrance.",
          foe="demon_cultivator", v=0),
        B("gather", "Rune Fragments From the Ring",
          "Elder Bai will want every fragment of the shattered obelisks studied once you're home.",
          item="rune_fragment", v=0),
        B("cultivate", "Steadying Before the Depths",
          "Before attempting the golden core, Ye Wuming insists on a proper rest, however impatient you are.",
          (YE, "The depths don't forgive an unsteady foundation. Sit. I'll watch. I'm good at watching."),
          v=0),
        B("social", "A Question for Ye Wuming",
          "Before you go deeper, you ask Ye Wuming outright whether he intends to keep helping past this point.",
          (P, "You could leave. You've paid whatever debt you thought you owed."),
          (YE, "I stopped counting debts a long time ago. I'm not doing this for a debt anymore."),
          v=0),
        B("gather", "Medicine for the Walk Out",
          "The freed prisoners' path back to the canyon entrance is long. Extra medicine won't go to waste.",
          item="medicine", v=0),
    ])
