from .dsl import P, N, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *

CHAPTER = chapter(
    5, "The Inner Sect Tournament",
    "Banners rise over the Azure Cloud for the Inner Sect Tournament. Rivals become partners, a poisoned pill box "
    "points at the Law Hall, and on the night of the final the traitor finally shows his face.",
    "ch05_intro", "sect",
    [
        # ---------------------------------------------------------------- q041
        quest("Banners on the Mountain",
              "The Inner Sect Tournament begins. Register with the Treasury Steward, then catch up on the gossip at the gate.",
              "sect", [
                  cinematic("ch05_intro", "Watch the opening of the Inner Sect Tournament"),
                  reach("FormationArray", "Take in the tournament stage",
                        (N, "Banners of every peak ring the plaza. Disciples crowd the walls and railings. Someone is selling roasted chestnuts at twice the price.")),
                  talk(QIAN, "Register with Steward Qian",
                       (QIAN, "Registration fee: two spirit stones. Non-refundable. Especially if you lose. Particularly if you die."),
                       (P, "The Sect Master told me to enter. Personally."),
                       (QIAN, "Then the Sect Master can pay. Fine, fine. Waived. Don't tell anyone. I have a reputation.")),
                  talk(LU, "Hear the gossip from Lu Ping",
                       (LU, "The betting pool is open! Yan Tie, three-time champion, two to one. Zhao Kang, five to one."),
                       (LU, "You're at nine to one. I put three stones on you. Don't tell Steward Qian. Actually, win, then tell him."),
                       (LU, "Oh, and Elder Gu is supervising the pill supplies this year. First time ever. Very thorough man.")),
              ], xp=260),
        # ---------------------------------------------------------------- q042
        quest("Sharpening the Blade",
              "Wei Tong insists on one last training session before the preliminary round.",
              "sect", [
                  talk(WEI, "Train with Wei Tong",
                       (WEI, "Right. Foundation Establishment. So the puppets need to be angrier. I've had them tuned up."),
                       (WEI, "Four at once. If you get hit, you buy lunch. If you don't get hit, I buy lunch. Either way, lunch.")),
                  defeat("training_puppet", 4, "TrainingGround", "Defeat four enhanced training puppets"),
                  talk(WEI, "Report back to Wei Tong",
                       (WEI, "Not a scratch. I'm buying lunch. I'm always buying lunch. How did this happen to me?"),
                       (WEI, "Listen. Yan Tie is strong, but he fights like a landslide, all at once. Make him chase you and he'll tire.")),
              ], xp=260, items={"medicine": 2}),
        # ---------------------------------------------------------------- q043
        quest("The Preliminary Round",
              "Three opponents on the formation plaza. Elder Mo is referee, and he does not believe in mercy.",
              "sect", [
                  talk(MO, "Report to Elder Mo, the referee",
                       (MO, "Rules: no killing, no crippling, no weeping on the formation. Last one standing advances."),
                       (MO, "And {junior}? Don't embarrass me. I told the other elders you were adequate.")),
                  defeat("sparring_disciple", 3, "FormationArray", "Win the preliminary round",
                         (MO, "Begin!")),
                  defeat("sparring_disciple", 2, "FormationArray", "Win the deciding bout of your bracket",
                         (MO, "Two more from Cloud Peak who think they were robbed. Settle it.")),
                  talk(MO, "Receive Elder Mo's verdict",
                       (MO, "Adequate. More than adequate. Hmph. Don't let it go to your head. Heads are heavy enough already."),
                       (P, "Was that a compliment, Elder Mo?"),
                       (MO, "It was an observation. Go and eat something. You look like a boiled noodle.")),
              ], xp=280, items={"spirit_stone": 3}),
        # ---------------------------------------------------------------- q044
        quest("Whispers at Night",
              "Zhao Kang slipped out through the moon gate after curfew. Follow him.",
              "sect", [
                  reach("MoonGate", "Follow Zhao Kang to the moon gate",
                        (N, "A figure in gold-trimmed robes slips through the moon gate, carrying a bundle of incense sticks."),
                        (P, "Sneaking out the night before the second round? What are you up to, Zhao Kang?")),
                  talk(ZHAO, "Confront Zhao Kang at the cliff edge",
                       (ZHAO, "Go ahead. Report me to the Law Hall. It's what they're for."),
                       (ZHAO, "My elder brother Zhao Ming died a year ago tonight. A Law Hall mission. Bandits, they said, in the bamboo forest."),
                       (ZHAO, "I burn incense here because he liked the view. That's all. That's all it is."),
                       (P, "I'm sorry, Zhao Kang. Who assigned his mission?"),
                       (ZHAO, "Elder Gu. Same as yours. Why does that matter?"), at="CliffEdge"),
                  talk(HAN, "Tell Han Xue what you found",
                       (HAN, "Zhao Ming. I remember him. He was kind. He was also ambushed in exactly the place you were ambushed."),
                       (HAN, "Elder Gu assigned both missions. The Law Hall held the Blood Moon token. Law Hall seals are on the missing pages."),
                       (HAN, "That isn't proof. It's a pattern. I'll watch the Law Hall. You win the tournament. Don't let him see you suspect.")),
              ], xp=280),
        # ---------------------------------------------------------------- q045
        quest("The Hundred-Disciple Melee",
              "The second round is a melee on the plaza. Wei Tong was knocked out early and is taking it well. Mostly.",
              "sect", [
                  talk(WEI, "Console Wei Tong",
                       (WEI, "Eliminated. By a girl half my size who hid behind a banner and poked me in the kidney. Twice."),
                       (WEI, "Honestly, it was brilliant. I'm going to learn it. Go on. Avenge my kidney.")),
                  defeat("sparring_disciple", 4, "FormationArray", "Survive the melee",
                         (MO, "Second round! Everyone against everyone! Try not to hit the audience!")),
                  collect("spirit_stone", 3, "SectGate", "Help Lu Ping gather his scattered winnings"),
                  talk(LU, "Collect Lu Ping's thanks",
                       (LU, "You're into the semifinal! I've won eleven stones! I'm rich! I'm going to buy a hat!"),
                       (LU, "Also, a Law Hall disciple told me to stop betting on you. Rude, right? I bet more.")),
              ], xp=300, items={"spirit_stone": 3}),
        # ---------------------------------------------------------------- q046
        quest("The Poisoned Cup",
              "Elder Hua has found something wrong with the tournament pills.",
              "sect", [
                  talk(HUA, "Answer Elder Hua's urgent summons",
                       (HUA, "Frenzy Pills. Blood lotus and wolf's bane, hidden inside Vitality Pills. They burn a cultivator from the inside."),
                       (HUA, "Three boxes were meant for the finalists' quarters. I need four moonbell herbs to brew an antidote. Hurry.")),
                  collect("spirit_herb", 4, "HerbGarden", "Gather moonbell herbs for the antidote"),
                  talk(MAN, "Ask Xiao Man what she saw",
                       (MAN, "The pill boxes? A disciple in Law Hall grey carried them in. He said Elder Gu approved them personally."),
                       (MAN, "One box went to Yan Tie's room. He's the champion. He's so strong already, why would he need pills?"),
                       (P, "Maybe he doesn't know what's in them.")),
                  talk(HUA, "Deliver the herbs to Elder Hua",
                       (HUA, "Good. I'll brew the antidote tonight. If Yan Tie has taken a Frenzy Pill, he will not know friend from foe."),
                       (HUA, "Tell no one about the Law Hall yet. An accusation without proof is just a very loud way to die.")),
              ], xp=300, items={"medicine": 3}),
        # ---------------------------------------------------------------- q047
        quest("Partners in the Semifinal",
              "The semifinal is a paired bout, and fate has a sense of humour: your partner is Zhao Kang.",
              "sect", [
                  talk(ZHAO, "Find your partner in the plum garden",
                       (ZHAO, "Of all the disciples in all the peaks. Fine. Stay on my left. Don't slow me down."),
                       (P, "You're still limping from the shrine."),
                       (ZHAO, "Then stay on my right. Whatever. Just win.")),
                  defeat("sparring_disciple", 5, "FormationArray", "Win the paired semifinal with Zhao Kang",
                         (ZHAO, "Five of them? Good. I was worried this would be boring."),
                         (P, "On your left, Zhao Kang!"),
                         (ZHAO, "I SEE them!")),
                  talk(ZHAO, "Talk with Zhao Kang on the stone bridge",
                       (ZHAO, "You fight like a farmer. Stubborn, unpolished, impossible to knock over."),
                       (ZHAO, "That was a compliment. Don't get used to it."),
                       (ZHAO, "Win the final. If anyone is going to beat Yan Tie, it should be the person who's going to lose to me someday."), at="StoneBridge"),
              ], xp=320, items={"spirit_stone": 3}),
        # ---------------------------------------------------------------- q048
        quest("Eve of the Final",
              "The night before the final, Elder Gu summons you. It is not about the tournament.",
              "sect", [
                  talk(GU, "Answer Elder Gu's summons",
                       (GU, "Congratulations on reaching the final. An unlikely journey for a village orphan."),
                       (GU, "Tournament rules forbid external artifacts. Bring your pendant to the Law Hall tonight for inspection."),
                       (P, "It's not an artifact, Elder. It's a family keepsake."),
                       (GU, "Then you have nothing to fear. The Law Hall. Tonight. Do not make me ask again.")),
                  talk(MO, "Ask Elder Mo about the rule",
                       (MO, "Inspection? There's no such rule. There never has been. I wrote half the tournament rules myself."),
                       (MO, "Gu... no. He is grieving, not wicked. Still. Don't go. If he asks, tell him I forbade it."),
                       (MO, "Go and clear your head. You've a champion to face at dawn.")),
                  meditate("StoneBridge", 8, "Steady your dao heart on the stone bridge",
                           (N, "The pond is still. The moon lies in it, whole. You breathe until your heart lies as still as the water.")),
                  talk(HAN, "Speak with Han Xue in the pavilion",
                       (HAN, "Gu asked for the pendant? Then he's run out of patience. That makes him dangerous."),
                       (HAN, "Win tomorrow. I'll be watching the pagoda. If the Law Hall moves while everyone watches the final, I'll know.")),
              ], xp=300),
        # ---------------------------------------------------------------- q049
        quest("The Final Bout",
              "Face Yan Tie, three-time champion of the Inner Sect Tournament. Something is wrong with his eyes.",
              "sect", [
                  talk(MO, "Step up for the final",
                       (MO, "The final! {player} of the Outer Court against Yan Tie of Thunder Peak, champion three years running!"),
                       (MO, "Bow to your opponent. Bow to the Sect Master. And for heaven's sake, bow to me.")),
                  defeat("tournament_champion", 1, "FormationArray", "Defeat the tournament champion",
                         (N, "Yan Tie bows, and when he straightens, his eyes are the colour of blood. Veins crawl black up his neck."),
                         (MO, "Frenzy qi! Stop the bout... no, he won't stop now. {player}, bring him down without killing him!"),
                         (P, "I'll try. Stay back, everyone!")),
                  talk(YUN, "Receive the Sect Master's judgement",
                       (YUN, "Yan Tie will live. Elder Hua's antidote reached him in time. You fought to save him, not to win. I saw that."),
                       (YUN, "The victory is yours, and with it, a place at my side. But someone fed him that pill."),
                       (YUN, "Wait. The pagoda bell... someone is ringing the pagoda bell. Where is Han Xue?")),
              ], xp=500, items={"spirit_stone": 8}),
        # ---------------------------------------------------------------- q050
        quest("The Law Hall's Shadow",
              "While the whole sect watched the final, someone broke into the scripture pagoda.",
              "sect", [
                  reach("Pavilion", "Find Han Xue",
                        (HAN, "{player}! Elder Bai's been hurt. It's Gu. Gu is in the pagoda. The seal diagram, he's taking the seal diagram!"),
                        (P, "Stay here. I'll stop him.")),
                  cinematic("ch05_traitor", "Confront the traitor"),
                  defeat("demon_cultivator", 4, "Pagoda", "Defeat the traitor's Blood Moon accomplices",
                         (GU, "Hold them. The pendant can wait. The diagram cannot.")),
                  talk(BAI, "Check on the wounded Elder Bai on the plaza",
                       (BAI, "I'm fine. I've been hit harder by falling bookshelves. Gu Hanshan... forty years we've shared tea."),
                       (BAI, "He took the Azure Heaven Seal diagram. The master copy. The one we would need to repair the seal."),
                       (BAI, "Without it, if the seal breaks, we cannot remake it. Go to the Sect Master. Quickly."), at="FormationArray"),
                  talk(YUN, "Report to the Sect Master at the teleport array",
                       (YUN, "He fled through the teleport array. Its last destination was the Blood Moon Abyss."),
                       (YUN, "Forty years I trusted him with our law. I trusted him with our children."),
                       (YUN, "Rest tonight, {player}. Tomorrow we go into the Abyss after him."), at="TeleportArray"),
              ], xp=500, items={"spirit_stone": 5, "medicine": 2}),
    ])
