from .dsl import P, N, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *

CHAPTER = chapter(
    9, "The Heart Demon",
    "On the eve of lighting the Great Azure Formation, a letter from the traitor lures you to the Heart Mirror, where you must "
    "defeat your own shadow. You return to a burning sky, and Elder Mo pays the price for the sect's trust. "
    "Now you know what the Patriarch truly wants: you.",
    "ch09_intro", "sect",
    [
        # ---------------------------------------------------------------- q081
        quest("The Great Azure Formation",
              "The Great Azure Formation is nearly complete. Elder Mo has been checking its runes for three nights without sleep.",
              "sect", [
                  cinematic("ch09_intro", "Watch Elder Mo inspect the Great Azure Formation"),
                  interact("seal", "FormationArray", "Inspect the Great Azure Formation",
                           (N, "Ten thousand runes glow a calm blue. Only in the outer ring, one branch seems to twist, like a signature written backwards.")),
                  talk(MO, "Speak with Elder Mo at the hall steps",
                       (MO, "Three nights, ten thousand runes. My eyes feel like two boiled dumplings. Don't tell Wei Tong I said that."),
                       (MO, "I found something. A turn in the outer ring that shouldn't be there. I need one more night to be certain."),
                       (MO, "Here. My old sword tassel. My master gave it to me when I formed my core. It's yours now."),
                       (P, "Elder, why give it to me now?"),
                       (MO, "Because I'm old, and I forget things. Better to give it too early than too late. Go on, {junior}.")),
                  talk(WEI, "Spend an evening with Wei Tong",
                       (WEI, "You're back! You're taller. Are you taller? Nascent Soul makes people taller, I read it somewhere. Maybe."),
                       (WEI, "Elder Mo's been in a strange mood. Keeps patting my shoulder. He gave me his tea set. His good tea set."),
                       (WEI, "Old men do that before long journeys. He's not going anywhere, is he?")),
              ], xp=900),
        # ---------------------------------------------------------------- q082
        quest("A Letter from the Abyss",
              "A crow has brought a letter to the sect gate, addressed to you, in the traitor's hand.",
              "sect", [
                  talk(LU, "Collect the letter from Lu Ping",
                       (LU, "A crow brought this. A crow! It bit me. Twice. It had opinions."),
                       (LU, "It's addressed to you. The seal is the Law Hall's. I thought about burning it. Then I thought, you'd want to know.")),
                  interact("seal", "SectGate", "Break the Law Hall seal on the letter",
                           (N, "Come to the Heart Mirror, alone. I will tell you how to save your sect. Bring anyone, and I will tell you nothing. Gu Hanshan.")),
                  talk(HAN, "Show the letter to Han Xue",
                       (HAN, "It's a trap. Obviously. Everything Gu does is a trap wrapped in a lesson."),
                       (P, "But if he knows something about the formation... Elder Mo found a flaw. I can't ignore this."),
                       (HAN, "I know. That's what worries me. Go. If you're not back by dawn, I'm telling Elder Mo, and then I'm coming to drag you home.")),
              ], xp=800),
        # ---------------------------------------------------------------- q083
        quest("The Mirror Pool",
              "Gu Hanshan waits in the depths of the Blood Moon Abyss, alone and unarmed.",
              "blood_abyss", [
                  defeat("corrupted_wolf", 3, "BoneField", "Slip past the scavengers on the field of bones"),
                  talk(GU, "Hear the traitor out in the abyss depths",
                       (GU, "You came alone. Good. Then listen, because there is no time. The formation your sect built is a key, not a lock."),
                       (GU, "Twenty years ago I altered the archive copy. Seven runes. When it is lit, it will pour the sect's qi into the Abyss and break the seal from above."),
                       (GU, "I did it for Lan. The Patriarch swore he held her soul. He did. He fed it to the Heart Mirror long ago. I heard her screaming there."),
                       (GU, "I cannot face the mirror. It shows me what I am. You can. Free her. Then run home before they light it."), at="AbyssDepths"),
                  reach("HeartMirror", "Approach the Heart Mirror",
                        (N, "A pool of black water, perfectly still. Your reflection looks back at you. Then it smiles, a moment before you do.")),
              ], xp=900),
        # ---------------------------------------------------------------- q084
        quest("The Heart Demon",
              "The mirror has let something out. It wears your face and knows all your fears.",
              "blood_abyss", [
                  cinematic("ch09_mirror", "Face the reflection in the Heart Mirror"),
                  defeat("heart_demon", 1, "HeartMirror", "Defeat your heart demon",
                         (DEMON, "You were never chosen, {player}. You were only unlucky enough to be born holding the key."),
                         (DEMON, "Everyone you love will die because of that pendant. Mo. Han Xue. That silly girl by the pond. Give it to me."),
                         (P, "You're not me. You're only the part of me that's afraid."),
                         (DEMON, "Then why are your hands shaking?")),
                  meditate("HeartMirror", 8, "Still the mirror and free the trapped souls",
                           (N, "You sit at the water's edge. Your hands stop shaking. The mirror ripples, and light rises from it like fireflies."),
                           (N, "Hundreds of souls, drifting upward. One stops in front of you: a girl with Gu's eyes, who bows once, and is gone.")),
                  talk(GU, "Return to Gu Hanshan",
                       (GU, "I saw her. She bowed to you. She always had better manners than her father."),
                       (GU, "Go. Now. The formation... I can feel it waking even from here. Run, {player}, run!"), at="AbyssDepths"),
              ], xp=1500, items={"spirit_stone": 8}),
        # ---------------------------------------------------------------- q085
        quest("Burning Sky over Azure Cloud",
              "The sky above the sect has turned red. The Great Azure Formation has been lit.",
              "sect", [
                  reach("SectGate", "Race back to the sect gate",
                        (LU, "{player}! The formation lit itself at midnight. Blood Moon disciples came out of nowhere, in our robes!"),
                        (LU, "Elder Mo went into the array. He told everyone to stay back. The light's gone red. It's gone all red!")),
                  defeat("blood_guard", 5, "SectGate", "Cut through the infiltrators at the gate"),
                  defeat("demon_cultivator", 4, "FormationArray", "Clear the demonic cultivators guarding the array",
                         (HAN, "They're protecting the array! They want it to keep burning. {player}, get to Elder Mo!")),
              ], xp=1200, items={"medicine": 3}),
        # ---------------------------------------------------------------- q086
        quest("Elder Mo's Choice",
              "At the heart of the burning formation, Elder Mo makes his last decision.",
              "sect", [
                  cinematic("ch09_sacrifice", "Witness Elder Mo's last stand"),
                  talk(YUN, "Stand with the Sect Master at the hall steps",
                       (YUN, "He poured his whole life into the array's eye and turned the flow back. Seventy years of cultivation, in one breath."),
                       (YUN, "The seal holds. The sect lives. And Mo Changfeng is gone."),
                       (YUN, "He asked me to tell you something. He said, adequate. More than adequate."), at="HallSteps"),
                  talk(WEI, "Find Wei Tong",
                       (WEI, "He gave me his tea set. I thought he was being nice. He was saying goodbye, and I didn't even notice."),
                       (WEI, "I was going to make him dumplings. Proper ones, for his birthday. I've been practising for a month."),
                       (P, "Make them anyway, Senior Brother. We'll eat them for him.")),
              ], xp=1200),
        # ---------------------------------------------------------------- q087
        quest("Ashes and Incense",
              "The sect mourns Elder Mo Changfeng.",
              "sect", [
                  interact("bronze_bell", "MainHall", "Toll the great bell nine times",
                           (N, "Nine strokes. Across the mountain, every disciple stops what they are doing and bows toward the hall.")),
                  talk(HUA, "Speak with Elder Hua",
                       (HUA, "I've mended a thousand broken bones for that stubborn old man. He never once said thank you."),
                       (HUA, "He'd leave peaches on my doorstep instead. Every autumn, for forty years. I'll miss the peaches.")),
                  talk(MAN, "Speak with Xiao Man at the lotus pond",
                       (MAN, "I brought plum blossoms. Elder Mo pretended he didn't like flowers, but he always smelled them when he thought no one was looking."),
                       (MAN, "Are you all right? You don't have to be. My brother says being all right is overrated.")),
                  meditate("CliffEdge", 10, "Remember Elder Mo at the cliff edge",
                           (N, "The sea of clouds, where you first condensed your qi. Elder Mo's tassel flutters in your hand."),
                           (N, "Back straight. A crooked spine makes a crooked meridian. You straighten your back, and weep, and breathe.")),
              ], xp=1000),
        # ---------------------------------------------------------------- q088
        quest("What the Patriarch Wants",
              "With the altered formation in pieces, Elder Bai can finally read what it was meant to do.",
              "sect", [
                  talk(BAI, "Hear Elder Bai's findings",
                       (BAI, "I've read the seven altered runes. The formation would open the Abyss upward, like a stairwell, for one soul to climb."),
                       (BAI, "The Patriarch cannot survive the heavenly tribulation in his own body. Too much blood, too much sin. Heaven would erase him."),
                       (BAI, "He needs a body with a clean dao and the Verdant Lotus in its veins. The mirror was meant to crack your heart so he could step in."),
                       (P, "He wants to wear me. To ascend in my skin.")),
                  interact("jade_slip", "Pagoda", "Compare the altered runes with the Heart Sutra",
                           (N, "Laid beside the Heart Sutra, the seven altered runes are plain as day: a lotus drawn upside down, a door drawn inside out.")),
                  talk(GU, "Face Gu Hanshan in chains at the moon gate",
                       (GU, "I surrendered at your gate an hour after you left the mirror. The Sect Master says my fate is yours to decide."),
                       (GU, "Execute me. It's what the precepts demand. I wrote half of them."),
                       (P, "No. Come with us to the Abyss. Fight as an elder of the Azure Cloud. If you must die, die as one."),
                       (GU, "...Mo would have said the same. Very well. I will show you the way through the black gate."), at="MoonGate"),
              ], xp=1100),
        # ---------------------------------------------------------------- q089
        quest("The Five Oaths",
              "Before the final assault, gather your allies and hear their oaths.",
              "sect", [
                  talk(ZHAO, "Hear Zhao Kang's oath",
                       (ZHAO, "The Zhao clan sent me a letter telling me to come home where it's safe. I used it to light incense for Elder Mo."),
                       (ZHAO, "I swear on my brother's name, I'll be at your side at the black gate. Try not to steal all the glory.")),
                  talk(SHI, "Hear Xiao Shi's oath",
                       (SHI, "I can't fight like you. But I know the Abyss. I was there for weeks. I'll draw every path I remember."),
                       (SHI, "Man Man is making medicine bundles. Hundreds of them. She's only dropped a few.")),
                  talk(QIAN, "Hear Steward Qian's oath",
                       (QIAN, "The treasury is open. All of it. Take whatever you need. Spirit stones are useless to the dead."),
                       (QIAN, "I have counted every stone in this sect for thirty years. Tonight I will count nothing. Just come back.")),
                  collect("medicine", 4, "LotusPond", "Collect Xiao Man's medicine bundles for the army"),
                  talk(YE, "Meet Ye Wuming at the sect gate",
                       (YE, "The blood moon rises in three days. On that night the Patriarch will break free with or without your formation."),
                       (YE, "The children you let me take are with me. And Iron-Fang, with his men. We will open the way."),
                       (YE, "I owe you a name, {player}. I intend to pay."), at="SectGate"),
              ], xp=1000, items={"spirit_stone": 10}),
        # ---------------------------------------------------------------- q090
        quest("Soul Transformation",
              "The Great Azure Formation has been repaired, its seven runes turned true. Use its power to transform your soul.",
              "sect", [
                  collect("spirit_stone", 6, "FormationArray", "Set spirit stones into the repaired formation"),
                  meditate("FormationArray", 12, "Transform your soul at the heart of the formation",
                           (N, "Where Elder Mo gave his life, you sit. The formation rises around you, blue and clean. It feels like being held."),
                           (N, "Your nascent soul grows, merges with your body, and the boundary between you and heaven and earth thins like mist."),
                           (P, "Thank you, Elder Mo. I'll carry it from here.")),
                  talk(YUN, "Receive the Sect Master's blessing",
                       (YUN, "Soul Transformation. Heaven itself will notice you now. So will the Patriarch."),
                       (YUN, "In three days we march on the Abyss, every disciple who can hold a sword. We end this, as our founders could not."),
                       (YUN, "Mo believed in you before any of us. Let's prove him right, {player}.")),
              ], xp=2000, items={"spirit_stone": 10}, realm="Soul Transformation"),
    ])
