from .dsl import P, N, added, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *
from .saga_gen import B, C

CHAPTER = chapter(
    3, "Shadows over Qingshi",
    "Mortals vanish from Qingshi Town every new moon. With Senior Sister Han Xue, you follow a trail of "
    "gossip, blood lotus and graveyard runes to a kindly temple keeper who is neither kindly nor a keeper.",
    "ch03_intro", "qingshi_town",
    [
        # ---------------------------------------------------------------- q021
        quest("The Town That Whispers",
              "The Sect Master sends you and Han Xue to Qingshi Town, where the freed captives say people vanish every new moon.",
              "sect", [
                  talk(YUN, "Receive the Sect Master's orders",
                       (YUN, "The captives you freed are from Qingshi. They say someone takes people every new moon, and nobody stops it."),
                       (YUN, "The Law Hall is investigating the token. I want eyes in the town. Han Xue will go with you."),
                       (YUN, "Mortals are not our subjects, {player}. They are our reason. Remember that.")),
                  cinematic("ch03_intro", "Watch your arrival at Qingshi Town"),
                  talk(DU, "Speak with the constable at the town gate",
                       (DU, "Cultivators. Finally. I sent three petitions to the yamen and two to the gods. You're the first to answer."),
                       (DU, "Eleven people in four months. Farmers, a fisherman's boy, a young man from your sect visiting his mother."),
                       (HAN, "From our sect?"),
                       (DU, "Said his name was Xiao Shi. Asked too many questions. Then one morning he didn't come back from the river.")),
              ], xp=180),
        # ---------------------------------------------------------------- q022
        quest("The Drunken Crane",
              "Every rumour in Qingshi passes through the Drunken Crane Inn. Then pay your respects to the magistrate.",
              "qingshi_town", [
                  reach("MainStreet", "Walk the main street of Qingshi",
                        (N, "Shutters close as you pass. A mother pulls her son indoors. The town looks at your sect robes like a sick man at a doctor."),
                        (HAN, "They're afraid. Not of us. Of whatever makes people disappear.")),
                  talk(FANG, "Ask Madam Fang for gossip at the inn",
                       (FANG, "Immortals in my inn! Sit, sit. Wine is ten coppers, noodles are five, gossip is free but you must tip."),
                       (FANG, "People vanish at the new moon, yes. And the temple keeper buries whoever the river gives back."),
                       (FANG, "Poor Keeper Hong. Such a gentle old man. He cries at every funeral, even the dogs'."),
                       (P, "The river gives some of them back?"),
                       (FANG, "Only bits, dear. Only bits. More wine?")),
                  talk(ZHOU, "Pay respects to Magistrate Zhou",
                       (ZHOU, "Ah, the immortals. Welcome, welcome. As you can see, the yamen has matters entirely in hand."),
                       (ZHOU, "People wander off. Mortals are like that. Gambling, debts, pretty widows in other towns."),
                       (HAN, "Eleven of them, Magistrate?"),
                       (ZHOU, "A rounded number! Bring me proof, and the yamen will act. Until then, please don't frighten the tax base.")),
              ], xp=160),
        # ---------------------------------------------------------------- q023
        quest("A Mother's Grief",
              "A widow at the town well lost her son to the new moon. The ferryman may have seen something on the river.",
              "qingshi_town", [
                  talk(LIU, "Comfort the widow at the well",
                       (LIU, "My Liu Er went to fetch the nets at dusk. The river was calm. He swam like a fish, my boy."),
                       (LIU, "They say he drowned. His body never came back. The river gives back everyone eventually."),
                       (P, "I'll find out what happened to him. I promise."),
                       (LIU, "Don't promise, young immortal. Promises are heavy. Just look. That's enough."),
                       added(HAN, "Then we'll look, Madam Liu. Both of us. Very carefully.")),
                  talk(PAN, "Question the old ferryman at the docks",
                       (PAN, "Seen something? Forty years on this water, I've seen everything twice."),
                       (PAN, "New moon, two months back. Lanterns moving on the far bank, toward the hill graves. Pale folk, carrying sacks."),
                       (PAN, "Sacks that wriggled. I told the magistrate. He told me to drink less. I drink exactly the right amount.")),
                  reach("Riverside", "Search the river bank",
                        (N, "Among the reeds: a broken sandal, a torn net, and footprints leading uphill, pressed deep, as if carrying weight."),
                        (HAN, "Five people. One dragged. Toward the graveyard.")),
                  interact("seal", "Well", "Test the well water for blood qi",
                           (N, "The well water is clean. Whatever took the townsfolk did not poison them. It wanted them healthy."),
                           (HAN, "Healthy blood. That's worse, somehow.")),
              ], xp=170, items={"spirit_herb": 2}),
        # ---------------------------------------------------------------- q024
        quest("Market of Rumours",
              "Blood lotus is a demonic herb, yet someone in Qingshi is buying it by the crate. Follow the money.",
              "qingshi_town", [
                  reach("MarketSquare", "Listen to the gossip in the market square",
                        (HAN, "Smell that? Beneath the fried dough. Blood lotus. It's used in demonic pills."),
                        (P, "It's coming from the guild carts. They're heading to the warehouse.")),
                  talk(JIN, "Question Merchant Jin at the warehouse",
                       (JIN, "Jin Baoshan, master of the merchant guild. What an honour. Buying? Selling? Leaving?"),
                       (JIN, "Blood lotus? Never heard of it. Is it a flower? We deal in silk, tea and entirely legal things."),
                       (HAN, "Your crates are dripping red, Master Jin."),
                       (JIN, "Imported beets. Very juicy. Now, if you'll excuse me, I have a pressing appointment elsewhere. Anywhere.")),
                  interact("treasure_chest", "Warehouse", "Search the guild's crates",
                           (N, "Under the silk bolts: dried blood lotus, bundled by the dozen, and a ledger."),
                           (N, "Every entry is paid in silver by a buyer who signs with a crescent moon. Deliveries: the hill graves, at the new moon."),
                           (P, "The graveyard again. Jin knows exactly who he's selling to.")),
              ], xp=190, items={"blood_lotus": 1}),
        # ---------------------------------------------------------------- q025
        quest("The Back Alley",
              "A scream in the night. Somebody is being taken right now.",
              "qingshi_town", [
                  reach("BackAlley", "Follow the scream into the back alley",
                        (N, "Masked figures in black and crimson drag a struggling woman toward the town wall."),
                        (HAN, "Demonic cultivators. Inside the town walls. {player}, left side. I'll take the right.")),
                  defeat("demon_cultivator", 3, "BackAlley", "Rescue the woman from the demonic cultivators"),
                  collect("rune_fragment", 2, "BackAlley", "Pick up the talismans the attackers dropped"),
                  reach("MainStreet", "Regroup with Han Xue on the main street",
                       (HAN, "Sleep talismans. Blood-ink. These people know the town, the patrols, even which windows don't lock."),
                       (HAN, "And I saw someone on the rooftops, watching. A masked man. He didn't help. He didn't run either."),
                       (P, "I've met him. In the bamboo forest. He warned me about the Blood Moon."),
                       (HAN, "A man who knows that much about demons... either hunts them, or is one."),
                       added(DU, "Cultivators! The woman is home, shaking but whole. I'm doubling the night watch. Tell me what else to do.")),
              ], xp=220, items={"rune_fragment": 1, "medicine": 1}),
        # ---------------------------------------------------------------- q026
        quest("The Masked Stranger",
              "Han Xue suspects the masked wanderer. Madam Fang says a masked guest has been renting her top room.",
              "qingshi_town", [
                  talk(FANG, "Ask Madam Fang about the masked guest",
                       (FANG, "The mask? Pays in old coins, never eats, never drinks, never smiles. My ideal guest, honestly."),
                       (FANG, "He goes up the watchtower every night and stares at the fields. Romantic, or murderous. Could be both.")),
                  reach("WatchTower", "Climb the watchtower",
                        (N, "From the tower, the terraced fields shine under a thin moon. A lone figure stands among the rice, looking up at you."),
                        (HAN, "He knows we're here. He wants us to come.")),
                  talk(YE, "Confront the masked wanderer in the fields",
                       (YE, "You've been talking about me. I'm flattered. Also, you're wrong."),
                       (HAN, "Then explain why you're always near demons."),
                       (YE, "Because I hunt them. I've tracked this nest for a year. Ask who tends the dead in this town."),
                       (P, "The temple keeper? Everyone says he's gentle."),
                       (YE, "Everyone said I was gentle once, too. Look beneath his graves. Then decide who to trust."), at="Farmland"),
              ], xp=190),
        # ---------------------------------------------------------------- q027
        quest("Lanterns Among the Graves",
              "Search the hillside graveyard, where the ledger's deliveries and the ferryman's lanterns both lead.",
              "qingshi_town", [
                  reach("Graveyard", "Search the hillside graveyard at night",
                        (N, "Fresh graves, far too many. Each mound is marked with a neat temple tablet and a sprig of dried blood lotus.")),
                  interact("seal", "Graveyard", "Examine the rune circle beneath the graves",
                           (N, "You brush the soil aside. The graves are empty, and beneath them runs a circle of blood-ink runes."),
                           (HAN, "A blood-gathering formation. Whoever's buried here never died here. They were taken somewhere, alive.")),
                  collect("rune_fragment", 3, "Graveyard", "Gather the blood-ink rune stones as proof"),
                  talk(HAN, "Decide what to do with Han Xue",
                       (HAN, "The tablets are temple tablets. Only Keeper Hong carves these."),
                       (P, "Madam Fang said he cries at every funeral."),
                       (HAN, "Some people cry at funerals because they're sad. Others because they're hungry. Let's pay him a visit."),
                       added(YE, "Visit him in daylight. A man who wears a kind face is weakest when he has to keep smiling."), at="Graveyard"),
              ], xp=210, items={"rune_fragment": 1}),
        # ---------------------------------------------------------------- q028
        quest("The Temple Keeper",
              "Visit Keeper Hong at the town temple, and watch his hands.",
              "qingshi_town", [
                  talk(HONG, "Visit Keeper Hong at the temple",
                       (HONG, "Young immortals! Come in, come in. Tea? It's a special blend. Very calming."),
                       (P, "It smells of blood lotus, Keeper."),
                       added(HAN, "Don't drink it, {player}. Keeper, put the cup down. Slowly."),
                       (HONG, "Does it? Old nose, old tea. Such strong young cultivators. Such... vigorous blood."),
                       (HONG, "And that pendant. Green jade, lotus-carved. Oh, the Patriarch will be so very pleased with me.")),
                  cinematic("ch03_reveal", "Watch the temple keeper reveal himself"),
                  defeat("demon_cultivator", 4, "MainStreet", "Fight through Hong's acolytes on the main street",
                         (HONG, "Hold them, my children! I must prepare the graves!")),
              ], xp=240, items={"spirit_stone": 3}),
        # ---------------------------------------------------------------- q029
        quest("Blood Beneath the Graves",
              "Keeper Hong, a deacon of the Blood Moon, has fled to his blood formation in the graveyard. The magistrate can no longer look away.",
              "qingshi_town", [
                  talk(ZHOU, "Rally the magistrate",
                       (ZHOU, "The temple keeper? I had tea with him every week! He blessed my house! He... he blessed my house."),
                       (ZHOU, "I was a fool and a coward. The yamen guards are yours. Tell me what to do."),
                       added(DU, "Twelve guards, Magistrate. Twelve spears, and one very old drum. We're ready."),
                       (P, "Keep the townsfolk indoors. We'll end this tonight.")),
                  reach("Graveyard", "Storm the graveyard",
                        (N, "The rune circle burns red. Keeper Hong stands at its centre, his kindly face peeling away like wet paper.")),
                  defeat("demon_elder", 1, "Graveyard", "Defeat Deacon Hong of the Blood Moon",
                         (HONG, "Three hundred hearts I have gathered for the Patriarch. Yours will make it three hundred and one."),
                         (P, "Your patriarch is dead."),
                         (HONG, "Dead? Oh, child. He is only hungry.")),
                  talk(HONG, "Follow the dying deacon to his temple",
                       (HONG, "Too late. The taken are already in the Abyss. The Blood Moon Abyss. Their blood drips on the seal as we speak."),
                       (HONG, "You think your sect protects you? The Patriarch has friends in high halls. Very high."),
                       (HONG, "Lotus-bearer... he is coming for you. He has always been coming for you."), at="Temple"),
              ], xp=320, items={"demon_core": 1, "spirit_stone": 4}),
        # ---------------------------------------------------------------- q030
        quest("A Debt of Qingshi",
              "Qingshi is safe for now. Keep your word to the town before you return to the sect.",
              "qingshi_town", [
                  talk(LIU, "Tell Widow Liu the truth",
                       (P, "Your son didn't drown. He was taken. To a place called the Blood Moon Abyss. He may still be alive."),
                       (LIU, "Alive? Don't... don't give me hope unless you mean it, immortal."),
                       added(HAN, "We saw his formation, Madam Liu. They wanted the taken alive. That hope is real."),
                       (P, "I mean it. I'll look for him. For him and for everyone they took."),
                       (LIU, "Then I'll keep the water sweet until you do.")),
                  talk(FANG, "Accept Madam Fang's thanks",
                       (FANG, "The heroes of Qingshi! Free noodles for life. Well, for a year. Well, one bowl. Today. Eat quickly."),
                       (FANG, "Truly, dear. Thank you. That old snake served me tea for ten years. I'll be checking my teeth for a month.")),
                  meditate("Temple", 6, "Cleanse the defiled temple",
                           (N, "You burn clean incense and let your qi wash through the hall. The smell of blood lotus fades, and a sparrow returns to the eaves.")),
                  reach("MainStreet", "Head home with Han Xue",
                       (HAN, "He said the Patriarch has friends in high halls. Very high."),
                       (P, "You think someone in our sect..."),
                       (HAN, "I think we should say it only to the Sect Master. And we should find out where Xiao Shi is before his sister does.")),
              ], xp=240, items={"spirit_stone": 3, "medicine": 2}),
    ])

# The graveyard fire is out, but a town does not heal in one night. Spliced
# in between Hong's defeat and the quiet farewell of "A Debt of Qingshi".
EXTRA = C(
    "Shadows over Qingshi", "qingshi_town",
    "The graveyard fire is out, but Qingshi does not heal in one night: the wounded, the frightened, and the "
    "questions Deacon Hong left unanswered about where the taken were sent.",
    cast=[HAN, ZHOU, DU, FANG, LIU, PAN, JIN],
    foes=["demon_cultivator", "bandit"],
    items=["medicine", "rune_fragment", "spirit_herb"],
    props=["stone_stele", "treasure_chest", "jade_slip"],
    beats=[
        B("rescue", "The Wounded of the Watch",
          "Constable Du's guards took wounds fighting Hong's acolytes. The Medicine Hall's supplies are thin this far from the mountain.",
          (DU, "Three men down, none dying, all complaining. I'll take that trade. Can you spare anything for them?"),
          v=0),
        B("probe", "Hong's Temple, By Daylight",
          "By daylight, the temple looks smaller, sadder, and full of things Keeper Hong never wanted found.",
          (N, "Behind a false wall: robes, a second set of temple seals, and a stack of letters written in a crescent-marked hand."),
          v=0),
        B("gather", "What the Graves Gave Up",
          "The rune circle is broken, but its stones still hum faintly. Han Xue wants every fragment collected and studied.",
          (HAN, "Every piece. Elder Bai will want to compare them to the archive, if the archive still remembers anything useful."),
          v=0),
        B("hunt", "The Last of Hong's Acolytes",
          "A handful of Hong's masked acolytes scattered into the fields rather than fight. They haven't gone far.",
          foe="demon_cultivator", v=0),
        B("social", "Magistrate Zhou's Accounting",
          "Zhou insists on personally accounting for every silver coin Hong ever accepted from the yamen's coffers.",
          (ZHOU, "Every donation, every blessing fee, all of it laundered piety. I should have smelled it. I only smelled the incense."),
          v=0),
        B("social", "The Ferryman's Second Story",
          "Old Pan remembers something else about the lantern-bearers, now that he isn't afraid of being called a drunk.",
          (PAN, "There was a barge, once. Heavier than it looked, riding low in the water. I thought it was grain. It wasn't grain."),
          v=0),
        B("probe", "Merchant Jin's Ledger, Fully Open",
          "With Hong exposed, Merchant Jin suddenly remembers every detail of the blood lotus trade, eager to be the first to confess.",
          (JIN, "I kept records! Excellent records! Dates, amounts, a little map. Innocent people keep excellent records, yes?"),
          v=0),
        B("cultivate", "Steadying the Town's Qi",
          "The graveyard's blood formation left the land itself uneasy. Han Xue asks you to help settle it.",
          (HAN, "Land remembers fear the way people do. Sit with it a while. Let it feel something else for a change."),
          v=0),
        B("social", "Widow Liu's Question",
          "Widow Liu asks, carefully, whether the Blood Moon Abyss is a place a person could still be found alive.",
          (LIU, "You said he might be alive. I need to know if that was kindness or truth. I can live with either. I need to know which."),
          v=0),
        B("stage", "What Qingshi Taught You",
          "Before the road home, Han Xue says your qi has changed here, hardened by something more than training.",
          (HAN, "You didn't just get stronger in this town. You got sure of something. That matters more, usually."),
          v=0),
    ])
