from .dsl import P, N, added, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *
from .saga_gen import B, C

CHAPTER = chapter(
    8, "Isles Above the Clouds",
    "The Celestial Sky Isles open once every sixty years. With Han Xue and Zhao Kang you gather star iron, thunder crystals "
    "and phoenix feathers for the Great Azure Formation, face the corrupted Jiao serpent, and hear a star-gazer doubt the sect's design.",
    "ch08_intro", "sky_isles",
    [
        # ---------------------------------------------------------------- q071
        quest("Stairway of Clouds",
              "The Sky Isles have opened. The Sect Master sends you, Han Xue and Zhao Kang to gather materials for the Great Azure Formation.",
              "sect", [
                  talk(YUN, "Receive the Sect Master's orders",
                       (YUN, "Elder Bai has rebuilt the formation design from the Law Hall archive copy. Elder Mo will build it. You will supply it."),
                       (YUN, "Five star iron, five thunder crystals, three phoenix feathers. The isles close again at the next full moon."),
                       (YUN, "Take Han Xue and Zhao Kang. And {player}? Look at the sky while you're up there. It's good for the soul.")),
                  cinematic("ch08_intro", "Ascend to the Celestial Sky Isles"),
                  talk(SAGE, "Meet the star-gazer at the cloud gate",
                       (SAGE, "Visitors. Sixty years, and they still come puffing up the stairs like it's a surprise."),
                       (SAGE, "I am Qing Luan. I was a sage of these isles, once. Now I'm mostly a very persistent memory."),
                       (SAGE, "The isles test those who cross. Your heart must be clear, your sword sharp, and your shoes sturdy."),
                       (SAGE, "Two out of three is usually fine. Go on, lotus child. I'll be in my pavilion, watching."),
                       added(ZHAO, "A persistent memory? Is she a ghost? {player}, is she a ghost? Nobody said ghosts."),
                       added(HAN, "Bow to the sage, Zhao Kang."),
                       added(P, "Thank you, Sage. We'll keep our shoes sturdy."), at="CloudGate"),
              ], xp=700),
        # ---------------------------------------------------------------- q072
        quest("The Jade Bridge",
              "Cross the long jade bridge to the second isle. The winds are strong, and you are not alone.",
              "sky_isles", [
                  reach("JadeBridge", "Cross the jade bridge",
                        (ZHAO, "It's very high. Isn't it very high? Why is there no railing? Who builds a bridge with no railing?"),
                        (HAN, "Immortals who can fly, Zhao Kang."),
                        (ZHAO, "Well, that's elitist."),
                        added(P, "Keep walking, Zhao Kang. And don't look down.")),
                  defeat("demon_cultivator", 3, "JadeBridge", "Fight off the Blood Moon pursuers on the bridge",
                         (HAN, "Blood Moon! They followed us through the array. Gu must have told them where we were going.")),
                  reach("IsleOfWinds", "Catch your breath with Han Xue",
                       (HAN, "Why follow us here? What do demons want with the materials for a sealing formation?"),
                       (P, "To stop us building it?"),
                       (HAN, "Then why did they only watch us, and not attack until we reached the bridge? Something is wrong. I don't know what yet.")),
              ], xp=720, items={"spirit_stone": 5}),
        # ---------------------------------------------------------------- q073
        quest("Isle of Winds",
              "The wind-swept isle is thick with cloud silk, and thick with sword intent for those who can listen.",
              "sky_isles", [
                  collect("cloud_silk", 5, "IsleOfWinds", "Gather cloud silk from the wind-swept pines"),
                  meditate("IsleOfWinds", 8, "Listen to the wind",
                           (N, "The wind has no shape, and so nothing can break it. It bends around every obstacle and arrives anyway.")),
                  talk(ZHAO, "Talk with Zhao Kang among the pines",
                       (ZHAO, "I've been thinking. It happens occasionally. I've been an insufferable brat to you for two years."),
                       (ZHAO, "My brother would have liked you. He always said pride is a wall you build to keep yourself small."),
                       (ZHAO, "So. I'm sorry. There. Never tell anyone. I'll deny it with my last breath."),
                       (P, "Apology accepted, Zhao Kang. Friend."),
                       added(HAN, "I heard all of that, Zhao Kang. I'm telling no one. I'm writing it down."), at="IsleOfWinds"),
              ], xp=720, items={"cloud_silk": 2}),
        # ---------------------------------------------------------------- q074
        quest("The Star-Gazer's Riddle",
              "Qing Luan will point you to the star iron, if you can answer her riddle. And read her chart. And listen to her complain.",
              "sky_isles", [
                  talk(SAGE, "Visit Qing Luan at the star pavilion",
                       (SAGE, "A riddle! I've waited sixty years to ask someone. What climbs higher the more you take away?"),
                       (P, "A hole? No... a debt? Wait. A cultivator. The more attachments we let go, the higher we rise."),
                       (SAGE, "Wrong, but I like your answer better than mine. It was a staircase with the bottom steps removed. Read my chart."),
                       added(ZHAO, "A staircase? That's not a riddle. That's carpentry.")),
                  interact("jade_slip", "StarPavilion", "Study the star chart",
                           (N, "Constellations drift across the jade. The star iron fell with the palace. The thunder grows where the vein runs."),
                           (N, "In the chart's corner, a seven-star pattern glows red. It is labelled: the Patriarch's Ladder.")),
                  talk(SAGE, "Ask Qing Luan about the red stars",
                       (SAGE, "Three hundred years ago a man called Xue Wuji came here. Very charming. He wanted the Ascension Stair."),
                       (SAGE, "He meant to ride the heavenly tribulation into the heavens and take them. Your founders stopped him, barely."),
                       (SAGE, "The star iron lies in the fallen palace. Watch out for the guardians. They're rude.")),
              ], xp=700),
        # ---------------------------------------------------------------- q075
        quest("Star Iron of the Fallen Palace",
              "The celestial palace fell ten thousand years ago. Its guardians did not get the message.",
              "sky_isles", [
                  reach("CelestialRuins", "Reach the celestial ruins",
                        (N, "Broken columns tower into the clouds. Among them lie lumps of dark metal, still faintly warm from falling out of the sky.")),
                  defeat("stone_golem", 4, "CelestialRuins", "Defeat the palace guardians"),
                  collect("star_iron", 5, "CelestialRuins", "Gather the star iron"),
                  interact("stone_stele", "CelestialRuins", "Read the palace inscription",
                           (N, "Whoever climbs the stair must carry nothing that is not theirs. Not a stolen body. Not a stolen name. Not a stolen heaven."),
                           (HAN, "Stolen body? What kind of warning is that?"),
                           added(ZHAO, "A warning for thieves. The Blood Moon would ignore it on principle."),
                           added(P, "Or for someone who means to steal a body. Remember it.")),
              ], xp=740, items={"star_iron": 1}),
        # ---------------------------------------------------------------- q076
        quest("The Spirit Vein",
              "Thunder crystals grow where the spirit vein breaks the surface. Someone else is already mining them.",
              "sky_isles", [
                  defeat("blood_guard", 4, "SpiritVein", "Drive the Blood Moon miners from the spirit vein",
                         (HAN, "Blood Guards, with picks and sacks. They're mining thunder crystals!")),
                  collect("thunder_crystal", 5, "SpiritVein", "Gather thunder crystals"),
                  interact("spirit_stone", "SpiritVein", "Examine the miners' cache",
                           (N, "Crates of thunder crystals, carefully packed, each stamped with the same seven-star mark as the red stars."),
                           (HAN, "Thunder crystals are only good for one thing: channelling heavenly lightning into a formation."),
                           (P, "Our formation needs them too. Why would the Blood Moon build the same thing we're building?"),
                           added(ZHAO, "Same stamp as the red stars. I don't like coincidences. They're never coincidences.")),
              ], xp=760, items={"thunder_crystal": 1}),
        # ---------------------------------------------------------------- q077
        quest("Garden of Immortals",
              "Phoenix feathers fall in the overgrown garden, where the Jiao serpent hunts.",
              "sky_isles", [
                  reach("ImmortalGarden", "Enter the overgrown garden",
                        (N, "Blossom trees taller than pagodas. Petals fall like warm snow. High in the branches, something golden rustles its wings.")),
                  collect("phoenix_feather", 3, "ImmortalGarden", "Gather phoenix feathers in the immortal garden"),
                  talk(SAGE, "Heed Qing Luan in the garden",
                       (SAGE, "You have the feathers. Good. Now you have a problem. The Jiao smelled them. It smells everything."),
                       (SAGE, "It was a noble beast, guardian of these isles for a thousand years. Then the Blood Moon fed it their blood."),
                       (SAGE, "It is suffering. It will kill you because it is suffering. Please free it."),
                       added(HAN, "Free it, not kill it. That's harder, Sage."),
                       added(P, "Then we do the harder thing."), at="ImmortalGarden"),
              ], xp=700),
        # ---------------------------------------------------------------- q078
        quest("The Jiao's Lair",
              "The corrupted flood dragon will not let you leave the isles alive. Face it in its lair.",
              "sky_isles", [
                  reach("SerpentLair", "Enter the serpent's lair",
                        (N, "The isle shudders. Scales the colour of storm clouds slide past, and a head the size of a house rises over the edge."),
                        (ZHAO, "Nobody told me the serpent was THAT big."),
                        (HAN, "Everyone told you, Zhao Kang."),
                        added(P, "Stay behind me, both of you. It's hurting, not hunting.")),
                  defeat("jiao_serpent", 1, "SerpentLair", "Defeat the corrupted Jiao serpent",
                         (SAGE, "Its heart is still in there, lotus child. Strike the blood from it, not the life!"),
                         (P, "I hear you. Hold on, great one. I'll set you free.")),
                  reach("ImmortalGarden", "Tend to your wounds with Han Xue",
                       (HAN, "It looked at you before it sank into the clouds. Not like a beast. Like someone saying thank you."),
                       (HAN, "You're shaking. Sit. That's an order from your senior sister, and I rarely give them."),
                       (P, "You give them constantly."),
                       (HAN, "I rarely give them nicely.")),
              ], xp=1100, items={"spirit_stone": 8}),
        # ---------------------------------------------------------------- q079
        quest("The Stars Disagree",
              "The Jiao left something behind in its lair, and Qing Luan has something to show you before you go.",
              "sky_isles", [
                  interact("treasure_chest", "SerpentLair", "Search the Jiao's hoard",
                           (N, "Among bones and coins lies a heart of star iron the size of a fist, humming with stored lightning."),
                           (N, "Its weight settles into your hands like it has been waiting for you.")),
                  reach("JadeBridge", "Prepare to leave with Zhao Kang",
                       (ZHAO, "Star iron, thunder crystal, phoenix feather, and a dragon heart. We're rich. We're heroes. We're rich heroes."),
                       (ZHAO, "Come on. Wei Tong promised a banquet. I'm told he's been practising dumplings for a month.")),
                  talk(SAGE, "Say farewell to Qing Luan",
                       (SAGE, "Show me the design your sect intends to build. Hm. Hmm. The stars disagree with it."),
                       (SAGE, "Here, where it should turn inward, it turns outward. As if it were meant to open rather than close."),
                       added(HAN, "Like a door instead of a lock. {player}, that archive belonged to the Law Hall."),
                       (P, "It was rebuilt from the sect's Law Hall archive."),
                       (SAGE, "Then ask who kept the archive. Go carefully, lotus child. Heaven is watching you now.")),
              ], xp=800, items={"star_iron": 1}),
        # ---------------------------------------------------------------- q080
        quest("Nascent Soul",
              "The winds of the isles have tempered you. At the cloud gate, give birth to your nascent soul, then bring the materials home.",
              "sky_isles", [
                  meditate("CloudGate", 12, "Form your nascent soul at the cloud gate",
                           (N, "Your golden core cracks, and from it unfolds a tiny figure of light, cross-legged, with your face and a lotus in its hands."),
                           (N, "It opens its eyes. For the first time, you see the world twice: with your eyes, and with your soul."),
                           (P, "Nascent Soul. Even the clouds look different. They look like they're breathing.")),
                  talk(MO, "Deliver the materials to Elder Mo at the formation array",
                       (MO, "Star iron. Thunder crystal. Phoenix feathers. And a dragon's heart, you show-off. The formation will be finished in a week."),
                       (P, "Elder, the star-gazer said the design is wrong. That it opens instead of closing. It was taken from the Law Hall archive."),
                       (MO, "Bai checked it against the archive copy, sealed and certified. The Law Hall... hm. Gu kept that archive for thirty years."),
                       added(BAI, "Certified by me. But I only checked the copy against itself, Mo. A forger's favourite kind of scholar."),
                       (MO, "Leave it with me. I'll check every rune myself. Go, see the Sect Master. You've earned your cake."), at="FormationArray", map="sect"),
                  talk(YUN, "Report to the Sect Master",
                       (YUN, "A nascent soul at your age. The elders are furious with envy. It's wonderful."),
                       (YUN, "Elder Mo told me about the design. He is checking it himself. If anyone can find a hidden flaw, it is him."),
                       (YUN, "Rest, {player}. For the first time in months, I think the sect can breathe.")),
              ], xp=1500, items={"spirit_stone": 10}, realm="Nascent Soul"),
    ])

# Qing Luan's warning about the formation's design lingers as you finish
# gathering what the isles have to give. Spliced in between "The Stars
# Disagree" and "Nascent Soul".
EXTRA = C(
    "Isles Above the Clouds", "sky_isles",
    "Qing Luan's warning about the formation's backward design lingers as the last materials are gathered and the "
    "isles begin, slowly, to close for another sixty years.",
    cast=[SAGE, HAN, ZHAO],
    foes=["stone_golem", "blood_guard"],
    items=["star_iron", "thunder_crystal", "cloud_silk"],
    props=["stone_stele", "spirit_stone"],
    beats=[
        B("gather", "One More Load of Star Iron",
          "The formation's frame will need more star iron than first estimated. Elder Bai's second letter says so, apologetically.",
          item="star_iron", v=0),
        B("probe", "Who Kept the Archive",
          "Qing Luan's parting question won't leave Han Xue alone: who kept the Law Hall archive copy all these years?",
          (HAN, "Gu kept it. Thirty years. Plenty of time to change one line and reseal the box."),
          v=0),
        B("hunt", "Guardians Still Angry",
          "A few of the fallen palace's stone guardians remain active, confused by visitors after ten thousand years of solitude.",
          foe="stone_golem", v=0),
        B("social", "Zhao Kang's Sky Habit",
          "Zhao Kang has taken to actually looking at the sky, as the Sect Master suggested, and finds he rather likes it.",
          (ZHAO, "Don't tell anyone. But she was right. It is good for something. I don't know what yet."),
          v=0),
        B("gather", "Thunder Crystals, the Honest Way",
          "With the Blood Moon miners driven off, the spirit vein can be mined properly, without anyone dying for it.",
          item="thunder_crystal", v=0),
        B("hunt", "The Miners' Reinforcements",
          "A second wave of Blood Moon miners arrives, unaware their first attempt already failed.",
          foe="blood_guard", v=0),
        B("probe", "The Ladder in the Chart",
          "Qing Luan's star chart marked a seven-star pattern as 'the Patriarch's Ladder.' Han Xue wants to know what climbs it.",
          (HAN, "A ladder needs someone to climb it. Or something. I don't like either answer."),
          v=0),
        B("social", "Qing Luan's Loneliness",
          "Before you go, Qing Luan admits, in her roundabout way, that visitors are the only thing that makes sixty years bearable.",
          (SAGE, "A memory doesn't get lonely, they say. They're wrong. Come back next time. I'll have new complaints ready."),
          v=0),
        B("gather", "Cloud Silk, One Last Bundle",
          "Elder Hua's request for cloud silk turns out to have been an underestimate. One more bundle won't hurt.",
          item="cloud_silk", v=0),
        B("cultivate", "Breathing at the Cloud Gate",
          "Before attempting the breakthrough, Han Xue insists on one last careful meditation at the cloud gate.",
          (HAN, "Nascent Soul isn't a fight you win. It's a door you open carefully. Sit. Get it right."),
          v=0),
    ])
