from .dsl import P, N, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *
from .saga_gen import B, C

CHAPTER = chapter(
    2, "Whispers in the Bamboo",
    "A routine herb mission into the Whispering Bamboo Forest turns into a hunt for corrupted wolves, "
    "a meeting with a hermit and a masked wanderer, and a bandit camp caging mortals. "
    "In its chest lies a blood-red jade token that should not exist.",
    "ch02_intro", "bamboo_forest",
    [
        # ---------------------------------------------------------------- q011
        quest("Beyond the Mountain Gate",
              "Elder Gu of the Law Hall has assigned you your first mission outside the sect: gather moonshadow grass in the Whispering Bamboo Forest with Wei Tong.",
              "sect", [
                  talk(GU, "Receive your mission from Elder Gu",
                       (GU, "The Medicine Hall needs moonshadow grass. It grows in the Whispering Bamboo, beyond the wolf dens."),
                       (GU, "Wei Tong will go with you. Take the teleport array outside the gate. Be back within three days."),
                       (P, "The wolf dens? After what we saw in the pines?"),
                       (GU, "A cultivator who fears wolves should have stayed a farmer. Go.")),
                  cinematic("ch02_intro", "Watch your arrival in the bamboo forest"),
                  talk(WEI, "Join Wei Tong on the forest path",
                       (WEI, "Smell that? Bamboo shoots. Wild mushrooms. Freedom. I packed twelve buns, in case of emergencies."),
                       (WEI, "Moonshadow grass grows in the sunny grove ahead. We pick it, we go home, nobody gets eaten."),
                       (P, "Why do I feel like you've said that before?"),
                       (WEI, "Because I have. Twice. Once somebody got eaten. Only a little bit, though."), at="ForestPath"),
              ], xp=120),
        # ---------------------------------------------------------------- q012
        quest("Moonshadow Grass",
              "Gather moonshadow grass in the herb grove. Something in the bamboo is watching.",
              "bamboo_forest", [
                  reach("HerbGrove", "Find the sunny herb grove",
                        (WEI, "There! Moonshadow grass. See how it glows? Pick the silver ones. The blue ones make you sneeze for a week.")),
                  collect("spirit_herb", 6, "HerbGrove", "Gather moonshadow grass in the herb grove"),
                  defeat("spirit_wolf", 3, "HerbGrove", "Fight off the spirit wolves",
                         (WEI, "Wolves! In broad daylight? Back to back, {junior}!")),
                  reach("Stream", "Regroup with Wei Tong by the stream",
                       (WEI, "Spirit wolves don't hunt at noon. And they don't hunt cultivators. We taste of pills and bad temper."),
                       (P, "These weren't red-eyed, at least."),
                       (WEI, "Not yet. Something's driving them out of their den. Let's find out what, then eat. Or eat, then find out.")),
              ], xp=130, items={"spirit_herb": 2}),
        # ---------------------------------------------------------------- q013
        quest("Fangs in the Dark",
              "The spirit wolves are fleeing their own den. Find out what drove them out.",
              "bamboo_forest", [
                  reach("WolfDen", "Scout the wolf den",
                        (N, "The hollow reeks of old blood. Bones lie in neat rows, far too neat for wolves."),
                        (N, "On the cave wall, someone has painted a crescent moon swallowing a sword. The paint is still wet."),
                        (WEI, "That's not wolf art. Wolves can't hold brushes. I checked once.")),
                  defeat("corrupted_wolf", 4, "WolfDen", "Slay the corrupted wolves"),
                  collect("wolf_fang", 3, "WolfDen", "Collect fangs from the corrupted wolves"),
                  reach("Clearing", "Show the fangs to Wei Tong in the clearing",
                       (WEI, "The roots are black. Somebody fed these wolves blood, cultivator blood, and on purpose."),
                       (WEI, "Elder Hua can study these. And the den is not empty. Something bigger is still in there.")),
              ], xp=140, items={"wolf_fang": 1}),
        # ---------------------------------------------------------------- q014
        quest("The King of the Den",
              "The wolf king, a spirit beast of great age, has been driven mad by blood qi. End its suffering.",
              "bamboo_forest", [
                  reach("WolfDen", "Return to the wolf den",
                        (N, "A howl shakes the bamboo. Something the size of an ox pads out of the cave, eyes like two red lanterns.")),
                  defeat("wolf_king", 1, "WolfDen", "Defeat the corrupted wolf king",
                         (WEI, "That's the wolf king! Its fur used to be silver... they've turned it into a monster!"),
                         (P, "Then let's give it peace.")),
                  interact("seal", "WolfDen", "Lay the wolf king to rest",
                           (N, "You press a purifying talisman to the great beast's brow. The red drains from its fur, leaving it silver again."),
                           (WEI, "Rest easy, old king. It wasn't your fault.")),
                  talk(YE, "Confront the masked stranger in the clearing",
                       (YE, "Clean work. The wolf king was old when your sect master was a child. It deserved a better death."),
                       (P, "Who are you? Did you do this?"),
                       (YE, "If I had, you would be dead. The wolves were fed blood. Someone is testing an old recipe."),
                       (YE, "Go home, little disciple. Keep that pendant under your robe. There are eyes in this forest older than mine."), at="Clearing"),
              ], xp=220, items={"wolf_fang": 2, "spirit_stone": 2}),
        # ---------------------------------------------------------------- q015
        quest("The Hermit of the Bamboo",
              "The wolf king's claws left Wei Tong with a festering wound. A hermit is said to live in a quiet clearing nearby.",
              "bamboo_forest", [
                  reach("HermitHut", "Carry Wei Tong to the hermit's hut",
                        (WEI, "If I die, tell my mother I died heroically. And tell the kitchen to stop making the bitter melon."),
                        (P, "You're not dying. You're just heavy.")),
                  talk(LAN, "Beg the hermit for help",
                       (LAN, "Wolf king claws. Blood-soaked, too. Put him down on the mat, not on my tea."),
                       (LAN, "The wound drinks qi. It needs water from the spirit spring, drawn by someone with a clean heart."),
                       (P, "I'll go. Where is it?"),
                       (LAN, "Follow the sound of the frogs. They are loud and very proud of it.")),
                  interact("seal", "SpiritSpring", "Draw water from the spirit spring",
                           (N, "The water glows where your gourd touches it. The lotus pads turn slowly toward you, then toward your pendant."),
                           (N, "For a moment the spring shows a reflection that is not yours: a woman in green robes, holding a lotus. Then it is gone.")),
                  collect("spirit_herb", 3, "SpiritSpring", "Pick lotus leaves by the spring for the poultice"),
                  talk(LAN, "Bring the spring water to the hermit",
                       (LAN, "The spring gave you water. It usually just gives people wet boots."),
                       (LAN, "Your friend will live, and complain, which is how you know he is alive."),
                       (LAN, "That jade you carry... no. Old men see ghosts everywhere. Mind the ruins to the north, child. They remember.")),
              ], xp=150, items={"medicine": 2}),
        # ---------------------------------------------------------------- q016
        quest("Smoke on the Ridge",
              "Wei Tong, recovered and ravenous, smells campfire smoke. Someone is camped deep in the forest.",
              "bamboo_forest", [
                  reach("OldBridge", "Meet Wei Tong on the old bridge",
                       (WEI, "I'm alive! And I smell roast pork. Either I've died and gone somewhere nice, or there's a camp nearby."),
                       (WEI, "Bandits, probably. The rogue cultivator kind. Let's take a look from the ridge before we do anything stupid.")),
                  reach("BanditLookout", "Scout the camp from the lookout",
                        (N, "Below: tents, a fire, crates stamped with a merchant guild's seal. And cages. Cages full of mortals."),
                        (WEI, "Those are townsfolk. Look at their clothes. Qingshi, maybe. What do bandits want with farmers?"),
                        (P, "Nothing good. We free them tonight."),
                        (WEI, "Tonight. Right. After dinner. Kidding! Mostly kidding.")),
                  meditate("BanditLookout", 5, "Wait for nightfall and steady your breath",
                           (N, "The fire burns low. The guards trade places. Inside the cages, a child is crying very quietly.")),
              ], xp=140),
        # ---------------------------------------------------------------- q017
        quest("Iron-Fang's Camp",
              "Raid the bandit camp and free the caged mortals.",
              "bamboo_forest", [
                  defeat("bandit", 4, "BanditCamp", "Raid the bandit camp",
                         (TIE, "Sect brats! On your feet, you drunks! Iron-Fang Tie Hu doesn't lose cargo!"),
                         (P, "They're people, not cargo.")),
                  interact("prison_cage", "BanditCamp", "Free the caged mortals",
                           (N, "The lock snaps. The prisoners stumble out, blinking, too frightened to cry."),
                           (N, "An old farmer grips your sleeve. They took us from Qingshi, he whispers. Every new moon, more of us vanish.")),
                  defeat("bandit", 3, "Clearing", "Cover the prisoners' escape",
                         (TIE, "Kill them! The buyer pays for heads, whole or not!")),
                  collect("spirit_stone", 3, "BanditCamp", "Recover the stolen spirit stones"),
              ], xp=200, items={"spirit_stone": 3}),
        # ---------------------------------------------------------------- q018
        quest("The Blood-Red Token",
              "Iron-Fang fled, leaving his strongbox behind. Search it for clues about his mysterious buyer.",
              "bamboo_forest", [
                  interact("treasure_chest", "BanditCamp", "Search the bandit chief's strongbox",
                           (N, "Silver, forged papers, and at the bottom a token of blood-red jade, carved with a moon swallowing a sword."),
                           (N, "It is cold as a corpse. Your pendant flares green, and the token hisses like a burnt insect."),
                           (P, "The same mark as the den. This is no ordinary bandit's loot.")),
                  reach("BanditLookout", "Show the token to Wei Tong",
                       (WEI, "A moon eating a sword. My grandmother used to scare me with that. Be good or the Blood Moon takes you."),
                       (WEI, "The hermit's old. Older than old. If anyone knows what this is, he does.")),
                  talk(LAN, "Ask the hermit about the token",
                       (LAN, "Put that thing down. Not on my tea! Not on anything I love."),
                       (LAN, "That is a Blood Moon Sect command token. Three hundred years ago, one of those could order a city to bleed."),
                       (P, "The Blood Moon Sect was destroyed. Everyone says so."),
                       (LAN, "Everyone says a great many things. The dead are rarely consulted. Take it to your elders. Quickly.")),
              ], xp=180, items={"jade_slip": 1}),
        # ---------------------------------------------------------------- q019
        quest("Ambush at the Old Bridge",
              "Iron-Fang wants his token back, and he has brought friends.",
              "bamboo_forest", [
                  defeat("bandit", 5, "OldBridge", "Survive the ambush on the old bridge",
                         (TIE, "That token isn't yours, brat. Hand it over and I'll leave you both your legs."),
                         (P, "Come and take it, Iron-Fang."),
                         (TIE, "Brave. I like brave. Brave screams louder.")),
                  collect("rune_fragment", 2, "OldBridge", "Search the fallen bandits for clues"),
                  talk(YE, "Speak with the masked wanderer at the stream",
                       (YE, "Iron-Fang ran again. He is a coward with good instincts, which is the most dangerous kind."),
                       (YE, "You found a Blood Moon token. Do you know how many people will kill for that? Now more will."),
                       (P, "Then help me. Tell me what's happening."),
                       (YE, "The Blood Moon rises. That is all you need to know. Tell your sect master, and trust fewer people than you'd like."), at="Stream"),
              ], xp=200, items={"spirit_stone": 2}),
        # ---------------------------------------------------------------- q020
        quest("Report to the Law Hall",
              "Return to the sect with the Blood Moon token and report to the Law Hall.",
              "sect", [
                  reach("SectGate", "Return to the Azure Cloud Sect",
                        (WEI, "Home! I can smell the kitchens from here. Tell Elder Gu about the token, I'll tell the cook about my stomach.")),
                  talk(GU, "Present the token to Elder Gu",
                       (GU, "A Blood Moon command token. Where did a bandit get this?"),
                       (P, "His buyer, I think. They're kidnapping mortals from Qingshi. And a masked man warned us the Blood Moon is rising."),
                       (GU, "Rumours and masks. The Law Hall will take this into custody and investigate. Properly. Hand it over."),
                       (GU, "You did well, disciple. Now forget you ever saw it. That is an order.")),
                  talk(MO, "Tell Elder Mo about the mission",
                       (MO, "Gu took the token? Well, it is his right. The Law Hall handles matters of the demonic path."),
                       (MO, "Still. Kidnapped mortals, fed wolves, command tokens. I don't like the shape of this."),
                       (MO, "I'll speak to the Sect Master. Wei Tong says you carried him on your back. Hmph. Good.")),
              ], xp=160, items={"spirit_stone": 3}),
    ])

# The road home is longer than the road out: freed prisoners to see safe,
# Iron-Fang's leftovers still lurking, and the hermit's warnings to weigh.
# Spliced in between "Ambush at the Old Bridge" and "Report to the Law Hall".
EXTRA = C(
    "Whispers in the Bamboo", "bamboo_forest",
    "The road home from the wolf den: freed prisoners to see safe out of the forest, Iron-Fang's scattered "
    "leftovers, and the hermit's warnings weighed against the mask's.",
    cast=[WEI, LAN, YE, TIE],
    foes=["bandit", "corrupted_wolf"],
    items=["spirit_herb", "medicine", "rune_fragment"],
    props=["stone_stele", "seal"],
    beats=[
        B("rescue", "Seeing the Prisoners Home",
          "The freed mortals from Qingshi are too frightened to travel alone. Someone has to walk them to the forest edge.",
          (WEI, "One foot in front of the other, that's all. Nobody's chasing you now. Well. Probably nobody."),
          v=0),
        B("social", "The Farmer's Thanks",
          "One of the freed farmers presses a keepsake into your hand before the others hurry him along.",
          (N, "It isn't much, he says, pressing a carved wooden bird into your palm. My daughter made it. Find her a name to hate."),
          v=0),
        B("hunt", "Stragglers of the Camp",
          "Not every bandit fled with Iron-Fang. A few stayed behind for the crates nobody carried off.",
          foe="bandit", v=0),
        B("gather", "What the Camp Left Behind",
          "Amid the trampled tents, useful things remain: medicine, rope, a bandit's half-eaten dinner.",
          (WEI, "Waste not. Iron-Fang isn't using it anymore, and my dinner is a distant memory."),
          v=0),
        B("probe", "The Den, One More Time",
          "Wei Tong wants to check the wolf king's den once more, to be sure nothing else was left to fester there.",
          (WEI, "Just a look. In and out. I have said that before and been wrong, but I mean it more this time."),
          v=0),
        B("hunt", "Wolves Still Restless",
          "A few corrupted wolves remain, confused and dangerous without their king to answer to.",
          foe="corrupted_wolf", v=0),
        B("cultivate", "Breath Among the Bamboo",
          "Before the long walk back, Wei Tong insists on a proper rest and a proper breathing exercise.",
          (WEI, "Elder Mo would skin me if I marched you home exhausted. Sit. Breathe. I'll guard, and eat, in that order."),
          v=0),
        B("probe", "The Hermit's Parting Word",
          "Before you leave the forest, the hermit has one more thing to say about the token and the mask.",
          (LAN, "That wanderer isn't lying to you. He also isn't telling you everything. Neither, child, am I."),
          (P, "Will you, one day?"),
          (LAN, "One day. Not today. Today, just walk carefully."),
          v=0),
        B("social", "Wei Tong's Twelfth Bun",
          "Somehow, impossibly, Wei Tong still has one bun left. He shares it, which is how you know it's serious.",
          (WEI, "Last one. I was saving it for an emergency. This feels like the end of an emergency, so: here."),
          v=0),
        B("stage", "The Long Walk Back", "The forest thins toward the road, and your cultivation has thinned with it too, into something steadier.",
          (WEI, "You're breathing different. Deeper. Elder Mo's going to notice and pretend he doesn't care."),
          v=0),
    ])
