from .dsl import P, N, added, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *
from .saga_gen import B, C

CHAPTER = chapter(
    1, "The Outer Disciple",
    "An orphan with a jade pendant climbs nine thousand steps to the Azure Cloud Sect. "
    "Sect rules, sore muscles, a proud rival and a first taste of qi, until red-eyed wolves "
    "prowl the sect wall for the first time in three hundred years.",
    "ch01_intro", "sect",
    [
        # ---------------------------------------------------------------- q001
        quest("The Mountain Gate",
              "You have climbed nine thousand steps to reach the Azure Cloud Sect. Present yourself at the gate and to the Outer Court Elder.",
              "sect", [
                  cinematic("ch01_intro", "Watch the mountain gate open"),
                  talk(LU, "Speak with the gate disciple",
                       (LU, "Halt! State your name and business. And please don't faint, the last three candidates fainted on my boots."),
                       (P, "I am {player}. I have a letter of recommendation from the village of Willow Creek."),
                       (LU, "A letter! Very fancy. Mostly they bring mud and hope. Go on through, Elder Mo is at the hall steps."),
                       (LU, "Tip from your future Senior Brother: bow low, speak little, and never, ever mention his beard.")),
                  reach("HallSteps", "Climb to the main hall",
                        (N, "The main hall rises above a sea of white stone, its double eaves curling like a crane about to fly."),
                        (P, "Nine thousand steps. My legs are crying. But I'm here.")),
                  talk(MO, "Present yourself to Elder Mo",
                       (MO, "Another one. Let me guess. Orphan, no family, dreams of flying on a sword."),
                       (P, "Orphan, yes. The sword can wait. I want to become strong enough to protect people."),
                       (MO, "Hmph. Better answer than most. What is that jade at your belt?"),
                       (P, "My mother's pendant. It's all I have of her."),
                       (MO, "Keep it close, then. Welcome to the Azure Cloud, {junior}. Tomorrow you learn how little you know."),
                       added(WEI, "Welcome, welcome! Don't mind the scowl, new one. It's how Elder Mo says hello."),
                       added(MO, "Wei Tong. Weapon rack. Now. And take the new one's bundle, since you're so welcoming.")),
              ], xp=60, items={"spirit_stone": 1}),
        # ---------------------------------------------------------------- q002
        quest("Rules of the Azure Cloud",
              "Every outer disciple must learn the Nine Precepts of the sect and draw the monthly allowance from the Treasury Steward.",
              "sect", [
                  talk(GU, "Report to Elder Gu of the Law Hall",
                       (GU, "You are the new one. I am Gu Hanshan of the Law Hall. I enforce the precepts. All of them."),
                       (GU, "The Nine Precepts are carved on the stele inside the gate. Learn them. Ignorance is not a defence."),
                       (GU, "And that pendant. Jade draws envy, and envy draws blood. Keep it hidden, disciple."),
                       (P, "Yes, Elder. I will be careful.")),
                  interact("stone_stele", "SectGate", "Read the Nine Precepts",
                           (N, "Do not harm a fellow disciple. Do not steal the sect's treasures. Do not consort with demonic cultivators."),
                           (N, "The last precept is worn smooth by generations of fingers. It reads: guard the seal, even unto death."),
                           (P, "Guard the seal? What seal?")),
                  reach("MainHall", "Bow before the main hall",
                        (N, "Incense smoke curls past the hall doors. Inside, the founder's tablet gleams, and beside it a lotus, carved in faded green.")),
                  talk(QIAN, "Collect your allowance from Steward Qian",
                       (QIAN, "Allowance, allowance. Everyone wants their allowance. Name? Ah, the new one. Three spirit stones."),
                       (QIAN, "Minus one for your robe. Minus one for the robe's laundering. That leaves... hmm, one. Congratulations."),
                       (P, "The robe was already dirty."),
                       (QIAN, "Then it was a very efficient laundering. Next!"),
                       added(LU, "Don't take it to heart. He docked me a stone last month for sneezing on the ledger."),
                       added(QIAN, "It was a very expensive sneeze, Lu Ping.")),
              ], xp=60, items={"spirit_stone": 1}),
        # ---------------------------------------------------------------- q003
        quest("Iron Body, Iron Will",
              "Senior Brother Wei Tong runs the outer disciples' combat drills. Show him you can swing a sword without losing it.",
              "sect", [
                  talk(WEI, "Find Senior Brother Wei at the weapon rack",
                       (WEI, "Ah, fresh meat! No offence. I call everyone fresh meat. I'm usually hungry."),
                       (WEI, "Wei Tong, senior outer disciple. I teach the basics: stance, strike, and not falling over."),
                       (WEI, "The training puppets are enchanted to fight back. Gently. Mostly gently. Break three and we'll talk.")),
                  defeat("training_puppet", 3, "TrainingGround", "Defeat the training puppets",
                         (WEI, "Lead with your feet, not your elbows! Your sword follows your body, {junior}!")),
                  defeat("training_puppet", 2, "TrainingGround", "Face the puppets' second wave",
                         (WEI, "Oh, did I forget to mention? They come back in pairs after the first set. Surprise!")),
                  talk(WEI, "Report back to Wei Tong",
                       (WEI, "Three puppets! Elder Mo owes me a bun. I bet him you'd manage two."),
                       (P, "You bet on me?"),
                       (WEI, "I bet on everyone. It keeps life interesting. Here, take this. Real fighters need real rice."),
                       added(MO, "Three, with a stumble on the second. The bet said clean. I owe you nothing, Wei Tong.")),
              ], xp=80, items={"medicine": 1}),
        # ---------------------------------------------------------------- q004
        quest("A Rival's Sneer",
              "Zhao Kang of the wealthy Zhao clan has decided that you are beneath him. His attendants want to prove it.",
              "sect", [
                  talk(ZHAO, "Answer Zhao Kang's summons in the plum garden",
                       (ZHAO, "So you're the village brat with the letter. The Zhao clan paid a thousand spirit stones for my place here."),
                       (ZHAO, "And you walked in with a scrap of paper and a trinket. The sect has lowered its standards."),
                       (P, "The steps were the same height for both of us."),
                       (ZHAO, "Clever mouth. My attendants will test it. Training ground. Now.")),
                  defeat("sparring_disciple", 2, "TrainingGround", "Defeat Zhao Kang's attendants",
                         (ZHAO, "Don't damage their faces. They're expensive."),
                         (P, "I'll try to be gentle. Mostly gently.")),
                  talk(WEI, "Tell Senior Brother Wei what happened",
                       (WEI, "You slapped the Zhao clan's face on your second day? Ha! I'll have to buy you dumplings."),
                       (WEI, "Careful, though. Zhao Kang's not wicked, just raised on gold and flattery. That kind of pride bruises easily."),
                       (P, "Then maybe it should bruise a little."),
                       added(LU, "Too late. Two of his attendants limped past the gate an hour ago. The whole mountain knows by now.")),
              ], xp=90, items={"spirit_stone": 1}),
        # ---------------------------------------------------------------- q005
        quest("Breath of Heaven and Earth",
              "Inner disciple Han Xue has been asked to teach you the Azure Cloud breathing method, your first step on the path of cultivation.",
              "sect", [
                  talk(HAN, "Meet Senior Sister Han Xue in the pavilion",
                       (HAN, "Elder Mo asked me to teach you to breathe. Apparently you've been doing it wrong your whole life."),
                       (HAN, "Qi flows everywhere. In the wind, the water, the stone. Cultivators learn to draw it in and keep it."),
                       (HAN, "Go to the stone bridge. Water and air meet there, and the qi is gentle. Sit. Listen.")),
                  meditate("StoneBridge", 6, "Meditate on the stone bridge",
                           (N, "Breathe in. The cool of the pond, the scent of lotus. Something bright stirs beneath your navel."),
                           (N, "Your pendant grows warm against your chest, as if it too were breathing.")),
                  talk(HAN, "Return to Han Xue",
                       (HAN, "You felt it? The first time, most people only feel their legs going numb."),
                       (P, "It was like a spark. And my pendant grew warm."),
                       (HAN, "Warm? Hm. Jade doesn't usually do that. Tell no one but the elders, {junior}."),
                       added(MO, "Tell this elder, then. Warm jade. Hmph. Keep breathing, disciple. And keep that pendant close.")),
              ], xp=90, items={"spirit_herb": 1}),
        # ---------------------------------------------------------------- q006
        quest("Herbs of the West Terrace",
              "Elder Hua of the Medicine Hall needs spirit herbs from the terraces, and her apprentice Xiao Man needs rescuing from herself.",
              "sect", [
                  talk(HUA, "Speak with Elder Hua at the herb terraces",
                       (HUA, "You're the new one Han Xue mentioned. Good. My hands are full and my apprentice's hands are... enthusiastic."),
                       (HUA, "Gather five spirit herbs from the terraces. Pull them at the root, gently, the way you'd lift a sleeping child.")),
                  collect("spirit_herb", 5, "HerbGarden", "Gather spirit herbs on the terraces"),
                  talk(MAN, "Find Xiao Man at the lotus pond",
                       (MAN, "Oh no, oh no. Elder Hua's herbs went in the pond. The carp ate two. I think they're enlightened now."),
                       (P, "Don't worry, I picked extra. Here."),
                       (MAN, "You're a lifesaver! I'm Xiao Man. My brother Xiao Shi is an outer disciple too, but he's home in Qingshi."),
                       (MAN, "He promised to write every week. It's been a month. He's probably too busy eating Mother's cooking.")),
                  talk(HUA, "Deliver the herbs to Elder Hua",
                       (HUA, "Five herbs, roots intact, and my apprentice still dry. You have a careful hand."),
                       added(MAN, "I only dropped two in the pond, Elder! The carp only ate one. Well. One and a half."),
                       added(P, "She was very brave about it. The carp were not."),
                       (HUA, "Careful hands make good alchemists and better friends. Take this pill. It will ease your meridians.")),
              ], xp=100, items={"medicine": 2}),
        # ---------------------------------------------------------------- q007
        quest("The Scripture Pagoda",
              "Elder Bai, keeper of the seven-tier scripture library, will lend you a cultivation manual if you help him find some wandering jade slips.",
              "sect", [
                  talk(BAI, "Visit Elder Bai at the scripture pagoda",
                       (BAI, "A visitor! Do you read? Can you read? Do you return things? Two out of three and we'll get along."),
                       (BAI, "I was airing the old jade slips and I dozed off. The mountain wind took three into the plum garden."),
                       (BAI, "Bring them back and I'll lend you the Azure Cloud Breathing Manual. The good edition, with footnotes.")),
                  collect("jade_slip", 3, "PlumGarden", "Recover the jade slips in the plum garden"),
                  interact("jade_slip", "Pavilion", "Peek at the slips in the quiet pavilion",
                           (N, "Most of the slips are breathing exercises. One is a list of Elder Bai's favourite teas, annotated with fierce opinions."),
                           (N, "The last is older, its jade gone milky. It shows two sects' banners side by side: an azure cloud and a green lotus.")),
                  talk(BAI, "Return the jade slips to Elder Bai",
                       (BAI, "All three! And no corners folded. You may live."),
                       (BAI, "This one here is old history. The Verdant Lotus Sect, who stood beside our founder three centuries ago."),
                       (P, "What happened to them?"),
                       (BAI, "They bled so that this land might sleep. Now nobody remembers their name. That is the fate of heroes, mostly."),
                       added(GU, "Old history is best left on the shelf, Bai. The Law Hall keeps its own records of those days."),
                       added(BAI, "The Law Hall keeps them very well hidden, Gu. Mind the stairs on your way out.")),
              ], xp=100, items={"jade_slip": 1}),
        # ---------------------------------------------------------------- q008
        quest("The Formation Array",
              "Elder Mo shows you the great formation array in the plaza, the heart of the sect's defences, and its lamps need oil.",
              "sect", [
                  talk(MO, "Meet Elder Mo at the formation array",
                       (MO, "This array links to a greater one, far below the mountains. It is called the Azure Heaven Seal."),
                       (MO, "What it seals is none of your business yet. What IS your business is that the spirit lamps are dry."),
                       (MO, "Someone overturned the oil cart in the pine woods. Monkeys, the gate disciple claims. Fetch four jars."), at="FormationArray"),
                  collect("lantern_oil", 4, "OuterPines", "Recover the lantern oil in the pine woods"),
                  interact("seal", "FormationArray", "Refill the lamps of the formation array",
                           (N, "As the last lamp flares, the array's runes turn to face you like flowers following the sun."),
                           (N, "Your pendant blazes green. For a heartbeat you hear distant chanting, and something vast beneath the earth turns over in its sleep."),
                           (P, "What... was that?")),
                  talk(GU, "Elder Gu wants a word",
                       (GU, "The array flared. Every rune, all at once. It has not done that in three hundred years."),
                       (GU, "You were standing at its heart. Show me that pendant."),
                       (P, "It's only my mother's jade, Elder."),
                       (GU, "Hm. Yes. A trinket. The array must be aging. Go, disciple, and speak of this to no one."),
                       added(MO, "Aging, Gu? I checked every rune of that array myself, last spring."),
                       added(GU, "Then check them again, Mo. The disciple may go.")),
              ], xp=110, items={"spirit_stone": 2}),
        # ---------------------------------------------------------------- q009
        quest("Red Eyes in the Pines",
              "Something howled beyond the sect wall at dusk. Find out what is prowling the pine woods.",
              "sect", [
                  reach("OuterPines", "Investigate the howling in the pine woods",
                        (N, "Pine needles crunch underfoot. Between the trunks, pairs of eyes glow the colour of fresh blood."),
                        (P, "Spirit wolves? This close to the sect?")),
                  defeat("corrupted_wolf", 2, "OuterPines", "Drive off the red-eyed wolves"),
                  interact("bronze_bell", "SectGate", "Ring the alarm bell at the gate",
                           (N, "The bronze bell booms across the mountain. Lanterns flare to life in every courtyard.")),
                  talk(LU, "Wake the gate disciple",
                       (LU, "Wha... I'm up! I'm up! I was guarding. With my ears. Very closely."),
                       (P, "There were wolves in the pines, Lu Ping. With red eyes."),
                       (LU, "Red eyes? That's an old granny story. Red eyes mean the Blood Moon is... oh. Oh no.")),
                  talk(MO, "Report to Elder Mo",
                       (MO, "Corrupted wolves. Their qi was poisoned with blood. That hasn't happened since the Blood Moon Sect fell."),
                       added(LU, "I rang the bell, Elder! Well. The new one rang it. I supervised, very closely."),
                       added(P, "There were two of them, Elder. Both with eyes like fresh blood."),
                       (MO, "Probably a stray demonic cultivator passing through. Probably. You did well, {junior}. Get some rest.")),
              ], xp=130, items={"wolf_fang": 1}),
        # ---------------------------------------------------------------- q010
        quest("Qi Condensation",
              "Your meridians are ready. With a pill from Elder Hua and the view from the cliff edge, it is time to condense your first qi.",
              "sect", [
                  talk(HUA, "Receive a Qi Gathering Pill from Elder Hua",
                       (HUA, "Elder Mo says you're ready. He said it grumpily, which means he's proud."),
                       (HUA, "This is a Qi Gathering Pill. Swallow it at the cliff edge. The sea of clouds will steady your mind.")),
                  meditate("CliffEdge", 10, "Break through at the cliff edge",
                           (N, "The pill dissolves into fire. Qi floods your meridians like a spring thaw, cold, then burning, then clear."),
                           (N, "The sea of clouds churns below. The scattered spark in your dantian draws tight and becomes a bright, steady pearl of qi."),
                           (P, "So this is Qi Condensation. I can hear the mountain breathing.")),
                  talk(YUN, "Present yourself to the Sect Master",
                       (YUN, "Yun Qingyao. Sect Master of the Azure Cloud. I felt your breakthrough from the hall. It was very... loud."),
                       (YUN, "Elder Mo tells me the formation array answered you, and that wolves with red eyes came to our wall."),
                       (YUN, "Omens come in pairs, they say. I would rather they didn't. Rest well, {player}. Tomorrow the sect needs you."),
                       (P, "I will not disappoint you, Sect Master."),
                       added(MO, "Hmph. A loud breakthrough, but a clean one. Adequate, Sect Master. Adequate.")),
              ], xp=200, items={"spirit_stone": 3}, realm="Qi Condensation"),
    ])

# Ten more days at the sect before the breakthrough: the watch doubled after
# the wolves, Zhao Kang's rematch, and the questions Elder Gu keeps returning
# to. Spliced in between "Red Eyes in the Pines" and "Qi Condensation".
EXTRA = C(
    "The Outer Disciple", "sect",
    "More of the outer disciple's first days: the watch doubled after the wolves, herbs for the infirmary, a rematch "
    "with Zhao Kang, and the questions Elder Gu keeps returning to.",
    cast=[MO, WEI, ZHAO, HAN, HUA, GU, QIAN, LU, MAN],
    foes=["spirit_wolf", "corrupted_wolf", "sparring_disciple"],
    items=["spirit_herb", "spirit_stone", "wolf_fang"],
    props=["stone_stele", "bronze_bell"],
    beats=[
        B("orders", "Watch Doubled at the Wall",
          "After last night's wolves, Elder Mo doubles the watch, and outer disciples pull their share of it.",
          (MO, "Two of you on the wall from dusk to the second bell, from now on. Red eyes don't knock twice before they bite."),
          (P, "I'll take the first watch, Elder."),
          (MO, "Good answer. Wrong shift. You're on the second. Go and sleep first, for once."),
          v=0),
        B("gather", "Wolfsbane for the Infirmary",
          "Elder Hua wants wolfsbane gathered before the pack returns, just in case it does.",
          (HUA, "Wolfsbane, not spirit herb this time. Uglier plant, better medicine. The terraces are full of it."),
          v=0),
        B("train", "Zhao Kang's Challenge, Again",
          "Losing face to a village brat once was bad enough. Zhao Kang wants a rematch, properly this time.",
          (ZHAO, "Sparring disciples don't count as a real match. You and me, training ground, no attendants."),
          (P, "If you insist."),
          (ZHAO, "I don't insist. I inform."),
          foe="sparring_disciple", v=0),
        B("social", "Lu Ping's Ledger of Fear",
          "Lu Ping has started a wager on how many more red-eyed wolves will turn up. Nobody finds it as funny as he does.",
          (LU, "Three to one says another pack shows up by the full moon. Care to bet against your own good luck?"),
          (P, "I'd rather there wasn't a pack at all."),
          (LU, "Boring answer. I'm writing it down anyway."),
          v=0),
        B("probe", "The Steward's Suspicious Math",
          "Steward Qian's accounts have not balanced since the array flared, and he blames everyone but himself.",
          (QIAN, "Three spirit stones unaccounted for! The array flares once and suddenly my ledger has opinions."),
          v=0),
        B("hunt", "Tracks Beyond the Wall",
          "Wolf tracks lead away from the pines toward the bamboo forest. Someone should follow them before dark.",
          foe="spirit_wolf", v=0),
        B("cultivate", "Sitting With the Spark",
          "Han Xue says the spark in your dantian needs patience more than effort. Sit, and prove her right.",
          (HAN, "Cultivation isn't a race, whatever Zhao Kang thinks. Sit. Breathe. Let it come to you."),
          v=0),
        B("social", "Xiao Shi's Overdue Letter",
          "Xiao Man is still waiting on her brother's letter from Qingshi. She asks you to write to him instead.",
          (MAN, "He promised every week. It's been two months now. Would you write, if I told you what to say?"),
          (P, "Of course."),
          (MAN, "Tell him the carp are fine. He worries about the strangest things."),
          v=0),
        B("probe", "What the Ninth Precept Costs",
          "Elder Gu returns, asking harder questions about the pendant and the array's flare.",
          (GU, "I have thought more about that array. And that jade. Show it to me again."),
          (P, "It's only ever been my mother's, Elder."),
          (GU, "Mm. See that it stays only that."),
          v=0),
        B("stage", "One Star Closer",
          "Your qi thickens by the day. Elder Mo says you're nearly ready for the cliff edge.",
          (MO, "Adequate progress. Don't let it go to your head. There isn't room in there for both."),
          v=0),
    ])
