from .dsl import P, N, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *
from .saga_gen import B, C

CHAPTER = chapter(
    10, "Heavenly Tribulation",
    "Under the last blood moon the Azure Cloud marches into the Abyss. A traitor opens the black gate at the cost of his life, "
    "the Blood Moon Patriarch falls on his throne, and his remnant flees to the Sky Isles to steal your heavenly tribulation. "
    "At the summit, with lightning in your veins, you face your shadow one last time, and climb.",
    "ch10_intro", "blood_abyss",
    [
        # ---------------------------------------------------------------- q091
        quest("The Last Blood Moon",
              "The Azure Cloud Sect marches on the Blood Moon Abyss.",
              "blood_abyss", [
                  cinematic("ch10_intro", "Watch the Azure Cloud Sect gather at the Abyss"),
                  talk(YUN, "Receive the battle plan from the Sect Master",
                       (YUN, "Wei Tong and Zhao Kang break the war camp. Ye Wuming's people take the obelisk ring. Gu will open the black gate."),
                       (YUN, "You go through the gate, to the throne. I'll be behind you, holding the sect together."),
                       (YUN, "Whatever happens, {player}, you are not carrying this alone. Remember the letter in the reliquary."), at="TeleportArray"),
                  talk(TIE, "Speak with Iron-Fang at the canyon rim",
                       (TIE, "My men are ready. Forty bandits, washed and fed, which is a first. They're a bit confused about it."),
                       (TIE, "Their families are behind that gate. We'll follow you through anything, sect brat. Sorry. Sect hero."), at="PlayerSpawn"),
                  talk(HAN, "Stand with Han Xue at the canyon mouth",
                       (HAN, "Stay alive. That's not a request, it's what the Sect Master said, and I'm saying it louder."),
                       (HAN, "And after, when this is done, you owe me a proper sparring match. No holding back."),
                       (P, "After, Senior Sister. I promise."), at="CanyonEntrance"),
              ], xp=2000),
        # ---------------------------------------------------------------- q092
        quest("Breaking the Line",
              "The Blood Moon army holds the field of bones and the war camp. Break through.",
              "blood_abyss", [
                  defeat("blood_guard", 6, "BoneField", "Break the Blood Guard line on the field of bones",
                         (WEI, "For Elder Mo! Hey, Elder, are you watching? Watch this one!")),
                  defeat("demon_cultivator", 5, "DemonCamp", "Burn the Blood Moon war camp",
                         (ZHAO, "Left side's mine, {player}! You can have the right side. It's smaller.")),
                  reach("BloodPools", "Regroup with Wei Tong at the blood pools",
                       (WEI, "We did it! The camp's burning, and I've only lost one bun. It was a very brave bun."),
                       (WEI, "Go on. The gate's ahead. Elder Mo would've said something grumpy and encouraging. Pretend I did.")),
              ], xp=2200, items={"medicine": 3}),
        # ---------------------------------------------------------------- q093
        quest("The Black Gate",
              "The fortress gate can only be opened from inside. Gu Hanshan has a way in.",
              "blood_abyss", [
                  talk(GU, "Meet Gu Hanshan at the obelisk ring",
                       (GU, "Remember the blood-red token you took from Iron-Fang's chest? The one I confiscated? I kept it."),
                       (GU, "It's a command token. With it, the gate guards will let me in. They don't know yet what I have become."),
                       (P, "They'll kill you when they find out."),
                       (GU, "Yes. I've made my peace with that. It is the first peace I have felt in twenty years."), at="ObeliskRing"),
                  reach("DemonGate", "Wait before the black gate",
                        (N, "The gate is black iron, carved with a moon swallowing a sword. It is taller than the main hall. It is utterly silent."),
                        (N, "Then, from inside, the sound of fighting. One man against many.")),
                  interact("seal", "DemonGate", "Break the gate's last seal",
                           (N, "You strike the seal with the Lotus Key. From the other side, someone pulls the great bar. The black gate groans open.")),
              ], xp=2200),
        # ---------------------------------------------------------------- q094
        quest("Court of Crimson",
              "Fight through the fortress courtyard, and find the man who opened the gate.",
              "blood_abyss", [
                  defeat("blood_guard", 5, "FortressCourt", "Clear the fortress courtyard"),
                  talk(GU, "Kneel beside Gu Hanshan at the gate",
                       (GU, "Ah. You came. I held them... as long as I could. I was always better at law than fighting."),
                       (GU, "Tell the sect... tell them the Law Hall is empty now. Fill it with someone kinder than me."),
                       (GU, "Lan... is waiting. I think she'll let me apologise. Thank you, {player}."), at="DemonGate"),
                  interact("prison_cage", "PrisonCages", "Break open the last cages",
                           (N, "The last locks fall. Mothers, children, old men stumble into the red light, blinking, alive.")),
                  talk(TIE, "Find Iron-Fang at the cages",
                       (TIE, "They're here. All of them. My sister. My men's wives, their children. Alive."),
                       (TIE, "Iron-Fang pays his debts. Today, in full. My blade is yours until the Patriarch's head is on the floor."), at="PrisonCages"),
              ], xp=2400, items={"spirit_stone": 10}),
        # ---------------------------------------------------------------- q095
        quest("The Shattered Altar",
              "The Altar of Blood still feeds the Patriarch. Destroy it, and let the void teach you what remains.",
              "blood_abyss", [
                  defeat("demon_cultivator", 4, "AltarOfBlood", "Defeat the altar's last defenders"),
                  interact("blood_altar", "AltarOfBlood", "Shatter the Altar of Blood",
                           (N, "The altar cracks from top to bottom. Three hundred years of stolen blood pours out and soaks away into the stone."),
                           (YE, "It's done. His power has no root now. Only what he carries in himself.")),
                  meditate("FortressCourt", 10, "Still your soul in the silence of the void",
                           (N, "In the silence after the altar breaks, you sink inward. Past body, past qi, past soul, to the empty place beneath."),
                           (N, "Nothing is there. And nothing is exactly enough. You rise with the stillness of the void in your bones.")),
              ], xp=3000, items={"spirit_stone": 10}),
        # ---------------------------------------------------------------- q096
        quest("The Blood Moon Patriarch",
              "Xue Wuji waits on his throne, and he has been waiting for three hundred years.",
              "blood_abyss", [
                  defeat("blood_guard", 4, "FortressCourt", "Cut down the Patriarch's throne guards"),
                  cinematic("ch10_patriarch", "Confront the Blood Moon Patriarch"),
                  defeat("blood_patriarch", 1, "PatriarchThrone", "Defeat the Blood Moon Patriarch",
                         (PATRIARCH, "Come then, little lotus. Show me the body I will wear to heaven."),
                         (P, "My body stays mine, Xue Wuji. So does my heart."),
                         (PATRIARCH, "We shall see how long you hold them both.")),
                  talk(YE, "Find Ye Wuming in the abyss depths",
                       (YE, "His body is dust. But his remnant soul tore free and fled upward. To the Sky Isles."),
                       (YE, "Your breakthrough has drawn heaven's eye. Your tribulation is gathering. He means to steal it, and ascend in your place."),
                       (YE, "I have my name back, {player}. The children have theirs. Go. Finish it. We'll hold the abyss."), at="AbyssDepths"),
              ], xp=4000, items={"demon_core": 3}),
        # ---------------------------------------------------------------- q097
        quest("Pursuit to the Heavens",
              "The Patriarch's remnant has fled to the Sky Isles. Follow it before the tribulation begins.",
              "sky_isles", [
                  talk(SAGE, "Meet Qing Luan at the cloud gate",
                       (SAGE, "You're back early. Also, the sky is on fire. I assume those two facts are related."),
                       (SAGE, "A remnant soul crossed my bridge an hour ago. It is climbing toward the tribulation peak, possessing everything it touches."),
                       (SAGE, "Heaven's lightning is gathering for you, lotus child. Get to the peak before he does."), at="CloudGate"),
                  defeat("blood_guard", 4, "JadeBridge", "Fight through the possessed Blood Guards on the jade bridge"),
                  reach("IsleOfWinds", "Speak with Han Xue on the Isle of Winds",
                       (HAN, "I followed you through the array. Obviously. Did you think I'd let you face the sky alone?"),
                       (HAN, "I'll hold the bridge. Nothing else crosses. Go."),
                       (HAN, "{player}... you still owe me that sparring match. Don't you dare ascend without paying your debts.")),
              ], xp=3000),
        # ---------------------------------------------------------------- q098
        quest("Remnants of the Blood Moon",
              "The remnant has corrupted the immortal garden. Clear the way and prepare lightning rods of thunder crystal.",
              "sky_isles", [
                  defeat("demon_cultivator", 5, "ImmortalGarden", "Purge the possessed cultivators in the garden"),
                  collect("thunder_crystal", 3, "SpiritVein", "Gather thunder crystals to ground the tribulation"),
                  interact("spirit_stone", "SpiritVein", "Charge the crystals at the spirit vein",
                           (N, "The crystals drink from the vein until they hum. Planted on the summit, they will split heaven's lightning like a river delta.")),
                  reach("CelestialRuins", "Speak with Zhao Kang at the celestial ruins",
                       (ZHAO, "Don't look at me like that. Of course I came. Someone has to witness your triumph and complain about it."),
                       (ZHAO, "Swear something to me. When you come back down, we fight. Properly. And I win."),
                       (P, "When I come back down, Zhao Kang. And you'll lose."),
                       (ZHAO, "Ha! That's the spirit. Go. The sky is waiting, and it has terrible manners.")),
              ], xp=3000, items={"thunder_crystal": 1}),
        # ---------------------------------------------------------------- q099
        quest("Heavenly Tribulation",
              "The heavenly tribulation descends on the summit, and the Patriarch's remnant rides the lightning.",
              "sky_isles", [
                  cinematic("ch10_tribulation", "Ascend to the tribulation peak"),
                  defeat("heart_demon", 1, "TribulationPeak", "Survive the heart tribulation and destroy the remnant",
                         (PATRIARCH, "The ninth bolt is the heart tribulation. I will be your heart, little lotus."),
                         (DEMON, "Hello again, {player}. He found me in the mirror. He says we can share."),
                         (P, "I beat you once. I'll do it as often as it takes.")),
                  meditate("TribulationPeak", 12, "Endure the nine bolts of heavenly lightning",
                           (N, "The lightning comes. First, second, third. Your body breaks and remakes itself. Fourth, fifth, sixth. Your qi burns white."),
                           (N, "Seventh, eighth. The remnant screams as the lightning finds it, and there is nothing left of Xue Wuji but ash on the wind."),
                           (N, "The ninth bolt strikes, and it does not hurt at all. It feels like the sky, saying your name.")),
              ], xp=6000, items={"phoenix_feather": 1}),
        # ---------------------------------------------------------------- q100
        quest("Immortal Ascension",
              "The Ascension Stair has opened. Say your farewells, and climb.",
              "sky_isles", [
                  talk(YUN, "Say farewell to the Sect Master at the cloud gate",
                       (YUN, "The stair has opened for you. Three hundred years, and our sect has its first immortal."),
                       (YUN, "You don't have to go. The heavens will wait. They have nothing but time."),
                       (P, "If I stay, the stair closes, and nobody climbs it again for a thousand years. Someone should see what's up there."),
                       (YUN, "Then go, {player}. And look down on us sometimes. We'll be the ones waving."), at="CloudGate"),
                  talk(SAGE, "Say farewell to Qing Luan",
                       (SAGE, "Sixty years I waited here for someone worth the climb. It was worth it. Don't tell anyone I said so."),
                       (SAGE, "At the top, you'll find a door. Knock politely. Heaven is very sensitive about manners.")),
                  reach("AscensionStair", "Climb the Ascension Stair",
                        (N, "Each step is made of light. Below, your friends grow small. Han Xue raises her sword in salute. Zhao Kang pretends not to cry."),
                        (P, "Elder Mo. Mother. Everyone. Thank you.")),
                  cinematic("ch10_ascension", "Ascend"),
                  cinematic("ch10_epilogue", "Epilogue: the Azure Cloud Sect"),
              ], xp=10000, items={"spirit_stone": 99}, realm="Immortal Ascension"),
    ])

# The last quiet before the ninth bolt. Everyone who can reach the summit
# does, one last time, before the tribulation itself. Spliced in between
# "Remnants of the Blood Moon" and "Heavenly Tribulation".
EXTRA = C(
    "Heavenly Tribulation", "sky_isles",
    "The delta is planted, the remnant is climbing, and heaven's storm is almost overhead. Before the ninth bolt, "
    "everyone who marched with you gathers on the isles one last time.",
    cast=[SAGE, HAN, ZHAO, YE, TIE, YUN],
    foes=["blood_guard", "demon_cultivator", "celestial_sentinel"],
    items=["thunder_crystal", "tribulation_jade", "void_shard"],
    props=["seal", "stone_stele", "demon_obelisk"],
    beats=[
        B("hunt", "The Remnant's Last Guards",
          "The Patriarch's remnant leaves possessed guards behind on the jade bridge, buying itself time to climb.",
          foe="blood_guard", v=0),
        B("gather", "The Last Forty Crystals",
          "Elder Bai's delta needs its final forty crystals planted on the summit before the ninth bolt falls.",
          item="thunder_crystal", v=0),
        B("probe", "Ye Wuming's Name",
          "At the obelisk ring below, Ye Wuming's crane reaches the isles: he has his name back at last.",
          (YE, "Ye Chen. My name was Ye Chen. My mother's cousin gave it to me before the moon took me. I remember it now. All of it."),
          v=0),
        B("social", "Iron-Fang's Sister",
          "A second crane follows: Iron-Fang's sister is free, mid-shout, exactly as frozen as she was taken.",
          (TIE, "She's shouting. At me. For being late. Twenty years late. I've never been so happy to be shouted at."),
          v=0),
        B("hunt", "Demon Cultivators on the Ruins",
          "A last pocket of demon cultivators, possessed by the fleeing remnant's touch, holds the celestial ruins.",
          foe="demon_cultivator", v=0),
        B("gather", "Void Shards From the Possessed Garden",
          "The immortal garden, cleared of possession, leaves void shards behind worth gathering before the storm.",
          item="void_shard", v=0),
        B("social", "Gu's Last Gift",
          "A final crane arrives from the abyss: Gu Hanshan's last request, granted by the Sect Master, is read aloud.",
          (N, "His last words, read at the moon gate: tell them the Law Hall is empty. Tell them I opened one gate, at least, before I closed for good."),
          v=0),
        B("hunt", "Celestial Sentinels, Guarding the Peak",
          "The palace's oldest sentinels form a line at the peak's edge, not to stop you, but to guard the ninth bolt's ground.",
          foe="celestial_sentinel", v=0),
        B("gather", "Tribulation Jade, One Last Piece",
          "You gather one final piece of tribulation jade, meaning to leave it at the summit for whoever climbs next.",
          item="tribulation_jade", v=0),
        B("cultivate", "Before the Ninth Bolt",
          "At the foot of the Ascension Stair, you sit one last time, and carry everyone who carried you, all the way here.",
          "@T:JadeBridge",
          (HAN, "I'm holding the bridge. Nothing crosses. Go and take the sky, {player}. I'll be right here when you're done."),
          (SAGE, "I'll be shouting. Loudly. The whole way up. Go, lotus child. Heaven's waited ten thousand years. It can wait one more minute."),
          v=0),
    ])
