from .dsl import P, N, added, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *
from .saga_gen import B, C

CHAPTER = chapter(
    4, "Ruins of the Forgotten Sect",
    "The library's Blood Moon records are missing. The Bamboo Hermit reveals who he really is and what your pendant "
    "really is. In the ruins of the Verdant Lotus Sect, a stone guardian waits for its heir, and you establish your foundation.",
    "ch04_intro", "bamboo_forest",
    [
        # ---------------------------------------------------------------- q031
        quest("Missing Pages",
              "The Sect Master wants to know everything about the Blood Moon Sect. Elder Bai's records should help. Should.",
              "sect", [
                  talk(YUN, "Report to the Sect Master",
                       (YUN, "A Blood Moon deacon, three hundred stolen hearts, and a hint of friends in high halls. I will not sleep tonight."),
                       (YUN, "Three centuries ago our founder and the Verdant Lotus Sect sealed the Blood Moon Patriarch beneath the Abyss."),
                       (YUN, "Elder Bai keeps the records. Learn how the seal was made, {player}. If it is failing, I must know why.")),
                  talk(BAI, "Ask Elder Bai for the Blood Moon records",
                       (BAI, "The Blood Moon War chronicles? Fourth floor, east shelf, beside the recipes for turtle soup. Do not ask."),
                       (BAI, "Here... hm. Hm! The pages on the Azure Heaven Seal are gone. Cut out. With a very sharp, very tidy blade."),
                       (BAI, "Only elders and the Law Hall may enter the fourth floor. Whoever did this had a pass, and patience."),
                       added(HAN, "Elders and the Law Hall. That is not a long list, Elder Bai."),
                       added(P, "And not one we can say out loud. Not yet."),
                       (BAI, "The Verdant Lotus built the seal. Their ruins lie in the Whispering Bamboo. Stones cannot be cut out of a book.")),
                  cinematic("ch04_intro", "Watch the journey to the forgotten ruins"),
                  reach("RuinsGate", "Find the gate of the ancient ruins",
                        (N, "A stone archway rises from the bamboo, choked with vines. Carved lotus flowers climb its pillars."),
                        (N, "At its keystone is a single lotus, exactly the shape of the jade at your belt.")),
              ], xp=260),
        # ---------------------------------------------------------------- q032
        quest("The Hermit's Secret",
              "The archway will not open for you. The hermit who warned you about the ruins knows more than he admits.",
              "bamboo_forest", [
                  reach("HermitHut", "Return to the hermit's hut",
                        (N, "The hermit sits outside with two cups of tea already poured. He does not look surprised to see you.")),
                  talk(LAN, "Ask the hermit about the ruins",
                       (LAN, "You went to the ruins. Of course you did. The young never listen and the old never stop talking."),
                       (P, "The keystone matches my pendant. You knew. The first time you saw it, you knew."),
                       (LAN, "I did. Sit down. This tea has waited three hundred years. It can wait for one more story.")),
                  cinematic("ch04_lotus", "Hear the hermit's story"),
                  talk(LAN, "Accept the hermit's charge",
                       (LAN, "My name is Lan Jue. Last disciple of the Verdant Lotus Sect. I ran when my masters died. I have been running ever since."),
                       (LAN, "Your pendant is the Lotus Key, half of what binds the Azure Heaven Seal. Your mother was of our blood."),
                       (LAN, "The ruins will test you. Gather the rune stones scattered at the gate, and the arch will know its heir."),
                       (P, "You could have come with me."),
                       (LAN, "I could have done many things for three hundred years. Go. I will follow when my shame lets me."),
                       added(YE, "He speaks true, lotus-bearer. I have watched those ruins for a year. They are waiting for you."),
                       added(LAN, "You again. You walk too quietly for an honest man.")),
              ], xp=240, items={"jade_slip": 1}),
        # ---------------------------------------------------------------- q033
        quest("Stones That Remember",
              "Gather the lotus rune stones and read the old stele at the shrine. Someone has followed you from the sect.",
              "bamboo_forest", [
                  collect("rune_fragment", 4, "RuinsGate", "Gather the lotus rune stones around the gate"),
                  talk(ZHAO, "Deal with Zhao Kang on the forest path",
                       (ZHAO, "Don't look so surprised. You're not the only one who can walk through bamboo."),
                       (P, "You followed me? From the sect?"),
                       (ZHAO, "Elder Gu ordered me to keep an eye on you. He said you carry something the sect must protect."),
                       (ZHAO, "Personally, I think it's a waste of my talents. But a Zhao obeys the Law Hall. So. Lead on, village brat."), at="ForestPath"),
                  interact("stone_stele", "AncientShrine", "Read the stele in the ruined shrine",
                           (N, "Here the Verdant Lotus gave its heart. With the Azure Cloud we bound the Patriarch Xue Wuji beneath the Abyss."),
                           (N, "The seal has two keys. The Lotus Key, which binds. The Azure Eye, which watches. Never let both fall to one hand."),
                           (ZHAO, "The Azure Eye... that's the formation array at home. And the Lotus Key is... your trinket?"),
                           (P, "Apparently my trinket is older than your clan."),
                           added(YE, "Never both to one hand. Remember that line, lotus-bearer. Someone in your sect has forgotten it."),
                           added(ZHAO, "Who said that? Show yourself! ...He's gone. I hate this forest.")),
              ], xp=240, items={"rune_fragment": 1}),
        # ---------------------------------------------------------------- q034
        quest("Stone Guardians",
              "The ruins' stone sentinels wake at the sound of footsteps. Get past them and open the archway.",
              "bamboo_forest", [
                  defeat("stone_golem", 3, "RuinsGate", "Defeat the stone sentinels at the gate",
                         (ZHAO, "Stone men! Wonderful. My sword was freshly polished, too.")),
                  interact("seal", "RuinsGate", "Set the rune stones into the archway",
                           (N, "The rune stones slide into place one by one. The carved lotus on the keystone opens its petals."),
                           (N, "With a sound like a sigh, the vines fall away and the gate of the Verdant Lotus opens for the first time in three centuries."),
                           (ZHAO, "It... opened. For you. Fine. FINE. I'm not impressed. I'm slightly impressed.")),
                  reach("RuinsInner", "Step through the opened archway",
                        (N, "Beyond the arch lies a courtyard of green stone. At its centre kneels a giant statue, head bowed, hands resting on a sword."),
                        (ZHAO, "Please tell me that one doesn't move."),
                        added(LAN, "It moves, young man. Only when it must. I would not stand quite so close."),
                        added(ZHAO, "Where did you come from? Does everyone in this forest walk like a ghost?"),
                        added(P, "He's the hermit. He's... a friend of the lotus.")),
              ], xp=260, items={"spirit_stone": 3}),
        # ---------------------------------------------------------------- q035
        quest("The Guardian of the Lotus",
              "The inner courtyard is watched by the last guardian of the Verdant Lotus. It will not accept an heir without a trial.",
              "bamboo_forest", [
                  talk(LAN, "Find the hermit at the shrine",
                       (LAN, "I followed. My shame is slower than my feet, it turns out."),
                       (LAN, "The guardian in the courtyard was carved by my master. It asks one question with its fists: are you worthy?"),
                       (LAN, "Do not fear it. It is not cruel, only very, very thorough."),
                       added(ZHAO, "Thorough. Wonderful. My favourite kind of stone monster."),
                       added(P, "Then I'll be thorough too."), at="AncientShrine"),
                  defeat("stone_golem", 2, "RuinsGate", "Stop the sentinels reforming at the gate",
                         (LAN, "The sentinels are reforming. Break them again, quickly, before the guardian wakes!")),
                  defeat("ancient_guardian", 1, "RuinsInner", "Pass the trial of the ancient guardian",
                         (N, "The great statue lifts its head. Moss sloughs from its shoulders. A voice grinds like millstones: who bears the lotus?"),
                         (P, "I do. {player}, of the Azure Cloud. And of the Verdant Lotus."),
                         (N, "Then show me that the lotus has not wilted.")),
              ], xp=380, items={"spirit_stone": 5}),
        # ---------------------------------------------------------------- q036
        quest("Legacy of the Lotus",
              "The guardian kneels. The Verdant Lotus left something for its heir.",
              "bamboo_forest", [
                  interact("treasure_chest", "RuinsInner", "Open the Verdant Lotus reliquary",
                           (N, "Inside lies a jade slip carved with lotus roots: the Verdant Lotus Heart Sutra, and a letter in an elegant hand."),
                           (N, "To whoever carries my key. I am sorry for the burden. It was always meant to be shared. Do not carry it alone.")),
                  meditate("SpiritSpring", 8, "Comprehend the Heart Sutra at the spirit spring",
                           (N, "The sutra unfolds in your mind like a flower opening underwater. Roots, stem, blossom. Patience, strength, compassion."),
                           (N, "Your qi begins to settle, layer upon layer, like silt forming bedrock.")),
                  talk(LAN, "Return to the hermit",
                       (LAN, "You read it. I can see it in your breathing. The lotus grows in mud and is not stained."),
                       (LAN, "Three hundred years I waited for someone to open that box. I thought I would feel relief. I feel... old."),
                       (P, "Come back to the sect with me. Tell them what you know."),
                       (LAN, "One day. Not yet. First I must forgive a coward, and he is very stubborn."),
                       added(ZHAO, "Forgive him quickly, old man. There's a tournament coming, and my rival is sitting in a forest.")),
              ], xp=300, items={"jade_slip": 1}),
        # ---------------------------------------------------------------- q037
        quest("Blood in the Shrine",
              "Blood Moon scouts have followed your trail to the ruins and are defacing the stele.",
              "bamboo_forest", [
                  defeat("demon_cultivator", 4, "AncientShrine", "Drive the Blood Moon scouts from the shrine",
                         (ZHAO, "They're smashing the stele! Barbarians! That's at least a thousand years of calligraphy!")),
                  reach("OldBridge", "Check on Zhao Kang at the old bridge",
                       (ZHAO, "It's a scratch. Don't fuss. A Zhao doesn't bleed. We... tactically leak."),
                       (P, "You stepped in front of that blade for me."),
                       (ZHAO, "Don't be sentimental. Nobody gets to defeat you except me. I've been planning it for months."),
                       added(LAN, "Tactically leak. I shall remember that one. Hold still, boy. This will sting.")),
                  collect("spirit_herb", 3, "HerbGrove", "Gather herbs to treat Zhao Kang's wound"),
              ], xp=280, items={"medicine": 2}),
        # ---------------------------------------------------------------- q038
        quest("The Law Hall's Interest",
              "Back at the sect, everyone wants to see the Heart Sutra. Some want it more than others.",
              "sect", [
                  reach("SectGate", "Return to the sect with Zhao Kang",
                        (ZHAO, "Home. I'm going to bathe for three days. Don't tell anyone I helped you. I have a reputation for being unbearable.")),
                  talk(BAI, "Show the Heart Sutra to Elder Bai",
                       (BAI, "The Verdant Lotus Heart Sutra. I have waited my whole life to see this. I may cry. Don't look."),
                       (BAI, "Keep it. It is bound to the Lotus Key and would only sulk in my shelves."),
                       (BAI, "And the missing pages... the fourth-floor log shows a Law Hall seal. The Law Hall borrows everything. It's how they keep us honest.")),
                  talk(GU, "Answer Elder Gu's summons",
                       (GU, "Zhao Kang tells me you found a Verdant Lotus relic. The Law Hall will take custody of it. For safekeeping."),
                       added(ZHAO, "I only told the Law Hall what I saw, Elder. As I was ordered."),
                       (P, "With respect, Elder, the Sect Master ordered me to keep it."),
                       (GU, "Did she. Then keep it, disciple. Keep it very close. Things kept close are the easiest to lose.")),
                  talk(MO, "Speak with Elder Mo",
                       (MO, "Gu wanted the sutra? Don't take it to heart. He's been cold ever since his daughter died. Twenty years now."),
                       (MO, "Gu Lan. A bright girl. Meridian sickness. No pill could save her. He searched the whole world."),
                       (MO, "Grief is a heart demon that never stops whispering. Be patient with him, {junior}. For my sake.")),
              ], xp=240, items={"spirit_stone": 3}),
        # ---------------------------------------------------------------- q039
        quest("Preparing the Foundation",
              "Establishing a foundation takes pills, spirit stones, and a clear conscience. You have one of three.",
              "sect", [
                  talk(HUA, "Ask Elder Hua for a Foundation Pill",
                       (HUA, "A Foundation Pill needs lotus root from the pond, gathered at dusk, and five spirit stones to fire the cauldron."),
                       (HUA, "The stones come from the treasury. Good luck with that.")),
                  talk(QIAN, "Negotiate with Steward Qian",
                       (QIAN, "Five spirit stones? Five? Do you know what five spirit stones could buy? Five spirit stones!"),
                       (P, "It's for a Foundation Pill. The Sect Master approved it."),
                       (QIAN, "Approved it. Everyone approves things. Nobody counts things. Fine. Take them. Sign here. And here. And here."),
                       added(HUA, "Sign it quickly, Steward, or I'll brew you something for your nerves. You won't enjoy it.")),
                  collect("spirit_herb", 4, "LotusPond", "Gather lotus root at the pond at dusk"),
                  talk(MAN, "Tell Xiao Man what you learned in Qingshi",
                       (MAN, "You're back! Did you go through Qingshi? Did you see my brother? Did he say why he hasn't written?"),
                       (P, "Xiao Man... Xiao Shi was taken. By the same people who took the townsfolk. I think he's alive."),
                       (MAN, "Taken? But he... he's so bad at fighting. He faints at the sight of needles."),
                       (MAN, "Promise me you'll bring him back. No. Don't promise. Just... do it. Please.")),
              ], xp=260, items={"spirit_stone": 5, "spirit_herb": 2}),
        # ---------------------------------------------------------------- q040
        quest("Foundation Establishment",
              "With the Foundation Pill in hand and Han Xue standing guard, build the foundation of your dao.",
              "sect", [
                  talk(HAN, "Ask Han Xue to guard your breakthrough",
                       (HAN, "Breakthroughs attract trouble. Heart demons, jealous juniors, very curious elders. I'll stand guard."),
                       (HAN, "The plum garden is quiet at night, and Zhao Kang is too injured to sulk there. Go.")),
                  meditate("PlumGarden", 12, "Establish your foundation in the plum garden",
                           (N, "Your qi pours downward like a waterfall into your dantian, and there it hardens, layer upon layer, into a foundation of jade."),
                           (N, "Beneath the plum blossoms, a single green lotus flickers into being around you, and slowly sinks into your heart."),
                           (P, "I can feel every blossom on every branch. Is this what the elders feel all the time?")),
                  talk(YUN, "Receive the Sect Master's news",
                       (YUN, "Foundation Establishment, and a Verdant Lotus sutra. You grow faster than my worries, {player}. Barely."),
                       (YUN, "In one month the sect holds the Inner Sect Tournament. The winner earns a place at my side, and the Azure Eye's trust."),
                       (YUN, "I want you to enter. And I want whoever cut those pages to watch you win."),
                       added(HAN, "I'll train {them} myself, Sect Master. Morning and evening."),
                       added(P, "Then whoever cut those pages will have a very good view.")),
              ], xp=400, items={"spirit_stone": 5}, realm="Foundation Establishment"),
    ])

# The last errands before the breakthrough: Zhao Kang's wound, Gu's grief,
# Xiao Shi's fate weighing on everyone. Spliced in between "Preparing the
# Foundation" and the "Foundation Establishment" breakthrough itself.
EXTRA = C(
    "Ruins of the Forgotten Sect", "sect",
    "The last errands before the breakthrough: Zhao Kang's wound still mending, Elder Gu's old grief, and Xiao "
    "Man's fear for her brother, taken by the same hands that fed the wolves.",
    cast=[ZHAO, BAI, GU, MO, HUA, QIAN, MAN, HAN, LAN],
    foes=["demon_cultivator", "stone_golem"],
    items=["spirit_herb", "spirit_stone", "jade_slip"],
    props=["stone_stele", "jade_slip", "seal"],
    beats=[
        B("social", "Zhao Kang's Tactical Leak",
          "Zhao Kang's wound is healing, loudly and with great commentary, in the sect's infirmary.",
          (ZHAO, "I am recovering with dignity. The dignity is mostly silent screaming, but it is dignified screaming."),
          v=0),
        B("probe", "The Fourth-Floor Log",
          "Elder Bai wants a second opinion on the fourth floor's borrowing log, now that a Law Hall seal is involved.",
          (BAI, "Someone signed for the missing pages properly, which is almost worse than if they'd stolen them outright."),
          v=0),
        B("gather", "Lotus Root, Properly This Time",
          "Elder Hua wants more lotus root gathered at dusk; the last batch went into a pill, and a second pill is safer than one.",
          item="spirit_herb", v=0),
        B("hunt", "Scouts Near the Ruins Again",
          "A few more Blood Moon scouts have been seen circling the Verdant Lotus ruins since the stele was defaced.",
          foe="demon_cultivator", v=0),
        B("social", "Gu Lan's Old Room",
          "Elder Mo mentions, carefully, that Gu Hanshan still keeps his daughter's old room exactly as she left it.",
          (MO, "Twenty years, and not a single thing moved. Grief keeps strange houses. Don't mention I told you."),
          v=0),
        B("probe", "Steward Qian's Second Thoughts",
          "Steward Qian, having signed away five spirit stones, now wants an itemised account of exactly how they were spent.",
          (QIAN, "Receipts! I need receipts! A pill without a receipt is just an expensive rumour!"),
          v=0),
        B("cultivate", "Steadying Before the Leap",
          "Han Xue insists on one more careful meditation before the actual breakthrough attempt, foundation pill or not.",
          (HAN, "A pill isn't a shortcut around readiness. Sit. Let's be sure, not just hopeful."),
          v=0),
        B("social", "Xiao Man's Sleepless Night",
          "Xiao Man hasn't slept properly since learning her brother was taken. She asks for company more than answers.",
          (MAN, "I don't need you to fix it tonight. I just don't want to sit with it alone."),
          v=0),
        B("probe", "The Hermit's Warning, Again",
          "A paper crane arrives from Lan Jue with a warning about breakthroughs attracting more than heart demons.",
          (LAN, "Blood Moon scouts near a fresh foundation is not a coincidence. Guard the garden well."),
          v=0),
        B("defend", "Guarding the Plum Garden",
          "Before the breakthrough, the plum garden itself needs clearing and warding against anything that might sense it.",
          foe="stone_golem", v=0),
    ])
