from .dsl import P, N, added, chapter, quest, talk, reach, defeat, collect, meditate, interact, cinematic
from .npcs import *
from .saga_gen import B, C

CHAPTER = chapter(
    7, "Siege of Qingshi",
    "The Blood Moon and Iron-Fang's bandits march on Qingshi. With Zhao Kang and Wei Tong at your side, you turn "
    "a frightened market town into a fortress, and learn that the siege was never really about the town.",
    "ch07_intro", "qingshi_town",
    [
        # ---------------------------------------------------------------- q061
        quest("Smoke on the Horizon",
              "The Sect Master sends you to Qingshi with Zhao Kang and Wei Tong. The Blood Moon will arrive within days.",
              "sect", [
                  talk(YUN, "Receive the Sect Master's orders",
                       (YUN, "Take Zhao Kang and Wei Tong. The sect must hold the mountain in case this is a feint, so you three are the vanguard."),
                       (YUN, "Hold Qingshi until the moon wanes. Whatever it costs, don't let them turn the town into another graveyard.")),
                  cinematic("ch07_intro", "Watch the Blood Moon host approach Qingshi"),
                  talk(ZHOU, "Meet Magistrate Zhou at the yamen",
                       (ZHOU, "The immortals! Good. I have forty guards, three hundred farmers and one very old ballista."),
                       (ZHOU, "I was a coward once, and a monster fed on my town while I drank his tea. Not twice. Tell me where to stand."),
                       (P, "Right here, Magistrate. People need to see you standing."),
                       added(ZHAO, "Forty guards and a ballista. The Zhao clan has held worse walls with less. ...Not many. But some.")),
              ], xp=500),
        # ---------------------------------------------------------------- q062
        quest("Walls and Wards",
              "The walls are old, the guards are few, and Merchant Jin's warehouse is full of lamp oil he refuses to share.",
              "qingshi_town", [
                  talk(DU, "Plan the defence with Constable Du",
                       (DU, "The gate will hold for an hour against cultivators. Maybe. Fire will buy us more. We need oil for the wall braziers."),
                       (DU, "Jin's warehouse has barrels of it. He says it's for export. I say it's for not dying.")),
                  talk(JIN, "Persuade Merchant Jin to open his warehouse",
                       (JIN, "My oil? That's six months' profit! Who compensates me? The yamen? The yamen owes me for the ballista!"),
                       added(DU, "Six months' profit, Jin, or no town left to sell it in. Pick one."),
                       (P, "You sold blood lotus to the people who took eleven of your neighbours. You owe this town more than oil."),
                       (JIN, "...That was business. I didn't know. I didn't want to know."),
                       (JIN, "Take it. Take all of it. Maybe it will weigh a little less on the scales in the next life.")),
                  collect("lantern_oil", 5, "Warehouse", "Carry the oil barrels to the wall"),
                  interact("seal", "TownGate", "Paint warding talismans on the town gate",
                           (N, "You paint the gate posts with cinnabar wards. Constable Du watches, then quietly paints a few crooked ones of his own.")),
              ], xp=500, items={"spirit_stone": 4}),
        # ---------------------------------------------------------------- q063
        quest("The Watchtower",
              "Climb the watchtower and sound the alarm when the host arrives.",
              "qingshi_town", [
                  reach("WatchTower", "Climb the watchtower",
                        (N, "Torches, thousands of them, flow over the far hills like a burning river. Blood Moon banners, and bandit flags beside them."),
                        (WEI, "That's... a lot of torches. I'm going to need a bigger lunch.")),
                  interact("bronze_bell", "WatchTower", "Ring the alarm bell",
                           (N, "The bell rings. Doors slam. Children are carried to the temple. Old men pick up hoes and stand in the street.")),
                  reach("MainStreet", "Take your positions with Zhao Kang",
                       (ZHAO, "I'll hold the east wall. Wei Tong takes the south. You go wherever it's worst. That's what you're good at."),
                       (ZHAO, "And if I die, tell my clan I died beautifully. Specify beautifully."),
                       (P, "Nobody's dying today, Zhao Kang."),
                       added(WEI, "Nobody's dying before dinner, anyway. After dinner, we'll see."),
                       (ZHAO, "Hmph. From your lips to heaven's ears.")),
              ], xp=500),
        # ---------------------------------------------------------------- q064
        quest("Raiders in the Fields",
              "The bandits strike the farmland first, to burn the harvest and scatter the farmers.",
              "qingshi_town", [
                  talk(PAN, "Ask Old Pan to ferry the farmers to safety",
                       (PAN, "Ferry the farmers across? At night, with bandits shooting at us? Double fare."),
                       (PAN, "I'm joking. No fare. Forty years on this river, and the first time anyone needed me. Go, I'll bring them over.")),
                  defeat("bandit", 5, "Farmland", "Drive the raiders from the fields",
                         (TIE, "Burn the rice! Burn the barns! Nobody eats this winter unless Iron-Fang says so!")),
                  reach("MarketSquare", "Report to Wei Tong at the market kitchens",
                       (WEI, "The farmers are across? Good. I've been guarding the kitchens. Strategically. Armies march on their stomachs."),
                       (WEI, "Here, a dumpling. Eat it. Then go and hit something. Elder Mo would want you fed and angry."),
                       added(ZHAO, "Strategically guarding the kitchens. Wei Tong, you are a genius and a disgrace."),
                       added(P, "Save me two dumplings. I'll be back for them.")),
              ], xp=520, items={"medicine": 2}),
        # ---------------------------------------------------------------- q065
        quest("The Graveyard Flank",
              "Demonic cultivators are trying to wake Deacon Hong's old blood formation beneath the graves.",
              "qingshi_town", [
                  defeat("demon_cultivator", 4, "Graveyard", "Break the demonic cultivators at the graves"),
                  defeat("corrupted_wolf", 3, "Graveyard", "Slay the blood-fed wolves they brought"),
                  interact("seal", "Graveyard", "Seal the blood formation for good",
                           (N, "You press your palm to the rune circle. The Heart Sutra flows from your golden core, and the blood-ink fades to grey dust.")),
                  reach("MainStreet", "Check on Zhao Kang",
                       (ZHAO, "The east wall held. Barely. I may have set my own sleeve on fire. It was a tactical fire."),
                       (ZHAO, "They didn't push the graveyard to take the town. They wanted blood on those runes. Why?"),
                       added(WEI, "Blood on the runes. Like the old deacon's circle. Somebody is still collecting."),
                       added(P, "And somebody is still paying for it. Let's find out who.")),
              ], xp=540, items={"rune_fragment": 2}),
        # ---------------------------------------------------------------- q066
        quest("The Riverside Assault",
              "Blood Guards come up the river on rafts. Old Pan's ferry is still out on the water.",
              "qingshi_town", [
                  reach("Riverside", "Race to the docks",
                        (N, "Black rafts slide down the river under the red moon. Out on the water, Old Pan's ferry is still crossing, packed with farmers.")),
                  defeat("blood_guard", 4, "Riverside", "Repel the Blood Guards at the docks"),
                  collect("medicine", 4, "Riverside", "Save the medicine crates washed up on the bank"),
                  talk(LIU, "Bring the medicine to Widow Liu at the well",
                       (LIU, "My Liu Er came home three days ago. Thin as a reed, but home. He talks about a sect disciple who broke his cage."),
                       added(PAN, "And every farmer's across the river, Madam Liu. My third plank complained the whole way."),
                       (LIU, "You didn't promise. You just did it. Now I'll carry water to your wall until my arms fall off."),
                       (P, "Tell Liu Er to stay inside tonight. And give him an extra bowl of rice from me.")),
              ], xp=540, items={"medicine": 2}),
        # ---------------------------------------------------------------- q067
        quest("Treachery at the Warehouse",
              "Bandits are pouring out of a tunnel under the guild warehouse. Merchant Jin knows why.",
              "qingshi_town", [
                  talk(JIN, "Catch Merchant Jin in the back alley",
                       (JIN, "Don't kill me! I dug that tunnel years ago for smuggling tea! Iron-Fang found out. He threatened my daughters."),
                       (JIN, "I opened it for him tonight. Then I saw you give away my oil to people who'd spat at me. I couldn't..."),
                       added(DU, "Iron-Fang threatened my runners too, Jin. You should have come to me."),
                       (JIN, "Turn me in. I deserve it. But close the tunnel first. Please."),
                       (P, "Fear made you do it. What you do next is your choice. Go help Constable Du, Master Jin."), at="BackAlley"),
                  defeat("bandit", 4, "Warehouse", "Stop the bandits in the warehouse yard"),
                  interact("seal", "Warehouse", "Collapse the smugglers' tunnel",
                           (N, "A talisman flares. The earth groans, and the tunnel folds in on itself with a satisfying thump.")),
              ], xp=560, items={"spirit_stone": 4}),
        # ---------------------------------------------------------------- q068
        quest("Iron-Fang Tie Hu",
              "Iron-Fang himself leads his men into the market square. End this.",
              "qingshi_town", [
                  defeat("bandit", 3, "MarketSquare", "Cut down Iron-Fang's lieutenants"),
                  defeat("bandit_chief", 1, "MarketSquare", "Defeat Iron-Fang Tie Hu",
                         (TIE, "You again! The sect brat who took my token. I've dreamed about this, you know. Every night."),
                         (P, "I've heard your men talk, Iron-Fang. The Blood Moon holds their families. Holds yours too."),
                         (TIE, "Shut up! Shut up and fight!")),
                  talk(TIE, "Decide Iron-Fang's fate at the temple",
                       (TIE, "Go on, then. Finish it. That's what you sect types do to trash like me."),
                       (P, "Where are your people's families, Tie Hu?"),
                       (TIE, "In the Abyss. Behind the black gate. I burned villages so they'd keep breathing. Does that make it better? It doesn't."),
                       (P, "Kneel at this temple and swear to fight for the town you tried to burn. Then help me bring your families home."),
                       added(DU, "Swear it here, Iron-Fang, and I'll write it down. In ink. The permanent kind."),
                       (TIE, "...You're a fool. Fine. Iron-Fang pays his debts. Eventually."), at="Temple"),
              ], xp=800, items={"spirit_stone": 6}),
        # ---------------------------------------------------------------- q069
        quest("The Last Wave",
              "The final wave hits the town gate, and a familiar figure watches from the graveyard hill.",
              "qingshi_town", [
                  defeat("demon_cultivator", 5, "TownGate", "Hold the town gate against the last wave",
                         (DU, "They're at the gate! Everyone with a spear, with me! For Qingshi!"),
                         added(ZHAO, "For Qingshi! And for the Zhao clan, who will hear about this in great detail!"),
                         added(P, "Hold the line! They're breaking!")),
                  talk(GU, "Confront Gu Hanshan on the graveyard hill",
                       (GU, "Well fought, disciple. Truly. You were always the most stubborn of the new ones."),
                       (P, "Why, Elder Gu? Why betray the sect? Why feed children to the Blood Moon?"),
                       (GU, "The Patriarch holds my daughter's soul. When the seal breaks, he will give her back. A new body. A new life."),
                       (GU, "This siege was never about the town. Every drop spilled here soaks down to the seal. You've helped him, you know."),
                       (GU, "You would do the same for someone you loved. Don't pretend you wouldn't."), at="Graveyard"),
                  reach("Graveyard", "Chase Gu into the graves",
                        (N, "Where Gu stood there is only a scorched talisman and the smell of blood. He is gone."),
                        (P, "No. I wouldn't. Not like this.")),
              ], xp=800, items={"demon_core": 2}),
        # ---------------------------------------------------------------- q070
        quest("Dawn over Qingshi",
              "The siege is broken. Mourn the fallen, share a meal with the living, and report to the sect.",
              "qingshi_town", [
                  talk(ZHOU, "Accept the magistrate's thanks",
                       (ZHOU, "Qingshi stands. Nineteen dead, which is nineteen too many and ten thousand too few for what they intended."),
                       (ZHOU, "I'm having a stele carved at the gate. Your name will be on it. The yamen will not forget. I will not forget.")),
                  talk(FANG, "Celebrate at the Drunken Crane",
                       (FANG, "Free wine for the heroes! One cup each. Immortals drink like fish and I'm not a lake."),
                       (FANG, "Iron-Fang is washing dishes in my kitchen, by the way. He's surprisingly good. Very thorough scrubber."),
                       added(TIE, "Very thorough. Tell them very thorough. Iron-Fang does nothing by halves."),
                       added(P, "One cup, then. To the nineteen.")),
                  meditate("Temple", 8, "Mourn the fallen at the temple",
                           (N, "Nineteen tablets. Farmers, a guard, a boy who carried arrows. You burn incense for each, and say each name aloud.")),
                  talk(YUN, "Report to the Sect Master",
                       (YUN, "You held the town. But Gu was right about one thing: the blood reached the seal. It has cracked again."),
                       (YUN, "We cannot patch it any longer. We must build a new one. The Great Azure Formation, a seal for ten thousand years."),
                       (YUN, "It needs star iron, thunder crystal and phoenix feathers. They exist in one place: the Celestial Sky Isles."), map="sect"),
              ], xp=700, items={"spirit_stone": 6, "medicine": 2}),
    ])

# Gu is gone into the graves and the gate held, but a siege leaves a town
# with wounds to count before it can properly celebrate. Spliced in between
# "The Last Wave" and "Dawn over Qingshi".
EXTRA = C(
    "Siege of Qingshi", "qingshi_town",
    "The gate held and the traitor fled, but Qingshi spends the last hours before dawn counting its wounded, its "
    "dead, and the strange new debts a siege leaves behind.",
    cast=[DU, ZHOU, FANG, JIN, TIE, LIU],
    foes=["bandit", "demon_cultivator"],
    items=["medicine", "spirit_stone", "lantern_oil"],
    props=["treasure_chest", "seal"],
    beats=[
        B("rescue", "The Wounded at the Temple",
          "The temple has filled with wounded faster than Elder Hua's borrowed supplies can stretch.",
          (N, "Rows of townsfolk and disciples lie on borrowed mats. A healer from Thunder Peak moves between them, humming to keep her hands steady."),
          v=0),
        B("hunt", "Bandits Still in the Fields",
          "Not all of Iron-Fang's men surrendered when he did. A few still hide among the burned rice paddies.",
          foe="bandit", v=0),
        B("social", "Iron-Fang's First Scrubbed Pot",
          "Iron-Fang, true to his word, has started washing dishes at the Drunken Crane, and is oddly good at it.",
          (TIE, "Forty years of terrorizing this river valley, and it turns out I'm excellent with a scrub brush. Nobody tell my old men."),
          v=0),
        B("gather", "Salvage From the Warehouse",
          "The collapsed smuggling tunnel left the warehouse in disarray. Merchant Jin wants an honest inventory this time.",
          item="lantern_oil", v=0),
        B("probe", "Gu's Scorched Talisman",
          "The talisman Gu left behind on the graveyard hill still holds a trace of the pattern that carried him away.",
          (N, "The scorch mark isn't random. It's a partial teleport rune, torn off mid-use. Someone should study it properly."),
          v=0),
        B("social", "Widow Liu's New Worry",
          "With Liu Er home safe, Widow Liu has found a new thing to worry about: that he'll do something reckless to prove himself.",
          (LIU, "He wants to guard the wall now. Sixteen years old and he wants to guard the wall. I don't know whether to be proud or furious."),
          v=0),
        B("gather", "Counting the Dead, Gently",
          "Magistrate Zhou wants every name recorded properly for the stele, and asks for help going door to door.",
          item="spirit_stone", v=0),
        B("hunt", "Demonic Stragglers by the River",
          "A handful of demonic cultivators, cut off from the retreat, still lurk near the docks.",
          foe="demon_cultivator", v=0),
        B("social", "Constable Du's Ledger of Debts",
          "Constable Du has started keeping a very different ledger: who helped, and how, so the town remembers properly.",
          (DU, "Not for punishment this time. For thanks. I've never kept a ledger that felt this good to write."),
          v=0),
        B("cultivate", "Breath Before the Dawn",
          "Before the town properly wakes, you take a last quiet moment to settle your core after the night's fighting.",
          (N, "The market square is finally still. Your golden core turns over once, slow and warm, like something finally allowed to rest."),
          v=0),
    ])
