"""Hand-written moral choices.

NEW maps (chapter number, beat index) of a generated chapter to a choice; it
is offered after the quest's last conversation (the last talk objective).
LEGACY maps (original quest number, objective index) of the ten voiced
chapters to a choice offered after that objective's voiced lines; the voiced
lines themselves are untouched.

Every option continues the story the same way. Options differ in alignment
(law: + lawful / - chaotic, good: + good / - evil), small rewards, flags that
later lines can react to, and the NPC's reaction, which the generator adds
from morality.REACT.
"""

from .morality import Ch, O

NEW = {
    # ---------------------------------------------------------------- volume I
    (4, 2): Ch("The ferret's nest also holds a jade hairpin that nobody has reported missing.",
               O("Hand it to Steward Qian's lost-and-found", law=8),
               O("Ask around quietly and return it yourself", law=-2, good=6),
               O("Keep it. Nobody's looking for it.", law=-4, good=-6, items={"spirit_stone": 1})),
    (5, 7): Ch("The young bandit is still tied up outside the hut, waiting to learn what you'll do with him.",
               O("Let him go to warn his family", law=-6, good=10, flag="freed_harvest_bandit"),
               O("Deliver him to the magistrate", law=10),
               O("Beat the rest of the truth out of him", law=-2, good=-8, xp=40)),
    (6, 8): Ch("Gou sits in the dirt, beaten, his men's names half-written. The carters he took want him punished.",
               O("Spare him, and send him with the names to Du", law=-3, good=10, flag="spared_gou"),
               O("Hand him to Constable Du for judgement", law=10, flag="judged_gou"),
               O("Break his sword hand so he never raids again", law=2, good=-12, flag="maimed_gou")),
    (7, 3): Ch("Your pill cracked a little at the edge, and Elder Hua didn't notice.",
               O("Point out the crack yourself", law=6, good=2),
               O("Say nothing. A pass is a pass.", law=-4),
               O("Swap it for a spare from Zhao Kang's tray", law=-8, good=-4, xp=40)),
    (8, 5): Ch("The dropped mask names its owner, a Qingshi fishmonger. The constable hasn't seen it.",
               O("Take it to Constable Du", law=8),
               O("Warn the fishmonger first; maybe he was forced", law=-4, good=6),
               O("Keep it, and make the fishmonger work for you", law=-4, good=-8, items={"spirit_stone": 2})),
    (9, 5): Ch("One of the rogues who woke the guardians is pinned under fallen stone, begging.",
               O("Free him and send him out", law=-2, good=10),
               O("Free him, and tie him up for the wardens", law=8),
               O("Leave him for the guardians", good=-12)),
    (10, 7): Ch("The grotto's prize token is in your pocket. By rights it's Zhao Kang's.",
                O("Give him the token", law=2, good=6),
                O("Hand it to the elders to decide", law=6),
                O("Keep it", law=-2, good=-6, items={"spirit_stone": 2})),
    # ---------------------------------------------------------------- volume II
    (13, 4): Ch("Among Gu's letters: names of disciples who took Blood Moon silver once, then refused it.",
                O("Give every letter to the Sect Master", law=10),
                O("Burn the names of the ones who refused", law=-8, good=8),
                O("Keep the letters. Leverage is useful.", law=-4, good=-10)),
    (14, 5): Ch("The three inner disciples who ambushed you are nursing bruises, afraid you'll report them.",
                O("Forgive them", law=-4, good=8),
                O("Report them to the Law Hall", law=8),
                O("Humiliate them in front of the inner court", good=-8)),
    (15, 7): Ch("One pill is left over. A tenth disciple, too proud to admit his red eyes, hides at the cliff.",
                O("Give it to him, quietly", law=-2, good=8),
                O("Report him so the Medicine Hall can treat him", law=8),
                O("Sell it to him", good=-8, items={"spirit_stone": 2})),
    (16, 8): Ch("The dug-up leash-stones would fetch a fortune from any beast-tamer, and leash beasts again.",
                O("Smash them", good=6),
                O("Give them to the sect to study", law=8),
                O("Sell them to a beast-tamer", good=-10, items={"spirit_stone": 3})),
    (17, 7): Ch("A water-seller at the well is charging ten times the price to the families who carried water all night.",
                O("Make him sell at a fair price", law=-4, good=6),
                O("Report him to the magistrate", law=8),
                O("Take a cut of his profits", good=-10, items={"spirit_stone": 2})),
    (18, 4): Ch("One rogue, caught with a sack of the shrine's lotus tiles, is barely more than a boy.",
                O("Let him go with a warning", law=-4, good=6),
                O("Hand him to the sect", law=8),
                O("Make him carry the tiles back, then beat him", good=-8)),
    (19, 1): Ch("Merchant Jin begs you to keep his guild's part in the night carts quiet.",
                O("Promise silence if he testifies", law=4, good=4, flag="jin_testified"),
                O("Tell him the magistrate will hear everything", law=10),
                O("Charge him for your silence", law=-6, good=-10, items={"spirit_stone": 3})),
    (20, 8): Ch("Qian's empty account in your name can draw on the treasury for the descent. Nobody would check.",
                O("Take only what's allotted", law=8),
                O("Draw extra for the town's wounded", law=-6, good=6),
                O("Draw extra for yourself", good=-8, items={"medicine": 2})),
    # ---------------------------------------------------------------- volume III
    (23, 3): Ch("The envoys demand that someone be punished for the broken chest before they leave.",
                O("Stand surety for the sect yourself", law=-2, good=6),
                O("Insist on a proper Law Hall inquiry", law=8),
                O("Point at an Iron Scale servant to end it quickly", law=-6, good=-10)),
    (24, 7): Ch("Ruan Jingtao, humiliated by the loss, stands alone among the banners.",
                O("Go and offer him your hand", good=8),
                O("Leave him to his own sect's customs", law=6),
                O("Mock the Iron Scale where he can hear", good=-8)),
    (25, 5): Ch("A captured raider offers the camp's cache in exchange for his freedom.",
                O("Agree, and keep your word", law=4, good=4),
                O("Refuse any deal with raiders", law=8, good=-2),
                O("Agree, then hand him in anyway", law=-6, good=-8, items={"spirit_stone": 2})),
    (26, 6): Ch("The stone librarian won't let one slip leave: a forbidden technique it has guarded for centuries.",
                O("Leave it with its guardian", law=6),
                O("Distract the librarian and take it for Elder Bai", law=-4, good=2, xp=40),
                O("Take it for yourself", law=-6, good=-6, xp=80)),
    (27, 6): Ch("The pale poisoner lies beaten among the graves, offering his employer's name for his life.",
                O("Let him go for the name", law=-6, good=2, xp=40),
                O("Hand him to the four sects' tribunal", law=10),
                O("Kill him before he can lie to you", good=-12)),
    (28, 2): Ch("Xiao Man asks you not to tell anyone her brother still counts bars at night.",
                O("Keep it between the three of you", law=-4, good=4, att={"xiao_shi": 1}),
                O("Put his name on Elder Hua's list", law=8),
                O("Tell him to toughen up", good=-10, att={"xiao_shi": -1})),
    (29, 3): Ch("The children of the rim have names now, but nowhere to live. The sect has no rule for them.",
                O("Petition the Sect Master to take them in", law=6, good=6),
                O("Take them down to Qingshi yourself, tonight", law=-6, good=8),
                O("Leave them. They're not your problem.", good=-10)),
    (30, 5): Ch("One Blood Moon scout survived the fall from the stair. He offers what he knows for his life.",
                O("Heal him and let him go", law=-4, good=8),
                O("Bring him to the Law Hall", law=8),
                O("Push him off again", good=-15)),
    # ---------------------------------------------------------------- volume IV
    (32, 6): Ch("A Blood Guard slips from the jade bridge and clings to the edge by his fingertips.",
                O("Pull him up", good=10),
                O("Pull him up in chains, for questioning", law=8, good=2),
                O("Step on his fingers", good=-15)),
    (33, 5): Ch("Jin asks, very quietly, whether the sect could forget his old part in the night carts.",
                O("Forgive him. He's paid.", law=-4, good=6),
                O("The Law Hall remembers everything", law=8),
                O("Name a price for forgetting", good=-8, items={"spirit_stone": 3})),
    (34, 7): Ch("Liu Er begs you to teach him a sword form tonight, before his mother finds out.",
                O("Teach him, then walk him home", law=-4, good=4),
                O("Tell him to ask his mother first", law=6, good=2),
                O("Laugh at him", good=-6)),
    (35, 4): Ch("A fog-struck wolf pup follows you, remembering nothing, not even to be afraid.",
                O("Carry it to the hermit", good=6),
                O("Give it to the sect's beast pens", law=6),
                O("Sell it", good=-6, items={"spirit_stone": 2})),
    (36, 5): Ch("Two hundred spirit stones from the Zhao clan. Steward Qian asks how to spend them.",
                O("Medicine for Qingshi", good=8),
                O("Into the treasury ledger, by the rules", law=8),
                O("A little for yourself first", law=-4, good=-6, items={"spirit_stone": 3})),
    (37, 3): Ch("The Rust Monk's acolytes lie beaten: villagers he twisted. Slowly, they could still be healed.",
                O("Take them to Elder Hua", good=10),
                O("Imprison them until the war is over", law=8),
                O("Cut them down. It's quicker.", good=-12)),
    (38, 1): Ch("The palace sentinels will reform by morning. You could shatter their cores so they never do.",
                O("Leave them be", good=4),
                O("Ask Qing Luan's leave first", law=6),
                O("Shatter the cores", law=-6, good=-4, xp=50)),
    (39, 5): Ch("The climber you caught is a Blood Moon deserter who wanted food, not the formation.",
                O("Feed him and let him go", law=-4, good=10),
                O("Hold him for the Law Hall", law=8),
                O("Throw him back down the mountain", good=-12)),
    (40, 4): Ch("Elder Mo's last order was to wake him if the runes flickered. They are flickering, a little.",
                O("Wake him, as ordered", law=8),
                O("Let him sleep and watch the runes yourself", law=-4, good=6),
                O("Fix the runes yourself and take the credit", law=-6, good=-4, xp=50)),
    # ---------------------------------------------------------------- volume V
    (42, 1): Ch("Gu Hanshan, in chains, asks for water. The guards' orders: nothing until the trial.",
                O("Give him water", law=-6, good=8, flag="gave_gu_water"),
                O("Follow the order", law=8),
                O("Pour it out in front of him", good=-10)),
    (43, 6): Ch("Wei Tong asks you never to tell anyone what his heart demon looked like.",
                O("Promise", law=-2, good=6),
                O("Tell Elder Hua, so she can help him", law=6, good=2),
                O("Laugh about it", good=-8, att={"senior_wei": -1})),
    (44, 6): Ch("Steward Qian refused the bun budget. The treasury would never notice a few coppers.",
                O("Pay from your own purse", good=8),
                O("File a proper request", law=8),
                O("Take it from the treasury", law=-10, good=2)),
    (45, 3): Ch("Liu Er, listening at the well, asks you to put in a word with the sect for spring.",
                O("Promise to vouch for him", good=6),
                O("Tell him the gate is the same for everyone", law=8),
                O("Ask what it's worth to him", law=-2, good=-8, items={"spirit_stone": 1})),
    (45, 6): Ch("Little Mei still wears the pendant Keeper Hong gave her. It is a Blood Moon token.",
                O("Let her keep it, and say nothing", law=-4, good=6),
                O("Take it to the Law Hall", law=8),
                O("Take it from her and sell it", good=-8, items={"spirit_stone": 2})),
    (46, 3): Ch("The Lotus ruins' pond is your family's. The Azure Cloud wants it registered as sect land.",
                O("Share it with both sects", good=6),
                O("Register it properly", law=8),
                O("Claim it for yourself alone", law=-6, good=-8)),
    (47, 3): Ch("The ash letters threaten the eighth village unless the heir comes alone.",
                O("Go alone, as asked", law=-6, good=6),
                O("Tell the Sect Master everything", law=8),
                O("Send a decoy in your robes", law=-2, good=-8)),
    (48, 2): Ch("Gu Hanshan offers what he knows of the Mirror in exchange for a softer cell.",
                O("Grant it. Information saves lives.", law=-4, good=4, flag="gu_softer_cell"),
                O("Promise nothing, and listen", law=4),
                O("Threaten him instead", good=-8)),
    (49, 9): Ch("Before they burn, you see Luo Hui's letters name the villages that paid him. Some paid in children.",
                O("Let them burn, as the villages ask", law=-4, good=6),
                O("Keep a copy for the Law Hall", law=8),
                O("Copy the names, and make those villages pay you", good=-15, items={"spirit_stone": 4})),
    (50, 4): Ch("In Elder Mo's room: his savings, and a note. 'For the orphans.'",
                O("Give it to the orphans yourself", good=8),
                O("Give it to the treasury to distribute", law=8),
                O("Keep it. He'd want you strong.", good=-8, items={"spirit_stone": 3})),
    # ---------------------------------------------------------------- volume VI
    (51, 2): Ch("A void creature, cornered, is only trying to go home through the rift.",
                O("Let it pass", law=-2, good=6),
                O("Kill it. Orders are orders.", law=6, good=-2),
                O("Trap it and sell it", good=-8, items={"void_shard": 2})),
    (52, 5): Ch("Among the faces in the fold: the Blood Guard who once beat you. He's lost, pleading.",
                O("Pull him out", good=10),
                O("Pull him out, in chains", law=8, good=2),
                O("Leave him to the nothing", good=-12)),
    (53, 8): Ch("The Rust Monk kneels in the rain and asks to atone rather than die.",
                O("Accept his penance", law=-2, good=10, flag="rust_monk_penance"),
                O("Deliver him to the alliance's court", law=10),
                O("Refuse him", good=-10)),
    (54, 7): Ch("The Abbess asks if the Azure Cloud would shelter her nuns for good, against custom.",
                O("Yes. Custom be damned.", law=-6, good=6),
                O("Put it to the elders' council", law=8),
                O("Only if the Moon-Well pays", good=-8, items={"spirit_stone": 3})),
    (55, 4): Ch("The dam will flood a demonic cultivator's hideout downstream. His family is inside.",
                O("Warn them first", law=-4, good=10),
                O("Follow the plan exactly", law=8, good=-4),
                O("Let it flood without warning", good=-15)),
    (56, 3): Ch("The old woman who brought the laced buns is only a hired carrier. She's terrified.",
                O("Let her go home", law=-4, good=6),
                O("Give her to the constable", law=8),
                O("Use her as bait for Ninefold", good=-10)),
    (57, 2): Ch("One of the three suspects must be Madam Ninefold. Arresting all three would be safest.",
                O("Investigate until you're sure", law=4, good=4),
                O("Arrest all three", law=6, good=-6),
                O("Threaten them until one breaks", law=-2, good=-8)),
    (58, 7): Ch("The Iron Scale needs supplies, but your sect's winter stores are thin.",
                O("Send them half our stores", law=-2, good=8),
                O("Send what the elders approved", law=8),
                O("Send nothing. Charity starts at home.", good=-8)),
    (59, 7): Ch("Ruan Hai offers you the Iron Scale's sacred manual in thanks.",
                O("Decline it", good=6),
                O("Accept it formally, for the sect", law=8),
                O("Accept it for yourself", law=-4, good=-4, xp=80)),
    (60, 3): Ch("Qing Luan offers to show you the Patriarch's path through the peak: a secret of her order.",
                O("Refuse. Keep her oath intact.", law=8),
                O("Accept. It may save lives.", law=-6, good=6),
                O("Insist. You're owed it.", good=-6)),
    # ---------------------------------------------------------------- volume VII
    (61, 2): Ch("The purple thread is still twitching. Elder Hua wants it studied; Han Xue wants it burned.",
                O("Burn it", good=4),
                O("Seal it for Elder Hua", law=8),
                O("Keep a piece, secretly", law=-6, good=-6, xp=60)),
    (62, 5): Ch("Thunder Peak's forge-masters offer a banned tempering. Faster, and more dangerous.",
                O("Refuse", law=6),
                O("Accept, but only on yourself", law=-6, xp=60),
                O("Accept, and have the juniors test it first", good=-12, xp=80)),
    (63, 3): Ch("Old Chen's son wants the hollowed kept locked up until they are cured.",
                O("Refuse. They heal among neighbours.", law=-4, good=8),
                O("Agree, as the magistrate ordered", law=8),
                O("Lock them up, and charge their families", good=-10, items={"spirit_stone": 2})),
    (64, 3): Ch("Brother Hollow wears Tan's body. Tan may still be in there, somewhere.",
                O("Try to save Tan", good=10),
                O("End it cleanly", law=4),
                O("Leave Tan hollow, as a lure", good=-10)),
    (65, 3): Ch("The hermit's plan means drowning a bamboo grove where spirit foxes den.",
                O("Move the foxes first, whatever it costs", law=-2, good=8),
                O("Follow the plan", law=6, good=-4),
                O("Drown them all", good=-12)),
    (66, 1): Ch("Merchant Jin was offered the Butcher's contract. He wants it burned before anyone sees his name.",
                O("Burn it", law=-4, good=4),
                O("Take it to the magistrate as evidence", law=10),
                O("Keep it, to hold over Jin", good=-8)),
    (67, 3): Ch("Iron-Fang confesses that years ago he sold men to the Butcher.",
                O("Forgive him", law=-4, good=8, att={"bandit_tie": 1}),
                O("He must face the magistrate after the war", law=10),
                O("Hold it over him, so he obeys you", good=-10, att={"bandit_tie": -1})),
    (68, 3): Ch("Nineteen frozen cultivators. Thawing risks their lives; leaving them risks the Butcher using them.",
                O("Thaw them slowly, whatever it costs", good=8),
                O("Wait for Elder Hua's order", law=8),
                O("Destroy them. It's safer.", good=-15)),
    (69, 8): Ch("The Butcher's ledger names every buyer. Some are respected elders of other sects.",
                O("Publish every name", law=-4, good=4),
                O("Hand it to the alliance court", law=10),
                O("Blackmail the elders", good=-12, items={"spirit_stone": 5})),
    (70, 5): Ch("The humming forge stone was chipped from Thunder Peak's sacred anvil without their elders' leave.",
                O("Return it quietly", law=6, good=2),
                O("Keep it. It was a gift.", law=-4),
                O("Sell it", good=-6, items={"spirit_stone": 3})),
    # ---------------------------------------------------------------- volume VIII
    (71, 5): Ch("A disciple confesses he hates carrying anyone but himself.",
                O("Tell him that's honest, and it's fine", law=-3, good=3),
                O("Remind him of the sect's oath", law=6),
                O("Tell him the weak deserve no carrying", good=-10)),
    (72, 4): Ch("The two brawling sects look to you to say who enters the main hall first.",
                O("The smallest sect first", law=-3, good=6),
                O("By seniority, as tradition says", law=8),
                O("Whoever pays the most", law=-2, good=-8, items={"spirit_stone": 4})),
    (73, 3): Ch("The rogues you beat were disciples once, expelled for being poor.",
                O("Give them work and a second chance", law=-4, good=10),
                O("Hand them to the constable", law=8),
                O("Recruit them as your own enforcers", law=-6, good=-8)),
    (74, 4): Ch("The drunk brawlers sober up. The side that started it is your oldest ally.",
                O("Punish the side that started it", law=8),
                O("Break it up and punish nobody", law=-3, good=5),
                O("Side with your allies regardless", law=-4, good=-4)),
    (75, 1): Ch("Afterwards, a small sect's master asks you privately to argue for his seat.",
                O("Promise to argue fairly for everyone", law=6),
                O("Argue for him; small sects need a voice", law=-2, good=6),
                O("Ask what it's worth to him", good=-8, items={"spirit_stone": 3})),
    (76, 4): Ch("Silk set the magistrate and the constable at each other's throats. The town wants one gone.",
                O("Reconcile them, whatever it takes", good=8),
                O("Let the law decide", law=8),
                O("Back whoever owes you more", good=-8)),
    (77, 2): Ch("The feast wine is threaded with silk. Announcing it means panic; silence means someone may drink.",
                O("Announce it at once", law=-2, good=6),
                O("Swap the wine quietly, as protocol says", law=6),
                O("Let the enemy's guests drink it", good=-15)),
    (78, 5): Ch("Ancestor Zhao asks you to hide his failing health from his clan.",
                O("Keep his secret", law=-2, good=4),
                O("Tell Zhao Kang. He has a right to know.", law=4, good=4),
                O("Use it for the alliance's advantage", good=-10)),
    (79, 3): Ch("Copying the sutra for everyone breaks the Pagoda's rule against sharing its texts.",
                O("Share them anyway", law=-8, good=8),
                O("Ask Elder Bai for an exception", law=6, good=2),
                O("Sell the copies", good=-8, items={"spirit_stone": 4})),
    (80, 6): Ch("On the bone field: Blood Moon survivors, old men and women, begging for passage.",
                O("Take them in", good=10),
                O("Register them for the alliance's judgement", law=8),
                O("Leave them", good=-12)),
    # ---------------------------------------------------------------- volume IX
    (81, 6): Ch("The richest seam of tribulation jade runs under a village shrine on the slope.",
                O("Leave the shrine alone", law=-2, good=6),
                O("Buy the land properly", law=6),
                O("Dig it up anyway", good=-10, items={"tribulation_jade": 1})),
    (82, 7): Ch("To fool Xue Chen's shadows, you must lie to your own disciples too.",
                O("Lie, and apologise afterwards", law=-4, good=2),
                O("Tell them the truth and trust them", law=4, good=4),
                O("Use them as unknowing bait", good=-10)),
    (83, 8): Ch("Stealing the shadow back needs a relic from a Willow Creek grave.",
                O("Ask the villagers' permission", law=6, good=4),
                O("Borrow it at night and return it after", law=-6),
                O("Take it and keep it", law=-4, good=-8)),
    (84, 1): Ch("Even Qian's tears won't cover nine lightning rods. The rest must come from somewhere.",
                O("Cut your own allowance first", good=8),
                O("Levy the town, as the charter allows", law=8, good=-4),
                O("Squeeze Merchant Jin until he pays", law=-4, good=-6, items={"spirit_stone": 3})),
    (85, 6): Ch("The disciples watched you nearly die in the lightning. They're frightened.",
                O("Tell them the truth: it will be worse", law=4, good=2),
                O("Tell them it didn't hurt", law=-4, good=4),
                O("Tell them fear is for the weak", good=-8)),
    (86, 7): Ch("Merchant Jin wants to forgive the town's debts in your name. It's a fortune.",
                O("Forgive them in his name, not yours", law=2, good=6),
                O("Let the debts stand. Contracts are contracts.", law=8, good=-4),
                O("Take the credit, and a share", good=-8, items={"spirit_stone": 4})),
    (87, 3): Ch("A sliver of Han Xue's shadow is left, cold and humming. It would feed a cultivator's soul.",
                O("Let it melt away", good=6),
                O("Give it to the hermit to seal", law=6),
                O("Absorb it", good=-12, xp=100)),
    (88, 2): Ch("Zhao Kang's clan offers you a fortune to make sure he loses the wager.",
                O("Refuse", law=4, good=4),
                O("Refuse, and tell Zhao Kang", good=6),
                O("Accept", law=-6, good=-10, items={"spirit_stone": 5})),
    (89, 5): Ch("Stargazers could warn the towns early, but the alliance fears a panic.",
                O("Warn the towns", law=-6, good=8),
                O("Follow the alliance's decision", law=8),
                O("Sell the warning to the rich", good=-12, items={"spirit_stone": 4})),
    (90, 1): Ch("The Stair's sentinels demand an oath: never to return to the mortal world.",
                O("Refuse the oath", law=-6, good=6),
                O("Swear it honestly", law=8),
                O("Swear it, and mean none of it", law=-8, good=-4)),
    # ---------------------------------------------------------------- volume X
    (91, 3): Ch("There's medicine for ten thousand, not eleven. Who goes without?",
                O("The sect's own disciples", good=8),
                O("Whoever enlisted last", law=8),
                O("The bandits", law=2, good=-8)),
    (92, 6): Ch("Some of Iron-Fang's men still owe old blood debts to Qingshi families.",
                O("Settle their debts from your own purse", good=8),
                O("Have the magistrate record them for after the war", law=8),
                O("Tell the families to take it out of their hides", good=-10)),
    (93, 6): Ch("Before the last letter burned, you read one line: the name of Gu Lan's poisoner, alive in another sect.",
                O("Let it lie. Gu has forgiven.", law=-2, good=6),
                O("Send it to that sect's Law Hall", law=8),
                O("Hunt him down yourself", law=-8, good=-6)),
    (94, 6): Ch("Xue Chen's captives are tied at the river. Freeing them now weakens the gate.",
                O("Free them now", law=-4, good=10),
                O("Hold the gate, as ordered", law=8, good=-4),
                O("Use the captives as a shield", good=-15)),
    (95, 4): Ch("Xue Chen asks whether you would spare him, if he gave up his rung.",
                O("Yes. I would.", good=10),
                O("The alliance court would decide", law=8),
                O("No. Never.", good=-6)),
    (96, 8): Ch("Steward Qian's last account shows a surplus nobody knows about.",
                O("Give it to the war widows", good=8),
                O("Return it to the treasury", law=8),
                O("Keep it for after the war", good=-8, items={"spirit_stone": 4})),
    (97, 3): Ch("Ye Wuming's children want to fight at the front. The youngest is barely grown.",
                O("Send the youngest to the rear", law=2, good=6),
                O("Let each of them choose", law=-6),
                O("Put them all at the front", good=-12)),
    (98, 7): Ch("The alliance wants Xue Chen's body hung at the black gate, as a warning.",
                O("Bury him at the rim, with the lotus", law=-4, good=8),
                O("Give him to the alliance", law=8),
                O("Hang him yourself", good=-10)),
    (99, 4): Ch("There's not enough of the treasury's best for everyone who marches.",
                O("Arm the weakest first", good=8),
                O("Arm by rank", law=8),
                O("Take the best for yourself", good=-8, items={"spirit_pill": 1})),
}

LEGACY = {
    (7, 3): Ch("You peeked at the jade slips in the pavilion. Elder Bai hasn't asked.",
               O("Confess that you read them", law=6, good=2),
               O("Say nothing. No harm done.", law=-4),
               O("Blame the wind in the pavilion", law=-4, good=-4)),
    (30, 0): Ch("Widow Liu has nothing left for her son's memorial.",
                O("Give her your whole allowance", good=8),
                O("Promise the sect will keep searching for him", law=4, good=2),
                O("You've done enough. Leave.", good=-6)),
    (45, 3): Ch("Lu Ping's winnings came from betting on you. Gambling is forbidden in the sect.",
                O("Tell him to give them to the Medicine Hall", law=4, good=4),
                O("Report him to the Law Hall", law=8, good=-3),
                O("Take a cut", law=-4, good=-6, items={"spirit_stone": 1})),
    (60, 0): Ch("The captured acolytes wait on your word.",
                O("Send them home, and trust them", law=-2, good=8),
                O("Bring them to the sect's Law Hall", law=8),
                O("Leave them to the Abyss", good=-12)),
    (68, 2): Ch("Iron-Fang kneels at the temple. The town wants blood.",
                O("Spare him, as you promised", law=2, good=8, att={"bandit_tie": 1}),
                O("Spare him, and bind him to the magistrate's justice", law=8),
                O("Spare him, and make him your servant", law=-4, good=-8, att={"bandit_tie": -1})),
    (88, 2): Ch("Gu Hanshan asks you for nothing. You could give him something anyway.",
                O("A cup of tea", good=5),
                O("Nothing. He's a traitor.", law=5),
                O("Spit at his feet", good=-8)),
    (94, 3): Ch("In the last cage, a Blood Guard begs to be freed with the rest.",
                O("Free him", law=-4, good=8),
                O("Leave him for the alliance's judges", law=8),
                O("Leave him to rot", good=-10)),
}
