"""All cutscenes. Shot tuples are (yaw degrees, distance m, height m) of the
camera around the shot's marker, interpolated from ``frm`` to ``to``."""

from .dsl import P, N, cin, actor, foe, shot
from .npcs import *

CINEMATICS = {
    # ================================================================ chapter 1
    "ch01_intro": cin("sect", title="Chapter One", subtitle="The Outer Disciple", music="sect", actors=[
        actor(P, "PlayerSpawn", "idle", "SectGate"),
        actor(LU, "GateGuardPost", "idle", "PlayerSpawn"),
        actor(MO, "HallSteps", "idle", "SectGate"),
        actor(YUN, "MainHall", "meditate"),
    ], shots=[
        shot("CliffEdge", (-60, 30, 12), (-20, 22, 8), N,
             "Three hundred years ago, the Azure Cloud and the Verdant Lotus sealed a monster beneath the earth, and the world forgot."),
        shot("FormationArray", (40, 18, 10), (80, 12, 5), N,
             "Only the Azure Cloud Sect remembers. It keeps its watch on this mountain, above the sea of clouds."),
        shot("MainHall", (0, 20, 6), (15, 14, 4), N,
             "Every spring, its gate opens to those with the talent and stubbornness to climb nine thousand steps."),
        shot("PlayerSpawn", (160, 9, 2.5), (200, 5, 1.8), N,
             "This spring, an orphan with nothing but a jade pendant reached the top."),
        shot("PlayerSpawn", (-20, 4, 1.8), (10, 3, 1.7), P,
             "The Azure Cloud Sect. I made it, Mother."),
        shot("SectGate", (30, 14, 5), (0, 10, 3), None, None, dur=3.5),
    ]),
    # ================================================================ chapter 2
    "ch02_intro": cin("bamboo_forest", title="Chapter Two", subtitle="Whispers in the Bamboo", music="forest", actors=[
        actor(P, "TeleportArray", "idle", "PlayerSpawn"),
        actor(WEI, "PlayerSpawn", "talk", "TeleportArray"),
    ], shots=[
        shot("TeleportArray", (90, 10, 6), (130, 6, 2.5), N,
             "The teleport array flares, and the mountain is gone. In its place, bamboo, green and endless, whispering in the wind."),
        shot("PlayerSpawn", (-30, 6, 2), (10, 4, 1.8), WEI,
             "First mission outside the walls! Don't wander off, don't eat red mushrooms, and don't pet anything with more than four eyes."),
        shot("ForestPath", (0, 16, 8), (40, 10, 4), N,
             "The Whispering Bamboo Forest. Spirit herbs grow here, and spirit wolves hunt here. Usually they leave cultivators alone."),
        shot("WolfDen", (200, 14, 6), (170, 9, 3), N,
             "Usually."),
    ]),
    # ================================================================ chapter 3
    "ch03_intro": cin("qingshi_town", title="Chapter Three", subtitle="Shadows over Qingshi", music="town", actors=[
        actor(P, "PlayerSpawn", "idle", "TownGate"),
        actor(HAN, "TeleportArray", "idle", "TownGate"),
        actor(DU, "TownGate", "idle", "PlayerSpawn"),
        actor(LIU, "Well", "idle"),
        actor(HONG, "Temple", "salute"),
    ], shots=[
        shot("TownGate", (180, 24, 10), (160, 16, 6), N,
             "Qingshi Town. Rice fields, a river, a market, and a temple where the kindly keeper buries the dead."),
        shot("MarketSquare", (30, 14, 6), (70, 10, 4), N,
             "Every new moon, somebody vanishes. Every morning after, the town pretends not to notice."),
        shot("Well", (0, 6, 2), (30, 4.5, 1.8), N,
             "Almost everybody."),
        shot("Temple", (-40, 8, 3), (-10, 5, 2), HONG,
             "Visitors from the mountain! How wonderful. May the ancestors bless your journey, young immortals."),
        shot("PlayerSpawn", (160, 6, 2), (200, 4, 1.8), HAN,
             "Eyes open, {junior}. Towns that smile this hard are usually hiding something."),
    ]),
    "ch03_reveal": cin("qingshi_town", music="battle", actors=[
        actor(P, "MainStreet", "idle", "Temple"),
        actor(HAN, "MarketSquare", "cast", "Temple"),
        actor(HONG, "Temple", "cast", "MainStreet"),
    ], enemies=[foe("demon_cultivator", "BackAlley", 3)], shots=[
        shot("Temple", (20, 5, 2), (0, 3.5, 1.8), HONG,
             "Clever children. Too clever. Keeper Hong was such a comfortable face. I wore it for eleven years."),
        shot("Temple", (-60, 7, 3), (-100, 5, 2.2), N,
             "The old man's skin splits like a husk. Beneath it: black and crimson robes, and eyes the colour of blood."),
        shot("Temple", (0, 4, 2), (15, 3, 1.9), HONG,
             "Deacon Hong Lie of the Blood Moon. The Patriarch stirs, lotus-bearer, and he dreams of you."),
        shot("MarketSquare", (90, 12, 5), (60, 9, 3), HAN,
             "Acolytes in the alley! {player}, he's running for the graves!"),
    ]),
    # ================================================================ chapter 4
    "ch04_intro": cin("bamboo_forest", title="Chapter Eleven", subtitle="Ruins of the Forgotten Sect", music="forest", actors=[
        actor(P, "ForestPath", "idle", "RuinsGate"),
        actor(LAN, "HermitHut", "meditate"),
    ], shots=[
        shot("ForestPath", (0, 12, 5), (30, 8, 3), N,
             "North of the wolf dens, where even the bamboo grows quiet, the forest hides something older than any sect alive."),
        shot("RuinsGate", (180, 18, 7), (150, 11, 4), N,
             "The Verdant Lotus Sect. Once it stood beside the Azure Cloud as an equal. Now its name is a footnote."),
        shot("AncientShrine", (60, 10, 4), (100, 7, 3), N,
             "Its ruins keep their secrets well. But stones cannot be cut out of a book."),
        shot("HermitHut", (-30, 8, 3), (0, 5, 2), LAN,
             "So. The lotus comes home at last. I had hoped to be dead before it did."),
    ]),
    "ch04_lotus": cin("bamboo_forest", music="sorrow", actors=[
        actor(LAN, "HermitHut", "talk", "Clearing"),
        actor(P, "Clearing", "idle", "HermitHut"),
    ], shots=[
        shot("HermitHut", (10, 5, 2), (-10, 4, 1.8), LAN,
             "Three hundred years ago the Blood Moon Patriarch drowned three kingdoms in blood, reaching for the heavens."),
        shot("RuinsInner", (0, 20, 10), (60, 14, 6), LAN,
             "Our sect master and your founder bound him beneath the Abyss. The seal needed two keys, and a price."),
        shot("AncientShrine", (120, 9, 4), (90, 6, 2.5), LAN,
             "The Verdant Lotus paid it. Every elder gave their life to the seal. The Patriarch's servants hunted the rest of us."),
        shot("SpiritSpring", (-90, 8, 3), (-60, 5, 2), LAN,
             "One disciple fled with the Lotus Key and a baby girl. Her line hid among mortals for three centuries."),
        shot("Clearing", (200, 4, 1.8), (170, 3.5, 1.7), LAN,
             "Your mother's pendant, child, is that key. And you are the last of the Verdant Lotus."),
    ]),
    # ================================================================ chapter 5
    "ch05_intro": cin("sect", title="Chapter Twelve", subtitle="The Inner Sect Tournament", music="sect", actors=[
        actor(YUN, "MainHall", "idle", "FormationArray"),
        actor(MO, "HallSteps", "talk", "FormationArray"),
        actor(GU, "ScholarRock", "idle", "FormationArray"),
        actor(ZHAO, "WeaponRack", "salute", "FormationArray"),
        actor(WEI, "TrainingGround", "attack", "WeaponRack"),
        actor(P, "FormationArray", "salute", "MainHall"),
    ], shots=[
        shot("FormationArray", (0, 28, 14), (45, 20, 9), N,
             "Once every three years, the Azure Cloud Sect raises its banners for the Inner Sect Tournament."),
        shot("HallSteps", (20, 7, 2.5), (-10, 5, 2), MO,
             "Disciples of the Azure Cloud! Fight hard, fight fair, and whoever breaks the formation tiles pays for them."),
        shot("MainHall", (0, 10, 4), (10, 7, 3), YUN,
             "The victor will stand beside me and learn the secrets of the Azure Eye. Show heaven what this sect is made of."),
        shot("ScholarRock", (-50, 6, 2), (-30, 4.5, 1.9), N,
             "In the crowd, not everyone is watching the fighters."),
        shot("FormationArray", (160, 6, 2), (200, 4, 1.8), P,
             "Nine to one odds. Lu Ping had better not be wrong about me."),
    ]),
    "ch05_traitor": cin("sect", music="battle", actors=[
        actor(GU, "Pagoda", "cast", "PlumGarden"),
        actor(P, "PlumGarden", "idle", "Pagoda"),
        actor(YUN, "StoneBridge", "cast", "Pagoda"),
    ], enemies=[foe("demon_cultivator", "Pagoda", 2)], shots=[
        shot("Pagoda", (180, 16, 8), (150, 10, 4), N,
             "The pagoda doors hang open. Scrolls lie scattered like fallen leaves. And at the heart of the mess stands the Law Hall Elder."),
        shot("Pagoda", (0, 5, 2), (20, 3.5, 1.8), GU,
             "You were supposed to be watching the final, disciple. Everyone was supposed to be watching the final."),
        shot("PlumGarden", (-30, 5, 2), (0, 3.5, 1.8), P,
             "Elder Gu. The token, the missions, the pages, the pills. It was you. All of it."),
        shot("Pagoda", (40, 4, 2), (60, 3, 1.8), GU,
             "I did what a father does. Heaven took my daughter. The Blood Moon offered her back. You would have done the same."),
        shot("StoneBridge", (90, 10, 4), (60, 7, 2.5), YUN,
             "Gu Hanshan! Put down the diagram and kneel, or I will strike you down where you stand."),
        shot("Pagoda", (-90, 12, 5), (-120, 8, 3), GU,
             "Forty years of loyalty, Sect Master, and you never once asked why I stopped smiling. Kill them."),
    ]),
    # ================================================================ chapter 6
    "ch06_intro": cin("blood_abyss", title="Chapter Twenty-One", subtitle="Descent into the Blood Moon", music="abyss", actors=[
        actor(P, "PlayerSpawn", "idle", "CanyonEntrance"),
        actor(HAN, "TeleportArray", "idle", "CanyonEntrance"),
        actor(YE, "CanyonEntrance", "idle", "PlayerSpawn"),
    ], shots=[
        shot("PlayerSpawn", (0, 30, 16), (40, 22, 10), N,
             "The Blood Moon Abyss. A wound in the earth, three hundred years deep, where the moon is always red."),
        shot("BoneField", (60, 20, 8), (100, 14, 5), N,
             "Once a kingdom stood here. Its people were the Patriarch's first harvest."),
        shot("TeleportArray", (-30, 5, 2), (0, 4, 1.8), HAN,
             "It stinks of old blood. Stay behind me. No. Stay beside me. Where I can see you."),
        shot("CanyonEntrance", (200, 7, 2.5), (170, 5, 2), YE,
             "Step where I step. Breathe when I breathe. Welcome to the place I was born."),
    ]),
    "ch06_altar": cin("blood_abyss", music="boss", actors=[
        actor(GU, "AltarOfBlood", "cast", "PatriarchThrone"),
        actor(XUEMEI, "FortressCourt", "idle", "AltarOfBlood"),
        actor(P, "PrisonCages", "idle", "AltarOfBlood"),
        actor(YE, "BloodPools", "idle", "AltarOfBlood"),
    ], shots=[
        shot("AltarOfBlood", (0, 20, 10), (40, 14, 6), N,
             "Blood from the broken obelisks still trickles along the channels, up the dais, into the great altar."),
        shot("AltarOfBlood", (-30, 5, 2.2), (-10, 3.5, 1.9), GU,
             "The diagram is delivered, Patriarch. The Azure Eye's design is in your hands. Now keep your promise. Give me my Lan."),
        shot("PatriarchThrone", (180, 14, 3), (180, 9, 2), PATRIARCH,
             "Patience, loyal Gu. When I walk again, you will have everything you deserve. Everything."),
        shot("FortressCourt", (60, 6, 2), (30, 4.5, 1.8), XUEMEI,
             "Master, the lotus-bearer is here. The little lamb has come to the altar all by itself."),
        shot("AltarOfBlood", (120, 8, 3), (90, 5, 2), GU,
             "Disciple. You should not have come. Xue Mei, keep it alive. The Patriarch needs the body intact."),
    ]),
    # ================================================================ chapter 7
    "ch07_intro": cin("qingshi_town", title="Chapter Twenty-Two", subtitle="Siege of Qingshi", music="town", actors=[
        actor(ZHOU, "TownGate", "talk", "MainStreet"),
        actor(P, "MainStreet", "idle", "TownGate"),
        actor(ZHAO, "WatchTower", "idle", "Farmland"),
        actor(WEI, "MarketSquare", "idle", "TownGate"),
    ], enemies=[foe("bandit", "Farmland", 3), foe("demon_cultivator", "Graveyard", 3)], shots=[
        shot("Farmland", (0, 26, 12), (40, 18, 7), N,
             "The Blood Moon comes to Qingshi on the third night: demon cultivators, blood-fed wolves, and Iron-Fang's bandits beside them."),
        shot("Graveyard", (90, 16, 6), (120, 12, 4), N,
             "Their banners rise on the graveyard hill, above empty graves the town has only just refilled."),
        shot("WatchTower", (-40, 8, 4), (-10, 6, 3), ZHAO,
             "I count four hundred. Maybe five. I'd count better if they stood still."),
        shot("TownGate", (160, 7, 2.5), (190, 5, 2), ZHOU,
             "People of Qingshi! Last time, we hid. We locked our doors and let a monster feed on our children. Not this time!"),
        shot("MainStreet", (0, 6, 2), (20, 4, 1.8), P,
             "Then we hold. Every street, every house, every wall. Not one more grave."),
    ]),
    # ================================================================ chapter 8
    "ch08_intro": cin("sky_isles", title="Chapter Thirty-One", subtitle="Isles Above the Clouds", music="sky", actors=[
        actor(P, "TeleportArray", "idle", "CloudGate"),
        actor(HAN, "PlayerSpawn", "idle", "CloudGate"),
        actor(ZHAO, "JadeBridge", "idle", "PlayerSpawn"),
        actor(SAGE, "CloudGate", "salute", "PlayerSpawn"),
    ], shots=[
        shot("CloudGate", (0, 40, 20), (60, 28, 12), N,
             "Once every sixty years the clouds part, and the Celestial Sky Isles drift down within reach of mortal arrays."),
        shot("JadeBridge", (90, 20, 6), (120, 14, 4), N,
             "Here, where immortals once lived, star iron falls like rain and thunder grows in the rocks like crystal flowers."),
        shot("TeleportArray", (-30, 6, 2), (0, 4, 1.8), P,
             "Everything is floating. The whole world is floating."),
        shot("JadeBridge", (40, 6, 2), (20, 4.5, 1.8), ZHAO,
             "Please stop saying floating. Say resting on very tall air."),
        shot("TribulationPeak", (180, 30, 14), (150, 20, 10), N,
             "And at the highest point, the summit where heavenly tribulation strikes, waits the stair that climbs to heaven."),
    ]),
    # ================================================================ chapter 9
    "ch09_intro": cin("sect", title="Chapter Forty-One", subtitle="The Heart Demon", music=None, actors=[
        actor(MO, "FormationArray", "cast"),
        actor(BAI, "Pagoda", "idle", "FormationArray"),
    ], shots=[
        shot("FormationArray", (0, 26, 14), (40, 18, 9), N,
             "The Great Azure Formation stands complete: star iron pillars, thunder crystals, a web of ten thousand runes."),
        shot("FormationArray", (-60, 5, 2), (-30, 3.5, 1.8), MO,
             "Outer ring. Seventh branch. This rune turns outward. It should turn inward. Why would it turn outward?"),
        shot("FormationArray", (60, 5, 1.5), (80, 4, 1.7), MO,
             "The Law Hall archive. Thirty years of Gu's hands on every page. Oh, you fool. You poor, grieving fool."),
        shot("CliffEdge", (180, 20, 6), (200, 16, 10), N,
             "Above the sea of clouds, the moon rises, and for the first time in three hundred years, it rises red."),
    ]),
    "ch09_mirror": cin("blood_abyss", actors=[
        actor(P, "HeartMirror", "idle", "AbyssDepths"),
        actor(GU, "AbyssDepths", "idle", "HeartMirror"),
    ], shots=[
        shot("HeartMirror", (0, 12, 5), (30, 8, 3), N,
             "The water does not ripple. Your reflection rises from it, dripping darkness, wearing your face like a mask."),
        shot("HeartMirror", (-20, 4, 1.8), (0, 3, 1.7), DEMON,
             "Hello, {player}. Don't you recognise me? I'm every time you were afraid, and pretended you weren't."),
        shot("HeartMirror", (160, 4, 1.8), (180, 3, 1.7), P,
             "I know what you are. A heart demon. You feed on doubt."),
        shot("HeartMirror", (-20, 4, 1.8), (-40, 3.5, 1.7), DEMON,
             "Then I'll never go hungry. Let me in. I'll carry the key for you. Isn't it heavy? Isn't it so very heavy?"),
    ]),
    "ch09_sacrifice": cin("sect", music="sorrow", actors=[
        actor(MO, "FormationArray", "cast"),
        actor(P, "IncenseBurner", "idle", "FormationArray"),
        actor(YUN, "HallSteps", "cast", "FormationArray"),
        actor(HAN, "ScholarRock", "idle", "FormationArray"),
    ], shots=[
        shot("FormationArray", (0, 24, 12), (20, 16, 7), N,
             "The Great Azure Formation roars like a furnace, blood-red, pulling the mountain's qi downward into the dark."),
        shot("FormationArray", (-40, 5, 2), (-20, 3.5, 1.8), MO,
             "Stay back, all of you! Seven runes. I can turn seven runes. I just need something big enough to push them."),
        shot("IncenseBurner", (30, 5, 2), (10, 4, 1.8), P,
             "Elder Mo, no! Let me help, I have the Lotus Key!"),
        shot("FormationArray", (180, 5, 1.8), (160, 3.5, 1.7), MO,
             "The key is for tomorrow, {junior}. Tonight is for old men. Back straight, now. Crooked spine, crooked meridian."),
        shot("FormationArray", (0, 30, 18), (90, 40, 25), N,
             "Elder Mo Changfeng burns his core, his soul and seventy years of cultivation in a single breath. The red light turns blue."),
        shot("HallSteps", (0, 8, 3), (20, 6, 2), YUN,
             "Mo Changfeng. Elder of the Outer Court. You stubborn, stubborn old man."),
    ]),
    # ================================================================ chapter 10
    "ch10_intro": cin("blood_abyss", title="Chapter One Hundred", subtitle="Heavenly Tribulation", music="abyss", actors=[
        actor(YUN, "TeleportArray", "idle", "CanyonEntrance"),
        actor(P, "PlayerSpawn", "salute", "TeleportArray"),
        actor(HAN, "CanyonEntrance", "idle", "PlayerSpawn"),
        actor(TIE, "BoneField", "idle", "CanyonEntrance"),
        actor(GU, "ObeliskRing", "meditate"),
    ], shots=[
        shot("PlayerSpawn", (0, 30, 15), (50, 22, 10), N,
             "Under the last blood moon, the Azure Cloud Sect goes to war: elders, disciples, a bandit's army and a traitor in chains."),
        shot("TeleportArray", (0, 8, 3), (20, 6, 2.2), YUN,
             "Three hundred years ago our founders stood here and did not finish the job. We will finish it."),
        shot("TeleportArray", (20, 6, 2), (-10, 4, 1.8), YUN,
             "For Mo Changfeng. For the Verdant Lotus. For everyone this Abyss has swallowed. Azure Cloud, advance!"),
        shot("DemonGate", (180, 26, 10), (160, 18, 6), N,
             "Beyond the black gate, on a throne of fused bone, something that was once a man opens its eyes."),
    ]),
    "ch10_patriarch": cin("blood_abyss", music="boss", actors=[
        actor(PATRIARCH, "PatriarchThrone", "idle", "FortressCourt"),
        actor(P, "FortressCourt", "idle", "PatriarchThrone"),
    ], shots=[
        shot("PatriarchThrone", (0, 22, 8), (20, 14, 5), N,
             "Xue Wuji, Patriarch of the Blood Moon. Three kingdoms drowned for his ambition. Three centuries of hunger in the dark."),
        shot("PatriarchThrone", (-20, 5, 2.4), (0, 4, 2.2), PATRIARCH,
             "The last of the Verdant Lotus. Do you know how long I have waited for you? Your great-grandmother's great-grandmother escaped me."),
        shot("FortressCourt", (30, 5, 2), (10, 4, 1.8), P,
             "You broke Gu with grief. You tried to break me with fear. It didn't work."),
        shot("PatriarchThrone", (160, 6, 2.4), (180, 4.5, 2.2), PATRIARCH,
             "Then I will break you the old way. With my hands. Come, little lotus. Show me my new body."),
    ]),
    "ch10_tribulation": cin("sky_isles", music="tribulation", actors=[
        actor(P, "AscensionStair", "idle", "TribulationPeak"),
    ], shots=[
        shot("TribulationPeak", (0, 40, 22), (60, 28, 14), N,
             "Above the summit, the clouds spiral into a black eye nine miles wide. Heaven has seen you. Heaven is coming."),
        shot("AscensionStair", (180, 8, 3), (160, 6, 2), P,
             "Nine bolts. Elder Bai said nobody knows what the ninth one is. Wonderful."),
        shot("TribulationPeak", (-40, 10, 4), (-20, 7, 2.5), PATRIARCH,
             "I know, little lotus. The ninth is the heart. And I will be waiting inside it."),
    ]),
    "ch10_ascension": cin("sky_isles", music="victory", actors=[
        actor(P, "AscensionStair", "salute", "CloudGate"),
        actor(YUN, "CloudGate", "salute", "AscensionStair"),
        actor(HAN, "ImmortalGarden", "salute", "AscensionStair"),
        actor(ZHAO, "JadeBridge", "salute", "AscensionStair"),
        actor(SAGE, "StarPavilion", "idle", "AscensionStair"),
    ], shots=[
        shot("AscensionStair", (180, 10, 3), (180, 20, 10), N,
             "The Ascension Stair opens, step by step, a road of light from the summit into the clouds."),
        shot("CloudGate", (0, 8, 3), (20, 6, 2), N,
             "Below, the Sect Master bows. Han Xue raises her sword. Zhao Kang shouts something rude, and wipes his eyes."),
        shot("AscensionStair", (0, 6, 2), (20, 4, 1.8), P,
             "I'll come back. Maybe not soon. But I'll come back."),
        shot("AscensionStair", (0, 30, 20), (0, 60, 50), N,
             "And {player}, last of the Verdant Lotus, disciple of the Azure Cloud, climbs into the heavens."),
    ]),
    "ch10_epilogue": cin("sect", title="Epilogue", subtitle="Ten Thousand Years", music="sect", actors=[
        actor(YUN, "MainHall", "idle"),
        actor(WEI, "TrainingGround", "talk", "WeaponRack"),
        actor(ZHAO, "PlumGarden", "meditate"),
        actor(MAN, "LotusPond", "idle"),
        actor(SHI, "StoneBridge", "idle", "LotusPond"),
        actor(HAN, "CliffEdge", "idle"),
        actor(LAN, "Pagoda", "talk", "PlumGarden"),
    ], shots=[
        shot("FormationArray", (0, 26, 14), (40, 18, 8), N,
             "The Great Azure Formation holds. The Blood Moon Abyss is sealed, and this time, the seal will last ten thousand years."),
        shot("TrainingGround", (30, 8, 3), (60, 6, 2), WEI,
             "Lead with your feet, not your elbows! And whoever breaks the puppet buys lunch. For Elder Mo!"),
        shot("Pagoda", (0, 8, 3), (20, 6, 2), N,
             "An old hermit teaches the Verdant Lotus Heart Sutra in the pagoda. Every morning, more students come."),
        shot("LotusPond", (-30, 7, 2), (0, 5, 1.8), N,
             "Xiao Man grows herbs. She only drops some of them. Her brother writes every week."),
        shot("CliffEdge", (180, 8, 3), (200, 14, 8), N,
             "And on clear nights, above the sea of clouds, one star blinks twice, as if someone up there were waving."),
    ]),
}
