"""Template lines the chapter generator uses around the hand-written heart of
each quest. Slots: {task} (the next objective, lower-cased), {Task}, {place},
{Place}, {foes}, {Foes}, {thing}, {item}, {name}. Protagonist tokens
({player}, {junior}, ...) are resolved at runtime.

Every line is text-only; nothing here is voiced.
"""

# a quest giver hands out the next step
OPEN = [
    "{Task}. I would do it myself, but my knees have filed a formal complaint.",
    "I need someone steady. {Task}, and come straight back.",
    "There's work, if you want it. {Task}.",
    "{Task}. Don't make that face; it builds character.",
    "Good, you're here. {Task}. Quickly, before the day gets any older.",
    "Listen carefully, because I'll only say it twice. {Task}.",
    "You have the look of someone with nothing to do. {Task}.",
    "I've asked three people already. Two ran. {Task}, would you?",
    "{Task}. And keep your eyes open. Things have been strange lately.",
    "It's a small task. Small tasks are how big trouble introduces itself. {Task}.",
    "Heaven sends help in odd shapes. Today it's yours. {Task}.",
    "{Task}. If anyone asks, you volunteered.",
    "The sooner this is done, the sooner I can stop worrying. {Task}.",
    "{Task}. You'll know what to do when you get there. Probably.",
    "I don't like the feel of it, {player}. {Task}.",
    "One more thing on a long list. {Task}.",
    "{Task}. Take care. I've grown used to you being in one piece.",
    "Your help again, {junior}. {Task}.",
]

# the protagonist's short answers
REPLY = [
    "Consider it done.", "On my way.", "Leave it to me.", "I'll be quick.", "I'll handle it.",
    "Right away.", "I won't let you down.", "Understood.", "Of course. I'll see what I can find.",
    "Then I'd better start walking.", "Say no more.", "Already going.",
    "I'll be careful. Mostly.", "You can count on me.", "I'll report back when it's done.",
    "Easy enough. Famous last words, I know.",
]

# an NPC receives the protagonist back
CLOSE = [
    "Done already? Good. The sect notices these things, even when it pretends not to.",
    "You came back in one piece. That's my favourite kind of report.",
    "Well done. I'll remember this, and so will the ledger.",
    "Thank you, {player}. Truly. Now sit down before you fall down.",
    "Hm. Better than I expected. Don't let it go to your head.",
    "Every day you surprise me a little less. That's a compliment.",
    "Good work. The world is a slightly tidier place, and I can finally have my tea.",
    "I knew you'd manage. I told everyone you'd manage. I lied about being sure.",
    "That settles one worry. Only a hundred left.",
    "You have dirt on your face and pride in your eyes. Keep the second one.",
    "Excellent. Rest while you can. Heaven never lets anyone rest for long.",
    "I owe you. Don't tell anyone; debts are embarrassing.",
    "That's that, then. You've grown, {junior}. I keep noticing.",
    "Thank you. Some things can only be done by walking there and doing them.",
]

# an ally regroups after an action, at a place
REGROUP = [
    "That's the last of it here. Catch your breath; {place} isn't done with us yet.",
    "Everyone still has all their fingers? Good. Count them again, to be sure.",
    "Not bad. Not bad at all. Remind me to be scared of you later.",
    "We're done at {place}. Whatever comes next, I'd rather meet it with a full stomach.",
    "Quiet now. I don't trust quiet. Let's keep moving.",
    "You fight like the mountain taught you personally.",
    "That was close. Closer than I'd like. Let's not do it like that again.",
    "Well. That happened. I'll tell the story better tomorrow.",
    "Hold still, you've got a scratch. There. Now you look heroic instead of careless.",
    "{Place} is clear. For now. Nothing stays clear for long these days.",
    "Breathe. In for four, out for four. Good. Now we go on.",
    "I've seen worse days. Not many, but some.",
]

# spoken as a fight starts ({foes} are the enemies)
CRY = [
    "{Foes}! Back to back, and mind your footing!",
    "Here they come. Strike first, apologise never.",
    "{Foes} ahead! Don't let them surround us!",
    "Weapons up! This is going to get loud.",
    "They've seen us. Good. I hate sneaking.",
    "Careful, {player}. These {foes} fight like they have nothing to lose.",
    "Left side's mine. Right side's yours. Middle is whoever's faster.",
    "Steady. Breathe. Then hit them very hard.",
    "More {foes}? Heaven must think we're bored.",
    "Stay close! I am not writing to your family.",
]

# narration when a fight starts and no ally is there
CRY_N = [
    "{Foes} spill out of cover, weapons bright.",
    "The {foes} spread out to surround you. They are not quite fast enough.",
    "A shout goes up. The {foes} have found you first.",
    "Steel whispers. The {foes} come on in silence.",
]

# narration for interacting with a prop; {thing} is its description
INTERACT = {
    "stone_stele": ["You brush dust from {thing}. The old characters are worn, but they still say what they mean.",
                    "{Thing} is cold under your palm. The carving is older than the sect, older maybe than the mountain.",
                    "You trace the words of {thing} one by one, and the hair on your arms rises."],
    "treasure_chest": ["The lid of {thing} groans open. Inside: dust, a moth, and exactly what you were looking for.",
                       "You pry open {thing}. Whoever packed it did so in a hurry, and in fear.",
                       "{Thing} is heavier than it looks. So is what's inside."],
    "blood_altar": ["{Thing} pulses like a sick heart. You press the Lotus Key to it, and it goes still.",
                    "Dark channels run across {thing}. You break them one by one until nothing flows."],
    "demon_obelisk": ["Runes crawl across {thing}. You set your palm against it and push your qi in, and it cracks.",
                      "{Thing} hums with stolen life. The counter-rune flares, and the hum dies."],
    "prison_cage": ["The lock of {thing} snaps. Whoever is inside blinks at you as if you were the sun.",
                    "You wrench {thing} open. Rust showers down like red snow."],
    "jade_slip": ["You press {thing} to your brow. Words pour into your mind, neat as a scholar's hand.",
                  "{Thing} glows faintly. Someone wanted this found, by the right person."],
    "bronze_bell": ["You strike {thing}. The note rolls out across the land, and far away, something answers.",
                    "{Thing} booms. Birds explode from every roof, and every head turns."],
    "spirit_stone": ["{Thing} drinks your qi and glows, then gives it back doubled, like an honest merchant.",
                     "You rest your hand on {thing}. It is warm, and it is humming a very old song."],
    "teleport_array": ["The jade runes of {thing} flicker, catch, and blaze. The air smells of rain.",
                       "You realign the runes of {thing}. The array coughs, then sings."],
    "seal": ["You press your palm to {thing}. Green light answers the pendant at your chest.",
             "{Thing} flares, then settles, as though it had been waiting for your hand.",
             "You trace the lines of {thing} with your qi until they glow clean."],
}

# narration when meditating, per volume (the realm being cultivated)
MEDITATE = {
    1: ["You breathe in for four, hold for four. Qi gathers below your navel like water in a cupped hand.",
        "The world goes quiet. Your meridians hum, a little wider than yesterday.",
        "Your pendant warms against your chest as the qi settles, strand by strand."],
    2: ["Your foundation drinks in the qi and hardens, layer on layer, like jade forming in the dark.",
        "Mud, root, blossom. The Heart Sutra turns in you, slow and patient.",
        "Breath by breath the foundation widens, until it feels like standing on bedrock."],
    3: ["Your golden core spins, bright and steady, and every turn draws the world a little closer.",
        "The core burns hotter. Impurities rise like smoke and are gone.",
        "You circulate qi through the core nine times. On the ninth, it rings like a struck bell."],
    4: ["Your nascent soul opens its eyes within you and looks around, curious as a child.",
        "You let your soul drift a hand's breadth from your body, then gently call it home.",
        "The tiny figure of light in your chest breathes when you breathe. It is getting stronger."],
    5: ["Soul and body blur at the edges. The wind feels like part of your own breath.",
        "You sit with your grief instead of fighting it, and your soul settles deeper for it.",
        "The boundary between you and heaven and earth thins, like mist in morning sun."],
    6: ["You sink past qi and soul into the stillness beneath. The void is not empty. It is waiting.",
        "Space folds around you like cloth. You learn where the creases are.",
        "Nothing, and nothing, and nothing. Then, in the nothing, a single clear thought."],
    7: ["Bone, blood and soul pull together like three strands of one rope.",
        "Your heartbeat and your qi fall into step, and your body stops feeling like a house you merely live in.",
        "Lightning-old aches fade from your bones. The body remembers it is yours."],
    8: ["You feel the whole mountain breathing: every disciple, every root, every stubborn carp.",
        "Your dao widens until it has room for everyone you have ever carried.",
        "Compassion is heavy. You find that you can lift it."],
    9: ["Far above, clouds turn slowly, as if heaven were leaning down to listen.",
        "You steady your heart against thunder that has not yet come.",
        "Every flaw in you surfaces, one by one, to be looked at and forgiven."],
    10: ["The sky is red at the edges. You breathe it in anyway, and hold it, and let it go.",
         "Your qi is as still as deep water, and as heavy.",
         "You sit at the edge of everything you have been, and breathe."],
}

# per-NPC personality lines, used to fill out conversations
QUIRKS = {
    "master_yun": ["The clouds are loud today. Or I am tired. One of us should rest.",
                   "I have a hundred elders and one sect. Some days I would trade the elders for a nap.",
                   "Don't bow so deeply. My neck hurts just watching.",
                   "When I was a disciple, I thought sect masters knew everything. I was wrong, and now it's my problem."],
    "elder_mo": ["Back straight. I won't say it again. I will say it again.",
                 "Hmph. Adequate. Don't look so pleased.",
                 "In my day we trained in the snow. Uphill. With buckets.",
                 "Eat something. You look like a boiled noodle with ambitions."],
    "elder_bai": ["Mind the shelves. They're older than your grandmother and less forgiving.",
                  "I have read everything in the pagoda twice, and the recipes three times.",
                  "Knowledge is like tea. Too hot, and it scalds. Too cold, and nobody wants it.",
                  "If you find a book with turtle soup stains on it, it's mine. Return it."],
    "elder_gu": ["The precepts are older than your grief, and mine.",
                 "Speak. The Law Hall listens, even when it does not answer."],
    "elder_hua": ["Hold out your wrist. Hm. Your pulse is stubborn. Like you.",
                  "Mind the moonbell. It bites, and it holds grudges.",
                  "A good healer asks what hurts. A great one asks why.",
                  "Drink this. No, it doesn't taste good. That's how you know it works."],
    "senior_han": ["Your stance is lazy. Fix it before someone fixes it for you.",
                   "I don't do speeches. Walk faster.",
                   "Stop smiling. It's suspicious.",
                   "If you get hurt, I'll be very annoyed. Don't annoy me."],
    "senior_wei": ["Have you eaten? I haven't eaten. We should both eat.",
                   "Dumpling, my sword, is ready. I'm ready. My stomach is always ready.",
                   "I trained three puppets this morning. They cried. Well, one creaked.",
                   "If we survive this, I'm cooking. If we don't, somebody else is cooking."],
    "rival_zhao": ["Hmph. Keep up, village brat. Friend. Village friend.",
                   "The Zhao clan does not panic. It becomes strategically alarmed.",
                   "I could have done this alone. I'm choosing not to. Appreciate it.",
                   "Don't tell anyone I'm enjoying myself."],
    "gate_lu": ["Heard the latest? No? Neither have I. Give me an hour.",
                "I was meditating. With my eyes closed. Loudly.",
                "I bet on you, by the way. I always bet on you. I've bought four hats.",
                "Nobody tells the gate disciple anything. So I listen. Constantly."],
    "steward_qian": ["Every spirit stone has a name, and all of them are mine.",
                     "Sign here. And here. And here. No, the other here.",
                     "Do you know what that costs? I do. I always do.",
                     "The treasury is not a well. It is a very small cup."],
    "xiao_man": ["I only dropped three herbs today! Well. Three that I know of.",
                 "The carp know my name now. They're very polite about it.",
                 "Elder Hua says I'm improving. She said it with her eyes closed.",
                 "Do you want a pill? I made it. It's probably a pill."],
    "xiao_shi": ["Thank you. I'll keep saying it until you're sick of it.",
                 "I draw maps now. It helps, knowing where the walls are.",
                 "My sister still feeds me like I'm a starving cat. I'm not complaining."],
    "hermit_lan": ["The tea has been steeping for a decade. It is nearly ready.",
                   "The bamboo bends, and so it outlives the storm.",
                   "Sit. Breathe. The forest will wait. It is very good at waiting."],
    "wanderer_ye": ["...", "Keep walking, lotus-bearer.", "Trust fewer people than you'd like. Trust me slightly less."],
    "bandit_tie": ["Iron-Fang pays his debts. Eventually.",
                   "I wash dishes now. I'm very good at it. Tell no one.",
                   "My men want to know if heroes get lunch breaks."],
    "magistrate_zhou": ["The yamen is open to all petitions. Between the second and fourth bell.",
                        "Order! Ah. It's already orderly. Carry on.",
                        "An honest magistrate sleeps poorly. I have not slept since spring."],
    "innkeeper_fang": ["Wine, noodles or gossip? The gossip is free. The rest, you pay for.",
                       "Immortals drink like fish and tip like cats.",
                       "Wipe your boots! This floor has seen a tax collector."],
    "constable_du": ["Trouble? Tell me. I'll write it down. Then I'll deal with it.",
                     "Keep your sword sheathed in town, cultivator. Mostly.",
                     "Gate closes at dusk. Always has. Always will."],
    "widow_liu": ["The water's sweet this season. Take a cup.",
                  "Heaven keeps its accounts. I keep mine.",
                  "Every face that passes, I look twice. Old habit."],
    "ferryman_pan": ["River's high. Fares are higher.",
                     "Mind the third plank. It has opinions.",
                     "Forty years on this water. It's never lied to me yet."],
    "merchant_jin": ["Everything has a price. I'm trying to learn which things shouldn't.",
                     "Mind the crates. The stamps are imported.",
                     "Business is business. I'm told friendship is also business, but warmer."],
    "star_sage": ["The stars do not lie. They merely exaggerate.",
                  "Sit. Look up. Try not to fall off.",
                  "I have been a memory for a very long time. It's restful, mostly."],
    "yan_tie": ["Thunder Peak says hello. Loudly. It always does.",
                "I owe you a rematch and a life. The rematch is easier to pay.",
                "Strength without a clear heart is a landslide. I learned that the hard way."],
    "liu_er": ["Mother says I have to be polite to immortals. Hello, immortal!",
               "I can swim across the river and back. Twice, if nobody's counting."],
    "young_ruan": ["The Iron Scale does not apologise. It... reconsiders.",
                   "Your mountain is taller. Ours is wider. We're both very proud of that."],
    "master_ruan": ["Speak plainly. I am too old for riddles and too tired for lies.",
                    "Scales do not rust. Neither do grudges. I am trying to let mine."],
    "abbess_jing": ["Mercy is a discipline, not a mood.", "The well reflects the moon. It does not argue with it."],
    "ancestor_zhao": ["The Zhao clan counts in centuries, and in gold.",
                      "My grandson has your stubbornness. Regrettably, he had it first."],
}
