"""Template lines the chapter generator uses around the hand-written heart of
each quest. Slots: {task} (the next objective, lower-cased), {Task}, {place},
{Place}, {foes}, {Foes}, {thing}, {item}, {name}. Protagonist tokens
({player}, {junior}, ...) are resolved at runtime.

Every line is text-only; nothing here is voiced.
"""

# a quest giver hands out the next step
OPEN = [
    "{Task}. I would do it myself, but my knees have filed a formal complaint.",
    "I need someone steady. {Task}, and come straight back.",
    "There's work, if you want it. {Task}.",
    "{Task}. Don't make that face; it builds character.",
    "Good, you're here. {Task}. Quickly, before the day gets any older.",
    "Listen carefully, because I'll only say it twice. {Task}.",
    "You have the look of someone with nothing to do. {Task}.",
    "I've asked three people already. Two ran. {Task}, would you?",
    "{Task}. And keep your eyes open. Things have been strange lately.",
    "It's a small task. Small tasks are how big trouble introduces itself. {Task}.",
    "Heaven sends help in odd shapes. Today it's yours. {Task}.",
    "{Task}. If anyone asks, you volunteered.",
    "The sooner this is done, the sooner I can stop worrying. {Task}.",
    "{Task}. You'll know what to do when you get there. Probably.",
    "I don't like the feel of it, {player}. {Task}.",
    "One more thing on a long list. {Task}.",
    "{Task}. Take care. I've grown used to you being in one piece.",
    "Your help again, {junior}. {Task}.",
]

# the protagonist's short answers
REPLY = [
    "Consider it done.", "On my way.", "Leave it to me.", "I'll be quick.", "I'll handle it.",
    "Right away.", "I won't let you down.", "Understood.", "Of course. I'll see what I can find.",
    "Then I'd better start walking.", "Say no more.", "Already going.",
    "I'll be careful. Mostly.", "You can count on me.", "I'll report back when it's done.",
    "Easy enough. Famous last words, I know.",
    "I'll see to it before the next bell.", "Then I'll go now, while the light holds.", "Consider it mine.",
    "I'll bring back whatever I find.", "If it can be done, I'll do it.", "Give me until dusk.",
    "I know the way. More or less.", "Leave the worrying to me for once.", "Right. Deep breath. Going.",
    "I won't come back empty-handed.",
]

# the protagonist's answers when coming back
REPLY2 = ["Glad to help.", "Any time.", "It was nothing. Well, it was something.", "Just doing my part.",
          "I learned a lot, actually.", "Next time, maybe something easier?"]

# an NPC receives the protagonist back
CLOSE = [
    "Done already? Good. The sect notices these things, even when it pretends not to.",
    "You came back in one piece. That's my favourite kind of report.",
    "Well done. I'll remember this, and so will the ledger.",
    "Thank you, {player}. Truly. Now sit down before you fall down.",
    "Hm. Better than I expected. Don't let it go to your head.",
    "Every day you surprise me a little less. That's a compliment.",
    "Good work. The world is a slightly tidier place, and I can finally have my tea.",
    "I knew you'd manage. I told everyone you'd manage. I lied about being sure.",
    "That settles one worry. Only a hundred left.",
    "You have dirt on your face and pride in your eyes. Keep the second one.",
    "Excellent. Rest while you can. Heaven never lets anyone rest for long.",
    "I owe you. Don't tell anyone; debts are embarrassing.",
    "That's that, then. You've grown, {junior}. I keep noticing.",
    "Thank you. Some things can only be done by walking there and doing them.",
]

# an ally regroups after an action, at a place
REGROUP = [
    "That's the last of it here. Catch your breath; {place} isn't done with us yet.",
    "Everyone still has all their fingers? Good. Count them again, to be sure.",
    "Not bad. Not bad at all. Remind me to be scared of you later.",
    "We're done at {place}. Whatever comes next, I'd rather meet it with a full stomach.",
    "Quiet now. I don't trust quiet. Let's keep moving.",
    "You fight like the mountain taught you personally.",
    "That was close. Closer than I'd like. Let's not do it like that again.",
    "Well. That happened. I'll tell the story better tomorrow.",
    "Hold still, you've got a scratch. There. Now you look heroic instead of careless.",
    "{Place} is clear. For now. Nothing stays clear for long these days.",
    "Breathe. In for four, out for four. Good. Now we go on.",
    "I've seen worse days. Not many, but some.",
]

# an ally met when nothing has happened yet (a conversation right after another one)
MEET = [
    "There you are. I was hoping you'd come by {place}.",
    "Sit a moment. The day's been long, and it isn't over yet.",
    "You found me. Good. I've been turning something over and I want another pair of eyes on it.",
    "Ah, {player}. Walk with me a little. My thoughts go further on foot.",
    "I heard you were about. News travels fast when you're the one making it.",
    "Come, come. I was just thinking about you. Nothing bad. Mostly.",
    "You look like someone with questions. I may even have answers.",
    "Good timing. Another minute and I'd have gone looking for you.",
    "Stay a moment. There's something you should hear from me, not from gossip.",
    "Here you are at last. I kept you a seat. And tea. The tea is cold now.",
    "Don't look so worried. Or do. It suits the week we're having.",
    "I wondered when you'd turn up at {place}. Everyone does, sooner or later.",
]

# the protagonist catching their breath after the action
AFTER_REPLY = ["We did what we could.", "I'm fine. Really. Mostly.", "Let's not do that again soon.",
               "It's done. For now.", "My hands are still shaking. Give them a moment.", "Is everyone all right?",
               "That was closer than it looked.", "I'll feel it tomorrow.", "Thank you for watching my back."]

MEET_REPLY = ["I came as soon as I could.", "What is it?", "I'm listening.", "Of course. What's on your mind?",
              "You wanted to see me?", "I have time. Go on.", "Is something wrong?", "Tell me."]

# spoken as a fight starts ({foes} are the enemies)
CRY = [
    "{Foes}! Back to back, and mind your footing!",
    "Here they come. Strike first, apologise never.",
    "{Foes} ahead! Don't let them surround us!",
    "Weapons up! This is going to get loud.",
    "They've seen us. Good. I hate sneaking.",
    "Careful, {player}. These {foes} fight like they have nothing to lose.",
    "Left side's mine. Right side's yours. Middle is whoever's faster.",
    "Steady. Breathe. Then hit them very hard.",
    "More {foes}? Heaven must think we're bored.",
    "Stay close! I am not writing to your family.",
]

# narration when a fight starts and no ally is there
CRY_N = [
    "{Foes} spill out of cover, weapons bright.",
    "The {foes} spread out to surround you. They are not quite fast enough.",
    "A shout goes up. The {foes} have found you first.",
    "Steel whispers. The {foes} come on in silence.",
]

# narration for interacting with a prop; {thing} is its description
INTERACT = {
    "stone_stele": ["You brush dust from {thing}. The old characters are worn, but they still say what they mean.",
                    "{Thing} is cold under your palm. The carving is older than the sect, older maybe than the mountain.",
                    "You trace the words of {thing} one by one, and the hair on your arms rises."],
    "treasure_chest": ["The lid of {thing} groans open. Inside: dust, a moth, and exactly what you were looking for.",
                       "You pry open {thing}. Whoever packed it did so in a hurry, and in fear.",
                       "{Thing} is heavier than it looks. So is what's inside."],
    "blood_altar": ["{Thing} pulses like a sick heart. You press the Lotus Key to it, and it goes still.",
                    "Dark channels run across {thing}. You break them one by one until nothing flows."],
    "demon_obelisk": ["Runes crawl across {thing}. You set your palm against it and push your qi in, and it cracks.",
                      "{Thing} hums with stolen life. The counter-rune flares, and the hum dies."],
    "prison_cage": ["The lock of {thing} snaps. Whoever is inside blinks at you as if you were the sun.",
                    "You wrench {thing} open. Rust showers down like red snow."],
    "jade_slip": ["You press {thing} to your brow. Words pour into your mind, neat as a scholar's hand.",
                  "{Thing} glows faintly. Someone wanted this found, by the right person."],
    "bronze_bell": ["You strike {thing}. The note rolls out across the land, and far away, something answers.",
                    "{Thing} booms. Birds explode from every roof, and every head turns."],
    "spirit_stone": ["{Thing} drinks your qi and glows, then gives it back doubled, like an honest merchant.",
                     "You rest your hand on {thing}. It is warm, and it is humming a very old song."],
    "teleport_array": ["The jade runes of {thing} flicker, catch, and blaze. The air smells of rain.",
                       "You realign the runes of {thing}. The array coughs, then sings."],
    "seal": ["You press your palm to {thing}. Green light answers the pendant at your chest.",
             "{Thing} flares, then settles, as though it had been waiting for your hand.",
             "You trace the lines of {thing} with your qi until they glow clean."],
    # -- the quest props of the enlarged world
    "notice_board": ["Slips flutter on {thing}, three deep. Under a request for firewood, one note is newer, and written in a hurry.",
                     "You read {thing} from corner to corner. Someone has crossed out a name and written a warning beside it.",
                     "Most of {thing} is chores and grudges. One slip, pinned upside down, is meant for someone who knows to look."],
    "ancestral_tablet": ["You bow before {thing}. Names in gold and faded red go back further than anyone alive can count.",
                         "Incense ash lies fresh before {thing}. One name has been touched so often its gilding is gone.",
                         "{Thing} stand in silent rows. You read the names aloud, softly, because someone should."],
    "pill_furnace": ["{Thing} breathes out heat like a sleeping beast. Inside, a batch of pills turns slowly in the glow.",
                     "You feed a little qi into {thing}. The flame steadies from angry red to patient gold.",
                     "Soot and bitter smoke pour from {thing} as you open it. Something in the last batch was not meant to be there."],
    "sword_in_stone": ["You close your hand on the hilt of {thing}. It hums, weighs you, and decides to stay where it is.",
                       "{Thing} is cold and humming. For a moment you hear its last owner's oath, word for word.",
                       "Rust flakes from {thing} as you touch it. The blade beneath is still bright, and still sharp."],
    "tortoise_stele": ["The stone tortoise bears {thing} on its back, patient as a mountain. The carved words record a debt.",
                       "You brush moss from {thing}. The characters are old, formal, and angrier than they first appear.",
                       "{Thing} has outlived the dynasty that raised it. Its last line has been deliberately chiselled away."],
    "guardian_lion": ["{Thing} stares down at you, one paw on a carved ball. Something is wedged beneath the paw.",
                      "You touch the mane of {thing}. The stone is warm, as if it had been sitting in the sun, or breathing.",
                      "The eyes of {thing} follow you. You decide that is the stonemason's skill, and nothing else."],
    "bronze_ding": ["Three legs, two handles, and a rim of ancient script: {thing} is older than the hall that shelters it.",
                    "Incense smoke curls out of {thing}. Beneath the ash, something that is not incense glints.",
                    "You read the rim of {thing} by touch. It lists the names of those who made an oath around it."],
    "bronze_mirror": ["You look into {thing}. Your face looks back, then, a moment later, a face that is not quite yours.",
                      "{Thing} is dark with age. When you breathe on it, words appear in the mist and fade.",
                      "The back of {thing} is carved with a lotus. The front shows the room behind you, and one extra shadow."],
    "spirit_lamp": ["The flame of {thing} leans toward you as if it knew your name, then steadies, clean and white.",
                    "You trim {thing}. The light spreads, and the shadows it drives back were hiding marks on the wall.",
                    "{Thing} burns without oil and without smoke. It has been burning for someone for a very long time."],
    "scroll_rack": ["You work along {thing} scroll by scroll. One is shelved in the wrong place, on purpose.",
                    "Dust lies thick on {thing}, except on one shelf, where a hand has been reaching often and recently.",
                    "{Thing} creaks under a century of learning. The scroll you need is behind the scroll everyone takes."],
    "war_drum": ["You strike {thing}. The boom rolls out across the land and comes back from the hills, twice.",
                 "{Thing} speaks in a voice like thunder. Every head turns. Somewhere, someone starts running.",
                 "The skin of {thing} is tight and ancient. One beat, and your heart falls into step with it."],
    "sealed_coffin": ["Paper seals cross {thing}, written in blood gone brown. One of them has been torn and pasted back.",
                      "Something shifts inside {thing} when you touch it. Then it is still again, very deliberately.",
                      "{Thing} is heavier than any coffin should be. The seals are sound. For now."],
    "offering_table": ["Fruit, rice and a cup of wine wait on {thing}. Someone set out one bowl more than there are gods.",
                       "You leave an offering on {thing} and bow. The candle flames bow back.",
                       "The dust on {thing} has been disturbed. Beneath the incense bowl lies a folded note."],
    "rune_pillar": ["Runes crawl up {thing} like ivy made of light. One of them is carved backward.",
                    "You lay your palm on {thing}. It drinks your qi, hums a note, and passes it to its neighbours.",
                    "{Thing} is cracked along one rune. Whoever did it knew exactly where to strike."],
    "armillary_sphere": ["You turn the bronze rings of {thing}. They settle on a date that has not happened yet.",
                         "{Thing} creaks as its rings align. The stars they point to are the ones the Blood Moon watches.",
                         "The rings of {thing} spin by themselves for a moment, then point, all together, down."],
    "medicine_cabinet": ["A hundred little drawers line {thing}, each labelled. One label is in a different hand.",
                         "You open drawer after drawer of {thing}. Ginseng, liquorice, and one drawer that smells of blood lotus.",
                         "{Thing} is almost bare. Someone has been emptying it faster than it can be filled."],
    "wine_jars": ["The jars are sealed with clay and stamped. One seal is fresh, though the jar is very old.",
                  "You tap {thing} one by one. Full, full, full, and one that answers hollow.",
                  "The smell from {thing} is sweet and strong. Beneath it is something sharper, and not wine at all."],
    "loom": ["The shuttle of {thing} has stopped mid-row. The half-finished pattern is a map, if you know how to read it.",
             "You run your fingers along the threads of {thing}. One colour runs through every bolt, like a signature.",
             "{Thing} clacks once as you touch it, as if the weaver had only stepped out for a moment."],
    "map_table": ["{Thing} is pinned with flags and scattered with notes. Someone has marked a route in red, recently.",
                  "You study {thing}. Three places are circled twice, and one has been scratched out so hard it tore.",
                  "The map on {thing} shows paths that are not on any other map. Some of them lead down."],
    "crane_statue": ["{Thing} stands on one leg, its bronze feathers green with age. Its beak points somewhere specific.",
                     "You touch the neck of {thing}. It is cool and smooth, polished by generations of wishes.",
                     "Cranes circle {thing} and settle on it one by one, as if it were their elder."],
    "spirit_fountain": ["{Thing} bubbles clear and cold. Your qi steadies the moment the water touches your hands.",
                        "Coins and petals glint in {thing}. The water hums faintly, a note just below hearing.",
                        "You cleanse {thing}. Dark threads rise out of the water like smoke and dissolve."],
    "puppet_frame": ["{Thing} creaks as you test it. The joints are oiled, the wood is new, and the runes are older.",
                     "You tighten the cords of {thing}. It twitches, tries a stance, and looks at you expectantly.",
                     "Someone has scratched a tally of defeats into {thing}. The puppet is winning."],
    "herb_drying_rack": ["Bundles of herbs hang from {thing}, drying in neat rows. One bundle is the wrong herb entirely.",
                         "You turn the bundles on {thing}. The smell of mint and bitter root makes your eyes water.",
                         "{Thing} sag under the day's harvest. Something small and furry has been nibbling the lower rows."],
    "chain_anchor": ["The links of {thing} are thick as your arm. One has been filed almost through.",
                     "You test {thing}. It holds, groaning, and rust showers down like red snow.",
                     "{Thing} is bolted into the living rock. Old blood has rusted into its links."],
    "soul_lantern": ["A pale flame flickers inside {thing}, and in the flame, for an instant, a face.",
                     "You open {thing}. A breath of cold escapes, and a whisper that sounds like thank you.",
                     "{Thing} hums with a trapped voice. You break the rune, and the flame goes out, gently."],
    "abacus_desk": ["The ledgers on {thing} balance to the last copper, which is exactly what makes them suspicious.",
                    "You run the beads of {thing}. The accounts come out one sum short, every month, for years.",
                    "{Thing} is covered in neat figures. Between them, in a smaller hand, someone has written a name."],
    "fishing_boat": ["{Thing} rocks at its rope. Under the nets lies a bundle that no fisherman would need.",
                     "You search {thing}. It smells of fish, tar and, faintly, of blood lotus.",
                     "The hull of {thing} has been patched in a hurry. Something scraped it, hard, from below."],
    "wishing_tree": ["Red ribbons crowd the branches of {thing}. One wish is written in a child's hand and names you.",
                     "You tie your own wish to {thing}. The branches rustle, though there is no wind.",
                     "Among the ribbons on {thing} is a strip of black cloth, knotted with a Blood Moon sigil."],
    "jade_screen": ["{Thing} is carved with a mountain, a river and a very small figure climbing. Behind it, a hidden niche.",
                    "Light passes through {thing} and throws a pattern on the floor: a map, if you stand just right.",
                    "You study the carving of {thing}. One panel has been replaced, and the new jade is a shade too green."],
    "stone_tablet_array": ["Rows of stone tablets stand in order. One is out of its place, and the gap is the message.",
                           "You read {thing} one after another. Together they make a sentence none of them says alone.",
                           "{Thing} are carved with names and dates. The last one is blank, waiting."],
}

# narration when meditating, per volume (the realm being cultivated)
MEDITATE = {
    1: ["You breathe in for four, hold for four. Qi gathers below your navel like water in a cupped hand.",
        "The world goes quiet. Your meridians hum, a little wider than yesterday.",
        "Your pendant warms against your chest as the qi settles, strand by strand."],
    2: ["Your foundation drinks in the qi and hardens, layer on layer, like jade forming in the dark.",
        "Mud, root, blossom. The Heart Sutra turns in you, slow and patient.",
        "Breath by breath the foundation widens, until it feels like standing on bedrock."],
    3: ["Your golden core spins, bright and steady, and every turn draws the world a little closer.",
        "The core burns hotter. Impurities rise like smoke and are gone.",
        "You circulate qi through the core nine times. On the ninth, it rings like a struck bell."],
    4: ["Your nascent soul opens its eyes within you and looks around, curious as a child.",
        "You let your soul drift a hand's breadth from your body, then gently call it home.",
        "The tiny figure of light in your chest breathes when you breathe. It is getting stronger."],
    5: ["Soul and body blur at the edges. The wind feels like part of your own breath.",
        "You sit with your grief instead of fighting it, and your soul settles deeper for it.",
        "The boundary between you and heaven and earth thins, like mist in morning sun."],
    6: ["You sink past qi and soul into the stillness beneath. The void is not empty. It is waiting.",
        "Space folds around you like cloth. You learn where the creases are.",
        "Nothing, and nothing, and nothing. Then, in the nothing, a single clear thought."],
    7: ["Bone, blood and soul pull together like three strands of one rope.",
        "Your heartbeat and your qi fall into step, and your body stops feeling like a house you merely live in.",
        "Lightning-old aches fade from your bones. The body remembers it is yours."],
    8: ["You feel the whole mountain breathing: every disciple, every root, every stubborn carp.",
        "Your dao widens until it has room for everyone you have ever carried.",
        "Compassion is heavy. You find that you can lift it."],
    9: ["Far above, clouds turn slowly, as if heaven were leaning down to listen.",
        "You steady your heart against thunder that has not yet come.",
        "Every flaw in you surfaces, one by one, to be looked at and forgiven."],
    10: ["The sky is red at the edges. You breathe it in anyway, and hold it, and let it go.",
         "Your qi is as still as deep water, and as heavy.",
         "You sit at the edge of everything you have been, and breathe."],
}

# per-NPC personality lines, used to fill out conversations
QUIRKS = {
    "master_yun": ["The clouds are loud today. Or I am tired. One of us should rest.",
                   "I have a hundred elders and one sect. Some days I would trade the elders for a nap.",
                   "Don't bow so deeply. My neck hurts just watching.",
                   "When I was a disciple, I thought sect masters knew everything. I was wrong, and now it's my problem."],
    "elder_mo": ["Back straight. I won't say it again. I will say it again.",
                 "Hmph. Adequate. Don't look so pleased.",
                 "In my day we trained in the snow. Uphill. With buckets.",
                 "Eat something. You look like a boiled noodle with ambitions."],
    "elder_bai": ["Mind the shelves. They're older than your grandmother and less forgiving.",
                  "I have read everything in the pagoda twice, and the recipes three times.",
                  "Knowledge is like tea. Too hot, and it scalds. Too cold, and nobody wants it.",
                  "If you find a book with turtle soup stains on it, it's mine. Return it."],
    "elder_gu": ["The precepts are older than your grief, and mine.",
                 "Speak. The Law Hall listens, even when it does not answer."],
    "elder_hua": ["Hold out your wrist. Hm. Your pulse is stubborn. Like you.",
                  "Mind the moonbell. It bites, and it holds grudges.",
                  "A good healer asks what hurts. A great one asks why.",
                  "Drink this. No, it doesn't taste good. That's how you know it works."],
    "senior_han": ["Your stance is lazy. Fix it before someone fixes it for you.",
                   "I don't do speeches. Walk faster.",
                   "Stop smiling. It's suspicious.",
                   "If you get hurt, I'll be very annoyed. Don't annoy me."],
    "senior_wei": ["Have you eaten? I haven't eaten. We should both eat.",
                   "Dumpling, my sword, is ready. I'm ready. My stomach is always ready.",
                   "I trained three puppets this morning. They cried. Well, one creaked.",
                   "If we survive this, I'm cooking. If we don't, somebody else is cooking."],
    "rival_zhao": ["Hmph. Keep up, village brat. Friend. Village friend.",
                   "The Zhao clan does not panic. It becomes strategically alarmed.",
                   "I could have done this alone. I'm choosing not to. Appreciate it.",
                   "Don't tell anyone I'm enjoying myself."],
    "gate_lu": ["Heard the latest? No? Neither have I. Give me an hour.",
                "I was meditating. With my eyes closed. Loudly.",
                "I bet on you, by the way. I always bet on you. I've bought four hats.",
                "Nobody tells the gate disciple anything. So I listen. Constantly."],
    "steward_qian": ["Every spirit stone has a name, and all of them are mine.",
                     "Sign here. And here. And here. No, the other here.",
                     "Do you know what that costs? I do. I always do.",
                     "The treasury is not a well. It is a very small cup."],
    "xiao_man": ["I only dropped three herbs today! Well. Three that I know of.",
                 "The carp know my name now. They're very polite about it.",
                 "Elder Hua says I'm improving. She said it with her eyes closed.",
                 "Do you want a pill? I made it. It's probably a pill."],
    "xiao_shi": ["Thank you. I'll keep saying it until you're sick of it.",
                 "I draw maps now. It helps, knowing where the walls are.",
                 "My sister still feeds me like I'm a starving cat. I'm not complaining."],
    "hermit_lan": ["The tea has been steeping for a decade. It is nearly ready.",
                   "The bamboo bends, and so it outlives the storm.",
                   "Sit. Breathe. The forest will wait. It is very good at waiting."],
    "wanderer_ye": ["...", "Keep walking, lotus-bearer.", "Trust fewer people than you'd like. Trust me slightly less."],
    "bandit_tie": ["Iron-Fang pays his debts. Eventually.",
                   "I wash dishes now. I'm very good at it. Tell no one.",
                   "My men want to know if heroes get lunch breaks."],
    "magistrate_zhou": ["The yamen is open to all petitions. Between the second and fourth bell.",
                        "Order! Ah. It's already orderly. Carry on.",
                        "An honest magistrate sleeps poorly. I have not slept since spring."],
    "innkeeper_fang": ["Wine, noodles or gossip? The gossip is free. The rest, you pay for.",
                       "Immortals drink like fish and tip like cats.",
                       "Wipe your boots! This floor has seen a tax collector."],
    "constable_du": ["Trouble? Tell me. I'll write it down. Then I'll deal with it.",
                     "Keep your sword sheathed in town, cultivator. Mostly.",
                     "Gate closes at dusk. Always has. Always will."],
    "widow_liu": ["The water's sweet this season. Take a cup.",
                  "Heaven keeps its accounts. I keep mine.",
                  "Every face that passes, I look twice. Old habit."],
    "ferryman_pan": ["River's high. Fares are higher.",
                     "Mind the third plank. It has opinions.",
                     "Forty years on this water. It's never lied to me yet."],
    "merchant_jin": ["Everything has a price. I'm trying to learn which things shouldn't.",
                     "Mind the crates. The stamps are imported.",
                     "Business is business. I'm told friendship is also business, but warmer."],
    "star_sage": ["The stars do not lie. They merely exaggerate.",
                  "Sit. Look up. Try not to fall off.",
                  "I have been a memory for a very long time. It's restful, mostly."],
    "yan_tie": ["Thunder Peak says hello. Loudly. It always does.",
                "I owe you a rematch and a life. The rematch is easier to pay.",
                "Strength without a clear heart is a landslide. I learned that the hard way."],
    "liu_er": ["Mother says I have to be polite to immortals. Hello, immortal!",
               "I can swim across the river and back. Twice, if nobody's counting."],
    "young_ruan": ["The Iron Scale does not apologise. It... reconsiders.",
                   "Your mountain is taller. Ours is wider. We're both very proud of that."],
    "master_ruan": ["Speak plainly. I am too old for riddles and too tired for lies.",
                    "Scales do not rust. Neither do grudges. I am trying to let mine."],
    "abbess_jing": ["Mercy is a discipline, not a mood.", "The well reflects the moon. It does not argue with it."],
    "ancestor_zhao": ["The Zhao clan counts in centuries, and in gold.",
                      "My grandson has your stubbornness. Regrettably, he had it first."],
}
