"""How the chapter generator talks about places, and which places suit what.

Every exterior marker of tools/world_spec.MAPS has an entry in ``MARKERS``:

    marker: (phrase, kinds, tags, [arrival narrations])

* ``phrase``  - how objective text names it ("the herb terraces");
* ``kinds``   - which objective types may be staged there: ``m`` meet (an NPC
  stands there to talk), ``f`` fight, ``g`` gather, ``d`` meditate, ``p`` an
  interactable prop, ``r`` reach;
* ``tags``    - the character of the place ("gate", "wild", "water", ...): a
  step pinned by an outline to a marker whose name its lines never mention
  may be moved to another marker sharing a tag (see saga_gen.Gen._relocate),
  which spreads the saga over the enlarged maps without breaking a scene;
* arrival narrations used when a reach objective has no authored lines.

``PROPS_AT`` names the quest props (world_spec.PROPS) that belong at a
marker, ``ITEMS_AT`` the collectibles that plausibly lie around it, and
``HAUNTS`` where each named character likes to be found when a conversation
is staged away from home. ``POOLS``, ``NAMES`` and ``ARRIVE`` are derived.

Markers that are NPC homes are filtered out at generation time when the NPC
is present. Door markers of the building interiors (ElderQuarters, TeaHouse,
...) are never used: stepping on them would carry the player inside.
"""

MARKERS = {
    # ------------------------------------------------------------------ the Azure Cloud Sect
    "sect": {
        "SectGate": ("the sect gate", "mfgprd", "gate",
                     ["The paifang gate throws a long shadow down the steps. Somewhere below, a new candidate is groaning at step four thousand.",
                      "Gate disciples straighten as you pass. A few of them bow. You are still not used to that."]),
        "GateGuardPost": ("the gate post", "mr", "gate", []),
        "FormationArray": ("the formation plaza", "mfgdpr", "plaza array",
                           ["The formation plaza hums underfoot, a thousand runes breathing in slow blue light.",
                            "Disciples cross the plaza in twos and threes, lowering their voices as they pass the array."]),
        "IncenseBurner": ("the incense cauldron", "mr", "plaza",
                          ["The great bronze cauldron smoulders. Someone has written 'donations welcome' on it in chalk."]),
        "HallSteps": ("the hall steps", "mr", "hall plaza",
                      ["The hall steps are worn into shallow bowls by three hundred years of hurrying feet.",
                       "Incense drifts down the hall steps. Above, the double eaves hold up the sky with practised ease."]),
        "MainHall": ("the main hall", "mpr", "hall",
                     ["Inside the main hall, the founder's tablet gleams. The faded green lotus beside it seems a little brighter today."]),
        "TrainingGround": ("the training ground", "mfpr", "training",
                           ["The training ground smells of sweat, sawdust and Wei Tong's lunch.",
                            "Straw dummies lean at tired angles across the training ground. One of them is wearing a hat."]),
        "WeaponRack": ("the weapon rack", "mr", "training", []),
        "Pavilion": ("the quiet pavilion", "mdpr", "garden quiet",
                     ["The hexagonal pavilion is empty except for a teapot, still warm, and a single fallen plum petal."]),
        "Pagoda": ("the scripture pagoda", "mpr", "scholar",
                   ["Seven tiers of scripture rise above you. From the fourth floor comes the sound of someone sneezing on dust."]),
        "LotusPond": ("the lotus pond", "mgdr", "water garden",
                      ["Carp rise to the surface of the lotus pond, hoping you are someone with crumbs."]),
        "StoneBridge": ("the stone bridge", "mdr", "water garden",
                        ["From the top of the stone bridge the pond reflects the whole sect upside down, calmer than the original."]),
        "PlumGarden": ("the plum garden", "mgdpr", "garden quiet",
                       ["Plum petals drift across the path. The garden is so quiet you can hear them land."]),
        "HerbGarden": ("the herb terraces", "mgpr", "medicine garden",
                       ["The herb terraces step down the slope in green stripes, each labelled in Elder Hua's stern hand."]),
        "MoonGate": ("the moon gate", "mdr", "gate garden",
                     ["The round moon gate frames the western courtyard like a painting someone forgot to finish.",
                      "Wind whistles through the moon gate. On the far side, the herb terraces shiver green."]),
        "CliffEdge": ("the cliff edge", "mdr", "cliff high",
                      ["The sea of clouds rolls below the cliff edge, white and endless, as if the mountain were a ship.",
                       "At the cliff edge the wind tugs at your robe. The world below is only cloud and the calls of cranes."]),
        "ScholarRock": ("the scholar rock", "mpr", "plaza scholar",
                        ["The Taihu scholar rock stands full of holes, as if the wind had tried to read it."]),
        "OuterPines": ("the outer pines", "mfgr", "wild woods",
                       ["Beyond the wall the pines grow close and dark, and the wind in them sounds like distant surf.",
                        "Needles crunch underfoot in the outer pines. Something small and watchful freezes, then flees."]),
        # -- the expanded mountain
        "InnerSectGate": ("the inner sect gate", "mfpr", "gate",
                          ["Two stone lions guard the inner sect gate, their jaws worn smooth by a thousand nervous hands.",
                           "Beyond the carved inner gate the paths are swept cleaner and the disciples walk slower. Rank has a pace."]),
        "OuterSectHall": ("the outer sect hall", "mpr", "hall assembly",
                          ["The outer sect hall echoes with a hundred sandals and a deacon shouting names from a list.",
                           "Benches fill the outer sect hall in crooked rows. Someone has carved 'Wei Tong was here' into the last one."]),
        "MissionHall": ("the mission hall", "mpr", "hall assembly",
                        ["Notice boards cover every wall of the mission hall, sect tasks pinned three deep and fluttering in the draught.",
                         "Disciples crowd the mission hall's boards, arguing over which chores pay the most contribution for the least mud."]),
        "ContributionPavilion": ("the contribution pavilion", "mpr", "hall assembly",
                                 ["Behind the counter of the contribution pavilion, abacus beads clack like hail. Merit goes in; pills come out.",
                                  "A queue of tired disciples waits at the contribution pavilion, each clutching a tally of hard-earned points."]),
        "Refectory": ("the refectory", "mpr", "hall dorm",
                      ["The long refectory smells of rice, ginger and a hundred disciples who trained since dawn.",
                       "Steam rolls out of the refectory kitchens. Somewhere inside, a ladle strikes a pot like a gong."]),
        "OuterDormitories": ("the outer dormitories", "mgr", "dorm",
                             ["Rows of outer-disciple dormitories step down the lower terraces, bedding aired over every railing.",
                              "Snoring drifts from the outer dormitories. Somebody has hung a sword to dry next to their socks."]),
        "LaundryStream": ("the laundry stream", "mgdrf", "water dorm",
                          ["Grey robes flap on lines above the laundry stream. The water runs cold enough to wake a sleeping core.",
                           "Juniors kneel at the laundry stream, beating robes on the stones and trading rumours with every stroke."]),
        "MartialStage": ("the martial stage", "mfpr", "training arena",
                         ["The raised sparring stage is scarred with sword marks and scorched with the ghosts of old techniques.",
                          "Sand is raked smooth across the martial stage. It will not stay that way for long."]),
        "ArenaStands": ("the arena stands", "mrf", "training arena",
                        ["The stone stands around the arena are empty now, but you can almost hear the roar of the tournament.",
                         "Someone left a half-eaten bun on the arena stands. The sparrows are already negotiating over it."]),
        "BellTower": ("the bell tower", "mdpr", "high tower",
                      ["The great bell hangs silent in its tower on the east ridge, green with age and heavy as a promise.",
                       "From the bell tower you can see every roof of the sect, and the long road winding down to the world."]),
        "DrumTower": ("the drum tower", "mpr", "tower plaza",
                      ["The drum tower faces the bell across the plaza road. Its war drum is taller than two disciples.",
                       "A drumstick as thick as your arm leans against the drum tower's railing, polished by generations of palms."]),
        "FormationHall": ("the formation hall", "mpr", "array scholar hall",
                          ["Rune pillars ring the formation hall, each humming a different note. Together they make something like a chord.",
                           "Chalk diagrams cover the formation hall's floor. Three deacons argue over a single misplaced line."]),
        "TreasureTower": ("the treasure tower", "mpr", "tower hall",
                          ["The nine-storey treasure tower rises dark and windowless. Its doors have more locks than a steward has worries.",
                           "Wards shimmer over the treasure tower's doors. Artefacts older than the sect sleep behind them."]),
        "SwordPeakPath": ("the Sword Peak path", "mfr", "cliff high path",
                          ["The switchback path to Sword Peak clings to the rock. Old sword marks score the stone at every turn.",
                           "Wind moans along the Sword Peak path. Below, the sect shrinks to a scatter of grey roofs."]),
        "CableBridge": ("the chain bridge", "mpr", "cliff high bridge",
                        ["The chain bridge sways over the gorge. Every link sings a different note when the wind blows.",
                         "Far below the chain bridge, a river flashes silver between the rocks. You decide not to look again."]),
        "SwordPeak": ("the summit of Sword Peak", "mfdpr", "sword high cliff",
                      ["The summit of Sword Peak is a bare platform of stone and wind, with nothing between you and heaven.",
                       "On Sword Peak the air is thin and sharp. Even your breath feels like it could cut."]),
        "SwordTomb": ("the sword tomb", "mgdprf", "sword tomb",
                      ["Old blades stand in the rock of the sword tomb like a field of iron grass, each one a disciple's last oath.",
                       "In the sword tomb the rusted blades hum faintly as you pass, as if some of them still remember a name."]),
        "SwordWashPool": ("the sword-washing pool", "mdpr", "sword water",
                          ["The sword-washing pool lies still and grey. Rust trails curl in it like smoke from old battles.",
                           "Disciples kneel at the sword-washing pool, rinsing blades after the trials. The water tastes of iron."]),
        "MedicineValley": ("the medicine valley", "mgdprf", "medicine garden",
                           ["Terraces of medicinal plants climb the medicine valley, and the air is thick with mint, earth and bitter root.",
                            "Drying racks line the medicine valley, hung with herbs in every shade of green and brown."]),
        "PillKilnYard": ("the pill kiln yard", "mgpr", "medicine fire",
                         ["The great pill kilns glow in their yard like sleeping dragons, and the air shimmers with heat.",
                          "Ash drifts across the pill kiln yard. A kiln door opens with a roar, and a disciple ducks a gout of flame."]),
        "SpiritBeastGarden": ("the spirit beast garden", "mfgpr", "beast garden",
                              ["Spirit deer lift their heads in the beast garden's pens. A fat golden carp watches you from its pond.",
                               "The spirit beast garden smells of hay and ozone. Something in the far pen is chewing on a thunderbolt."]),
        "CraneRoost": ("the crane roost", "mdprf", "beast woods high",
                       ["Cranes stand on one leg among the high pines of the roost, watching you like disapproving elders.",
                        "Feathers drift down from the crane roost. One lands on your sleeve, light as a thought."]),
        "Waterfall": ("the Hundred-Chi Waterfall", "mgdrf", "water wild",
                      ["The Hundred-Chi Waterfall thunders into its pool, and the spray hangs in the air like a silver veil.",
                       "At the foot of the waterfall rainbows come and go in the mist. The roar is so loud it feels like silence."]),
        "WaterfallCave": ("the cave behind the waterfall", "dpr", "water quiet",
                          ["Behind the falling water the cave is dim and cool. Old meditation mats lie worn to the shape of their owners.",
                           "The waterfall's roar becomes a hush inside the cave. A single spirit lamp still burns in a niche."]),
        "AncestorTombs": ("the ancestral tombs", "mdpr", "tomb quiet",
                          ["Tortoise steles stand among the cypresses of the ancestral tombs, each carrying three hundred years of names.",
                           "Incense ash lies fresh on the ancestral altars. Someone has been here before you, and wept."]),
        "ReflectionCliff": ("the Cliff of Reflection", "mdpr", "cliff quiet",
                            ["The Cliff of Reflection is bare and cold. Disciples in confinement stare at the same stone for months.",
                             "Lines of old confessions are scratched into the Cliff of Reflection, some of them very small and very sorry."]),
        "TeaTerraces": ("the tea terraces", "mgdprf", "garden quiet",
                        ["The spirit tea terraces curve around the southern slope, glossy leaves catching the light in green waves.",
                         "Tea pickers move along the terraces with baskets on their backs, singing a song about a lazy dragon."]),
        "SpiritOrchard": ("the spirit peach orchard", "mgdprf", "garden",
                          ["Spirit peaches hang heavy and pink in the orchard. A sign says 'Counted daily. Signed, Steward Qian.'",
                           "Bees drunk on spirit nectar stagger through the peach orchard. The branches hum with them."]),
        "SunriseTerrace": ("the sunrise terrace", "mdprf", "cliff high quiet",
                           ["The sunrise terrace faces the east. Even at midday the stones hold a little of the dawn's warmth.",
                            "From the sunrise terrace the sea of clouds stretches gold to the edge of the world."]),
        "CoreDisciplesCourt": ("the core disciples' court", "mpr", "hall quiet",
                               ["Private cottages ring the core disciples' court, each with a tiny garden and a very firmly closed door.",
                                "The core disciples' court is quiet as a held breath. Somewhere, a sword hums through a slow form."]),
        "MountainRoad": ("the mountain road", "mfgr", "path wild",
                         ["The mountain road winds down toward the valley, cart ruts cut deep by three centuries of supplies.",
                          "Porters puff up the mountain road with baskets of rice. One of them waves at you, then regrets the effort."]),
        "StoneSteps": ("the long stone stairway", "mprf", "path plaza",
                       ["The long stone stairway climbs between the terraces. Every hundredth step carries a carved lucky cloud.",
                        "Juniors race up the stone stairway with buckets. Juniors walk down it very, very slowly."]),
    },
    # ------------------------------------------------------------------ the Whispering Bamboo Forest
    "bamboo_forest": {
        "ForestPath": ("the forest path", "mfr", "path wild",
                       ["The forest path winds between green columns of bamboo. Light falls in long, trembling bars.",
                        "Bamboo creaks overhead like an old house settling. The path ahead forks, and forks again."]),
        "OldBridge": ("the old bridge", "mfgr", "water bridge",
                      ["The old bridge sags over the stream. Every plank has a different opinion about your weight."]),
        "Stream": ("the stream", "mgr", "water wild",
                   ["The stream chatters over its stones, too busy to notice you."]),
        "HermitHut": ("the hermit's hut", "mr", "quiet",
                      ["Tea steam curls from the hermit's hut. It always does. Nobody has ever seen the fire."]),
        "HerbGrove": ("the herb grove", "mfgr", "herbs wild",
                      ["Sun pools in the herb grove. Spirit herbs glow faintly among the ferns, like embers in green ash."]),
        "SpiritSpring": ("the spirit spring", "mgdpr", "water sacred quiet",
                         ["The spirit spring lies still and clear. The lotus pads turn slowly toward you, then toward your pendant."]),
        "WolfDen": ("the wolf den", "fgr", "wild beast",
                    ["The wolf den gapes in the rock. Old bones, older claw marks, and a smell that makes the neck prickle."]),
        "BanditCamp": ("the old bandit camp", "fgpr", "camp",
                       ["The old bandit camp is ash and broken crates now. A rusted cage door creaks in the breeze."]),
        "BanditLookout": ("the lookout rock", "mdr", "high camp",
                          ["From the lookout rock the whole valley opens below, bamboo rolling like a green sea."]),
        "RuinsGate": ("the ruins gate", "mfgpr", "ruins",
                      ["The lotus archway of the ruins rises from the bamboo, its carved petals furred with moss."]),
        "AncientShrine": ("the ruined shrine", "mfdpr", "ruins sacred",
                          ["Broken pillars ring the old shrine. The stele at its heart has outlasted three hundred winters and one hermit."]),
        "RuinsInner": ("the ruins courtyard", "fpr", "ruins",
                       ["The green stone courtyard of the ruins is silent. Even the birds seem to land more carefully here."]),
        "Clearing": ("the clearing", "mfdr", "open wild",
                     ["The clearing opens like a held breath. Tall grass bends in a wind you cannot feel."]),
        # -- the expanded forest
        "WoodcutterCamp": ("the woodcutters' camp", "mfgpr", "camp village",
                           ["Split bamboo is stacked in pale towers around the woodcutters' camp. A saw pit yawns beside a cold fire.",
                            "Axes ring through the woodcutters' camp, and the smell of green sap is sharp enough to sneeze at."]),
        "CharcoalKilns": ("the charcoal kilns", "mfgpr", "camp fire",
                          ["The domed charcoal kilns smoulder in their hollow, and the air is thick enough to chew.",
                           "Soot-faced burners tend the charcoal kilns, poking vents with long poles and coughing politely."]),
        "BambooVillage": ("the bamboo village", "mgpr", "village",
                          ["Stilt houses of the bamboo village stand over the mud on long legs. Chickens patrol beneath them like guards.",
                           "Children in the bamboo village stop their game to stare at your robes, then bow all at once and giggle."]),
        "VillageShrine": ("the village shrine", "mdpr", "village sacred",
                          ["The earth-god shrine at the heart of the village is small and much loved, heaped with rice and paper flowers.",
                           "A clay earth god smiles from the village shrine, his nose rubbed shiny by a hundred hopeful thumbs."]),
        "MistyLake": ("the misty lake", "mfgdpr", "water lake",
                      ["Mist lies on the lake like a sleeping animal. Somewhere out on the water, an oar dips and is still.",
                       "The shore of the misty lake is soft and grey. The far bank comes and goes like a rumour."]),
        "LakePavilion": ("the lake pavilion", "mdpr", "water lake quiet",
                         ["The lake pavilion stands on stilts above the water, its boards silver with age and damp.",
                          "From the lake pavilion the mist looks close enough to touch. Fish nose at the pilings below."]),
        "Waterwheel": ("the waterwheel", "mgr", "water village",
                       ["The mill waterwheel creaks round and round, complaining about the stream in a voice like an old uncle.",
                        "Water spills from the paddles of the waterwheel in bright ribbons, and moss grows thick on its axle."]),
        "FishingJetty": ("the fishing jetty", "mgpr", "water lake village",
                         ["The fishing jetty juts into the lake on crooked piles. Nets hang drying like grey curtains.",
                          "A small boat knocks against the fishing jetty. Someone left a pipe on the last post, still warm."]),
        "PandaGrove": ("the giant bamboo grove", "mfgr", "wild beast",
                       ["Giant bamboo towers over the grove, thick as pillars. Something heavy has been chewing through the stems.",
                        "In the giant bamboo grove a black-and-white bear looks up from its meal, decides you are not food, and goes back to eating."]),
        "TigerRidge": ("the tiger ridge", "mfgr", "wild beast high",
                       ["Claw marks score the rocks of the ridge, deep enough to lay a hand in.",
                        "The wind on the tiger ridge carries a musky smell. Something large is watching from the long grass."]),
        "BanyanGiant": ("the giant banyan", "mdpr", "sacred quiet wild",
                        ["The giant banyan's roots form a hall of living pillars. Ribbons of old wishes flutter from its branches.",
                         "Under the giant banyan it is twilight at noon. The roots creak as if the tree were breathing."]),
        "SpiderHollow": ("the spider hollow", "fgpr", "dark wild",
                         ["Silk hangs in grey curtains across the spider hollow, and every thread trembles as you step in.",
                          "The spider hollow is cold and smells of old leaves. Wrapped shapes hang from the webs. You do not count them."]),
        "PoisonMarsh": ("the poison marsh", "fgr", "dark water",
                        ["Green bubbles rise and burst in the poison marsh. The reeds are the colour of old bruises.",
                         "Your eyes water at the edge of the poison marsh. Frogs with jewelled backs watch you without blinking."]),
        "MushroomRing": ("the mushroom ring", "mgdpr", "herbs sacred",
                         ["A ring of lingzhi mushrooms glows softly in the gloom, each cap as wide as a hand.",
                          "Spores drift like golden dust over the mushroom ring. The ground inside it feels warm."]),
        "ForestWatchpost": ("the forest watchpost", "mfpr", "camp high sect",
                            ["The sect's forest watchpost stands on stilts above the bamboo, a lantern hung at every corner.",
                             "A bored sentry leans over the watchpost railing, straightening hurriedly when he sees your robes."]),
        "HunterLodge": ("the hunter's lodge", "mgpr", "camp village",
                        ["Pelts dry on racks outside the hunter's lodge, and a row of traps hangs by the door like teeth.",
                         "Smoke curls from the hunter's lodge. Antlers and wolf skulls grin down from the eaves."]),
        "BuriedTemple": ("the buried temple", "mfgpr", "ruins sacred",
                         ["The buried temple leans out of the earth, half its roof swallowed by roots as thick as dragons.",
                          "Stone guardians flank the buried temple's steps, their faces worn blank by centuries of rain."]),
        "TempleUndercroft": ("the sunken courtyard", "fpr", "ruins dark",
                             ["The sunken courtyard before the buried temple is cold and dim. Water drips from the roots overhead.",
                              "Carved pillars stand half-drowned in earth around the sunken courtyard. Something scratches behind the doors."]),
        "StoneBuddhas": ("the carved buddhas", "mdpr", "sacred cliff quiet",
                         ["Weathered stone buddhas gaze out from the cliff face, their smiles softened by three hundred years of rain.",
                          "Offerings of wild fruit lie at the feet of the carved buddhas. Moss has made them green robes."]),
        "CliffPath": ("the cliff path", "mfr", "cliff path",
                      ["The cliff path is barely a shoulder wide. Carved buddhas watch your every careful step.",
                       "Wind pushes at you on the cliff path. Far below, the bamboo sways like a green sea."]),
        "WaterfallGorge": ("the waterfall gorge", "mfgdr", "water wild",
                           ["The stream leaps into the gorge in a white roar, and the pool below churns like boiling jade.",
                            "Spray drifts up from the waterfall gorge, cold on your face. Ferns cling to every ledge."]),
        "ForestCrossroads": ("the forest crossroads", "mfpr", "path",
                             ["A wayside shrine marks the forest crossroads, a stub of incense still smoking before it.",
                              "Four paths meet at the crossroads. Someone has scratched arrows and warnings into the shrine post."]),
        "OldBattlefield": ("the old battlefield", "mfgpr", "ruins open",
                           ["Rusted spearheads poke from the grass of the old battlefield, and low mounds mark where the dead were laid.",
                            "Nothing sings on the old battlefield. The bamboo grows thin here, as if it remembered."]),
        "HiddenValley": ("the hidden valley", "mgdpr", "open quiet",
                         ["The hidden valley opens in a blaze of wild plum, pink and white, humming with bees.",
                          "In the hidden valley the air is so still you can hear petals land on the grass."]),
        "EchoCave": ("the echo cave", "fgpr", "dark",
                     ["The mouth of the echo cave throws your footsteps back at you, a heartbeat late.",
                      "Cold air breathes out of the echo cave. Somewhere inside, a voice that sounds like yours says hello."]),
        "SmugglersTrail": ("the smugglers' trail", "mfgpr", "path camp",
                           ["The smugglers' trail twists through the thickest bamboo, marked only by knotted cords and cut stems.",
                            "Cart ruts that should not exist run along the smugglers' trail, pressed deep by heavy loads."]),
        "RopeBridge": ("the rope bridge", "mpr", "bridge water high",
                       ["The rope bridge swings over the waterfall gorge. The planks are new. The ropes are not.",
                        "Halfway across the rope bridge, spray soaks your sleeves and the whole world sways."]),
        "AlchemistCottage": ("the alchemist's cottage", "mgpr", "herbs village",
                             ["Drying racks crowd the alchemist's cottage, and the smoke from its chimney smells of liquorice and scorched hair.",
                              "Jars of pickled roots line the alchemist's windowsill. One of them appears to be pickled back at you."]),
        "SacredSpring": ("the sacred spring", "mdpr", "water sacred",
                         ["The sacred spring rises within a low stone wall, and the villagers' paper prayers float on its surface.",
                          "The water of the sacred spring is so clear it looks like air. Coins glint on the bottom."]),
        "ForestGate": ("the far forest gate", "mfpr", "gate path",
                       ["The far forest gate is two old stone posts and a crossbeam carved with a faded road-blessing.",
                        "Past the forest gate the road runs south, out of the bamboo and into the wide world."]),
    },
    # ------------------------------------------------------------------ Qingshi Town
    "qingshi_town": {
        "TownGate": ("the town gate", "mfpr", "gate",
                     ["The town gate is scarred and patched, and the gate guards salute a little too eagerly."]),
        "MainStreet": ("the main street", "mfgr", "street",
                       ["Qingshi's main street bustles: noodle sellers, water carriers, a dog stealing a dumpling with great dignity.",
                        "Shutters are open on the main street today. People nod at your robes instead of hiding from them."]),
        "MarketSquare": ("the market square", "mfgr", "market street",
                         ["The market square is a riot of awnings and haggling. Somebody is selling 'genuine immortal sandals'."]),
        "Inn": ("the Drunken Crane", "mr", "street", []),
        "Well": ("the town well", "mpr", "street",
                 ["The town well is ringed with gossip and wet stones. Widow Liu's bucket hangs ready."]),
        "MagistrateHall": ("the yamen", "mpr", "official", []),
        "Temple": ("the town temple", "mdpr", "sacred",
                   ["The town temple smells of clean incense. A sparrow nests in the eaves, bold as a magistrate."]),
        "Riverside": ("the docks", "mfgrp", "river",
                      ["The Qing River slides past the docks, brown and patient. Old Pan's ferry creaks at its rope."]),
        "BackAlley": ("the back alley", "mfgr", "alley",
                      ["The back alley is narrow and damp, and every window in it is watching you."]),
        "Warehouse": ("the guild warehouse", "mfgpr", "trade river",
                      ["Crates stand in towers across the guild warehouse yard, every one stamped twice and counted thrice."]),
        "Graveyard": ("the hill graves", "mfgdpr", "tomb",
                      ["The hill graves are quiet now. Fresh flowers lie on the tablets, and the blood-ink is long gone."]),
        "Farmland": ("the terraced fields", "mfgrp", "fields",
                     ["The terraced fields step down to the river. Farmers straighten, shade their eyes, and wave."]),
        "WatchTower": ("the watchtower", "mdrp", "gate high",
                       ["From the watchtower the fields stretch gold to the hills, and the road runs white toward the mountain."]),
        # -- the expanded town
        "NorthGate": ("the north gate", "mfpr", "gate",
                      ["The north gate of the new walls smells of fresh lime and old fear. Its drum hangs ready by the arch.",
                       "Carts queue at the north gate while a clerk squints at every seal and sighs at every bribe."]),
        "EastGate": ("the east gate", "mfr", "gate fields",
                     ["The east gate opens onto the farmlands. Farmers pass through with hoes on their shoulders and mud to the knee.",
                      "Beyond the east gate the fields roll away in stripes of green and gold."]),
        "SouthMarket": ("the night market", "mfgpr", "market street",
                        ["Paper lanterns bob over the southern night market, and the smell of fried dough could stop a sword.",
                         "Hawkers in the night market cry their wares under the lanterns: crickets, charms, and skewers of something brown."]),
        "Granary": ("the county granary", "mgpr", "official trade",
                    ["The county granary squats on its stone plinth, its doors sealed with the magistrate's red paper.",
                     "Sparrows hop around the granary steps, hoping someone will be careless with a sack."]),
        "SilkWorkshop": ("the silk workshop", "mgpr", "craft",
                         ["Looms clack in the silk workshop like a hundred patient crickets. Colour runs through every hand.",
                          "Weavers glance up from their looms in the silk workshop, then back down. The thread waits for no one."]),
        "DyeYard": ("the dye yard", "mgpr", "craft river",
                    ["Lengths of cloth hang in the dye yard in indigo, madder and saffron, snapping like banners.",
                     "The vats of the dye yard steam. The dyers' arms are blue to the elbow."]),
        "Pharmacy": ("the Wang pharmacy", "mgpr", "craft official",
                     ["Hundreds of little drawers line the great pharmacy, each labelled in a neat, anxious hand.",
                      "The Wang pharmacy smells of liquorice root and ginseng. A clerk grinds something that crunches."]),
        "Academy": ("the county academy", "mdpr", "scholar",
                    ["Students recite the classics in the county academy, their voices rising and falling like a slow sea.",
                     "Ink stains every step of the academy. A scholar walks past reading a scroll and colliding with nothing, somehow."]),
        "ExamHall": ("the examination cells", "mpr", "scholar",
                     ["The examination cells stand in long rows, each barely big enough for a desk and a nervous young man.",
                      "Graffiti of despair covers the examination cells. 'Third attempt' reads one. 'Fourth' reads the next."]),
        "MerchantManor": ("the guild master's manor", "mpr", "trade wealthy",
                          ["Two stone lions guard the manor gate of the guild master, polished to a gloss by nervous servants.",
                           "Red lanterns hang over the manor gate. Every visitor's name is written in a book before they may knock."]),
        "ManorGarden": ("the manor garden", "mdpr", "wealthy quiet",
                        ["A rockery of Taihu stones rises over the manor garden pond, where fat carp idle like rich uncles.",
                         "The manor garden is so perfectly arranged it feels rude to breathe in it."]),
        "OperaStage": ("the opera stage", "mfpr", "fair",
                       ["The open-air opera stage is hung with painted cloths. A drum waits at its side for the next performance.",
                        "An actor in half his face paint practises a death scene on the opera stage. It is very long."]),
        "TempleFair": ("the temple fair", "mfgpr", "fair market",
                       ["Stalls crowd the temple fair square: sugar figures, fortune tellers, a man juggling live fish.",
                        "The temple fair roars with drums and laughter, and a wishing tree sags under a thousand red ribbons."]),
        "CityGodTemple": ("the City God temple", "mdpr", "sacred official",
                          ["Incense smoke fills the City God temple's court. The painted god glares down at liars, sternly impartial.",
                           "Petitioners kneel in the City God temple, burning paper money for relatives and complaints for rivals."]),
        "BellPavilion": ("the bell pavilion", "mpr", "street official",
                         ["The drum-and-bell pavilion straddles the crossroads. Its bell tolls the hours for the whole of Qingshi.",
                          "A keeper dozes under the bell pavilion's eaves, one hand still on the rope."]),
        "Bathhouse": ("the public bathhouse", "mr", "street",
                      ["Steam drifts out of the public bathhouse, and with it the sound of someone singing very badly.",
                       "Towels hang drying outside the bathhouse. A cat sits on the warm stones, supremely content."]),
        "Pawnshop": ("the pawnshop", "mpr", "trade alley",
                     ["The pawnshop's counter stands taller than a man, so the owner can look down on everyone's treasures.",
                      "Pledged swords, a wedding hairpin, a lute with one string: the pawnshop window is a museum of bad luck."]),
        "Tavern": ("the riverside tavern", "mfpr", "river alley",
                   ["The riverside tavern is loud even at noon. Someone is arm-wrestling a boatman and losing money on it.",
                    "Wine fumes and river fog mix at the tavern door. A drunk salutes you with a chicken leg."]),
        "Brewery": ("the brewery", "mgpr", "craft",
                    ["Great jars of rice wine stand in rows at the brewery, sealed with clay and sleeping like fat monks.",
                     "The brewery smells sweet and sour at once. A brewer taps a jar and listens to it like a physician."]),
        "Mill": ("the watermill", "mgr", "river craft",
                 ["The watermill grinds at the river bend, and flour hangs in the air like a fine, sneezy fog.",
                  "Water thunders under the mill wheel. The miller shouts every word, because he has forgotten how not to."]),
        "BoatYard": ("the boat yard", "mfgpr", "river craft",
                     ["Half-built hulls lie like fish skeletons in the boat yard, and the smell of tar is everywhere.",
                      "Shipwrights hammer in the boat yard, pausing only to argue about wood."]),
        "LowerDocks": ("the lower docks", "mfgpr", "river trade",
                       ["Grain barges crowd the lower docks, and porters trot up and down the gangplanks with sacks on their heads.",
                        "The lower docks smell of fish, tar and river mud. Gulls argue over everything."]),
        "StoneBridgeTown": ("the humpbacked bridge", "mdr", "river street",
                            ["The humpbacked stone bridge arches over the canal, its lions worn smooth by generations of children.",
                             "From the top of the stone bridge you can see boats sliding under you like slow thoughts."]),
        "Canal": ("the canal walk", "mdr", "river quiet",
                  ["Willows trail their hair in the canal. A washerwoman beats cloth on the steps and hums.",
                   "The canal walk is quiet and green. Lantern boats drift past, even by day."]),
        "Orphanage": ("the temple orphanage", "mgrp", "sacred",
                      ["Children chase each other round the temple orphanage courtyard, shrieking like happy sparrows.",
                       "Washing hangs across the orphanage courtyard, dozens of tiny tunics in a row."]),
        "PostStation": ("the post station", "mpr", "official gate",
                        ["Horses stamp in the post station stables. A rider in a dusty coat gulps water and gallops off again.",
                         "The post station's board is pinned with notices: wanted men, lost oxen, a reward for a runaway goose."]),
        "Barracks": ("the militia barracks", "mfpr", "official gate",
                     ["The county militia drills in the barracks yard, spears wobbling, a sergeant bellowing counts.",
                      "Straw targets stand in the barracks yard, bristling with arrows mostly nowhere near the centre."]),
        "ExecutionGround": ("the execution ground", "mfpr", "official tomb",
                            ["Nothing grows on the execution ground outside the west wall. Crows sit on the post and wait.",
                             "A faded proclamation flaps on the execution ground's board, listing crimes nobody likes to read aloud."]),
        "Tannery": ("the tannery", "mfgr", "craft river",
                    ["The tannery stinks so hard your eyes water. The tanners grin at you, immune and amused.",
                     "Hides soak in the tannery pits downstream of everything else, and the river here runs brown."]),
        "Kilns": ("the pottery kilns", "mfgr", "craft",
                  ["The pottery kilns glow on the clay bank, and rows of fresh bowls dry in the sun like pale mushrooms.",
                   "A potter at the kilns wipes clay on her apron and nods at you without stopping her wheel."]),
    },
    # ------------------------------------------------------------------ the Blood Moon Abyss
    "blood_abyss": {
        "CanyonEntrance": ("the canyon mouth", "mfrp", "canyon",
                           ["The crimson canyon opens its mouth. Warm, wet air rises from below, tasting of copper."]),
        "BoneField": ("the field of bones", "mfgdr", "bones open",
                      ["Bones crunch underfoot on the old plain. Dead trees claw at a sky the colour of a bruise.",
                       "The field of bones is silent. Even the wind here walks carefully."]),
        "BloodPools": ("the blood pools", "mfgdr", "blood water",
                       ["The blood pools steam and bubble. Pale lotus grows in them, beautiful and wrong."]),
        "ObeliskRing": ("the obelisk ring", "mfgpr", "ritual",
                        ["The broken obelisks lean together like old men sharing a secret."]),
        "PrisonCages": ("the old cages", "", "fortress prison",
                        ["The iron cages hang empty, their doors bent outward. Scratched tallies cover the bars."]),
        "DemonCamp": ("the war camp", "mfgpr", "camp",
                      ["The war camp's banners hang slack. The drums are silent, but the stone remembers them."]),
        "DemonGate": ("the black gate", "", "fortress", []),
        "FortressCourt": ("the fortress court", "", "fortress", []),
        "AltarOfBlood": ("the altar", "", "fortress", []),
        "PatriarchThrone": ("the throne", "", "fortress", []),
        "HeartMirror": ("the Heart Mirror", "fdpr", "ritual water",
                        ["The Heart Mirror lies still and black. You do not look into it for long."]),
        "AbyssDepths": ("the abyss depths", "mfdr", "deep open",
                        ["At the bottom of the abyss the darkness is so thick it feels like weather."]),
        # -- the expanded abyss
        "BloodRiver": ("the blood river", "mfgr", "blood water",
                       ["The river of blood slides past thick and slow, and things that are not fish move beneath its skin.",
                        "Red mist hangs over the blood river. The banks are stained to the height of a man's shoulder."]),
        "BoneBridge": ("the bone bridge", "mfpr", "bones bridge",
                       ["The bone bridge is built from the ribs of something vast. It creaks like a ship with every step.",
                        "Halfway across the bone bridge, the river of blood gurgles below as if it were hungry."]),
        "SlaveMines": ("the slave mines", "mfgpr", "prison camp",
                       ["Tunnels honeycomb the canyon wall at the slave mines, and broken chains trail from every entrance.",
                        "Pickaxes lie where they were dropped at the slave mines. The rock is scored with thousands of tally marks."]),
        "MineShaft": ("the deep mine shaft", "fgpr", "deep prison",
                      ["The deepest shaft drops into blackness. A winch creaks above it, its chain disappearing into the dark.",
                       "Cold air rises from the mine shaft, carrying the faint sound of picks that nobody is swinging."]),
        "ForgeOfSouls": ("the soul forge", "mfgpr", "fire ritual",
                         ["The bellows of the soul forge heave by themselves, and every breath of them sounds like a scream.",
                          "Sparks the colour of old blood fly from the soul forge's anvil. The heat smells of burned prayers."]),
        "Barracks": ("the black barracks", "mfgpr", "camp",
                     ["Black tents stand in grim rows at the Blood Moon barracks, their banners stitched with red moons.",
                      "Weapon racks and cold cookfires fill the black barracks. Someone scratched a tally of kills into a pole."]),
        "TrainingPit": ("the training pit", "fpr", "camp open",
                        ["The training pit is a ring of blood-dark sand. Chains hang from its walls for those who lose.",
                         "Old bones lie half-raked into the sand of the training pit. The Blood Moon trains without mercy."]),
        "BeastPens": ("the beast pens", "fgpr", "beast prison",
                      ["Corrupted beasts pace in the pens, their eyes red as coals, their ribs showing through mangy fur.",
                       "The beast pens stink of rot and rage. Claw marks scar the bars from the inside."]),
        "PoisonGarden": ("the poison garden", "fgpr", "blood herbs",
                         ["Flowers of violet and black bloom in the poison garden, lovely enough to stop your heart. Literally.",
                          "The poison garden hums with fat flies. Every leaf here has killed somebody."]),
        "SkullTower": ("the skull tower", "fpr", "bones high",
                       ["The tower of skulls stands on its spur of rock, thousands of empty eyes turned toward the canyon.",
                        "Wind whistles through the skull tower, and for a moment it sounds like thousands of people breathing."]),
        "WailingCliffs": ("the wailing cliffs", "mfdr", "canyon high",
                          ["The wind screams through the wailing cliffs in voices almost human. You try not to listen to the words.",
                           "At the wailing cliffs the rock is riddled with holes, and every hole has something to say."]),
        "AshPlains": ("the ash plains", "mfgdr", "open",
                      ["Grey ash stretches to the canyon walls under the red moon, soft as snow and silent as a grave.",
                       "Your footprints fill in behind you on the ash plains, as if you had never been here."]),
        "LavaFalls": ("the lava falls", "mfgr", "fire deep",
                      ["Molten rock pours over the lip of the canyon in a slow, glowing fall. The heat pushes like a hand.",
                       "The lava falls roar softly, and the air shimmers so hard the far wall ripples."]),
        "ObsidianSpires": ("the obsidian spires", "mfgpr", "ritual open",
                           ["Black glass spires rise in a forest, each one reflecting you a little wrongly.",
                            "The obsidian spires ring faintly as you pass between them, like glasses touched in a toast."]),
        "SacrificePit": ("the sacrificial pit", "fpr", "ritual blood",
                         ["Chains ring the sacrificial pit, their iron bitten by years of struggle. The bottom is lost in dark.",
                          "The sacrificial pit breathes out a warm, sweet stink. Something at the bottom is still moving."]),
        "DemonLibrary": ("the forbidden library", "mgpr", "scholar ritual",
                         ["Scroll racks sag under the weight of forbidden techniques in the Blood Moon's library. The dust has teeth.",
                          "Every scroll in the forbidden library is chained. Some of the chains are straining."]),
        "ElderPalace": ("the palace of the elders", "mfpr", "fortress wealthy",
                        ["The palace of the demon elders is all black lacquer and red silk, beautiful as a wound.",
                         "Jade screens line the elders' palace, painted with scenes you look away from."]),
        "ShadowMarket": ("the shadow market", "mgpr", "market camp",
                         ["Hooded traders murmur in the shadow market, selling pills, poisons and souls by the jin.",
                          "Lanterns of human skin light the shadow market. The haggling is quiet and very polite."]),
        "BloodMoonShrine": ("the Blood Moon shrine", "mdpr", "ritual sacred",
                            ["The Blood Moon's shrine stands open to the sky. Offerings of dried blood crust its steps.",
                             "Red moonlight pours into the open shrine and pools on its altar like something spilled."]),
        "CorpseForest": ("the corpse forest", "fgpr", "dark bones",
                         ["Black trees stand in the corpse forest, and from their branches hang things you decide are sacks.",
                          "Soul lanterns flicker among the black trees of the corpse forest. Each flame is someone."]),
        "RuinedSectGate": ("the ruined sect gate", "mfpr", "ruins gate",
                           ["The ruined gate of a destroyed sect still stands, its name chiselled off by some thorough hand.",
                            "Scorched stone lions guard a gate to nothing. Beyond them, only ash and a burned path."]),
        "RuinedSectHall": ("the burned hall", "mfpr", "ruins",
                           ["The burned hall's roof is gone. Ancestral tablets lie in the ash where they fell, their names cracked.",
                            "Charred pillars stand in the burned hall like the fingers of a buried hand."]),
        "ChainBridge": ("the chain bridge", "mpr", "bridge deep",
                        ["The chain bridge spans a chasm with no bottom. Links as thick as your waist groan at every gust.",
                         "Anchors of black iron hold the chain bridge to the rock. Old blood has rusted into the links."]),
        "WatchSpire": ("the watch spire", "mdpr", "high camp",
                       ["From the watch spire the whole abyss unrolls below: rivers of blood, black tents, fires in the dark.",
                        "A map table stands in the watch spire, pinned with red flags that mark where the sect's scouts died."]),
        "SealStones": ("the seal stones", "mdpr", "ritual sacred",
                       ["The old seal stones of the Verdant Lotus stand in a ring, their carved lotuses still faintly green.",
                        "Your pendant warms among the seal stones. They remember a hand like yours."]),
        "GhostVillage": ("the ghost village", "mfgpr", "ruins dark",
                         ["Empty houses line the ghost village street. Doors stand open, bowls wait on tables, and nobody is home.",
                          "Pale shapes drift at the edge of sight in the ghost village. When you turn, only the wind moves."]),
        "RedMoonTerrace": ("the red moon terrace", "mdpr", "ritual high",
                           ["The red moon hangs so close over its terrace that you could count its scars.",
                            "On the red moon terrace your shadow is red too, and it moves a moment after you do."]),
        "CaveOfEchoes": ("the cave of echoes", "fdpr", "dark deep",
                         ["The cave of echoes repeats your breathing, then your heartbeat, then something you only thought.",
                          "Water drips in the cave of echoes. Every drop comes back as a whisper of your name."]),
        "SulphurVents": ("the sulphur vents", "fgr", "fire open",
                         ["Yellow vents hiss steam across the rock. The stink of sulphur makes your eyes run.",
                          "The ground near the sulphur vents is warm and crusted yellow. It crunches like old sugar."]),
        "BoneThrone": ("the bone throne", "fpr", "bones ritual",
                       ["The first patriarch's throne of bones sits alone on its dais, crusted with the dust of centuries.",
                        "Skulls grin from the arms of the bone throne. The seat is worn smooth by a long-dead weight."]),
    },
    # ------------------------------------------------------------------ the Celestial Sky Isles
    "sky_isles": {
        "CloudGate": ("the cloud gate", "mdr", "gate open",
                      ["The stone cloud gate frames nothing but sky, as if heaven were a room next door."]),
        "JadeBridge": ("the jade bridge", "mfr", "bridge",
                       ["The jade bridge stretches over nothing at all, and the wind tests every step."]),
        "IsleOfWinds": ("the Isle of Winds", "mfgdr", "wind open",
                        ["The pines of the Isle of Winds bow and rise, bow and rise, as if in endless greeting."]),
        "StarPavilion": ("the star pavilion", "mpr", "stars", []),
        "CelestialRuins": ("the celestial ruins", "mfgdpr", "ruins palace",
                           ["Broken palace columns tower into the clouds, still warm from a fall ten thousand years ago."]),
        "SerpentLair": ("the serpent's isle", "fpr", "open wild",
                        ["The serpent's isle is scarred with old coils. Storm-grey scales glint in the grass."]),
        "SpiritVein": ("the spirit vein", "fgpr", "crystal",
                       ["Crystals jut from the spirit vein, humming a note just below hearing."]),
        "ImmortalGarden": ("the immortal garden", "mfgr", "garden",
                           ["Blossom trees taller than pagodas drop petals like warm snow on the immortal garden."]),
        # -- the expanded sky isles
        "CrystalIsle": ("the crystal isle", "mfgpr", "crystal",
                        ["The crystal isle sings as the wind moves through it, a hundred clear notes that never quite make a tune.",
                         "Light breaks into colours across the crystal isle. Your shadow is a rainbow here."]),
        "LotusLake": ("the golden lotus lake", "mgdr", "water garden",
                      ["Golden lotuses float on the high lake, each as wide as a cart wheel and warm to the touch.",
                       "The lotus lake is so still the clouds seem to have been painted on it."]),
        "WaterfallIsle": ("the waterfall isle", "mgdpr", "water",
                          ["A waterfall pours off the edge of its isle and falls forever into the sea of clouds.",
                           "Spray from the waterfall isle drifts upward here, glittering, as if the water had changed its mind."]),
        "PhoenixNest": ("the phoenix nest", "mfgr", "fire high",
                        ["The great phoenix nest crowns a burnt crag, a tangle of blackened branches still warm at the heart.",
                         "Scorched feathers as long as spears lie around the phoenix nest, glowing faintly at the tips."]),
        "CraneIsle": ("the crane isle", "mgdpr", "beast garden",
                      ["Celestial cranes stalk the shallows of their isle, white as snow, their crowns red as a seal.",
                       "On the crane isle a hundred cranes turn their heads to look at you at once. It is unsettling."]),
        "MoonIsle": ("the moon isle", "mdpr", "quiet stars",
                     ["Silver sand covers the moon isle, and a pale moon hangs over it even at noon.",
                      "Footprints glow faintly on the silver sand of the moon isle, then fade like forgotten words."]),
        "SunAltar": ("the sun altar", "mfdpr", "ritual palace",
                     ["The golden sun altar blazes even under cloud. The stone is too hot to touch for long.",
                      "Sun-glyphs circle the golden altar, each one a hymn that nobody alive can sing."]),
        "ThunderIsle": ("the thunder isle", "fgpr", "storm",
                        ["Lightning walks on the thunder isle. Every hair on your arms stands up and salutes it.",
                         "The rocks of the thunder isle are glassy where bolts have struck them, again and again."]),
        "RainbowBridge": ("the rainbow bridge", "mfr", "bridge",
                          ["The bridge of seven-coloured light hums under your feet. It feels solid. It does not look it.",
                           "Halfway across the rainbow bridge the colours shift, and for a moment you walk on blue."]),
        "ChainIsles": ("the chain isles", "mfpr", "bridge open",
                       ["Small isles hang in a chain, linked by stepping stones that drift a little whenever you look away.",
                        "Rusted anchors hold the chain isles together. One of the chains is snapped and swaying."]),
        "ImmortalPalace": ("the Immortal Palace gate", "mfpr", "palace gate",
                           ["The gate of the Immortal Palace towers over you, white jade guarded by lions with sapphire eyes.",
                            "Cloud-servants sweep the Immortal Palace steps with brooms of light, never raising their eyes."]),
        "PalaceCourt": ("the palace court", "mfpr", "palace",
                        ["The palace's inner court is white jade from wall to wall, so clean it reflects the sky.",
                         "Bronze tripods smoke in the palace court, and jade screens stand in rows like silent courtiers."]),
        "HallOfRecords": ("the hall of records", "mpr", "scholar palace",
                          ["Scroll racks in the hall of heavenly records climb into the clouds, each tagged with a star.",
                           "In the hall of records, a brush writes by itself on a scroll that never ends."]),
        "StarObservatory": ("the star observatory", "mdpr", "stars high",
                            ["The armillary observatory crowns its spire, bronze rings turning slowly around nothing at all.",
                             "At the top of the observatory the stars are close enough to make you duck."]),
        "WindTemple": ("the temple of the four winds", "mdpr", "wind sacred",
                       ["The temple of the four winds has no walls, only pillars and a bell that rings with every gust.",
                        "Four winds meet in the temple and sit down together, briefly, like old friends."]),
        "CloudHarbour": ("the cloud harbour", "mfgpr", "harbour",
                         ["Empty moorings line the cloud harbour where sky ships once docked, chains trailing into the cloud sea.",
                          "Rotted gangplanks hang from the cloud harbour's piers. A harbourmaster's bell still waits for a ship."]),
        "SkyShipWreck": ("the sky ship wreck", "mfgpr", "harbour ruins",
                         ["A wrecked sky ship lies on its side on a lonely isle, sails of cloud silk rotting on its masts.",
                          "The sky ship's hull is split like a nutshell. Charts and crates spill from the gap."]),
        "DragonBones": ("the dragon bones", "mfgpr", "bones open",
                        ["The bleached bones of a true dragon curve across the isle like the ribs of a fallen temple.",
                         "Wind whistles through the dragon's skull. The sound is almost a word."]),
        "PeachGarden": ("the peach garden", "mgdpr", "garden",
                        ["Peaches of immortality hang in the heavenly garden, glowing like little suns. Nobody is watching them. Supposedly.",
                         "The peach garden smells so sweet it makes your eyes water. A sign reads 'Counted every thousand years.'"]),
        "JadeTerraces": ("the jade terraces", "mgpr", "garden fields",
                         ["Spirit servants tend the jade rice terraces, their sleeves rolled, their feet never quite touching the water.",
                          "The jade terraces shine green and white. Each grain of rice glows like a tiny pearl."]),
        "HermitIsle": ("the hermit's isle", "mdr", "quiet",
                       ["A single hut sits on the hermit's isle, with a kettle on the step and a note: 'Out. Or in. Knock.'",
                        "The hermit's isle is barely big enough to turn around on. Somehow a pine has found room."]),
        "MirrorLake": ("the mirror lake", "mdpr", "water quiet",
                       ["The mirror lake reflects the sky so perfectly that you cannot tell where the water ends.",
                        "Your reflection in the mirror lake blinks a moment after you do. You decide not to mention it."]),
        "FloatingForest": ("the floating forest", "mfgpr", "wild garden",
                           ["Trees float above their isle, roots dangling in the air like the beards of old men.",
                            "In the floating forest the leaves fall upward, drifting into the clouds like green snow."]),
        "SealOfHeaven": ("the Seal of Heaven", "mdpr", "ritual sacred",
                         ["The Seal of Heaven is a disc of stone so large the isle seems built around it, carved with a single word.",
                          "The great stone disc of the Seal of Heaven is cold and faintly humming, like a held note."]),
        "GateOfHeaven": ("the Southern Gate of Heaven", "mfpr", "palace gate",
                         ["The Southern Gate of Heaven stands closed, as it has for an age. Its guardians have moss on their shoulders.",
                          "Wind moans through the cracks of the Southern Gate of Heaven. It sounds like distant laughter."]),
        "SwordIsle": ("the sword isle", "mfgpr", "sword high",
                      ["Flying swords circle the spire of the sword isle like a flock of silver birds, humming in formation.",
                       "One of the circling swords dips to look at you, considers, and rejoins the flock."]),
        "ElixirSpring": ("the elixir spring", "mgdpr", "water sacred",
                         ["The spring of the elixir of life bubbles softly, and the moss around it is greener than green.",
                          "A cup of carved jade waits beside the elixir spring. Nobody has touched it in a thousand years."]),
        "StormCloudPlateau": ("the storm plateau", "mfgdpr", "storm open",
                              ["The plateau floats above a sea of storm clouds that flash and grumble beneath your feet.",
                               "Rune pillars stand on the storm plateau, drinking the lightning that crawls up from below."]),
        "LanternIsle": ("the lantern isle", "mgdpr", "stars quiet",
                        ["Sky lanterns float over their isle in their thousands, each one carrying a wish nobody has granted.",
                         "The lantern isle glows gold and red. A lantern drifts close and bumps your shoulder, gently."]),
        "TreeOfAges": ("the Tree of Ages", "mdpr", "sacred garden",
                       ["The Tree of Ages rises until its crown is lost among the stars. Its bark is warm, like skin.",
                        "Wishing ribbons from every age hang from the Tree of Ages. Some are written in scripts no one reads now."]),
    },
}

# ---------------------------------------------------------------- props and items that belong somewhere

PROPS_AT = {
    "sect": {
        "SectGate": ["stone_stele", "bronze_bell"], "FormationArray": ["seal", "rune_pillar"],
        "MainHall": ["ancestral_tablet"], "TrainingGround": ["puppet_frame"], "Pavilion": ["scroll_rack"],
        "Pagoda": ["scroll_rack", "jade_slip"], "PlumGarden": ["wishing_tree"], "HerbGarden": ["herb_drying_rack"],
        "ScholarRock": ["stone_stele"], "InnerSectGate": ["guardian_lion"], "OuterSectHall": ["notice_board", "war_drum"],
        "MissionHall": ["notice_board", "abacus_desk"], "ContributionPavilion": ["abacus_desk", "notice_board"],
        "Refectory": ["bronze_ding"], "MartialStage": ["war_drum", "puppet_frame"], "BellTower": ["bronze_bell"],
        "DrumTower": ["war_drum"], "FormationHall": ["rune_pillar", "stone_tablet_array"],
        "TreasureTower": ["treasure_chest", "jade_screen"], "CableBridge": ["chain_anchor"],
        "SwordPeak": ["sword_in_stone"], "SwordTomb": ["sword_in_stone"], "SwordWashPool": ["spirit_fountain"],
        "MedicineValley": ["herb_drying_rack", "medicine_cabinet"], "PillKilnYard": ["pill_furnace"],
        "SpiritBeastGarden": ["prison_cage"], "CraneRoost": ["crane_statue"], "WaterfallCave": ["spirit_lamp"],
        "AncestorTombs": ["tortoise_stele", "ancestral_tablet", "offering_table"],
        "ReflectionCliff": ["stone_stele", "spirit_lamp"], "TeaTerraces": ["herb_drying_rack"],
        "SpiritOrchard": ["wishing_tree"], "SunriseTerrace": ["bronze_ding"], "CoreDisciplesCourt": ["jade_screen"],
        "StoneSteps": ["guardian_lion"],
    },
    "bamboo_forest": {
        "SpiritSpring": ["spirit_fountain"], "BanditCamp": ["treasure_chest", "map_table"],
        "RuinsGate": ["guardian_lion"], "AncientShrine": ["stone_stele"], "RuinsInner": ["rune_pillar"],
        "WoodcutterCamp": ["map_table"], "CharcoalKilns": ["treasure_chest"], "BambooVillage": ["loom", "wine_jars"],
        "VillageShrine": ["offering_table", "ancestral_tablet"], "MistyLake": ["fishing_boat"],
        "LakePavilion": ["bronze_mirror"], "FishingJetty": ["fishing_boat"], "BanyanGiant": ["wishing_tree"],
        "SpiderHollow": ["sealed_coffin"], "MushroomRing": ["spirit_lamp"],
        "ForestWatchpost": ["map_table", "war_drum"], "HunterLodge": ["herb_drying_rack", "map_table"],
        "BuriedTemple": ["guardian_lion", "stone_tablet_array"], "TempleUndercroft": ["sealed_coffin", "rune_pillar"],
        "StoneBuddhas": ["offering_table"], "ForestCrossroads": ["offering_table"],
        "OldBattlefield": ["war_drum", "sword_in_stone"], "HiddenValley": ["wishing_tree"], "EchoCave": ["soul_lantern"],
        "SmugglersTrail": ["treasure_chest"], "RopeBridge": ["chain_anchor"],
        "AlchemistCottage": ["pill_furnace", "medicine_cabinet", "herb_drying_rack"], "SacredSpring": ["spirit_fountain"],
        "ForestGate": ["stone_stele"],
    },
    "qingshi_town": {
        "TownGate": ["notice_board"], "Well": ["wishing_tree"], "Riverside": ["fishing_boat"],
        "WatchTower": ["bronze_bell"], "Farmland": ["herb_drying_rack"], "Orphanage": ["offering_table"], "MagistrateHall": ["notice_board"],
        "Temple": ["offering_table"], "Warehouse": ["treasure_chest", "abacus_desk"],
        "Graveyard": ["ancestral_tablet"], "NorthGate": ["war_drum"], "SouthMarket": ["spirit_lamp"],
        "Granary": ["abacus_desk"], "SilkWorkshop": ["loom"], "DyeYard": ["loom"], "Pharmacy": ["medicine_cabinet"],
        "Academy": ["scroll_rack", "stone_stele"], "ExamHall": ["stone_tablet_array"],
        "MerchantManor": ["guardian_lion", "jade_screen"], "ManorGarden": ["jade_screen"], "OperaStage": ["war_drum"],
        "TempleFair": ["wishing_tree"], "CityGodTemple": ["offering_table", "bronze_ding"],
        "BellPavilion": ["bronze_bell"], "Pawnshop": ["abacus_desk"], "Tavern": ["wine_jars"],
        "Brewery": ["wine_jars"], "BoatYard": ["fishing_boat"], "LowerDocks": ["fishing_boat", "chain_anchor"],
        "PostStation": ["notice_board", "map_table"], "Barracks": ["war_drum", "map_table"],
        "ExecutionGround": ["notice_board"],
    },
    "blood_abyss": {
        "CanyonEntrance": ["stone_stele"], "ObeliskRing": ["demon_obelisk"], "PrisonCages": ["prison_cage"], "DemonCamp": ["war_drum", "map_table"],
        "AltarOfBlood": ["blood_altar"], "HeartMirror": ["bronze_mirror"], "BoneBridge": ["chain_anchor"],
        "SlaveMines": ["prison_cage", "chain_anchor"], "MineShaft": ["chain_anchor"],
        "ForgeOfSouls": ["soul_lantern", "bronze_ding"], "Barracks": ["war_drum", "map_table"],
        "TrainingPit": ["puppet_frame"], "BeastPens": ["prison_cage"], "PoisonGarden": ["herb_drying_rack"],
        "SkullTower": ["soul_lantern"], "ObsidianSpires": ["demon_obelisk"],
        "SacrificePit": ["blood_altar", "chain_anchor"], "DemonLibrary": ["scroll_rack", "jade_slip"],
        "ElderPalace": ["jade_screen", "bronze_mirror"], "ShadowMarket": ["abacus_desk", "wine_jars"],
        "BloodMoonShrine": ["blood_altar", "offering_table"], "CorpseForest": ["soul_lantern"],
        "RuinedSectGate": ["guardian_lion"], "RuinedSectHall": ["ancestral_tablet"], "ChainBridge": ["chain_anchor"],
        "WatchSpire": ["map_table"], "SealStones": ["seal", "tortoise_stele"],
        "GhostVillage": ["spirit_lamp", "ancestral_tablet"], "RedMoonTerrace": ["bronze_mirror"],
        "CaveOfEchoes": ["bronze_mirror"], "BoneThrone": ["sealed_coffin"],
    },
    "sky_isles": {
        "StarPavilion": ["armillary_sphere"], "CelestialRuins": ["stone_stele"], "SpiritVein": ["spirit_stone"],
        "SerpentLair": ["stone_stele"], "CrystalIsle": ["spirit_stone"], "WaterfallIsle": ["spirit_fountain"],
        "CraneIsle": ["crane_statue"], "MoonIsle": ["bronze_mirror"], "SunAltar": ["bronze_ding", "offering_table"],
        "ThunderIsle": ["rune_pillar"], "ChainIsles": ["chain_anchor"], "ImmortalPalace": ["guardian_lion"],
        "PalaceCourt": ["jade_screen", "bronze_ding"], "HallOfRecords": ["scroll_rack", "stone_tablet_array"],
        "StarObservatory": ["armillary_sphere"], "WindTemple": ["bronze_bell"],
        "CloudHarbour": ["chain_anchor", "map_table"], "SkyShipWreck": ["treasure_chest", "map_table"],
        "DragonBones": ["stone_stele"], "PeachGarden": ["wishing_tree"], "JadeTerraces": ["herb_drying_rack"],
        "MirrorLake": ["bronze_mirror"], "FloatingForest": ["spirit_lamp"], "SealOfHeaven": ["seal", "tortoise_stele"],
        "GateOfHeaven": ["guardian_lion"], "SwordIsle": ["sword_in_stone"], "ElixirSpring": ["spirit_fountain"],
        "StormCloudPlateau": ["rune_pillar"], "LanternIsle": ["soul_lantern", "spirit_lamp"],
        "TreeOfAges": ["wishing_tree"],
    },
}

# collectibles that plausibly lie around a marker; (item, first volume it may appear in)
ITEMS_AT = {
    "sect": {
        "HerbGarden": ["spirit_herb"], "MedicineValley": ["spirit_herb", "medicine"], "PillKilnYard": ["spirit_pill"],
        "ContributionPavilion": ["spirit_pill", "spirit_stone"], "MissionHall": ["letter"], "Pagoda": ["jade_slip"],
        "TreasureTower": ["spirit_stone"], "SwordTomb": ["star_iron"], "AncestorTombs": ["incense"],
        "FormationHall": ["rune_fragment"], "BellTower": ["lantern_oil"], "TeaTerraces": ["spirit_herb"],
        "SpiritOrchard": ["spirit_herb"], "OuterDormitories": ["letter"], "SunriseTerrace": ["tribulation_jade"],
        "CraneRoost": ["phoenix_feather"], "OuterPines": ["lantern_oil"],
    },
    "bamboo_forest": {
        "HerbGrove": ["spirit_herb"], "WolfDen": ["wolf_fang"], "TigerRidge": ["wolf_fang"],
        "HunterLodge": ["wolf_fang"], "MushroomRing": ["spirit_herb"], "HiddenValley": ["spirit_herb"],
        "AlchemistCottage": ["spirit_pill", "medicine"], "PoisonMarsh": ["blood_lotus"],
        "BuriedTemple": ["rune_fragment"], "RuinsInner": ["rune_fragment"], "VillageShrine": ["incense"],
        "StoneBuddhas": ["incense"], "SmugglersTrail": ["letter"], "SpiritSpring": ["spirit_stone"],
        "BambooVillage": ["medicine"], "OldBattlefield": ["star_iron"],
    },
    "qingshi_town": {
        "Pharmacy": ["medicine"], "PostStation": ["letter"], "Warehouse": ["letter"], "MerchantManor": ["letter"],
        "SouthMarket": ["lantern_oil"], "SilkWorkshop": ["cloud_silk"], "DyeYard": ["cloud_silk"],
        "CityGodTemple": ["incense"], "Temple": ["incense"], "Academy": ["jade_slip"], "ExamHall": ["jade_slip"],
        "Pawnshop": ["spirit_stone"], "Farmland": ["spirit_herb"], "Orphanage": ["medicine"],
        "Graveyard": ["incense"], "Brewery": ["lantern_oil"],
    },
    "blood_abyss": {
        "BloodPools": ["blood_lotus"], "BloodRiver": ["blood_lotus"], "PoisonGarden": ["blood_lotus"],
        "ForgeOfSouls": ["demon_core"], "SkullTower": ["demon_core"], "CorpseForest": ["demon_core"],
        "TrainingPit": ["demon_core"], "SlaveMines": ["spirit_stone"], "MineShaft": ["spirit_stone"],
        "DemonLibrary": ["jade_slip"], "SealStones": ["rune_fragment"], "AshPlains": ["void_shard"],
        "ObsidianSpires": ["void_shard"], "WatchSpire": ["letter"], "ShadowMarket": ["spirit_pill"],
        "GhostVillage": ["incense"],
    },
    "sky_isles": {
        "SpiritVein": ["spirit_stone"], "CrystalIsle": ["spirit_stone", "thunder_crystal"],
        "ThunderIsle": ["thunder_crystal"], "StormCloudPlateau": ["thunder_crystal", "tribulation_jade"],
        "PhoenixNest": ["phoenix_feather"], "SunAltar": ["phoenix_feather"], "CloudHarbour": ["cloud_silk"],
        "SkyShipWreck": ["cloud_silk", "star_iron"], "DragonBones": ["star_iron"], "SwordIsle": ["star_iron"],
        "HallOfRecords": ["jade_slip"], "LanternIsle": ["lantern_oil"], "ElixirSpring": ["spirit_pill"],
        "SealOfHeaven": ["rune_fragment", "void_shard"], "GateOfHeaven": ["void_shard"],
        "TreeOfAges": ["tribulation_jade"], "PeachGarden": ["spirit_herb"],
    },
}
# the first volume in which a collectible may turn up where the outline did not ask for it
ITEM_FROM_VOLUME = {"void_shard": 6, "tribulation_jade": 9, "demon_core": 2, "phoenix_feather": 4,
                    "thunder_crystal": 4, "star_iron": 3, "cloud_silk": 1, "blood_lotus": 1}

# ---------------------------------------------------------------- where characters are found

# npc -> map -> markers where a conversation with them may be staged away from home
HAUNTS = {
    "master_yun": {"sect": ["FormationHall", "SunriseTerrace", "BellTower", "InnerSectGate", "AncestorTombs",
                            "TreasureTower", "CliffEdge", "FormationArray"]},
    "elder_mo": {"sect": ["TrainingGround", "MartialStage", "OuterSectHall", "StoneSteps", "MissionHall", "ArenaStands",
                          "FormationArray", "DrumTower"]},
    "elder_bai": {"sect": ["TreasureTower", "AncestorTombs", "TeaTerraces", "FormationHall", "ReflectionCliff",
                           "ScholarRock", "BellTower"]},
    "elder_gu": {"sect": ["ReflectionCliff", "OuterSectHall", "InnerSectGate", "AncestorTombs", "MissionHall",
                          "FormationHall"]},
    "elder_hua": {"sect": ["MedicineValley", "PillKilnYard", "SpiritOrchard", "TeaTerraces", "SpiritBeastGarden",
                           "LaundryStream", "Waterfall"]},
    "senior_han": {"sect": ["SwordPeak", "SwordWashPool", "Waterfall", "CliffEdge", "CoreDisciplesCourt",
                            "SwordPeakPath", "ReflectionCliff", "MartialStage"],
                   "bamboo_forest": ["ForestWatchpost", "CliffPath", "WaterfallGorge", "RopeBridge", "ForestCrossroads"],
                   "qingshi_town": ["StoneBridgeTown", "Canal", "WatchTower", "NorthGate", "BellPavilion"]},
    "senior_wei": {"sect": ["Refectory", "TrainingGround", "MartialStage", "OuterDormitories", "ArenaStands",
                            "DrumTower", "LaundryStream", "MountainRoad"],
                   "qingshi_town": ["SouthMarket", "Tavern", "MarketSquare", "Brewery", "TempleFair"],
                   "bamboo_forest": ["WoodcutterCamp", "HunterLodge", "FishingJetty", "BambooVillage"]},
    "rival_zhao": {"sect": ["CoreDisciplesCourt", "TeaTerraces", "MartialStage", "SunriseTerrace", "TreasureTower",
                            "InnerSectGate", "SpiritOrchard"],
                   "qingshi_town": ["MerchantManor", "ManorGarden", "Academy", "OperaStage"]},
    "gate_lu": {"sect": ["SectGate", "MountainRoad", "StoneSteps", "Refectory", "BellTower", "DrumTower", "MissionHall"]},
    "steward_qian": {"sect": ["ContributionPavilion", "MissionHall", "TreasureTower", "Refectory", "OuterSectHall",
                              "SpiritOrchard"]},
    "xiao_man": {"sect": ["MedicineValley", "PillKilnYard", "SpiritBeastGarden", "SpiritOrchard", "LaundryStream",
                          "CraneRoost"]},
    "xiao_shi": {"sect": ["OuterDormitories", "CraneRoost", "SpiritBeastGarden", "Waterfall", "LaundryStream",
                          "StoneSteps"],
                 "qingshi_town": ["Canal", "Orphanage", "Kilns"]},
    "yan_tie": {"sect": ["SwordPeak", "MartialStage", "SwordTomb", "CableBridge", "ArenaStands", "SunriseTerrace",
                         "SwordPeakPath"]},
    "liu_er": {"qingshi_town": ["EastGate", "Mill", "Canal", "BoatYard", "Orphanage", "Granary"],
               "sect": ["OuterDormitories", "StoneSteps", "Refectory", "LaundryStream"]},
    "hermit_lan": {"bamboo_forest": ["BanyanGiant", "SacredSpring", "MistyLake", "LakePavilion", "StoneBuddhas",
                                     "HiddenValley", "AncientShrine", "MushroomRing"],
                   "sect": ["TeaTerraces", "AncestorTombs", "WaterfallCave", "SunriseTerrace"]},
    "wanderer_ye": {"bamboo_forest": ["SmugglersTrail", "CliffPath", "EchoCave", "ForestCrossroads", "TigerRidge",
                                      "OldBattlefield"],
                    "qingshi_town": ["BackAlley", "Pawnshop", "Tavern", "ExecutionGround", "Canal"],
                    "blood_abyss": ["WatchSpire", "RuinedSectGate", "GhostVillage", "WailingCliffs", "ChainBridge"],
                    "sect": ["MountainRoad", "ReflectionCliff", "CraneRoost"],
                    "sky_isles": ["HermitIsle", "SkyShipWreck", "ChainIsles"]},
    "bandit_tie": {"bamboo_forest": ["WoodcutterCamp", "CharcoalKilns", "SmugglersTrail", "HunterLodge", "BanditLookout"],
                   "qingshi_town": ["Tavern", "LowerDocks", "Barracks", "Warehouse", "Tannery"],
                   "sect": ["MountainRoad", "Refectory"],
                   "blood_abyss": ["SlaveMines", "Barracks", "ChainBridge"]},
    "magistrate_zhou": {"qingshi_town": ["Granary", "Academy", "ExamHall", "BellPavilion", "PostStation",
                                         "CityGodTemple"]},
    "innkeeper_fang": {"qingshi_town": ["Tavern", "Brewery", "SouthMarket", "TempleFair", "Bathhouse", "MarketSquare"]},
    "constable_du": {"qingshi_town": ["NorthGate", "EastGate", "Barracks", "ExecutionGround", "WatchTower",
                                      "PostStation", "BackAlley"]},
    "widow_liu": {"qingshi_town": ["Canal", "DyeYard", "SilkWorkshop", "Orphanage", "CityGodTemple", "Temple"]},
    "ferryman_pan": {"qingshi_town": ["LowerDocks", "BoatYard", "Mill", "StoneBridgeTown", "Canal"]},
    "merchant_jin": {"qingshi_town": ["MerchantManor", "ManorGarden", "Pawnshop", "SouthMarket", "Granary",
                                      "MarketSquare", "LowerDocks"]},
    "keeper_hong": {"qingshi_town": ["CityGodTemple", "Graveyard", "Orphanage"]},
    "star_sage": {"sky_isles": ["StarObservatory", "HallOfRecords", "MoonIsle", "MirrorLake", "LanternIsle",
                                "TreeOfAges", "WindTemple"]},
    "young_ruan": {"sect": ["OuterSectHall", "ArenaStands", "MartialStage", "InnerSectGate", "CoreDisciplesCourt"]},
    "master_ruan": {"sect": ["OuterSectHall", "InnerSectGate", "SunriseTerrace", "AncestorTombs"]},
    "abbess_jing": {"sect": ["AncestorTombs", "TeaTerraces", "SunriseTerrace", "WaterfallCave"],
                    "qingshi_town": ["CityGodTemple", "Orphanage", "Temple"],
                    "bamboo_forest": ["VillageShrine", "StoneBuddhas", "SacredSpring"]},
    "ancestor_zhao": {"sect": ["CoreDisciplesCourt", "TeaTerraces", "PlumGarden", "ContributionPavilion"],
                      "qingshi_town": ["MerchantManor", "ManorGarden"]},
    "rung_chen": {"blood_abyss": ["ElderPalace", "RedMoonTerrace", "BloodMoonShrine", "BoneThrone"]},
}

# Generic arrival lines for any marker; {place} is its phrase.
ARRIVE_ANY = [
    "You reach {place}. For a moment everything is quiet, and then you notice the tracks.",
    "{Place} looks exactly as it should, which is what makes you uneasy.",
    "At {place} the air changes, heavy with qi and something older underneath.",
    "You slow at {place}, letting your senses spread like ripples on a pond.",
    "Somebody was here at {place} not long ago. The grass has not finished standing up.",
    "The path to {place} is longer than you remember. The view is worth it.",
]

# ---------------------------------------------------------------- derived tables

_KINDS = {"m": "meet", "f": "fight", "g": "gather", "d": "med", "p": "prop", "r": "reach"}

NAMES = {m: {k: v[0] for k, v in spec.items()} for m, spec in MARKERS.items()}
for _m, _extra in {"sect": {"TeleportArray": "the teleport array", "PlayerSpawn": "the processional way"},
                   "bamboo_forest": {"TeleportArray": "the mossy array", "PlayerSpawn": "the forest edge"},
                   "qingshi_town": {"TeleportArray": "the roadside array", "PlayerSpawn": "the town road"},
                   "blood_abyss": {"TeleportArray": "the cracked array", "PlayerSpawn": "the canyon rim"},
                   "sky_isles": {"TeleportArray": "the floating array", "PlayerSpawn": "the arrival platform",
                                 "TribulationPeak": "the tribulation peak", "AscensionStair": "the Ascension Stair"}}.items():
    NAMES[_m].update(_extra)
NAMES["sky_isles"].setdefault("StarPavilion", "the star pavilion")

TAGS = {m: {k: set(v[2].split()) for k, v in spec.items()} for m, spec in MARKERS.items()}

POOLS = {m: {kind: [k for k, v in spec.items() if letter in v[1]] for letter, kind in _KINDS.items()}
         for m, spec in MARKERS.items()}

ARRIVE = {m: {k: list(v[3]) for k, v in spec.items() if v[3]} for m, spec in MARKERS.items()}
ARRIVE["sky_isles"]["StarPavilion"] = ["The star pavilion's jade floor is inlaid with constellations. Some of them are moving."]
ARRIVE["sky_isles"]["TribulationPeak"] = ["The summit altar is scorched black in rings, each one a cultivator who stood here and was answered."]
ARRIVE["sky_isles"]["AscensionStair"] = ["The Ascension Stair climbs into cloud, each step made of light, none of them for you. Not yet."]

_STOP = {"the", "of", "a", "an", "old", "great", "and", "by", "at", "to", "s"}


def keywords(map_id, marker):
    """Words that tie a line to ``marker``: those of its phrase and of its CamelCase id."""
    import re
    words = set(re.findall(r"[a-z]+", NAMES.get(map_id, {}).get(marker, "").lower()))
    words |= {w.lower() for w in re.findall(r"[A-Z][a-z]+", marker)}
    words |= set(EXTRA_KEYWORDS.get(marker, ()))
    return {w for w in words if len(w) > 2 and w not in _STOP} - GENERIC_WORDS


# words too common in the saga's prose to tie a line to a place
GENERIC_WORDS = {"sect", "inner", "outer", "town", "forest", "isle", "isles", "heaven", "sky", "blood", "moon",
                 "red", "black", "long", "far", "high", "deep", "old", "new", "stone", "ring", "hall", "gate",
                 "house", "yard", "path", "road", "court", "great", "abyss", "cloud", "clouds", "spirit", "golden"}
# a few markers are named by words the generic list swallows
EXTRA_KEYWORDS = {
    "SectGate": ["paifang", "gatehouse", "gate"], "TownGate": ["gate"], "NorthGate": ["gate"], "EastGate": ["gate"],
    "CloudGate": ["gate"], "InnerSectGate": ["lions"], "RuinsGate": ["archway", "arch"],
    "MainHall": ["hall", "founder"], "OuterSectHall": ["assembly"], "MissionHall": ["notice", "mission", "board"],
    "FormationArray": ["array", "plaza", "formation", "runes"], "BoneField": ["bones", "bone"],
    "ObeliskRing": ["obelisks", "obelisk"], "CelestialRuins": ["columns", "ruins", "dais"],
    "BloodPools": ["pools", "pool"], "RuinsInner": ["courtyard"], "Riverside": ["river", "ferry", "docks"],
    "MountainRoad": ["road"], "ForestPath": ["path"], "SwordPeakPath": ["switchback"], "CliffPath": ["ledge"],
    "HallOfRecords": ["records"], "IsleOfWinds": ["winds", "pines"], "OuterPines": ["pines", "pine"],
    "StoneSteps": ["stairway", "steps"], "HallSteps": ["steps"], "Clearing": ["clearing", "grass"],
    "AbyssDepths": ["depths", "bottom"], "CanyonEntrance": ["canyon"],
}


def name(map_id, marker):
    return NAMES.get(map_id, {}).get(marker, marker)
