"""Volume IX · Mahayana — chapters 81-90.

Heaven has noticed. Clouds spiral over the sect, the Sky Isles open again
for the one heaven is watching, and the long preparation for a tribulation
begins: thunder crystals, lightning rods, a lesser tribulation, and
farewells said early. The Seventh Rung, the Patriarch's Shadow, steps into
the light, and Qing Luan reads in the stars that the last blood moon and the
heir's lightning will fall on the same night.
"""

from .dsl import N, P
from .npcs import *  # noqa: F401,F403
from .saga_gen import B, C

CHAPTERS = [
    # ------------------------------------------------------------------ chapter 81
    C("Heaven Takes Notice", "sky_isles",
      "The clouds over the Azure Cloud turn in a slow spiral, and one morning a stair of cloud unrolls from them without "
      "waiting for any sixty-year cycle. The Sky Isles have opened again, for one visitor. Qing Luan is waiting at the "
      "cloud gate, frowning at the sky like it's disappointed a constellation.",
      cast=[SAGE, HAN, ZHAO, YUN, YAN, WEI], foes=["thunder_wolf", "celestial_sentinel", "void_wraith"],
      items=["thunder_crystal", "cloud_silk", "tribulation_jade"], props=["spirit_stone", "stone_stele", "seal"],
      foe_names={"thunder_wolf": "storm wolves"},
      things={"stone_stele": "the star chart"},
      beats=[
          B("orders", "A Stair Without Waiting",
            "A stair of cloud unrolls over the sect, years early, for no one but you. The whole mountain comes out in its nightclothes again.",
            (WEI, "The stair! Again! Years early! Everyone's in their nightclothes again! Elder Bai's still got the turtles!"),
            "@R:CliffEdge", (N, "The stair of cloud descends from the spiral above your room, step by step, and stops at your feet. Only yours."),
            "@T:sky_isles/CloudGate",
            (SAGE, "Heaven opened my isles for you. Without asking me. Rude. Also flattering. Mostly rude. Come in."),
            (SAGE, "You've caught heaven's eye, lotus child. That's either the best thing that can happen to a cultivator, or the last."),
            map="sect"),
          B("probe", "The Spiral Over the Mountain",
            "From the isles, Qing Luan shows you the spiral in the clouds from above. It is centred exactly on you.",
            "@R:CloudGate", (N, "Below the isles, a spiral of cloud turns over the Azure Cloud Sect, slow and vast. At its centre, the roof of your room."),
            "@I:StarPavilion", ">Read heaven's spiral on the star chart",
            (N, "The chart shows the spiral too, and within it, nine faint rings. Nine bolts. One ring is brighter than the rest: the ninth. The heart."),
            "@T:CloudGate",
            (SAGE, "Nine bolts. Like your founder's. The ninth is the heart. She never told anyone what it was. I watched. I didn't understand."),
            prop="stone_stele", thing="the star chart"),
          B("hunt", "Storm Wolves Gather",
            "Heaven's attention charges the isles. The storm wolves are crackling, restless, drawn to you like iron to a lodestone.",
            "@R:SpiritVein", (N, "Storm wolves pace the spirit vein, fur crackling, eyes fixed on you. Every one of them is humming the same note as the clouds."),
            "@F:SpiritVein",
            "@G:SpiritVein", ">Gather the charged crystals they guard",
            "@T:CloudGate",
            (ZHAO, "The wolves are following you. The lightning is following you. Everything's following you. I'm following you. It's a parade."),
            foe="thunder_wolf", item="thunder_crystal", noun="charged crystals"),
          B("social", "Qing Luan Is Worried",
            "Qing Luan is worried. She never worries. She's a memory. Memories don't worry.",
            (SAGE, "I'm worried. I don't worry. I'm ten thousand years old and I've never worried. It's very uncomfortable."),
            (SAGE, "Heaven's early. The Patriarch is waiting. The Seventh Rung is somewhere. And you're very young to be struck by lightning."),
            "|",
            (HAN, "Then we prepare. Crystals. Rods. Training. Everything. Early. Like heaven."),
            ),
          B("cultivate", "Standing Where Heaven Looks",
            "Qing Luan asks you to stand on the isle where heaven's eye is brightest and let it look. Not fight it. Be seen.",
            (SAGE, "Let heaven look at you. Don't hide. Don't fight. Be seen. Heaven hates being hidden from. It punishes that."),
            "@M:IsleOfWinds", ">Let heaven look at you",
            (N, "The sky looks at you. Not the clouds. Behind the clouds. Something vast and not unkind, weighing you the way a teacher weighs a student."),
            "@T:CloudGate",
            (SAGE, "It liked what it saw. I think. Heaven's very hard to read. It frowned. That's good. It frowns at people it's interested in."),
            ),
          B("battle", "Sentinels That Know",
            "The palace sentinels know what heaven's eye means. They come to test whether you deserve it.",
            (YAN, "Thunder Peak came up the stair! We're here for the lightning! Where's the lightning? Oh. Sentinels. Also fine!"),
            "@F:CelestialRuins",
            "@F2:JadeBridge",
            "@T:CloudGate",
            (YAN, "They bowed. After we beat them. The sentinels bowed to you. Thunder Peak has never been bowed to by a building."),
            foe="celestial_sentinel", foe2="thunder_wolf"),
          B("gather", "Tribulation Jade",
            "Qing Luan says tribulations leave jade behind: the ground remembers lightning. There are old seams on the peak's slopes.",
            (SAGE, "Tribulation jade. Where lightning struck cultivators before you, the ground turned to jade. It remembers. It can teach."),
            "@G:CelestialRuins", ">Gather tribulation jade from the old strikes",
            "@T:CloudGate",
            (SAGE, "Hold one. Feel it? That's someone's third bolt, ten thousand years ago. They survived. The jade is proud of them."),
            item="tribulation_jade", noun="tribulation jade"),
          B("probe", "The Peak From Afar",
            "From the isle of winds, you look at the tribulation peak. It's quiet. Black rings. And someone standing on it.",
            "@R:IsleOfWinds", (N, "Across the gap, the tribulation peak. Black rings on the summit. And on the highest ring, very small, a figure in dark red, looking back."),
            "@I:StarPavilion", ">Look at the figure through the star chart",
            (N, "The chart shows the seventh red star directly over the peak. The figure beneath it waves, once, and steps into a rift, and is gone."),
            "@T:CloudGate",
            (SAGE, "The Seventh Rung. On my peak. Looking at you. The Patriarch's Shadow. Nobody's seen them. Until now. Now they want to be seen."),
            prop="stone_stele", thing="the star chart"),
          B("interlude", "Heaven's Timetable",
            "Qing Luan says she can't tell when the tribulation will come. Only that it's closer than anyone thought.",
            (SAGE, "A year. Two. Less. Heaven doesn't keep calendars. It keeps promises. It's promised you lightning. It'll deliver."),
            (SAGE, "Prepare. And before you prepare, break through. You're ready. You've been ready since the Great Vehicle."),
            ),
          B("hunt", "Storm Wolves, the Second Gathering",
            "A second, larger gathering of storm wolves arrives, drawn even more strongly by heaven's attention overhead.",
            foe="thunder_wolf", v=0),
          B("gather", "Cloud Silk for the Coming Storm",
            "Qing Luan asks for cloud silk to be gathered now, before the real tribulation storm makes the isles too dangerous to harvest.",
            item="cloud_silk", v=0),
          B("social", "Elder Yan's Excitement",
            "Elder Yan, thrilled beyond words at the idea of a real tribulation, has to be talked out of trying to stand in the lightning himself.",
            (YAN, "Just once! Just one bolt! For Thunder Peak! ...Fine. Fine. I'll watch. From very close. Very, very close."),
            v=0),
          B("hunt", "Celestial Sentinels, Bowing Again",
            "More palace sentinels wake and bow, this time without needing to fight first, recognizing heaven's mark on you.",
            foe="celestial_sentinel", v=0),
          B("gather", "Tribulation Jade, a Second Vein",
            "A second vein of tribulation jade turns up on the peak's far slope, older and deeper than the first.",
            item="tribulation_jade", v=0),
          B("probe", "The Founder's Old Jade",
            "Among the tribulation jade, one piece is warmer than the rest: it remembers the Azure Cloud's own founder, three hundred years gone.",
            (SAGE, "That one's hers. Your founder's third bolt. I felt her survive it. I felt how much it cost her. Hold it gently."),
            v=0),
          B("social", "Zhao Kang's Nerves, Named",
            "Zhao Kang finally admits, out loud, that watching you prepare for tribulation frightens him more than any Rung has.",
            (ZHAO, "A Rung, I can hit. Heaven, I can't. I don't know how to protect you from the sky. That's a new kind of scared for me."),
            v=0),
          B("hunt", "Storm Wolves, the Charged Vein's Guard",
            "The spirit vein's charged wolves grow bolder as the tribulation approaches, testing anyone who comes near.",
            foe="thunder_wolf", v=0),
          B("gather", "Spirit Stones for the Isles' Wards",
            "Qing Luan wants the isles' old wards reinforced with fresh spirit stones before the tribulation storm arrives in full.",
            item="spirit_stone", v=0),
          B("social", "Han Xue's Question About the Ninth Bolt",
            "Han Xue asks Qing Luan directly what she thinks the ninth bolt actually asks, since the founder never said.",
            (SAGE, "I don't know. Ten thousand years and I don't know. But I know it asks something, not just hurts something. That's different, and worse."),
            v=0),
          B("break", "Mahayana",
            "At the cloud gate, under heaven's eye, you take the last step before the sky: preparing to transcend.",
            (SAGE, "Mahayana. The Great Vehicle, as a realm. Everyone you carry, carrying you. Sit at the gate. Let heaven's eye fill you."),
            "@G:CloudGate", ">Set tribulation jade around the gate",
            "@M:CloudGate", ">Open yourself to heaven's eye",
            (N, "Heaven's eye settles on you, and you don't flinch. Qi, soul, body, vehicle: everything you are rises to meet it, and holds."),
            (N, "Far above, very faint, the first rumble of a storm that has been gathering for ten thousand years, and is gathering for you."),
            "@T:CloudGate",
            (YUN, "Mahayana. The first in three hundred years. The storm's gathering. So are we. Come home. We've work to do."),
            item="tribulation_jade", noun="tribulation jade"),
      ]),
    # ------------------------------------------------------------------ chapter 82
    C("Thunder Crystal Harvest", "sky_isles",
      "A tribulation can be survived, the old books say, if the lightning can be split: thunder crystals planted on the "
      "summit, like a river delta. The isles hold the only crystals strong enough, and the storm wolves, the sentinels "
      "and the Seventh Rung's shadows all want them too.",
      cast=[SAGE, YAN, HAN, ZHAO, WEI, BAI], foes=["thunder_wolf", "celestial_sentinel", "void_wraith"],
      items=["thunder_crystal", "tribulation_jade", "star_iron"], props=["spirit_stone", "seal", "stone_stele"],
      foe_names={"void_wraith": "shadow-born", "thunder_wolf": "storm wolves"},
      things={"spirit_stone": "the crystal heart"},
      beats=[
          B("orders", "Bai's Delta",
            "Elder Bai has read every book on tribulations. His plan: split the lightning like a river delta, with crystals.",
            (BAI, "Split the lightning! Like a river delta! Crystals on the summit, drawing off the bolts! Your founder did it! I think! The page is smudged!"),
            (BAI, "Ninety-nine crystals. The strongest. From the isles. Go. I'll draw the delta. On my ceiling. Next to Xiao Shi's map."),
            "@R:sky_isles/SpiritVein", (N, "The spirit vein glitters with crystals, blue and humming. You'll need ninety-nine. There are, at a guess, ninety-eight."),
            "@T:CloudGate",
            (SAGE, "Ninety-nine? Your librarian is an optimist. The vein will give what it can. Ask nicely. It remembers the rust."),
            map="sect"),
          B("gather", "Asking the Vein Nicely",
            "The spirit vein remembers the Rust Monk, and you, who healed it. It gives its crystals freely.",
            (SAGE, "It remembers you healed it. It's giving you its best. Take them gently. They're very old and very proud."),
            "@G:SpiritVein", ">Harvest crystals from the grateful vein",
            "@T:CloudGate",
            (SAGE, "Forty. The vein gave forty of its best. It's never given anyone more than three. It likes you. Everything likes you. It's exhausting."),
            item="thunder_crystal", noun="vein crystals"),
          B("battle", "Shadows at the Vein",
            "Shadow-born things step out of rifts at the vein, grabbing crystals. The Seventh Rung wants them too.",
            (HAN, "Shadows! Out of the rifts! Grabbing crystals! Whoever the Seventh Rung is, they want your delta broken before you build it!"),
            "@F:SpiritVein",
            "@F2:ImmortalGarden",
            "@T:CloudGate",
            (HAN, "They took three. Only three. We'll need more. The Seventh Rung is playing a very long game. So are we."),
            foe="void_wraith", foe2="void_wraith"),
          B("hunt", "Storm Wolf Crystals",
            "The storm wolves carry crystals in their fur. They'll let them go, if you're faster than lightning.",
            "@R:IsleOfWinds", (N, "Storm wolves race across the Isle of Winds, crystals glittering in their fur like frost. They're very fast. So are you now."),
            "@F:IsleOfWinds",
            "@G:IsleOfWinds", ">Gather the crystals the wolves shed",
            "@T:CloudGate",
            (YAN, "You outran a storm wolf! Thunder Peak has been trying for three hundred years! We're carving it on the forge! Next to your name!"),
            foe="thunder_wolf", item="thunder_crystal", noun="wolf crystals"),
          B("delve", "The Crystal Heart",
            "At the vein's deepest point, beneath the ruins, lies a crystal heart that can charge all the others at once.",
            "@R:CelestialRuins", (N, "Beneath the ruins, a cavern of blue light. At its centre, a crystal the size of a house, beating slowly, like a heart."),
            "@G:CelestialRuins", ">Gather the shards around the crystal heart",
            "@I:CelestialRuins", ">Charge the crystals at the heart",
            (N, "You set the crystals around the heart. It beats faster. Each crystal brightens with its pulse until they all beat together."),
            "@F:SerpentLair", (N, "The heart's ancient guardians stir on the old serpent's isle, and come to see who woke it."),
            "@R:CloudGate", (N, "The charged crystals hum in your pack like a hive of lightning. Ninety of them. Nearly enough."),
            item="star_iron", foe="celestial_sentinel", prop="spirit_stone", thing="the crystal heart"),
          B("social", "The Jiao Remembers",
            "A shadow passes over the isles: a great serpent, storm-grey, circling. The Jiao you freed has come back.",
            (SAGE, "The Jiao! It's come back! It remembers you! Look, it's carrying something in its claws!"),
            "|",
            (N, "The Jiao circles once and drops nine crystals at your feet, each as large as a fist and humming with stored storm. Then it bows its great head."),
            (P, "Thank you, great one. We're even now."),
            (N, "The Jiao rumbles, which might be a laugh, and sinks into the clouds."),
            ),
          B("probe", "Ninety-Nine",
            "Ninety crystals from the vein and the wolves, nine from the Jiao. Ninety-nine. Exactly what Elder Bai asked for.",
            "@I:CloudGate", ">Count the ninety-nine crystals",
            (N, "Ninety-nine crystals, each humming a different note. Together they sound like the sky clearing its throat."),
            "@R:CloudGate", (N, "Beneath the humming, faint, one crystal is off-key. A shadow is curled inside it, very small, listening."),
            "@T:CloudGate",
            (HAN, "A shadow in a crystal. Listening. The Seventh Rung put a spy in our delta. Crush it. No. Wait. Let it listen. Let's tell it lies."),
            prop="spirit_stone", thing="the crystals"),
          B("social", "Lies for a Shadow",
            "Han Xue has a plan: let the Seventh Rung's spy hear a false plan. Wei Tong is terrible at lying. That's why it'll work.",
            (HAN, "Talk near the crystal. Loudly. Say the delta goes on the eastern slope. It'll go on the western one. The shadow will report east."),
            "|",
            (WEI, "The delta goes on the EASTERN slope! The EASTERN one! Definitely not the western one! I've never heard of the western one!"),
            (HAN, "...That's perfect. That's the worst lie I've ever heard. They'll believe it completely."),
            ),
          B("battle", "Carrying Crystals Down",
            "Carrying ninety-nine charged crystals down the cloud stair, with shadows snapping at your heels.",
            (ZHAO, "Ninety-nine crystals down a staircase made of cloud with shadows chasing us. I've had worse days. I can't remember when."),
            "@F:JadeBridge",
            "@F2:CloudGate",
            "@T:CloudGate",
            (SAGE, "Down you go. Keep them dry. Keep them humming. And tell your librarian the delta was a good idea. It was your founder's, too."),
            foe="void_wraith", foe2="thunder_wolf"),
          B("hunt", "Shadow-Born, the Vein's Last Guard",
            "A last cluster of shadow-born things lingers near the drained vein, reluctant to give up the search for crystals.",
            foe="void_wraith", v=0),
          B("gather", "Tribulation Jade From the Crystal Cavern",
            "The cavern around the crystal heart holds tribulation jade too, worth gathering before it's sealed again.",
            item="tribulation_jade", v=0),
          B("social", "Elder Bai's Delta Diagram",
            "Elder Bai insists on showing you his full delta diagram before the crystals go in the ground, checking every angle personally.",
            (BAI, "Ninety-nine points, each one calculated from the smudged page and a lot of guessing. If I'm wrong, I'm wrong beautifully."),
            v=0),
          B("hunt", "Celestial Sentinels, the Ruins' Guard",
            "A pair of celestial sentinels, disturbed by the crystal heart's awakening, need calming before the harvest is complete.",
            foe="celestial_sentinel", v=0),
          B("gather", "Star Iron From the Heart's Chamber",
            "The chamber around the crystal heart holds star iron deposits, worth harvesting while the guardians are calm.",
            item="star_iron", v=0),
          B("probe", "The Jiao's Old Wound",
            "Before it leaves, the Jiao shows you an old scar on its flank, from the storm wolf king's fight years ago.",
            (N, "The Jiao's scar has healed clean. It nudges your hand with its huge head, once, and you understand it's saying thank you, still, after all this time."),
            v=0),
          B("social", "Yan Tie's Carving Request",
            "Elder Yan formally requests that outrunning a storm wolf be added permanently to the forge's carved achievements.",
            (YAN, "It's official now! Carved in stone! 'Outran a storm wolf, Thunder Peak witnessed it personally'! History has been made!"),
            v=0),
          B("hunt", "Storm Wolves, the Delta's Test",
            "A final test: storm wolves circle the crystal cache, checking whether the ninety-nine can hold against real lightning.",
            foe="thunder_wolf", v=0),
          B("gather", "Spirit Stones for the Pagoda's Crystal Shelf",
            "Elder Bai wants a proper shelf built for the ninety-nine crystals, reinforced with spirit stones so they don't roll off in his excitement.",
            item="spirit_stone", v=0),
          B("social", "Zhao Kang's Spy Report",
            "Zhao Kang, inspired by Wei Tong's terrible lying, writes an equally terrible fake report to leave where a shadow might find it.",
            (ZHAO, "I wrote that the delta has a hundred crystals, not ninety-nine, and one is cursed. Completely made up. Very convincing, I think."),
            v=0),
          B("interlude", "Crystals in the Pagoda",
            "Elder Bai stores the ninety-nine crystals in the pagoda, under the ceiling map. The pagoda hums all night.",
            (BAI, "Ninety-nine crystals! In my pagoda! Humming! I can't sleep! I don't want to sleep! I'm going to read by them!"),
            "|",
            (WEI, "The eastern slope! I told the shadow the eastern slope! Did it work? Han Xue says it worked. I'm a spy now. A terrible spy. The best terrible spy."),
            map="sect"),
      ]),
    # ------------------------------------------------------------------ chapter 83
    C("The Seventh Rung", "blood_abyss",
      "The Seventh Rung's shadows have been seen at the Abyss rim, gathering blood from the fold's edge. Ye Wuming asks "
      "you to come. At the obelisk ring, for the first time, the Patriarch's Shadow steps into the light: a young man "
      "with red eyes and your mother's cousin's village name on his lips.",
      cast=[YE, GU, TIE, HAN, ZHAO, SHI], foes=["void_wraith", "blood_guard", "demon_cultivator"],
      items=["demon_core", "void_shard", "blood_lotus"], props=["demon_obelisk", "seal", "treasure_chest"],
      foe_names={"void_wraith": "shadow-born"},
      beats=[
          B("orders", "Shadows Drinking at the Rim",
            "Ye Wuming sends Spring with a message: shadows are drinking blood from the fold's edge, and something is watching them.",
            (YE, "Shadows at the rim. Drinking from the fold's edge. The Seventh Rung's. And something's watching them drink. Someone."),
            "@R:blood_abyss/CanyonEntrance", (N, "At the rim, shadow-born things crouch at the fold's edge, lapping at the dark. Something else watches from the obelisk ring. Very still."),
            "@T:CanyonEntrance",
            (YE, "Forty sects' wards held the fold for a year. The shadows are wearing them thin. Drinking them. Someone taught them how."),
            map="sect"),
          B("battle", "The Shadow-Born",
            "The shadow-born things are made of the Patriarch's own darkness. They're faster than wraiths, and they don't fear light.",
            (ZHAO, "These don't flinch at wards! These don't flinch at anything! These are new! I hate new!"),
            "@F:BloodPools",
            "@F2:BoneField",
            "@T:CanyonEntrance",
            (HAN, "They're made of him. The Patriarch. His own shadow, cut into pieces. The Seventh Rung isn't just his servant. They're his shadow."),
            foe="void_wraith", foe2="blood_guard"),
          B("probe", "The Watcher at the Ring",
            "At the obelisk ring, a young man in dark red sits on a stump, watching. He doesn't wave. He bows.",
            "@R:ObeliskRing", (N, "A young man in dark red sits on an obelisk stump. Red eyes. A face that looks almost familiar. He stands, and bows, very correctly."),
            "@I:ObeliskRing", ">Look at the young man with your soul",
            (N, "In soul sight he is two things at once: a young man, frightened, and a shadow cast by something enormous behind the fold."),
            "@T:ObeliskRing",
            (RUNG7, "Xue Chen. Seventh Rung. The Patriarch's Shadow. I was born in his shadow. I've never been anywhere else. I wanted to see you."),
            (RUNG7, "You're the one who writes back. And gives rain. And carries spiders. He's very curious about you. So am I."),
            prop="seal", thing="the young man"),
          B("social", "Willow Creek",
            "Xue Chen says a name that stops your heart: Willow Creek. He was born there, too. Before he was taken.",
            (RUNG7, "Willow Creek. I was born there. Taken at three. My mother was a cousin of yours, I think. Everyone there was someone's cousin."),
            (RUNG7, "The Patriarch raised me in his shadow. I've never seen the sun properly. It's very bright. I don't like it."),
            (P, "You could leave his shadow."),
            (RUNG7, "...No. I'm the last rung. Without me, he falls. He's the only father I've ever had. I'll see you at the peak, cousin."),
            ),
          B("battle", "The Shadow Leaves",
            "Xue Chen steps into a rift, and his shadow-born cover his escape.",
            (TIE, "He's gone! Into a rift! His shadows are everywhere! Iron-Fang's men, hold the rim!"),
            "@F:ObeliskRing",
            "@F2:DemonCamp",
            "@T:CanyonEntrance",
            (TIE, "A boy. The last rung is a boy. Taken at three. Like my men's children. Like Ye's children. I don't want to hit a boy."),
            foe="void_wraith", foe2="demon_cultivator"),
          B("social", "Gu Knew Him",
            "Gu Hanshan, in chains at the rim, says he knew Xue Chen as a child. He tried to save him. He failed.",
            (GU, "Xue Chen. I saw him once, when he was five. In the Patriarch's shadow. I tried to take him out with Lan's soul. I failed at both."),
            (GU, "He's not evil. He's never been anywhere else. The Patriarch is his whole world. Breaking him will break a child."),
            "|",
            (YE, "I was that child. Once. Nobody broke me. Somebody stole me back. Maybe that's the answer. Not breaking. Stealing."),
            ),
          B("hunt", "The Shadow's Trail",
            "Xue Chen's shadow-born leave a trail of drained blood lotus toward the heart mirror. He's been visiting it.",
            "@R:HeartMirror", (N, "The Heart Mirror lies still and black. Around it, drained blood lotus, grey and brittle. Someone sits here often, looking in."),
            "@F:HeartMirror",
            "@G:HeartMirror", ">Gather the drained lotus around the mirror",
            "@T:AbyssDepths",
            (SHI, "He comes here to look at himself. In the mirror. I know that. I used to look at myself in puddles in the cage, to remember my face."),
            foe="void_wraith", item="blood_lotus", noun="drained lotus"),
          B("probe", "What the Shadow Sees",
            "You look into the Heart Mirror where Xue Chen sits. It shows you what he sees there.",
            "@R:HeartMirror", (N, "The mirror shows a boy of three, in Willow Creek, holding his mother's hand, laughing. The mirror shows it over and over."),
            "@I:HeartMirror", ">Look at Xue Chen's reflection",
            (N, "That's what he comes to see. Not a monster. Not a rung. A boy in a village by a creek, with his mother, before the shadow."),
            "@T:AbyssDepths",
            (HAN, "He comes to see himself before. Every day. That's the saddest thing I've ever heard. Don't cry. I'm not crying either."),
            prop="seal", thing="the Heart Mirror"),
          B("interlude", "Steal Him Back",
            "Ye Wuming says it again, on the way back: not breaking. Stealing back. Like someone stole him.",
            (YE, "When the time comes, try to steal him back. Before you break him. Like someone stole me. If it can't be done, then break him."),
            (YE, "But try. Please. For the boy in the mirror."),
            (P, "I'll try, Ye Wuming. For the boy in the mirror."),
            ),
          B("hunt", "Shadow-Born, Guarding the Mirror",
            "A cluster of shadow-born things guards the approach to the Heart Mirror, protecting Xue Chen's private grief.",
            foe="void_wraith", v=0),
          B("gather", "Demon Cores From the Rim's Watch",
            "The fallen shadow-born and blood guards leave demon cores behind, worth gathering before the Abyss reclaims them.",
            item="demon_core", v=0),
          B("social", "Han Xue's Question",
            "Han Xue asks whether stealing Xue Chen back is even possible, given how deep the Patriarch's shadow runs in him.",
            (HAN, "Ye Wuming was stolen back as a child, before the shadow set fully. Xue Chen's grown in it his whole life. I don't know if that's different. I hope not."),
            v=0),
          B("hunt", "Blood Guards, the Fold's Reinforced Watch",
            "The fold's watch has grown since Xue Chen's visit, reinforced blood guards testing the rim's defenses.",
            foe="blood_guard", v=0),
          B("gather", "Void Shards From the Shadow's Trail",
            "The trail of drained lotus and shadow residue leaves void shards worth gathering for Elder Bai's study.",
            item="void_shard", v=0),
          B("probe", "Gu's Old Attempt",
            "Gu Hanshan describes, in painful detail, exactly how he tried and failed to steal the young Xue Chen away, hoping it helps this time.",
            (GU, "I got as far as the outer camp. Lan's soul-shield held for one night. Then the Patriarch noticed. I ran. I've regretted running every day since."),
            v=0),
          B("social", "Zhao Kang's Vow",
            "Zhao Kang vows, quietly, that if it comes to a fight, he'll try to pull his blows, for a boy who never had a choice.",
            (ZHAO, "I'll hit him if I have to. But I'll hit him like I'd hit a friend who's lost his mind, not an enemy. There's a difference. I'll find it."),
            v=0),
          B("hunt", "Demon Cultivators, the Ring's Last Guard",
            "A last watch of demon cultivators, left to guard the obelisk ring, retreats when the rim's defenders press forward.",
            foe="demon_cultivator", v=0),
          B("gather", "Blood Lotus, the Mirror's Garden",
            "More drained blood lotus grows around the mirror's edge, worth gathering to study what feeds and drains it.",
            item="blood_lotus", v=0),
          B("social", "Xiao Shi's Own Mirror",
            "Xiao Shi admits she understands Xue Chen's need to look at who he was before, since she once did the same with puddles.",
            (SHI, "I stopped looking, eventually. Not because it stopped hurting. Because I found people worth looking at instead. Maybe he needs that. People, not a mirror."),
            v=0),
          B("cultivate", "Thinking of Willow Creek",
            "At the rim, you sit and remember Willow Creek. The creek. The willows. A cousin you never knew you had.",
            "@M:AbyssDepths", ">Remember Willow Creek in the depths",
            (N, "A creek, a willow, a woman singing. Your mother. And somewhere, a cousin's child, laughing, three years old, before the shadow came."),
            "@T:CanyonEntrance",
            (TIE, "Willow Creek. The village I burned. Twenty years ago. His mother might have... I don't know. I'll carry that too. Iron-Fang carries two."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 84
    C("Lightning Rods for a Sect", "sect",
      "A tribulation strikes the cultivator, but lightning is careless: stray bolts can burn a mountain. The sect must be "
      "protected before heaven comes. Thunder Peak has opinions, Elder Bai has diagrams, and Steward Qian has a budget "
      "he's already crying over.",
      cast=[YAN, BAI, QIAN, WEI, HAN, YUN, LIUER, LU, MAN, SHI], foes=["thunder_wolf", "void_wraith", "stone_golem"],
      items=["thunder_crystal", "star_iron", "spirit_stone"], props=["spirit_stone", "stone_stele", "seal"],
      foe_names={"thunder_wolf": "peak thunder wolves", "void_wraith": "shadow-born"},
      things={"spirit_stone": "the lightning rod"},
      beats=[
          B("orders", "Stray Lightning",
            "Elder Bai explains the danger: the tribulation strikes you, but the storm is enormous, and stray bolts can burn the sect.",
            (BAI, "The tribulation strikes you. But the storm around it is vast. Stray bolts. Your founder's tribulation burned half a forest. We have a sect."),
            (BAI, "Lightning rods. Nine. Around the mountain. Star iron and crystal. Thunder Peak knows how. Ask them. Don't let them shout at you."),
            "@R:CliffEdge", (N, "The spiral of cloud over the sect is lower today. The air tastes of metal. Somewhere far above, heaven is clearing its throat."),
            "@T:CliffEdge",
            (YAN, "Lightning rods! Thunder Peak has been waiting for this day for three hundred years! We have designs! Very loud designs!"),
            ),
          B("social", "Qian's Budget",
            "Steward Qian has costed nine lightning rods. He is crying. He is also, strangely, smiling.",
            (QIAN, "Nine rods. Star iron. Crystal caps. Thunder Peak's labour, which is loud. It's the most expensive thing the sect has ever built."),
            (QIAN, "And I don't care. For the first time in my life, I don't care what it costs. It protects everyone. Don't tell anyone. I have a reputation."),
            "|",
            (LU, "Steward Qian said 'I don't care what it costs'! Out loud! I heard it! I'm writing it on the gate!"),
            ),
          B("gather", "Star Iron for Nine Rods",
            "Nine rods need star iron. The Thunder Peak forge has old anvils. They'll have to be melted. Yan Tie is heartbroken and proud.",
            (YAN, "The old anvils. Melted. For rods. Three hundred years of anvils. Thunder Peak weeps. Thunder Peak also says yes."),
            "@G:CliffEdge", ">Carry the forge's old anvils",
            "@T:CliffEdge",
            (YAN, "Nine anvils. Nine rods. Thunder Peak's history, protecting everyone. That's what history's for. We'll carve new anvils. Louder ones."),
            item="star_iron", noun="old anvils"),
          B("hunt", "Wolves Want the Iron",
            "The peak thunder wolves love star iron. They follow the anvils down the mountain, hopefully.",
            "@R:OuterPines", (N, "Thunder wolves follow the anvil carts down the path, tongues out, crackling, like dogs following a butcher's cart."),
            "@F:OuterPines",
            "@G:OuterPines", ">Gather the sparks the wolves shed",
            "@T:CliffEdge",
            (YAN, "Rumble followed us all the way down! He wants to help! He's licking the rods! It's actually charging them! Good boy!"),
            foe="thunder_wolf", item="thunder_crystal", noun="wolf sparks"),
          B("probe", "Raising the First Rod",
            "The first rod goes up at the cliff edge, where the lightning always strikes first. You set its crystal cap.",
            "@R:CliffEdge", (N, "A rod of star iron, twice the height of the main hall, rises at the cliff edge. It hums as the spiral above turns."),
            "@I:CliffEdge", ">Set the crystal cap on the first rod",
            (N, "The crystal cap clicks into place. Above, a single thread of lightning reaches down from the spiral, touches the rod, and runs harmlessly into the earth."),
            "@T:SectGate",
            (BAI, "It works! The first rod works! The delta will work! The founder's plan works! My grandmother's turtle soup recipe works!"),
            prop="spirit_stone", thing="the first rod"),
          B("battle", "Shadows Against the Rods",
            "The Seventh Rung's shadow-born try to tear down the rods before they're finished. The eastern slope has twice as many. Wei Tong's lie worked.",
            (WEI, "They're attacking the eastern slope! Twice as many there! My lie worked! I'm a genius! A terrible genius!"),
            "@F:OuterPines",
            "@F2:TrainingGround",
            "@T:SectGate",
            (HAN, "Eastern slope, overrun, empty. Western slope, rods standing. The shadow believed Wei Tong. I'm never going to let him forget it."),
            foe="void_wraith", foe2="void_wraith"),
          B("gather", "Nine Rods Around the Mountain",
            "Eight more rods, around the mountain. Every disciple helps carry. Even the twelve. Even the chicken.",
            (LIUER, "Every disciple carries! The twelve! Me! The chicken! Qiu Hua insisted! The chicken is carrying a very small piece of crystal!"),
            "@G:FormationArray", ">Carry the rods to their places",
            "@T:SectGate",
            (MAN, "Nine rods. Around the mountain. I dropped one. Only one. It bounced. Rods bounce. Who knew?"),
            item="spirit_stone", noun="rod sections"),
          B("cultivate", "Singing With the Rods",
            "The nine rods hum in the storm. Yan Tie says Thunder Peak's tradition is to shout back. You try humming instead.",
            (YAN, "Thunder Peak shouts back at the storm! It's tradition! Try it! No? Humming? Fine! Hum! Hum loudly!"),
            "@M:CliffEdge", ">Hum with the nine rods in the storm",
            (N, "You hum. The rods hum. The storm above hums back. For a moment, heaven and the mountain and you are one very long note."),
            (N, "Middle stage of Mahayana. The storm is closer. You are readier."),
            "@T:SectGate",
            (YUN, "Nine rods. The sect is safe from stray lightning. Now it's only you the sky wants. That's a sentence I never wanted to say."),
            ),
          B("social", "Xiao Shi's Map, Updated",
            "Xiao Shi adds the nine rods to his ceiling map. Beside them, the fold. And a red line where the moon rises.",
            (SHI, "Nine rods on the map. And the fold. And look: the moon's path. It passes directly over the fold and the peak. Every month, a little redder."),
            (SHI, "The moon's turning red. Slowly. The old books say the last blood moon comes when the Ladder is almost gone. We're almost there."),
            "|",
            (BAI, "The last blood moon and your tribulation. The books never said they'd be the same night. But they might be. I don't like that."),
            ),
          B("hunt", "Thunder Wolves, Guarding the Rods",
            "The peak thunder wolves, having helped charge the rods, appoint themselves unofficial guards and challenge anyone who approaches.",
            foe="thunder_wolf", v=0),
          B("gather", "Spirit Stones for the Rods' Foundations",
            "Each of the nine rods needs its foundation reinforced with spirit stones before the real storm arrives.",
            item="spirit_stone", v=0),
          B("social", "Wei Tong's Terrible Genius, Confirmed",
            "Wei Tong, insufferably proud of his successful lie, demands a formal title from the Sect Master to commemorate it.",
            (WEI, "Terrible Genius of the Eastern Slope. That's my title now. I've decided. Somebody tell the Sect Master. Tell her it's official."),
            v=0),
          B("hunt", "Void Wraiths, the Western Slope's Last",
            "A last handful of shadow-born, realizing the deception too late, retreats from the correctly-fortified western slope.",
            foe="void_wraith", v=0),
          B("gather", "Star Iron for the Tenth Rod",
            "Elder Bai, reading the smudged page again, insists on a tenth backup rod, just in case his math was off by one.",
            item="star_iron", v=0),
          B("probe", "Bai's Recalculation",
            "Elder Bai recalculates the delta a third time, muttering about smudged ink and a founder who apparently had terrible handwriting.",
            (BAI, "Ninety-nine crystals, nine rods, one very smudged page. If this works, I'm naming a room after myself. A small room."),
            v=0),
          B("social", "Liu Er's Rod Duty",
            "Liu Er, assigned to guard the eastern rod overnight, takes the job with the same seriousness he brought to guarding a chicken.",
            (LIUER, "Nobody touches this rod. Nobody. I've got a broom and a very stern expression. Both are fully deployed."),
            v=0),
          B("hunt", "Stone Golems, Disturbed by the Rods",
            "The rods' humming disturbs a few dormant stone golems near the formation, who wake confused and mildly annoyed.",
            foe="stone_golem", v=0),
          B("gather", "Spirit Stones for Xiao Shi's Updated Map",
            "Xiao Shi's expanding ceiling map needs more spirit stones to properly mark the moon's reddening path.",
            item="spirit_stone", v=0),
          B("social", "Xiao Man's Worry About the Moon",
            "Xiao Man, staring at the reddening moon through Xiao Shi's map, admits it frightens her more than any Rung has.",
            (MAN, "A Rung you can fight. The moon just... comes. On its own schedule. Nobody asked it to. Nobody can stop it either."),
            v=0),
          B("interlude", "Farewells Early",
            "The Sect Master says something that makes everyone go quiet: it's time to start saying goodbyes. Not because you'll die. Because you'll climb.",
            (YUN, "Start saying goodbye. Not because you'll fall. Because you won't. When you transcend, the stair opens. Most who climb don't come back."),
            (YUN, "Say what you need to say to the people you love. Early. So there's no rush at the end. Start with Qingshi. They'd want to be first."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 85
    C("The Lesser Tribulation", "sky_isles",
      "Before the great tribulation comes a lesser one: three bolts, a warning shot from heaven. Qing Luan says every "
      "cultivator gets one, and most of them die of it. She says it cheerfully. Then she says your heart demon will "
      "flicker in the third bolt, and she isn't cheerful any more.",
      cast=[SAGE, HAN, ZHAO, YAN, WEI], foes=["thunder_wolf", "heart_demon", "celestial_sentinel"],
      items=["thunder_crystal", "tribulation_jade", "cloud_silk"], props=["spirit_stone", "seal", "stone_stele"],
      boss=("heart_demon", "The Flickering Shadow", "CelestialRuins"),
      foe_names={"thunder_wolf": "storm wolves"},
      beats=[
          B("orders", "Heaven's Warning Shot",
            "Qing Luan's crane arrives crackling. Heaven is sending a lesser tribulation. Three bolts. Tonight. On the isles.",
            (YUN, "A crane from the star-gazer. Crackling. A lesser tribulation. Three bolts. Tonight. Go. We'll watch from the mountain. Everyone's watching."),
            "@R:sky_isles/CloudGate", (N, "The isles are dark and humming. Overhead, a small spiral of black cloud turns directly above the Isle of Winds."),
            "@T:CloudGate",
            (SAGE, "Three bolts. A warning. Heaven checking you're serious. Most die. You won't. Probably. I'm cheerful. I'm very cheerful. Sit."),
            map="sect"),
          B("gather", "Crystals on the Isle",
            "You plant thunder crystals around the Isle of Winds, a small delta for a small storm.",
            (SAGE, "Crystals around the isle. A small delta. Practice for the big one. Plant them where the wind is strongest."),
            "@G:IsleOfWinds", ">Plant thunder crystals around the isle",
            "@T:CloudGate",
            (YAN, "Thunder Peak came to watch! We brought a banner! It says 'strike harder'! Is that helpful? Thunder Peak isn't sure!"),
            item="thunder_crystal", noun="delta crystals"),
          B("cultivate", "The First Bolt",
            "The first bolt comes down white. Your body takes it the way the forge taught you: usefully.",
            "@M:IsleOfWinds", ">Endure the first bolt",
            (N, "White. Everything white. Your integrated body takes the bolt and doesn't break. It hums. The crystals around you split the rest into the sea of clouds."),
            "@T:CloudGate",
            (SAGE, "One. Good. You didn't die. I'm less cheerful now. The second is worse. The third is the heart."),
            ),
          B("battle", "Storm Wolves in the Lightning",
            "The lesser tribulation charges the storm wolves. They come howling out of the pines, crackling, mad with lightning.",
            (ZHAO, "Storm wolves! Drunk on lightning! Between bolts! Heaven's warning shot has brought friends! Rude friends!"),
            "@F:IsleOfWinds",
            "@F2:JadeBridge",
            "@T:CloudGate",
            (ZHAO, "Cleared. The second bolt's coming. I can feel my hair standing up. I have very good hair. This is a tragedy."),
            foe="thunder_wolf", foe2="thunder_wolf"),
          B("cultivate", "The Second Bolt",
            "The second bolt is purple. It goes through your body and into your soul, looking for seams. There aren't any.",
            "@M:IsleOfWinds", ">Endure the second bolt",
            (N, "Purple. The bolt goes through body and into soul, searching for a seam where it could split you. It finds none. It goes away, disappointed."),
            "@T:CloudGate",
            (SAGE, "Two. The third is the heart. Your heart demon will flicker in it. It'll look like you. It'll know you. Don't be kind to it."),
            (SAGE, "No. Be kind to it. That's how you won last time. I'm confused. I'm frightened. Be yourself."),
            ),
          B("boss", "The Flickering Shadow",
            "The third bolt comes down black, and out of it steps a shadow wearing your face, flickering like a candle in wind.",
            "@R:CelestialRuins", (N, "The third bolt hits the ruins and doesn't vanish. It stands up, black, wearing your face, flickering in and out like a bad lamp."),
            "@X",
            (DEMON, "Hello again. Heaven sent me. A little piece of you, to test the rest. Every time you win, I come back stronger. See you at the ninth."),
            (P, "Every time you come back, so do I."),
            "@I:CelestialRuins", ">Let the third bolt pass through you",
            (N, "The shadow fades into the bolt, and the bolt fades into you, and you're still standing. The lesser tribulation is over."),
            "@T:CloudGate",
            (SAGE, "Three. You survived a lesser tribulation. The first in three hundred years. Your founder was the last. She'd be proud. I'm proud. I'm crying."),
            prop="seal", thing="the third bolt"),
          B("social", "Everyone Watched",
            "The whole sect watched from the mountain. The whole alliance, their cranes say. They all saw the three bolts fall.",
            (HAN, "We watched from the cliff. Three bolts. Three. The whole sect cheered. Wei Tong fainted. Then he got up and cheered."),
            "|",
            (WEI, "I didn't faint. I sat down very suddenly. And lay down. Briefly. For morale."),
            "|",
            (YAN, "Thunder Peak's banner said strike harder. Heaven listened. We're very sorry. We're making a new banner. It says 'please don't'."),
            ),
          B("gather", "Tribulation Jade, Fresh",
            "Where the three bolts struck the isle, the ground has turned to fresh jade. Your jade.",
            (SAGE, "Your jade. Where you stood. Fresh. Take some. Someday, someone will find the rest and feel your three bolts and be proud of you."),
            "@G:IsleOfWinds", ">Gather your own tribulation jade",
            "@T:CloudGate",
            (SAGE, "Give some to the people you love. Tribulation jade is warm forever. They'll have something of you when you climb."),
            item="tribulation_jade", noun="fresh tribulation jade"),
          B("probe", "The Ninth Ring",
            "Qing Luan reads the chart after the lesser tribulation. The ninth ring is brighter. Closer. And red.",
            "@I:StarPavilion", ">Read the star chart after the storm",
            (N, "Nine rings on the chart. The ninth is red now, not white. The seventh star sits right on it. The Patriarch's Shadow, on your heart bolt."),
            "@R:StarPavilion", (N, "Beneath it, in Qing Luan's hand, fresh ink: the last blood moon and the ninth bolt. Same night. Same hour. Oh no."),
            "@T:CloudGate",
            (SAGE, "Same night. The last blood moon and your heart tribulation. He's planned it. For three hundred years. He'll ride your heart bolt."),
            prop="stone_stele", thing="the star chart"),
          B("hunt", "Storm Wolves, the Aftermath",
            "The lesser tribulation leaves storm wolves scattered and lightning-drunk across the isle, needing one last calming pass.",
            foe="thunder_wolf", v=0),
          B("gather", "Cloud Silk From the Storm's Edge",
            "The lesser tribulation's storm leaves unusually potent cloud silk in the pines, worth harvesting while it's fresh.",
            item="cloud_silk", v=0),
          B("social", "Zhao Kang's Hair Tragedy",
            "Zhao Kang mourns his lightning-frizzed hair with the same gravity most people reserve for actual tragedies.",
            (ZHAO, "Three hundred years of good hair in my family, ruined in one bolt. I survived a tribulation and lost to static electricity."),
            v=0),
          B("hunt", "Celestial Sentinels, Checking the Damage",
            "A pair of celestial sentinels inspect the ruins after the third bolt, curious rather than hostile for once.",
            foe="celestial_sentinel", v=0),
          B("gather", "Spirit Stones for the Isle's Recovery",
            "The isle's spirit vein, drained by the lesser tribulation, needs spirit stones to recover its usual glow.",
            item="spirit_stone", v=0),
          B("probe", "Wei Tong's Fainting, Reconsidered",
            "Wei Tong insists on a formal re-examination of whether 'sitting down very suddenly' technically counts as fainting.",
            (WEI, "I was conscious the whole time! Mostly! I remember most of it! That's not fainting, that's a dignified reaction!"),
            v=0),
          B("social", "Elder Yan's New Banner",
            "Thunder Peak unveils its apologetic new banner, which somehow manages to be even louder than the last one.",
            (YAN, "'PLEASE DON'T', in letters this big! Heaven can't possibly misread it now! Unless it wants to! Heaven does what it wants!"),
            v=0),
          B("hunt", "Storm Wolves, One Last Pack",
            "A final pack of storm wolves, still crackling from residual lightning, needs clearing before the isle settles.",
            foe="thunder_wolf", v=0),
          B("gather", "Tribulation Jade for the Alliance",
            "Qing Luan suggests sending a piece of your tribulation jade to each of the forty allied sects, as both gift and warning.",
            item="tribulation_jade", v=0),
          B("social", "Han Xue's Jade",
            "Han Xue receives her piece of warm jade quietly, holding it for a long moment before saying anything at all.",
            (HAN, "It's warm. Really warm. Like you're still in it, a little. I'm going to carry this every day until you come back down."),
            v=0),
          B("interlude", "Warm Jade",
            "You carry pieces of warm tribulation jade down the stair. Everyone you love will get one.",
            (SAGE, "Go. Give out your jade. Say your goodbyes early. And come back up when the sky calls. I'll be at the gate. Frowning."),
            "|",
            (HAN, "Warm jade for everyone. You're giving away pieces of your own tribulation. That's the most you thing you've ever done."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 86
    C("Words for Those Left Behind", "qingshi_town",
      "The Sect Master said start with Qingshi. So you walk down the nine thousand steps with a bag of warm tribulation "
      "jade, and say goodbye early to a town that has been saving your bowl of noodles for years.",
      cast=[FANG, TIE, LIU, LIUER, DU, ZHOU, PAN, JIN, HAN], foes=["void_wraith", "rogue_cultivator", "demon_cultivator"],
      items=["tribulation_jade", "medicine", "incense"], props=["seal", "stone_stele", "treasure_chest"],
      foe_names={"void_wraith": "shadow-born"},
      beats=[
          B("orders", "Down the Steps With Jade",
            "You walk down the nine thousand steps with a bag of warm jade. Qingshi sees you coming from the watchtower.",
            "@R:qingshi_town/TownGate", (N, "Qingshi's gate is open. The whole town is waiting in the street. Somebody saw you from the watchtower and rang the bell, very gently."),
            "@T:MainStreet",
            (DU, "The watchtower saw you coming. We rang the bell soft. Not an alarm. A welcome. We've never had a bell for that. We do now."),
            map="sect"),
          B("social", "Madam Fang's Bowl",
            "Madam Fang has kept a bowl of noodles hot for you since the Crimson Road. Every day. She's not going to stop.",
            (FANG, "Your bowl. Kept hot. Every day since the Crimson Road. I'm not going to stop when you climb. I'll keep it hot forever."),
            (P, "Madam Fang. For you. Tribulation jade. It stays warm forever too."),
            (FANG, "...Warm forever. Like the bowl. Oh, you terrible child. Now I'm crying into the noodles. Eat them anyway. They're salty now."),
            ),
          B("social", "Iron-Fang's Dishes",
            "Iron-Fang is washing dishes. He doesn't look up. He's been expecting this. He doesn't want it.",
            (TIE, "Goodbyes. Early. The Sect Master's idea. I don't like it. Iron-Fang doesn't say goodbye. Iron-Fang says see you later."),
            (P, "See you later, Tie Hu. At the black gate."),
            (TIE, "...At the black gate. Yes. That's a see-you-later I can say. Give me the jade. I'll keep it with my sister's ribbon."),
            ),
          B("gather", "Water for the Last Time",
            "Widow Liu asks you to carry water with her, one last time, to the old houses on the hill. Liu Er comes too.",
            (LIU, "Carry water with me. To the hill houses. One more time. My son too. The three of us. Like a family."),
            "@G:Well", ">Carry water up the hill with the Lius",
            "@T:MainStreet",
            (LIUER, "Mother cried the whole way. I cried the whole way. You didn't cry. You carried twice as much. That's how you cry, isn't it?"),
            (LIU, "Heaven keeps its accounts. I keep mine. You're paid in full. Forever. Take care up there."),
            item="medicine", noun="buckets of water"),
          B("battle", "Shadows in the Town",
            "The Seventh Rung's shadows have followed you down. They want to see who you love. They're taking notes.",
            (DU, "Shadows! In the street! Following you! Watching who you talk to! The town's not having that!"),
            "@F:MainStreet",
            "@F2:MarketSquare",
            "@T:MainStreet",
            (DU, "Gone. The whole town chased them. With brooms. Liu Er taught everyone. Qingshi's the best-armed town in the world. With brooms."),
            foe="void_wraith", foe2="rogue_cultivator"),
          B("social", "The Magistrate's Speech",
            "Magistrate Zhou has written a speech. It's nine pages. He reads one word of it.",
            (ZHOU, "I've written a speech. Nine pages. I'm going to read one word. It's the best word I know."),
            (ZHOU, "Hold."),
            "|",
            (ZHOU, "...That's it. That's the speech. Hold. Whatever happens up there. Hold. Qingshi will. For you."),
            ),
          B("probe", "Jade in the Qing River",
            "Old Pan takes you out on the river, one last time. He doesn't charge a fare. He never did, after the siege.",
            "@R:Riverside", (N, "Old Pan's ferry slides out onto the Qing River. The town lights shine on the water. He rows slowly, very slowly."),
            "@I:Riverside", ">Drop a piece of jade into the river",
            (N, "The jade sinks, glowing, into the river. Old Pan nods. Now the river remembers you too, he says. Forty years, it's never lied."),
            "@T:MainStreet",
            (PAN, "Forty years on this water. I've carried everyone. You were the only one who ever carried me back. Mind the third plank. Always."),
            prop="seal", thing="the river"),
          B("social", "Merchant Jin's Ledger",
            "Merchant Jin has closed his books for the day, to give you something: the guild's ledger, with a new last page.",
            (JIN, "The guild's ledger. The last page. Every debt the town owes you. I've written them all. It's a very long page."),
            (JIN, "And at the bottom, in my own hand: paid in full, by a town that learned to be honest. I'm framing it. In the warehouse."),
            ),
          B("cultivate", "The Temple, One Last Time",
            "You sit in the town temple, clean now, where you cleansed Hong's defilement years ago, and carry the whole town.",
            "@M:Temple", ">Carry Qingshi in the temple's quiet",
            (N, "The whole town, breathing. Madam Fang humming. Iron-Fang scrubbing. Widow Liu counting in elevens. You hold them, and then you let them hold you."),
            "@T:MainStreet",
            (HAN, "I came down to walk you home. I watched you carry the whole town. From the temple steps. Every face in the street was crying."),
            ),
          B("hunt", "Rogue Cultivators, the Town's Last Test",
            "A handful of rogue cultivators, testing the town's grief-weakened watch, are met by the whole street armed with brooms.",
            foe="rogue_cultivator", v=0),
          B("gather", "Incense for Every Doorstep",
            "The town lights incense on every doorstep for you, a tradition Widow Liu insists on starting that evening.",
            item="incense", v=0),
          B("social", "Qiu Hua's Chicken, Farewelled",
            "Qiu Hua brings Elder Drumstick down from the mountain specially so the chicken can say its own goodbye.",
            (N, "The chicken regards you with the profound indifference of a creature that has survived a Rung's web and several battles. You take it as affection."),
            v=0),
          B("hunt", "Demon Cultivators, the Watchtower's Alarm",
            "A pair of demon cultivators tests the watchtower's new gentle-bell system, and get the town's full, un-gentle response.",
            foe="demon_cultivator", v=0),
          B("gather", "Medicine for the Road Ahead",
            "Elder Hua, reached by crane, asks that Qingshi send a final supply of medicine up the mountain with you.",
            item="medicine", v=0),
          B("probe", "The Third Plank",
            "Old Pan explains, in more detail than strictly necessary, the exact history of the loose third plank on his ferry.",
            (PAN, "Forty-one years old, that plank. Replaced twice. Still loose. Some things are loose on purpose. Keeps you paying attention."),
            v=0),
          B("social", "Liu Er's Broom, Passed On",
            "Liu Er, preparing to return to the sect for good, passes his famous broom to the next child who'll need it.",
            (LIUER, "It's not just my broom anymore. It's the town's broom. Whoever needs it next gets it. That's how legends work, right?"),
            v=0),
          B("hunt", "Void Wraiths, the Temple's Last Watch",
            "A last cluster of void wraiths tests the temple's wards even as the town gathers for its farewell.",
            foe="void_wraith", v=0),
          B("gather", "Tribulation Jade for the Whole Town",
            "There isn't enough jade for every household, so the town agrees to keep one piece in the temple, shared by all.",
            item="tribulation_jade", v=0),
          B("social", "Zhou's Ninth Page",
            "Magistrate Zhou, asked what the other eight pages of his speech said, admits he never actually wrote them.",
            (ZHOU, "There were no other pages. I just wanted it to sound like I'd prepared more than one word. Hold is easier to believe with a prop."),
            v=0),
          B("interlude", "See You Later",
            "You leave Qingshi at dusk. The whole town lines the road. Nobody says goodbye. Everybody says see you later.",
            (DU, "See you later. That's what Iron-Fang says. So that's what the town says. See you later. At the gate. On the stair. Later."),
            "|",
            (LIUER, "See you later, Senior Brother. Senior Sister. Whichever. See you later. I'll be the loudest one at the gate. After Thunder Peak."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 87
    C("Han Xue's Soul", "sect",
      "Han Xue has been close to forming her nascent soul for a year, and has refused to try while you needed guarding. "
      "Now she asks you to do what she did for you, long ago in the plum garden: stand guard, and keep the trouble away.",
      cast=[HAN, YUN, WEI, ZHAO, HUA, LU, YAN, SHI], foes=["void_wraith", "heart_demon", "demon_cultivator"],
      items=["spirit_herb", "medicine", "tribulation_jade"], props=["seal", "stone_stele", "bronze_bell"],
      foe_names={"void_wraith": "shadow-born", "heart_demon": "Han Xue's shadow"},
      beats=[
          B("orders", "A Senior Sister Asks",
            "Han Xue asks for something. She never asks for anything. She asks very stiffly.",
            (HAN, "I need to break through. Nascent Soul. I've been close for a year. I didn't want to while you needed guarding."),
            (HAN, "You guarded me once, in your head. When you broke through, I stood guard in the plum garden. Now it's your turn. Please."),
            "@R:PlumGarden", (N, "The plum garden is quiet. The same stone where you established your foundation, years ago. Han Xue sits on it. Very straight."),
            "@T:PlumGarden",
            (HAN, "Breakthroughs attract trouble. Heart demons, jealous juniors, very curious elders. And shadow-born. Keep them away. That's all."),
            ),
          B("defend", "Curious Elders",
            "The first trouble is Elder Hua, Elder Bai, Wei Tong, Zhao Kang and Lu Ping, all of whom want to watch.",
            (LU, "Is she breaking through? Can we watch? Everyone wants to watch! Elder Bai brought a notebook! Wei Tong brought snacks!"),
            "@I:PlumGarden", ">Ward the plum garden against visitors",
            (N, "Your ward rises gently around the plum garden. Outside it, a crowd of well-meaning people press their noses to the light."),
            "@F:OuterPines", (N, "Not all the visitors are well-meaning. In the pines, shadow-born are gathering, drawn by a soul about to form."),
            "@F2:SectGate",
            "@T:SectGate",
            (WEI, "Shadow-born, trying to get at her while she's breaking through. I've been waiting all year to hit one of those for her."),
            foe="void_wraith", foe2="demon_cultivator", prop="seal", thing="the plum garden ward"),
          B("social", "Han Xue's Heart",
            "Halfway through, Han Xue speaks without opening her eyes. Her heart demon is flickering. She's telling you about it.",
            (HAN, "My demon's here. It says I only follow you because I'm afraid to lead. It says I'll be your senior sister forever and nothing else."),
            (P, "You're the one who walked me into the Abyss, Senior Sister. You lead. I follow you."),
            (HAN, "...It went quiet. It didn't like that. Keep talking. About anything. Tell me about the chicken."),
            ),
          B("battle", "Han Xue's Shadow",
            "Han Xue's heart demon steps out of the plum trees: a copy of her, sword drawn, cold eyes. You won't let it reach her.",
            (N, "A figure in Frost Sword blue steps out of the plum trees. Han Xue's face. Han Xue's sword. Eyes like a frozen lake."),
            "@F:PlumGarden",
            "@F2:PlumGarden",
            "@T:PlumGarden",
            (N, "The shadow-Han falls apart like frost in sunlight. Behind you, the real Han Xue breathes out, long and slow, and smiles with her eyes closed."),
            foe="void_wraith", foe2="void_wraith"),
          B("cultivate", "Guarding the Stone",
            "Han Xue's soul is forming. You sit beside her on the stone and hold the ward, and wait, and don't talk about the chicken.",
            "@M:PlumGarden", ">Hold the ward beside Han Xue",
            (N, "Plum petals fall. Han Xue's breath slows. In soul sight, a tiny figure is forming in her chest: a small, straight sword, with her face."),
            "@T:PlumGarden",
            (HAN, "Nascent Soul. It's a sword. Of course it is. With my face. Frowning. Of course it is."),
            (HAN, "Thank you. For guarding. For the plum garden. For everything. That's all. Don't make it weird."),
            ),
          B("social", "Everyone Comes In",
            "The ward comes down, and everyone who has been waiting comes in at once, with snacks.",
            (WEI, "Nascent Soul! Han Xue! I brought snacks! Everyone brought snacks! We've been waiting for hours! The snacks are cold! Eat them!"),
            "|",
            (HUA, "Let me see your wrist. Hm. Steady. Very steady. Stubborn pulse. Like someone else I know."),
            "|",
            (ZHAO, "Congratulations. Now you're only three realms behind the heir instead of seven. I'm eight behind. I'm going to be very dramatic about it."),
            ),
          B("gather", "Plum Blossoms for a New Soul",
            "Wei Tong insists on a tradition he invented just now: plum blossoms for a new soul.",
            (WEI, "New tradition! Plum blossoms for a new soul! I invented it just now! Everyone gather blossoms! Throw them at her!"),
            "@G:PlumGarden", ">Gather plum blossoms for Han Xue",
            "@T:PlumGarden",
            (HAN, "Everyone's throwing plum blossoms at me. I'm going to have petals in my hair for a week. I'm going to allow it. Once."),
            item="spirit_herb", noun="plum blossoms"),
          B("social", "The Sparring Match",
            "Han Xue reminds you, as she always does, that you owe her a sparring match. Now she has a soul to match yours.",
            (HAN, "You owe me a proper sparring match. Remember? From the rim, years ago. Now I've got a soul. Now it'll be closer."),
            (P, "When, Senior Sister?"),
            (HAN, "After. When this is done. After the gate, and the sky. You don't get to ascend without paying your debts. That's my rule."),
            ),
          B("probe", "A Gift of Jade",
            "You give Han Xue a piece of your tribulation jade. She holds it for a long time.",
            "@I:PlumGarden", ">Give Han Xue your tribulation jade",
            (N, "She holds the jade in both hands. It's warm. She doesn't say anything. She puts it inside her robe, over her heart, next to her new soul."),
            "@T:Pavilion",
            (HAN, "Warm forever, the star-gazer said. Good. I get cold on the Frost Sword Peak. I'll wear it. Always. Don't tell anyone."),
            prop="seal", thing="the tribulation jade"),
          B("hunt", "Shadow-Born, the Plum Garden's Last",
            "A last handful of shadow-born, drawn by the breakthrough's afterglow, tests the plum garden's edges overnight.",
            foe="void_wraith", v=0),
          B("gather", "Medicine for the New Nascent Soul",
            "Elder Hua insists a fresh nascent soul needs a specific tonic, and Xiao Man is dispatched to gather the herbs.",
            item="medicine", v=0),
          B("social", "Wei Tong's Blossom Tradition, Formalized",
            "Wei Tong petitions the Sect Master to make plum-blossom-throwing an official sect tradition for every future breakthrough.",
            (WEI, "Official! In the sect rules! Right after 'no fighting near the tea sets'! I'm very serious about this!"),
            v=0),
          B("hunt", "Demon Cultivators, the Outer Watch",
            "A pair of demon cultivators, drawn by the same afterglow as the shadow-born, test the outer wall's watch.",
            foe="demon_cultivator", v=0),
          B("gather", "Spirit Herbs for Han Xue's New Sword Style",
            "Han Xue, adjusting to her new soul, asks for spirit herbs to support the more demanding forms she can now attempt.",
            item="spirit_herb", v=0),
          B("probe", "Elder Bai's Notebook",
            "Elder Bai, having watched the whole breakthrough from outside the ward, reveals pages of surprisingly detailed notes.",
            (BAI, "I recorded everything! The ward's exact shade of green! The timing of the plum petals! Science demands rigor, even at a distance!"),
            v=0),
          B("social", "Zhao Kang's Wager",
            "Zhao Kang, prompted by the Sect Master's comment, formally wagers Wei Tong that he'll form his own nascent soul within the year.",
            (ZHAO, "One year. If I don't do it, I owe Wei Tong a hundred buns. If I do, he owes me a spar he can't win. Deal?"),
            (WEI, "Deal! I like this bet either way! Buns or a spar! I win regardless!"),
            v=0),
          B("hunt", "Shadow-Born, a Second Test",
            "The shadow-born return once more that night, testing whether the ward holds without the breakthrough's power feeding it.",
            foe="void_wraith", v=0),
          B("gather", "Tribulation Jade for Zhao Kang's Wager",
            "Zhao Kang, motivated by his new wager, asks for a small piece of jade to keep as incentive during his own cultivation push.",
            item="tribulation_jade", v=0),
          B("social", "Xiao Shi's Congratulations",
            "Xiao Shi, ever precise, calculates exactly how many days it's been since Han Xue first mentioned being close to her breakthrough.",
            (SHI, "Three hundred and eleven days of waiting. I kept count because someone should appreciate patience properly. Congratulations, Senior Sister."),
            v=0),
          B("interlude", "Two Souls on the Mountain",
            "That night, from the cliff edge, you can see two souls glowing on the mountain: yours, and a small, straight sword.",
            (YUN, "Two nascent souls younger than thirty on my mountain. Three hundred years since that happened. The last two founded the sect."),
            (YUN, "Zhao Kang is next, he says. He's been saying it for a year. He's very close. He needs a push. Maybe a wager."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 88
    C("Zhao Kang's Wager", "sect",
      "Zhao Tianlu, a hundred and fifteen years old, climbs the steps one last time to name his great-grandson head of the "
      "Zhao clan. Zhao Kang doesn't want it. He wants something else: a wager with you, for old times' sake, before the "
      "sky takes you somewhere he can't follow.",
      cast=[ZHAO, TIANLU, HAN, WEI, YUN, LU, QIAN], foes=["sparring_disciple", "void_wraith", "training_puppet"],
      items=["spirit_stone", "letter", "tribulation_jade"], props=["stone_stele", "seal", "treasure_chest"],
      foe_names={"sparring_disciple": "Zhao clan champions"},
      things={"stone_stele": "Zhao Ming's stone"},
      beats=[
          B("orders", "The Last Palanquin",
            "The gold palanquin climbs the nine thousand steps one last time. The Zhao ancestor has something to say.",
            (LU, "The gold palanquin! Again! The bearers are older now! One of them is crying again! It's the same one!"),
            "@R:SectGate", (N, "The palanquin sets down at the gate. The ancestor steps out, slower than last time, leaning on a cane of gold."),
            "@T:SectGate",
            (TIANLU, "A hundred and fifteen. I've climbed these steps for the last time. I've come to name my heir. Where is he? Hiding?"),
            ),
          B("social", "Zhao Kang Hides Again",
            "Zhao Kang is hiding. Behind the turtle soup books again. Elder Bai has given up and brought him tea.",
            (ZHAO, "I don't want to be clan head. I want to be here. At the gate. When it opens. With you. And then I want to fight you, when you come back down."),
            (ZHAO, "He'll say I have to. The clan needs me. I know the clan needs me. I just... need something first."),
            (P, "What do you need, Zhao Kang?"),
            (ZHAO, "A wager. With you. Like when we were idiots. One last idiotic wager. Then I'll be clan head. Then I'll be an adult. Ugh."),
            ),
          B("social", "The Wager",
            "The wager: if Zhao Kang can reach the golden core's peak before your tribulation, you owe him a bout when you come back down.",
            (ZHAO, "The wager. If I reach the peak of Core Formation before your sky falls, you owe me a proper bout when you come back down. Properly."),
            (ZHAO, "If I don't, I... I'll be clan head without complaining. For a month. That's the stakes."),
            (P, "You're on. Though I'd have given you the bout anyway."),
            (ZHAO, "I know. That's why it has to be a wager. So it's earned. Zhao clan standards. Low ones, but standards."),
            ),
          B("train", "Training for the Wager",
            "Zhao Kang trains for a month. Day and night. You help. So does everyone. He complains the whole time. It works.",
            (ZHAO, "Train! Now! Puppets! Harder puppets! Wei Tong, tune them to furious! I want furious!"),
            "@F:TrainingGround", ">Help Zhao Kang train on furious puppets",
            (WEI, "Furious puppets! For Zhao Kang! I've never tuned them this high! One of them is growling! Puppets can't growl!"),
            "@T:WeaponRack",
            (ZHAO, "One month. Every day. I've never trained this hard. I've never complained this hard. It's the best month of my life."),
            foe="training_puppet", count=5),
          B("duel", "The Clan Champions",
            "The Zhao clan's champions want to test their future head. They're very polite about it, and very hard to beat.",
            (TIANLU, "My champions. They want to test the boy. The old way. You'll stand beside him. The Zhao clan's test always has a friend in it."),
            "@F:FormationArray", ">Stand beside Zhao Kang against the champions",
            "@T:SectGate",
            (TIANLU, "He beat them. With you beside him, but he beat them. His brother did the same. The Zhao clan is in good hands. Stubborn ones."),
            foe="sparring_disciple", count=4),
          B("cultivate", "Zhao Kang's Peak",
            "On the last night of the month, Zhao Kang sits at his brother's stone, and reaches for the peak.",
            (ZHAO, "Sit with me. At Ming's stone. I'm going to try. If I don't make it, don't tell anyone I cried."),
            "@M:CliffEdge", ">Sit with Zhao Kang as he reaches for his peak",
            (N, "Incense for Zhao Ming, twisting over the sea of clouds. Zhao Kang's golden core burns brighter and brighter, like a lantern with a crack in it, letting the light out."),
            (N, "Peak of Core Formation. And beside him, your own cultivation rises with his: late stage of Mahayana."),
            "@T:SectGate",
            (ZHAO, "Peak. I made it. I won. You owe me a bout. When you come back down. I'm going to win that too."),
            ),
          B("social", "The Ancestor's Blessing",
            "Zhao Tianlu names his great-grandson head of the clan, in front of the whole sect. Zhao Kang doesn't hide.",
            (TIANLU, "Zhao Kang. Head of the Zhao clan. Who will lead it from the Azure Cloud, because that's where his heart is. The clan agrees. I agree."),
            (ZHAO, "...Thank you, Great-Grandfather. I'll write monthly. With love. In gold ink. Because we're the Zhao clan."),
            "|",
            (TIANLU, "Gold ink. Of course. You've learned something after all. Now I'm going home to die in comfort. In about twenty years. Out of spite."),
            ),
          B("gather", "Jade for the Zhao Clan",
            "You give Zhao Kang a piece of your tribulation jade. He gives you something back: the small copy of his brother's stone.",
            (ZHAO, "Your jade. Warm. I'll keep it with the monthly letters. And here. Ming's stone. The small one. Take it up the stair with you."),
            (ZHAO, "So a Zhao climbs to heaven too. First out of the grotto. First up the stair. Ming would've liked that."),
            "@G:SectGate", ">Gather the Zhao clan's farewell gifts",
            "@T:SectGate",
            (QIAN, "Gifts from the Zhao clan. Gold. For the treasury. For the march. I'm not going to faint. I've grown. I've grown so much."),
            item="spirit_stone", noun="clan gifts"),
          B("battle", "Shadows at the Palanquin",
            "The Seventh Rung's shadows come for the palanquin on its way down, to hurt someone you love. They find Zhao Kang waiting.",
            (ZHAO, "Shadows! At Great-Grandfather's palanquin! On MY steps! I'm clan head now! Nobody touches the palanquin!"),
            "@F:SectGate",
            "@F2:OuterPines",
            "@T:SectGate",
            (ZHAO, "Clan head for one day and I've already defended the palanquin. Great-Grandfather says I'm too dramatic. He's smiling."),
            foe="void_wraith", foe2="void_wraith"),
          B("interlude", "When You Come Back Down",
            "Zhao Kang walks you to the cliff edge. He says the thing he's going to say again, years from now, at the ruins.",
            (ZHAO, "When you come back down, we fight. Properly. Promise. Not see-you-later. A promise. Zhao clan standards."),
            (P, "When I come back down, Zhao Kang."),
            (ZHAO, "Good. Hmph. Go and be struck by lightning. I'll be here. Complaining. Forever."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 89
    C("The Red Star Aligns", "sky_isles",
      "Qing Luan calls you back to the isles. The seventh red star, Xue Chen's, is sliding into place over the tribulation "
      "peak, and the moon is redder every night. She has finally read the whole chart, and she wishes she hadn't.",
      cast=[SAGE, HAN, YE, ZHAO, YUN], foes=["void_wraith", "celestial_sentinel", "thunder_wolf"],
      items=["tribulation_jade", "thunder_crystal", "cloud_silk"], props=["stone_stele", "seal", "spirit_stone"],
      foe_names={"void_wraith": "shadow-born", "thunder_wolf": "storm wolves"},
      things={"stone_stele": "the star chart"},
      beats=[
          B("orders", "The Chart Read Whole",
            "Qing Luan's crane says only: come. I've read the whole chart. It's worse. Bring the sword girl. And the nameless one.",
            (YUN, "The star-gazer's crane. 'Come. Read the whole chart. Worse.' Take Han Xue. And Ye Wuming. She asked for him. By description."),
            "@R:sky_isles/CloudGate", (N, "The isles are dim. Above, the moon hangs full and dark red, like an eye that's been crying."),
            "@T:CloudGate",
            (SAGE, "You came. Good. Sit. Don't sit. Stand. This is standing news. I'm not cheerful. I'll never be cheerful again. Look at the chart."),
            map="sect"),
          B("probe", "The Whole Chart",
            "On the star pavilion's jade floor, the whole chart, read at last. The ladder, the moon, the ninth bolt, and the stair.",
            "@R:StarPavilion", (N, "Seven red stars in a ladder. Six dark. The seventh bright, over the peak. The moon's path crossing it. The ninth ring, red. And the stair."),
            "@I:StarPavilion", ">Read the whole star chart",
            (N, "The last blood moon rises. The fold opens. The Patriarch falls, or seems to. His soul climbs the seventh rung to the peak, and rides the ninth bolt into you."),
            "@T:CloudGate",
            (SAGE, "That's his plan. Three hundred years. Your body, cleaned by heaven's own lightning, with him inside it. Walking up the stair."),
            (SAGE, "Unless the seventh rung falls first. Then he has nothing to climb. Then he has to jump. Jumping is much harder."),
            prop="stone_stele", thing="the star chart"),
          B("social", "Ye Wuming Reads It Too",
            "Ye Wuming reads the chart. He's quiet for a long time. Then he says what he's decided.",
            (YE, "The seventh rung. Xue Chen. The boy in the mirror. If he falls before the moon, the Patriarch has to jump. He might miss."),
            (YE, "I'll try to steal him back. Before. If I can't, you'll have to break him. I'm sorry. I wish there were a third way."),
            "|",
            (HAN, "There's always a third way. We just haven't found it yet. We'll look. Until the moon rises. Then we'll do what we have to."),
            ),
          B("battle", "Shadow-Born on the Isles",
            "The shadow-born have followed the red star to the isles. They're guarding the peak, waiting for their master's son.",
            (ZHAO, "Shadows! On the isles! Guarding the peak! I followed you up the stair! Obviously! I'm clan head! I do what I want!"),
            "@F:JadeBridge",
            "@F2:ImmortalGarden",
            "@T:CloudGate",
            (ZHAO, "They're guarding the peak for Xue Chen. For the night of the moon. We should break their guard now. So it's broken then."),
            foe="void_wraith", foe2="void_wraith"),
          B("hunt", "The Peak's Guardians",
            "The shadow-born have taken the tribulation peak's slopes. You can't let them hold it until the moon.",
            "@R:CelestialRuins", (N, "Shadow-born crouch on the peak's lower slopes, among the ruins, in a ring. They're drawing something on the stones. A ladder."),
            "@F:CelestialRuins",
            "@G:CelestialRuins", ">Gather the stones they drew on",
            "@T:CloudGate",
            (YE, "A ladder, drawn on the slopes. Seven rungs. Six scratched out. The seventh fresh. They're making sure he knows the way."),
            foe="void_wraith", item="tribulation_jade", noun="drawn-on stones"),
          B("cultivate", "Watching the Red Moon",
            "Qing Luan asks you to watch the red moon rise with her. She says it helps to look at what's coming.",
            (SAGE, "Watch it rise. The red moon. Every month, redder. The last one will be the colour of the Patriarch's robes. Look at it."),
            "@M:IsleOfWinds", ">Watch the red moon rise",
            (N, "The moon rises red over the sea of clouds. Beneath it, the fold is a dark smudge on the earth. Above it, heaven's spiral turns. All three, lining up."),
            "@T:CloudGate",
            (SAGE, "Months. Not years. Months. The moon, the fold, the stair and your lightning. All one night. I've never seen stars this certain."),
            ),
          B("social", "Qing Luan's Promise",
            "Qing Luan makes a promise: on the night, she'll be at the cloud gate. Whatever happens.",
            (SAGE, "On the night, I'll be at the cloud gate. When the Patriarch's soul crosses my bridge, I'll see it. I'll tell you. Loudly."),
            (SAGE, "Ten thousand years I watched the stair and did nothing. Not this time. This time I'll shout."),
            "|",
            (HAN, "You'll shout. I'll hold the bridge. Zhao Kang will complain. Ye Wuming will hold the abyss. Everyone has a job. Good."),
            ),
          B("gather", "Crystals for the Peak",
            "Before you leave, you plant the first of Elder Bai's ninety-nine crystals on the peak's lower slopes. The delta begins.",
            (SAGE, "Plant the first crystals now. On the lower slopes. Let them settle in. Crystals like to get to know a place before they work."),
            "@G:CelestialRuins", ">Plant the delta's first crystals",
            "@T:CloudGate",
            (SAGE, "Forty on the slopes. The rest on the night. The delta's begun. Your founder's plan, in your hands. She'd be glad."),
            item="thunder_crystal", noun="delta crystals"),
          B("probe", "Xue Chen at the Peak",
            "As you leave, you see him again: Xue Chen, on the summit, alone, looking at the red moon. He doesn't wave. He doesn't bow.",
            "@R:IsleOfWinds", (N, "On the summit, a young man in dark red, alone, looking up at the moon. He doesn't wave. He looks tired. He looks three years old."),
            "@I:StarPavilion", ">Watch Xue Chen through the star chart",
            (N, "Through the chart, his star flickers. Not bright and certain like the others were. Flickering. Like someone who isn't sure."),
            "@T:CloudGate",
            (YE, "He's not sure. His star's flickering. Nobody in the Ladder ever flickered. There's a door there. A small one. We'll try it."),
            prop="stone_stele", thing="the star chart"),
          B("interlude", "Down to the Last Preparations",
            "You go down the stair. Months, not years. Everyone on the mountain looks up at the moon every night now.",
            (YUN, "Months. We prepare. Everyone. Forty sects, one mountain, one moon. And one boy on a peak who isn't sure."),
            (YUN, "Rest while you can. Say your goodbyes. And one day soon, the moon will be the colour of his robes."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 90
    C("The Stair Remembers", "sky_isles",
      "Qing Luan takes you to the foot of the Ascension Stair, the stair nobody has climbed since your founders pulled the "
      "Patriarch off it. You won't climb it today. She just wants the stair to meet you, and you to meet it, before the "
      "night when everything happens at once.",
      cast=[SAGE, HAN, ZHAO, YUN, WEI], foes=["celestial_sentinel", "void_wraith", "thunder_wolf"],
      items=["cloud_silk", "tribulation_jade", "star_iron"], props=["stone_stele", "seal", "spirit_stone"],
      foe_names={"void_wraith": "shadow-born", "thunder_wolf": "storm wolves"},
      beats=[
          B("orders", "To the Foot of the Stair",
            "Qing Luan meets you at the cloud gate with a lantern, though it's day. She says the stair likes lanterns.",
            (SAGE, "A lantern. The stair likes them. Don't ask me why. Ten thousand years and I still don't understand it. Follow me."),
            "@R:sky_isles/CloudGate", (N, "Qing Luan walks ahead with a lantern in broad daylight, humming. The isles are quiet. The red moon is a pale ghost in the day sky."),
            "@T:CloudGate",
            (SAGE, "The stair. Nobody's stood at its foot since your founders. I want it to meet you. Before the night. So it knows your face."),
            map="sect"),
          B("battle", "The Stair's Sentinels",
            "The stair has its own sentinels, older than the palace's. They don't want anyone near. Qing Luan tells them to move.",
            (SAGE, "Move! I was a sage when your stones were still stars! Move! ...They won't move. Hit them. Gently. They're very old."),
            "@F:CelestialRuins",
            "@F2:JadeBridge",
            "@T:CloudGate",
            (SAGE, "They'll let you pass now. They bowed. They never bow. The stair must have told them to. It's curious about you."),
            foe="celestial_sentinel", foe2="celestial_sentinel"),
          B("probe", "The Ascension Stair",
            "At the foot of the Ascension Stair, you look up. Each step is made of light. It climbs into cloud, and out of sight.",
            "@R:AscensionStair", (N, "The Ascension Stair climbs into cloud, each step made of light. It hums, very quietly. As you watch, the first step brightens."),
            "@I:AscensionStair", ">Lay your hand on the first step",
            (N, "The step is warm. It knows you. Not yet, it seems to say. Soon. It dims again, patiently. It has waited ten thousand years. It can wait a few months."),
            "@T:CloudGate",
            (SAGE, "It knew you. It brightened. It told you not yet. That's a stair being polite. Stairs are almost never polite."),
            prop="seal", thing="the first step"),
          B("social", "What's at the Top",
            "Everyone asks the same question: what's at the top? Qing Luan doesn't know. Nobody does.",
            (ZHAO, "What's at the top? Heaven? A door? A very large tea room? I need to know what to complain about."),
            (SAGE, "A door, I think. I watched your founders pull him down before he reached it. Nobody's ever knocked on it."),
            "|",
            (HAN, "Then you'll be the first to knock. Be polite. Heaven's sensitive about manners, the star-gazer says. Don't knock too loud."),
            (P, "I'll knock gently, Senior Sister."),
            ),
          B("gather", "Silk for the Stair",
            "Qing Luan asks you to tie cloud silk to the stair's railing. For every person you love. So the stair remembers them too.",
            (SAGE, "Tie silk to the stair. One ribbon for everyone you love. The stair will remember them. When you climb, they'll climb with you. In a way."),
            "@G:IsleOfWinds", ">Gather silk ribbons for everyone you love",
            "@T:CloudGate",
            (WEI, "I followed you up! Again! You're tying ribbons! For everyone! Is there one for me? There's one for me! There's one for Elder Mo!"),
            item="cloud_silk", noun="silk ribbons"),
          B("social", "Ribbons for Everyone",
            "Ribbons for everyone: Elder Mo, the hermit, Madam Fang, the Xiao siblings, Iron-Fang, Ye Wuming, even Gu Hanshan.",
            (SAGE, "Gu Hanshan? The traitor? You tied a ribbon for him?"),
            (P, "He's trying. That's worth a ribbon."),
            (SAGE, "...You're going to be a very strange immortal. Heaven's going to have no idea what to do with you. I'm delighted."),
            "|",
            (WEI, "Elder Mo's ribbon is blue. And straight. I tied it very straight. He'd want it straight."),
            ),
          B("hunt", "Shadows on the Stair",
            "Shadow-born try to climb the stair's lowest steps, testing it for their master. The stair burns them.",
            "@R:AscensionStair", (N, "Shadow-born claw at the stair's lowest steps. Each time they touch it, they burn, and shriek, and try again."),
            "@F:ImmortalGarden",
            "@G:ImmortalGarden", ">Gather the ash of the burned shadows",
            "@T:CloudGate",
            (SAGE, "The stair burns anything that isn't its own. Anything carrying something that isn't theirs. The palace inscription said so. A stolen body. A stolen heaven."),
            foe="void_wraith", item="tribulation_jade", noun="shadow ash"),
          B("cultivate", "Sitting at the Stair",
            "You sit at the foot of the stair for an hour, and let it get to know you. It hums. You hum back.",
            "@M:CloudGate", ">Sit at the foot of the Ascension Stair",
            (N, "The stair hums a note too low to hear. You hum it back. For an hour, you and the stair are alone on the isles, getting acquainted."),
            "@T:CloudGate",
            (SAGE, "It likes you. The stair likes you. I've never seen it like anyone. It liked your founder, a little. It likes you more."),
            ),
          B("social", "The Sect Master Comes Up",
            "The Sect Master comes up the cloud road to see the stair herself. She's never seen it. She's never had time.",
            (YUN, "The Ascension Stair. I've been sect master for eleven years and never seen it. I never had time. I'm taking time."),
            (YUN, "When you climb it, I'll be at the cloud gate. I'll bow. I'll try not to cry. I'll fail."),
            (P, "Sect Master, you said I don't have to go."),
            (YUN, "You don't. But you will. Because someone should see what's up there. That's what I'd say. That's what you'll say."),
            ),
          B("interlude", "The Moon Is Almost Red",
            "On the way down, the moon rises, and it's almost the colour of the Patriarch's robes. Almost.",
            (SAGE, "Almost red. One more month. Maybe two. Go home. Get ready. I'll be here. Frowning. Fondly."),
            "|",
            (HAN, "One more month. Then everything, all at once. I'll hold the bridge. You hold everything else. Like always."),
            ),
      ]),
]
