"""Volume I · Qi Condensation — new chapters 4-10 (after "Shadows over Qingshi").

The Sect Master is in secluded cultivation, steadying the Azure Eye; the
Qingshi report must wait for her. Meanwhile: sect life, a herb harvest, the
remnants of Iron-Fang's gang, the outer sect examination, the Ghost Festival
in Qingshi and the first secret realm. Elder Gu is still trusted; the
Verdant Lotus is still a secret; Xiao Man is away with the herb caravan.
"""

from .dsl import N, P
from .npcs import *  # noqa: F401,F403
from .saga_gen import B, C

CHAPTERS = [
    # ------------------------------------------------------------------ chapter 4
    C("A Closed Door on the Mountain", "sect",
      "Home from Qingshi with a deacon's dying words, you find the main hall sealed: the Sect Master is in secluded "
      "cultivation, steadying the flickering Azure Eye. Until she emerges there are contribution points to earn, a "
      "treasury that keeps losing stones, and a mountain that has begun to notice you.",
      cast=[MO, WEI, QIAN, LU, HAN, BAI, HUA], foes=["training_puppet", "spirit_wolf"],
      items=["spirit_stone", "spirit_herb", "jade_slip"], props=["treasure_chest", "stone_stele", "bronze_bell"],
      things={"treasure_chest": "the treasury strongbox", "stone_stele": "the contribution stele"},
      beats=[
          B("orders", "The Sealed Doors",
            "The main hall is shut and sealed with gold paper. Elder Mo says the Sect Master entered seclusion the night you left.",
            "@R:MainHall", ">Report at the main hall",
            (N, "The doors of the main hall are shut and sealed with a strip of gold paper. Behind them, the Azure Eye hums louder than you remember."),
            "@T",
            (MO, "She went into seclusion the night you left for Qingshi. The Azure Eye has been flickering, and she won't say why."),
            (P, "Elder, the deacon said the Patriarch has friends in high halls."),
            (MO, "Then we tell her and no one else. Write your report. I'll slip it under her door myself."),
            (MO, "Meanwhile you'll do what disciples do. Work, eat, stay out of trouble. Two out of three will do."),
            giver=LU, v=0),
          B("probe", "Points on the Stele",
            "Outer disciples earn contribution points by doing the sect's chores. Your name on the stele has a very lonely zero beside it.",
            "@R:SectGate",
            (N, "The contribution stele lists every outer disciple and their points. Beside your name, a single zero sits like an egg."),
            "@I:SectGate", ">Read the contribution stele",
            (N, "Zhao Kang: four hundred and twelve. Wei Tong: nine, and a note in Steward Qian's hand that says 'dumplings are not a contribution'."),
            "@T",
            (LU, "Points buy pills, manuals, a better bunk. Or you can do what I do and earn them by being charming."),
            (P, "How many points has charm earned you?"),
            (LU, "Three. But they were very charming points. Go see Steward Qian, he's handing out chores."),
            v=0),
          B("gather", "The Missing Spirit Stones",
            "Steward Qian swears the treasury is short by eleven spirit stones and that somebody in this sect is a thief.",
            (QIAN, "Eleven spirit stones! Gone! I count them every night and every morning, and twice at lunch."),
            (QIAN, "No lock broken, no seal touched. A thief who walks through walls. Find them, and I'll write you ten points."),
            (P, "Ten? For eleven stones?"),
            (QIAN, "Nine, then. Don't haggle with a steward, disciple. We're born haggling."),
            "@G:PlumGarden", ">Follow the glinting trail through the plum garden",
            "@T",
            (QIAN, "Under a plum tree? In a nest? Lined with my stones? Show me the thief."),
            (P, "A spirit ferret, Steward. It likes shiny things. It has also stolen three hairpins and somebody's spectacles."),
            (QIAN, "Elder Bai's spectacles! He's been reading with his nose for a week. Ten points. No, eleven. I'm generous."),
            item="spirit_stone", gcount=5, v=0),
          B("train", "Puppets Before Breakfast",
            "Wei Tong has taken on a class of brand-new disciples and would like a demonstration that does not end in tears.",
            (WEI, "New disciples! Twelve of them, and they all looked at the puppets like they were ghosts."),
            (WEI, "Show them it can be done. Politely. With your feet, not your elbows. You know the speech."),
            "@F:TrainingGround", ">Demonstrate on the training puppets",
            (WEI, "Watch the stance, everyone! Look how bored the puppet looks. That's how you know it's losing."),
            "@T",
            (WEI, "Twelve disciples, twelve dropped jaws. One of them asked if you were an elder. I said yes."),
            (P, "Senior Brother!"),
            (WEI, "It got them to stand up straight! Here, a steamed bun. Contribution points are nice, buns are nicer."),
            foe="training_puppet", count=4, v=0),
          B("probe", "Dust in the Fourth Floor", "Elder Bai wants the Blood Moon War chronicles copied before anything else goes missing from his shelves.",
            (BAI, "My spectacles are back, and I can see again, which means I can see how much work there is."),
            (BAI, "I want every scroll that mentions the Blood Moon War copied, twice, and hidden in two places. Humour an old man."),
            "@R:Pagoda", (N, "The pagoda's fourth floor smells of dust and camphor. A gap on the east shelf shows where something was taken."),
            "@I:Pavilion", ">Copy the war chronicles in the quiet pavilion",
            (N, "You copy until your wrist aches. The chronicles praise the Azure Cloud's founder, and mention an ally only once, as 'our green friends'."),
            "@T",
            (BAI, "'Our green friends.' Always that phrase. Someone went to great trouble to make a whole sect into a footnote."),
            (BAI, "Put your copy behind the turtle soup recipes. Nobody ever reads those. Except me."),
            prop="jade_slip", v=1),
          B("hunt", "Wolves Under the Wall",
            "Howling again, beyond the outer pines. The wolves are thin, frightened, and closer to the sect than wolves should be.",
            "@R:OuterPines",
            (N, "Beyond the outer pines, three wolves watch you with ordinary grey eyes. Not red. Only hungry, and afraid of something behind them."),
            "@F:OuterPines",
            (HAN, "Drive them off, don't kill them if you can. Their eyes are clean. Something chased them here."),
            "@T",
            (HAN, "They came from the bamboo forest. Whatever was feeding the wolf king blood, the rest of the pack remembers it."),
            (P, "The deacon's dead. Who's still doing it?"),
            (HAN, "That's the right question. Keep asking it quietly. Some people in this sect dislike questions."),
            foe="spirit_wolf", item="wolf_fang", noun="shed wolf fur", v=0),
          B("social", "Contribution by Kindness",
            "The sect is short-handed with the Medicine Hall's apprentice away on the herb caravan. Chores pile up in odd places.",
            (HUA, "Xiao Man has gone south with the herb caravan for the season, and I've discovered she did the work of three."),
            (HUA, "I need the drying racks turned. I need the moonbell fed. Please don't ask what moonbell eats."),
            "|",
            (LU, "You're doing Xiao Man's chores? She waters the gate lanterns, you know. I never asked why. Now you can."),
            (P, "Why does she water the lanterns?"),
            (LU, "Luck, she says. And nothing's attacked the gate since she started. Mostly nothing."),
            "|",
            (MO, "Eleven points for a ferret, four for puppets, six for the Medicine Hall. You're climbing the stele."),
            (MO, "Hmph. Don't grin. The stele is stone. It doesn't care, and neither do I."),
            (MO, "...I'm told I'm grinning. I'm not. Go away."),
            v=0),
          B("probe", "A Letter Under the Door",
            "Someone else slid a letter under the Sect Master's sealed door. Elder Mo found it, and does not like the handwriting.",
            (MO, "Your report went under her door. So did another, this morning. Unsigned, and folded in the Law Hall's way."),
            (MO, "I don't read other people's letters. I read the envelopes. This one smelled of blood lotus."),
            "@R:MainHall", (N, "Faint footprints lead from the sealed doors toward the scholar rock and the Law Hall beyond, then vanish on swept stone."),
            "@I:MainHall", ">Examine the sealed hall doors",
            (N, "The gold seal is intact. Your pendant warms as you pass it, as if the doors were breathing on the other side."),
            "@T",
            (HAN, "Law Hall folding and blood lotus. Might mean nothing. The Law Hall handles evidence, and evidence smells."),
            (HAN, "Might mean something. Tell no one but Elder Mo. And me. You've told me, so that's done."),
            prop="seal", giver=MO, v=1),
          B("defend", "The Bell Nobody Rang",
            "At midnight the gate bell sounds once, then stops. Lu Ping swears he didn't touch it. Something is testing the wall.",
            (LU, "I didn't ring it! I was asleep. I mean, meditating. The bell rang itself, once, and then the pines went quiet."),
            (LU, "Quiet like a held breath. I hate that kind of quiet."),
            "@I:SectGate", ">Ring the gate bell to wake the watch",
            (N, "The bell booms. Lanterns flare along the wall, and in the pines something that was creeping forward stops, and turns."),
            "@F:OuterPines", (N, "Grey wolves come out of the dark, and behind them, a pair of eyes the colour of old blood that does not come closer."),
            "@T",
            (WEI, "Those eyes at the back. Red. Like the wolf king's. It didn't fight. It watched."),
            (P, "It counted us. Like Hong counted graves."),
            (WEI, "I didn't need that thought tonight. I'm going to sleep with Dumpling under my pillow."),
            foe="spirit_wolf", foe2="corrupted_wolf", ally=WEI, v=0),
          B("stage", "The Stele Remembers You",
            "Your points are enough for a cultivation manual and an hour at the formation's edge. Qi gathers faster than it did in spring.",
            (MO, "Enough points for a manual. Choose the Cloud-Step Breathing. It is boring. Boring is how you get strong."),
            (MO, "Go and sit on the stone bridge. Don't come back until your breath is longer than your excuses."),
            "@M:StoneBridge",
            (N, "The Cloud-Step Breathing is boring, exactly as promised. Your qi does not care. It gathers, and gathers, and rises a level."),
            (N, "When you open your eyes, the pond is full of stars, and your meridians feel like rivers after rain."),
            "@T",
            (MO, "Middle stage. Adequate. Back straight, though. The pond saw you slouching."),
            giver=MO, v=0),
      ]),
    # ------------------------------------------------------------------ chapter 5
    C("The Moonbell Harvest", "bamboo_forest",
      "Elder Hua's autumn harvest takes you back into the Whispering Bamboo, where the herb grove is sickening "
      "and the spirit spring runs faintly red. The hermit pours tea, the wolves are gone, and something beneath "
      "the old den is still bleeding into the earth.",
      cast=[HUA, WEI, LAN, HAN], foes=["corrupted_wolf", "spirit_wolf", "bandit"],
      items=["spirit_herb", "blood_lotus", "wolf_fang"], props=["seal", "treasure_chest", "stone_stele"],
      things={"seal": "the blood-rune seal"},
      beats=[
          B("journey", "Baskets for the Bamboo",
            "Elder Hua is taking the Medicine Hall to the bamboo forest for the autumn harvest, and you have been volunteered as a mule.",
            (HUA, "Twelve baskets, three disciples, one forest. The moonbell sprouts are ripe and they won't pick themselves. They bite, remember."),
            (HUA, "Wei Tong has gone ahead to 'scout'. That means he's found somewhere to eat. Find him."),
            (P, "And if he's eaten the baskets?"),
            (HUA, "Then you'll carry the herbs in your robe. Go on."),
            "@R:ForestPath", (N, "The forest path is carpeted in gold leaves. It is almost peaceful, if you forget the last time you walked it."),
            "@T",
            (WEI, "I scouted. The mushrooms by the stream are delicious. Well, one was. The other was educational."),
            (WEI, "The grove's further in. I didn't want to go alone. Not after last time. Let's go together."),
            v=0),
          B("gather", "Ash on the Moonbell",
            "The herb grove's moonbell is spotted with grey ash that smears like blood when you touch it.",
            "@R:HerbGrove",
            (N, "Half the moonbell in the grove is spotted grey. When you rub the spots, your fingers come away red."),
            "@G:HerbGrove", ">Pick the healthy moonbell",
            "@T",
            (HUA, "Blood qi, in the soil. The grove is drinking it up from somewhere deeper."),
            (HUA, "Healthy ones in this basket, sick ones in that one. Don't eat either. Wei Tong, I'm looking at you."),
            giver=WEI, item="spirit_herb", noun="healthy moonbell", v=2),
          B("probe", "Tea With the Hermit",
            "The hermit of the bamboo is expecting you. He has poured three cups, which is one more than there are of you.",
            "@R:HermitHut", (N, "Three cups of tea steam on the hermit's step. He looks at your baskets, then at the grey ash on your fingers."),
            "@T",
            (LAN, "Ash on the moonbell. Ah. The den still bleeds, then. Old wounds in the earth close slower than in people."),
            (P, "The wolf king's den? The wolf king is dead."),
            (LAN, "The wolf is. The blood they poured into him is not. It soaked down, and down, and is still looking for a way up."),
            (LAN, "The third cup is for your Elder Hua. She never drinks it. I keep pouring. That is what hope looks like at my age."),
            v=0),
          B("hunt", "The Den Still Bleeds",
            "Down in the old wolf den, the rock weeps red. Something has moved in to drink from it.",
            "@R:WolfDen", (N, "The wolf den breathes warm air. Red water seeps from cracks in the rock and pools in the hollows."),
            "@F:WolfDen", (WEI, "Wolves. Red-eyed ones. I thought we'd seen the last of these. Dumpling, wake up!"),
            "@G:WolfDen", ">Collect the blood-soaked earth for Elder Hua",
            "@T",
            (WEI, "They weren't a pack. They were just... drinking. Like moths at a lamp."),
            (P, "Then we put out the lamp."),
            foe="corrupted_wolf", item="blood_lotus", noun="blood-soaked earth", ally=WEI, v=0),
          B("delve", "Roots in the Red Rock",
            "The blood seeps from a seal carved deep in the den, far older than the wolf king and nothing like Keeper Hong's work.",
            "@R:WolfDen",
            (N, "At the back of the den a round seal is carved into the rock: a moon swallowing a sword, ringed with runes worn nearly smooth."),
            "@G:WolfDen", ">Gather the loose rune chips around the seal",
            "@I:WolfDen", ">Scrub the blood-rune seal with the hermit's salt",
            (N, "The salt hisses. Red runs out of the grooves. For a moment the seal glows green at its edges, answering your pendant."),
            "@F:HerbGrove", (N, "Somewhere in the grove behind you, the last of the drinking wolves howl, and come."),
            "@R:Clearing", (N, "In the clearing the air smells clean for the first time today. Even the bamboo seems to stand up straighter."),
            item="rune_fragment", foe="corrupted_wolf", v=0),
          B("cultivate", "Salt, Sutras and Silence",
            "The hermit says the seal must be quieted with a still heart, not a sword. He means yours.",
            (LAN, "The Blood Moon carved that seal three centuries ago, to bleed this forest slowly. Somebody has been feeding it again."),
            (LAN, "A sword would crack it. A quiet heart will close it. Go and sit beside it, and be very dull for an hour."),
            (P, "Wei Tong says I'm good at being dull."),
            (LAN, "Your friend is wise in unexpected directions."),
            "@M:SpiritSpring", ">Still your heart beside the spirit spring",
            (N, "You breathe with the spring. Far off, deep in the den, a knot in the earth loosens, and the red in the water thins to nothing."),
            "@T",
            (LAN, "Closed. For now. The forest thanks you. It thanks you by not trying to eat you tomorrow."),
            v=0),
          B("battle", "Bandits at the Harvest",
            "Scavengers from Iron-Fang's broken gang have smelled the Medicine Hall's baskets. Rare herbs sell well in the lowlands.",
            (HAN, "Senior Sister Han Xue, reporting for basket duty. Elder Mo sent me. He said you'd find trouble within the hour."),
            (HAN, "Bandits on the path. Six. They want the herbs. I want them to leave. Let's see who's more persuasive."),
            "@F:ForestPath",
            "@F:OldBridge", (HAN, "More on the bridge! These ones have Iron-Fang's red headbands. The gang didn't scatter as far as we hoped."),
            "@R:Stream", (N, "The bandits flee downstream, leaving one sandal and a very small, very old basket of stolen herbs."),
            foe="bandit", v=0),
          B("social", "What the Bandit Said",
            "One bandit was too slow to run. He is young, frightened, and says something about families that nobody in the sect wants to hear.",
            (HAN, "This one was too slow to run. He's younger than you. He keeps saying the chief made them do it."),
            (HAN, "Ask him. He won't talk to me. I apparently look like I bite."),
            "|",
            (N, "The young bandit won't meet your eyes. They took my mother, he whispers. Iron-Fang says if we don't pay, she doesn't eat."),
            (P, "Who took her? Iron-Fang?"),
            (N, "Not him. Them. The ones with the red moon. He shakes and says no more, and Han Xue lets him run home."),
            "|",
            (LAN, "Families held against good behaviour. That is how they did it three hundred years ago, too. Some recipes never change."),
            (LAN, "Take your herbs home, child. And your questions. Keep the questions somewhere safer than the herbs."),
            v=0),
          B("festival", "Moonbell Wine",
            "The harvest is in. Elder Hua allows exactly one cup of moonbell wine, and the hermit finally drinks his tea.",
            (HUA, "The grove is healing, the baskets are full, and not one of my disciples was bitten. By moonbell. I count wolves separately."),
            (HUA, "Fetch the spring water for the wine. One cup each. I will be counting, and so will the moonbell."),
            "@G:SpiritSpring", ">Fill the flasks at the spirit spring",
            "@I:AncientShrine", ">Pour the first cup at the ruined shrine",
            (N, "You pour a cup onto the stones of the old shrine. A breeze turns the bamboo toward you, and the shrine's cracked lotus carving seems to lean closer."),
            "@T",
            (LAN, "She drank the tea. Forty years I've poured that cup. She drank it and called it bitter."),
            (P, "Is that good?"),
            (LAN, "It's a beginning. The bitter ones always are."),
            item="spirit_herb", noun="spring water", prop="stone_stele", v=0),
          B("interlude", "Carry It Home",
            "The Medicine Hall returns with full baskets and one worried Elder. On the road back, Elder Hua asks what the bandit said.",
            (HUA, "Han Xue says one of those bandits spoke to you. Families held hostage. By the Blood Moon."),
            (HUA, "I've mended bandits before. They always said they had reasons. I never listened. I wonder now how many were true."),
            (P, "We'll tell Elder Mo, and the Sect Master when she comes out."),
            "|",
            (WEI, "I carried four baskets. Four! Elder Hua gave me one dried persimmon for my trouble."),
            (WEI, "It was a very good persimmon. I'd carry four more. Don't tell her."),
            map="bamboo_forest", v=0),
      ]),
    # ------------------------------------------------------------------ chapter 6
    C("Bandits of the Salt Road", "qingshi_town",
      "Iron-Fang's scattered gang is raiding the salt caravans into Qingshi under his lieutenant, Gou the Scarred. "
      "Constable Du wants the road open, Magistrate Zhou wants to look brave, and the bandits want something no "
      "amount of salt can buy.",
      cast=[DU, ZHOU, FANG, PAN, LIU, HAN, JIN], foes=["bandit", "rogue_cultivator"],
      items=["spirit_stone", "medicine", "letter"], props=["treasure_chest", "bronze_bell", "stone_stele"],
      boss=("bandit_chief", "Gou the Scarred", "BanditCamp"),
      foe_names={"bandit": "salt-road bandits"},
      things={"treasure_chest": "the salt-master's strongbox", "bronze_bell": "the caravan bell"},
      beats=[
          B("orders", "No Salt in Qingshi",
            "Qingshi has had no salt for a month. Constable Du asks the sect for help, and Elder Mo sends you and Han Xue down the mountain.",
            (MO, "Qingshi has had no salt in a month. Bandits on the road. The Sect Master is still sealed away, so I'm sending you."),
            (MO, "Han Xue goes too. Don't argue. She's a better cook and a worse liar than you."),
            "@R:qingshi_town/TownGate",
            (N, "Qingshi's gate is open, but the market beyond it is half empty. A child is licking a salt-lick meant for oxen."),
            "@T",
            (DU, "Cultivators. Good. Salt's gone, tempers are short, and last night someone boiled seawater they don't have."),
            (DU, "Caravans vanish on the forest road. Iron-Fang's leftovers, the carters say. Led by a man with a scar like a canal."),
            map="sect", v=0),
          B("probe", "Tallies at the Warehouse",
            "Merchant Jin keeps the guild's salt tallies. He is nervous, overdressed, and suddenly very keen to be helpful.",
            (JIN, "Salt, salt, everybody asks me about salt. The guild lost four caravans. Four! I'm practically a victim."),
            (JIN, "Here, look at the tallies. Every wagon, every weight. I've nothing to hide. Please stop looking at my crates."),
            "@R:Warehouse",
            (N, "The warehouse yard is stacked with empty salt barrels. Somebody has scrubbed the stamps off half of them."),
            "@I:Warehouse", ">Search the guild's salt tallies",
            (N, "The tallies are neat and honest, except for one column, marked with a crescent, where the numbers are far too round."),
            "@T",
            (HAN, "A crescent. Same as Hong's ledger. Jin is still selling to somebody who signs with a moon."),
            (HAN, "Not now. We can't prove anything and we need his wagons. But I'm writing it down. In ink."),
            giver=JIN, prop="stone_stele", thing="the guild tallies", v=1),
          B("social", "Gossip Is Also Salt",
            "Madam Fang's customers complain about the food, the bandits, and the magistrate, in that order.",
            (FANG, "My noodles taste of nothing and my customers taste of complaints. Bring back the salt, immortal, and eat free."),
            (FANG, "The carters drink here. They say the bandits don't take the salt. They take the salt and the carters. Then send the carters home."),
            "|",
            (PAN, "Seen them. From the river. They camp in the old bandit camp in the bamboo, the one you burned last spring."),
            (PAN, "Came back like weeds. They're thinner now. Hungrier. Hungry men are dangerous and sad in equal parts."),
            "|",
            (ZHOU, "The yamen has issued a strongly worded proclamation. It is nailed to the gate. It uses the word 'forthwith' twice."),
            (ZHOU, "I, ah, have also put forty guards on the road. That was Constable Du's idea. The proclamation was mine."),
            v=0),
          B("defend", "Guarding the Last Caravan",
            "The last salt caravan of the season leaves the forest road at dusk. The bandits will not let it pass quietly.",
            (DU, "Last caravan of the season comes out of the bamboo at dusk. If it doesn't reach the gate, the town goes hungry."),
            (DU, "I've six men and a very old spear. You're the rest of the plan."),
            "@I:TownGate", ">Ring the caravan bell at the gate",
            (N, "The caravan bell clangs. Out on the road, wagons creak into a run, and shapes rise out of the ditches on either side."),
            "@F:Farmland",
            (HAN, "They're on the fields! Get between them and the wagons!"),
            "@F:MainStreet",
            "@T",
            (DU, "Every barrel's in. Not one carter hurt. I'm going to write this down in the good ink."),
            (P, "They weren't fighting to kill. They wanted the carters alive."),
            (DU, "Then I'll ask the carters what they were for. Quietly, over a cup of Madam Fang's awful tea."),
            foe="bandit", foe2="rogue_cultivator", prop="bronze_bell", v=0),
          B("probe", "The Carter Who Came Back",
            "A carter taken last week walked home with a message pinned to his coat. It is addressed to the sect.",
            (LIU, "He came to the well at dawn, the carter. Walked like a man asleep. There was a letter pinned to him."),
            (LIU, "I read it. I shouldn't have. It isn't for me. It's for you."),
            "@R:Well", (N, "The carter sits by the well, staring at nothing, a folded paper pinned to his coat with a bandit's knife."),
            "@I:Well", ">Read the letter pinned to the carter",
            (N, "Sect brats. Stay out of the bamboo, and the salt comes back. Come in, and my men stop being gentle. Gou."),
            "@T",
            (HAN, "Gentle. They call that gentle. The man doesn't know his own name."),
            (HAN, "He's afraid of something bigger than us. That's the only reason a bandit writes letters."),
            prop="treasure_chest", thing="the pinned letter", v=1),
          B("chase", "Tracks Toward the Bamboo",
            "The carters' tracks lead off the road and into the forest, toward the camp you burned in spring.",
            "@R:Riverside", (N, "Wheel ruts leave the road at the river and turn toward the dark line of bamboo on the far bank."),
            "@F:bamboo_forest/ForestPath", (N, "Lookouts drop from the bamboo with sharpened poles. They are thin, and frightened, and very determined."),
            "@R:BanditLookout", (N, "From the lookout rock you can see the old camp rebuilt: tents, fires, and a pen full of silent carters."),
            "@T",
            (HAN, "They're holding the carters. Feeding them, even. Like livestock."),
            (P, "Or like hostages. Someone's holding their families. Now they're holding ours."),
            (HAN, "Then we take them all home. Carters first. Answers second. The scarred man last."),
            foe="bandit", map="qingshi_town", v=0),
          B("rescue", "The Pen of Carters",
            "Before Gou can move his prisoners, you slip into the camp at night to open the pen.",
            "@R:BanditCamp", (N, "The pen is a ring of stakes and rope. Inside, a dozen carters sit very still, listening to the fires."),
            "@F:BanditCamp",
            "@I:BanditCamp", ">Cut open the carters' pen",
            (N, "The ropes part. The carters don't run at first. They've forgotten how. Then one laughs, and they all run at once."),
            "@T",
            (HAN, "They're out. Gou isn't in the camp. His tent is empty and warm."),
            (HAN, "He'll be back, and angry. Angry men are sloppy. Let's be the opposite."),
            foe="bandit", prop="prison_cage", thing="the carters' pen", map="bamboo_forest", v=0),
          B("probe", "A Scar Like a Canal",
            "Gou's tent holds maps, a child's wooden toy and a list of names. The names are not his victims.",
            "@R:BanditCamp",
            (N, "Gou's tent is neat as a soldier's. A map of the salt road, a carved wooden horse, and a long list of names."),
            "@I:BanditCamp", ">Search Gou's tent",
            (N, "Beside each name: a village, and the words 'held since'. Beside the last name: Gou's own mother. Held since spring."),
            "@T",
            (HAN, "They're not stealing salt. They're paying a ransom with it. Salt, carters, whatever the moon asks for."),
            (P, "The Blood Moon has their families. Just like the young one said."),
            (HAN, "This goes to Elder Mo. And the Sect Master, when she opens that door. I'm starting to hate that door."),
            prop="treasure_chest", thing="Gou's strongbox", map="bamboo_forest", v=0),
          B("boss", "Gou the Scarred",
            "Gou the Scarred returns to find his camp empty and his hostages gone. He has nothing left to bargain with, and nothing to lose.",
            "@R:BanditLookout", (N, "Torches below. Gou the Scarred is back, and he is not shouting. He is very quietly sharpening a blade on the empty pen."),
            "@X",
            (GOU, "You took my carters. Do you know what that costs me? Not silver. Not salt. My mother's dinner."),
            (P, "Then help us get her back instead. We're not the ones holding her."),
            (GOU, "Nobody gets them back! Nobody! Pick up your sword, sect brat!"),
            "@T",
            (GOU, "Why... didn't you kill me?"),
            (P, "Because you're not the one I'm angry at. Give Constable Du your men's names. All of them. And the villages."),
            (GOU, "...You're a fool. Iron-Fang would've gutted you. Fine. Fine. Names. For whatever good it does."),
            arena="BanditCamp", map="bamboo_forest", v=1),
          B("stage", "Salt on the Table",
            "Qingshi has salt again. Madam Fang's noodles taste of something, and Gou sits in the yamen cell writing names.",
            (FANG, "Salt! Noodles that taste like noodles! Free bowls for the heroes. Two each. I'm feeling reckless."),
            (FANG, "Constable Du has the scarred one writing in the yamen. Page after page. Villages I've never heard of."),
            "@M:Temple", ">Sit in the quiet of the town temple",
            (N, "In the clean temple, you breathe. A page of names drifts through your mind. Every name is somebody's mother."),
            (N, "Your qi steadies around the thought, and deepens. Not anger. Something slower, that will last longer."),
            "@T",
            (DU, "Forty-one names. Forty-one families held by the Blood Moon. The magistrate fainted. Then he got up and sent letters."),
            (DU, "I don't know where they're kept. But now I know they exist. That's how every case starts."),
            giver=FANG, v=0),
      ]),
    # ------------------------------------------------------------------ chapter 7
    C("The Outer Sect Examination", "sect",
      "Once a year every outer disciple is tested: the precepts before Elder Gu, the puppets before Wei Tong, a pill "
      "before Elder Hua and a sparring bout before the whole plaza. Zhao Kang intends to win. So do you.",
      cast=[GU, WEI, HUA, ZHAO, MO, LU, HAN, BAI], foes=["training_puppet", "sparring_disciple"],
      items=["spirit_herb", "jade_slip", "spirit_stone"], props=["stone_stele", "jade_slip", "treasure_chest"],
      things={"stone_stele": "the precept stele", "jade_slip": "the examination slip"},
      beats=[
          B("orders", "Notices on Every Pillar",
            "The examination notices have gone up. Lu Ping has already opened a betting book, and the odds on you are insulting.",
            (LU, "Examination in five days! Precepts, puppets, pills and a bout. I've opened a book. You're at six to one."),
            (P, "Six to one? Who's the favourite?"),
            (LU, "Zhao Kang, obviously. Two to one. He's been training at night. Very dramatically. With his shirt off."),
            "@R:FormationArray",
            (N, "Examination banners hang around the plaza. A list of rules is pinned to every pillar. Rule one: no bribing the puppets."),
            "@T",
            (ZHAO, "Come to look at the banners? Look well. You'll see my name on the top one soon enough."),
            (ZHAO, "Don't embarrass yourself, village brat. It reflects badly on the whole outer court. On me, specifically."),
            giver=LU, v=0),
          B("probe", "The Ninth Precept",
            "Elder Gu will test the Nine Precepts himself. He has never been known to pass anyone who stumbled on the ninth.",
            (GU, "The written examination is mine. Nine precepts, recited and explained. Most disciples stumble on the ninth."),
            (GU, "Guard the seal, even unto death. Tell me, disciple. What seal?"),
            (P, "I don't know, Elder. Nobody will tell me."),
            (GU, "Good. An honest ignorance. Go and read the stele again. Then come back and tell me what it means to you."),
            "@I:SectGate", ">Study the ninth precept on the stele",
            (N, "Guard the seal, even unto death. The words are worn smooth by generations of fingers. Yours join them."),
            "@T",
            (P, "I think it means some things are worth more than the one guarding them."),
            (GU, "...Yes. That is what it means. It is also what it costs. Pass. Go. Go, disciple."),
            (N, "For a moment Elder Gu looks very old. Then the Law Hall's cold returns to his face, and he waves you out."),
            prop="stone_stele", v=0),
          B("train", "The Puppet Gauntlet",
            "Wei Tong runs the puppet gauntlet this year, and has tuned the puppets to 'mildly offended'.",
            (WEI, "The gauntlet! Five puppets, one after another. I've tuned them to mildly offended. Last year was enraged. We lost a wall."),
            (WEI, "No elbows. No weeping. No hitting me, even if I deserve it."),
            "@F:TrainingGround", ">Run the puppet gauntlet",
            "@T",
            (WEI, "Clean run! Zhao Kang did it faster, but he knocked one puppet's head into the lotus pond. Points off for littering."),
            (WEI, "You're neck and neck. Elder Hua's pill test is next. That one I can't help you with. I once made a pill that exploded."),
            foe="training_puppet", count=5, v=0),
          B("gather", "A Pill Worth Passing",
            "Elder Hua's test is simple: refine one Qi-Gathering Pill that doesn't explode. You'll need the right herbs first.",
            (HUA, "One Qi-Gathering Pill. Three kinds of herb, one clean fire, and a hand that doesn't shake. Gather your own herbs."),
            (HUA, "Last year three disciples picked moonbell instead of mountain sage. They're fine now. They can almost whistle again."),
            "@G:HerbGarden", ">Pick mountain sage on the terraces",
            "@T",
            (HUA, "Mountain sage. Correct. Now the fire. Breathe. The cauldron can hear panic."),
            (N, "The pill rolls out round and pale green, and smells faintly of rain. Elder Hua sniffs it and nods once."),
            (HUA, "Pass. Zhao Kang's pill was perfect. Also, it had his clan's crest pressed into it. Show-off."),
            item="spirit_herb", noun="mountain sage", v=0),
          B("social", "The Night Before the Bout",
            "The bout is at dawn. Han Xue gives advice, Elder Mo gives none, and Zhao Kang gives you a look you can't read.",
            (HAN, "Zhao Kang favours his left. He was taught by expensive masters, and they all had the same bad habit."),
            (HAN, "Also, get some sleep. You look like a ghost that's worried about exams."),
            "|",
            (MO, "Advice? No. You know how to fight. The question is whether you know how to lose. Everyone should, once."),
            (P, "I don't intend to lose, Elder."),
            (MO, "Nobody intends to. Hmph. Sleep."),
            "|",
            (ZHAO, "I heard what Elder Gu said to you. About the ninth precept. He passed you. He's never passed anyone on the ninth."),
            (ZHAO, "My brother was the last one who came close. Never mind. Tomorrow I'll beat you properly. Sleep well. I mean it."),
            v=0),
          B("duel", "Zhao Kang at Dawn",
            "The final bout of the examination: you and Zhao Kang, on the formation plaza, in front of every outer disciple.",
            (MO, "Bout of the outer examination! Zhao Kang against {player}! Wooden swords, clean strikes, no clan politics!"),
            (ZHAO, "Wooden swords. How quaint. Don't cry when I win."),
            "@F:FormationArray", ">Win the examination bout",
            (MO, "Zhao Kang's attendants insist on 'assisting their young master'. Fine. Beat them too. Begin!"),
            "@T",
            (ZHAO, "Draw. Elder Mo called it a draw. A draw! I had you at the second exchange."),
            (P, "You had me at the fourth. I had you at the fifth."),
            (ZHAO, "Hmph. Fine. A draw. The first time a draw hasn't felt like losing. Don't read anything into that."),
            foe="sparring_disciple", count=3, giver=MO, v=0),
          B("probe", "Results on the Stele",
            "The results are carved at the gate, and your name sits where nobody expected it to sit.",
            "@R:SectGate", (N, "A crowd at the stele. Your name is carved third from the top, level with Zhao Kang's. Lu Ping is weeping into his betting book."),
            "@I:SectGate", ">Read the examination results",
            (N, "First: a quiet girl from Cloud Peak who nobody bet on. Joint second: Zhao Kang, and you."),
            "@T",
            (LU, "Six to one! I had three stones on you and two on Zhao Kang. I've won and lost at the same time. Is this enlightenment?"),
            (LU, "And the Cloud Peak girl! Nobody bet on her. Nobody even knew her name. It's Qiu Ling, by the way. I asked. Late."),
            prop="stone_stele", v=0),
          B("interlude", "Gu Hanshan's Question",
            "Elder Gu summons you to the Law Hall after the results. He wants to know about your pendant, and about Qingshi.",
            (GU, "Third place, and the ninth precept. You interest me, disciple. So does your report on Qingshi. It reached me too."),
            (GU, "The deacon spoke of your pendant before he died. What did he say? Exactly."),
            (P, "That the Patriarch would be pleased with him. Then that he is coming for me."),
            (GU, "Dying men say many things. Keep that jade close, and your mouth closer. The Law Hall will see to the rest."),
            "|",
            (HAN, "He asked about the pendant? Before he asked about the deacon?"),
            (HAN, "It's nothing. It's his job. I'll keep telling myself that until it stops being true."),
            v=0),
          B("festival", "Lanterns for the Passing",
            "Every disciple who passed floats a lantern from the cliff edge. It is tradition, and slightly dangerous.",
            (BAI, "The Lantern of Passing. Write what you want from your cultivation on the paper, then let the wind take it."),
            (BAI, "Mine said 'more shelves'. Sixty years ago. Heaven has a slow delivery service."),
            "@G:FormationArray", ">Collect paper lanterns from the plaza",
            "@I:CliffEdge", ">Release your lantern over the sea of clouds",
            (N, "Your lantern drifts out over the sea of clouds with a hundred others. You wrote: to be strong enough to protect people."),
            (N, "Beside you, Zhao Kang's lantern says: to beat you. Beneath it, in smaller writing: and to make my brother proud."),
            "@T",
            (ZHAO, "Don't read other people's lanterns. It's the worst manners in the sect. What did yours say? No. Don't tell me."),
            item="lantern_oil", noun="paper lanterns", prop="seal", thing="the cliff edge", v=0),
          B("stage", "Late Autumn, Late Stage",
            "Examination over, you have earned a month in the cultivation caves. Elder Mo walks you there himself.",
            (MO, "A month in the caves. Your first. No food, no talk, no Wei Tong. Heaven's gift to you."),
            (MO, "If you open your eyes before the month is out, you'll find me outside, disappointed."),
            "@M:CliffEdge", ">Cultivate in seclusion above the clouds",
            (N, "Days fold into each other. Your qi wears smooth grooves in your meridians, and deepens them, and deepens them again."),
            (N, "On the last morning you open your eyes. Elder Mo is outside, asleep sitting up, a blanket on his knees."),
            "@T",
            (MO, "I was not sleeping. I was guarding. Late stage of Qi Condensation? Adequate."),
            (MO, "The Sect Master stirs, they say. Not yet. Soon. Go and eat something."),
            giver=MO, v=0),
      ]),
    # ------------------------------------------------------------------ chapter 8
    C("Lanterns on the Qing River", "qingshi_town",
      "Qingshi keeps the Ghost Festival for everyone it lost to the new moon. You and Han Xue come down to help, and "
      "find the river restless: whatever Deacon Hong buried under the graves did not all stay buried.",
      cast=[LIU, FANG, PAN, ZHOU, DU, HAN, JIN], foes=["demon_cultivator", "spirit_wolf", "bandit"],
      items=["incense", "lantern_oil", "medicine"], props=["seal", "stone_stele", "bronze_bell"],
      things={"seal": "the river seal", "stone_stele": "the memorial stele"},
      beats=[
          B("journey", "Invitation From the Yamen",
            "Magistrate Zhou writes to the sect: Qingshi holds its Ghost Festival for the lost, and the town would like its heroes there.",
            (HAN, "The magistrate's written. The town's holding the Ghost Festival for everyone the new moon took. They want us there."),
            (HAN, "I said yes. Then I realised I have to be polite for a whole day. Come with me. You're better at polite."),
            "@R:qingshi_town/MainStreet",
            (N, "Paper lanterns hang from every eave in Qingshi. Children fold boats from red paper. The whole town smells of incense and fried dough."),
            "@T",
            (ZHOU, "The heroes of Qingshi! Welcome, welcome. I have prepared a speech. It is only nine pages."),
            (ZHOU, "Constable Du says I should cut it to one. Constable Du has no poetry in his soul."),
            map="sect", v=0),
          B("festival", "Paper Boats and Names",
            "Widow Liu is folding a paper boat for her son, and asks you to write his name on it. She can't bring herself to.",
            (LIU, "Every boat carries a name down the river to the ones we lost. I've folded one for Liu Er."),
            (LIU, "I can't write it. My hand won't. Will you? You found out what happened to him. You should."),
            "@G:MarketSquare", ">Buy lantern oil in the market for the boats",
            "@I:Riverside", ">Launch Liu Er's boat on the river",
            (N, "You write Liu Er in your neatest hand. The boat turns once in the current, as if looking back, then drifts away."),
            "@T",
            (LIU, "He's not dead. I know you think he's not. I only let the boat go because the town expects it."),
            (P, "Then let it carry a message instead. We're coming."),
            (LIU, "...Yes. That's better. That's a much better boat."),
            item="lantern_oil", prop="seal", thing="the water", v=0),
          B("probe", "The River Won't Take Them",
            "The paper boats are drifting back to shore, upstream, against the current. Old Pan has never seen anything like it.",
            (PAN, "Forty years on this water and I've never seen boats come back. Upstream. Against the current."),
            (PAN, "The river's refusing the names. Or something under it is."),
            "@R:Riverside", (N, "Dozens of paper boats bob against the bank, pressed there by a current that runs the wrong way."),
            "@I:Riverside", ">Touch the backward current with your qi",
            (N, "Cold, and a pull downward. A thread of old blood qi runs along the riverbed toward the hill graves."),
            "@T",
            (HAN, "Hong's circle. We broke it. We didn't dig it out. Some of its roots must run under the river."),
            (HAN, "Festival or not, we have to look. Quietly. Nobody wants a panic at a funeral."),
            prop="seal", thing="the backward current", v=1),
          B("hunt", "Things in the Reeds",
            "Something drags itself out of the reeds after dark, drawn by the festival lanterns and the living warmth of the town.",
            "@R:Riverside", (N, "The festival lanterns reflect on black water. Among the reeds, eyes. Many eyes, low to the ground."),
            "@F:Riverside", (HAN, "Wolves! Soaked, starving, and blood-drunk. Keep them away from the boats, the children are still out!"),
            "@G:Riverside", ">Gather the lanterns the wolves scattered",
            "@T",
            (DU, "Wolves, in town, during the festival. I'm going to have to write a very long report."),
            (DU, "Thank you. The children didn't see. Well, they saw. They think it was a play. They want it again tomorrow."),
            foe="spirit_wolf", item="lantern_oil", noun="scattered lanterns", v=0),
          B("delve", "Roots Under the Graves",
            "Beneath the hill graves, the blood-ink circle you broke is dry. But something new has been dug beside it.",
            "@R:Graveyard", (N, "The old rune circle is grey dust. Beside it, fresh earth, and a new trench running downhill toward the river."),
            "@G:Graveyard", ">Collect the fresh blood-ink stones",
            "@I:Graveyard", ">Break the new rune trench",
            (N, "Your palm meets the runes and they fizz like wet fuses. The trench goes dark, and far below you the river sighs."),
            "@F:Graveyard", (N, "Robed figures rise from behind the tombs, masks painted with red moons. They were waiting for someone to come."),
            "@R:MainStreet", (N, "The street is bright with lanterns again. Nobody noticed. Somewhere behind you, the river begins to flow the right way."),
            item="rune_fragment", foe="demon_cultivator", v=0),
          B("probe", "The Mask That Stayed Behind",
            "One of the masked cultivators dropped a mask as he fled. Inside it, someone has written a name, and a date.",
            "@R:Graveyard", (N, "A cracked red mask lies among the graves. Inside, in neat brush strokes: the next new moon. Qingshi. Again."),
            "@I:Graveyard", ">Study the dropped mask",
            (N, "The ink is fresh. Not Hong's hand; this writer is younger, and in a hurry. Beneath the date, a crescent."),
            "@T",
            (HAN, "They're not finished with this town. Hong was one deacon. There are others, and they have calendars."),
            (P, "Then the town needs more than a festival. It needs watchers."),
            (HAN, "It needs the Sect Master to open that door. I'm going to write her another letter. A rude one."),
            prop="stone_stele", thing="the dropped mask", v=0),
          B("social", "Watchers for Qingshi",
            "Qingshi needs its own eyes. The ferryman, the innkeeper and the constable volunteer. So, surprisingly, does Merchant Jin.",
            (DU, "Watchers. Yes. I can put men on the gate and the tower. The river is harder."),
            "|",
            (PAN, "The river? I'm on it day and night anyway. I'll watch. Fare's free for this one."),
            "|",
            (FANG, "Everybody tells me everything eventually. It's the wine. I'll send word up the mountain if anyone new asks about the graves."),
            "|",
            (JIN, "The guild has pigeons. Fast ones. For prices. They could carry other messages. For a fee. A small fee. No fee. Fine."),
            (P, "Thank you, Master Jin."),
            (JIN, "Don't thank me. It makes me nervous. People only thank me before bad news."),
            v=0),
          B("defend", "The Night of Lanterns",
            "On the festival's last night the whole town walks to the river with lanterns. The masked cultivators choose that moment.",
            (ZHOU, "My speech! I'm about to give my speech! Nine pages! Why are there men with swords on the rooftops?"),
            "@I:WatchTower", ">Sound the watchtower bell",
            (N, "The bell rings out over the river. Lantern-bearers scatter to the doorways, just as masked figures drop into the street."),
            "@F:MainStreet",
            "@F:MarketSquare", (HAN, "They're after the crowd! Keep them in the square. Nobody gets dragged anywhere tonight!"),
            "@T",
            (ZHOU, "I gave my speech. All nine pages. Behind a barricade. To seven people and a goat. It was my finest hour."),
            (ZHOU, "Thank you, immortal. The town saw you stand in the square. They'll remember that longer than my speech."),
            foe="demon_cultivator", foe2="demon_cultivator", prop="bronze_bell", thing="the watchtower bell", v=0),
          B("cultivate", "Incense for the Lost",
            "When the lanterns are gone, Widow Liu asks you to burn incense at the temple for everyone still missing.",
            (LIU, "Burn one for Liu Er, and one for every name the scarred bandit wrote down. There's a lot of names."),
            (LIU, "Heaven keeps its accounts. So do I. So should you, I think."),
            "@M:Temple", ">Burn incense for the missing",
            (N, "Forty-one names from Gou's list, and eleven from Qingshi. You burn one stick for each. The temple fills with slow grey smoke."),
            (N, "Your qi settles into the silence like a stone into deep water."),
            "@T",
            (FANG, "You look like you need wine. You're getting tea. Tea is for people who have more work tomorrow."),
            v=0),
          B("interlude", "Back Up the Mountain",
            "The festival is over. Han Xue walks you to the town gate with a letter for the Sect Master and a very long face.",
            (HAN, "My letter to the Sect Master is four pages. Three of them are just the word 'please'."),
            (HAN, "Word from the sect, too. The outer disciples are being sent into the Moonlit Grotto. It opens once a decade."),
            (P, "A secret realm? Now?"),
            (HAN, "Elder Mo says it's exactly now. The sect needs strong disciples, and the grotto makes them. Or eats them. Mostly makes them."),
            "|",
            (DU, "Safe road, immortals. The watchers are set. The town will hold till you're back."),
            (DU, "And if it doesn't, I'll write it down. Then I'll hold it anyway."),
            v=0),
      ]),
    # ------------------------------------------------------------------ chapter 9
    C("The Moonlit Grotto", "bamboo_forest",
      "Once a decade a secret realm opens beneath the bamboo, and the sect sends its best outer disciples in. Han Xue "
      "leads, Wei Tong carries the food, Zhao Kang carries a grudge, and the grotto carries everyone somewhere else.",
      cast=[HAN, WEI, ZHAO, MO, LAN], foes=["stone_golem", "spirit_wolf", "rogue_cultivator"],
      items=["spirit_herb", "jade_slip", "spirit_stone", "rune_fragment"], props=["seal", "stone_stele", "treasure_chest"],
      things={"seal": "the grotto seal", "stone_stele": "the grotto tablet", "treasure_chest": "the moss-grown chest"},
      beats=[
          B("orders", "Once a Decade",
            "Elder Mo gathers the chosen disciples at the teleport array: the Moonlit Grotto opens tonight, beneath the old wolf den.",
            (MO, "The Moonlit Grotto opens once a decade, under the bamboo. Disciples go in, disciples come out stronger. Usually."),
            (MO, "Han Xue leads. Wei Tong carries the food. Zhao Kang carries his mouth. You carry that pendant, and bring it back."),
            (P, "Why the pendant, Elder?"),
            (MO, "Because it glows when it's near old things, and the grotto is very old. Go."),
            "@R:bamboo_forest/WolfDen",
            (N, "Where the blood seal once wept, the rock has split, and silver light pours out of the crack like water from a jar."),
            "@T",
            (HAN, "In we go. Stay together. The grotto moves its rooms around. Last decade a disciple came out two weeks late and very confused."),
            map="sect", v=0),
          B("probe", "The Tablet of Rules",
            "Just inside the grotto a tablet lists its rules. Most of them are warnings. One of them is a joke. You hope.",
            "@R:Clearing", (N, "Inside, the forest is the forest, but silvered, as if the moon had soaked into every leaf. The sky is a stone ceiling."),
            "@I:AncientShrine", ">Read the grotto tablet",
            (N, "Take nothing that is not offered. Harm nothing that does not harm you. Do not eat the silver peaches. We mean it."),
            "@T",
            (WEI, "Silver peaches? There are silver peaches? Where? Just to know where not to go."),
            (ZHAO, "He's going to eat the peaches."),
            (HAN, "He's going to eat the peaches."),
            prop="stone_stele", v=0),
          B("gather", "Moonlit Herbs",
            "The grotto's herbs grow in minutes and fade in hours. Han Xue wants a basket before the light changes.",
            (HAN, "Moon-sage. It only grows here. Elder Hua would give a year of her life for a basket of it."),
            (HAN, "Pick fast. They wilt when the grotto shifts, and it shifts often."),
            "@G:HerbGrove", ">Pick moon-sage in the silvered grove",
            "@T",
            (HAN, "A full basket. Good. Did Wei Tong eat a peach?"),
            (P, "Half a peach."),
            (HAN, "Then we have about an hour before something very large comes to complain."),
            item="spirit_herb", noun="moon-sage", v=0),
          B("battle", "The Peach Keepers",
            "Something very large comes to complain about the peach.",
            (WEI, "It was half a peach! Half! It was mostly pit! Who's coming? Why is the ground shaking?"),
            "@F:HerbGrove", (ZHAO, "Stone golems. Wonderful. Wei Tong, next time, starve."),
            "@F2:Clearing",
            "@R:Stream", (N, "The last golem crumbles. From its rubble rolls a single silver peach, which Wei Tong looks at, then very bravely does not touch."),
            foe="stone_golem", v=1),
          B("probe", "Rivals Among the Silver",
            "You are not the only sect in the grotto. Rogue cultivators have slipped in through the crack, and they are not following the rules.",
            "@R:BanditCamp",
            (N, "Tents in the silver forest. Rogue cultivators, a dozen of them, digging up everything that glows."),
            "@I:BanditCamp", ">Search the rogues' spoils",
            (N, "Sacks of moon-sage torn up by the roots. Carved tablets smashed for their jade. A map, with the grotto's heart marked in red."),
            "@T",
            (ZHAO, "Tomb raiders. Grave robbers with swords. They'll strip this place bare."),
            (HAN, "They're heading for the heart. So are we. Now it's a race."),
            prop="treasure_chest", thing="the rogues' sacks", v=0),
          B("battle", "Rules of the Grotto",
            "The rogue cultivators have found the grotto's guardians too, and are losing badly. They'd like to take you down with them.",
            (HAN, "They woke the guardians and ran toward us. That's a tactic. A cowardly, effective tactic."),
            "@F:OldBridge",
            "@F2:ForestPath", (ZHAO, "Rogues on the left, golems on the right. I'll take the rogues. They're uglier."),
            "@R:Clearing",
            (N, "When the dust settles, the surviving rogues are gone, and the path to the grotto's heart stands open beneath a silver arch."),
            foe="rogue_cultivator", foe2="stone_golem", v=0),
          B("social", "Around a Silver Fire",
            "The grotto's night is short and bright. Around the fire, your companions say things they wouldn't say in daylight.",
            (WEI, "When I was small, I wanted to be a cook. My father said cultivators eat better. He was wrong. Cultivators eat faster."),
            (WEI, "I'm still going to open a noodle shop one day. The Dumpling. Named after my sword. Or the other way round."),
            "|",
            (ZHAO, "My brother came to this grotto ten years ago. He came out first. My father had it carved on a stone in our hall."),
            (ZHAO, "I'm going to come out first too. Not for my father. For the stone. It looks lonely."),
            "|",
            (HAN, "I don't have a story. I have a sword and a senior sister's responsibilities. Go to sleep, all of you."),
            (P, "Senior Sister, you're smiling."),
            (HAN, "It's the fire. Silver fire. Very misleading. Sleep."),
            v=0),
          B("delve", "The Silver Arch",
            "Beyond the arch the grotto grows old: carved pillars, faded murals, and a green that is not quite moonlight.",
            "@R:RuinsGate", (N, "The arch is carved with flowers so worn you can't tell what they were. Your pendant warms. Just slightly."),
            "@G:RuinsGate", ">Gather the fallen tiles of the arch",
            "@I:RuinsGate", ">Set the tiles back into the arch",
            (N, "The last tile clicks home. For a heartbeat every carved flower flushes green, then fades back to silver."),
            "@F:RuinsInner", (N, "The floor shivers, and the grotto's stone keepers rise to see who has touched their arch."),
            "@R:RuinsInner", (N, "Beyond the keepers lies a quiet courtyard, silver on green, and a sound like distant water."),
            item="rune_fragment", foe="stone_golem", v=0),
          B("probe", "The Flower Nobody Remembers",
            "A mural in the grotto's heart shows a sect in green robes. The paint has been scraped from every face.",
            "@R:AncientShrine",
            (N, "A mural covers the wall: cultivators in green robes, holding flowers. Every face has been scraped away, carefully."),
            "@I:AncientShrine", ">Study the scraped mural",
            (N, "Only one flower remains untouched in the corner: a lotus, carved exactly like the jade at your belt. Your pendant is warm as a hand."),
            "@T",
            (HAN, "Someone came in here with a knife and took their time. Why scrape faces off a painting?"),
            (P, "So nobody remembers them."),
            (HAN, "That's what I'm afraid of. Don't touch it. We tell Elder Mo. Keep your pendant under your robe."),
            prop="stone_stele", thing="the scraped mural", v=0),
          B("stage", "Moonlight in the Marrow",
            "At the edge of the grotto's heart a spring of silver qi bubbles up. Han Xue stands guard while each of you takes a turn.",
            (HAN, "One at a time. The spring is strong. Too much and you'll be seeing silver for a week. Wei Tong goes last."),
            (WEI, "Why me last?"),
            (HAN, "Because you ate the peach."),
            "@M:SpiritSpring", ">Bathe your meridians in silver qi",
            (N, "Silver qi floods your meridians, cool as moonlight on water. Everything you have gathered this year settles, and brightens."),
            (N, "Behind your eyes the green lotus from the mural opens, once, and closes, like a door you are not yet allowed through."),
            "@T",
            (HAN, "Peak of Qi Condensation. I can see it in the way you're standing. Don't let it go to your head."),
            (HAN, "The heart is ahead. Something is guarding it. It has been guarding it for a very long time."),
            giver=HAN, v=0),
      ]),
    # ------------------------------------------------------------------ chapter 10
    C("Heart of the Grotto", "bamboo_forest",
      "At the heart of the Moonlit Grotto waits its warden, a stone giant that has asked the same question for three "
      "hundred years. The rogues want what it guards, the grotto wants to close, and Wei Tong wants lunch.",
      cast=[HAN, WEI, ZHAO, LAN, MO], foes=["stone_golem", "rogue_cultivator", "spirit_wolf"],
      items=["jade_slip", "spirit_stone", "spirit_herb"], props=["seal", "treasure_chest", "stone_stele"],
      boss=("ancient_guardian", "The Grotto Warden", "RuinsInner"),
      things={"seal": "the grotto's heart-seal", "treasure_chest": "the warden's chest"},
      beats=[
          B("hunt", "The Rogues Come Back",
            "The rogue cultivators have regrouped with friends, and they have brought picks for the grotto's heart.",
            "@R:RuinsGate", (N, "Torches at the silver arch. The rogues are back, twice as many, with picks and chains and one very large hammer."),
            "@F:RuinsGate", (ZHAO, "They're going to break the arch! Barbarians! That's at least a thousand years of carving!"),
            "@G:RuinsGate", ">Recover the jade the rogues pried loose",
            "@T",
            (ZHAO, "They ran. Again. They're very good at running. I should learn it. Tactically."),
            (ZHAO, "The one with the hammer said something about the warden's treasure being worth a city. What treasure?"),
            foe="rogue_cultivator", item="jade_slip", noun="pried-loose jade", ally=ZHAO, v=0),
          B("probe", "A Question in Stone",
            "Carved over the heart's door is a single question, repeated in seven scripts. Only one of them you can read.",
            "@R:RuinsInner", (N, "A door of green stone, and above it one question carved in seven scripts. You can read only the last."),
            "@I:RuinsInner", ">Read the question over the door",
            (N, "Who carries the flower? And beneath, smaller: if no one, go home. If someone, wake me gently."),
            "@T",
            (HAN, "Who carries the flower. It means you, doesn't it. Your pendant hasn't stopped glowing since the arch."),
            (P, "I don't know what it means. But it's the same flower."),
            (HAN, "Then we don't wake it. Not yet. Not until we know what gently means to a stone."),
            prop="stone_stele", thing="the carved question", v=0),
          B("council", "Counsel From Outside",
            "A paper crane flies in through the grotto's crack, carrying a note from the hermit, who seems to know where you are.",
            "@R:Clearing",
            (N, "A paper crane circles your head and lands on your hand. It unfolds into a note in a spidery, ancient hand."),
            (N, "The warden asks a question. Answer it honestly, and it will test you. Lie, and it will bury you. Bring tea. The Hermit."),
            "|",
            (WEI, "Bring tea? To a fight? The hermit is very strange. I respect it."),
            (WEI, "I have tea. I have everything. I packed for a war and a picnic, just in case."),
            "|",
            (ZHAO, "How does a hermit know where we are? How does a hermit send cranes into a secret realm?"),
            (ZHAO, "The older I get, the less I understand old people."),
            v=0),
          B("gather", "Stones for the Door",
            "The door to the heart has seven empty sockets. The seven stones are scattered where the grotto last shifted.",
            (HAN, "Seven sockets. Seven stones, and the grotto moved them around to be difficult."),
            "@G:Clearing", ">Find the seven door-stones in the clearing",
            "@F:Clearing", (N, "Grey wolves with silver-tipped fur lope out of the long grass, guarding the stones like shepherds."),
            "@T",
            (HAN, "Seven stones. The wolves only wanted to see if we were polite. We were. Mostly."),
            item="spirit_stone", noun="door-stones", foe="spirit_wolf", v=1),
          B("probe", "Tea for a Giant",
            "You set the stones and pour a cup of Wei Tong's tea at the door, feeling ridiculous. The door opens anyway.",
            "@R:RuinsInner", (N, "You set the seventh stone and pour a cup of tea at the threshold. It feels ridiculous. The door opens."),
            "@I:RuinsInner", ">Pour tea at the warden's door",
            (N, "Inside, a giant of green stone kneels with its head bowed over a sword. Moss has grown over its shoulders like a cloak."),
            "@T",
            (WEI, "It's asleep. It's very big and very asleep. Can we leave it like that? I vote we leave it like that."),
            (HAN, "Whatever it guards, the rogues will be back for it. We can't leave it like that."),
            prop="seal", thing="the warden's threshold", v=0),
          B("boss", "The Grotto Warden",
            "The warden wakes, and asks its question with its fists.",
            "@R:RuinsInner", (N, "The warden lifts its head. Moss sloughs away. A voice like millstones: who carries the flower?"),
            "@X",
            (P, "I do. I don't know what it means. But I carry it."),
            (N, "Honest. Good. Show me the flower has roots."),
            "@I:RuinsInner", ">Accept what the warden offers",
            (N, "The warden kneels again, and opens its stone hand. In it lies a slip of green jade, warm, and a single seed of a lotus."),
            (N, "Not yet, it grinds. The rest when you are ready. It closes its eyes, and is moss again."),
            "@T",
            (HAN, "It gave you a seed and a slip, and went back to sleep. That's the strangest treasure I've ever heard of."),
            (P, "The slip is blank. The seed is just a seed."),
            (HAN, "Then they're for later. Put them with your pendant. Everything strange seems to belong together."),
            prop="treasure_chest", thing="the warden's hand", v=0),
          B("battle", "The Grotto Begins to Close",
            "With the heart given up, the grotto starts to fold shut. The rogues make one last grab on the way out.",
            (ZHAO, "The walls are moving! The grotto's closing! Everyone to the crack, now!"),
            "@F:Clearing", (N, "The rogues burst out of the silver trees, desperate, hammers raised, grabbing at anything that glows."),
            "@F2:ForestPath",
            "@R:WolfDen", (N, "You tumble out of the crack into ordinary bamboo, ordinary daylight. Behind you the rock closes like a mouth."),
            foe="rogue_cultivator", foe2="rogue_cultivator", ally=ZHAO, v=0),
          B("probe", "Who Came Out First",
            "Out in the bamboo, the other teams are waiting, counting heads. Zhao Kang wants to know who came out first.",
            "@R:ForestPath", (N, "The other teams wait on the forest path, counting heads. The monitor elder is marking a list with great ceremony."),
            "@T",
            (ZHAO, "Who came out first? I need to know. For the stone. Tell me it was me."),
            (P, "It was you, Zhao Kang. By a whole step. I saw it."),
            (ZHAO, "...You're lying. You were in front of me. You stepped back. Why would you do that?"),
            (P, "Your brother's stone looked lonely."),
            (ZHAO, "...Don't. Don't be kind to me. It's unbearable. Thank you."),
            v=0),
          B("social", "The Hermit's Tea, Returned",
            "On the way back you stop at the hermit's hut to return his cup. He looks at the seed in your hand for a long time.",
            (LAN, "The warden gave you a seed. Three hundred years it held that seed. It never gave it to anyone."),
            (P, "Do you know what it is?"),
            (LAN, "I know what it will be. Not what it is. Plant it when you have a home that deserves it. Not before."),
            (LAN, "And go home, child. Your Sect Master is waking. Even I can feel it, all the way out here."),
            "|",
            (WEI, "I left the rest of the tea with the hermit. He cried. Just a bit. I think it was the tea. It's very strong."),
            v=0),
          B("stage", "The Door Opens",
            "Home at last, you find the gold seal torn from the main hall doors. The Sect Master has emerged, and she has read every letter.",
            (MO, "She's out. This morning. She read your report and Han Xue's four pages of please."),
            (MO, "Before you see her, sit. The grotto shook your qi loose. Settle it, or you'll wobble in front of the Sect Master."),
            "@M:StoneBridge", ">Settle the grotto's qi on the stone bridge",
            (N, "The silver qi of the grotto settles into your meridians like snow into a valley. The peak of Qi Condensation holds, clear and full."),
            "@T",
            (MO, "Better. She'll send for you tomorrow. She has questions about Qingshi, and the deacon, and friends in high halls."),
            (MO, "Tonight, eat. Sleep. Tomorrow you'll need both."),
            giver=MO, map="sect", v=0),
      ]),
]
