"""Volume V · Soul Transformation — new chapters 42-50 (after "The Heart
Demon").

The sect marches on the blood moon, as promised, and the seal holds: Elder
Mo's sacrifice and the repaired formation are too strong. So the Patriarch
does the one thing no one expected. He folds his fortress into the void and
waits. The march becomes a long war against his Ladder. Meanwhile the sect
grieves: heart demons, a teacher's empty place, a Law Hall without a judge,
and the letters an old man left behind. Gu Hanshan is a prisoner in chains who
has offered to help. Mo is gone.
"""

from .dsl import N, P
from .npcs import *  # noqa: F401,F403
from .saga_gen import B, C

CHAPTERS = [
    # ------------------------------------------------------------------ chapter 42
    C("The Blood Moon That Did Not Break", "blood_abyss",
      "Three days after the formation was mended, the blood moon rises and the Azure Cloud's vanguard stands at the rim "
      "of the Abyss. The seal holds. The Patriarch cannot break it. So, with the whole sect watching, he folds his "
      "black fortress into the void and vanishes, to wait for a better night.",
      cast=[YUN, HAN, WEI, ZHAO, YE, TIE, GU, SHI], foes=["blood_guard", "demon_cultivator", "void_wraith"],
      items=["demon_core", "void_shard", "medicine"], props=["demon_obelisk", "seal", "treasure_chest"],
      things={"seal": "the edge of the fold"},
      beats=[
          B("orders", "Three Days Later",
            "The blood moon rises in three days, Ye Wuming said. On the third day the vanguard of the Azure Cloud stands at the Abyss.",
            (YUN, "The vanguard goes first. You, Han Xue, Zhao Kang, Wei Tong. Ye Wuming's people. Iron-Fang's men. Gu, in chains, to show the way."),
            (YUN, "I'll hold the formation from the mountain. If the seal holds tonight, we finish this. If not, we finish it anyway."),
            "@R:blood_abyss/CanyonEntrance", (N, "The canyon rim is crowded with blue robes and black ones. Above, the moon is rising, and it is the colour of a wound."),
            "@T:CanyonEntrance",
            (YE, "The moon's rising. He'll try to break the seal tonight. With or without your formation. We'll see which."),
            map="sect"),
          B("social", "The Traitor in Chains",
            "Gu Hanshan walks in chains beside the vanguard. Some of the disciples spit as he passes. Zhao Kang doesn't.",
            (GU, "They spit. They're right to. I would have, once. I wrote the precept about treason myself."),
            (GU, "The black gate is past the obelisk ring. I'll show you. After tonight you'll have no use for me."),
            "|",
            (ZHAO, "I promised myself I'd ask you one thing. Why did you send my brother to the bamboo forest?"),
            (GU, "...Because he was asking about the Law Hall's grain. He was clever. I was afraid. I'm sorry. It's worth nothing. I'm sorry."),
            (ZHAO, "No. It's worth something. Not much. Something."),
            ),
          B("battle", "The Bone Field Holds",
            "The Blood Moon's last army waits on the bone field. It does not expect the Iron Scale's banners behind yours.",
            (TIE, "Forty of my men, and the Iron Scale's banners on the left! Didn't know they were coming! Nobody tells a bandit anything!"),
            "@F:BoneField",
            "@F2:DemonCamp", (WEI, "For Elder Mo! Hey, Elder, are you watching? I'm doing the stance right! Mostly!"),
            "@R:BloodPools", (N, "The line breaks. Across the steaming pools the black gate stands open, and beyond it, something vast is waking."),
            foe="blood_guard", foe2="demon_cultivator"),
          B("probe", "The Moon Rises",
            "At the obelisk ring, you feel the blood moon reach its height, and the whole Abyss pulls upward at the seal.",
            "@R:ObeliskRing", (N, "The blood moon stands overhead. The earth heaves. Every obelisk stump lights red at once, pulling upward, pulling at the seal."),
            "@I:ObeliskRing", ">Press your palm to the shuddering earth",
            (N, "Through your soul you feel it: the Azure Eye on the mountain, blue and whole, and beneath you the seal, holding. Holding. Holding."),
            "@T:CanyonEntrance",
            (HAN, "It's holding. The seal's holding. Elder Mo's formation is holding. He can't get out."),
            prop="demon_obelisk", thing="the obelisk stump"),
          B("probe", "The Fortress Folds",
            "Then the Patriarch does something nobody expected. The black gate, the fortress and the altar fold into nothing.",
            "@R:BloodPools", (N, "Beyond the pools the black fortress creases like paper. It folds, and folds again, smaller and smaller, into a seam of purple dark."),
            "@I:BloodPools", ">Reach into the fold with your soul",
            (N, "Nothing. Not darkness, not stone. Nothing. The void, between one place and another. The black gate is in there somewhere, very far away."),
            "@T:CanyonEntrance",
            (YE, "He's gone where no army can follow. Folded his home into the void and taken it with him. Behind that fold are my... Iron-Fang's family."),
            (YE, "He won't come out tonight. He'll come out when he's ready. He's always been very good at waiting."),
            prop="seal", thing="the edge of the fold"),
          B("battle", "What the Fold Leaves Behind",
            "The fold leaves a wound in the air, and things come out of it: shapes of purple dark with hands.",
            (ZHAO, "Things coming out of the nothing! With hands! Why does everything bad have hands?"),
            "@F:BloodPools",
            "@F2:BoneField",
            "@T:CanyonEntrance",
            (HAN, "Void wraiths. The fold is leaking. The Abyss is going to be dangerous in a completely new way. Wonderful."),
            foe="void_wraith", foe2="void_wraith"),
          B("social", "Iron-Fang at the Fold",
            "Iron-Fang stands at the edge of the fold with his hand pressed flat against nothing.",
            (TIE, "They were behind that gate. My sister. My men's children. I came to bring them home. Now there isn't a gate."),
            (TIE, "Iron-Fang pays his debts. I don't know how to pay this one. There's nothing to hit."),
            (P, "There will be, Tie Hu. He'll open it again. He has to. And we'll be there."),
            (TIE, "...You're a fool, sect brat. I keep saying that. I keep believing you."),
            ),
          B("social", "The Sect Master's Choice",
            "The Sect Master arrives at the rim through the array. She listens, looks at the fold, and makes the hardest choice of her life.",
            (YUN, "We came to finish it. He's folded himself into nothing. I can't march an army into nothing."),
            (YUN, "So we go home. We get strong enough to walk into nothing. We break whatever he's waiting for. And we come back."),
            "|",
            (GU, "He's waiting for you, Lotus heir. For your tribulation. That's the only door heaven will open for him. You're his key and his ladder both."),
            (GU, "I'm sorry. That's all I seem to say now. I'm sorry."),
            ),
          B("gather", "Collecting the Wounded",
            "The retreat is orderly. Xiao Shi, who knows every path, leads the wounded to the array. You carry what he can't.",
            (SHI, "I know every path down here. I'll lead the wounded. You carry the medicine. My sister made eight hundred bundles. Eight hundred."),
            "@G:BoneField", ">Gather Xiao Man's medicine bundles for the wounded",
            "@T:CanyonEntrance",
            (SHI, "Everyone out. Nobody left behind. That's the rule I made in the cages. I'm keeping it."),
            item="medicine", noun="medicine bundles"),
          B("hunt", "Void Wraiths, Cleaning the Rim",
            "The wound in the air keeps leaking void wraiths even after the retreat begins. The rim needs clearing before it's safe to leave.",
            foe="void_wraith", v=0),
          B("gather", "Demon Cores From the Bone Field",
            "The fallen demon cultivators leave behind cores worth harvesting before the Abyss reclaims the field.",
            item="demon_core", v=0),
          B("probe", "The Fold, Measured",
            "Before leaving, you study the fold's edge with your soul, trying to learn its shape for whenever it opens again.",
            (HAN, "Memorize it. Every crease. If it opens again, even for a second, we need to know exactly where."),
            v=0),
          B("social", "Wei Tong's Silence",
            "Wei Tong, usually the loudest voice in any retreat, says nothing at all on the walk back to the array.",
            (ZHAO, "He hasn't said a word. Wei Tong. Not one word. That scares me more than the wraiths did."),
            v=0),
          B("hunt", "Blood Guard, the Last Stragglers",
            "A handful of Blood Moon stragglers, cut off by the fold, must be dealt with before the retreat is complete.",
            foe="blood_guard", v=0),
          B("gather", "Void Shards From the Wound",
            "The wound in the air sheds strange void shards, unlike anything the sect's collectors have catalogued before.",
            item="void_shard", v=0),
          B("social", "Iron-Fang's Men, Steadied",
            "Iron-Fang's men, shaken by the fold swallowing their families' hope, need steadying before the long march home.",
            (TIE, "Steady, all of you. We came for a door. We'll come back when there's a door again. Until then, we march."),
            v=0),
          B("probe", "Gu's Chains, Loosened",
            "The Sect Master orders Gu Hanshan's chains loosened, not removed, in recognition of his help at the fold.",
            (YUN, "Loosened. Not removed. You are still a traitor, Gu Hanshan. You are also, tonight, useful. Both things are true."),
            v=0),
          B("social", "Ye Wuming's Silence",
            "Ye Wuming watches the fold long after everyone else has turned to leave, saying nothing until you join him.",
            (YE, "I've hunted this man for longer than you've been alive. Tonight is the closest I've come. It doesn't feel like close."),
            v=0),
          B("hunt", "The Wound's Last Guardians",
            "A final cluster of things-with-hands guards the wound itself, reluctant to let the vanguard leave unbothered.",
            foe="void_wraith", v=0),
          B("interlude", "The Long War",
            "On the rim, as the blood moon sets, Ye Wuming tells you the war has just changed shape.",
            (YE, "It was going to be one night. Now it's a long war. Against a patriarch who isn't here, and seven servants who are."),
            (YE, "The Ladder. The rungs. Break them and he has nothing to climb when he comes out. I'll hunt with you."),
            (P, "Still no name, Ye Wuming?"),
            (YE, "Not yet. It's close. I can feel it, like a word on the tip of the tongue. I'll tell you when I have it."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 43
    C("Grief Has Teeth", "sect",
      "The sect comes home from a war that didn't happen to a teacher who isn't there. Disciples wake with red at the edge "
      "of their vision again, not from pills this time, but from grief. Heart demons are gathering on the mountain, and "
      "the one feeding on Wei Tong is the hungriest.",
      cast=[HAN, WEI, HUA, MAN, SHI, YUN, BAI, LU, YAN], foes=["heart_demon", "void_wraith", "training_puppet"],
      items=["incense", "medicine", "spirit_herb"], props=["seal", "bronze_bell", "stone_stele"],
      boss=("heart_demon", "Wei Tong's Despair", "TrainingGround"),
      foe_names={"void_wraith": "grief-shades"},
      beats=[
          B("orders", "Coming Home to an Empty Step",
            "The vanguard comes home. At the hall steps, where Elder Mo always stood, there is nobody to tell you you're late.",
            "@R:HallSteps", (N, "The hall steps are swept and empty. Somebody has left a cup of tea where Elder Mo used to stand. It has gone cold."),
            "@T:SectGate",
            (LU, "I keep expecting him to come out and shout at me. I've started standing up straight in case. It doesn't help."),
            (LU, "Wei Tong hasn't left the training ground since you got back. He's just sitting with the puppets. Not training. Sitting."),
            ),
          B("social", "Wei Tong With the Puppets",
            "Wei Tong is sitting among the training puppets, the way Elder Mo sat among his runes.",
            (WEI, "He used to bet me buns on how many puppets the new ones could break. I lost every bet. On purpose. He knew."),
            (WEI, "I made his birthday dumplings. We ate them. You said we'd eat them for him. We did. It didn't help."),
            (P, "It wasn't supposed to help, Senior Brother. It was supposed to hurt a little less."),
            (WEI, "...It hurts exactly the same. But I'm eating again. That's something, right? Tell me that's something."),
            ),
          B("probe", "Red at the Edges Again",
            "Elder Hua has three disciples in the infirmary with red at the edges of their eyes. No pill caused it this time.",
            (HUA, "Red at the edges. No Frenzy Pill this time. They're grieving, and something is feeding on the grief."),
            "@R:Pavilion", (N, "In the pavilion a disciple sits hugging his knees, whispering to someone who isn't there, and the someone whispers back."),
            "@I:Pavilion", ">Look at the grieving disciple with your soul",
            (N, "Soul sight shows a shadow on his shoulder, small and grey, feeding. Heart demons. Dozens of them, all over the mountain."),
            "@T:HerbGarden",
            (HUA, "Heart demons. The void fold at the Abyss loosened something. Grief is an open door, and things are walking through it."),
            prop="seal", thing="the grieving disciple"),
          B("battle", "Shades on the Mountain",
            "At dusk the grief-shades gather, more than anyone can count, drawn to the sect like moths to a lamp.",
            (HAN, "They're coming out at dusk. Everywhere there's someone grieving. Which is everywhere."),
            "@F:FormationArray",
            "@F2:OuterPines",
            "@T:SectGate",
            (HAN, "They scatter when you strike them. They come back when people remember. We can't strike grief."),
            foe="void_wraith", foe2="void_wraith"),
          B("cultivate", "What You Did at the Mirror",
            "You faced your own heart demon at the Heart Mirror. Elder Hua asks you to teach the grieving how.",
            (HUA, "You faced yours at the mirror. What did you do? Not the fighting. Before."),
            (P, "I said it out loud. What I was afraid of. It's smaller when it's said."),
            (HUA, "Then teach them to say it. I'll bring them to the stone bridge. You sit with them."),
            "@M:StoneBridge", ">Sit with the grieving on the stone bridge",
            (N, "One by one they say it. I miss him. I'm afraid I'll die too. I should have said thank you. The shades on their shoulders shrink."),
            "@T:StoneBridge",
            (MAN, "It's working. The shades are getting smaller. My brother said his, too. He said he misses the cages. He hates that he does."),
            ),
          B("probe", "The Biggest Shade",
            "One shade isn't shrinking. It has grown so large it walks on its own, and it is walking toward Wei Tong.",
            (YAN, "There's a shade at the training ground as big as a man. It looks like... it looks like you. But it's following Wei Tong."),
            "@R:WeaponRack", (N, "At the weapon rack, a shadow shaped like you stands behind Wei Tong, bent close, whispering in his ear."),
            "@T:SectGate",
            (WEI, "It says it was your fault. That you went to the mirror and left Elder Mo alone. It sounds like you. It uses your voice."),
            (WEI, "I know it's not true. I know. But it's so loud. Make it stop. Please make it stop."),
            ),
          B("boss", "Wei Tong's Despair",
            "The heart demon feeding on Wei Tong has taken the shape of the person he'd least like to blame. You.",
            "@R:TrainingGround", (N, "The shade steps away from Wei Tong and turns. It has your face, your stance, your sword. Its eyes are Wei Tong's grief."),
            "@X",
            (WEI, "Don't hold back because it looks like you! It's not you! You're... you're my friend! Hit it!"),
            "@T:TrainingGround",
            (WEI, "It's gone. It's quiet. For the first time since the formation lit, it's quiet in my head."),
            (WEI, "It wasn't your fault. I knew that. I just needed someone to hit the part of me that didn't. Thank you. I'm hungry."),
            ),
          B("festival", "Tea for the Empty Step",
            "Wei Tong wants to do something for Elder Mo. Something he'd grumble at. He decides on tea, at the hall steps, every morning.",
            (WEI, "Every morning. A cup of tea on the hall steps, where he stood. He'd hate it. He'd say tea is for people who've finished training."),
            (WEI, "So we'll train first. Then tea. Help me carry the pot."),
            "@G:HerbGarden", ">Pick tea leaves from the terraces",
            "@I:HallSteps", ">Pour the first cup at the hall steps",
            (N, "Steam rises from the cup on the empty step. Nobody drinks it. Everybody who passes bows to it. Then goes to train."),
            "@T:WeaponRack",
            (WEI, "He'd hate it so much. It's perfect."),
            item="spirit_herb", noun="tea leaves", prop="seal", thing="the empty step"),
          B("social", "The Sect Master's Grief",
            "The Sect Master has not wept for Elder Mo. Elder Bai asks you to go and see her. He says she won't see him.",
            (BAI, "She won't see me. She won't see Hua. She's in the main hall with the doors shut, and she's not in seclusion. She's hiding."),
            "|",
            (YUN, "Forty years. He argued with every decision I made. I'd give the sect to hear him argue with one more."),
            (YUN, "I can't weep. If I weep, I'll stop, and I can't stop. There's too much to do."),
            (P, "He'd say you're being stubborn, Sect Master."),
            (YUN, "...He would. He'd say it exactly like that. Close the door on your way out. I'm going to be stubborn in private for an hour."),
            ),
          B("hunt", "Grief-Shades, the Training Ground",
            "A few grief-shades linger at the training ground even after Wei Tong's shade is gone, feeding on smaller sorrows.",
            foe="void_wraith", v=0),
          B("gather", "Incense for Every Hall",
            "Elder Hua asks for incense to be lit in every hall on the mountain, a small steady thing while the shades thin.",
            item="incense", v=0),
          B("social", "Lu Ping's Small Grief",
            "Lu Ping admits, quietly, that his grief is smaller than everyone else's, and that this makes him feel guilty.",
            (LU, "I barely knew him. Not like you, or Wei Tong. But I still feel it. Is it wrong to grieve someone you barely knew?"),
            (HUA, "No. A mountain misses its own weather. You don't have to have loved him best to miss him."),
            v=0),
          B("train", "Wei Tong Teaches the Stance",
            "Wei Tong, still raw, starts teaching Elder Mo's favorite stance to whoever will stand still long enough.",
            (WEI, "Feet like this. He corrected mine four hundred times. I'm only going to correct yours forty. I'm being generous."),
            foe="training_puppet", count=4, v=0),
          B("probe", "Bai Ling's Question",
            "Bai Ling asks you something she's clearly been afraid to ask: whether the heart demon told you anything true.",
            (BAI, "Did it? Say anything true? You don't have to answer. I just — I want to know if grief lies about everything or just some things."),
            (P, "It lied about blame. It didn't lie about how much it would hurt."),
            v=0),
          B("gather", "Spirit Herbs for Elder Hua's Tonic",
            "Elder Hua brews a calming tonic for the grieving and needs fresh spirit herbs from the terraces.",
            item="spirit_herb", noun="fresh spirit herbs", v=0),
          B("hunt", "The Shade That Looks Like Wei Tong",
            "A smaller shade, shaped like Wei Tong himself, appears near a grieving junior disciple who blames himself for surviving.",
            foe="void_wraith", v=0),
          B("social", "Elder Yan's Loud Grief",
            "Elder Yan grieves the only way Thunder Peak knows how: loudly, and by making everyone else train harder.",
            (YAN, "I shout so I don't have to feel it quietly! It's a valid technique! Elder Mo would call it excessive! HE'D BE RIGHT!"),
            v=0),
          B("gather", "Medicine for the Last of the Infirmary",
            "A handful of disciples remain in the infirmary, their shades stubborn. Elder Hua wants more medicine on hand.",
            item="medicine", v=0),
          B("social", "Han Xue's Watch",
            "Han Xue has taken to sitting with you in the evenings, not talking, just present, the way you once did for her.",
            (HAN, "I'm not going to say anything wise. I'm just going to sit here. You did that for me once. I remember."),
            v=0),
          B("interlude", "The Shades Thin",
            "Night by night, the grief-shades thin. Not gone. Grief never goes. But smaller, and quieter, and no longer hungry.",
            (HUA, "The infirmary's empty. The shades are small now. They'll never be gone. Grief isn't a wound. It's a scar. Scars are fine."),
            "|",
            (SHI, "I told my sister I miss the cages. She didn't laugh. She held my hand. The shade on my shoulder is the size of a sparrow now."),
            (SHI, "I don't mind a sparrow."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 44
    C("Adequate", "sect",
      "The outer court has no elder, and twelve new disciples arrived at the gate this spring as if nothing had happened. "
      "Somebody has to teach them to stand up straight. Wei Tong would rather do anything else. He does it anyway.",
      cast=[WEI, YUN, HAN, LU, QIAN, HUA, YAN, SHI], foes=["training_puppet", "stone_golem", "spirit_wolf"],
      items=["spirit_stone", "spirit_herb", "jade_slip"], props=["stone_stele", "seal", "bronze_bell"],
      foe_names={"stone_golem": "tuned-up puppets"},
      beats=[
          B("orders", "Twelve at the Gate",
            "Twelve new disciples climbed the nine thousand steps this spring. None of them know who Elder Mo was.",
            (LU, "Twelve new ones! At the gate! Mud and hope, like always. One of them fainted on my boots. It felt like old times."),
            "@R:SectGate", (N, "Twelve candidates stand at the gate, muddy and shaking. One clutches a letter. One clutches a chicken. Nobody knows why."),
            "@T:SectGate",
            (YUN, "The outer court needs an elder. I have no elder to give it. I have Wei Tong. I'm going to ask him. Come with me. He'll say no."),
            ),
          B("social", "Wei Tong Says No",
            "Wei Tong says no. Then no again. Then, at the hall steps, next to the cup of tea, he says something else.",
            (WEI, "No. I'm not an elder. I'm a senior outer disciple with a sword called Dumpling. Elder Mo was... he was Elder Mo."),
            (YUN, "He wrote your name in his notes. Under 'if I'm gone'. He wrote: Wei Tong. He'll say no. Ask twice."),
            (WEI, "...He wrote that? He wrote 'ask twice'?"),
            "|",
            (WEI, "Fine. Fine. I'll teach them. Not as an elder. As a senior brother who's very, very stubborn. He'd want stubborn."),
            ),
          B("train", "The First Lesson",
            "Wei Tong's first lesson with the new disciples. He asks you to demonstrate, the way you did for him years ago.",
            (WEI, "Right! New disciples! This is {player}. Soul Transformation. Very scary. Watch the stance. Not the face. The face is distracting."),
            "@F:TrainingGround", ">Demonstrate on the puppets for the new disciples",
            (WEI, "Lead with your feet, not your elbows! Your sword follows your body! That's what he said to me. Now I'm saying it to you!"),
            "@T:WeaponRack",
            (WEI, "They stood up straight. All twelve. One of them saluted the puppet. I cried a bit. Don't tell them."),
            foe="training_puppet", count=5),
          B("gather", "Chickens and Contribution Points",
            "The new disciple with the chicken has lost the chicken. It is somewhere on the mountain, being a chicken.",
            (WEI, "The girl with the chicken lost the chicken. It's her only family. Well, it's a chicken. But it's hers. Find it?"),
            "@G:PlumGarden", ">Search the plum garden for the lost chicken",
            "@T:WeaponRack",
            (WEI, "You found it! In the plum garden! Eating plums! Qiu Hua is crying. The chicken is not. Chickens are very calm."),
            item="spirit_herb", noun="scattered chicken feathers"),
          B("probe", "Elder Mo's Notes",
            "Elder Mo left notes on every outer disciple he ever taught. Wei Tong asks you to read them with him.",
            (WEI, "His notes. On every disciple. Forty years of them. I found them under his bed. With his old tea set. The good one."),
            "@I:HallSteps", ">Read Elder Mo's notes with Wei Tong",
            (N, "Wei Tong: eats too much, laughs too loud, heart the size of the mountain. Will make a better teacher than me. Do not tell him."),
            "@T:HallSteps",
            (WEI, "He said I'd be better than him. He never told me. He told the paper. Why do old men tell paper things?"),
            (P, "Because paper doesn't argue back."),
            prop="jade_slip", thing="Elder Mo's notes"),
          B("duel", "The New Ones Test the Teacher",
            "The new disciples challenge Wei Tong to a spar, all twelve at once. He asks you to stand beside him, just in case.",
            (WEI, "All twelve at once! They think I'm soft because I cried at the salute! Stand next to me. I'm not soft. I'm... medium."),
            "@F:TrainingGround", ">Stand beside Wei Tong against the new disciples",
            "@T:WeaponRack",
            (WEI, "Twelve on the floor, laughing. Nobody hurt. That's how you do it. You make them fall, then you make them laugh."),
            foe="sparring_disciple", count=4),
          B("social", "The Budget for Buns",
            "Wei Tong asks Steward Qian for a budget for buns. For the new disciples. For morale. Steward Qian has opinions.",
            (QIAN, "Buns! A budget for buns! Elder Mo never asked for buns!"),
            (WEI, "He bet me buns every week for six years. I lost every bet. On purpose. That's three hundred buns. Consider it back pay."),
            (QIAN, "...That's actually a very good argument. Fine. Buns. A small budget. Very small. Medium."),
            "|",
            (HUA, "He's going to be a wonderful teacher. He's already the only one who's ever beaten Qian in an argument."),
            ),
          B("hunt", "Wolves at the Wall",
            "Spring wolves come down from the snowline to the outer wall, hungry and young. Wei Tong takes the new disciples to watch.",
            "@R:OuterPines", (N, "Young wolves nose along the outer wall, grey and thin. Twelve new disciples watch from the gate, frightened and thrilled."),
            "@F:OuterPines", (WEI, "Watch how you drive them off. Not kill. Drive. They're only hungry. Hungry isn't a crime. Elder Mo taught me that."),
            "@G:OuterPines", ">Leave meat scraps for the wolves at the treeline",
            "@T:SectGate",
            (WEI, "They'll go back to the snowline now, fed. The new ones think we're heroes. We're just people who feed wolves."),
            foe="spirit_wolf", item="spirit_herb", noun="meat scraps"),
          B("cultivate", "Standing Where He Stood",
            "Wei Tong asks you to meditate at the hall steps, where Elder Mo stood every morning. He says someone should.",
            (WEI, "Someone should stand where he stood. Not me. I'd cry. You. Sit there. With the tea. Be grumpy at the sunrise."),
            "@M:HallSteps", ">Meditate at the hall steps at sunrise",
            (N, "The sun comes up over the sea of clouds. Your soul settles, deeper than it has since the formation. Middle stage of Soul Transformation."),
            (N, "Back straight, you think, and straighten it, and smile."),
            "@T:WeaponRack",
            (WEI, "You straightened your back at the end. I saw. He'd have said adequate."),
            ),
          B("gather", "Spirit Stones for the Outer Court",
            "The outer court's twelve new disciples need spirit stones for their first formations. Wei Tong asks you to help gather them.",
            item="spirit_stone", v=0),
          B("hunt", "Tuned-Up Puppets",
            "Wei Tong has Elder Bai tune the training puppets harder, insisting Elder Mo would want the new batch tested properly.",
            foe="stone_golem", v=0),
          B("social", "The Girl With the Chicken",
            "Qiu Hua, the disciple with the chicken, asks Wei Tong shyly if the chicken can stay in the outer court permanently.",
            (WEI, "The chicken stays. I've decided. It's outer court morale now. Its name is Elder Drumstick. Don't tell Elder Yan."),
            v=0),
          B("gather", "Jade Slips for the New Curriculum",
            "Wei Tong, copying Elder Mo's method, wants jade slips prepared for the twelve new disciples' first lessons.",
            item="jade_slip", v=0),
          B("train", "The Second Lesson",
            "Wei Tong's second lesson goes worse than the first: one disciple hits herself in the face with her own sword.",
            (WEI, "Sword goes THAT way, not this way! Nobody panic, she's fine, she's laughing, see, she's fine!"),
            foe="training_puppet", count=4, v=0),
          B("social", "Lu Ping's Unsolicited Advice",
            "Lu Ping, despite having never taught anyone anything, gives Wei Tong extensive unsolicited advice on teaching.",
            (LU, "You should be stricter! Or gentler! One of those! I read a book about it once! I forget which one it recommended!"),
            v=0),
          B("hunt", "Spirit Wolves, a Second Pack",
            "A second, larger pack of spirit wolves tests the outer wall, drawn by the scent of the first pack's fed retreat.",
            foe="spirit_wolf", v=0),
          B("social", "Steward Qian's Bun Audit",
            "Steward Qian insists on personally auditing the bun budget, suspicious that Wei Tong is overselling how few buns cost.",
            (QIAN, "Three hundred buns is not a small budget! I have receipts! I have OPINIONS about these receipts!"),
            v=0),
          B("gather", "Spirit Herbs for the Chicken",
            "Qiu Hua asks, very seriously, for spirit herbs to supplement Elder Drumstick's diet, insisting a sect chicken deserves better feed.",
            item="spirit_herb", noun="chicken feed", v=0),
          B("social", "Xiao Shi Watches the New Ones",
            "Xiao Shi, who remembers being new and frightened somewhere much worse than a sect gate, watches the twelve with quiet approval.",
            (SHI, "They're scared the good way. The way you're scared of something worth being scared of. I like watching that heal into confidence."),
            v=0),
          B("interlude", "Adequate",
            "At the end of the first month, the twelve new disciples give Wei Tong a gift: a plaque for the weapon rack.",
            (LU, "The new ones made a plaque for Wei Tong. They asked me what to carve. I said one word. They carved it."),
            "|",
            (WEI, "It says 'Adequate'. Just that. On the weapon rack. In terrible calligraphy. I'm never taking it down. Never."),
            (WEI, "Somebody bring me a bun. I'm having a moment."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 45
    C("The Empty Law Hall", "qingshi_town",
      "Magistrate Zhou writes to the sect: Qingshi's disputes used to go to the Law Hall of the Azure Cloud when the yamen "
      "couldn't settle them. The Law Hall is empty. The Sect Master sends you, with a warning, and with advice from the "
      "last man who sat in its chair.",
      cast=[ZHOU, DU, JIN, PAN, LIU, FANG, TIE, LIUER, GU, HAN], foes=["bandit", "rogue_cultivator", "demon_cultivator"],
      items=["letter", "spirit_stone", "medicine"], props=["stone_stele", "jade_slip", "treasure_chest"],
      things={"stone_stele": "the yamen's law tablet"},
      beats=[
          B("orders", "A Judge Wanted",
            "Magistrate Zhou needs a judge from the sect. The Sect Master sends you, and suggests you ask the last judge for advice.",
            (YUN, "Qingshi needs a judge. You're the closest thing to a judge I have who isn't in chains. Ask the one who is, before you go."),
            "@T:MoonGate",
            (GU, "You want advice. From me. The man who wrote half the precepts and broke all of them."),
            (GU, "Very well. Listen to everyone twice. Decide once. And never, ever judge someone for what you'd have done in their place. That was my mistake."),
            "@R:qingshi_town/MagistrateHall", (N, "The yamen courtyard is full. Petitioners, witnesses, three goats and one very loud rooster. Magistrate Zhou looks relieved to see you."),
            map="sect"),
          B("social", "The Case of the Ferry",
            "The first case: Old Pan and Merchant Jin both claim the old ferry landing. Both have documents. Both are shouting.",
            (PAN, "Forty years I've used that landing! Forty! My father used it! His father probably fell off it!"),
            "|",
            (JIN, "The guild bought it! Twelve years ago! I have the deed! I'm not asking him to leave! I'm asking him to pay rent! Small rent! Tiny!"),
            "|",
            (P, "The guild owns the landing. Old Pan rows people for free when the town needs him. The guild will charge him the same: nothing."),
            (JIN, "...Nothing? That's... hm. That's exactly what I'd have done if I were a better man. Fine. Nothing. I'm getting good at nothing."),
            ),
          B("probe", "The Case of the Stolen Chickens",
            "Somebody is stealing chickens from the terraced fields. The farmers blame Iron-Fang's reformed men. Iron-Fang is furious.",
            (TIE, "They say my men took the chickens. My men haven't stolen anything in two years. They've been farming. Badly. But honestly."),
            "@R:Farmland", (N, "The chicken coops on the terraces stand empty. Feathers lead not to the bandits' huts but uphill, toward the graves."),
            "@I:Farmland", ">Follow the feathers from the coops",
            (N, "The feathers lead to a fox den under a grave tablet. A very fat fox. And a very small pile of bones."),
            "@T:MainStreet",
            (TIE, "A fox. Two years honest, and they blame us for a fox. Well. The fox is very clever. I respect the fox."),
            prop="stone_stele", thing="the trail of feathers"),
          B("social", "The Case That Isn't Simple",
            "Widow Liu brings a case she doesn't want to bring. Her son wants to climb the nine thousand steps. She wants a judge to forbid it.",
            (LIU, "He's sixteen now. He wants to climb the steps. To become a cultivator. Like you. I want a judge to say no."),
            (LIU, "I lost him once. I won't lose him to the Abyss. I won't."),
            "|",
            (LIUER, "Mother, I won't go to the Abyss. I want to learn to protect the town. Like Constable Du. Like the immortal."),
            "|",
            (P, "No judge should decide this. He'll climb in spring, with your blessing, or not at all. That's between you."),
            (LIU, "...Coward. That's a coward's judgement. It's also correct. Spring. Not before. And he writes every week."),
            ),
          B("battle", "Justice With Swords",
            "Rogue cultivators have heard the Law Hall is empty and decided the law no longer applies to them. They are wrong.",
            (DU, "Rogues on the river road, robbing travellers. They say there's no Law Hall anymore, so no law. I've written them a very firm letter."),
            "@F:Riverside",
            "@F2:TownGate",
            "@T:MainStreet",
            (DU, "Letter delivered. By you. With your fist. That's the kind of letter they understand."),
            foe="rogue_cultivator", foe2="rogue_cultivator"),
          B("probe", "The Case of the Old Temple",
            "Someone has been leaving offerings at Keeper Hong's old temple. Offerings to the Blood Moon.",
            (ZHOU, "Someone is leaving offerings at the temple at night. Red candles. Crescents. Hong's old altar. The town is frightened."),
            "@R:Temple", (N, "Red candles burn on the old altar, arranged in a crescent. Beside them, a child's drawing of a man with a kind face."),
            "@I:Temple", ">Examine the offerings on Hong's old altar",
            (N, "On the back of the drawing: Grandfather Hong. He was kind to me. Nobody else was. A child's hand."),
            "@T:MainStreet",
            (HAN, "A child. Grieving a monster who was kind to her. That's... I don't know what that is. Not a crime."),
            prop="stone_stele", thing="the offerings"),
          B("social", "The Child at the Temple",
            "You find the child who left the offerings. She is nine, an orphan, and she knew Keeper Hong only as someone who fed her.",
            "@R:BackAlley", (N, "In the back alley, a girl of nine sits hugging her knees, a red candle stub in her hand. She looks at your sword, then your face."),
            "@T:Inn",
            (FANG, "Little Mei. Orphan. Hong fed her every day for three years. He was a monster, and he fed her. People are complicated."),
            (FANG, "I'll take her. The inn needs someone to dry the cups. Iron-Fang's getting old. Don't tell him I said that."),
            ),
          B("defend", "Night Court",
            "Blood Moon cultivators come for the child. Hong's old followers think she belongs to them.",
            (DU, "Masked men at the inn! Asking for the orphan! Madam Fang hit one with a ladle and he's very upset!"),
            "@I:Inn", ">Ward the Drunken Crane's door",
            (N, "Your ward flares on the inn door. Inside, Madam Fang stands in front of the child with a ladle and an expression like thunder."),
            "@F:MainStreet",
            "@F2:BackAlley",
            "@T:Inn",
            (FANG, "Nobody takes a child from my inn. Not the Blood Moon, not the yamen, not heaven itself. She dries cups now. She's mine."),
            foe="demon_cultivator", foe2="demon_cultivator", prop="seal", thing="the inn door"),
          B("gather", "The Law Tablet",
            "Magistrate Zhou wants your judgements carved on the yamen's law tablet. He says it's how Qingshi remembers.",
            (ZHOU, "Your judgements. On the law tablet. The ferry, the fox, the boy, the child. Qingshi remembers its judges."),
            "@G:MarketSquare", ">Gather carving stones from the market",
            "@I:MagistrateHall", ">Watch the judgements carved on the tablet",
            (N, "Beneath the four judgements the carver adds a line nobody asked for: judged by one who listened twice."),
            "@T:MainStreet",
            (ZHOU, "Listened twice. I told him to carve it. It's the finest thing I've ever said about anyone. I'm going to weep now."),
            item="spirit_stone", noun="carving stones", prop="stone_stele", thing="the law tablet"),
          B("hunt", "Bandits on the River Road",
            "A separate band of bandits, unrelated to the rogue cultivators, tests the river road while the Law Hall is distracted.",
            foe="bandit", v=0),
          B("social", "Constable Du's Backlog",
            "Constable Du confesses the yamen has a backlog of small disputes too minor for a judge but too sharp for him alone.",
            (DU, "Boundary stones. Borrowed goats. A dispute about a rooster's crowing hours. I need a judge for none of it and all of it."),
            v=0),
          B("gather", "Medicine for the Widow Liu",
            "Widow Liu, still shaken from the temple offerings, needs medicine for a cough that worry has made worse.",
            item="medicine", v=0),
          B("social", "Little Mei's First Week",
            "Little Mei, drying cups at the Drunken Crane, asks you shyly whether the monster who fed her was really a monster.",
            (P, "He did terrible things to a great many people. He was also kind to you. Both are true. You're allowed to grieve one and not excuse the other."),
            v=0),
          B("probe", "The Case of the Borrowed Goats",
            "Constable Du's backlog starts with a genuinely baffling case: three goats, two farmers, and no clear owner.",
            (ZHOU, "Nobody remembers whose goats they were originally. They've just been borrowed back and forth for six years."),
            (P, "Split them three ways: one each, and the third takes turns by season. Nobody loses a goat forever."),
            v=0),
          B("hunt", "Rogue Cultivators, a Second Letter",
            "The rogue cultivators' friends come looking for them, and receive Constable Du's kind of letter too.",
            foe="rogue_cultivator", v=0),
          B("gather", "Letters for the Law Tablet's Record",
            "Magistrate Zhou wants copies of every judgement written up as letters, sent to neighboring towns as precedent.",
            item="letter", v=0),
          B("social", "Iron-Fang's Testimony",
            "Iron-Fang, cleared of the chicken theft, offers to testify on behalf of his men in every future dispute, unasked.",
            (TIE, "I'll vouch for my men in writing, in blood if you want it. Two years honest ought to count for something in a court."),
            v=0),
          B("hunt", "Demon Cultivators at the Temple",
            "A few Blood Moon stragglers try to reclaim Keeper Hong's old temple as a shrine. The town wants them gone.",
            foe="demon_cultivator", v=0),
          B("social", "Han Xue's Verdict",
            "Han Xue, watching you judge case after case, offers her own opinion on what makes a good judge.",
            (HAN, "You're good at this because you'd rather understand someone than punish them. Gu was the opposite, once. He's trying to learn from you."),
            v=0),
          B("interlude", "Report to the Chains",
            "Back at the sect you tell Gu Hanshan how it went. He listens twice, as he said to.",
            "@T:sect/MoonGate",
            (GU, "A fox, a ferry, a boy and a child. You judged none of them for what you'd have done. Good."),
            (GU, "The Law Hall is empty. It should stay empty until someone kinder than me sits in it. That may be a long time."),
            (P, "Maybe it's you, after all this."),
            (GU, "No. I'll never sit there again. But thank you for saying it. It's a strange thing to be forgiven by the person you wronged most."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 46
    C("Where the Lotus Grew", "sect",
      "The Verdant Lotus seed you planted in the sect's pond before the descent has flowered, green and gold, beside "
      "the Azure Cloud's carp. The hermit promised he would visit when it did. After three hundred years in the bamboo, "
      "Lan Jue climbs the nine thousand steps.",
      cast=[LAN, YUN, MAN, SHI, HUA, BAI, WEI, HAN], foes=["spirit_wolf", "void_wraith", "training_puppet"],
      items=["spirit_herb", "incense", "jade_slip"], props=["seal", "stone_stele", "jade_slip"],
      things={"seal": "the green lotus"},
      beats=[
          B("orders", "Green in the Pond",
            "Xiao Man comes running: the lotus in the pond has opened, and it is green, and the carp are bowing to it.",
            (MAN, "The lotus! The one you planted! It opened this morning and it's green! Green and gold! The carp are bowing! Carp can't bow!"),
            "@R:LotusPond", (N, "A lotus the colour of new jade floats in the pond, gold at its heart. Every carp in the water faces it, perfectly still."),
            "@T:StoneBridge",
            (SHI, "My sister's been sitting here since dawn. She says the hermit promised to come. She's sent him six cranes. They were very bad cranes."),
            ),
          B("journey", "The Nine Thousand Steps",
            "At noon, Lu Ping runs up from the gate: an old man in a straw hat is climbing the steps, very slowly, and complaining the whole way.",
            (LU, "An old man on the steps! Straw hat! He's complaining about every single step! He says they were lower three hundred years ago!"),
            "@R:SectGate", (N, "Up the last steps comes the hermit, straw hat, walking stick, bad knees, and an expression of profound betrayal toward staircases."),
            "@T:SectGate",
            (LAN, "Nine thousand steps. Your founder was a sadist. I told her so three hundred years ago. She laughed. I'm still right."),
            (LAN, "Where's the lotus? I came to see the lotus. Not the steps. Definitely not the steps."),
            ),
          B("social", "The Hermit Meets the Sect Master",
            "The Sect Master comes to the gate herself. The last disciple of the Verdant Lotus bows to the master of the Azure Cloud.",
            (YUN, "Lan Jue of the Verdant Lotus. Welcome to the Azure Cloud. Three hundred years late. Better late."),
            (LAN, "Sect Master. I ran when your founder and mine needed me most. I've come to say I'm sorry. And to look at a flower."),
            (YUN, "Your sect gave everything to the seal. Ours forgot your name. We're both sorry. Come and look at the flower."),
            ),
          B("cultivate", "Two Sects at One Pond",
            "The hermit and the Sect Master sit at the pond together. They ask you to sit between them.",
            (LAN, "Sit between us. You're the only thing both our sects have in common now. Humour two old people."),
            "@M:LotusPond", ">Sit between the two sects at the pond",
            (N, "Blue on one side, green on the other. The lotus turns toward you. For a moment the pond reflects two founders, side by side, and then only the three of you."),
            "@T:StoneBridge",
            (YUN, "He'll stay a few days. He says the pagoda needs someone who knows how to read Verdant Lotus script. Bai is ecstatic."),
            ),
          B("social", "Bai Meets Lan",
            "Elder Bai has waited his whole life to meet a Verdant Lotus scholar. The hermit has waited three hundred years to meet a good librarian.",
            (BAI, "You read the old script! You read it fluently! Do you know what the third character on the drowned stele means? I've guessed for forty years!"),
            (LAN, "It means 'turtle'. It was a soup recipe. We hid everything important in soup recipes."),
            (BAI, "...I knew it. I knew it! My grandmother! She learned it from you! From your sect! Oh, sit down, sit down, have some tea!"),
            "|",
            (LAN, "Finally. Someone who pours for me. Three hundred years I've been pouring my own."),
            ),
          B("gather", "Peach Trees for the Old Man",
            "Elder Hua has an idea: plant Elder Mo's peach trees beside the lotus, so there's something of him by the water too.",
            (HUA, "Peach saplings from the old orchard. Mo's orchard. Plant them by the pond. He left me peaches for forty years. I'm leaving him trees."),
            "@G:OuterPines", ">Dig peach saplings from the old orchard",
            "@I:LotusPond", ">Plant Elder Mo's peach trees by the pond",
            (N, "Three peach saplings beside the green lotus. Elder Hua pats the earth around each one, and doesn't say anything for a long time."),
            "@T:HerbGarden",
            (HUA, "In five years they'll fruit. I'll leave a peach on my own doorstep every autumn, and pretend. That's our tradition."),
            item="spirit_herb", noun="peach saplings", prop="seal", thing="the peach saplings"),
          B("hunt", "Wolves Follow the Hermit",
            "The hermit's old friends from the forest have followed him up the mountain: grey wolves who don't understand stairs either.",
            "@R:OuterPines", (N, "Grey wolves pace at the outer wall, whining. They followed the hermit's scent up nine thousand steps and are very confused."),
            "@F:OuterPines", (N, "Some of the wolves are not his. Some have purple in their eyes, and came up with the hermit's scent to hide their own."),
            "@G:OuterPines", ">Calm the hermit's wolves with meat",
            "@T:SectGate",
            (LAN, "My wolves. And void-touched ones pretending to be my wolves. The fold at the Abyss is leaking all over the world. I felt it in the forest."),
            foe="void_wraith", item="spirit_herb", noun="scraps for the wolves"),
          B("probe", "The Letter for Lan",
            "You still have the letter from the reliquary, addressed to Lan when he stops running. You think he has.",
            "@I:LotusPond", ">Give the hermit his master's letter",
            (N, "Lan Jue breaks the green wax with trembling fingers. He reads it twice. Then he laughs, and cries, and laughs."),
            "@T:StoneBridge",
            (LAN, "She wrote: Lan, you idiot, stop running and go and teach someone. That's all. Three hundred years. That's all it said."),
            (LAN, "I'll teach. The sutra. Here, in the pagoda, if your Sect Master allows. Somebody has to, and it seems I'm the only one left."),
            prop="jade_slip", thing="the letter"),
          B("social", "Wei Tong Is Jealous",
            "Word spreads that the hermit will teach the Heart Sutra in the pagoda. Wei Tong wants to know if there's lunch.",
            (WEI, "He's going to teach? In the pagoda? Every morning? Is there lunch? The Verdant Lotus must have had lunch."),
            (LAN, "We had tea. And a turtle soup. Very famous. Very secret. The recipe was also a sealing diagram."),
            (WEI, "...I'm going to learn the Heart Sutra. For the soup. Mostly for the soup. A bit for the sutra."),
            "|",
            (HAN, "Everyone's happy. I'm suspicious. It's been a week without an attack. Something's wrong."),
            ),
          B("interlude", "Something's Wrong",
            "Han Xue is right. A crane arrives from Qingshi, spotted with ash: the outer villages are burning, one each night.",
            (HAN, "A crane from Constable Du. Villages burning in the lowlands. One a night. Each one leaves a pile of ash in the shape of a ladder."),
            (HAN, "Ash. Luo Hui. The First Rung is back, and he wants you to know it."),
            (LAN, "Go. I'll be in the pagoda, being taught to use your terrible modern brushes by your excitable librarian. Come back."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 47
    C("A Letter Signed With Ash", "qingshi_town",
      "Every night a village near Qingshi burns, and in the ashes someone draws a ladder. Luo Hui, the First Rung, is "
      "healed and hungry and writing to you. The letters are polite. The fires are not.",
      cast=[DU, ZHOU, HAN, ZHAO, TIE, LIUER, YE, PAN], foes=["demon_cultivator", "blood_guard", "void_wraith"],
      items=["letter", "medicine", "void_shard"], props=["treasure_chest", "bronze_bell", "seal"],
      foe_names={"demon_cultivator": "ash-cultists"},
      things={"seal": "the ash ladder"},
      beats=[
          B("orders", "Ladders in the Ash",
            "Constable Du takes you to the latest burned village. In the ash, someone has drawn a ladder with seven rungs.",
            "@R:Farmland", (N, "Beyond the fields a village smoulders. In the ash of the largest house, a ladder has been drawn with a finger. Seven rungs. The first rung is circled."),
            "@T:MainStreet",
            (DU, "Seven villages. Nobody killed. Everyone woken, marched out, then the houses burned. Like he wants us to count."),
            (DU, "And every time, a letter nailed to the well. Addressed to you."),
            ),
          B("probe", "The First Letter",
            "The letters are in a beautiful hand. They are polite. They are very, very specific about you.",
            "@I:Well", ">Read the letter nailed to the well",
            (N, "Dear heir. You shook me in the warehouse. I have healed. My star is bright again. Come and shake me properly. Luo Hui, the First Rung."),
            "@R:Well", (N, "There's a second page. A map of Qingshi's outer villages. Seven of them crossed out. The eighth circled. Tonight."),
            "@T:MainStreet",
            (HAN, "He's telling you where he'll be. That's either arrogance or a trap. It's both. It's always both."),
            prop="jade_slip", thing="the letter"),
          B("defend", "The Eighth Village",
            "The eighth village is on the river. You get there before the ash does.",
            (PAN, "The eighth village is across my river. I'll ferry you over. No fare. I'll wait. I'll pray. I'll hit anyone who comes near with an oar."),
            "@I:Riverside", ">Ring the dock bell to wake the village",
            (N, "The bell clangs across the water. Lamps flare in the village. Families pour out of their houses, just as figures in grey ash pour in."),
            "@F:Farmland",
            "@F2:Riverside",
            "@T:MainStreet",
            (ZHAO, "Nobody burned tonight. That's one village he didn't get. He'll be angry. Good. Angry people write worse letters."),
            foe="demon_cultivator", foe2="blood_guard", prop="bronze_bell", thing="the dock bell"),
          B("social", "Letters Back",
            "Zhao Kang suggests writing back. Rudely. Han Xue suggests writing back politely. You write back honestly.",
            (ZHAO, "Write back. Tell him he's a pile of ash with ideas above his station. Rungs are for climbing on. Tell him that."),
            "|",
            (HAN, "Write back politely. Politeness makes arrogant people careless. He'll underestimate you."),
            "|",
            (P, "I'll write back honestly. Dear Luo Hui. I'm coming. I won't burn anything. Stop burning things. That's all."),
            (HAN, "...That's worse. That's much worse. He'll hate that. Send it."),
            ),
          B("hunt", "Ash on the Wind",
            "Luo Hui's answer comes as ash on the wind, blowing north toward the bamboo forest.",
            "@R:WatchTower", (N, "From the watchtower you see it: a thin grey line of ash in the sky, blowing north, toward the forest, like a finger pointing."),
            "@F:Graveyard", (N, "Ash-cultists wait in the hill graves to slow you down. They've been told to die slowly. They're good at following orders."),
            "@G:Graveyard", ">Gather the ash-cultists' letters",
            "@T:MainStreet",
            (YE, "I followed the ash from the rim. He's been moving between the Abyss and the forest. He's building something in the ruins."),
            (YE, "The Verdant Lotus ruins. He's using your family's stones. For his rung."),
            foe="demon_cultivator", item="letter", noun="cultists' letters"),
          B("chase", "The Burning Bamboo",
            "The bamboo forest's edge is burning. Luo Hui wants you to come through fire.",
            "@R:bamboo_forest/ForestPath", (N, "The bamboo at the forest's edge is burning in a perfect line, like a fence. Through the smoke, a ladder of ash hangs in the air."),
            "@F:HerbGrove", (N, "Ash-cultists stand in the burning grove, feeding the fire, chanting a single word over and over: climb."),
            "@R:RuinsGate", (N, "The ruins gate is black with soot. On the archway, over the carved lotus, someone has painted a red rung."),
            "@T:Clearing",
            (TIE, "I followed you. My men are putting out the fire. We're very good at fire. We used to start them. Now we stop them. It's better."),
            foe="demon_cultivator"),
          B("delve", "The Rung in the Ruins",
            "Inside the ruins, Luo Hui has built an altar of Verdant Lotus stones, tied to his star. He's using your family to hold up his ladder.",
            "@R:RuinsInner", (N, "In the courtyard, lotus stones have been piled into an altar. A thread of red light rises from it, up through the canopy, toward a star."),
            "@G:RuinsInner", ">Pull the stolen lotus stones from the altar",
            "@I:RuinsInner", ">Cut the red thread to the star",
            (N, "The thread snaps. Far above, a red star flickers. Somewhere in the forest, someone screams in rage, and the ash stops falling."),
            "@F:RuinsGate", (N, "Luo Hui's cultists pour out of the bamboo, too late to save the altar, just in time to be angry about it."),
            "@R:AncientShrine", (N, "The shrine is quiet. The lotus stones are back where they belong. Luo Hui is gone. His ash trail leads south. Toward the Abyss."),
            item="rune_fragment", foe="demon_cultivator", prop="seal", thing="the red thread", map="bamboo_forest"),
          B("social", "He'll Be at the Abyss",
            "Ye Wuming reads the ash trail. Luo Hui has gone home to the Abyss rim, to heal. It's where he'll be strongest.",
            (YE, "He's gone to the rim. Near the fold. That's where the rungs draw power now. He'll be strongest there."),
            (YE, "Which is where you should fight him. Because there, if you win, his star doesn't come back."),
            "|",
            (HAN, "Then we rest. We heal. We go to the rim when we're ready, not when he wants us. Everyone agree? Good. Nobody argue."),
            ),
          B("stage", "Ash and Soul",
            "Before the hunt you sit in the ruined shrine and let the week settle into your transformed soul.",
            "@M:AncientShrine", ">Meditate in the ruined shrine",
            (N, "Your soul and body blur at the edges, like ink in water. The ruins hum with your family's old patience. Late stage of Soul Transformation."),
            "@T:Clearing",
            (TIE, "You glow when you meditate. Did you know that? My men think you're a god. I told them you're a very stubborn orphan. They prefer god."),
            map="bamboo_forest"),
          B("interlude", "Liu Er's Steps",
            "Back in Qingshi, Liu Er is packing. It's spring. He's climbing the nine thousand steps tomorrow, with his mother's blessing.",
            (LIUER, "Tomorrow! The nine thousand steps! Mother blessed me. She cried. Then she packed me eleven meals. For one day."),
            (LIUER, "Will you be at the gate? You don't have to. But if you were. That would be... that would be very good."),
            "|",
            (LIU, "He writes every week. That's the deal. And if he fails the test he comes home and carries water. That's also the deal."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 48
    C("The Mirror Within", "blood_abyss",
      "Before you hunt Luo Hui at the rim, the Heart Mirror calls. It's outside the fold, still black, still still, and "
      "your transformed soul can hear it humming your name. There is one fear you haven't faced yet: not of dying, but "
      "of ascending, and leaving everyone behind.",
      cast=[HAN, YE, ZHAO, GU, SHI], foes=["void_wraith", "blood_guard", "heart_demon"],
      items=["void_shard", "demon_core", "medicine"], props=["seal", "demon_obelisk", "stone_stele"],
      boss=("heart_demon", "The Fear of Leaving", "HeartMirror"),
      beats=[
          B("orders", "The Mirror Calls",
            "You wake with the Heart Mirror humming in your soul. Han Xue says no. Then says she's coming.",
            (HAN, "The mirror's calling you? Absolutely not. Last time it let out a monster wearing your face."),
            (HAN, "...You're going anyway. I can see it. Fine. I'm coming. I'll stand at the edge and glare at it."),
            "@R:blood_abyss/CanyonEntrance", (N, "The canyon is quieter since the fold. The wind comes up from below carrying the smell of nothing at all."),
            "@T:CanyonEntrance",
            (YE, "You're going to the mirror. Don't look surprised; I can see it on you. I'll guide you. The paths have changed since the fold."),
            map="sect"),
          B("battle", "Wraiths on the Old Paths",
            "The fold's leak has filled the old Abyss paths with void wraiths, and they are drawn to souls like yours.",
            (YE, "Wraiths. They smell transformed souls. You're a feast to them. Stay close, and hit first."),
            "@F:BoneField",
            "@F2:BloodPools",
            "@R:AbyssDepths", (N, "At the bottom of the Abyss the darkness is thicker than you remember, as if the fold had poured some of itself down here."),
            foe="void_wraith", foe2="void_wraith"),
          B("social", "Gu's Warning",
            "Gu Hanshan insisted on coming, chained, to the depths. He says there is something about the mirror you need to hear.",
            (GU, "I couldn't face the mirror. You could. Now it wants to finish what it started. It will show you something new."),
            (GU, "Not your fear of dying. You've faced that. Your fear of living. Of going on when everyone else stops."),
            (P, "How do you know?"),
            (GU, "Because I watched my daughter die and went on living. That was my mirror. Yours will be the same, only higher."),
            ),
          B("probe", "The Mirror's Surface",
            "The Heart Mirror is still, black and patient. When you look into it, it doesn't show you. It shows everyone else.",
            "@R:HeartMirror", (N, "The mirror shows Han Xue, old, grey-haired. Zhao Kang, bent over a cane. Wei Tong's grave. The sect, and you above it, young and alone."),
            "@I:HeartMirror", ">Look deeper into the Heart Mirror",
            (N, "You climb the Ascension Stair, and every step, someone you love grows older and falls away, until there's no one left to wave."),
            "@T:AbyssDepths",
            (HAN, "Stop looking. {player}, stop. You've gone white. What did you see?"),
            (P, "You. Old. Everyone, gone. And me, still climbing."),
            prop="seal", thing="the black water"),
          B("boss", "The Fear of Leaving",
            "The mirror lets out a new shade. This one wears your face too, but older, sadder, and it doesn't want to hurt you. It wants you to stop.",
            "@R:HeartMirror", (N, "A figure steps out of the water, wearing your face, but older, with eyes that have watched everyone die. It raises its sword, and weeps."),
            "@X",
            (DEMON, "Stay. Don't climb. Stay with them. Grow old with them. Heaven is lonely, {player}. I've seen it. I'm what you become."),
            (P, "Maybe. But they'd tell me to climb. Every one of them would tell me to climb."),
            "@M:HeartMirror", ">Still the mirror once more",
            (N, "The mirror calms. Your reflection is only you again, tired, not alone. Behind you, in the water, Han Xue is scowling. It's very comforting."),
            "@T:AbyssDepths",
            (HAN, "I'd tell you to climb. And then come back down and visit. Weekly. Like Zhao Kang writes to his grandfather."),
            ),
          B("social", "Everyone Would Say Climb",
            "On the way back up, Zhao Kang, who came to find you, says the thing the mirror couldn't argue with.",
            (ZHAO, "I heard what you said to it. That we'd all tell you to climb. Of course we would. And then complain about it forever."),
            (ZHAO, "Heaven's lonely? Then take us with you. In here. The complaints especially. Heaven could use some complaints."),
            "|",
            (YE, "When you reach the top, remember us down here. That's all anyone who stays behind wants. To be remembered."),
            (YE, "I remembered a name down there. Not mine. My mother's. It's a start."),
            ),
          B("hunt", "Blood Guards at the Rim",
            "Luo Hui's Blood Guards are waiting at the rim. He knows you went to the mirror. He knows you're tired.",
            "@R:BoneField", (N, "Blood Guards line the rim, and behind them ash drifts upward, toward one flickering red star."),
            "@F:BoneField",
            "@G:BoneField", ">Gather demon cores from the fallen guards",
            "@T:CanyonEntrance",
            (YE, "He's watching. He wanted you tired. You're not tired. You're something else. I don't know the word."),
            foe="blood_guard", item="demon_core", noun="demon cores"),
          B("cultivate", "Rest Before the Rung",
            "Han Xue orders you to rest one night before facing Luo Hui. You don't argue. You're learning.",
            (HAN, "One night. You rest. That's not a suggestion from your senior sister. That's an order from the person who'll carry you home if you don't."),
            "@M:AbyssDepths", ">Rest your soul in the abyss depths",
            (N, "In the stillness at the bottom of the world, your soul rests. The fear of leaving is still there, but small, and folded, like a letter kept for later."),
            "@T:CanyonEntrance",
            (SHI, "I came to bring you medicine. My sister made more. It says 'eat this, idiot' on the label. That's how she says I love you."),
            ),
          B("probe", "The Flickering Star",
            "In soul sight, the thread from the rim to Luo Hui's star is thick and bright. His rung is at the obelisk ring.",
            "@R:ObeliskRing", (N, "In soul sight, a red thread rises from the obelisk ring to the sky, thick as a rope, humming. The First Rung is there."),
            "@I:ObeliskRing", ">Trace the red thread with your soul",
            (N, "At the thread's root, among the obelisk stumps, a pale man sits in a ring of ash, waiting. He waves."),
            "@T:CanyonEntrance",
            (HAN, "He waved. The First Rung waved at you. I'm going to enjoy this more than a senior sister should."),
            prop="demon_obelisk", thing="the red thread"),
          B("interlude", "The Night Before the Rung",
            "At the rim, before the fight, Ye Wuming tells you the name he remembered. His mother's name.",
            (YE, "Her name was Ye Qing. Evening Clear. I remembered it in the mirror. I think she named me something like it."),
            (YE, "When this is done, I'll find the rest. Tomorrow, break the first rung. For the children in the cages. For her."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 49
    C("The Rung of Ash", "blood_abyss",
      "Luo Hui, the First Rung of the Patriarch's Ladder, waits at the obelisk ring in a circle of ash. He has healed "
      "twice. He intends to test you one last time. This time, with the fold at his back and his star overhead, he is "
      "not going anywhere, and neither are you.",
      cast=[HAN, YE, ZHAO, TIE, YUN, WEI], foes=["blood_guard", "demon_cultivator", "void_wraith"],
      items=["demon_core", "void_shard", "rune_fragment"], props=["demon_obelisk", "seal", "treasure_chest"],
      boss=("rung_deacon", "Luo Hui, the First Rung", "ObeliskRing"),
      foe_names={"demon_cultivator": "ash-cultists"},
      beats=[
          B("battle", "The Ash Circle",
            "Luo Hui's last followers form a circle of ash around the obelisk ring. Breaking it means breaking them.",
            (ZHAO, "A circle of ash, and people standing in it chanting. I'm not going to ask. I'm just going to hit them."),
            "@F:BoneField",
            "@F2:BloodPools",
            "@R:CanyonEntrance", (N, "The ash circle breaks. At the obelisk ring, the pale man stands up and dusts himself off, politely."),
            foe="demon_cultivator", foe2="blood_guard"),
          B("social", "The Last Letter",
            "Before the fight, Luo Hui sends one last letter by a trembling cultist. It's very short.",
            (N, "The cultist hands you a letter and runs. It says: Dear heir. Thank you for writing back. Nobody ever writes back. Luo Hui."),
            (P, "He's lonely."),
            "|",
            (HAN, "He burned seven villages. Lonely isn't an excuse. But... yes. He's lonely. That's what makes it sad."),
            ),
          B("delve", "Seven Anchors",
            "The First Rung's star is tied to seven anchor-stones around the obelisk ring. Cut them, and his star can't heal him.",
            "@R:ObeliskRing", (N, "Seven anchor-stones glow red among the obelisk stumps. Each one sings a single note up to a flickering star."),
            "@G:ObeliskRing", ">Pry loose the seven anchor-stones",
            "@I:ObeliskRing", ">Break the last anchor",
            (N, "The last anchor cracks. Overhead, the red star stops flickering and holds, steady and small. It can't send him anything now."),
            "@F:BoneField", (N, "Luo Hui's guards charge from the bone field, too late. The pale man doesn't join them. He's waiting for you."),
            "@R:BloodPools", (N, "Everything is quiet. The ash has stopped falling. Across the pools, the First Rung stands alone in his circle."),
            item="rune_fragment", foe="blood_guard", prop="demon_obelisk", thing="the last anchor"),
          B("boss", "The First Rung Falls",
            "The First Rung of the Patriarch's Ladder stands in his circle of ash and bows. One rung is nothing. Seven is a road to heaven.",
            "@R:ObeliskRing", (N, "Luo Hui bows. Ash drifts from his sleeves. His star is overhead, cut off. He knows. He smiles anyway."),
            "@X",
            (RUNG1, "You wrote back. Nobody ever writes back. I was a scribe once, before the moon took me. I wrote a thousand letters. No answers."),
            (RUNG1, "Come, heir. Test me properly. One rung is nothing. But I'd like to be something, just once."),
            "@I:ObeliskRing", ">Stand over the fallen First Rung",
            (N, "Luo Hui lies in his ash, smiling. Thank you for the letter, he says, and becomes ash, and the wind takes him, and his star goes out."),
            "@T:CanyonEntrance",
            (YE, "One star out. On Qing Luan's chart, one red star is dark now. Six left."),
            (YE, "He thanked you. The Blood Moon never taught anyone to thank. He learned it somewhere. That's almost worse."),
            prop="seal", thing="the ash"),
          B("social", "One Star Out",
            "The Sect Master comes through the array to see for herself. Above the fold, one of seven red points of light is gone.",
            (YUN, "One star. Out. I saw it from the mountain; Qing Luan's crane arrived five minutes later, shouting."),
            (YUN, "Six left. Each one harder. But the Ladder can be broken. You've proved it. The long war has its first victory."),
            "|",
            (WEI, "I brought dumplings to the Abyss. For the victory. They're a bit ashy. Everything's a bit ashy here."),
            ),
          B("gather", "The Scribe's Letters",
            "In Luo Hui's camp you find crates of letters. Thousands of them. All written by him. None of them sent.",
            (HAN, "Crates. Letters. Thousands. All in his hand. All addressed to people. None sent."),
            "@G:DemonCamp", ">Gather the unsent letters",
            "@T:CanyonEntrance",
            (HAN, "To his mother. To a friend called Bo. To a girl he met once at a market. Forty years of letters to people he never saw again."),
            (P, "Like Gu's letters to his daughter."),
            item="letter", noun="unsent letters"),
          B("probe", "What the Letters Say",
            "Among the unsent letters, one is addressed to the Patriarch. It's the only one that's been opened.",
            "@I:DemonCamp", ">Read the letter addressed to the Patriarch",
            (N, "Master. The heir grows. When the seventh rung is set and the heir's lightning comes, the ladder will hold your weight. Your faithful first."),
            "@R:DemonCamp", (N, "Beneath, in a different, older hand, a single word in red: Good."),
            "@T:CanyonEntrance",
            (YE, "When the heir's lightning comes. Your tribulation. They're waiting for it. All seven rungs, to hold him while he climbs your lightning."),
            (YE, "Six to go. Break them before your sky breaks. That's the whole war, in one sentence."),
            prop="jade_slip", thing="the opened letter"),
          B("social", "Iron-Fang's Question",
            "Iron-Fang asks the question everyone has been avoiding: if the fold opens only for the tribulation, how long will his family wait?",
            (TIE, "If he only comes out for your lightning, how long's that? Years? My sister's behind that fold. Years."),
            (P, "Ye Wuming says the void holds them still. Like flies in amber. They won't age. They won't know how long."),
            (TIE, "...Then I'll wait for them. Iron-Fang pays his debts, and he waits. Get strong, sect brat. Get strong faster."),
            ),
          B("battle", "Void at the Rim",
            "With the first rung gone, the fold shudders, and more void wraiths spill out at the rim, angry and lost.",
            (HAN, "The fold's upset. More wraiths. They don't know what they are. They just know something broke."),
            "@F:BloodPools",
            "@F2:BoneField",
            "@T:CanyonEntrance",
            (ZHAO, "I've counted. That's one Rung, forty guards, sixty wraiths and one very ashy dumpling. Best week of my life."),
            foe="void_wraith", foe2="void_wraith"),
          B("interlude", "Burning the Letters",
            "At dusk, Han Xue asks what to do with Luo Hui's thousand unsent letters. You know what he'd want.",
            (HAN, "A thousand letters. We can't deliver them. Most of the people are dead. What do we do?"),
            (P, "We send them. The only way we can."),
            "@I:CanyonEntrance", ">Burn the unsent letters at the rim",
            (N, "The letters burn, and the ash rises, and for the first time it doesn't form a ladder. It just goes up, into the dark, like it's finally being delivered."),
            "@T:CanyonEntrance",
            (HAN, "That's the kindest thing anyone's ever done for a monster. I'm not crying. It's the ash."),
            prop="seal", thing="the pile of letters"),
      ]),
    # ------------------------------------------------------------------ chapter 50
    C("What the Old Man Left", "sect",
      "Elder Mo left very little: a tea set, a peach orchard, forty years of notes, and a locked box addressed to you. "
      "With the first rung broken and the long war begun, the Sect Master decides it's time you opened it.",
      cast=[YUN, WEI, HUA, HAN, BAI, LAN, MAN, SHI, LU, LIUER], foes=["training_puppet", "void_wraith", "demon_cultivator"],
      items=["jade_slip", "spirit_herb", "incense"], props=["treasure_chest", "jade_slip", "seal"],
      things={"treasure_chest": "Elder Mo's box"},
      beats=[
          B("orders", "The Locked Box",
            "The Sect Master gives you a box of plain wood, locked, with your name on it in Elder Mo's square handwriting.",
            (YUN, "He left this for you. With instructions: 'give it when the first rung falls, not before'. He knew about the rungs. Of course he did."),
            "@I:MainHall", ">Open Elder Mo's box",
            (N, "Inside: a sword manual in Elder Mo's hand, a folded letter, and a single dried peach blossom, pressed flat."),
            "@T:HallSteps",
            (WEI, "His handwriting. That's his handwriting. I'd know those square characters anywhere. He wrote like he talked. Like a wall."),
            prop="treasure_chest", thing="Elder Mo's box"),
          B("probe", "The Letter",
            "You read Elder Mo's letter on the hall steps, where he stood every morning.",
            "@R:HallSteps", (N, "The letter is short. Elder Mo's letters are always short. You read it twice."),
            "@I:HallSteps", ">Read Elder Mo's letter",
            (N, "Junior. If you're reading this, I found the flaw too late. Don't blame yourself. I'd have gone anyway. Back straight. Adequate. More than. Mo."),
            "@T:StoneBridge",
            (HAN, "Back straight. Even in his last letter. Of course. He'd have written it on his own gravestone."),
            prop="jade_slip", thing="the letter"),
          B("train", "The Sword Manual",
            "Elder Mo's sword manual is thirty pages of diagrams and one page of advice. The advice is: stop overthinking.",
            (WEI, "The manual! Thirty pages! Diagrams! And the last page just says: stop overthinking, you overthinker. That's you. That's definitely you."),
            "@F:TrainingGround", ">Practise Elder Mo's forms on the puppets",
            (WEI, "That's his stance! The low one! He only did it when he was really angry! You do it better! Don't tell him! He can't hear! Tell him anyway!"),
            "@T:WeaponRack",
            (WEI, "His forms, in your hands. It's like watching him. Younger, and less grumpy. And better looking. Don't tell him that either."),
            foe="training_puppet", count=5),
          B("social", "The Peach Blossom",
            "The dried peach blossom in the box has a note on its back. It's not for you.",
            (HUA, "A blossom from his orchard. The note on the back. Let me see. ...It says 'for Hua'. In his hand. Forty years."),
            (HUA, "Forty years of anonymous peaches, and he signs a blossom when he's gone. That stubborn, stubborn old man."),
            "|",
            (HUA, "I'm going to press it in my herbal. Between moonbell and mountain sage. He'd hate that. It's perfect."),
            ),
          B("gather", "Cleaning His Room",
            "Somebody has to clean Elder Mo's room. Wei Tong can't. Elder Hua won't. So you do, with Xiao Man, who drops everything.",
            (MAN, "I'll help! I'll only drop the unimportant things! Probably! Is a teapot important? It's his good teapot. I'll hold it very carefully."),
            "@G:HallSteps", ">Pack up Elder Mo's belongings",
            "@T:LotusPond",
            (MAN, "I didn't drop the teapot. I dropped the lid. It's fine. It's fine! It bounced! Wei Tong's keeping the teapot. For the tea on the steps."),
            item="jade_slip", noun="Elder Mo's belongings"),
          B("social", "The Hermit Reads the Manual",
            "The hermit reads Elder Mo's sword manual in the pagoda and declares it the most irritating document he's ever loved.",
            (LAN, "This is the most irritating sword manual I've ever read. Every diagram has a note. 'Back straight.' 'No.' 'Again.' 'Adequate.'"),
            (LAN, "I wish I'd met him. I'd have liked to argue with him. People who write 'no' in the margins are wonderful to argue with."),
            "|",
            (BAI, "I'm making a copy for the pagoda. Every note. Every 'no'. The Verdant Lotus hid everything in soup. The Azure Cloud hides it in grumbling."),
            ),
          B("defend", "Guarding His Grave",
            "At night, void wraiths gather at the cliff edge where Elder Mo's ashes were scattered. The fold's leak is drawn to grief.",
            (LU, "Wraiths at the cliff! Where we scattered his ashes! They're just... standing there! Like they're mourning! Or feeding!"),
            "@I:CliffEdge", ">Ward the cliff edge where his ashes lie",
            (N, "Your ward rises blue over the cliff, and the wraiths flinch back. For a moment in the blue light you'd swear someone was standing very straight."),
            "@F:CliffEdge",
            "@F2:OuterPines",
            "@T:SectGate",
            (WEI, "Nobody feeds on his grave. Nobody. I'll stand guard here every night if I have to. With Dumpling. And tea."),
            foe="void_wraith", foe2="void_wraith", prop="seal", thing="the cliff edge"),
          B("social", "Liu Er at the Gate",
            "Liu Er reaches the top of the nine thousand steps, muddy and shaking and triumphant. Lu Ping lets him faint on his boots.",
            (LU, "He made it! Liu Er! He fainted on my boots! It's tradition! I'm so proud! I've known him since he was in a cage!"),
            "|",
            (LIUER, "I made it. Nine thousand. I counted. I'm going to write to Mother right now. Can I write to Mother right now?"),
            (P, "Welcome to the Azure Cloud, Liu Er. Tomorrow you learn how little you know."),
            (LIUER, "...That's what Elder Mo said to you, isn't it? Wei Tong told me. I'm going to try very hard to be adequate."),
            ),
          B("stage", "Standing Straight",
            "On the last night of the first year without him, you sit at the cliff edge with Elder Mo's manual and straighten your back.",
            "@M:CliffEdge", ">Meditate where Elder Mo's ashes lie",
            (N, "Back straight. Breath long. Your soul and body settle into one shape, like a sword into its sheath. Great Perfection of Soul Transformation."),
            (N, "The wind off the sea of clouds sounds, just for a moment, like someone saying hmph."),
            "@T:SectGate",
            (YUN, "Great Perfection. Next you sever what binds you, and walk in the void. Qing Luan's crane says the isles are tearing open with rifts. She needs you."),
            (YUN, "Mo would say go. So go. Adequately."),
            ),
          B("interlude", "Tea on the Steps",
            "In the morning, Wei Tong pours tea on the hall steps for Elder Mo. Today, twelve new disciples pour with him.",
            (WEI, "Twelve new ones, and me, and a cup for him. Every morning. Train first. Then tea. That's the rule now. His rule. Our rule."),
            "|",
            (HAN, "The void, next. Rifts in the sky. We'll need everything he taught us. Straight backs included."),
            ),
      ]),
]
