"""Volume IV · Nascent Soul — new chapters 32-40 (after "Isles Above the
Clouds", before "The Heart Demon").

The isles close to mortal feet at the full moon, but a nascent soul can walk
the cloud road. Qing Luan teaches soul techniques; Elder Mo raises the Great
Azure Formation's nine pillars; the seven-star mark leads to the first Rungs
of the Patriarch's Ladder; the Zhao clan calls its heir home. Nobody yet knows
the formation's design was altered. Zhao Kang has apologised; he is a friend.
"""

from .dsl import N, P
from .npcs import *  # noqa: F401,F403
from .saga_gen import B, C

CHAPTERS = [
    # ------------------------------------------------------------------ chapter 32
    C("The Cloud Road", "sky_isles",
      "The full moon has closed the Sky Isles to mortal feet, but a paper crane from Qing Luan says a nascent soul can "
      "walk the cloud road anyway. She has things to teach: how to see with the soul, how to step with it, and what "
      "seven red stars really mean.",
      cast=[SAGE, HAN, ZHAO, MO], foes=["celestial_sentinel", "blood_guard", "thunder_wolf"],
      items=["cloud_silk", "star_iron", "thunder_crystal"], props=["stone_stele", "spirit_stone", "seal"],
      foe_names={"thunder_wolf": "storm wolves"},
      things={"stone_stele": "the star chart", "spirit_stone": "the soul crystal"},
      beats=[
          B("orders", "A Crane From the Clouds",
            "A paper crane made of cloud lands on your windowsill and dissolves into Qing Luan's voice.",
            (MO, "A crane made of cloud flew into my tea. It said your name and then it was rain. I'm choosing to be calm about this."),
            (MO, "The star-gazer wants you. Nascent souls can walk the cloud road, apparently. Go. The pillars can wait a week."),
            "@R:sky_isles/CloudGate", (N, "The cloud road holds under a soul's weight, if not a body's. The isles are silent and closed, and utterly beautiful."),
            "@T:CloudGate",
            (SAGE, "You came! Through a closed gate, on a road made of your own soul. Sixty years, and you're my first repeat visitor."),
            (SAGE, "Sit down. You have a soul now. Nobody ever teaches people what to do with it. I'm going to."),
            map="sect"),
          B("cultivate", "Seeing With the Soul",
            "Qing Luan's first lesson: close your eyes and look anyway.",
            (SAGE, "Close your eyes. Now look. Not with those. With the little one inside, with your face and the lotus."),
            "@M:IsleOfWinds", ">See the isle with your soul",
            (N, "Behind your eyelids the isle glows: every pine a green flame, every crystal a blue one. And far off, beneath the clouds, a red smear."),
            "@T:IsleOfWinds",
            (SAGE, "The red smear is the Abyss. You'll always see it now. Sorry. Soul sight doesn't have a way to not look."),
            ),
          B("train", "Stepping With the Soul",
            "The second lesson: let the soul step where the body can't, and the body will follow.",
            (SAGE, "Soul step. Your soul goes first, one pace, and your body follows before it notices. Try it on my sentinels. They're very forgiving."),
            "@F:CelestialRuins", ">Soul-step through the palace sentinels",
            (SAGE, "They're not forgiving at all. I lied. Step faster!"),
            "@T:CloudGate",
            (SAGE, "You're a pace ahead of yourself now. Everyone will think you're very quick. You're just early."),
            foe="celestial_sentinel", count=4),
          B("probe", "Seven Red Stars",
            "Qing Luan brings out her star chart again. The seven red stars have moved, and she doesn't like where.",
            "@R:StarPavilion", (N, "On the jade floor of the pavilion, the seven red stars have shifted since you last saw them. Lower. Closer to the Abyss."),
            "@I:StarPavilion", ">Study the moving red stars",
            (N, "Each red star is tied to a point on the earth below by a thread only soul sight can see. Seven threads. Seven places."),
            "@T:StarPavilion",
            (SAGE, "The Patriarch's Ladder. Last time, he had seven servants, each holding one star. Rungs, they called themselves."),
            (SAGE, "The rungs are held again. Seven someones, somewhere. Each one a step toward the sky for a soul that shouldn't climb."),
            prop="stone_stele", thing="the star chart"),
          B("hunt", "Storm Wolves on the Vein",
            "Storm wolves have found the spirit vein, drawn by the crystals the Blood Moon left behind.",
            "@R:SpiritVein", (N, "Wolves with lightning in their fur prowl the spirit vein, licking the crystals until sparks run down their jaws."),
            "@F:SpiritVein",
            "@G:SpiritVein", ">Gather the crystals the wolves were guarding",
            "@T:CloudGate",
            (SAGE, "Storm wolves. They used to be ordinary. The Blood Moon's crystals changed them. Everything they touch changes."),
            foe="thunder_wolf", item="thunder_crystal", noun="loose crystals"),
          B("social", "The Soul Knows Its Friends",
            "Han Xue and Zhao Kang have followed you up the cloud road. With nascent souls you can see them for the first time.",
            (HAN, "Mo said you'd gone up alone. So we came. Obviously. Stop staring at me like that."),
            (P, "Your soul is a sword, Senior Sister. A very small, very straight sword."),
            (HAN, "...That's the nicest thing anyone's ever said to me. Don't say it again."),
            "|",
            (ZHAO, "What's mine? No. Don't tell me. It's a peacock, isn't it. It's a peacock."),
            (P, "It's a lantern, Zhao Kang. A gold one. With a crack in it that lets the light out."),
            (ZHAO, "...I need a moment. On the other side of this pine. Alone."),
            ),
          B("battle", "Pursuers on the Cloud Road",
            "Blood Guards who couldn't take the cloud road took the jade bridge instead, the long way. They are very tired and very angry.",
            (HAN, "Blood Guards on the bridge. They came the long way round. They look exhausted. Good."),
            "@F:JadeBridge",
            "@F2:IsleOfWinds",
            "@T:CloudGate",
            (SAGE, "They're following your soul now, not your footprints. You shine, lotus child. Everyone can see you coming."),
            foe="blood_guard", foe2="blood_guard"),
          B("delve", "The Soul Crystal",
            "Qing Luan has one more thing: a crystal in the ruins that holds a soul's first memory. She wants you to see hers.",
            "@R:CelestialRuins", (N, "In the ruins, a crystal the height of a man stands in a ring of broken columns, lit from within."),
            "@G:CelestialRuins", ">Gather the fallen crystal shards",
            "@I:CelestialRuins", ">Touch the soul crystal",
            (N, "A girl on these isles, ten thousand years ago, watching a man in red climb the Ascension Stair. Watching seven stars go red behind him."),
            "@F:CelestialRuins", (N, "The crystal's guardians wake, offended that anyone saw."),
            "@T:CloudGate",
            (SAGE, "That was me. That was him. That was the first time. He fell. Your founders pushed. He'll try again."),
            item="star_iron", prop="spirit_stone", thing="the soul crystal", foe="celestial_sentinel"),
          B("interlude", "Back Down the Cloud Road",
            "Qing Luan walks you to the cloud gate. She says she'll watch the red stars. She says to watch the earth.",
            (SAGE, "I'll watch the stars. You watch the earth. Find the seven. Each one you break, the ladder loses a rung."),
            (SAGE, "And lotus child? Take care of that formation of yours. The stars still disagree with it."),
            "|",
            (MO, "You're back! Your body's been sitting in the pavilion for three days. Wei Tong fed it soup. It ate the soup."),
            (MO, "Rungs. Ladders. Stars. Fine. Help me with the pillars and tell me about it while we lift."),
            ),
          B("probe", "Mo Checks a Rune",
            "Elder Mo has started checking the formation's runes one by one, as he promised, before a single pillar goes up.",
            "@R:FormationArray", (N, "Elder Mo sits cross-legged on the plaza with the archive copy spread before him, running a finger down ten thousand runes."),
            "@I:FormationArray", ">Help Elder Mo check the first ring of runes",
            (N, "Rune after rune after rune. All correct. All certified. Your eyes water long before his do."),
            "@T:FormationArray",
            (MO, "Four hundred checked. All correct. Nine thousand six hundred to go. The star-gazer said the stars disagree. So I check."),
            (MO, "Go to bed. I'll do the next four hundred. My eyes are older, but they're more stubborn."),
            map="sect", prop="jade_slip", thing="the archive copy"),
      ]),
    # ------------------------------------------------------------------ chapter 33
    C("Nine Pillars", "sect",
      "The Great Azure Formation stands on nine pillars, and each pillar must be inscribed by a nascent soul. There is "
      "exactly one nascent soul on the mountain young enough to carry stone. Elder Mo builds, Steward Qian weeps, Wei "
      "Tong carries, and the mountain slowly rises into a new shape.",
      cast=[MO, QIAN, WEI, SHI, MAN, JIN, HAN, YAN, LU], foes=["stone_golem", "training_puppet", "demon_cultivator"],
      items=["star_iron", "spirit_stone", "thunder_crystal"], props=["stone_stele", "spirit_stone", "seal"],
      things={"spirit_stone": "the pillar-stone", "stone_stele": "the pillar"},
      beats=[
          B("orders", "The First Pillar-Stone",
            "Elder Mo needs nine pillar-stones cut from the mountain's heart. He wants the first one today.",
            (MO, "Nine pillars. Each one cut from the mountain's heart, below the herb terraces. Then each one inscribed by a nascent soul. That's you."),
            (MO, "The mountain's heart is guarded by old stone. It'll want to know why we're cutting it. Tell it the truth."),
            "@R:HerbGarden", (N, "Below the terraces the mountain opens into a cave of grey-blue stone that hums when you breathe near it."),
            "@T:MoonGate",
            (WEI, "I'm carrying the stones. Elder Mo said I'm the strongest back on the mountain. I've never been so proud of my back."),
            ),
          B("battle", "The Mountain's Old Stone",
            "The mountain's heart has guardians older than the sect. They do not like the sound of chisels.",
            (MO, "The heart's guardians. Older than the sect. Don't break them. Convince them. Firmly."),
            "@F:OuterPines",
            "@F2:TrainingGround",
            "@T:MoonGate",
            (MO, "Convinced. The mountain's letting us cut. It remembers the founder. It remembers the Verdant Lotus too. It liked them better."),
            foe="stone_golem", foe2="stone_golem"),
          B("gather", "Stone by Stone",
            "Nine pillar-stones, each the size of a cart. Wei Tong carries two at once to prove a point.",
            (WEI, "Nine stones! I'll carry two at a time! Watch! No, don't watch! Watch later!"),
            "@G:OuterPines", ">Mark the pillar-stones for cutting",
            "@T:FormationArray",
            (WEI, "Nine stones on the plaza! My back has never been happier. My back is going to hate me tomorrow."),
            item="spirit_stone", noun="pillar-stones"),
          B("social", "The Treasury Weeps",
            "Steward Qian has seen the bill for nine pillars' worth of inscribing ink. He has locked himself in the treasury.",
            (LU, "Steward Qian has locked himself in the treasury. He says he's not coming out until the formation's cheaper. It won't get cheaper."),
            "|",
            (QIAN, "Star-iron ink! Ground phoenix feather! Do you know what that costs? It costs everything! Everything I've ever saved!"),
            (P, "It keeps the mountain safe for ten thousand years, Steward."),
            (QIAN, "...Ten thousand years. That's... that's actually very good value. Fine. I'm coming out. Nobody look at my eyes."),
            ),
          B("cultivate", "Inscribing With the Soul",
            "Each pillar must be inscribed by a nascent soul. Yours steps out of your body, a hand's breadth, and writes.",
            (MO, "Your soul holds the brush. Your body holds the soul. Don't let go of either. If the soul wanders, the rune wanders."),
            "@M:FormationArray", ">Inscribe the first pillar with your soul",
            (N, "Your nascent soul leans out of your chest like someone leaning out of a window, and writes in light on the stone. It takes all day."),
            "@T:FormationArray",
            (MO, "One pillar. Eight to go. You look like a boiled noodle again. It's a good look on you. It means you worked."),
            ),
          B("probe", "A Merchant's Donation",
            "A cart arrives at the gate from Qingshi: star-iron ink, bought at cost, from a merchant who wants no thanks.",
            (LU, "A cart from Qingshi! Ink, lots of ink! There's a note. It says 'at cost'. There's a second note. It says 'no thanks needed'."),
            "@I:SectGate", ">Open Merchant Jin's crates",
            (N, "Twelve jars of star-iron ink, packed in straw. At the bottom, a third note: For the town I nearly sold. Jin Baoshan."),
            "@T:SectGate",
            (JIN, "I came with the cart, to make sure. Not for thanks. For... the feeling. I've started liking the feeling. It's dreadful."),
            prop="treasure_chest", thing="Merchant Jin's crates"),
          B("defend", "Night Raid on the Pillars",
            "Someone tries to smash the first pillar in the night. Whoever it is knows exactly where it stands.",
            (HAN, "Someone went for the first pillar. With a hammer. They knew exactly which one was finished."),
            "@I:FormationArray", ">Ward the finished pillar",
            (N, "Your ward flares blue over the pillar just as shapes drop from the plaza wall."),
            "@F:FormationArray",
            "@F2:SectGate",
            "@T:SectGate",
            (HAN, "Blood Moon again. On our mountain, again. How are they still getting in?"),
            (HAN, "Someone's leaving a door open. I'm going to find out who, and close them."),
            foe="demon_cultivator", foe2="demon_cultivator", prop="seal", thing="the pillar"),
          B("social", "The Open Door",
            "Xiao Shi remembers something: in the Abyss, the guards talked about a way into the sect that didn't need the gate.",
            (SHI, "In the cages, the guards used to laugh about 'the back door of heaven'. A way into the sect. I thought it was a joke."),
            (SHI, "Below the cliff edge, they said. Where the clouds are thickest."),
            "|",
            (HAN, "Below the cliff. There's an old path down there, from before the sect had walls. Nobody uses it. Nobody watches it."),
            (HAN, "Well. Somebody uses it."),
            ),
          B("chase", "The Back Door of Heaven",
            "Below the cliff edge, an old path winds down into the clouds. It has been swept recently.",
            "@R:CliffEdge", (N, "Beneath the cliff, hidden by cloud, a path of old steps winds down the mountain. The moss on them has been scraped away by feet."),
            "@F:OuterPines", (N, "At the path's foot, where it meets the outer pines, masked figures are waiting for their next climb."),
            "@R:OuterPines", (N, "At the bottom, the path ends at a rusted gate in the outer wall. The lock is new. Very new."),
            "@T:SectGate",
            (YAN, "Thunder Peak will guard the back door. All of Thunder Peak. Nobody gets past us. We're very loud and very awake."),
            foe="demon_cultivator"),
          B("interlude", "Eight More Pillars",
            "With the back door shut, the work goes faster. Elder Mo checks runes by night and builds by day, and doesn't sleep.",
            (MO, "Eight pillars to go. I check runes at night, I build by day. Sleep is a habit. I've broken worse habits."),
            (MO, "Four thousand runes checked. All correct. All certified. I'm beginning to think the star-gazer is wrong. I'll keep checking."),
            "|",
            (MAN, "Elder Mo hasn't slept in four days. I left soup outside his door. He ate the soup and left a note. 'Adequate soup.'"),
            (MAN, "I'm framing the note."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 34
    C("The Seven-Star Crates", "qingshi_town",
      "Crates stamped with seven stars have been passing through Qingshi's docks. Merchant Jin, who is now honest and "
      "hates it, has noticed. The crates lead to a warehouse nobody owns, and to a pale man who calls himself the First "
      "Rung of the Patriarch's Ladder.",
      cast=[JIN, DU, PAN, FANG, TIE, HAN, ZHAO, LIUER], foes=["blood_guard", "demon_cultivator", "rogue_cultivator"],
      items=["thunder_crystal", "letter", "demon_core"], props=["treasure_chest", "jade_slip", "seal"],
      boss=("rung_deacon", "Luo Hui, the First Rung", "Warehouse"),
      things={"treasure_chest": "the seven-star crate"},
      beats=[
          B("orders", "Honest Merchant, Worried Merchant",
            "Merchant Jin writes to the sect in his own hand: crates with seven stars, passing his docks, paid in silver he won't take.",
            "@R:qingshi_town/Warehouse", (N, "The guild warehouse is neat and honest now, which makes the three seven-starred crates in the corner look very out of place."),
            "@T:Warehouse",
            (JIN, "Seven stars on the lids. A man paid me in silver to store them. I refused the silver. He left the crates anyway."),
            (JIN, "Honesty is terrifying. Nobody tells you. Please take them away."),
            map="qingshi_town"),
          B("probe", "What the Crates Hold",
            "The crates are heavier than crystals should be, and one of them is humming a tune.",
            "@I:Warehouse", ">Pry open a seven-star crate",
            (N, "Thunder crystals, packed in blood-lotus straw. And at the bottom, sewn into the lining, a letter signed with ash."),
            "@R:Warehouse", (N, "The letter reads: first rung holds. Deliver to the rim at the new moon. Luo Hui, of the Ladder."),
            "@T:MainStreet",
            (HAN, "Luo Hui. First rung. Qing Luan's seven. One of them is in this town, or was."),
            (HAN, "The new moon is in three days. So we wait, and we watch the docks."),
            prop="treasure_chest", thing="the seven-star crate"),
          B("social", "Watchers Watching",
            "Qingshi's watchers have been busy. Old Pan, Madam Fang and Constable Du all saw the pale man. None of them liked him.",
            (PAN, "Pale fellow. Came in on a raft, not my ferry. Didn't pay a fare. Didn't cast a reflection in the water. I noticed that."),
            "|",
            (FANG, "He took a room. Paid in old coins. Never ate. Left ash in the bed. Ash! I had to burn the sheets!"),
            "|",
            (DU, "I followed him to the old guild warehouse by the river. The one nobody owns. He went in. He didn't come out. I wrote it down."),
            ),
          B("chase", "The Warehouse Nobody Owns",
            "The old guild warehouse by the river has no owner, no door, and fresh footprints in ash on its floor.",
            "@R:Riverside", (N, "The old warehouse leans over the river on rotting stilts. Ash footprints lead in, and none lead out."),
            "@F:BackAlley", (N, "The alley behind it is guarded by men in crimson who have been told to let no one near the river."),
            "@R:Warehouse", (N, "Inside: nothing. Empty. And yet the ash footprints stop in the middle of the floor, as if someone went straight down."),
            "@T:MainStreet",
            (ZHAO, "Elder Mo sent me. He said you'd need someone to complain at. I see you've found a haunted warehouse. Of course you have."),
            foe="blood_guard"),
          B("hunt", "Under the Floorboards",
            "Beneath the ash footprints, a trapdoor. Beneath the trapdoor, a tunnel toward the graves. The Blood Moon loves a tunnel.",
            "@R:Warehouse", (N, "The trapdoor opens on stairs. Down there it smells of river mud and burning, and of blood lotus."),
            "@F:Graveyard", (N, "The tunnel comes up among the hill graves, where Blood Guards are loading crates onto a cart."),
            "@G:Graveyard", ">Seize the crates from the cart",
            "@T:MainStreet",
            (TIE, "Seven stars on those crates. I've seen them before. On the black gate, back when the Blood Moon had my family. Same stars."),
            (TIE, "Whatever this is, it's big. They were scared of it. People like that are never scared of anything."),
            foe="blood_guard", item="thunder_crystal", noun="seized crates"),
          B("defend", "The New Moon",
            "On the night of the new moon, the pale man comes back for his crates.",
            (DU, "New moon. Every watcher's out. The town's asleep, or pretending to be. Old Pan's on the river with a lantern."),
            "@I:WatchTower", ">Signal the watchers from the tower",
            (N, "You swing a lantern twice. Across the dark town, lanterns answer: river, inn, yamen, gate. Qingshi is awake."),
            "@F:Riverside", (N, "Rafts slide out of the dark. Blood Guards, and among them a pale figure who leaves ash on the water."),
            "@F2:MainStreet",
            "@T:MainStreet",
            (DU, "He's gone to the warehouse. The one with the crates. Alone. He wants them badly enough to come himself."),
            foe="blood_guard", foe2="demon_cultivator", prop="seal", thing="the signal lantern"),
          B("boss", "Luo Hui, the First Rung",
            "In the guild warehouse, among his crates, stands the First Rung of the Patriarch's Ladder. He is made mostly of patience and ash.",
            "@R:Warehouse", (N, "A pale man sits on a seven-starred crate, turning a handful of ash in his fingers. He looks up and smiles with grey teeth."),
            "@X",
            (RUNG1, "The heir. The Patriarch said you would come. He says a lot of things about you. He's very fond of you, in his way."),
            (RUNG1, "I am Luo Hui, the First Rung. One rung is nothing. Seven is a road to heaven. Shall we see if you can climb?"),
            "@R:Warehouse", (N, "Luo Hui staggers, laughs, and comes apart into ash that blows out through the cracks in the warehouse wall. His crates stay behind."),
            "@T:MainStreet",
            (HAN, "He ran. Like smoke. But he left his crates, and his crates are the point. One rung, shaken. Six to go."),
            ),
          B("social", "Liu Er Wants to Help",
            "Liu Er, now fourteen and very tall, followed the fight from a rooftop and would like to become a cultivator immediately.",
            (LIUER, "I saw everything! From the roof! The pale man turned into ash! I want to learn that! Not the ash part. The fighting part."),
            (LIUER, "Can I climb the nine thousand steps? Mother says I have to ask you. She says you'll say no."),
            (P, "When you're sixteen. Train with Constable Du until then. And ask your mother again."),
            (LIUER, "Sixteen! That's forever! ...Fine. Constable Du. I'll be the best constable's apprentice there's ever been."),
            ),
          B("stage", "Ash on the River",
            "Luo Hui's ash drifts on the river. You sit on the dock and let the fight settle into your nascent soul.",
            "@M:Temple", ">Settle your soul in the town temple",
            (N, "Your nascent soul turns the fight over like a stone in its hands, and learns from it, and grows. Middle stage of Nascent Soul."),
            (N, "In soul sight, the red thread from Qingshi to the sky has thinned. Not broken. Thinner."),
            "@T:MainStreet",
            (ZHAO, "One rung shaken, six to go, and you're meditating in a temple like an old monk. You should celebrate. With noodles. My treat."),
            (ZHAO, "Don't look at me like that. I've apologised for two years of being awful. Now I'm being nice. It's very tiring."),
            ),
          B("interlude", "Crates Up the Mountain",
            "The seized crates go up the mountain to Elder Bai. Old Pan ferries them across the river himself, at no fare.",
            (PAN, "No fare. For crates that nearly helped a monster climb to heaven, no fare. Mind the third plank."),
            "|",
            (FANG, "Tell the Sect Master Qingshi says hello. And that we burned the pale man's sheets. Twice. For good measure."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 35
    C("The Soul Fog", "bamboo_forest",
      "A grey fog has settled on the Whispering Bamboo, and everything it touches forgets itself: birds forget to sing, "
      "streams forget to run, and the hermit has forgotten your name. Only a soul that can see can find what is feeding "
      "on the forest's memories.",
      cast=[LAN, HAN, ZHAO, HUA, SHI], foes=["void_wraith", "spirit_wolf", "stone_golem"],
      items=["spirit_herb", "rune_fragment", "void_shard"], props=["seal", "stone_stele", "treasure_chest"],
      foe_names={"void_wraith": "fog wraiths", "spirit_wolf": "fog-lost wolves"},
      things={"seal": "the fog's anchor-stone"},
      beats=[
          B("orders", "The Hermit Forgets",
            "A crane arrives from the hermit. It is blank. The hermit has forgotten how to write.",
            (HUA, "A blank crane from the hermit. Blank. He's never sent a blank crane. He wouldn't know how."),
            (HUA, "Go. Take Xiao Shi, he knows how to be patient with confused people. And take this. Smelling salts. For whoever needs them."),
            "@R:bamboo_forest/ForestPath", (N, "The forest is grey and silent. Birds sit on branches, staring at nothing. The stream is not moving."),
            "@T:HermitHut",
            (LAN, "Hello. Do I know you? You look like someone who drinks my tea. I have tea. I think. What is tea?"),
            map="sect"),
          B("cultivate", "Soul Sight in the Fog",
            "With ordinary eyes the fog is only grey. With soul sight it has threads, and the threads are pulling.",
            "@M:Clearing", ">Look at the fog with your soul",
            (N, "In soul sight the fog is a web, and every strand runs to something living, sipping at it. Every strand also runs north, toward the ruins."),
            "@T:Clearing",
            (SHI, "I can't see the threads. But the hermit keeps asking me my name. I keep telling him. It seems to help, a bit."),
            (SHI, "In the cages, people forgot things too. We told each other our names every morning. It's a good habit."),
            ),
          B("battle", "Fog With Hands",
            "The fog has thickened into shapes that walk, and the shapes have hands.",
            (HAN, "The fog's standing up. It's got hands. I really didn't need the fog to have hands."),
            "@F:ForestPath",
            "@F2:HerbGrove",
            "@R:Stream", (N, "Where the wraiths fall, the fog thins, and a bird somewhere remembers one note of its song."),
            foe="void_wraith", foe2="void_wraith"),
          B("social", "Telling the Hermit Who He Is",
            "The hermit has forgotten three hundred years. Somebody has to tell him who he is. It's harder than it sounds.",
            (P, "Your name is Lan Jue. You were the last disciple of the Verdant Lotus. You ran, and then you stopped running."),
            (LAN, "Ran? I don't run. My knees are terrible. Did I really run? From what?"),
            (P, "From a flood. From a song. You went back and sang it. You were very brave."),
            (LAN, "...I think I remember a song. Tell me again. The part where I was brave. I like that part."),
            "|",
            (SHI, "Every hour. We'll tell him every hour until the fog's gone. That's what we did in the cages. It works if you keep doing it."),
            ),
          B("hunt", "Wolves Who Forgot",
            "The forest's wolves have forgotten they were ever tame, or wild, or anything. They only remember hunger.",
            "@R:WolfDen", (N, "Wolves stand in the fog outside the den, swaying, eyes blank. When you step closer, they remember one thing: teeth."),
            "@F:WolfDen",
            "@G:WolfDen", ">Gather the fog-shards the wolves shed",
            "@T:Clearing",
            (ZHAO, "Fog shards. They taste of nothing. I licked one. Don't ask. I've been told I have a curious tongue."),
            foe="spirit_wolf", item="void_shard", noun="fog shards"),
          B("delve", "The Anchor at the Ruins",
            "The fog's threads all run to the ruins gate, where someone has planted a stone that drinks memories.",
            "@R:RuinsGate", (N, "At the ruins gate stands a black stone the fog pours out of like steam from a kettle. Seven dots are carved on it."),
            "@G:RuinsGate", ">Chip the seven-dot runes from the stone",
            "@I:RuinsGate", ">Break the fog's anchor-stone",
            (N, "The stone cracks. The fog screams without a mouth, and pulls back into the crack, and then there is only the forest, and birds."),
            "@F:RuinsInner", (N, "The last of the fog-wraiths boil out of the courtyard, desperate, grabbing at anything that still remembers."),
            "@R:AncientShrine", (N, "The shrine is green again. From somewhere behind you comes the sound of a kettle, and an old man cursing it."),
            item="rune_fragment", foe="void_wraith"),
          B("social", "Tea, Remembered",
            "The hermit remembers everything, all at once, including that he has run out of tea.",
            (LAN, "I remember. All of it. Three hundred years at once. It's very loud. Also I've run out of tea. That's unforgivable."),
            (LAN, "You told me I was brave. I heard it, through the fog. Nobody's ever told me that. I'm going to remember it on purpose."),
            "|",
            (SHI, "He remembered my name before he remembered his own. He said it first. Xiao Shi. I'm going to go and cry by the stream."),
            ),
          B("probe", "Seven Dots on the Stone",
            "The anchor-stone's seven dots match the crates. The Ladder didn't just want the forest's memories. It wanted a map.",
            "@R:RuinsGate", (N, "In the broken anchor-stone's heart lies a slip of jade, full of stolen memory: every path, every stream, every door in the forest."),
            "@I:RuinsGate", ">Read the stolen memory-slip",
            (N, "The ruins. The archive. The spring. The path to the sect's back door. The Ladder is mapping everything the Verdant Lotus ever touched."),
            "@T:Clearing",
            (HAN, "They wanted a map of the Verdant Lotus. Of everything that's yours. Why would a ladder need to know where you've been?"),
            (P, "Maybe to know where I'll go."),
            prop="jade_slip", thing="the memory-slip"),
          B("cultivate", "Giving Back the Forest's Memories",
            "The memory-slip holds the forest's stolen memories. The hermit says they should go back where they came from.",
            (LAN, "Give them back. Every birdsong, every stream's direction. Open the slip at the spring and let them go home."),
            "@M:SpiritSpring", ">Release the forest's memories at the spring",
            (N, "Memories pour out of the slip like fireflies: a stream remembering downhill, a bird remembering its song, an old man remembering his teacher's voice."),
            "@T:Clearing",
            (LAN, "My teacher's voice. It was in there. I'd forgotten it long before the fog. Thank you for giving back more than was taken."),
            ),
          B("interlude", "What the Ladder Wants",
            "On the way home, Han Xue says what you are both thinking: the Ladder is studying you.",
            (HAN, "The first rung tested you. The fog mapped you. The assassin in Qingshi measured you. Someone is studying you."),
            (HAN, "A ladder for one soul to climb. I don't like where my thoughts go when I put those together."),
            (P, "Neither do I."),
            (HAN, "Then we both keep thinking. Separately. Loudly. And we tell Elder Mo, because he's building a thing that touches the sky."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 36
    C("The Zhao Clan's Summons", "sect",
      "Zhao Tianlu, ancestor of the Zhao clan, climbs the nine thousand steps to bring his great-grandson home: the clan "
      "needs an heir, not a sect disciple who picks fights with ladders. Zhao Kang must choose, and he has never been "
      "good at choosing anything but arguments.",
      cast=[TIANLU, ZHAO, YUN, HAN, WEI, MO, LU], foes=["sparring_disciple", "stone_golem", "demon_cultivator"],
      items=["spirit_stone", "letter", "jade_slip"], props=["stone_stele", "treasure_chest", "seal"],
      foe_names={"sparring_disciple": "Zhao clan guards"},
      things={"stone_stele": "Zhao Ming's stone"},
      beats=[
          B("orders", "A Palanquin on the Steps",
            "A gold palanquin is coming up the nine thousand steps, carried by eight very tired men.",
            (LU, "A gold palanquin! On the steps! Eight bearers! They've been climbing since yesterday! One of them is crying!"),
            "@R:SectGate", (N, "The palanquin sets down at the gate. The curtain parts. The ancestor of the Zhao clan steps out, frowning at the height of the steps."),
            "@T:SectGate",
            (TIANLU, "I have come for my great-grandson. The clan requires its heir. He has played at cultivation long enough."),
            (TIANLU, "Where is he? Hiding, no doubt. He hides from me the way his father did. It's a family tradition."),
            ),
          B("social", "Zhao Kang Hides",
            "Zhao Kang is, in fact, hiding. In the pagoda. Behind the turtle soup books.",
            (ZHAO, "I'm not hiding. I'm researching. Turtle soup. It's fascinating. Go away."),
            (ZHAO, "He wants me to go home and marry a merchant's daughter and count gold. I'm good at counting gold. I hate it."),
            (P, "Then tell him."),
            (ZHAO, "Tell him? He's a hundred and twelve. He's never been told anything. It would kill him. Or me. Probably me."),
            "|",
            (BAI, "He's been behind my turtle soup shelf for three hours. He's reorganised it. Alphabetically. I'm furious. It's very well done."),
            ),
          B("probe", "Zhao Ming's Stone",
            "In the Zhao clan hall, Zhao Kang's great-grandfather says, there is a stone for his dead brother. The ancestor carries a copy.",
            (TIANLU, "Zhao Ming's stone. I had it copied, small, to carry. First out of the grotto, ten years ago. Dead on a mission two years later."),
            (TIANLU, "I will not lose another heir to this mountain. Tell him that. He won't hear it from me."),
            "@I:FormationArray", ">Look at Zhao Ming's stone",
            (N, "The small stone is carved: Zhao Ming, first out of the Moonlit Grotto. Beneath it, newer, in a clumsy hand: and his brother, first out after."),
            "@T:SectGate",
            (TIANLU, "Someone carved that line last year. A servant, I assumed. It's his hand, isn't it. He's been visiting home. Secretly."),
            prop="stone_stele", thing="Zhao Ming's stone"),
          B("duel", "The Clan's Test",
            "The Zhao ancestor proposes a test: if his guards can't take Zhao Kang home by force, the boy can stay. He means it kindly. Probably.",
            (TIANLU, "The old way. My guards will escort him home. If he can refuse them, he can refuse me. That is the Zhao clan's test."),
            (ZHAO, "Of course it is. Everything's a test. Will you stand with me? Not for me. Beside me. There's a difference."),
            "@F:TrainingGround", ">Stand beside Zhao Kang against the clan guards",
            (ZHAO, "Don't hurt them! They carried me on their shoulders when I was four! Hurt them a little!"),
            "@T:SectGate",
            (TIANLU, "Refused. By force. With a friend. Hm. His brother did the same, once, with a different friend."),
            foe="sparring_disciple", count=4),
          B("social", "What Zhao Kang Says",
            "Zhao Kang finally says it: to his great-grandfather, in front of the whole sect, with his voice shaking.",
            (ZHAO, "I'm not coming home. Not because I don't love the clan. Because Ming would have stayed, and I'm finishing what he started."),
            (ZHAO, "And because I have a friend here who's going to do something stupid and heroic, and somebody has to complain about it."),
            "|",
            (TIANLU, "...Your brother said almost the same words. Minus the complaining. You're more honest than he was."),
            (TIANLU, "Stay, then. The clan will manage. The clan managed before gold. It'll manage without you. Write to me. Monthly."),
            ),
          B("gather", "Gifts From the Clan",
            "The Zhao ancestor does not leave empty-handed or leave anyone else empty-handed. The palanquin was full of gifts.",
            (TIANLU, "The palanquin was full of gifts in case he came home. Take them. Spirit stones for the formation. Gold for the kitchen."),
            "@G:SectGate", ">Unload the Zhao clan's gifts",
            "@T:SectGate",
            (QIAN, "Two hundred spirit stones. From the Zhao clan. For free. I think I'm going to faint. Somebody catch me. Anyone."),
            item="spirit_stone", noun="clan gifts"),
          B("battle", "Uninvited Escort",
            "The palanquin is ambushed on its way down the steps. Somebody wants the Zhao clan to blame the Azure Cloud.",
            (WEI, "The palanquin's under attack! On the steps! Masked men! The bearers are throwing gold at them! It's not working!"),
            "@F:SectGate",
            "@F2:OuterPines",
            "@T:SectGate",
            (TIANLU, "Blood Moon. Trying to kill me on your steps, so the clan would blame you. They don't know the clan. We blame precisely."),
            (TIANLU, "The Zhao clan will stand with the Azure Cloud when you go after them. That's not gratitude. It's accounting."),
            foe="demon_cultivator", foe2="demon_cultivator"),
          B("social", "Monthly Letters",
            "Zhao Kang writes his first monthly letter home before the palanquin has even reached the bottom of the steps.",
            (ZHAO, "Dear Great-Grandfather. It's been an hour. I'm fine. The food is terrible. Wei Tong made dumplings. They were fine. Love, Kang."),
            (ZHAO, "Too much? It's too much. I've never written 'love' to him. He's going to die of shock."),
            (P, "Send it."),
            (ZHAO, "...Fine. If he dies, it's your fault. I'll carve it on your stone."),
            ),
          B("cultivate", "Brothers' Stone",
            "Zhao Kang asks you to sit with him at the cliff edge where he used to burn incense for his brother.",
            (ZHAO, "I burned incense here for Ming. Every year. You found me here, once, and asked who assigned his mission. Remember?"),
            "@M:CliffEdge", ">Burn incense with Zhao Kang at the cliff",
            (N, "Two sticks of incense, side by side, their smoke twisting together over the sea of clouds."),
            "@T:SectGate",
            (ZHAO, "Gu assigned it. He's in the Abyss. When we go after him, I'm going to ask him why. Just ask. I think that's what Ming would do."),
            ),
          B("interlude", "Accounting",
            "The Sect Master notes that in one year the Azure Cloud has gained the Iron Scale, the Zhao clan and a very honest merchant as allies.",
            (YUN, "The Iron Scale. The Zhao clan. Qingshi's yamen and its merchants. A year ago we had none of them. You collect allies like Wei Tong collects buns."),
            (YUN, "The Blood Moon keeps trying to set us against each other, and keeps pushing us together instead. Someone there is very bad at accounting."),
            "|",
            (MO, "Pillar six is up. Seven thousand runes checked. All correct. I'm starting to hate the word correct. It sounds smug."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 37
    C("Duel Above the Clouds", "sky_isles",
      "Qing Luan sends word that someone is poisoning the spirit vein with rust. You walk the cloud road again and find "
      "the Second Rung: a monk in rotting robes who prays over the crystals as they die. He is very polite, and he wants "
      "to see how strong your soul has grown.",
      cast=[SAGE, HAN, ZHAO, YAN], foes=["celestial_sentinel", "thunder_wolf", "blood_guard"],
      items=["thunder_crystal", "star_iron", "void_shard"], props=["spirit_stone", "stone_stele", "seal"],
      boss=("rung_deacon", "Tie Shan, the Rust Monk", "SpiritVein"),
      foe_names={"thunder_wolf": "storm wolves"},
      things={"spirit_stone": "the rusting crystals"},
      beats=[
          B("orders", "Rust on the Vein",
            "Qing Luan's cloud crane is spotted with rust. It dissolves into her voice, and her voice is worried.",
            (MO, "Another crane. It's rusty. How does a cloud rust? Don't answer. Go and find out."),
            "@R:sky_isles/CloudGate", (N, "On the cloud gate, rust creeps along the stone in orange veins, like something slowly bleeding."),
            "@T:CloudGate",
            (SAGE, "The vein is rusting. Crystals that were blue for ten thousand years are turning orange. Someone is praying over them."),
            (SAGE, "Praying. With a rosary made of rusted nails. I watched from my pavilion. I don't usually feel sick. I felt sick."),
            map="sect"),
          B("hunt", "Storm Wolves in Rust",
            "The storm wolves on the spirit vein are rusting too. They are in pain, and pain makes them fast.",
            "@R:SpiritVein", (N, "Storm wolves limp across the vein, rust in their fur where lightning used to be. They snap at anything that moves."),
            "@F:SpiritVein",
            "@G:SpiritVein", ">Gather the crystals that haven't rusted yet",
            "@T:CloudGate",
            (HAN, "It's spreading. Every crystal the rust touches dies. If it reaches the heart of the vein, the isles will fall."),
            foe="thunder_wolf", item="thunder_crystal", noun="unrusted crystals"),
          B("probe", "Prayer Beads of Nails",
            "At the vein's heart a string of rusted nails lies coiled on a crystal like a sleeping snake.",
            "@R:SpiritVein", (N, "A rosary of rusted nails lies on the largest crystal. Where it touches, the crystal is orange and crumbling."),
            "@I:SpiritVein", ">Lift the nail rosary from the crystal",
            (N, "The rosary is warm. Somewhere on the isles, someone feels it lifted, and stops praying."),
            "@T:CloudGate",
            (SAGE, "He felt that. The Rust Monk. Tie Shan. He was a monk once, in a temple that burned. Now he's the Second Rung."),
            (SAGE, "He'll come for his beads. He'll be polite about it. That's the worst part."),
            prop="spirit_stone", thing="the rusting crystal"),
          B("battle", "The Monk's Acolytes",
            "The Rust Monk's acolytes come first, bowing before they strike.",
            (ZHAO, "They bowed. Then they tried to stab me. I don't know how to feel. I bowed back. Then I stabbed them."),
            "@F:JadeBridge",
            "@F2:IsleOfWinds",
            "@T:CloudGate",
            (YAN, "Thunder Peak came up the cloud road! My soul is very small, but it's very loud! Where's the monk?"),
            foe="blood_guard", foe2="blood_guard"),
          B("cultivate", "Soul Against Rust",
            "Qing Luan says rust eats iron, not souls. If you can hold your soul outside your body, the rust can't touch it.",
            (SAGE, "Rust eats iron. Iron is body. Soul is not iron. Step your soul out, a hand's breadth, and let the rust find nothing to bite."),
            "@M:IsleOfWinds", ">Hold your soul outside your body",
            (N, "Your soul steps out a hand's breadth and stays there, shining. The wind of the isle blows through it like light through a window."),
            "@T:CloudGate",
            (SAGE, "Good. Now fight like that. It's exhausting. That's why nobody does it. You're going to do it anyway."),
            ),
          B("boss", "Tie Shan, the Rust Monk",
            "The Second Rung comes for his beads. He is huge, polite, and rotting, and he bows before every blow.",
            "@R:SpiritVein", (N, "A huge monk in rotting orange robes kneels at the vein's heart, hands pressed together. Rust flakes from his fingers like snow."),
            "@X",
            (RUNG2, "Tie Shan, Second Rung. Forgive me. All iron rusts. All vows rust. Yours will too. Let me show you."),
            (P, "My soul isn't iron, monk."),
            (RUNG2, "Ah. Luo Hui said you were clever. Pray with me, then. It won't help."),
            "@R:SpiritVein", (N, "The monk bows one last time and crumbles into a heap of rust that the wind carries off the edge of the isle. His laughter goes with it."),
            "@T:CloudGate",
            (SAGE, "He's not dead. Rungs don't die easily; they're tied to their stars. But his star dimmed. I saw it from here."),
            ),
          B("gather", "Healing the Vein",
            "The vein can heal if the rusted crystals are cleared away. Qing Luan wants every one gone before it spreads.",
            (SAGE, "Clear away the dead crystals. The vein will grow new ones. It's patient. It's ten thousand years patient."),
            "@G:SpiritVein", ">Clear the rusted crystals from the vein",
            "@T:CloudGate",
            (SAGE, "Blue again. Look at that. Ten thousand years, and it still manages to surprise me."),
            item="void_shard", noun="rusted crystals"),
          B("stage", "The Soul Grows Tall",
            "After holding your soul outside your body through a whole fight, it doesn't want to go back in. It wants to grow.",
            (SAGE, "Your soul is bigger than it was this morning. That happens when you make it do something stupid. Sit. Let it settle."),
            "@M:CloudGate", ">Let your nascent soul settle at the cloud gate",
            (N, "Your nascent soul settles back into your body like a cat into a basket, turning twice. It is taller. Late stage of Nascent Soul."),
            "@T:CloudGate",
            (HAN, "You glowed. The whole fight. Like a lantern with a person in it. Don't do that again without warning me."),
            ),
          B("social", "Two Rungs Shaken",
            "Two Rungs shaken, neither broken. Qing Luan's chart shows five red stars bright, and two dim.",
            (SAGE, "Two dim. Five bright. The Ladder can't climb with dim rungs. But dim isn't broken. They'll heal, like the vein."),
            (SAGE, "You need to break them, not shake them. For that you'll need to be stronger than a nascent soul. Much stronger."),
            "|",
            (ZHAO, "Stronger than a nascent soul. We only just got here. Is there always a next stage? Doesn't it ever end?"),
            (P, "Qing Luan says it ends at the top of a staircase."),
            (ZHAO, "Of course it does. Everything ends with stairs. I hate stairs."),
            ),
          B("interlude", "Back to the Pillars",
            "Back at the sect, Elder Mo has raised eight pillars and checked nine thousand runes. He is thinner, and very pleased with himself.",
            (MO, "Eight pillars. Nine thousand runes. All correct. One ring left. Then we light it, and the sect is safe for ten thousand years."),
            (MO, "The star-gazer can disagree all she likes. I've checked. Twice."),
            "|",
            (WEI, "He's so thin. I've been making him soup. He says 'adequate soup' and eats three bowls. He's going to be fine. Right?"),
            map="sect"),
      ]),
    # ------------------------------------------------------------------ chapter 38
    C("What the Stars Remember", "sky_isles",
      "Qing Luan asks you up one last time before the isles close for good. She wants to show you the night Xue Wuji "
      "first climbed, and the night the founders pulled him down. The palace sentinels would prefer she didn't.",
      cast=[SAGE, HAN, ZHAO], foes=["celestial_sentinel", "thunder_wolf", "void_wraith"],
      items=["star_iron", "phoenix_feather", "cloud_silk"], props=["stone_stele", "spirit_stone", "seal"],
      foe_names={"void_wraith": "star-shadows", "thunder_wolf": "storm wolves"},
      things={"stone_stele": "the palace mural", "spirit_stone": "the memory crystal"},
      beats=[
          B("orders", "One Last Visit",
            "The isles are going to close to souls too, soon. Qing Luan wants to show you one more thing before they do.",
            "@R:sky_isles/CloudGate", (N, "The cloud road is thinner than last time, almost transparent. Below, the sea of clouds is very far away."),
            "@T:CloudGate",
            (SAGE, "The isles are closing, even to souls, for another sixty years. I want you to see something first. Something I saw."),
            (SAGE, "The palace doesn't like visitors to see it. The palace is going to have to live with that."),
            map="sect"),
          B("battle", "The Palace Says No",
            "The palace sentinels bar the way. Qing Luan tells them to move. They don't.",
            (SAGE, "Move. I was a sage of this palace when your stone was still gravel. Move! ...Fine. Hit them."),
            "@F:CelestialRuins",
            "@F2:CelestialRuins",
            "@T:CloudGate",
            (SAGE, "They'll reform by morning. They always do. They're very loyal and very stupid. I used to find it charming."),
            foe="celestial_sentinel", foe2="celestial_sentinel"),
          B("probe", "The Mural of the First Climb",
            "Inside the palace, a mural shows a man in red climbing the stair, seven stars behind him, and two sects pulling at his robe.",
            "@R:CelestialRuins", (N, "A mural on a broken wall: a man in red on a stair of light, seven red stars behind him, two figures at his heels, one blue, one green."),
            "@I:CelestialRuins", ">Study the palace mural",
            (N, "The figure in green holds a lotus. The figure in blue holds a sword. Both are pulling. Both are falling with him."),
            "@T:CelestialRuins",
            (SAGE, "Your founders. They pulled him down, and fell with him, into the earth. The Abyss is the hole they made landing."),
            (SAGE, "The blue one lived. The green one... there's a reason the Verdant Lotus gave its elders to the seal. They'd already lost their founder."),
            prop="stone_stele", thing="the palace mural"),
          B("social", "Qing Luan Remembers",
            "Qing Luan tells you what she was, before she was a memory.",
            (SAGE, "I was the palace's youngest sage. I watched him climb. I didn't stop him. I didn't know I could."),
            (SAGE, "When he fell, the palace fell with him. I stayed. As a memory. Watching the stair. Waiting for someone to do what I didn't."),
            (P, "You're doing it now. You're teaching me."),
            (SAGE, "...Yes. I suppose I am. Ten thousand years late, but teaching. That's something."),
            ),
          B("hunt", "Star-Shadows",
            "Where the red stars shine on the isles at night, their light casts shadows that walk.",
            "@R:ImmortalGarden", (N, "Under the blossom trees, shadows move without anything to cast them. The red stars are directly overhead."),
            "@F:ImmortalGarden",
            "@G:ImmortalGarden", ">Gather phoenix feathers the shadows scattered",
            "@T:CloudGate",
            (ZHAO, "Shadows with nothing to cast them. I've fought wolves, stone men, monks and fog. Now shadows. I want a holiday."),
            foe="void_wraith", item="phoenix_feather", noun="scattered feathers"),
          B("delve", "The Memory Crystal",
            "Qing Luan leads you to a crystal where the isles keep their oldest memory: the night of the fall.",
            "@R:CelestialRuins", (N, "Deep in the ruins, a crystal hangs in the air, turning slowly. Inside it, very small, a man in red is falling forever."),
            "@G:CelestialRuins", ">Gather star iron from the crystal's base",
            "@I:CelestialRuins", ">Touch the memory of the fall",
            (N, "You hear him as he falls. Not screaming. Laughing. Next time, he says, I'll bring a body heaven can't refuse."),
            "@F:SerpentLair", (N, "The crystal's keepers stir in the serpent's old isle, disturbed by the memory, and come to see who woke it."),
            "@R:CloudGate", (N, "At the cloud gate, the wind is cold. A body heaven can't refuse. The words sit in your chest like a stone."),
            item="star_iron", foe="celestial_sentinel", prop="spirit_stone", thing="the memory crystal"),
          B("social", "A Body Heaven Can't Refuse",
            "Han Xue heard it too. So did Zhao Kang. Nobody wants to say what everyone is thinking.",
            (HAN, "A body heaven can't refuse. A clean one. With the Verdant Lotus in it. I'm going to say it, because nobody else will."),
            (HAN, "He wants you. Not to kill. To wear."),
            "|",
            (ZHAO, "Then he'll have to get through me. And her. And the entire Zhao clan, who've recently become very emotional about you."),
            (ZHAO, "Also I'll complain. Loudly. Forever. Nobody wants to wear a body that has me complaining at it."),
            ),
          B("cultivate", "Watching the Stair",
            "Before the isles close, Qing Luan asks you to sit with her and watch the Ascension Stair, the way she has for ten thousand years.",
            (SAGE, "Sit with me. Watch the stair. I've done it alone for ten thousand years. Tonight I'd like company."),
            "@M:IsleOfWinds", ">Watch the Ascension Stair with Qing Luan",
            (N, "The stair climbs into cloud, faint, made of light. It is not for you. Not yet. But for the first time, it looks back."),
            "@T:CloudGate",
            (SAGE, "It looked at you. I saw it. Ten thousand years and it has never looked at anyone. Heaven is starting to notice."),
            ),
          B("gather", "Gifts for the Formation",
            "Qing Luan fills your arms with star iron and cloud silk for Elder Mo. The isles are generous when they're closing.",
            (SAGE, "For your formation. Star iron from the palace floor, cloud silk from the pines. The isles are generous when they close."),
            "@G:IsleOfWinds", ">Gather cloud silk for Elder Mo",
            "@T:CloudGate",
            (SAGE, "And lotus child. When you light it... be careful. I still don't like its shape. But I'm a memory, and memories worry."),
            item="cloud_silk", noun="cloud silk bolts"),
          B("interlude", "The Isles Close",
            "The cloud road dissolves behind you as you step onto the mountain. Above, the isles fade until they are only clouds.",
            "@R:sect/CliffEdge", (N, "The cloud road dissolves behind your last step. Above, the isles fade into ordinary cloud, and then into sky."),
            "@T:SectGate",
            (HAN, "Sixty years until they open again. We'll be old. Well. You won't be. You'll be something else by then."),
            (HAN, "Let's go and give Elder Mo his silk. He'll say adequate. He'll mean wonderful."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 39
    C("The Last Pillar", "sect",
      "The ninth pillar goes up. The mountain holds a festival for the Great Azure Formation: lanterns, dumplings, "
      "Thunder Peak shouting, and Elder Mo, who has checked nine thousand nine hundred runes and has one ring left.",
      cast=[MO, WEI, HUA, MAN, SHI, QIAN, LU, YAN, HAN, BAI, YUN], foes=["training_puppet", "demon_cultivator", "stone_golem"],
      items=["lantern_oil", "spirit_stone", "spirit_herb"], props=["seal", "stone_stele", "bronze_bell"],
      things={"stone_stele": "the ninth pillar"},
      beats=[
          B("orders", "The Ninth Pillar",
            "The ninth pillar is ready to raise. Elder Mo wants you to inscribe it, and Wei Tong wants to carry it alone.",
            (MO, "The ninth pillar. Last one. You inscribe. Wei Tong carries. Nobody helps him carry. He's been looking forward to it for a month."),
            "@R:FormationArray", (N, "Eight pillars ring the plaza, humming faintly blue. The ninth lies on the stones, waiting."),
            "@T:FormationArray",
            (WEI, "Alone! I'm carrying it alone! Stand back! Stand further back! That's too far, I want an audience!"),
            ),
          B("cultivate", "The Final Inscription",
            "You inscribe the ninth pillar with your soul while the whole sect watches from the walls.",
            "@M:FormationArray", ">Inscribe the ninth pillar",
            (N, "Your soul writes the last rune in light. Nine pillars hum together, one long note that you feel in your teeth. The whole mountain sighs."),
            "@T:FormationArray",
            (MO, "Nine. It's done. The frame of the Great Azure Formation. Ten thousand years of safety, and I built it. I built it."),
            (MO, "...With help. Adequate help. More than adequate. Somebody hand me a chair."),
            ),
          B("festival", "Lanterns for Nine Pillars",
            "The Sect Master declares a festival. Nine pillars, nine lanterns, and every disciple on the mountain gets a night off.",
            (YUN, "A festival. Nine lanterns for nine pillars. Every disciple gets a night off. Even Steward Qian. Especially Steward Qian."),
            "@G:FormationArray", ">Collect lanterns for the pillars",
            "@I:FormationArray", ">Hang the first lantern on the ninth pillar",
            (N, "Nine lanterns, one on each pillar. The formation glows gold and blue, and the whole mountain comes out to see it."),
            "@T:SectGate",
            (QIAN, "A night off. I don't know what to do with a night off. I counted my spirit stones. It was very relaxing."),
            item="lantern_oil", noun="festival lanterns", prop="seal", thing="the ninth pillar's lantern"),
          B("social", "Voices at the Festival",
            "The festival is loud and bright. Everyone you love is there, and most of them want to talk to you.",
            (HUA, "Mo ate. At the festival. Two bowls. I watched him. I've never been so relieved to watch a man eat noodles."),
            "|",
            (MAN, "My brother laughed. Out loud. At Wei Tong falling off a bench. First time since the cages. I'm going to remember it forever."),
            (SHI, "It was a very good fall. He fell with dignity. Then without."),
            "|",
            (BAI, "The formation's glow makes the pagoda look beautiful. I'm going to read by it. All night. Nobody stop me."),
            ),
          B("train", "Thunder Peak's Tribute",
            "Thunder Peak insists on a tribute: a shouting contest against the training puppets. Everyone must participate.",
            (YAN, "Thunder Peak's tribute! Everyone fights a puppet! Everyone shouts! The loudest wins nothing! It's tradition! I invented it tonight!"),
            "@F:TrainingGround", ">Shout at puppets for Thunder Peak",
            "@T:TrainingGround",
            (YAN, "You shouted beautifully. Elder Mo shouted too. He said 'adequate' very loudly. The whole peak cheered."),
            foe="training_puppet", count=5),
          B("defend", "Uninvited to the Festival",
            "In the middle of the festival, Thunder Peak's guard at the back door rings its bell. Someone is climbing.",
            (LU, "The back door bell! Thunder Peak's ringing it! Someone's climbing up from the clouds! During the festival! How rude!"),
            "@I:CliffEdge", ">Ring the alarm at the cliff edge",
            (N, "The bell rings over the sea of clouds. Below, on the hidden path, masked figures freeze, then climb faster."),
            "@F:OuterPines",
            "@F2:SectGate",
            "@T:SectGate",
            (HAN, "They came for the formation. On festival night, when everyone was drunk on noodles. They're learning."),
            foe="demon_cultivator", foe2="demon_cultivator", prop="bronze_bell", thing="the cliff bell"),
          B("probe", "One Ring Left",
            "Elder Mo leaves the festival early. He has one ring of runes left to check, and he wants to finish before the lighting.",
            "@R:FormationArray", (N, "While the festival roars on, Elder Mo sits alone at the edge of the formation, lamp in hand, bent over the outer ring."),
            "@I:FormationArray", ">Sit with Elder Mo as he checks the outer ring",
            (N, "Rune by rune. He mutters each one. Correct. Correct. Correct. His finger pauses once, then moves on. Correct."),
            "@T:FormationArray",
            (MO, "Nearly done. The outer ring's fiddly. Some of these runes are written backwards to look forwards. Bai's copying is very precise."),
            (MO, "Go back to the festival. Eat something. I'll be done in a few nights."),
            prop="jade_slip", thing="the outer ring"),
          B("gather", "Peaches for Elder Hua",
            "Elder Mo gives you a basket and asks you to pick peaches from the outer pines' old orchard. For Elder Hua. Don't tell her who sent them.",
            (MO, "Peaches. From the old orchard past the pines. For Hua. Every autumn I leave them on her doorstep. I'm busy this year. You do it."),
            (MO, "Don't tell her who they're from. She knows. We both pretend. It's been forty years. It works."),
            "@G:OuterPines", ">Pick peaches in the old orchard",
            "@T:HerbGarden",
            (HUA, "Peaches on my doorstep. From an anonymous admirer. Who has been anonymous for forty years. Tell him thank you. No. Don't."),
            item="spirit_herb", noun="peaches"),
          B("social", "The Sect Master's Night Off",
            "The Sect Master finds you at the cliff edge after the festival. She is not wearing her crown. She looks much younger without it.",
            (YUN, "I took my crown off. First time in eleven years. My neck doesn't know what to do."),
            (YUN, "In a few days Mo finishes checking. Then we light it. Ten thousand years, and I can sleep. Do you know how long it's been?"),
            (P, "Since you became Sect Master?"),
            (YUN, "Since I was a child, I think. Sit. Watch the formation glow. We've earned one night of looking at something beautiful."),
            ),
          B("interlude", "The Morning After",
            "The morning after the festival, the sect is quiet and hungover on noodles. Elder Mo is still at the formation's edge.",
            (WEI, "Elder Mo didn't come to bed. He's still out there checking runes. I brought him soup. He said adequate. He didn't look up."),
            (WEI, "He looked... worried. Elder Mo doesn't look worried. He looks annoyed. This was different."),
            "|",
            (HAN, "Leave him. He's doing what he promised. When he finds something, he'll tell us. That's Elder Mo."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 40
    C("Before the Lighting", "sect",
      "The formation's frame is finished. The star iron is set, the thunder crystals charged, the phoenix feathers laid "
      "in the outer ring. All that remains is for Elder Mo to finish checking, and for the Sect Master to light it. "
      "The mountain holds its breath, and nobody knows why.",
      cast=[MO, YUN, HAN, WEI, BAI, HUA, ZHAO, LU, SHI, MAN, YAN], foes=["demon_cultivator", "training_puppet", "stone_golem"],
      items=["star_iron", "thunder_crystal", "phoenix_feather"], props=["seal", "jade_slip", "spirit_stone"],
      things={"spirit_stone": "the charged crystals"},
      beats=[
          B("orders", "Setting the Star Iron",
            "The star iron you brought from the isles goes into the formation's heart. Elder Mo wants your soul to guide it in.",
            (MO, "Star iron in the heart. Guide it with your soul. It remembers the sky. It'll want to go back. Don't let it."),
            "@I:FormationArray", ">Guide the star iron into the formation's heart",
            (N, "The star iron sinks into the heart of the formation like a stone into a pond. The whole plaza shivers once, and settles."),
            "@T:FormationArray",
            (MO, "In. The heart's set. Now the crystals. Then the feathers. Then... then I finish the outer ring, and we're done."),
            prop="spirit_stone", thing="the star iron"),
          B("gather", "Charging the Crystals",
            "The thunder crystals must be charged at the cliff edge, where lightning strikes the mountain in storms.",
            (MO, "Thunder crystals charge where lightning strikes. The cliff edge, in the storm tonight. Don't stand too close. Stand exactly close enough."),
            "@G:CliffEdge", ">Set the thunder crystals on the cliff",
            "@T:SectGate",
            (YAN, "I watched from Thunder Peak! The lightning hit every crystal! You didn't even flinch! Thunder Peak is very proud of you!"),
            item="thunder_crystal", noun="thunder crystals"),
          B("battle", "Storm Visitors",
            "The storm brings more than lightning. Blood Moon cultivators use the thunder to cover their climb.",
            (HAN, "Under the thunder! They're climbing under the thunder so nobody hears them! Thunder Peak can't hear anything!"),
            "@F:OuterPines",
            "@F2:SectGate",
            "@T:SectGate",
            (HAN, "They want the formation damaged before it's lit. Or... no. They didn't touch it. They went around it. Why go around it?"),
            foe="demon_cultivator", foe2="demon_cultivator"),
          B("probe", "Feathers in the Outer Ring",
            "The phoenix feathers go into the outer ring, the ring Elder Mo hasn't finished checking.",
            (BAI, "Phoenix feathers in the outer ring. Mo says wait. He's not done checking. I've told him the copy is certified. He says 'so was Gu'."),
            "@I:FormationArray", ">Lay the phoenix feathers in the outer ring",
            (N, "The feathers settle into the outer ring's grooves. Where they touch one particular rune, they curl, very slightly, as if from heat."),
            "@T:Pagoda",
            (BAI, "Curled? Feathers don't curl. Mo. MO! ...He's asleep. At last. I'll tell him in the morning. It's probably nothing."),
            prop="seal", thing="the outer ring"),
          B("social", "Mo Asleep",
            "Elder Mo is asleep at the formation's edge for the first time in weeks. Nobody has the heart to wake him.",
            (WEI, "He's asleep. Sitting up. With his lamp still lit. I put a blanket on him. He said 'adequate blanket' in his sleep."),
            "|",
            (HUA, "Let him sleep. He's been awake for weeks. He'll find whatever he's looking for with fresh eyes. Or he won't, and it's nothing."),
            (HUA, "I left peaches by his lamp. Anonymous. It's our tradition."),
            ),
          B("train", "Last Spar Before the Lighting",
            "Zhao Kang wants a spar. He says it's to celebrate. He's nervous. Everyone is nervous and nobody knows why.",
            (ZHAO, "Spar. Now. I'm nervous and I don't know why. When I'm nervous, I hit things. Better you than the formation."),
            "@F:TrainingGround", ">Spar with Zhao Kang's practice puppets",
            "@T:TrainingGround",
            (ZHAO, "Better. Still nervous. The whole mountain's nervous. The birds are nervous. Wei Tong only ate one breakfast."),
            foe="training_puppet", count=4),
          B("social", "The Whole Mountain Waits",
            "Lu Ping has a theory about why everyone is nervous. Xiao Shi has a better one.",
            (LU, "My theory: everyone's nervous because nobody's had a disaster in weeks and we're out of practice."),
            "|",
            (SHI, "In the cages, before something bad, the guards would go quiet. Everyone felt it. Nobody knew what it was."),
            (SHI, "It feels like that. I'm sorry. I'm probably wrong. I hope I'm wrong."),
            "|",
            (MAN, "He's not wrong. The carp are all at the bottom of the pond. They never go to the bottom. Not even in winter."),
            ),
          B("cultivate", "Soul at the Peak",
            "You sit on the stone bridge and let your nascent soul reach its peak, as if something in you knows you'll need it soon.",
            "@M:StoneBridge", ">Bring your nascent soul to its peak",
            (N, "Your nascent soul sits cross-legged in your chest, lotus in its hands, and opens its eyes very wide. Peak of Nascent Soul."),
            (N, "In soul sight, the formation behind you glows blue. In one place, in the outer ring, the blue has a thread of red in it."),
            "@T:StoneBridge",
            (HAN, "You look like you saw something. Did you see something?"),
            (P, "A red thread in the outer ring. Very thin. I'll tell Elder Mo when he wakes."),
            ),
          B("probe", "Telling Mo",
            "Elder Mo wakes at dawn. You tell him about the red thread and the curling feathers. He goes very still.",
            (MO, "Red thread. Outer ring. Curling feathers. Hm."),
            (MO, "Bai's copy is certified. Gu kept that archive for thirty years. ...Thirty years. Leave it with me. Three more nights."),
            "@I:FormationArray", ">Show Elder Mo where the red thread runs",
            (N, "You point. He looks. For a long moment he says nothing at all, and his hand, holding the lamp, is not quite steady."),
            "@T:HallSteps",
            (MO, "Go and rest. Tell no one yet. Not the Sect Master, not Bai. Not until I'm sure. Three nights. I'll check every rune on that ring."),
            (MO, "Go on, {junior}. Adequate work. More than adequate."),
            prop="seal", thing="the outer ring"),
          B("interlude", "Three Nights",
            "Elder Mo begins his three nights. The mountain goes quiet around him, and waits.",
            (YUN, "Mo's asked for three nights before the lighting. He won't say why. Forty years I've known him. He's never asked for anything."),
            (YUN, "I'll give him three nights. And you. Rest. Whatever Mo finds, we'll need you rested."),
            "|",
            (WEI, "Three nights. I'll bring him soup every night. He'll say adequate. I'll say you're welcome. That's our tradition now."),
            ),
      ]),
]
