"""Volume VIII · Body Integration — chapters 71-80.

The Great Vehicle: a realm nobody reaches alone. The Sect Master calls the
orthodox sects to a conclave; the Iron Scale, the Zhao clan, the Moon-Well
and Qingshi answer, along with smaller sects nobody has heard of. Si Rou,
Lady Silk, the Sixth Rung, spins her web through the middle of it. The
answer to a web is not a sword. It's a vehicle.
"""

from .dsl import N, P
from .npcs import *  # noqa: F401,F403
from .saga_gen import B, C

CHAPTERS = [
    # ------------------------------------------------------------------ chapter 71
    C("The Great Vehicle", "sect",
      "Five Rungs have fallen and the fold at the Abyss grows thinner. When it opens, the Azure Cloud cannot march "
      "alone. The Sect Master decides to call every orthodox sect to one conclave, and the hermit says the heir must "
      "learn the realm that carries others: Body Integration, the first step of the Great Vehicle.",
      cast=[YUN, LAN, HAN, WEI, ZHAO, BAI, HUA, LU, SHI], foes=["void_wraith", "training_puppet", "demon_cultivator"],
      items=["letter", "spirit_herb", "incense"], props=["jade_slip", "seal", "stone_stele"],
      beats=[
          B("orders", "Not Alone",
            "The Sect Master stands on the formation plaza and says something no Azure Cloud master has said in three hundred years.",
            (YUN, "When the fold opens, we cannot march alone. Three hundred years ago we had the Verdant Lotus. Now we need everyone."),
            (YUN, "I'm calling a conclave. Every orthodox sect. On our mountain. The first in three centuries. Lu Ping, prepare the cranes."),
            "@R:FormationArray", (N, "The formation glows under the Sect Master's feet. Every disciple on the plaza goes very quiet, and then starts talking at once."),
            "@T:SectGate",
            (LU, "Cranes! Hundreds of cranes! I've never folded hundreds of cranes! I've folded eleven, and three of them flew into walls!"),
            ),
          B("social", "The Hermit Explains the Body of Many",
            "The hermit explains the next realm over tea in the pagoda. It's not what you expected.",
            (LAN, "Body Integration. The body of many. Every realm before this was about you. Your qi, your core, your soul, your body. This one isn't."),
            (LAN, "You carry others. Their hopes, their fears, their weight. And they carry you. You can't reach it alone. You never could."),
            (P, "How do I cultivate carrying people?"),
            (LAN, "You carry them. Literally, sometimes. Start small. Start with the ones already on your back."),
            ),
          B("gather", "Paper for a Thousand Cranes",
            "Lu Ping needs paper for a thousand cranes. Elder Bai's pagoda has paper. Elder Bai has conditions.",
            (BAI, "Paper! For cranes! From my pagoda! My good paper! ...For a conclave of sects. Fine. Take it. Take the second-best paper."),
            "@G:Pagoda", ">Gather crane paper from the pagoda",
            "@T:SectGate",
            (LU, "Second-best paper. Still better than anything I've ever folded. I'm going to fold my best crane ever. It's going to fly perfectly."),
            item="letter", noun="crane paper"),
          B("probe", "Folding a Thousand Cranes",
            "Everyone on the mountain folds cranes. Some are beautiful. Wei Tong's look like dumplings. They fly anyway.",
            "@R:FormationArray", (N, "The whole sect sits on the plaza folding paper cranes. Children, elders, the hermit, the Sect Master. Wei Tong's cranes look like dumplings."),
            "@I:FormationArray", ">Breathe life into the thousand cranes",
            (N, "You breathe qi into the pile. A thousand paper cranes rise, circle the mountain once, and scatter east, west, north and south."),
            "@T:SectGate",
            (WEI, "My dumpling cranes flew! They flew! One of them flew into Elder Bai. He kept it. He said it was the most honest crane he's ever met."),
            prop="seal", thing="the thousand cranes"),
          B("train", "Carrying Wei Tong",
            "The hermit said start with the ones already on your back. Wei Tong volunteers. Literally. He wants to be carried.",
            (WEI, "Carrying people? Start with me! Carry me around the training ground! I carried you once, when the wolf king got me! Your turn!"),
            "@F:TrainingGround", ">Fight the puppets while carrying Wei Tong",
            (WEI, "Faster! Left! There's a puppet on the left! I'm very heavy! I've been eating for this moment all week!"),
            "@T:WeaponRack",
            (WEI, "You carried me and fought four puppets. I'm going to tell everyone. I'm going to tell my twelve. I'm going to tell the chicken."),
            foe="training_puppet", count=4),
          B("social", "What Everyone Carries",
            "You ask people what they carry. Everyone has an answer, and none of them are small.",
            (HAN, "What do I carry? Frost Sword Peak. Thirty disciples who think I'm frightening. I am. It's on purpose. It keeps them alive."),
            "|",
            (SHI, "I carry the map. And the cages. And my sister, who carries everyone. I'm getting better at carrying her back."),
            "|",
            (HUA, "Every patient I've ever lost. And forty years of peaches. The peaches are lighter."),
            ),
          B("defend", "Wraiths Follow the Cranes",
            "Some of the cranes are followed. Void wraiths slip out of rifts and drift after them like moths.",
            (ZHAO, "Wraiths following the cranes! They want to eat the invitations! I'm not letting a wraith eat my great-grandfather's invitation!"),
            "@I:CliffEdge", ">Ward the cranes' flight path from the cliff",
            (N, "Your ward rises over the cliff like a shield. The cranes fly through it. The wraiths don't."),
            "@F:OuterPines",
            "@F2:SectGate",
            "@T:SectGate",
            (ZHAO, "All the cranes made it out. Every single one. Even the dumpling ones. Especially the dumpling ones. They're very determined."),
            foe="void_wraith", foe2="void_wraith", prop="seal", thing="the flight path"),
          B("cultivate", "Carrying the Mountain",
            "The hermit asks you to sit on the formation and feel the whole mountain at once. Every person on it.",
            (LAN, "Sit on the formation. Feel everyone on the mountain. Every breath. Not to watch them. To hold them. Gently."),
            "@M:FormationArray", ">Feel everyone on the mountain at once",
            (N, "Three thousand breaths, all at once. Wei Tong snoring. Xiao Man humming. The Sect Master worrying. You hold them, and they're light."),
            "@T:SectGate",
            (LAN, "You're smiling. Everyone who first feels it smiles. Then they cry. Then they get up and carry things. That's Body Integration."),
            ),
          B("social", "The First Answers",
            "The first cranes come back within a week. Every sect you've ever helped has answered.",
            (LU, "Answers! From the Iron Scale! The Zhao clan! The Moon-Well! Qingshi's yamen! And... sects I've never heard of! Dozens!"),
            (LU, "The Silk Pavilion. The Cinder Cloud. The Hundred Wells. I didn't even know there were that many sects. There are loads!"),
            "|",
            (YUN, "Everyone's coming. Everyone we've helped, and everyone who heard we helped. You did this. You said yes too often."),
            ),
          B("hunt", "Void Wraiths, the Second Flight",
            "A second wave of cranes needs escorting, and a fresh batch of void wraiths tries to follow them.",
            foe="void_wraith", v=0),
          B("gather", "Incense for the Conclave Tents",
            "Steward Qian prepares incense for every guest tent, insisting a good host thinks of comfort before politics.",
            item="incense", v=0),
          B("social", "Wei Tong's Guest List Anxiety",
            "Wei Tong, put in charge of guest lodging, panics gently about where to seat sects who dislike each other.",
            (WEI, "The Iron Scale and the Zhao clan don't get along. Neither do the Moon-Well and half the smaller sects. Where do I even put everyone?"),
            v=0),
          B("hunt", "Demon Cultivators, Testing the Roads",
            "Demon cultivators test the mountain roads ahead of the conclave, probing for a way to disrupt the gathering.",
            foe="demon_cultivator", v=0),
          B("gather", "Spirit Herbs for the Welcome Feast",
            "Elder Hua and Madam Fang, working together for once, need spirit herbs for a welcome feast worthy of every sect.",
            item="spirit_herb", v=0),
          B("probe", "Bai Ling's Seating Chart",
            "Bai Ling, delighted to have a real logistics problem, draws up an elaborate seating chart based on old alliances.",
            (BAI, "I've mapped every feud back three generations! Nobody sits next to an old enemy! This is the best project I've ever had!"),
            v=0),
          B("social", "Lu Ping's Best Crane",
            "Lu Ping proudly shows off the one crane he folded perfectly, insisting it be the one that carries the Sect Master's personal invitation.",
            (LU, "This one. My best one. It's going to the Zhao clan patriarch himself. I practiced folding it forty times."),
            v=0),
          B("hunt", "Training Puppets, Hollowed by Nerves",
            "A training puppet, left unattended amid the conclave prep chaos, gets accidentally reactivated by a nervous disciple.",
            foe="training_puppet", v=0),
          B("gather", "Jade Slips for the Conclave's Record",
            "Elder Bai wants every word of the coming conclave recorded on jade slips, insisting history deserves accuracy.",
            item="jade_slip", v=0),
          B("social", "Han Xue's Worry About Crowds",
            "Han Xue, more comfortable with thirty disciples than three hundred strangers, admits the conclave makes her nervous.",
            (HAN, "I know how to protect thirty people I know. I don't know how to protect everyone who's about to show up. That scares me more than wraiths."),
            v=0),
          B("break", "Body Integration",
            "On the eve of the conclave, with every answer in, the hermit asks you to sit at the pond and carry them all at once.",
            (LAN, "Every answer. Every sect. Every person who said yes because you said yes first. Carry them. All of them. Tonight."),
            "@G:LotusPond", ">Gather the returned cranes by the pond",
            "@M:LotusPond", ">Carry every sect in your cultivation",
            (N, "Iron Scale, Zhao, Moon-Well, Qingshi, and dozens more. You carry them all, and they carry you. It's the lightest you've ever felt."),
            (N, "Beside you the green lotus opens wider than it ever has. Beneath the water, something like a vehicle made of light begins to take shape."),
            "@T:StoneBridge",
            (YUN, "Body Integration. A body of many. The first in the Azure Cloud since the founder. Tomorrow the sects arrive. Carry them well."),
            item="letter", noun="returned cranes"),
      ]),
    # ------------------------------------------------------------------ chapter 72
    C("The Sects Arrive", "sect",
      "For a week the nine thousand steps are never empty. Iron Scale green, Zhao gold, Moon-Well white and the colours "
      "of sects nobody has heard of climb the mountain, argue about who goes first, and set up camp on every flat stone.",
      cast=[YUN, RUANHAI, RUAN, TIANLU, JING, ZHAO, LU, QIAN, WEI, HAN], foes=["iron_scale_disciple", "sparring_disciple", "void_wraith"],
      items=["spirit_stone", "medicine", "incense"], props=["stone_stele", "bronze_bell", "seal"],
      foe_names={"sparring_disciple": "rowdy sect disciples"},
      beats=[
          B("orders", "Green Banners Again",
            "The Iron Scale arrive first. This time, the green banners bow at the gate.",
            (LU, "Green banners! The Iron Scale! They're bowing! At the gate! The Iron Scale doesn't bow! I'm going to faint on my own boots!"),
            "@R:SectGate", (N, "Iron Scale green fills the processional way. At the gate, Ruan Hai stops, and bows. Every Iron Scale disciple behind him bows too."),
            "@T:SectGate",
            (RUANHAI, "The Iron Scale answers. Remembering Hill sends its greetings. We brought tea. The good tea. For the Cinder Peak incident."),
            (RUAN, "Father insisted on the tea. He's been practising his bow for a week. Don't tell him it was slightly crooked."),
            ),
          B("social", "The Zhao Clan Arrives in Gold",
            "The Zhao clan arrives in gold palanquins. Zhao Kang pretends not to be waiting at the gate. He's been there since dawn.",
            (TIANLU, "The Zhao clan answers. With gold, naturally. And with three hundred disciples, and my great-grandson's monthly letters, framed."),
            (ZHAO, "Framed? You framed my letters? The one about the dumplings? The one where I said 'love'?"),
            (TIANLU, "Especially that one. It's in the ancestral hall. Next to your brother's stone."),
            "|",
            (ZHAO, "...I need a moment. Behind the gate. Alone. Don't follow me."),
            ),
          B("social", "The Moon-Well Arrives Singing",
            "The Moon-Well Nunnery comes up the steps singing. The girl from the cage, Lian, leads the song.",
            (JING, "The Moon-Well answers. We sing on the steps. Lian's idea. So we know we're here. It's become a tradition. Traditions start small."),
            "|",
            (N, "A young nun with bright eyes bows to you. Lian. She doesn't say anything. She sings one line of the song, only for you, and walks on."),
            ),
          B("gather", "Space for Everyone",
            "Steward Qian needs somewhere to put two thousand guests. The mountain has flat stones. Not enough.",
            (QIAN, "Two thousand guests! Where do I put them? The plaza? The terraces? The roof? I've put forty on the roof! It's a very nice roof!"),
            "@G:FormationArray", ">Mark out camp spaces across the plaza",
            "@T:SectGate",
            (QIAN, "Everyone has a flat stone. Some of them have flat stones on the roof. Nobody's complained. Well, the Zhao clan complained. Politely."),
            item="spirit_stone", noun="camp markers"),
          B("duel", "Who Goes First",
            "The Cinder Cloud and the Hundred Wells argue about who should enter the main hall first. The argument becomes a brawl.",
            (WEI, "The Cinder Cloud and the Hundred Wells are fighting! About who goes through the door first! It's a very big door! They could both fit!"),
            "@F:TrainingGround", ">Separate the brawling sect disciples",
            "@T:WeaponRack",
            (WEI, "You carried two brawling disciples off the training ground, one under each arm. They're friends now. They bonded over being carried."),
            foe="sparring_disciple", count=5),
          B("probe", "The Silk Pavilion",
            "A small sect nobody has heard of arrives last: the Silk Pavilion. Its envoy is a woman in pink silk who smiles at everyone.",
            "@R:SectGate", (N, "A single palanquin of pink silk arrives at the gate. The woman who steps out is beautiful, gracious, and bows to everyone, including the gate."),
            "@I:SectGate", ">Read the Silk Pavilion's credentials",
            (N, "Credentials in perfect order. A small sect, far to the south. Envoy: Lady Si Rou. The seal is flawless. It is almost too flawless."),
            "@T:SectGate",
            (HAN, "Lady Si Rou. She smiled at me. Nobody smiles at me. I'm frightening on purpose. I'm going to watch her."),
            prop="jade_slip", thing="the credentials"),
          B("battle", "Wraiths at the Camp",
            "Two thousand guests means two thousand people who might grieve, fear, or hope. The wraiths come to feed.",
            (RUAN, "Wraiths in the Iron Scale camp! We've fought them before! On Remembering Hill! We know how! Kind of!"),
            "@F:OuterPines",
            "@F2:FormationArray",
            "@T:SectGate",
            (RUAN, "Iron Scale and Azure Cloud, fighting side by side. Again. It's becoming a habit. A good habit."),
            foe="void_wraith", foe2="void_wraith"),
          B("social", "The Night Before the Conclave",
            "On the night before the conclave, the whole mountain is lit by two thousand lanterns, and nobody sleeps.",
            (YUN, "Two thousand guests. Forty sects. One mountain. Tomorrow I have to speak to all of them. I've never been so frightened."),
            (P, "Sect Master, you've faced the Blood Moon."),
            (YUN, "The Blood Moon doesn't ask questions after your speech. Forty sect masters do. Sit with me. Don't say anything. Carry me a bit."),
            ),
          B("festival", "Lanterns for Forty Sects",
            "Every sect hangs a lantern on the formation's nine pillars. Forty colours. It's the most beautiful thing on the mountain.",
            (LU, "Forty lanterns! On nine pillars! Some pillars have five! The Zhao clan's is gold! Of course it's gold!"),
            "@G:FormationArray", ">Carry the forty sects' lanterns",
            "@I:FormationArray", ">Hang the last lantern on the ninth pillar",
            (N, "Forty lanterns on nine pillars. Blue, green, gold, white, pink. The formation glows beneath them, and the mountain looks like a festival of stars."),
            "@T:SectGate",
            (JING, "Forty sects. Three hundred years of quarrels. One mountain of lanterns. Whatever happens tomorrow, tonight was worth it."),
            item="incense", noun="sect lanterns", prop="seal", thing="the ninth pillar"),
          B("hunt", "Rowdy Disciples, a Second Brawl",
            "The Cinder Cloud and Hundred Wells, now friends, accidentally start a second brawl with a third sect over lantern placement.",
            foe="sparring_disciple", count=3, v=0),
          B("gather", "Medicine for the Camp's Minor Injuries",
            "Two thousand guests and one lantern-hanging festival produce a steady trickle of minor injuries for Elder Hua to treat.",
            item="medicine", v=0),
          B("social", "Ruan Jingtao's Old Grudge, Set Down",
            "Ruan Jingtao finds Zhao Kang at the lantern-hanging and formally apologizes for the coldness between their sects at the banners.",
            (RUAN, "I was cold to you, at the banners. Pride, mostly. Remembering Hill taught me pride is expensive. I'm sorry, Zhao Kang."),
            (ZHAO, "Apology accepted. Also, help me carry this lantern, it's heavier than it looks."),
            v=0),
          B("hunt", "Void Wraiths, the Camp's Second Night",
            "A second wave of wraiths tests the crowded camp, drawn by the mix of hope and old grief among two thousand strangers.",
            foe="void_wraith", v=0),
          B("gather", "Spirit Stones for the Formation's Extra Load",
            "Powering forty lanterns on nine pillars strains the formation, and Steward Qian asks for more spirit stones to compensate.",
            item="spirit_stone", v=0),
          B("probe", "Lady Si Rou's Twelfth Visit",
            "Han Xue tracks Lady Si Rou to a twelfth camp, the smallest sect present, and watches what she says there.",
            (HAN, "She didn't cause an argument this time. She just asked questions. About alliances. About who trusts whom. She's mapping us."),
            v=0),
          B("social", "Lian's Second Song",
            "Lian, the young nun, sings a second time, this time for the whole mountain, and even the Zhao clan patriarch stops talking.",
            (N, "Lian's voice carries over two thousand lanterns and forty sects. For one song, nobody argues. Nobody plots. Everyone just listens."),
            v=0),
          B("hunt", "Iron Scale Disciples, Testing the New Recruits",
            "A friendly sparring match between Iron Scale disciples and Wei Tong's twelve turns rowdier than intended.",
            foe="iron_scale_disciple", v=0),
          B("gather", "Incense for the Sect Master's Speech",
            "Yun Zhi asks for incense lit at the main hall before tomorrow's speech, a small steadying ritual before the biggest one of her life.",
            item="incense", v=0),
          B("social", "The Sect Master's Rehearsal",
            "Late at night, Yun Zhi rehearses her speech to an audience of exactly one: you, sitting quietly, carrying her the way she asked.",
            (YUN, "Tell me if it's terrible."),
            (P, "It's not terrible. It's honest. That's better."),
            (YUN, "Honest. Yes. Let's go with honest. I don't have the energy left to be anything else."),
            v=0),
          B("interlude", "Pink at the Edges",
            "Late at night, Han Xue finds you. She's been watching Lady Si Rou. She has something to show you.",
            (HAN, "Lady Si Rou. She visited eleven camps tonight. Eleven. She smiled at everyone. And after each visit, someone started arguing."),
            (HAN, "Iron Scale with Zhao. Moon-Well with Cinder Cloud. Always after she left. I'm going to keep watching. You keep carrying."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 73
    C("A Week Without a Name", "qingshi_town",
      "Before the conclave begins, Abbess Jing of the Moon-Well sets you a test: a week in Qingshi, serving the poor, "
      "and nobody may know who you are. The Great Vehicle, she says, is carrying people who don't know your name.",
      cast=[JING, FANG, LIU, DU, PAN, TIE, ZHOU, JIN, LIUER], foes=["rogue_cultivator", "bandit", "void_wraith"],
      items=["medicine", "spirit_herb", "incense"], props=["treasure_chest", "seal", "stone_stele"],
      things={"treasure_chest": "the rice sacks"},
      beats=[
          B("orders", "The Abbess's Test",
            "Abbess Jing has a condition for the Moon-Well's support: a week of service, anonymous, in the town below.",
            (JING, "The Moon-Well will stand with you. On one condition. A week in Qingshi. Serving the poor. Nobody may know who you are."),
            (JING, "The Great Vehicle is carrying people who don't know your name. Anyone can carry people who cheer."),
            "@R:qingshi_town/TownGate", (N, "You walk into Qingshi in a plain grey robe, hood up. The gate guard doesn't look twice. It's the strangest feeling in the world."),
            "@T:MainStreet",
            (FANG, "A new dishwasher? Iron-Fang needs help. He's getting old. Don't tell him I said that. What's your name? No name? Fine. Dishes."),
            map="sect"),
          B("gather", "Dishes at the Drunken Crane",
            "Your first task: dishes, at the Drunken Crane, beside Iron-Fang, who doesn't recognise you with your hood up.",
            (TIE, "New dishwasher? Good. Stack them by size. Rinse twice. Don't talk. Dishwashing is a sacred silence."),
            "@G:Inn", ">Wash the Drunken Crane's dishes",
            "@T:Inn",
            (TIE, "You're good. Very good. Where'd you learn? ...Wait. I know that stance. Sect brat? No. Don't tell me. I won't tell anyone."),
            item="medicine", noun="stacks of dishes"),
          B("social", "Water for the Well",
            "Widow Liu is too old to carry all the water now. A hooded stranger offers to help.",
            (LIU, "Help? From a stranger? Well. My arms aren't what they were. Twenty buckets to the old houses on the hill. Thank you, stranger."),
            "|",
            (LIU, "You carry water the way someone I know carries it. Straight-backed. ...I won't ask. Heaven keeps its accounts. So do I."),
            ),
          B("hunt", "Rogues in the Poor Quarter",
            "Rogue cultivators are shaking down the poor quarter. The hooded dishwasher happens to be passing.",
            "@R:BackAlley", (N, "In the back alley, three rogues are taking coppers from an old man who hasn't got any. The old man is crying. The rogues are laughing."),
            "@F:BackAlley",
            "@G:BackAlley", ">Return the stolen coppers",
            "@T:MainStreet",
            (DU, "Someone beat three rogues in the back alley and gave all the coppers back. A stranger in grey. Nobody knows who. I'm writing it down as 'grey'."),
            foe="rogue_cultivator", item="spirit_stone", noun="stolen coppers"),
          B("probe", "Rice for the Hill Houses",
            "The old houses on the hill have no rice this winter. The guild warehouse has plenty. Merchant Jin has a new policy.",
            (JIN, "Rice for the hill houses? The guild has a new policy. Anyone who asks gets rice. It's a terrible policy. I love it."),
            "@I:Warehouse", ">Open the guild's rice sacks",
            (N, "Sacks of rice, stamped with the guild's seal and a new mark underneath: a small lotus, in green. Jin's added it. Nobody asked him to."),
            "@T:Warehouse",
            (JIN, "The lotus? It's for... someone. Who saved the town. Who I nearly sold. Carry the rice, stranger. Don't ask about the lotus."),
            prop="treasure_chest", thing="the rice sacks"),
          B("social", "Liu Er Doesn't Recognise You",
            "Liu Er is home on leave. He's teaching the town children to stand straight. He asks the hooded stranger to demonstrate.",
            (LIUER, "Stranger! Can you stand straight? Show the children? Like this. Back straight. A crooked spine makes a crooked meridian. My teacher's teacher said that."),
            (P, "Like this?"),
            (LIUER, "Exactly like that. Perfect. You stand like... never mind. You stand very well, stranger. Thank you."),
            ),
          B("defend", "Night in the Poor Quarter",
            "Wraiths come to the poor quarter at night, where people are cold and afraid and have given up. The stranger in grey is there.",
            (PAN, "Shades in the old houses! Drawn to the cold ones! The poor ones! Someone ring the bell!"),
            "@I:Riverside", ">Ring the dock bell to wake the quarter",
            (N, "The bell rings. Lamps flare in the old houses. People come out, and a hooded stranger stands between them and the purple dark."),
            "@F:Graveyard",
            "@F2:BackAlley",
            "@T:MainStreet",
            (PAN, "The stranger in grey. Standing in the street all night. Nobody knows who. I know who. I'm not saying. Forty years. I can keep a secret."),
            foe="void_wraith", foe2="void_wraith", prop="bronze_bell", thing="the dock bell"),
          B("cultivate", "Carrying Without Being Seen",
            "On the sixth night, you sit in the temple, hood up, and carry the whole town the way you carried the mountain. Nobody knows.",
            "@M:Temple", ">Carry the town in silence",
            (N, "The whole town, breathing. Nobody knows who's holding them. They don't need to. They're held. It's lighter than being cheered."),
            "@T:MainStreet",
            (ZHOU, "A stranger has been helping everyone this week. The yamen would like to honour them. We can't find them. It's very frustrating. It's wonderful."),
            ),
          B("social", "Everyone Knew",
            "On the seventh day, you find out that everyone knew who you were. Nobody said. The whole town kept the secret.",
            (FANG, "Everyone knew. From the first day. Iron-Fang knew by the stance. Widow Liu knew by the water. We decided not to say."),
            (FANG, "You wanted to carry us without being seen. So we let you. That's what a town does for someone it loves. It pretends."),
            "|",
            (JING, "They all knew. And they let you carry them anyway, and carried your secret. That's the Great Vehicle. Both directions. You've passed."),
            ),
          B("hunt", "Bandits, Testing the Quiet Week",
            "A small band of bandits, hearing Qingshi's usual defenders are distracted, tests the town's edges during the anonymous week.",
            foe="bandit", v=0),
          B("gather", "Medicine for the Hill Houses",
            "The old houses on the hill need medicine as much as rice, and the hooded stranger makes one more supply run.",
            item="medicine", v=0),
          B("social", "Old Chen's Recognition",
            "Old Chen, the plum farmer, claims he recognized the hooded stranger by their whistle, which they'd apparently unconsciously picked up from him.",
            (N, "Old Chen says the stranger whistled his tune while carrying water. He didn't say anything. He just started whistling back."),
            v=0),
          B("hunt", "Void Wraiths, the Poor Quarter's Second Night",
            "A second night of wraiths tests the poor quarter, and the hooded stranger stands watch again without complaint.",
            foe="void_wraith", v=0),
          B("gather", "Spirit Herbs for Elder Hua's Quiet Shipment",
            "Elder Hua sends spirit herbs to Qingshi anonymously too, matching the spirit of the stranger's own quiet work.",
            item="spirit_herb", v=0),
          B("probe", "Merchant Jin's Second Policy",
            "Merchant Jin, inspired by the rice policy's success, quietly extends free credit to anyone the hooded stranger vouches for.",
            (JIN, "I don't ask who the stranger vouches for. I just extend the credit. It's worked out well so far. Suspiciously well."),
            v=0),
          B("social", "Liuer's Growing Class",
            "Liu Er's posture class for the town's children has grown to twenty students, all copying the hooded stranger's stance exactly.",
            (LIUER, "Twenty kids now! All standing like you! I didn't tell them who to copy! They just picked the best stance in the room!"),
            v=0),
          B("hunt", "Rogue Cultivators, a Second Shakedown",
            "The rogue cultivators from the back alley return with reinforcements, testing whether the grey stranger got lucky the first time.",
            foe="rogue_cultivator", v=0),
          B("gather", "Incense for the Temple's Quiet Nights",
            "The temple where you carry the town in silence needs incense, a small comfort Zhou insists on providing anonymously in turn.",
            item="incense", v=0),
          B("social", "Widow Liu's Thanks, Unspoken",
            "On the last day, Widow Liu leaves a small gift on the doorstep of the room the stranger stayed in, and says nothing about it.",
            (N, "A folded blanket, still warm from the hearth, with no note. You don't need one to know who left it, or why."),
            v=0),
          B("interlude", "Up the Mountain Again",
            "You walk back up the nine thousand steps without the hood. At the gate, Abbess Jing bows to you. The Moon-Well is with you.",
            (JING, "The Moon-Well stands with the Azure Cloud. Not because you asked. Because a whole town kept your secret for a week."),
            "|",
            (HAN, "Welcome back. Lady Silk visited thirty camps while you were gone. Thirty arguments. The conclave starts tomorrow. It's going to be a mess."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 74
    C("The Conclave of Forty Sects", "sect",
      "Forty sects in the main hall, the first conclave in three hundred years. The Sect Master speaks. The sect masters "
      "argue. Somewhere in the middle of it, a woman in pink silk smiles, and every argument gets a little worse.",
      cast=[YUN, RUANHAI, TIANLU, JING, HAN, ZHAO, RUAN, BAI, LU], foes=["iron_scale_disciple", "sparring_disciple", "demon_cultivator"],
      items=["letter", "jade_slip", "incense"], props=["jade_slip", "stone_stele", "seal"],
      foe_names={"sparring_disciple": "quarrelling disciples"},
      beats=[
          B("orders", "The Sect Master Speaks",
            "The conclave opens. The Sect Master stands before forty sect masters and speaks for three minutes. Nobody moves.",
            (YUN, "Three hundred years ago two sects sealed a monster. One gave everything. The other forgot. When the fold opens, we cannot forget again."),
            (YUN, "I'm not asking you to follow the Azure Cloud. I'm asking you to walk beside it. That's all. That's the speech."),
            "@R:MainHall", (N, "Forty sect masters sit in the main hall in silence. Then Ruan Hai stands and bows. Then the Zhao ancestor. Then everyone at once."),
            "@T:FormationArray",
            (LU, "Three minutes! Everyone stood up! I cried! Wei Tong cried! A Hundred Wells elder cried! The Zhao ancestor pretended not to!"),
            ),
          B("social", "The First Argument",
            "The standing ovation lasts three minutes. The first argument lasts three hours. It's about who marches in front.",
            (RUANHAI, "The Iron Scale marches at the front. We have the most to avenge. Forty of our children in the ice."),
            (TIANLU, "The Zhao clan marches at the front. We have the most gold. Gold marches very well."),
            "|",
            (JING, "The Moon-Well marches wherever we're needed. That's usually the back. Where the wounded are. Nobody argues about the back."),
            ),
          B("probe", "Pink Silk in the Hall",
            "Lady Si Rou sits quietly through the argument. Each time she whispers to someone, the argument gets worse.",
            "@R:MainHall", (N, "Lady Si Rou leans over and whispers to the Cinder Cloud's master. He stands up and shouts at the Hundred Wells. She smiles."),
            "@I:MainHall", ">Watch Lady Si Rou with your soul",
            (N, "In soul sight, silk threads run from her fingers to eleven sect masters. Thin, pink, almost invisible. Each tugs, gently, toward anger."),
            "@T:FormationArray",
            (HAN, "Threads. On eleven sect masters. She's puppeteering the conclave. She's the Sixth Rung. Lady Silk. Qing Luan's chart said silk."),
            (HAN, "We can't accuse an envoy in the middle of a conclave. Nobody would believe us. They'd think we're the ones pulling strings."),
            prop="seal", thing="Lady Si Rou"),
          B("social", "Cutting Threads Quietly",
            "You can't accuse her. But you can cut threads, quietly, one sect master at a time, by carrying them.",
            (P, "Sect Master Ruan. You lost forty. We'll get them out. Together. The front doesn't matter. Getting them out matters."),
            (RUANHAI, "...Yes. Yes, you're right. I don't know why I was shouting. It felt like someone else's anger. I'll march at the side."),
            "|",
            (TIANLU, "The side is fine for the Zhao clan too. Gold looks good from any angle. I don't know why I was so angry."),
            ),
          B("battle", "Disciples Brawl",
            "The sect masters calm down. Their disciples, who have been drinking in the camps, do not.",
            (ZHAO, "The disciples are brawling! Forty sects' worth! In the camps! Someone started a rumour that the Iron Scale cheated at the banners!"),
            "@F:FormationArray",
            "@F2:TrainingGround",
            "@T:SectGate",
            (ZHAO, "Everyone's calm. Mostly. I found out who started the rumour. A servant in pink. Silk Pavilion. Of course."),
            foe="sparring_disciple", foe2="iron_scale_disciple"),
          B("gather", "Collecting the Threads",
            "Now you know what to look for, you can see Lady Silk's threads everywhere in the camps. You gather them.",
            (HAN, "Threads everywhere. On tents. On banners. On teacups. She's woven the whole camp. Cut them. Quietly. Before she notices."),
            "@G:OuterPines", ">Gather the pink threads from the camps",
            "@T:SectGate",
            (HAN, "Forty threads. Cut. She'll notice. She'll be angry. Angry is good. Angry makes people careless. Even spiders."),
            item="letter", noun="pink threads"),
          B("probe", "Bai's Research",
            "Elder Bai has been researching the Silk Pavilion. It doesn't exist. It never has.",
            (BAI, "The Silk Pavilion. Far to the south. I've read every map. There's nothing there. A lake. A very pretty lake. No sect."),
            "@I:Pagoda", ">Compare the Silk Pavilion's seal with the Blood Moon records",
            (N, "The Silk Pavilion's seal, under magnification, has a tiny crescent woven into its border. Seven threads. Six still bright."),
            "@T:Pagoda",
            (BAI, "Blood Moon. The Sixth Rung. In our conclave. In my pagoda, borrowing books. She borrowed three and returned them on time. I'm furious."),
            prop="jade_slip", thing="the Silk Pavilion's seal"),
          B("social", "Telling the Sect Master",
            "You tell the Sect Master. She listens, and smiles, and it's the most frightening smile you've ever seen.",
            (YUN, "A Rung. In my conclave. Pulling my guests' strings. In my hall."),
            (YUN, "We don't accuse her. We let her pull, and we cut, and we carry, and when she's tired, we ask her to leave. Politely. With swords."),
            "|",
            (JING, "The Moon-Well saw the threads too. We said nothing. We've been cutting them since the first day. Quietly. We're very good at quiet."),
            ),
          B("defend", "The Conclave's Second Day",
            "On the second day, the threads are gone and the sect masters agree on everything. Lady Silk's servants try something louder.",
            (LU, "Fire in the Cinder Cloud camp! And the Hundred Wells camp! Both at once! Blamed on each other! Both sects are drawing swords!"),
            "@I:FormationArray", ">Raise the formation over both camps",
            (N, "The Great Azure Formation rises over the camps like a hand. Blue light, and under it, both fires go out."),
            "@F:OuterPines",
            "@F2:SectGate",
            "@T:SectGate",
            (RUAN, "Servants in pink. Both fires. The Cinder Cloud and the Hundred Wells are embracing. Crying. It's very awkward. It's lovely."),
            foe="demon_cultivator", foe2="demon_cultivator", prop="seal", thing="the formation"),
          B("hunt", "Demon Cultivators, the Camp's Retreat",
            "The demon cultivators who set the fires scatter into the outer pines, and Thunder Peak insists on running them down.",
            foe="demon_cultivator", v=0),
          B("gather", "Jade Slips for the Conclave's Second Record",
            "Elder Bai wants the second day's proceedings recorded as carefully as the first, threads and all.",
            item="jade_slip", v=0),
          B("social", "The Cinder Cloud and Hundred Wells, Formalized",
            "The two sects, embracing after the fire, formally announce a permanent alliance on the spot, much to Lu Ping's delight.",
            (LU, "An alliance! Forming right in front of me! I get to write it down! This is the best conclave I've ever attended! It's the only one!"),
            v=0),
          B("hunt", "Sparring Disciples, Celebrating Too Hard",
            "The newly allied sects celebrate with a sparring exhibition that gets slightly out of hand.",
            foe="sparring_disciple", count=4, v=0),
          B("gather", "Incense for the Formation's Long Day",
            "The Great Azure Formation, strained from a full day of shielding camps, needs incense offerings to steady it overnight.",
            item="incense", v=0),
          B("probe", "The Threads, Recounted",
            "Han Xue does a final count of Lady Silk's cut threads, cross-referencing which sects were targeted and why.",
            (HAN, "She targeted the sects with the most to lose and the least trust in each other. Efficient. I almost respect it. Almost."),
            v=0),
          B("social", "Ruan Hai's New Ease",
            "Ruan Hai, freed from Lady Silk's tugging, admits he hasn't felt this calm in a conclave hall in decades.",
            (RUANHAI, "I don't know if it's you or just not being pulled at anymore. Probably both. Thank you, either way."),
            v=0),
          B("hunt", "Iron Scale Disciples, the Late Watch",
            "A late watch of Iron Scale disciples, still wound up from the day's excitement, spar off their energy against the puppets.",
            foe="iron_scale_disciple", v=0),
          B("gather", "Letters for the Absent Sects",
            "A few invited sects never arrived, and Lu Ping wants letters sent checking on them, just in case Lady Silk reached them first.",
            item="letter", v=0),
          B("social", "Bai Ling's Growing Suspicion",
            "Bai Ling, cross-referencing more records, grows suspicious that Lady Silk's threads reach further than the conclave alone.",
            (BAI, "I think she's been pulling strings outside this mountain too. For months. Maybe years. I need more books. I need more time."),
            v=0),
          B("stage", "Carrying Forty",
            "At the end of the second day, you sit on the formation and carry forty sects. It's heavier than a mountain. It's lighter than you feared.",
            "@M:FormationArray", ">Carry the forty sects on the formation",
            (N, "Forty sects, two thousand breaths. Somewhere among them, a woman in pink, holding her breath, very angry. You carry her too."),
            (N, "Middle stage of Body Integration. Your vehicle has room for more than you thought."),
            "@T:SectGate",
            (HAN, "You're carrying her too, aren't you. Lady Silk. I can see it on your face. You're carrying the spider."),
            (HAN, "...That's either very foolish or very wise. The hermit would say both. I say be careful."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 75
    C("Threads Between Sects", "sect",
      "The conclave agrees on everything except the thing that matters: who holds the Lotus Key when the fold opens. "
      "Lady Silk has one thread left, and she ties it to the oldest wound in the room, the question the Iron Scale gave up "
      "at the Nine Banners.",
      cast=[YUN, RUANHAI, RUAN, TIANLU, JING, HAN, ZHAO, WEI, LAN], foes=["demon_cultivator", "iron_scale_disciple", "void_wraith"],
      items=["letter", "jade_slip", "spirit_herb"], props=["jade_slip", "seal", "stone_stele"],
      beats=[
          B("orders", "The Old Question",
            "On the third day of the conclave, someone asks who should hold the Lotus Key. The room goes cold.",
            (RUANHAI, "The Iron Scale gave up that question at the banners. We don't raise it. But forty sects didn't give it up. They're asking."),
            "@R:MainHall", (N, "The main hall is silent. Forty sect masters look at you. Somewhere at the back, a woman in pink silk is very still."),
            "@T:FormationArray",
            (TIANLU, "It's a fair question. The key opens the seal. The seal holds the Patriarch. Should one young person carry all of that?"),
            (TIANLU, "I ask as an old man who likes you. Not as a Zhao. Answer honestly."),
            ),
          B("social", "An Honest Answer",
            "You answer honestly. It's not the answer anyone expected.",
            (P, "No. One person shouldn't carry it. That's the mistake the founders made. The Verdant Lotus gave everything and everyone forgot."),
            (P, "I'll carry the key. You carry me. All of you. When the fold opens, I walk in front, and you walk beside me. That's the only answer."),
            "|",
            (JING, "The Moon-Well accepts that answer. Carry the key. We'll carry the carrier."),
            ),
          B("probe", "The Last Thread",
            "Lady Silk's last thread is on the one sect master who hasn't answered. The Cinder Cloud's master stands, eyes glazed.",
            "@R:MainHall", (N, "The Cinder Cloud's master stands. His eyes are glazed pink. He says, in a voice not quite his own: the key should go to the Silk Pavilion."),
            "@I:MainHall", ">Trace the last thread with your soul",
            (N, "One thread, thick as rope, from the Cinder Cloud master to the woman in pink. She's pulling with everything she has."),
            "@T:FormationArray",
            (HAN, "She's pulling hard. Too hard. She's exposed herself. Everyone felt that. Everyone's looking at her now."),
            prop="seal", thing="the last thread"),
          B("battle", "The Spider Runs",
            "Exposed, Lady Silk doesn't fight. She runs, and her servants cover her escape with fire and pink smoke.",
            (ZHAO, "She's running! Pink smoke everywhere! Her servants are throwing fire! In the main hall! That's the founder's tablet in there!"),
            "@F:FormationArray",
            "@F2:SectGate",
            "@T:SectGate",
            (ZHAO, "The founder's tablet is safe. The faded green lotus beside it is safe. Lady Silk is gone. Down the back path. Toward Qingshi."),
            foe="demon_cultivator", foe2="demon_cultivator"),
          B("social", "The Conclave Decides",
            "With Lady Silk gone, the conclave decides in an hour what it couldn't decide in three days.",
            (YUN, "The key stays with its bearer. Forty sects walk beside the bearer when the fold opens. The Great Vehicle. All in favour."),
            "|",
            (RUANHAI, "The Iron Scale. In favour."),
            (TIANLU, "The Zhao clan. In favour. In gold."),
            (JING, "The Moon-Well. In favour. Singing."),
            ),
          B("gather", "Signatures on One Scroll",
            "Forty sects sign one scroll. It takes a long time. Some sects have very long names.",
            (LU, "Forty signatures! On one scroll! The Hundred Wells has a very long name! It took them ten minutes! The scroll's going to need an extension!"),
            "@G:MainHall", ">Collect the forty sects' seals",
            "@T:FormationArray",
            (BAI, "The scroll of the Great Vehicle. Forty seals. I'm putting it in the pagoda. On the top shelf. Above the turtle soup. Where it belongs."),
            item="letter", noun="sect seals"),
          B("probe", "Where Silk Goes",
            "Lady Silk fled toward Qingshi. The hermit says spiders always go where they've already spun.",
            (LAN, "Spiders go home to their webs. She's spun in Qingshi before. Many times, I'd guess. Look for the places where people quarrel too easily."),
            "@I:Pagoda", ">Read Madam Fang's crane about Qingshi",
            (N, "A crane from Madam Fang: the town's been quarrelling for months. Over nothing. Neighbours who've been friends for forty years. It started last spring."),
            "@T:SectGate",
            (HAN, "Last spring. When the Silk Pavilion's envoy first 'visited' the region. She's been weaving Qingshi for a year. We didn't notice."),
            prop="jade_slip", thing="Madam Fang's crane"),
          B("defend", "Webs on the Mountain",
            "Before you go after her, you have to clear the webs she left on the mountain. They're in the camps, the hall, the pagoda.",
            (WEI, "Pink threads everywhere! On my twelve! On the chicken! She threaded the chicken! That's a new low!"),
            "@I:TrainingGround", ">Cut the threads from Wei Tong's disciples",
            (N, "One by one the threads snap. Wei Tong's twelve blink, shake their heads, and stop glaring at each other."),
            "@F:TrainingGround",
            "@F2:OuterPines",
            "@T:WeaponRack",
            (WEI, "The chicken's free. The chicken's fine. Qiu Hua's crying. The chicken isn't. Chickens don't cry. The chicken has seen too much."),
            foe="void_wraith", foe2="demon_cultivator", prop="seal", thing="the threads"),
          B("cultivate", "Carrying a Web",
            "The hermit says: to unravel a web, you have to hold every thread at once. Only a body of many can do that.",
            (LAN, "Hold every thread at once. Every quarrel she started. Carry them all, and they'll untangle, because you'll be too heavy to pull."),
            "@M:LotusPond", ">Hold every thread of the web at once",
            (N, "A thousand quarrels. You hold them all, and they hang slack, because nobody is pulling any more. Some of them snap. Some of them become friendships."),
            "@T:StoneBridge",
            (LAN, "The mountain's free of her. Now the town. Go. Take someone who's good with gossip. Actually, the town has someone better."),
            ),
          B("hunt", "Demon Cultivators, Silk's Rearguard",
            "A handful of demon cultivators left behind to cover Lady Silk's escape make a final stand near the outer pines.",
            foe="demon_cultivator", v=0),
          B("gather", "Jade Slips for the Scroll's Archive Copy",
            "Elder Bai insists on a full archive copy of the Great Vehicle scroll before the original ever leaves the pagoda.",
            item="jade_slip", v=0),
          B("social", "Wei Tong's Chicken, Debriefed",
            "Wei Tong holds a solemn debriefing with the chicken, insisting it deserves to know it survived a Rung's web intact.",
            (WEI, "You were threaded by a Sixth Rung and you didn't even blink. Elder Drumstick, you're the bravest chicken in this sect."),
            v=0),
          B("hunt", "Iron Scale Disciples, Working Off Anger",
            "Ruan Jingtao's disciples, furious on his behalf, work off their anger against the training puppets before the journey to Qingshi.",
            foe="iron_scale_disciple", v=0),
          B("gather", "Spirit Herbs for the Journey Down",
            "Elder Hua packs spirit herbs for the trip to Qingshi, insisting a hunt for a Rung is no excuse to travel unprepared.",
            item="spirit_herb", v=0),
          B("probe", "The Cinder Cloud Master's Apology",
            "The Cinder Cloud's master, freed from Lady Silk's thread, apologizes to the whole hall for nearly derailing the vote.",
            (N, "He says it felt like watching himself from outside his own body. Forty sect masters nod. More than one of them knows that feeling now."),
            v=0),
          B("social", "Tianlu's Elder Abuse Complaint",
            "Zhao Tianlu formally files a complaint about elder abuse with Steward Qian, entirely for comedic effect, and Qian plays along.",
            (QIAN, "Complaint received. Filed under 'Zhao clan nonsense.' We have a very thick folder for that category."),
            v=0),
          B("hunt", "Void Wraiths, Drawn to the Broken Web",
            "The unraveling of Lady Silk's web across the mountain draws a small cluster of void wraiths to feed on the loose threads.",
            foe="void_wraith", v=0),
          B("gather", "Letters for the Sects Heading Home",
            "Several sects begin the journey home after the conclave, and Lu Ping wants farewell letters sent with each one.",
            item="letter", v=0),
          B("social", "Bai Ling's Web Diagram",
            "Bai Ling draws a full diagram of every thread Lady Silk spun on the mountain, hoping the pattern reveals where she'll strike next.",
            (BAI, "It's the same pattern as Qingshi. Old friendships, frayed slowly. She doesn't create hate. She just removes the trust holding peace together."),
            v=0),
          B("interlude", "Down to Qingshi",
            "The conclave agrees to wait while you go after Lady Silk. Ruan Jingtao and Zhao Kang insist on coming.",
            (RUAN, "The Iron Scale comes. She threaded my father. Nobody threads my father."),
            (ZHAO, "The Zhao clan comes. She threaded my great-grandfather. He's a hundred and twelve. That's elder abuse."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 76
    C("The Web Unravels", "qingshi_town",
      "Qingshi has been quarrelling for a year. Neighbours of forty years aren't speaking; the magistrate and the constable "
      "have fallen out; even Madam Fang and Iron-Fang argued over a dish. Lady Silk has woven the whole town, and somewhere "
      "in it, she's hiding at the centre of her web.",
      cast=[FANG, TIE, DU, ZHOU, LIU, PAN, JIN, RUAN, ZHAO], foes=["demon_cultivator", "rogue_cultivator", "void_wraith"],
      items=["letter", "medicine", "spirit_herb"], props=["seal", "treasure_chest", "jade_slip"],
      foe_names={"demon_cultivator": "silk servants"},
      beats=[
          B("orders", "A Town That Quarrels",
            "Qingshi's main street is full of people not speaking to each other. The silence is louder than shouting.",
            "@R:MainStreet", (N, "Neighbours cross the street to avoid each other. The noodle seller and the tea seller have put up a fence between their stalls."),
            "@T:MainStreet",
            (DU, "Nobody's talking. The magistrate and I had a row about a lost chicken three months ago. We haven't spoken since. It was a chicken."),
            (DU, "It feels like someone else's anger. I don't know how to explain it."),
            ),
          B("social", "Madam Fang and Iron-Fang",
            "Madam Fang and Iron-Fang have argued. Over a dish. They're both miserable. Neither will apologise.",
            (FANG, "He broke my favourite dish. On purpose, I said. By accident, he said. We haven't spoken in a month. The inn's very quiet."),
            "|",
            (TIE, "I didn't break it on purpose. I'd never. I love that dish. She loves that dish. I just... couldn't say it. Something stopped me."),
            "|",
            (P, "There's a thread on both of you. Pink. Lady Silk's. Let me cut it."),
            (TIE, "...I love that dish. I love this inn. Madam Fang, I'm sorry. I'll wash every dish forever. I was going to anyway."),
            ),
          B("probe", "Threads Across the Town",
            "In soul sight, the whole town is laced with pink threads, and they all lead to one place.",
            "@R:WatchTower", (N, "From the watchtower, in soul sight: pink threads across every street, every house, every friendship. They all lead to the temple."),
            "@I:WatchTower", ">Follow the threads with your soul",
            (N, "The temple. Hong's old temple, where the Rust Monk prayed. At its heart, a knot of pink, pulsing, and someone sitting in it, weaving."),
            "@T:MainStreet",
            (ZHAO, "The temple again. That temple has had a terrible few decades. I'm going to donate to it. Heavily. After we clear the spider out."),
            prop="seal", thing="the pink threads"),
          B("gather", "Mending Friendships",
            "Before you face her, the hermit's advice: carry the town. Cut the threads one friendship at a time.",
            (LIU, "The noodle seller and the tea seller. Forty years they shared a stall. Now there's a fence. Help me take it down."),
            "@G:MarketSquare", ">Take down the fences in the market",
            "@T:MainStreet",
            (LIU, "They're sharing tea and noodles again. The noodle seller cried into the tea. It's fine. It's salty tea now. People like it."),
            item="spirit_herb", noun="fence posts"),
          B("social", "The Magistrate and the Constable",
            "Magistrate Zhou and Constable Du haven't spoken in three months. Over a chicken.",
            (ZHOU, "Constable Du lost my chicken. My prize chicken. Three months ago. He said it wasn't his fault."),
            (DU, "It wasn't my fault. It was the fox. The one from the judgement. It came back. I should have said so. Something stopped me."),
            "|",
            (ZHOU, "...The fox? The clever one? Oh. Oh, Du. I'm sorry. I'm sorry. I'll buy a new chicken. We'll guard it together."),
            ),
          B("battle", "Silk Servants",
            "As the threads snap, Lady Silk's servants come out of hiding, desperate to reweave what's breaking.",
            (RUAN, "Servants in pink! Everywhere! They're trying to reweave the threads! Stop them before they tie anyone back up!"),
            "@F:MainStreet",
            "@F2:MarketSquare",
            "@T:MainStreet",
            (RUAN, "They're gone. The town's talking again. Loudly. I've never heard so many apologies at once. It's deafening."),
            foe="demon_cultivator", foe2="rogue_cultivator"),
          B("probe", "Jin's Guild Pigeons",
            "Merchant Jin's guild pigeons have been carrying messages for Lady Silk for a year. He didn't know. He's horrified.",
            (JIN, "My pigeons! My guild pigeons! Carrying her messages! For a year! Through my loft! I didn't know!"),
            "@I:Warehouse", ">Search the guild's pigeon loft",
            (N, "Tiny scrolls, tied to pigeon legs, all in pink silk. Orders. Quarrels to start. Friendships to cut. And one scroll: the heir's friends are next."),
            "@T:MainStreet",
            (JIN, "I'm going to burn the loft. No. I'm going to keep the pigeons and send honest messages. Forever. Just to spite her."),
            prop="treasure_chest", thing="the pigeon loft"),
          B("defend", "The Heir's Friends Are Next",
            "The last scroll said the heir's friends are next. Lady Silk's threads reach up the mountain, toward everyone you love.",
            (FANG, "Your friends! Up the mountain! She's threading them! Han Xue! Wei Tong! The Xiao children! Go! Go!"),
            "@I:TownGate", ">Send your soul up the mountain along the threads",
            (N, "Your soul runs up the pink threads like fire up a fuse. On the mountain, Han Xue, Wei Tong and the Xiao children blink, and the threads fall away."),
            "@F:TownGate",
            "@F2:Riverside",
            "@T:MainStreet",
            (ZHAO, "You cut the threads on the mountain from down here? With your soul? That's Body Integration? I'm going to need to sit down."),
            foe="demon_cultivator", foe2="void_wraith", prop="seal", thing="the threads"),
          B("cultivate", "The Town Carries Back",
            "Qingshi, freed from the web, does something unexpected: the whole town gathers in the square and holds hands. For you.",
            (DU, "The whole town. In the square. Holding hands. The magistrate's idea. He said the immortal carries us. We should carry back."),
            "@M:MarketSquare", ">Stand in the circle of the town",
            (N, "A thousand hands, and you in the middle. The town carries you. It's the lightest you've ever been. Your vehicle grows wider."),
            "@T:MainStreet",
            (ZHOU, "I've never held so many hands. I'm going to make a speech. One word. Hold. We held. I held. We all held."),
            ),
          B("interlude", "The Spider in the Temple",
            "Lady Silk has nowhere left to spin. She's in the temple, at the centre of a web that's falling apart. And then she isn't.",
            "@R:Temple", (N, "The temple is empty. At its heart, a knot of pink silk, unravelling, and a note in a beautiful hand."),
            "@T:MainStreet",
            (HAN, "I came down. I'm not threaded any more. She left a note. It says: come to the conclave's last night. I'll be the guest of honour."),
            (HAN, "She's going back up the mountain. Into the middle of forty sects. For one last trick."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 77
    C("Lady Silk", "sect",
      "The conclave's last night is a feast for forty sects on the formation plaza. Lady Si Rou, Sixth Rung of the "
      "Ladder, has promised to attend as guest of honour, and nobody knows what face, what thread, or what knife she'll "
      "bring.",
      cast=[YUN, HAN, WEI, ZHAO, RUAN, JING, TIANLU, LAN, LU, BAI], foes=["demon_cultivator", "void_wraith", "blood_guard"],
      items=["incense", "medicine", "letter"], props=["seal", "stone_stele", "bronze_bell"],
      boss=("rung_deacon", "Si Rou, Lady Silk", "FormationArray"),
      foe_names={"demon_cultivator": "silk servants"},
      beats=[
          B("orders", "The Last Feast",
            "The conclave's last feast. Forty sects on the formation plaza. Every lantern lit. Every guard watching. One empty seat.",
            (YUN, "Forty sects, one feast, one empty seat. She said she'd come. She will. Spiders keep their appointments."),
            "@R:FormationArray", (N, "Long tables on the plaza, lanterns on every pillar. At the head table, one seat is empty, draped in pink silk."),
            "@T:SectGate",
            (LU, "The empty seat's got pink silk on it! Nobody put it there! It was just there! I'm not sitting near it! I'm sitting near Wei Tong!"),
            ),
          B("social", "Watching Every Face",
            "At the feast, everyone watches everyone. It makes for very awkward conversation.",
            (WEI, "Everyone's watching everyone. Nobody's eating. It's the worst feast ever. I'm eating. Somebody has to."),
            "|",
            (JING, "The Moon-Well sings when it's nervous. We're about to sing. I apologise in advance."),
            "|",
            (TIANLU, "At my age, every feast might be the last. This one might actually be. I'm going to have the duck."),
            ),
          B("probe", "The Wine",
            "Halfway through the feast, you notice the wine. Every cup on every table has a thread of pink in it.",
            "@R:FormationArray", (N, "Every cup of wine on every table has a single pink thread floating in it, curled like a question mark."),
            "@I:FormationArray", ">Pull the threads from the wine with your soul",
            (N, "Two thousand threads rise out of two thousand cups at once and drift together, twisting, into a single silk rope above the empty seat."),
            "@T:SectGate",
            (BAI, "Silk in the wine. If everyone had drunk it... forty sects, threaded at once. She'd have had the whole alliance on a string."),
            prop="seal", thing="the wine"),
          B("battle", "Servants at the Tables",
            "When the threads leave the wine, Lady Silk's servants, disguised as serving staff, drop their trays.",
            (HAN, "The servers! Half of them are hers! Trays down, knives out! Protect the sect masters!"),
            "@F:FormationArray",
            "@F2:TrainingGround",
            "@T:SectGate",
            (RUAN, "My father hit one with a duck. A whole roast duck. He says it's the best thing he's done in years."),
            foe="demon_cultivator", foe2="demon_cultivator"),
          B("defend", "The Guest of Honour Arrives",
            "The silk rope above the empty seat twists, and becomes a woman in pink. The guest of honour has arrived.",
            (LU, "She's here! In the seat! She came out of the rope! I'm ringing the bell! I'm ringing it so hard!"),
            "@I:FormationArray", ">Raise the formation around the feast",
            (N, "The Great Azure Formation rises, blue, around every table. Two thousand guests inside it. One woman in pink, outside, smiling."),
            "@F:SectGate",
            "@F2:OuterPines",
            "@T:SectGate",
            (YUN, "Everyone's inside the formation. She's outside it, alone. Go. The whole alliance is watching. Carry them into this fight."),
            foe="blood_guard", foe2="void_wraith", prop="bronze_bell", thing="the formation"),
          B("social", "Lady Silk Speaks",
            "Lady Silk speaks to you from outside the formation, very politely, as if you were old friends.",
            (RUNG6, "Si Rou. Sixth Rung. Every alliance is a web, heir. I merely spin faster. You untangled mine. How rude. How impressive."),
            (RUNG6, "Five of my brothers and sisters gone. My thread is the last strong one before the Shadow. Come and cut it, if you can."),
            (P, "I'm not coming alone, Lady Silk."),
            (RUNG6, "No. I see that. Forty sects. What a heavy vehicle. Let's see if it breaks."),
            ),
          B("boss", "The Sixth Rung Falls",
            "On the formation plaza, before forty sects, you face Lady Silk. She fights with thread and knife and smile.",
            "@R:FormationArray", (N, "Lady Silk steps onto the plaza. Silk unspools from her sleeves like water. Two thousand people watch from behind the formation's light."),
            "@X",
            (RUNG6, "Such lovely manners. Such soft throats. Let's see how much you can carry, heir, when I cut the straps."),
            (P, "Everything. They're carrying me too."),
            "@I:FormationArray", ">Stand over the fallen Sixth Rung",
            (N, "Si Rou lies on the plaza. Her silk unravels around her. You carried them, she says. I only pulled. I never learned to carry. Her star goes out."),
            "@T:SectGate",
            (HAN, "Six. Six stars out. One left. The Shadow. The one nobody's seen. Forty sects watched you do it. They're cheering. Listen."),
            prop="seal", thing="the fallen Sixth Rung"),
          B("festival", "The Feast, Properly",
            "With Lady Silk gone, the feast begins again. Properly this time. Wei Tong makes sure of it.",
            (WEI, "Feast! Properly! No threads! No knives! Just duck and noodles and forty sects being ridiculous! Eat! Everyone eat!"),
            "@G:FormationArray", ">Carry dishes to all forty tables",
            "@I:FormationArray", ">Raise a cup to the alliance",
            (N, "Two thousand cups, raised together. No threads in any of them. The Moon-Well sings. The Iron Scale shouts. Thunder Peak shouts louder."),
            "@T:SectGate",
            (JING, "The Great Vehicle. Forty sects in one feast. Three hundred years since anyone saw this. Enjoy it. It won't come again for a while."),
            item="medicine", noun="feast dishes", prop="seal", thing="the raised cups"),
          B("stage", "Carrying Two Thousand",
            "After the feast, you sit on the empty plaza and carry everyone who was at it. Two thousand people. It's light.",
            "@M:FormationArray", ">Carry the whole alliance in stillness",
            (N, "Two thousand breaths, and more beyond them: towns, villages, mountains. Your vehicle is vast now, and still light. Late stage of Body Integration."),
            "@T:SectGate",
            (LAN, "You carried her too. At the end. Lady Silk. I saw it. She died being carried. That's more than most Rungs get."),
            ),
          B("interlude", "One Left",
            "Qing Luan's last crane before the isles sealed said the seventh star was different. Now you understand why.",
            (YUN, "One star left. The Seventh Rung. The Patriarch's Shadow. Nobody's ever seen them. Gu doesn't know. Ye Wuming doesn't know."),
            (YUN, "Whoever it is, they're closest to him. When they fall, the Ladder is gone. And the fold, Qing Luan said, will have to open."),
            "|",
            (HAN, "One left. Tomorrow, the alliance swears its oath. Then we get ready. For the Shadow. And for the sky."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 78
    C("The Oath of the Great Vehicle", "sect",
      "Forty sects swear one oath on the formation plaza: when the fold opens, they march together. Then they go home, "
      "to train, to wait, and to write monthly letters. The mountain empties slowly, like a tide going out.",
      cast=[YUN, RUANHAI, RUAN, TIANLU, JING, ZHAO, HAN, LU, QIAN, WEI], foes=["void_wraith", "training_puppet", "sparring_disciple"],
      items=["letter", "spirit_stone", "incense"], props=["stone_stele", "seal", "jade_slip"],
      things={"stone_stele": "the oath stele"},
      beats=[
          B("orders", "Carving the Oath",
            "The oath is to be carved on a new stele beside the Nine Precepts at the gate. Forty sects, forty lines.",
            (YUN, "A new stele. Beside the Nine Precepts. Forty lines, one for each sect. The oath of the Great Vehicle. Carve the first line."),
            "@R:SectGate", (N, "A new stele stands beside the old one at the gate. The Nine Precepts on the left. On the right, blank stone, waiting for forty lines."),
            "@I:SectGate", ">Carve the first line of the oath",
            (N, "You carve: when the fold opens, we walk together. The Azure Cloud. Then you hand the chisel to Ruan Hai."),
            "@T:SectGate",
            (RUANHAI, "The Iron Scale. We walk together. And we remember. I'll carve that. My hands are shaking. Old hands. Good hands."),
            prop="stone_stele", thing="the oath stele"),
          B("social", "Forty Lines",
            "Each sect carves one line. Some are solemn. Some are not. All of them are true.",
            (TIANLU, "The Zhao clan. We walk together, in gold. I've carved it very neatly. I've been practising calligraphy for a century."),
            "|",
            (JING, "The Moon-Well. We walk together, singing. Lian carved it. Her hand was steady. Mine wouldn't have been."),
            "|",
            (LU, "The Hundred Wells carved theirs and it took twenty minutes! The Cinder Cloud carved a joke! About the Hundred Wells! Everyone laughed! Even the Hundred Wells!"),
            ),
          B("gather", "A Ledger of Forty Letters",
            "Steward Qian insists on a system: every sect writes monthly. He will keep the ledger. He's never been so happy.",
            (QIAN, "Monthly letters! Forty sects! A ledger! I'll track every letter! Every reply! Every late one! This is the best day of my career!"),
            "@G:MainHall", ">Collect the sects' first monthly letters",
            "@T:SectGate",
            (QIAN, "Forty letters. All on time. Well, thirty-nine. The Zhao clan's was early. Of course it was. Gold is always early."),
            item="letter", noun="monthly letters"),
          B("social", "Ruan Jingtao's Farewell",
            "Ruan Jingtao leaves with the Iron Scale. He wants a spar before he goes. It's how the Iron Scale says goodbye, apparently. Also the Zhao clan.",
            (RUAN, "A spar before I go. The Iron Scale says goodbye with swords. So does the Zhao clan, Zhao Kang says. Everybody says goodbye with swords except the Moon-Well."),
            (P, "The Moon-Well says goodbye with songs."),
            (RUAN, "...Maybe we should all try songs. After the spar. Pick up a sword."),
            "@F:TrainingGround", ">Spar with Ruan Jingtao's escort",
            "@T:SectGate",
            (RUAN, "Draw. Obviously. Draws are the only honest ending between friends. See you at the fold. I'll be the one in green, shouting."),
            foe="iron_scale_disciple", count=3),
          B("battle", "The Tide Goes Out",
            "As the sects leave, the wraiths that followed them come with them, drifting after the last banners down the steps.",
            (HAN, "Wraiths trailing the last banners. Like gulls after boats. Clear them before they follow anyone home."),
            "@F:SectGate",
            "@F2:OuterPines",
            "@T:SectGate",
            (HAN, "The steps are clear. The last banners are gone. The mountain's quiet. I miss the noise. Don't tell anyone."),
            foe="void_wraith", foe2="void_wraith"),
          B("social", "The Zhao Ancestor's Last Words",
            "Zhao Tianlu stays a day longer than the others. He's a hundred and fourteen. He wants to say something.",
            (TIANLU, "I'm a hundred and fourteen. I may not be alive when the fold opens. My great-grandson will march in my place."),
            (TIANLU, "Look after him. He's very bad at being looked after. He complains. Let him. It's how he knows he's loved."),
            "|",
            (ZHAO, "He said that? About me? To you? ...He's going to live forever, that old man. He's too stubborn to die. Like me."),
            ),
          B("cultivate", "An Empty Mountain",
            "With the sects gone, the mountain feels empty. The hermit says the Great Vehicle includes carrying absence.",
            (LAN, "Empty mountain. Two thousand people gone home. Carry them anyway. They're still there, on their own mountains. Carry the distance too."),
            "@M:CliffEdge", ">Carry the departed sects from the cliff",
            (N, "Forty sects, forty mountains, scattered across the land. You carry them all, even from here. The distance is light."),
            "@T:SectGate",
            (LAN, "You're getting good at this. Too good. Heaven will notice soon. It always notices people who carry too much."),
            ),
          B("probe", "Qing Luan's Last Crane",
            "A crane arrives from the closed Sky Isles, dim and flickering. Qing Luan's voice, very faint.",
            (LU, "A crane! From the isles! They're closed! How did it get out? It's very dim! It's saying your name!"),
            "@I:CliffEdge", ">Listen to Qing Luan's faint crane",
            (N, "Lotus child. Six stars out. The seventh is moving. Toward the Abyss. And heaven is leaning down to look at you. Your tribulation is coming."),
            "@T:SectGate",
            (YUN, "Your tribulation. Heaven's noticed. Years yet, maybe. But it's started. The last stage before the sky: Tribulation Transcendence."),
            prop="seal", thing="the faint crane"),
          B("social", "What Comes After the Body",
            "The Sect Master explains the stage beyond: not a realm you reach, but a sky you survive.",
            (YUN, "Mahayana first. Then Tribulation Transcendence. You don't reach that one. Heaven sends it. Nine bolts, and the ninth is the heart. You survive it, or you don't."),
            (YUN, "Nobody from the Azure Cloud has faced it in three hundred years. Your founder did. She survived. Barely. She never talked about the ninth bolt."),
            "|",
            (HAN, "Years yet. We'll prepare. We'll break the last Rung. We'll open the fold. Then the sky. In that order. Nobody skip ahead."),
            ),
          B("interlude", "Letters From Forty Mountains",
            "A month later, forty letters arrive on time. Steward Qian reads them all aloud at dinner. Nobody minds.",
            (QIAN, "Forty letters! On time! The Iron Scale's training! The Moon-Well's singing! The Zhao clan's rich! The Hundred Wells has a new well!"),
            (QIAN, "I've never been so happy to count anything. Forty. Every month. For as long as it takes."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 79
    C("Teaching the Many", "bamboo_forest",
      "The alliance sends its young disciples to the Verdant Lotus ruins, to learn the Heart Sutra from the hermit and "
      "the Great Vehicle from you. The ruins, which held three hundred years of silence, are suddenly full of children "
      "arguing about roots, stems and blossoms.",
      cast=[LAN, HAN, SHI, MAN, LIUER, YE, WEI, JING], foes=["stone_golem", "spirit_wolf", "void_wraith"],
      items=["jade_slip", "spirit_herb", "rune_fragment"], props=["stone_stele", "seal", "jade_slip"],
      foe_names={"stone_golem": "old sentinels"},
      beats=[
          B("orders", "A School in the Ruins",
            "The hermit has turned the Verdant Lotus ruins into a school. Three hundred young disciples from forty sects. One old man.",
            (LAN, "Three hundred children. Forty sects. One old man. And you. Mostly you. I'm very old. I get tired after lunch."),
            "@R:bamboo_forest/RuinsInner", (N, "The ruins' courtyard is full of children in forty colours, sitting in rows, arguing about which verse of the sutra is best."),
            "@T:AncientShrine",
            (LAN, "They're arguing. About the sutra. Three hundred years of silence in these ruins and now they're arguing. It's the best sound I've ever heard."),
            map="sect"),
          B("social", "Teaching Roots",
            "Your first lesson: the root. Patience. Three hundred children are not patient.",
            (LIUER, "I'm helping teach! I'm teaching roots! Patience! They're very impatient about patience!"),
            "|",
            (SHI, "I'm teaching them to count breaths. Four in, four out. The Iron Scale children count loudly. The Moon-Well children sing it."),
            "|",
            (MAN, "I'm teaching herbs. I've only dropped four. The children think dropping is part of the lesson. I'm not correcting them."),
            ),
          B("train", "Old Sentinels, New Students",
            "The ruins' old stone sentinels don't understand children. The children want to fight them. Carefully.",
            (HAN, "The sentinels woke up when the children arrived. They think it's an invasion. It kind of is. Show the students how. Carefully."),
            "@F:RuinsGate", ">Demonstrate on the old sentinels",
            "@T:AncientShrine",
            (HAN, "The sentinels have sat down. The children are climbing them. The sentinels seem... happy? Can stone be happy? These look happy."),
            foe="stone_golem", count=3),
          B("gather", "Sutra Slips for Everyone",
            "Every child needs a copy of the sutra. The hermit has one. The drowned archive has more, if someone will dive.",
            (LAN, "The archive under the courtyard. Dry now, mostly. There are copies of the sutra down there. Hundreds. Bring them up."),
            "@G:RuinsInner", ">Carry sutra slips up from the archive",
            "@T:AncientShrine",
            (LAN, "Three hundred copies. For three hundred children. My masters wrote these for a school that died. Now there's a school again."),
            item="jade_slip", noun="sutra slips"),
          B("hunt", "Wolves Come to Class",
            "The forest's wolves have come to see what the noise is. The children want to pet them. Some of them shouldn't be petted.",
            "@R:Clearing", (N, "Grey wolves at the edge of the clearing, curious. The children are delighted. One wolf has purple eyes."),
            "@F:Clearing",
            "@G:Clearing", ">Gather the scared students",
            "@T:AncientShrine",
            (YE, "Void-touched wolves near children. I don't like it. I'll stay with the school. My own children can help. They know about being scared."),
            foe="spirit_wolf", item="spirit_herb", noun="scattered students"),
          B("social", "Ye Wuming's Children Teach",
            "Ye Wuming's children, once the Blood Moon's, now teach the alliance's children how to tell a trap from a friend.",
            (YE, "Spring's teaching. River's teaching. Small Mountain's teaching the youngest ones to hide. He's very good at hiding. It's his gift."),
            (YE, "They were weapons once. Now they're teachers. That's the whole war, isn't it. Turning weapons into teachers."),
            "|",
            (JING, "The Moon-Well children are learning from Blood Moon children. Three hundred years ago that would have been a war. Now it's a class."),
            ),
          B("cultivate", "Teaching the Blossom",
            "The last lesson is the blossom: compassion. The hermit asks you to teach it. He says he only just learned it himself.",
            (LAN, "The blossom. You teach it. I only learned it last year, from a hollow man. You've been living it since you were a child."),
            "@M:RuinsInner", ">Teach the blossom to three hundred children",
            (N, "You don't explain it. You carry them, all three hundred, and let them feel it. One by one, they go quiet. Then they carry each other."),
            "@T:AncientShrine",
            (LAN, "Three hundred children, carrying each other. In my masters' courtyard. I'm going to cry. I'm old. I'm allowed."),
            ),
          B("defend", "Wraiths at the School",
            "Wraiths come for the school at night, drawn by three hundred young souls. The children stay calm. They were taught.",
            (HAN, "Wraiths at the ruins! Three hundred children! Stay calm! ...They are calm. They're counting breaths. All of them. Together."),
            "@I:RuinsInner", ">Raise the old Verdant Lotus ward over the school",
            (N, "The ward rises green over the courtyard, stronger than ever, fed by three hundred children counting breaths at once."),
            "@F:RuinsGate",
            "@F2:AncientShrine",
            "@T:Clearing",
            (WEI, "I came to bring food for three hundred children and walked into a battle. The children are fine. The food is fine. I'm fine. Mostly."),
            foe="void_wraith", foe2="void_wraith", prop="seal", thing="the old ward"),
          B("probe", "The Hermit's Successor",
            "The hermit has been watching one child especially: Qiu Hua, Wei Tong's disciple, the girl with the chicken.",
            (LAN, "Qiu Hua. The girl with the chicken. She reached the blossom today. Nine years old. It took me three hundred."),
            "@I:AncientShrine", ">Read Qiu Hua's sutra copy",
            (N, "In the margin of her sutra copy, in a nine-year-old's hand: the chicken is also carrying me. Beside it, a drawing of a chicken."),
            "@T:Clearing",
            (LAN, "She'll teach it after me. The Verdant Lotus has a future. A future that brings a chicken to class. My masters would approve."),
            prop="jade_slip", thing="Qiu Hua's sutra copy"),
          B("interlude", "The School Stays",
            "The alliance decides the school will stay. Every year, forty sects will send children to the Verdant Lotus ruins.",
            (JING, "The school stays. Every year. Forty sects' children, in the Verdant Lotus ruins. The Moon-Well will send teachers. And songs."),
            "|",
            (LAN, "The Verdant Lotus is a school now. Not a sect. A school. That's better. Sects fall. Schools grow."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 80
    C("A Vehicle for Ten Thousand", "blood_abyss",
      "The alliance's first joint action: every sect sends fighters to the Abyss rim, to seal the rifts leaking from the "
      "fold before they reach anyone's home. Forty sects, one rim, one heir in the middle carrying all of them.",
      cast=[YUN, RUAN, ZHAO, HAN, JING, YE, TIE, WEI, GU], foes=["void_wraith", "blood_guard", "void_colossus"],
      items=["void_shard", "medicine", "demon_core"], props=["seal", "demon_obelisk", "stone_stele"],
      boss=("void_colossus", "The Fold's Guardian", "BoneField"),
      foe_names={"blood_guard": "fold-born guards"},
      beats=[
          B("orders", "Forty Sects at the Rim",
            "Forty sects' fighters gather at the Abyss rim. It's the largest army the world has seen in three hundred years.",
            (YUN, "Forty sects at the rim. Not to march. Not yet. To seal the rifts. To practise walking together. Carry them."),
            "@R:blood_abyss/CanyonEntrance", (N, "The canyon rim is a sea of banners: green, gold, white, blue, and forty more. The fold hums below them like a disturbed hive."),
            "@T:CanyonEntrance",
            (YE, "Forty sects. At the rim. My children are crying. They never imagined anyone would come. Now everyone has."),
            map="sect"),
          B("battle", "Fold-Born Guards",
            "The fold feels forty sects at its edge, and spits out everything it has.",
            (RUAN, "They're coming out of the fold! Guards made of nothing! Iron Scale, left flank! We practised this! On Remembering Hill!"),
            "@F:BoneField",
            "@F2:BloodPools",
            "@T:CanyonEntrance",
            (RUAN, "Forty sects fighting as one. I've never seen anything like it. Nobody has. For three hundred years, nobody has."),
            foe="blood_guard", foe2="void_wraith"),
          B("gather", "Rift Shards for Forty Wards",
            "Each sect needs a shard from the fold to anchor its ward. You gather them, one for each sect.",
            (JING, "Each sect needs a shard to anchor its ward. Forty shards. Forty wards. One ring around the fold."),
            "@G:BloodPools", ">Gather forty shards from the fold's edge",
            "@T:CanyonEntrance",
            (JING, "Forty shards, forty wards. The Moon-Well will sing while we set them. Everyone else will shout. It'll be very noisy."),
            item="void_shard", noun="fold shards"),
          B("probe", "Forty Wards Around the Fold",
            "Forty sects set forty wards around the fold at once. You hold them all together.",
            "@R:ObeliskRing", (N, "Forty wards rise around the fold like a crown of light. Each one flickers. Each one needs someone to hold it steady."),
            "@I:ObeliskRing", ">Hold all forty wards at once",
            (N, "You hold them all. Forty sects, forty wards, one ring. The fold shudders, and shrinks, and for the first time since it formed, stops leaking."),
            "@T:CanyonEntrance",
            (HAN, "It stopped. The fold stopped leaking. Forty sects did that. You did that. We all did that. I'm going to sit down on this bone."),
            prop="seal", thing="the forty wards"),
          B("social", "Gu at the Rim",
            "Gu Hanshan, in chains, watches the forty wards rise. He asks to say something to the alliance.",
            (GU, "I betrayed the Azure Cloud. I fed children to the Abyss. I altered the formation that killed Mo Changfeng."),
            (GU, "And I am here, in chains, watching forty sects do what I thought was impossible. I was wrong about everything. That's all. Thank you."),
            "|",
            (YUN, "He asked me to let him say it. I let him. Some things should be said in front of everyone."),
            ),
          B("boss", "The Fold's Guardian",
            "The fold doesn't like the wards. Something enormous climbs out of it: a colossus of nothing, built to guard the door.",
            "@R:BoneField", (N, "The fold bulges. Out of it climbs a colossus of purple stone and nothing, taller than the canyon wall, eyes like holes in the sky."),
            "@X",
            (ZHAO, "It's huge! It's very, very huge! Forty sects, one giant! I like those odds! I'm lying! Hit it anyway!"),
            "@I:BoneField", ">Seal the colossus back into the fold",
            (N, "The colossus falls, and the forty wards pull it back into the fold, and the fold closes behind it like a mouth closing on a secret."),
            "@T:CanyonEntrance",
            (TIE, "Forty sects and a giant. Iron-Fang's men fought beside the Zhao clan. The Zhao clan paid us. In gold. We gave it back. We're honest now."),
            prop="seal", thing="the fold"),
          B("hunt", "What's Left",
            "With the colossus sealed, the last wraiths wander the bone field, lost. The alliance hunts them together.",
            "@R:DemonCamp", (N, "The old war camp is overrun with lost wraiths, drifting, purposeless now that the fold has stopped feeding them."),
            "@F:DemonCamp",
            "@G:DemonCamp", ">Gather the demon cores they leave",
            "@T:CanyonEntrance",
            (WEI, "I brought food for forty sects! To the Abyss! It's a very bad place for a picnic! We're having one anyway!"),
            foe="void_wraith", item="demon_core", noun="demon cores"),
          B("festival", "A Picnic in the Abyss",
            "Wei Tong's picnic for forty sects on the bone field is the strangest meal anyone has ever eaten. Everyone attends.",
            (WEI, "Dumplings for forty sects! On the bone field! It's disgusting here! Eat anyway! For morale! For Elder Mo!"),
            "@G:BoneField", ">Hand out Wei Tong's dumplings",
            "@I:CanyonEntrance", ">Raise a cup at the rim with forty sects",
            (N, "Forty sects, eating dumplings on a field of bones, under a sky the colour of a bruise. Somebody laughs. Then everybody laughs."),
            "@T:CanyonEntrance",
            (JING, "A picnic. In the Abyss. The Moon-Well will sing about this for a hundred years. It'll be a very strange song."),
            item="medicine", noun="dumplings", prop="seal", thing="the cups"),
          B("stage", "A Vehicle for Ten Thousand",
            "At the rim, with forty sects around you and the fold sealed below, you carry them all, and your Body Integration reaches Great Perfection.",
            "@M:AbyssDepths", ">Carry ten thousand in the stillness of the depths",
            (N, "Ten thousand souls. Forty sects. Villages beyond them. You carry them all, and far above, heaven's attention settles on you like weather."),
            (N, "Great Perfection of Body Integration. The sky is leaning down to look at you. Your tribulation is gathering."),
            "@T:CanyonEntrance",
            (YUN, "I felt it. Heaven, looking at you. The whole alliance felt it. Your tribulation isn't years away any more. It's gathering."),
            ),
          B("interlude", "Heaven Takes Notice",
            "On the way home, the sky over the sect is strange: clouds turning slowly in a spiral, directly above your room.",
            (HAN, "The clouds over the sect are spiralling. Directly over your room. Wei Tong says it's weather. It's not weather."),
            (HAN, "It's heaven. Taking notice. Qing Luan was right. The last stage before the sky is starting. Tribulation Transcendence."),
            ),
      ]),
]
