"""Volume II · Foundation Establishment — new chapters 13-20 (after the Inner
Sect Tournament, before the descent into the Blood Moon Abyss).

Gu Hanshan has fled through the teleport array and burned its route behind
him. The sect cannot follow at once: the Azure Eye is cracked, the Law Hall is
hollow, and the forest wards Gu kept have failed. Inner-sect duties, alchemy,
a beast tide, the hermit's second verse and the Crimson Road lead to the eve
of the descent. Xiao Shi is still in the cages; Ye Wuming is still a stranger.
"""

from .dsl import N, P
from .npcs import *  # noqa: F401,F403
from .saga_gen import B, C

CHAPTERS = [
    # ------------------------------------------------------------------ chapter 13
    C("The Burned Array", "sect",
      "The morning after the traitor fled, the teleport array's route to the Abyss is slag, the Azure Eye is cracked, "
      "and the Law Hall is a row of empty chairs. Before anyone can follow Gu Hanshan, the sect has to find out who "
      "else was helping him.",
      cast=[YUN, HAN, BAI, MO, HUA, MAN, LU, WEI], foes=["demon_cultivator", "sparring_disciple"],
      items=["jade_slip", "spirit_stone", "letter"], props=["teleport_array", "jade_slip", "treasure_chest"],
      foe_names={"sparring_disciple": "Law Hall turncoats"},
      beats=[
          B("orders", "Slag Where the Array Stood",
            "The Sect Master promised to follow Gu into the Abyss at dawn. At dawn, she finds out why that is impossible.",
            (YUN, "I said tomorrow we go after him. I was angry, and I was wrong. Look at the array."),
            (YUN, "He burned the Abyss route behind him. The jade is slag. It will take weeks to lay it again."),
            "@I:TeleportArray", ">Examine the burned teleport array",
            (N, "The array's outer ring is melted glass. Scorched into the stone, still faintly warm, is a single character: Lan."),
            "@T",
            (HAN, "His daughter's name. He signed his escape with it."),
            (HAN, "Whatever he was promised, he believes it. That makes him more dangerous, not less."),
            prop="teleport_array", thing="the burned array"),
          B("probe", "The Empty Chairs of the Law Hall",
            "The Law Hall's disciples are being questioned one by one. Han Xue wants you there, to watch their faces.",
            (HAN, "Eleven Law Hall disciples. One of them carried the Frenzy Pills. Maybe more. I want you to watch their faces while I ask."),
            "@R:ScholarRock", (N, "Beyond the scholar rock, the Law Hall's chairs stand in a neat row. Only ten of the eleven are occupied."),
            "@I:ScholarRock", ">Search the empty Law Hall desk",
            (N, "The eleventh desk has been cleared in a hurry. Wedged behind a drawer: a Frenzy Pill box, and a crescent drawn in ink."),
            "@T",
            (HAN, "Pei Rong. The one who carried the boxes. He ran in the night, toward the outer pines."),
            (HAN, "The pines are thick and he doesn't know them. We do. Let's go and introduce ourselves."),
            prop="treasure_chest", thing="the empty desk"),
          B("hunt", "Grey Robes in the Pines",
            "The runaway Law Hall disciple has friends waiting beyond the wall. They wear grey by day and crimson by night.",
            "@R:OuterPines", (N, "Grey robes flutter between the pines. Too many for one runaway. They have been waiting for him."),
            "@F:OuterPines", (HAN, "Law Hall grey on the outside, Blood Moon red underneath. Take them alive if you can!"),
            "@G:OuterPines", ">Recover the letters they scattered",
            "@T",
            (HAN, "Pei Rong's alive. Barely. He's crying and saying it was for his family. Everyone has a family, apparently, except the Blood Moon."),
            (P, "They hold families. That's how they own people. Gou's list said the same thing."),
            foe="sparring_disciple", item="letter", noun="scattered letters", ally=HAN),
          B("social", "Bai Qiu Counts His Scrolls",
            "Elder Bai is back among his shelves, bandaged and furious, counting everything Gu touched.",
            (BAI, "Forty years we shared tea. He took the master diagram of the seal, and my second-best inkstone. I miss the inkstone more today."),
            (BAI, "That's a lie. I miss the tea. Help me count, disciple. Counting stops me thinking."),
            "|",
            (HUA, "Bai won't rest. I've given him a sleeping draught three times. He reads the label and puts it on a shelf."),
            (HUA, "Keep him company. Grief is easier to mend when someone else holds the other end of the bandage."),
            "|",
            (MAN, "Is it true? Elder Gu? The man who carried those pill boxes was his. And my brother... Is it all connected?"),
            (P, "I think so, Xiao Man. And I think it all leads to the same place."),
            (MAN, "Then go there. Please. Before it's too late. I'll keep the herbs ready. I won't even drop them."),
            ),
          B("probe", "Gu Hanshan's Study",
            "The Sect Master orders the traitor's rooms opened. Nobody has been inside in twenty years but him.",
            (YUN, "Open his rooms. I want every letter, every note, every lie. Han Xue has the key. Bring me what you find, not what you feel."),
            "@R:ScholarRock",
            (N, "Gu's study is spotless and bare. One brush, one inkstone, one portrait of a smiling girl with ink on her fingers."),
            "@I:ScholarRock", ">Read the letters in Gu's desk",
            (N, "Hundreds of letters, all addressed to Gu Lan, all unsent. Today you learned the ninth precept. You would have liked it."),
            "@T",
            (HAN, "Twenty years of letters to a dead girl. I wanted to hate him. It's harder now. I'm still going to try."),
            prop="jade_slip", thing="the unsent letters"),
          B("defend", "Fire in the Pagoda",
            "In the dead of night someone tries to burn what is left of the seal records. The pagoda bell wakes the mountain.",
            (LU, "Fire! In the pagoda! I saw them go in, three shadows, and I rang the bell twice, which is once more than required!"),
            "@I:Pagoda", ">Beat out the fire on the pagoda steps",
            (N, "Oil burns on the lowest steps. You smother it with your robe and your qi. Above, glass breaks on the fourth floor."),
            "@F:Pagoda", (N, "Masked figures drop from the pagoda's eaves, blades out, oil flasks in their belts."),
            "@F:FormationArray",
            "@T",
            (BAI, "The fourth floor survived. My turtle soup recipes did not. I will never forgive them. Truly, this is war."),
            (BAI, "They came for what's left of the seal records. Gu must have told them what he couldn't carry."),
            foe="demon_cultivator", prop="seal", thing="the burning steps"),
          B("interlude", "Why We Wait",
            "The Sect Master explains why she will not march on the Abyss today, or tomorrow, and it costs her to say it.",
            (YUN, "Every disciple wants to charge into the Abyss after him. So do I. But the Azure Eye is cracked, and I am its keeper."),
            (YUN, "If I leave the mountain, the Eye goes dark. If the Eye goes dark, the seal has only one key left. Yours."),
            (P, "Then how do we follow him?"),
            (YUN, "Slowly. We rebuild the array. We find a way down on foot. We grow strong enough to survive the bottom."),
            "|",
            (MO, "She's right, and she hates it. So do I. So: we get strong. You first. You're behind schedule."),
            (MO, "Foundation Establishment, and still sloppy on the left side. Tomorrow, dawn."),
            ),
          B("gather", "Jade for a New Road",
            "Laying a teleport route to the Abyss again needs raw jade, and the treasury is suddenly careful with its stones.",
            (MO, "The array masters need raw jade to lay the Abyss route again. The treasury has some. Steward Qian has opinions."),
            "@T:IncenseBurner",
            (QIAN, "Raw jade! For a road to the worst place in the world! Do you know what that costs?"),
            (QIAN, "...Fine. Fine. But you dig the rest yourself. There's a seam in the herb terraces. Elder Hua will pretend not to see you."),
            "@G:HerbGarden", ">Dig raw jade from the terrace seam",
            "@T",
            (HUA, "You're digging up my terraces for a road to the Abyss. I'm pretending not to see. Dig faster; my pretending has limits."),
            item="spirit_stone", noun="raw jade"),
          B("cultivate", "A Place at Her Side",
            "The tournament's prize was a place at the Sect Master's side. She shows you what that means: the Azure Eye, from the inside.",
            (YUN, "You won a place at my side. Here is what it means. Sit on the Eye with me. Feel what I feel every day."),
            "@M:FormationArray", ">Sit within the Azure Eye beside the Sect Master",
            (N, "The formation rises around you like water. Somewhere deep in its pattern a thin crack runs, and through it, very faint, something is breathing."),
            (N, "It is patient. It is hungry. It knows your name."),
            "@T:FormationArray",
            (YUN, "You felt him. Three hundred years under the earth and he still breathes through a crack in my formation."),
            (YUN, "That is what I carry. Now you know why I don't sleep. Go and sleep for both of us."),
            ),
          B("interlude", "A Promise Without the Word",
            "Xiao Man has packed a bag. She intends to go to the Abyss herself. Somebody has to talk her out of it.",
            (MAN, "I packed a bag. Medicine, rope, a knife I don't know how to use. I'm going to the Abyss. Don't stop me."),
            (P, "Xiao Man, you faint when Elder Hua lances a boil."),
            (MAN, "Then I'll faint in the Abyss! At least I'll be closer!"),
            "|",
            (HUA, "Let her cry. Then give her something to do. I'll have her make medicine bundles for whoever goes. Hundreds."),
            (HUA, "Grief with work is survivable. Grief with nothing is a cliff edge."),
            "|",
            (MAN, "Hundreds of bundles. For whoever goes. You're going, aren't you? Don't promise. I hate promises now."),
            (P, "I'm going. I won't promise. I'll just bring him back."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 14
    C("Robes of the Inner Sect", "sect",
      "A tournament champion cannot stay an outer disciple. New robes, new duties, a champion from Thunder Peak who owes "
      "you his life, and a sect that looks at you differently now: some with hope, some with envy, all with questions.",
      cast=[YUN, MO, YAN, HAN, ZHAO, QIAN, WEI, LU], foes=["sparring_disciple", "training_puppet", "stone_golem"],
      items=["spirit_stone", "jade_slip", "spirit_herb"], props=["stone_stele", "jade_slip", "bronze_bell"],
      foe_names={"sparring_disciple": "inner disciples", "stone_golem": "peak guardians"},
      beats=[
          B("orders", "Blue Robes, Heavy Sleeves",
            "The Sect Master names you an inner disciple before the whole sect. The robes are blue, and the sleeves are very long.",
            (YUN, "By the tournament's law and my own wish, you are an inner disciple of the Azure Cloud. Kneel. Now stand. Don't trip on the sleeves."),
            "@R:FormationArray", (N, "A hundred disciples watch from the plaza. Some clap. Some don't. Lu Ping cheers loud enough for the ones who don't."),
            "@T:FormationArray",
            (MO, "Blue suits you. Don't let it go to your head; the sleeves are there to hide how much your arms shake."),
            (MO, "Inner disciples get a peak, a master and a thousand new ways to be embarrassed. Go and find out which peak wants you."),
            ),
          B("probe", "Every Peak Wants You",
            "Frost Sword, Thunder, Cloud and Cinder Peak all send letters. Every letter is very polite and slightly threatening.",
            (LU, "Four letters! Four peaks want you! Frost Sword, Thunder, Cloud and Cinder. Cinder's letter is on fire. Literally, a bit."),
            "@I:SectGate", ">Read the peaks' invitations",
            (N, "Frost Sword: discipline. Thunder: strength. Cloud: patience. Cinder: we have the best food. The last line is underlined twice."),
            "@T",
            (HAN, "Frost Sword Peak is my peak. I'm not going to tell you to choose it. I'm going to stand here and look disappointed until you do."),
            (P, "Can I choose the Sect Master's side and visit all four?"),
            (HAN, "That's the most diplomatic cowardice I've ever heard. She'll love it."),
            prop="jade_slip", thing="the invitations"),
          B("social", "Thunder Peak's Debt",
            "Yan Tie, the champion you saved from the Frenzy Pill, is on his feet again. He has come to repay a debt he cannot measure.",
            (YAN, "Yan Tie. You know me. You broke my ribs to save my life. I've come to say thank you, and to ask for a rematch."),
            (YAN, "Not now. When I've forgotten the taste of that pill. Some nights I still wake with red at the edges of my eyes."),
            (P, "Elder Hua says it passes."),
            (YAN, "Elder Hua says a lot of kind things. I'd rather hear them from someone who's been through it. So, you, eventually."),
            "|",
            (ZHAO, "The great Yan Tie, thanking a village brat. The world's gone upside down. I suppose I'll have to get used to it."),
            (ZHAO, "Don't tell him I said he fought well in the final. Before the pill. He did."),
            ),
          B("train", "Thunder Peak Trials",
            "Yan Tie invites you to Thunder Peak's morning trials, where the puppets are heavier and the disciples are louder.",
            (YAN, "Thunder Peak trains at dawn. We shout. It helps the qi. It also annoys Frost Sword Peak, which helps morale."),
            "@F:TrainingGround", ">Face Thunder Peak's heavy puppets",
            (YAN, "Louder! If the puppet can't hear you, it won't respect you!"),
            "@T:TrainingGround",
            (YAN, "Good. Your foundation is solid. Heavy, like a river stone. Most new inner disciples float. You sink. That's a compliment."),
            foe="training_puppet", count=5),
          B("gather", "The Inner Sect Allowance",
            "Inner disciples draw a real allowance. Steward Qian regards this as a personal tragedy.",
            (QIAN, "Inner allowance: twelve spirit stones a month. Twelve! When I was an inner disciple it was six, and we were grateful."),
            (QIAN, "Collect them from the donation boxes yourself. I refuse to hand over that many stones with my own hands. It's bad for my heart."),
            "@G:IncenseBurner", ">Collect your allowance from the donation boxes",
            "@T",
            (QIAN, "Twelve. Count them in front of me. Slowly. I want to say goodbye to each one."),
            item="spirit_stone", noun="allowance stones"),
          B("duel", "Envy Wears Blue Too",
            "Not every inner disciple is pleased that a village orphan skipped the line. Three of them want to test the new robes.",
            (ZHAO, "Three inner disciples from Cloud Peak are waiting at the training ground. They say you bought your victory with luck."),
            (ZHAO, "I said it was stubbornness, which is much worse to fight. They didn't listen. Go on. I'll hold your sleeves."),
            "@F:TrainingGround", ">Answer the Cloud Peak challenge",
            (N, "Three Cloud Peak disciples bow with exaggerated courtesy, and then do not wait for you to bow back."),
            "@T",
            (ZHAO, "Three. Hm. I would have beaten four. But you didn't use your elbows once, which Elder Mo will be pleased about."),
            (ZHAO, "The Zhao clan has always said envy is a compliment with a knife in it. Congratulations. You're being complimented."),
            foe="sparring_disciple", count=3),
          B("probe", "Duties of a Champion",
            "Your first task at the Sect Master's side: carry her orders around the mountain, and learn how a sect is actually run.",
            (YUN, "Take these to every peak master. Read them first. If you understand why I wrote each one, you'll understand the sect."),
            "@R:Pavilion", (N, "One order about rice, one about roof tiles, one about a disciple's mother who is ill. And one that says only: watch the Abyss road."),
            "@I:Pavilion", ">Read the Sect Master's orders",
            (N, "Every order is signed the same way, in small plain characters: Yun Qingyao, who is tired, and grateful."),
            "@T",
            (HAN, "She signs them like that? Every one? ...I never read the signatures. I should have."),
            prop="jade_slip", thing="the Sect Master's orders"),
          B("defend", "The Stone Guardians Wake",
            "The cracked Azure Eye leaks qi, and the old stone guardians of the peaks wake confused and angry.",
            (WEI, "The peak guardians are awake! The big stone ones! One of them sat on Cinder Peak's kitchen! Nobody's getting lunch!"),
            "@I:FormationArray", ">Calm the leaking formation",
            (N, "Qi spills from the crack in the Azure Eye like steam from a kettle. You press your palm to it until the hiss softens."),
            "@F:TrainingGround", (N, "Stone guardians lumber across the training ground, eyes glowing a confused and furious blue."),
            "@F:OuterPines",
            "@T",
            (WEI, "They went back to sleep! Mostly. One of them is still sitting on the kitchen. Cinder Peak says they're used to it."),
            foe="stone_golem", prop="seal", thing="the leaking formation"),
          B("social", "Different Eyes",
            "The mountain looks at you differently now. Some of the looks are warm. Some are measuring. One is Elder Mo's.",
            (LU, "The outer disciples have started bowing to you. I bowed to you this morning. It felt weird. Let's never do that again."),
            (LU, "Also, I've started a fan club. It has four members. Three of them are me under different names."),
            "|",
            (HAN, "Some of the inner disciples think you're the Sect Master's pet. Some think you're a Blood Moon spy. Nobody thinks you're ordinary."),
            (HAN, "Ordinary was nice while it lasted. Walk straight. They're watching."),
            "|",
            (MO, "I watched your spar with the Cloud Peak three. Adequate. The blue is heavy. It's supposed to be."),
            (MO, "Don't let it bend you. Let it hold you up. That's the only trick to wearing it."),
            ),
          B("stage", "Foundation Like River Stone",
            "Yan Tie called your foundation a river stone. Elder Mo agrees, and sends you to the cliff to prove it.",
            (MO, "River stone, Yan Tie says. River stones get smooth by sitting in the current for a very long time. Go and sit."),
            "@M:CliffEdge", ">Temper your foundation at the cliff edge",
            (N, "The wind off the sea of clouds pours over you like a river. Your foundation does not move. Layer by layer, it grows."),
            (N, "When you rise, you are heavier and lighter at once. Middle stage of Foundation Establishment."),
            "@T",
            (YAN, "You were sitting in my spot. I let you. That is the biggest thank you Thunder Peak knows how to give."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 15
    C("The Cauldron's Temper", "sect",
      "Gu's Frenzy Pills went into more than the tournament supplies: disciples on three peaks are waking with red at "
      "the edges of their eyes. Elder Hua needs a cure, the cure needs herbs from the bamboo, and the cauldron needs "
      "someone who can hold a fire steady without blowing up the Medicine Hall.",
      cast=[HUA, MAN, YAN, LAN, WEI, HAN, QIAN], foes=["spirit_wolf", "corrupted_wolf", "sparring_disciple"],
      items=["spirit_herb", "medicine", "blood_lotus"], props=["seal", "jade_slip", "treasure_chest"],
      foe_names={"sparring_disciple": "frenzied disciples"},
      beats=[
          B("probe", "Red at the Edges",
            "Disciples on three peaks have red at the edges of their eyes. Elder Hua knows exactly what that means.",
            (HUA, "Nine disciples, three peaks, the same red ring around the iris. Frenzy residue. Gu salted our rations, not just the tournament."),
            (HUA, "It sleeps in the meridians until anger wakes it. We need a Clear-Heart Pill. We've never needed one before."),
            "@R:Pavilion", (N, "In the pavilion, a Cloud Peak disciple sits very still, fists clenched, humming to drown out something only he can hear."),
            "@T",
            (YAN, "I know that humming. I did it for a week after the final. It's what you do so you don't hit anyone."),
            (YAN, "Whatever Elder Hua needs, I'll help. Nobody should have to hum through that."),
            ),
          B("gather", "Recipe From the Fourth Floor",
            "Elder Bai finds a Clear-Heart recipe in a book about turtle soup. Of course he does. It calls for herbs the sect doesn't grow.",
            (MAN, "Elder Bai found the recipe! In a turtle soup book! He says it's where he hides everything important. We need calm-root and red-veined sage."),
            (MAN, "We have the sage. Calm-root only grows in the bamboo, near water. I'll draw you a map. It'll be a bad map."),
            "@G:HerbGarden", ">Gather red-veined sage on the terraces",
            "@T",
            (MAN, "That's the sage. Now the calm-root. Take my map. The squiggle is a stream. The other squiggle is also a stream."),
            item="spirit_herb", noun="red-veined sage"),
          B("hunt", "Calm-Root by the Stream",
            "The calm-root grows along the forest stream, where the wolves have started drinking again.",
            "@R:bamboo_forest/Stream", (N, "Pale calm-root trails in the stream like hair. On the far bank, wolves lift their heads, water dripping from their jaws."),
            "@F:Stream", (N, "The wolves have red at the edges of their eyes too. Whoever salted the sect's rations salted the forest's water."),
            "@G:Stream", ">Harvest calm-root from the stream",
            "@T:Clearing",
            (WEI, "I came to help carry. I ate one calm-root. I feel incredibly calm. I may never move again."),
            (WEI, "The wolves had the red too. Poor things. They didn't hum. They just bit."),
            foe="corrupted_wolf", item="spirit_herb", noun="calm-root", map="sect"),
          B("social", "The Hermit's Correction",
            "The hermit reads the recipe over your shoulder and tuts. The Verdant Lotus made Clear-Heart Pills three centuries ago.",
            (LAN, "Turtle soup. Of course. Bai Qiu's grandmother taught him that trick. Your recipe is wrong, by the way. One line."),
            (LAN, "Add a lotus petal, from the spring, picked by the heir. The Heart Sutra does the rest. That is how we made them."),
            (P, "Picked by me? Why me?"),
            (LAN, "Because the lotus listens to you. It never listened to me. I ran from it, and it remembers."),
            "@G:SpiritSpring", ">Pick a lotus petal from the spirit spring",
            "@T",
            (LAN, "One petal is enough. Don't take more; the spring is generous, not stupid."),
            item="spirit_herb", noun="lotus petals", gcount=1, map="bamboo_forest"),
          B("train", "Holding the Fire",
            "Refining a Clear-Heart Pill takes a fire held perfectly steady for an hour. Elder Hua has you practise on ordinary pills first.",
            (HUA, "The fire must not flicker for one hour. Not for a sneeze, not for a thought. Practise on these Vitality Pills first."),
            (HUA, "If the cauldron starts to sing, step back. If it starts to scream, run."),
            "@M:Pavilion", ">Hold the cauldron fire steady",
            (N, "Your qi flows into the flame. It gutters, steadies, gutters. The cauldron begins to sing, very softly."),
            (N, "Then scream. You run. Behind you, a small green explosion, and a rain of slightly singed Vitality Pills."),
            "@T",
            (HUA, "Singed, not ruined. Better than my first attempt. I lost my eyebrows for a season."),
            (HUA, "Again. And this time, when it sings, sing back. The fire likes company."),
            ),
          B("battle", "Frenzy on Cinder Peak",
            "Before the pill is ready, three disciples on Cinder Peak lose the fight with their residue.",
            (HAN, "Cinder Peak! Three of them snapped at once. They're tearing up the training ground. Don't hurt them. Much."),
            "@F:TrainingGround", (N, "Red-eyed disciples swing practice swords like woodcutters, weeping as they do it."),
            "@F:FormationArray", (HAN, "Another two on the plaza! Pin them, don't break them!"),
            "@T:Pavilion",
            (HUA, "Five more in my infirmary. We need that pill. Tonight. Whatever it takes."),
            foe="sparring_disciple", foe2="sparring_disciple"),
          B("cultivate", "One Hour Without Flicker",
            "The real refinement: calm-root, red-veined sage, a lotus petal, and one hour in which your fire must not waver.",
            (HUA, "Everything's in the cauldron. The rest is you. One hour. I'll stand by with a bucket."),
            (MAN, "And I'll stand by with a second bucket. For Elder Hua."),
            "@M:Pavilion", ">Refine the Clear-Heart Pills",
            (N, "The cauldron sings. You sing back, a nonsense song Wei Tong taught you. The fire steadies. An hour passes like a breath."),
            (N, "Nine pills roll out, white as milk, each with a faint green lotus in its heart."),
            "@T",
            (HUA, "Nine. Nine perfect pills. I'm not crying. The smoke is very strong."),
            ),
          B("gather", "Nine Pills, Nine Disciples",
            "Nine pills for nine disciples. Some of them are in the infirmary; some are hiding their red eyes around the mountain.",
            (HUA, "Five in my infirmary, four still out there pretending they're fine. Find them. They won't come to me."),
            "@G:PlumGarden", ">Find the hiding disciples in the plum garden",
            "@T:Pavilion",
            (YAN, "That's all nine. The humming's stopped. You don't know how quiet the world is when it stops."),
            (YAN, "Thunder Peak owes you another debt. We'll have to invent a bigger bow."),
            item="medicine", noun="hidden disciples"),
          B("probe", "Where the Residue Came From",
            "The pills are working. But how did the residue get into the rations? Steward Qian keeps the grain ledgers.",
            (QIAN, "The grain ledgers? Every sack in, every sack out. I keep them under my pillow. Don't ask why."),
            "@I:IncenseBurner", ">Check the treasury's grain ledgers",
            (N, "Every grain delivery for two years came through Qingshi, and every one was approved by the Law Hall. Gu's seal, on every page."),
            "@T",
            (QIAN, "He approved the rice. I thought he was being thorough. I thought, how kind, the Law Hall checking our rice."),
            (QIAN, "I count stones. I never counted what was in the sacks. I'm going to count everything now. Everything."),
            prop="jade_slip", thing="the grain ledgers"),
          B("social", "Xiao Man's Medicine Bundles",
            "Elder Hua was right: work helps. Xiao Man has made two hundred medicine bundles and is starting on the third hundred.",
            (MAN, "Two hundred bundles! For whoever goes to the Abyss. I've only dropped eleven. Well, eleven that I know of."),
            (MAN, "Each one has a note inside. Most say 'get well soon'. One says 'Xiao Shi, you idiot, write to me'. In case."),
            "|",
            (HUA, "She'll make a healer yet. Not because of her hands. Because of the notes."),
            (HUA, "Take one bundle. For luck. And for when you find him."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 16
    C("The Beast Tide", "bamboo_forest",
      "The wards Gu kept on the bamboo forest were never wards at all, only leashes, and he has let go of them. Every "
      "beast the Blood Moon ever fed pours out of the deep forest at once, and the hermit's hut is directly in the way.",
      cast=[HAN, WEI, LAN, YAN, ZHAO, MO], foes=["spirit_wolf", "corrupted_wolf", "stone_golem"],
      items=["wolf_fang", "spirit_herb", "rune_fragment"], props=["seal", "stone_stele", "bronze_bell"],
      boss=("wolf_king", "Bloodmaw, Lord of the Tide", "Clearing"),
      things={"seal": "the forest ward-stone"},
      beats=[
          B("orders", "Every Bird at Once",
            "At dawn every bird in the bamboo forest takes flight at once. Elder Mo does not need a scout to know what that means.",
            (MO, "Every bird in the bamboo took off at dawn. All at once. That's not weather. That's a tide."),
            (MO, "Gu kept the forest wards. We thought. Take Han Xue, Wei Tong and Yan Tie. Get the hermit out, or dig in beside him."),
            "@R:bamboo_forest/ForestPath", (N, "The forest is loud with running things. Deer, foxes, a family of boars, all fleeing past you toward the sect."),
            "@T:ForestPath",
            (HAN, "Everything's running this way. Which means whatever they're running from is that way."),
            (HAN, "The hermit's hut is that way too. Of course it is."),
            map="sect"),
          B("probe", "Leashes, Not Wards",
            "The ward-stones Gu planted along the forest path are cracked from the inside. They were never keeping beasts out.",
            "@R:ForestPath", (N, "A ward-stone stands by the path, split down the middle. The runes inside are not warding runes."),
            "@I:ForestPath", ">Examine the split ward-stone",
            (N, "Summoning runes. Gu planted leashes and called them wards. Every beast within a day's walk has been waiting for them to break."),
            "@T",
            (YAN, "He planted a trap and waited for his own flight to spring it. Twenty years of patience. That's frightening."),
            (P, "Then we're the ones who have to be faster."),
            prop="seal", thing="the split ward-stone"),
          B("battle", "The First Wave",
            "The first wave comes through the herb grove: wolves, dozens of them, red-eyed and running.",
            (WEI, "Wolves! A river of wolves! Dumpling, I'm sorry, you're going to get very dirty today."),
            "@F:HerbGrove",
            "@F2:OldBridge", (HAN, "Hold the bridge! If they cross the stream, they're at the hut!"),
            "@R:Stream", (N, "The first wave breaks on the bridge and scatters. Across the water, the bamboo is still shaking."),
            foe="corrupted_wolf", foe2="spirit_wolf"),
          B("defend", "The Hermit Won't Leave",
            "The hermit refuses to leave his hut. He says he ran once, three hundred years ago, and has only just stopped.",
            (LAN, "I will not leave. I ran from the Verdant Lotus's last stand. I have only recently stopped running. I will not start again for wolves."),
            (LAN, "But you may stay and help, if you like. I'll make tea."),
            "@I:AncientShrine", ">Wake the old shrine's ward",
            (N, "The shrine's stele answers your pendant with a low green hum. For the first time in three centuries, a real ward rises over the forest."),
            "@F:HerbGrove", (N, "Wolves hit the edge of the ward and recoil, snarling. Some of them find the gaps."),
            "@T",
            (LAN, "A true ward. Verdant Lotus work, woken by Verdant Lotus blood. It won't hold forever. Nothing does."),
            prop="stone_stele", thing="the shrine's stele", foe="corrupted_wolf"),
          B("hunt", "Stones That Walk",
            "The tide has woken the ruins' stone sentinels, and they cannot tell friend from wolf.",
            "@R:RuinsGate", (N, "At the ruins gate, stone sentinels stagger out, swinging at wolves and trees and anything that moves."),
            "@F:RuinsGate", (ZHAO, "Stone men again! I came to help! Nobody told me it was stone men again!"),
            "@G:RuinsGate", ">Collect the sentinels' rune-stones",
            "@T",
            (ZHAO, "Elder Mo sent me after you. He said you'd need someone to complain at. I'm very good at it."),
            (ZHAO, "Those stones were your family's, weren't they. The Verdant Lotus. I'm sorry I broke them. Slightly."),
            foe="stone_golem", item="rune_fragment", noun="sentinel rune-stones"),
          B("cultivate", "The Eye of the Storm",
            "The ward holds for now. In the lull, the hermit tells you to rest, because the next wave has a king.",
            (LAN, "The ward holds. For an hour, perhaps two. Sit. Breathe. The next wave will have a king at its head."),
            "@M:SpiritSpring", ">Rest your qi by the spirit spring",
            (N, "The spring is still while the forest howls. Your foundation drinks from it, slow and deep, like roots in dry season."),
            "@T:Clearing",
            (YAN, "There's something huge in the deep forest. The wolves part for it. It's coming this way."),
            (YAN, "Thunder Peak has a saying. The bigger they are, the louder you shout. I intend to shout very loudly."),
            ),
          B("battle", "The Wolves Before the King",
            "The king's pack comes first, circling to find the gaps in the ward.",
            (HAN, "They're circling. Looking for the weak side. Wei Tong, left. Yan Tie, right. You, wherever it's worst."),
            "@F:Clearing",
            "@F2:WolfDen", (N, "From the old den pour wolves with silver-tipped fur, larger than any you've seen. The king's own pack."),
            "@T:Stream",
            (WEI, "I've stopped counting wolves. I'm counting teeth now. It's a bigger number but it feels more manageable."),
            foe="corrupted_wolf", foe2="spirit_wolf"),
          B("boss", "Bloodmaw, Lord of the Tide",
            "At the head of the tide comes Bloodmaw, a wolf king older than the one you buried, gorged on twenty years of Gu's blood.",
            "@R:Clearing", (N, "The bamboo bends aside. A wolf the size of a cart pads into the clearing, fur black with old blood, eyes like coals."),
            "@X", (HAN, "That's not a wolf. That's twenty years of someone's patience with teeth. Together!"),
            "@I:Clearing", ">Lay the wolf king to rest",
            (N, "You press a purifying talisman to the great brow. The red drains from its eyes. For a moment it is only an old wolf, very tired."),
            "@T:Stream",
            (WEI, "Rest easy, old king. I'm saying that to all of them now. It seems right."),
            prop="seal", thing="the fallen wolf king"),
          B("gather", "After the Tide",
            "The tide has broken. The forest is torn and quiet, and the hermit wants every one of the leash-stones dug up.",
            (LAN, "Dig up every leash-stone Gu planted. Every one. I want this forest to belong to itself again."),
            "@G:HerbGrove", ">Dig up the leash-stones in the grove",
            "@F:WolfDen", (N, "A few stragglers still guard the old den, confused and frightened now that no one is calling them."),
            "@T",
            (LAN, "Thank you. It is a strange thing, to be protected. I had forgotten how it feels."),
            item="rune_fragment", noun="leash-stones", foe="spirit_wolf"),
          B("social", "Beasts Toward Qingshi",
            "Not every beast ran into your ward. The hermit's birds say a second tide turned east, toward the river and the town.",
            (LAN, "My birds say half the tide turned east. Toward the river. Toward your town with the good noodles."),
            "|",
            (HAN, "Qingshi. Of course. The town's always in the way of something."),
            (HAN, "We go now. The magistrate will make a speech. We'll have to fight through it."),
            "|",
            (YAN, "Thunder Peak goes where the thunder goes. Lead the way."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 17
    C("Tide at the Town Gate", "qingshi_town",
      "Half the beast tide has turned toward Qingshi, and the town has only its constable, its magistrate's new spine and "
      "a merchant who suddenly wants very badly to be liked. You have until nightfall.",
      cast=[DU, ZHOU, FANG, PAN, LIU, JIN, HAN, YAN, WEI], foes=["spirit_wolf", "corrupted_wolf", "stone_golem"],
      items=["lantern_oil", "medicine", "spirit_stone"], props=["bronze_bell", "seal", "treasure_chest"],
      things={"bronze_bell": "the town bell", "seal": "the gate ward"},
      beats=[
          B("orders", "Before Nightfall",
            "You reach Qingshi at noon. The tide will reach it at dusk. Constable Du is already stacking carts across the road.",
            "@R:TownGate", (N, "Carts are stacked across the road. Farmers carry children and chickens through the gate in a steady, frightened stream."),
            "@T:MainStreet",
            (DU, "Beasts, the birds say. A whole forest's worth. I've got carts, spears and the magistrate. The magistrate's making a speech."),
            (DU, "Tell me what to do and I'll do it. Tell the magistrate and he'll do it louder."),
            ),
          B("social", "Everyone Has a Job",
            "A town can be saved by everyone doing one small thing. Madam Fang, Old Pan and Widow Liu already know theirs.",
            (FANG, "The inn's cellar holds forty. I've put the children in it with the wine. The children are guarding the wine. We'll see who wins."),
            "|",
            (PAN, "Ferry's running both ways. Farmers across, fish back. If the beasts come by water, I'll ring the dock bell. Twice. With feeling."),
            "|",
            (LIU, "Water. Fighters need water. I'll carry it to the wall. I carried it for a year looking for my son. I can carry it one more night."),
            ),
          B("gather", "Oil for the Braziers",
            "Beasts fear fire. The town's braziers need oil, and the only oil is in the guild warehouse.",
            (JIN, "Oil? For the braziers? Take it! All of it! Well, most of it. Some of it is imported. Fine! All of it!"),
            (JIN, "I'd like it noted that I was helpful. By someone. In writing."),
            "@G:Warehouse", ">Carry oil from the warehouse",
            "@I:TownGate", ">Light the gate braziers",
            (N, "The braziers catch one by one along the wall. A ring of fire rises around Qingshi as the sun touches the hills."),
            "@T:MainStreet",
            (DU, "Fire's up. Beasts are coming. Merchant Jin asked me to write down that he was helpful. I wrote it down. In pencil."),
            item="lantern_oil", noun="oil barrels", prop="seal", thing="the gate braziers"),
          B("defend", "The Tide Arrives",
            "At dusk the fields fill with eyes.",
            (ZHOU, "Citizens of Qingshi! Fear not! The Azure Cloud is here, and I have written a very short speech! It is one word! Hold!"),
            "@I:WatchTower", ">Ring the town bell",
            (N, "The bell rings. Across the fields a hundred pairs of red eyes turn toward the sound, and begin to run."),
            "@F:Farmland", (YAN, "Keep them off the fields! Every wolf on the rice is a winter without bread!"),
            "@F:TownGate",
            "@T:MainStreet",
            (ZHOU, "One word! Hold! And they held! I have never given a better speech. I may never speak again. It can't be topped."),
            foe="corrupted_wolf", foe2="spirit_wolf", prop="bronze_bell", thing="the town bell"),
          B("battle", "Wolves on the Water",
            "Some of the wolves took the river. Old Pan rings the dock bell twice, with feeling.",
            (PAN, "Wolves in the water! Swimming! I didn't know wolves swam! Nobody tells a ferryman anything!"),
            "@F:Riverside",
            "@F2:MarketSquare", (HAN, "They're in the market! Keep them away from the inn cellar!"),
            "@T:Riverside",
            (PAN, "Forty years on this water. First time I've hit a wolf with an oar. Won't be the last, I'd wager. It felt wonderful."),
            foe="spirit_wolf", foe2="corrupted_wolf"),
          B("hunt", "Stone in the Graveyard",
            "Something heavy is walking among the hill graves. Deacon Hong's old circle has woken a stone guardian meant for the dead.",
            "@R:Graveyard", (N, "Grave tablets topple one by one. Among them lumbers a stone guardian, blood-ink still smeared on its chest."),
            "@F:Graveyard", (N, "It swings at the tombs as if the dead had wronged it personally."),
            "@G:Graveyard", ">Gather the fallen grave tablets",
            "@T:MainStreet",
            (LIU, "You put the tablets back. All of them. People will cry when they see that in the morning. Good crying."),
            foe="stone_golem", item="spirit_stone", noun="fallen grave tablets"),
          B("defend", "The Longest Hour",
            "The tide throws everything left at the town gate in one last push.",
            (DU, "Everything they've got, right at the gate. My spear's broken. I'm using the magistrate's proclamation board."),
            "@I:TownGate", ">Reinforce the gate ward with your qi",
            (N, "Your foundation pours into the gate like water into cracks. The old timbers stop groaning."),
            "@F:TownGate",
            "@F2:MainStreet",
            "@T:MarketSquare",
            (WEI, "I followed you down from the sect. Elder Mo said stay. I said Qingshi has noodles. He understood."),
            (WEI, "Look. Dawn. They're running back to the forest. We did it. The noodle shop is safe."),
            foe="corrupted_wolf", foe2="spirit_wolf", prop="seal", thing="the gate"),
          B("social", "Morning in the Market",
            "The town wakes up alive. Madam Fang opens the cellar. The children have not drunk the wine. Mostly.",
            (FANG, "The children guarded the wine. Heroically. One of them guarded it into his stomach. He's asleep in a barrel."),
            (FANG, "Free noodles for everyone who stood on that wall. Which is everyone. I'm going to be poor and happy."),
            "|",
            (JIN, "I was helpful. Everyone saw. The constable wrote it in pencil, but it's written."),
            (JIN, "It felt... strange. Good strange. I didn't charge anyone for anything all night. I may be ill."),
            "|",
            (LIU, "My arms hurt. I carried water all night. I kept thinking, Liu Er would have carried twice as much and complained the whole way."),
            ),
          B("probe", "What Drove Them",
            "Among the beasts you find a collar of blood-red jade, still humming. Someone didn't just release the tide. Someone steered it.",
            "@R:Farmland", (N, "Among the fallen beasts lies a wolf wearing a collar of blood-red jade, carved with a crescent. It still hums faintly."),
            "@I:Farmland", ">Break the humming collar",
            (N, "The collar cracks. For a moment you hear a voice from very far and very deep, counting, as if it were keeping score."),
            "@T:MainStreet",
            (HAN, "Steered. Not released. Someone pointed this tide at Qingshi on purpose."),
            (HAN, "Someone who knows the town. Someone who's been here. Gu, or his friends. We need to know where they come and go."),
            prop="seal", thing="the jade collar"),
          B("stage", "Standing on the Wall",
            "You watch the sun rise over the fields from the town wall, and something in your foundation settles into a new shape.",
            "@R:WatchTower", (N, "From the watchtower, the fields are trampled but green. Smoke rises from a hundred chimneys, all of them breakfast."),
            "@M:WatchTower", ">Cultivate on the town wall at sunrise",
            (N, "You breathe in a town that did not die. Your foundation settles, and deepens, and grows quiet. Late stage."),
            "@T:MainStreet",
            (YAN, "You look like someone who's just understood something. Thunder Peak usually just shouts at that point. Go ahead."),
            (P, "I think I'm fighting for the wrong reasons. Not the wrong people. The wrong reasons."),
            (YAN, "Hm. That's too deep for me before breakfast. Tell me after noodles."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 18
    C("The Second Verse", "bamboo_forest",
      "The Heart Sutra has three verses. You learned the first in the ruins. The hermit says the second is harder: it "
      "can only be learned by someone who has forgiven something. He has been trying for three hundred years.",
      cast=[LAN, HAN, ZHAO, YAN, MO], foes=["stone_golem", "spirit_wolf", "rogue_cultivator"],
      items=["spirit_herb", "rune_fragment", "jade_slip"], props=["stone_stele", "seal", "treasure_chest"],
      things={"stone_stele": "the reliquary stele", "seal": "the lotus seal"},
      beats=[
          B("orders", "A Letter in Spidery Hand",
            "A paper crane lands on your windowsill at the sect: the hermit wants you in the forest. He does not say why.",
            (MO, "A paper crane landed on my head this morning. For you. From the hermit. He writes like a spider fell in ink."),
            (MO, "Go. Take Han Xue. The sect can spare its champion for a few days. The puppets will be relieved."),
            "@R:bamboo_forest/HermitHut", (N, "The hermit is waiting outside his hut. There are no cups of tea. That has never happened before."),
            "@T:Clearing",
            (LAN, "No tea today. Today we do something difficult, and tea would only make me feel better than I deserve."),
            map="sect"),
          B("interlude", "Roots, Stem, Blossom",
            "The hermit explains the Heart Sutra's three verses, and why he never finished learning the second.",
            (LAN, "Root: patience. You learned it at the ruins. Stem: forgiveness. Blossom: compassion. Nobody reaches the blossom without the stem."),
            (LAN, "I have been stuck on the stem for three hundred years. I cannot forgive a boy who ran while his masters died."),
            (P, "You were that boy."),
            (LAN, "Yes. That is what makes it hard."),
            "|",
            (HAN, "I didn't know sutras could be that personal. The Frost Sword manuals are mostly about angles."),
            ),
          B("delve", "The Reliquary Below",
            "Beneath the reliquary where you found the first verse, a second chamber has opened, answering the ward you woke during the tide.",
            "@R:RuinsInner", (N, "Where the reliquary stood, a stair now leads down into green-lit stone. The ward you woke opened more than one door."),
            "@G:RuinsInner", ">Gather the stair's scattered lotus tiles",
            "@I:RuinsInner", ">Read the reliquary stele below",
            (N, "Stem, the stele says. To forgive is not to forget. It is to put the burden down long enough to pick up someone else's."),
            "@F:RuinsGate", (N, "The chamber's guardians wake behind you, stone and patient, and bar the way out."),
            "@R:AncientShrine", (N, "Outside, the shrine is warm with late sun. The hermit is sitting on a broken pillar, not looking at you."),
            item="rune_fragment", foe="stone_golem"),
          B("social", "What Zhao Kang Can't Forgive",
            "Zhao Kang has followed you into the forest again. The stele's words have found a raw place in him too.",
            (ZHAO, "Don't look surprised. I followed you again. I'm very good at following. It's a clan skill."),
            (ZHAO, "Put the burden down long enough to pick up someone else's. My brother died on a mission Gu gave him. How do I put that down?"),
            (P, "I don't know. Maybe you don't have to put it down all at once."),
            (ZHAO, "...That's the least helpful helpful thing anyone's ever said to me. Thank you."),
            "|",
            (HAN, "He'll be all right. He's stubborn. Stubborn people forgive slowly, but they forgive all the way."),
            ),
          B("battle", "Robbers at the Shrine",
            "Word of the ruins' second chamber has spread. Rogue cultivators have come with sacks and crowbars.",
            (HAN, "Rogues again. They heard the ruins opened. They want everything that glows, including you."),
            "@F:AncientShrine",
            "@F2:ForestPath",
            "@R:OldBridge", (N, "The rogues scatter into the bamboo, dropping crowbars and one very expensive-looking lantern."),
            foe="rogue_cultivator", foe2="rogue_cultivator"),
          B("cultivate", "The Stem",
            "The hermit asks you to sit with him at the spirit spring and try to forgive something. Anything. He will try too.",
            (LAN, "Sit. Find one thing you have not forgiven. It needn't be big. Big ones are for later."),
            (P, "Elder Gu. For the pendant, for Qingshi, for everything."),
            (LAN, "That is a big one. Well. We'll both fail together, then. That's something."),
            "@M:SpiritSpring", ">Meditate on forgiveness at the spirit spring",
            (N, "You sit with your anger at Gu the way you'd sit with a fire, watching it without feeding it. It doesn't go out. It gets smaller."),
            (N, "Beside you the hermit weeps without a sound, and the lotus on the spring turns, very slowly, toward him."),
            "@T",
            (LAN, "It turned to me. After three hundred years. Not forgiveness. Not yet. But it turned."),
            ),
          B("hunt", "Wolves at the Spring",
            "The spring's new light has drawn wolves from the deep forest. Not red-eyed ones. Curious ones. And a few that are neither.",
            "@R:SpiritSpring", (N, "Wolves ring the spring, drinking the light. Most are grey and calm. Three are thin and wild, and they are not here to drink."),
            "@F:HerbGrove", (N, "The wild ones break from the pack and come for the hermit."),
            "@G:HerbGrove", ">Gather herbs for the hermit's bitten arm",
            "@T:SpiritSpring",
            (LAN, "One bite. Old men are chewy; the wolf will have regretted it. Thank you for the herbs."),
            foe="spirit_wolf", item="spirit_herb", noun="healing herbs"),
          B("probe", "The Letter in the Reliquary",
            "In the lower chamber lies a second letter in the elegant hand that wrote the first. This one is addressed to Lan Jue.",
            "@R:RuinsInner", (N, "On a shelf in the lower chamber lies a letter, sealed with green wax, addressed: to Lan, when he stops running."),
            "@I:RuinsInner", ">Bring the letter to the light",
            (N, "You don't open it. It isn't yours. But the seal is warm, as if someone had just pressed it."),
            "@T:AncientShrine",
            (LAN, "That's my master's hand. She knew. Three hundred years ago she knew I'd run, and she left me a letter for when I stopped."),
            (LAN, "I'm not ready to read it. Keep it for me. Give it to me when I am. You'll know. I won't."),
            prop="treasure_chest", thing="the sealed letter"),
          B("social", "Carrying Someone Else's",
            "Yan Tie arrives with news from the sect, and finds three people sitting in silence around a spring. He sits too.",
            (YAN, "Elder Mo sent me. The array masters say the Abyss route will be ready in a month. Also, why is everyone crying?"),
            (ZHAO, "We're not crying. We're forgiving. It's different. It's wetter."),
            "|",
            (YAN, "Forgiving. Hm. I've been angry at the pill for a year. Not at Gu. At the pill. As if the pill chose."),
            (YAN, "I'll sit with you. Thunder Peak doesn't usually sit. But I'll try."),
            ),
          B("gather", "The Hermit's Parting Gift",
            "Before you go, the hermit gives you seeds from the spring's lotus, and asks you to plant one at the sect.",
            (LAN, "Take these seeds. Plant one at your sect, by the water. When the Verdant Lotus grows beside the Azure Cloud again, I'll visit."),
            (LAN, "Not before. I'm not ready to see your Sect Master. She'll ask me why I ran. I'll have to say."),
            "@G:SpiritSpring", ">Gather lotus seeds from the spring",
            "@T:Clearing",
            (HAN, "He'll come. People who give seeds always come to see if they grew."),
            item="spirit_herb", noun="lotus seeds"),
      ]),
    # ------------------------------------------------------------------ chapter 19
    C("The Crimson Road", "qingshi_town",
      "The steered tide came from somewhere, and the blood lotus in Qingshi's crates goes somewhere. Follow the carts "
      "west along the river and you find a road nobody admits exists: the Crimson Road, down to the Abyss.",
      cast=[HAN, DU, PAN, JIN, FANG, ZHOU, YAN], foes=["demon_cultivator", "bandit", "rogue_cultivator"],
      items=["blood_lotus", "letter", "rune_fragment"], props=["treasure_chest", "jade_slip", "seal"],
      foe_names={"bandit": "cart guards", "demon_cultivator": "Blood Moon runners"},
      things={"treasure_chest": "the cart's false bottom", "seal": "the waystation seal"},
      beats=[
          B("probe", "Carts That Leave at Night",
            "Constable Du has been watching the guild's carts. Some of them leave at night, heading west, and come back empty.",
            (DU, "I've been watching the guild's carts, like you asked. Three a week leave after dark, heading west. Come back empty. Wheels muddy red."),
            (DU, "Nothing grows red to the west. Nothing but bad luck."),
            "@R:Warehouse", (N, "A cart stands loaded in the warehouse yard, tarpaulin tied tight. It smells of silk, and underneath, of blood lotus."),
            "@I:Warehouse", ">Search the cart's false bottom",
            (N, "Beneath the silk: blood lotus, dried and bundled, and a map of a road that follows the river west, then turns down."),
            "@T:MainStreet",
            (HAN, "Down. Toward the Abyss. There's a road. There's been a road all along."),
            prop="treasure_chest", thing="the cart"),
          B("social", "Merchant Jin Sweats",
            "Merchant Jin swears the carts aren't his. His hands say otherwise. So do his daughters' shoes, which are new.",
            (JIN, "Those carts aren't mine! They're the guild's! I'm only the master of the guild! That's completely different!"),
            (JIN, "...They pay in silver. A lot of silver. My daughters have new shoes. Do you know what shoes cost?"),
            (P, "Who pays?"),
            (JIN, "A man with a crescent on his seal. I never see his face. I don't want to. Please. I have daughters."),
            "|",
            (HAN, "Leave him. For now. A frightened merchant is more useful than a dead one. The road is what matters."),
            ),
          B("orders", "Old Pan's River",
            "Old Pan knows every bend of the river. He knows where the carts cross, and where the lanterns wait on the far bank.",
            (PAN, "West bank, past the third bend. There's a ford nobody uses, and lanterns on the far side on moonless nights. Bone lanterns."),
            (PAN, "I'll take you as far as the ford. Not a step past. I'm brave, not stupid."),
            "@R:Riverside", (N, "Old Pan's ferry noses into the current. The town slides away behind you, and the river turns quiet and dark."),
            "@T:Riverside",
            (YAN, "Bone lanterns. Wonderful. I love a road with decorations."),
            ),
          B("battle", "Guards at the Ford",
            "At the ford the carts meet their escort: bandits in borrowed armour and two runners in crimson.",
            (HAN, "Cart guards at the ford. And two in crimson behind them. Blood Moon runners. Don't let the runners get away."),
            "@F:Riverside",
            "@F2:Farmland", (N, "The crimson runners break for the fields, fast as hares, blood-talismans burning at their ankles."),
            "@R:Farmland", (N, "One runner falls, and a satchel spills open. Letters, a lantern of carved bone, a pouch of red soil."),
            foe="bandit", foe2="demon_cultivator"),
          B("probe", "Letters in the Satchel",
            "The runner's satchel is full of letters. They are addressed to Qingshi's watchers, and they are not friendly.",
            "@R:Farmland", (N, "The satchel's letters are orders. Names of Qingshi's watchers. Old Pan. Madam Fang. Constable Du. Beside each: when."),
            "@I:Farmland", ">Read the runner's orders",
            (N, "The last line says: the heir must not reach the road. Beneath it, in a different, older hand, someone has written: yet."),
            "@T:MainStreet",
            (HAN, "They know about the watchers. They know about you. Yet. What does yet mean?"),
            (P, "It means someone wants me on this road. Just not yet."),
            (HAN, "I hate that. I hate that more than the rest of it put together."),
            prop="jade_slip", thing="the orders"),
          B("defend", "Protecting the Watchers",
            "If the Blood Moon has names, it will come for them. You and Han Xue split up to guard Qingshi's watchers.",
            (FANG, "My name's on a list? Mine? I'm flattered. I'm terrified. I'm going to hide behind the wine and hit people with a ladle."),
            "@I:Inn", ">Set a ward over the Drunken Crane",
            (N, "You draw a ward on the inn's lintel in cinnabar. Madam Fang watches, then adds a small cat of her own for luck."),
            "@F:MainStreet", (N, "They come at midnight, masked and quiet, toward the inn, the docks and the yamen at once."),
            "@F2:Riverside",
            "@T:MainStreet",
            (DU, "All three watchers alive. My name was on the list and I'm still here. I'm going to frame the list."),
            prop="seal", thing="the inn's lintel", foe="demon_cultivator", foe2="demon_cultivator"),
          B("chase", "Bone Lanterns",
            "The last runner flees west along the Crimson Road. You follow the bone lanterns as far as you dare.",
            "@R:Graveyard", (N, "Past the hill graves the road runs west, lit at every hundred paces by a lantern carved from a single bone."),
            "@F:Farmland", (N, "Rogues guarding the road step out from the lanterns' shadows. Hired swords, cheap and many."),
            "@R:TownGate", (N, "You turn back before the road turns down. Far to the west, the sky is a faint red smudge that never fades."),
            "@T:MainStreet",
            (HAN, "That red smudge. That's where the road goes. That's where Gu went. That's where Xiao Shi is."),
            (HAN, "We tell the Sect Master everything. And then, I think, we finally go."),
            foe="rogue_cultivator"),
          B("social", "The Magistrate's Seal",
            "Magistrate Zhou insists on writing an official report of the Crimson Road for the Sect Master. It is sealed with his best seal.",
            (ZHOU, "An official report! From the yamen of Qingshi to the Sect Master of the Azure Cloud! My best seal! My second-best brush!"),
            (ZHOU, "I have described you as 'valiant'. I have described myself as 'present'. I feel that's fair."),
            "|",
            (PAN, "Took the ferry to the third bend and back. Didn't see any bone lanterns. Saw a heron. Very judgemental heron."),
            ),
          B("gather", "Evidence for the Mountain",
            "The Sect Master will want proof. You gather what the runners dropped along the road.",
            (HAN, "The Sect Master will want proof, not stories. Pick up everything they dropped. Even the unpleasant things."),
            "@G:Farmland", ">Gather the runners' dropped evidence",
            "@I:Graveyard", ">Take a rubbing of the road's first lantern",
            (N, "The bone lantern's carving is a crescent over a sword. The same mark as the token. The same mark as everything."),
            "@T:MainStreet",
            (YAN, "Thunder Peak will march with you when you go down. All of us. We shout very loudly in dark places."),
            item="letter", noun="dropped letters", prop="stone_stele", thing="the first bone lantern"),
          B("interlude", "Home With the Map",
            "You leave Qingshi with a map, a satchel of letters and a magistrate's report. The town waves you up the mountain.",
            (DU, "Go on. We're watched now, but we're watching back. Bring the missing home. All of them."),
            "|",
            (FANG, "Bring Liu Er home. Bring the Xiao boy home. Bring yourself home. That's three bowls I'm keeping hot."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 20
    C("Eve of the Descent", "sect",
      "The array masters have laid a new route to the Abyss's rim. The Sect Master reads the Crimson Road report twice, "
      "and makes her choice: not an army, but two disciples and whoever knows the way down. Before you go, the sect "
      "says goodbye in its own ways.",
      cast=[YUN, MO, HAN, HUA, MAN, BAI, WEI, ZHAO, QIAN, LU, YAN], foes=["training_puppet", "demon_cultivator"],
      items=["medicine", "spirit_stone", "spirit_herb"], props=["teleport_array", "jade_slip", "seal"],
      beats=[
          B("orders", "The Report Read Twice",
            "The Sect Master reads the Crimson Road report twice, then Magistrate Zhou's description of himself as 'present', and almost smiles.",
            (YUN, "A road. All this time, a road, and our own Law Hall approving the carts. Thank you for bringing this home."),
            (YUN, "An army would be seen for a hundred miles. I'll decide by morning who goes. Go and rest. You won't."),
            "@R:TeleportArray", (N, "The array masters kneel around the teleport array, laying the last jade of the new route. It glows faintly red at its edge."),
            "@T:SectGate",
            (MO, "The new route only reaches the rim. After that, it's feet. Whoever goes, goes carefully."),
            (MO, "It'll be you. Don't pretend you don't know. Go and say your goodbyes, and don't make them sound like goodbyes."),
            ),
          B("gather", "Two Hundred Bundles",
            "Xiao Man's medicine bundles are finished: three hundred of them. She wants you to carry as many as you can.",
            (MAN, "Three hundred bundles! I only dropped twenty. Take as many as you can carry. Take more than you can carry."),
            (MAN, "The one with the red string is for my brother. Don't give it to anyone else. Promise. No, don't. Just don't."),
            "@G:LotusPond", ">Pack Xiao Man's medicine bundles",
            "@T",
            (MAN, "You'll find him. I know it. I dreamed it. I also dreamed I was a carp, so. But I know it."),
            item="medicine", noun="medicine bundles"),
          B("train", "One Last Lesson",
            "Elder Mo insists on one last lesson before the descent. It is about falling down, and getting up.",
            (MO, "Last lesson. Not about winning. About falling. In the Abyss you will fall. The question is how fast you get up."),
            "@F:TrainingGround", ">Spar with Elder Mo's puppets",
            (MO, "Fall! Up! Fall! Up! Faster! The puppet doesn't care how you feel about it!"),
            "@T",
            (MO, "Adequate. More than adequate. Hmph. I've said that twice now. Don't tell anyone."),
            foe="training_puppet", count=5),
          B("social", "Lessons From the Shelves",
            "Elder Bai has something for you: everything the pagoda knows about the Abyss, which is not much, copied very small.",
            (BAI, "Everything the pagoda knows about the Abyss. It fits on one slip. That's how little we know. Copied very small."),
            (BAI, "The Abyss has a heart, the old books say. A black pool that shows you yourself. Do not look into it. Or do. The books disagree."),
            "|",
            (HUA, "Pills for pain, pills for poison, pills for when you're sure you can't go on. The last ones are sugar. They work anyway."),
            ),
          B("probe", "Planting the Seed",
            "Before you go, you plant one of the hermit's lotus seeds in the sect's pond. Just in case you don't come back to do it.",
            "@R:LotusPond", (N, "The lotus pond is still. The carp gather, curious, as you kneel at the edge with a seed in your palm."),
            "@I:LotusPond", ">Plant the Verdant Lotus seed",
            (N, "The seed sinks. For a moment a green light spreads under the water like a breath, and every carp in the pond turns to face it."),
            "@T:StoneBridge",
            (HAN, "Planting things before a journey. My grandmother did that. She said it gives you a reason to come back."),
            (HAN, "I've got plenty of reasons. You're one of them. Don't make it weird."),
            prop="seal", thing="the lotus seed"),
          B("duel", "Zhao Kang's Farewell",
            "Zhao Kang won't say goodbye. He challenges you to a spar instead, which is how the Zhao clan says goodbye.",
            (ZHAO, "I'm not saying goodbye. The Zhao clan doesn't say goodbye. We spar. Loudly. Pick up a sword."),
            "@F:FormationArray", ">Spar with Zhao Kang's attendants first",
            (ZHAO, "My attendants insist on going first. They say it's tradition. It's not. They just want to hit you."),
            "@T:FormationArray",
            (ZHAO, "If you find out what happened to my brother down there... anything... tell me. Even if it's bad."),
            (P, "I'll tell you everything, Zhao Kang."),
            (ZHAO, "Hmph. Good. Now go away before I say something I'll regret. Like 'be careful'. Be careful."),
            foe="sparring_disciple", count=2),
          B("battle", "Shadows at the Array",
            "On your last night, someone tries to sabotage the new array. Gu's friends are still on the mountain.",
            (LU, "Someone's at the array! In the dark! I'm pretty sure it's not the array masters, they snore!"),
            "@F:SectGate",
            "@F2:OuterPines", (N, "The saboteurs flee toward the pines. One of them drops a crescent seal and doesn't stop to pick it up."),
            "@T:SectGate",
            (LU, "The array's safe. I stood on it all night after that. I'm very cold. I'm very proud."),
            foe="demon_cultivator", foe2="demon_cultivator"),
          B("interlude", "Wei Tong's Dumplings",
            "Wei Tong has made dumplings for the journey. Forty of them. He says it's for luck. He says a lot of things when he's worried.",
            (WEI, "Forty dumplings. For the journey. They're wrapped in lotus leaves so they'll stay fresh in the Abyss. I asked Elder Hua."),
            (WEI, "She said nothing stays fresh in the Abyss. So I made extra."),
            (P, "Senior Brother, you're crying."),
            (WEI, "It's the onions. I put a lot of onions in. For luck. Come back and eat the rest."),
            ),
          B("social", "Steward Qian's Ledger",
            "Steward Qian stops you at the gate with a ledger. He has opened an account in your name. It is empty. That's the point.",
            (QIAN, "I've opened an account in your name. Contribution points for the descent. It's empty. You'll fill it when you come back."),
            (QIAN, "I don't open accounts for people who don't come back. It's a very bad investment. So come back."),
            "|",
            (YAN, "Thunder Peak will be at the rim when you come out. Shouting. You'll hear us before you see us."),
            ),
          B("stage", "The Night Before",
            "The night before the descent, you sit on the cliff edge and let your foundation settle one last time.",
            "@R:CliffEdge", (N, "The sea of clouds is silver under the moon. Somewhere to the west, below the edge of the world, the sky is faintly red."),
            "@M:MoonGate", ">Sit in the moon gate's quiet before dawn",
            (N, "Root, stem, blossom. Patience you have. Forgiveness you are trying. The blossom will have to wait for the Abyss."),
            (N, "Your foundation reaches its peak, solid as the mountain under you."),
            "@T:MoonGate",
            (YUN, "You're awake. So am I. I've chosen: you and Han Xue. And someone is waiting at the gate who says he knows the way down."),
            (YUN, "Sleep an hour. Then come and find me. We'll talk about guides, and traitors, and coming home."),
            ),
      ]),
]
