"""Volume III · Core Formation — new chapters 23-30 (after the Siege of
Qingshi, before the Sky Isles open).

The Great Azure Formation needs materials from the Sky Isles, which open once
in sixty years; until they do, the orthodox sects quarrel over the Lotus Key.
The Iron Scale Sect arrives with grievances, the Blood Moon feeds the quarrel,
the Verdant Lotus ruins give up an archive, and the Abyss rim is patrolled.
Xiao Shi and Liu Er are home; Iron-Fang washes dishes at the Drunken Crane;
Zhao Kang has not yet apologised for two years of being insufferable.
"""

from .dsl import N, P
from .npcs import *  # noqa: F401,F403
from .saga_gen import B, C

CHAPTERS = [
    # ------------------------------------------------------------------ chapter 23
    C("Envoys of the Iron Scale", "sect",
      "The Iron Scale Sect lost eleven disciples to Blood Moon raids this year, and blames the Azure Cloud for the "
      "traitor who armed them. Its sect master climbs the nine thousand steps with a demand: surrender the Lotus Key "
      "to a council of sects. His son would rather settle it with swords.",
      cast=[YUN, RUANHAI, RUAN, HAN, MO, ZHAO, LU, SHI, YAN], foes=["iron_scale_disciple", "demon_cultivator"],
      items=["letter", "spirit_stone", "jade_slip"], props=["stone_stele", "treasure_chest", "bronze_bell"],
      things={"treasure_chest": "the envoys' gift chest"},
      beats=[
          B("orders", "Green Banners on the Steps",
            "Green banners are climbing the nine thousand steps: the Iron Scale Sect, unannounced and in full armour.",
            (LU, "Green banners on the steps! Thirty of them! In armour! Do we have an appointment? I don't think we have an appointment!"),
            "@R:SectGate", (N, "Iron Scale disciples line the processional way, green scale armour polished to a shine. None of them bow."),
            "@T:SectGate",
            (RUANHAI, "Ruan Hai, master of the Iron Scale. I have climbed nine thousand steps to say one thing to your Sect Master."),
            (RUANHAI, "Your traitor armed the Blood Moon. The Blood Moon took eleven of my children. I want the Lotus Key under a council's guard."),
            ),
          B("social", "An Audience Without Tea",
            "The Sect Master receives the Iron Scale in the main hall. Nobody is offered tea, which in the Azure Cloud is a declaration.",
            (YUN, "Sect Master Ruan. Your grief is real, and our shame is real. The Lotus Key is not ours to give. It belongs to its bearer."),
            (RUANHAI, "Then the bearer will come with me, under guard, to a council of the orthodox sects."),
            (YUN, "The bearer will do no such thing. You may stay as our guests. Without tea."),
            "|",
            (MO, "No tea. She's furious. I haven't seen her refuse tea since the Cinder Peak incident. Nobody talks about the Cinder Peak incident."),
            (MO, "Keep away from the green armour. Especially the young one. He's been glaring at you since the gate."),
            ),
          B("duel", "The Young Master's Glare",
            "Ruan Jingtao, the Iron Scale's heir, does not keep away from you. He brings friends.",
            (RUAN, "So you're the famous Lotus heir. You look like a farmer. My cousin died on the Crimson Road. What did you ever lose?"),
            (P, "My mother. My village. Nearly my senior sister. I'm sorry for your cousin."),
            (RUAN, "Sorry. Everyone on this mountain is sorry. My friends want to see if you're sorry with a sword."),
            "@F:TrainingGround", ">Defend yourself against the Iron Scale disciples",
            "@T",
            (RUAN, "...Fine. You can fight. That doesn't make you right."),
            (RUAN, "My cousin could fight too. It didn't help him. Remember that, farmer."),
            foe="iron_scale_disciple", count=3),
          B("probe", "Theft in the Guest Hall",
            "In the night the Iron Scale's gift chest is broken open, and an Azure Cloud robe is found beside it.",
            (HAN, "Their gift chest was forced in the night. An Azure Cloud outer robe was left beside it. Neatly folded. Too neatly."),
            "@R:Pavilion", (N, "The guest hall is a storm of green armour and shouting. The chest lies open, and beside it, a folded blue robe."),
            "@I:Pavilion", ">Examine the forced gift chest",
            (N, "The lock was cut with a blade that leaves a curved mark. There are traces of blood lotus in the cut. No Azure Cloud blade smells like that."),
            "@T",
            (HAN, "Someone wants us fighting. Someone who carries blood lotus and knows where our laundry is kept."),
            (HAN, "Gu had friends here. Some of them are still here. I'm starting to hate folded robes."),
            prop="treasure_chest", thing="the forced gift chest"),
          B("hunt", "The Folder of Robes",
            "Footprints in the dew lead from the guest hall to the outer pines, where someone has been folding robes for a living.",
            "@R:OuterPines", (N, "In a hollow under the pines: a stack of stolen robes, blue and green, and a blade with a curved edge still wet."),
            "@F:OuterPines", (N, "Two of the sect's own servants turn from the hollow with knives. Their eyes flash red at the edges."),
            "@G:OuterPines", ">Gather the stolen robes as proof",
            "@T:SectGate",
            (SHI, "I know them. They carried food to the Law Hall cells. I saw them once in the Abyss too, bringing sacks. I didn't say. I'm sorry."),
            (P, "You didn't know what it meant, Xiao Shi."),
            (SHI, "I know now. I'll say everything I remember. Everything. Even the parts I'd rather keep in the cage."),
            foe="demon_cultivator", item="letter", noun="stolen robes"),
          B("social", "Evidence Before the Envoys",
            "The Sect Master lays the stolen robes and the curved blade before Ruan Hai. He looks at them for a long time.",
            (YUN, "Your chest was opened by the Blood Moon. The robe was ours, and stolen. They want our sects at each other's throats."),
            (RUANHAI, "...And they very nearly had it. My son had his sword half drawn at breakfast."),
            (RUANHAI, "I do not withdraw my demand. But I withdraw my accusation. There will be a duel of banners instead. By the old law."),
            "|",
            (MO, "The Nine Banners. Nine duels, nine champions a side. Nobody's done that in eighty years. We'll need nine people who can fight."),
            (MO, "You're one. Pick the other eight. Choose well; the loser's sect gives up the question."),
            ),
          B("gather", "Nine Banner Poles",
            "The old law requires nine banner poles cut from the sect's own pines. Nobody remembers how tall. Lu Ping guesses.",
            (LU, "Nine banner poles! From our own pines! The law says 'as tall as honour'. I've decided honour is about four men tall."),
            "@G:OuterPines", ">Cut banner poles in the outer pines",
            "@T:SectGate",
            (LU, "Perfect. Very honourable poles. I've also started a betting book. The Iron Scale are betting too. Business is booming."),
            item="spirit_stone", noun="pine banner poles"),
          B("social", "Choosing Nine",
            "Nine champions for the Azure Cloud. Everyone wants to be chosen. Not everyone should be.",
            (YAN, "Thunder Peak volunteers. All of Thunder Peak. We've been practising shouting in green. Pick me."),
            "|",
            (ZHAO, "I'm on your list. Don't argue. The Zhao clan has fought in every duel of banners since the sect was founded. All two of them."),
            (ZHAO, "And Han Xue. And Wei Tong, because he'll sulk otherwise, and a sulking Wei Tong eats the whole kitchen."),
            "|",
            (SHI, "I'm not on the list. Good. I'll hold the banners. I'm good at holding things. I held on for weeks in that cage."),
            ),
          B("defend", "Night Before the Banners",
            "The night before the duel, someone rings the gate bell and sets fire to the Iron Scale's camp.",
            (LU, "Fire at the Iron Scale camp! And I didn't ring the bell this time, someone else did, which is very rude!"),
            "@I:SectGate", ">Ring the bell to wake both sects",
            (N, "The bell booms. Blue robes and green armour pour out together, buckets in hand, as masked figures slip toward the pines."),
            "@F:SectGate",
            "@F2:OuterPines",
            "@T:SectGate",
            (RUAN, "You... carried water to my camp. You fought the arsonists beside my disciples. Why?"),
            (P, "Because it was on fire, Ruan Jingtao."),
            (RUAN, "...That's a stupid reason. It's the best reason I've heard in a year. The duel's still on tomorrow."),
            foe="demon_cultivator", foe2="demon_cultivator", prop="bronze_bell", thing="the gate bell"),
          B("interlude", "The Rules of Banners",
            "Elder Bai reads the old rules of the Nine Banners aloud, with commentary nobody asked for.",
            (BAI, "Rule one: no killing. Rule two: no crippling. Rule three: no insulting the other sect's grandmother. Rule three was added later."),
            (BAI, "The last duel of banners, eighty years ago, ended when both champions fell in love. Rule nine was added after that."),
            "|",
            (YUN, "Win if you can. Lose if you must. But whatever happens, make them see we are not their enemy."),
            (YUN, "The Blood Moon is laughing at us. Let's give it less to laugh at."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 24
    C("The Nine Banners", "sect",
      "Nine duels, nine banners, two sects and eighty years of dusty rules. The Iron Scale fights for its dead; the Azure "
      "Cloud fights for the right to keep carrying its own burden. And beneath the plaza, the cracked Azure Eye listens "
      "to every blow.",
      cast=[MO, YUN, ZHAO, HAN, WEI, YAN, RUAN, RUANHAI, LU, SHI, BAI], foes=["iron_scale_disciple", "sparring_disciple"],
      items=["spirit_stone", "medicine", "spirit_herb"], props=["stone_stele", "bronze_bell", "seal"],
      boss=("tournament_champion", "Ruan Jingtao", "FormationArray"),
      beats=[
          B("orders", "Banners Around the Plaza",
            "Nine banners ring the formation plaza. Both sects fill the walls. Lu Ping's betting book is thicker than the rules.",
            "@R:FormationArray", (N, "Nine banners, blue and green, ring the plaza. Both sects crowd the walls. Somebody is selling roasted chestnuts at three times the price."),
            "@T:SectGate",
            (MO, "First banner: Wei Tong. He insisted on going first. He said he wants to finish before lunch."),
            (MO, "Stand with me and watch. A champion watches before he fights. Otherwise he's just a man with a sword."),
            ),
          B("battle", "The First Three Banners",
            "Wei Tong wins the first banner. Yan Tie shouts his way through the second. Han Xue loses the third, and is furious about it.",
            (WEI, "First banner! I won! He was very big and I was very hungry! Hunger wins!"),
            "@F:FormationArray", ">Help the heralds clear the rowdy crowd",
            (N, "Iron Scale supporters vault the wall after the second banner. Azure Cloud disciples vault after them. The heralds look at you."),
            "@F2:TrainingGround",
            "@T:SectGate",
            (HAN, "I lost the third. He was better. I'm going to go and be angry in the pavilion. Win yours."),
            foe="iron_scale_disciple", foe2="sparring_disciple"),
          B("probe", "The Eye Is Listening",
            "Between banners you feel the cracked Azure Eye stir under the plaza, drinking the qi of every duel.",
            "@R:FormationArray", (N, "Every clash on the plaza sends a ripple through the stone. Beneath your feet, the Azure Eye's crack drinks the ripples in."),
            "@I:FormationArray", ">Press your palm to the formation between bouts",
            (N, "Faint, beneath the stone: the breathing you felt beside the Sect Master. Slower now. Pleased."),
            "@T",
            (BAI, "You felt it too? The Eye is feeding on the duel. Fighting on the formation was always a strange tradition."),
            (BAI, "I'll note it. I note everything. I'm noting that you look pale. Go and eat something before your banner."),
            prop="seal", thing="the formation stones"),
          B("social", "Fourth to Sixth",
            "Zhao Kang takes the fourth banner with style. The fifth is a draw. The sixth, Iron Scale. The plaza holds its breath.",
            (ZHAO, "Fourth banner, mine. Did you see the second exchange? Tell me you saw the second exchange. It was beautiful."),
            (ZHAO, "Fifth was a draw. Sixth went to them. Three all. Your banner's the ninth. Of course it is. Everything important falls on you."),
            "|",
            (RUAN, "Ninth banner. You and me. I asked for it. My father said I was being childish. I said yes."),
            (RUAN, "My cousin used to say the Azure Cloud were soft. I want to know if he was wrong."),
            ),
          B("gather", "Salve Between Bouts",
            "Both sects' fighters are battered. Elder Hua has sent salve, and someone has to carry it round both camps.",
            (HUA, "Salve for every fighter. Both sides. A bruise doesn't care what colour the robe is."),
            "@G:HerbGarden", ">Gather salve jars from the Medicine Hall",
            "@T:SectGate",
            (RUANHAI, "You brought salve to my disciples. Before your own bout. Hm."),
            (RUANHAI, "My son thinks the Azure Cloud is soft. I'm beginning to think he means kind, and doesn't know the word."),
            item="medicine", noun="salve jars"),
          B("train", "Seventh and Eighth",
            "The seventh banner goes to Yan Tie. The eighth to the Iron Scale. The ninth is yours. Elder Mo gives you one minute of advice.",
            (MO, "Four all. Ninth banner. One minute of advice. The boy fights with his grief. Don't fight his grief. Fight him."),
            "@M:StoneBridge", ">Steady your golden core before the ninth banner",
            (N, "Your core turns slowly, gold and steady. The plaza's noise falls away until there is only breath, and the next breath."),
            "@T",
            (MO, "Adequate. Go."),
            ),
          B("boss", "The Ninth Banner",
            "The ninth banner: you against Ruan Jingtao, heir of the Iron Scale, with both sects' fate on the plaza.",
            "@R:FormationArray", (N, "The plaza falls silent. Ruan Jingtao draws a blade of green steel and salutes, stiffly, correctly."),
            "@X",
            (RUAN, "For my cousin! For the eleven!"),
            (P, "For them too, Ruan Jingtao. Come on."),
            "@T:SectGate",
            (RUAN, "You could have ended it at the third exchange. You didn't. You let me fight until I'd said everything I needed to say with my sword."),
            (RUAN, "My cousin was wrong. You're not soft. You're something worse. You're kind on purpose."),
            ),
          B("social", "The Question Given Up",
            "Five banners to four. By the old law the Iron Scale gives up the question of the Lotus Key. Ruan Hai does it with dignity.",
            (RUANHAI, "The Iron Scale gives up the question, by the old law. The key stays with its bearer. We will not raise it again."),
            (RUANHAI, "And we will ask for something else. When you go after the Blood Moon, send word. The Iron Scale will stand with you."),
            "|",
            (YUN, "Thank you, Sect Master Ruan. Now there will be tea. A great deal of tea."),
            (YUN, "The Cinder Peak incident started with tea. Let us hope this ends with it."),
            ),
          B("festival", "Tea for Two Sects",
            "The Azure Cloud serves tea to the Iron Scale on the plaza. It is awkward. Then it is less awkward. Then Wei Tong sings.",
            (LU, "Tea for everyone! I'm pouring! I've won nineteen stones and lost eighteen. I'm up one stone and I feel like an emperor."),
            "@G:FormationArray", ">Carry tea cups around the plaza",
            "@I:FormationArray", ">Raise a cup to the fallen of both sects",
            (N, "Two sects raise their cups together, to eleven Iron Scale dead and to everyone the Blood Moon has taken. Then Wei Tong sings, badly."),
            "@T",
            (RUAN, "Your senior brother is a terrible singer. He's wonderful. We don't have anyone like that. We should get one."),
            item="spirit_herb", noun="tea cups", prop="seal", thing="the raised cups"),
          B("stage", "Five Banners to Four",
            "When the plaza empties, you sit where the ninth banner stood and let the duel settle into your core.",
            "@M:FormationArray", ">Settle your core on the empty plaza",
            (N, "Your core spins, and each turn remembers a blow you didn't strike. It grows denser, and quieter. Middle stage of Core Formation."),
            (N, "Beneath you the Azure Eye breathes. Slower now, and patient, like something that can wait a long time for what it wants."),
            "@T:SectGate",
            (HAN, "I lost the third banner. I'm going to train until I never lose another. You're going to help. Tomorrow. Dawn."),
            (HAN, "And... you did well. That's all. Don't look at me like that."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 25
    C("Smoke on the Border", "bamboo_forest",
      "The duel settled the question, but not the border. Iron Scale raiders are burning herb groves on the forest's "
      "eastern edge, and Ruan Hai swears he never sent them. The raiders' eyes are red at the edges, and they are "
      "wearing borrowed armour.",
      cast=[RUAN, HAN, LAN, ZHAO, HUA, YAN], foes=["iron_scale_disciple", "demon_cultivator", "corrupted_wolf"],
      items=["spirit_herb", "letter", "rune_fragment"], props=["seal", "treasure_chest", "stone_stele"],
      foe_names={"iron_scale_disciple": "green-armoured raiders"},
      beats=[
          B("orders", "Groves on Fire",
            "Smoke rises from the forest's eastern groves. The hermit sends a crane: green armour, burning herbs, and something wrong.",
            (HUA, "The eastern groves are burning. The best moonbell in the province. The hermit's crane says green armour."),
            (HUA, "The Iron Scale swore peace a week ago. Either they lied, or someone is wearing their armour. Find out which."),
            "@R:bamboo_forest/HerbGrove", (N, "The herb grove is ash and smoke. Among the burned moonbell, a scrap of green scale armour, still hot."),
            "@T:Clearing",
            (LAN, "They came at dawn, in green. They burned the grove and left the wolves alone. Bandits burn everything. These chose."),
            map="sect"),
          B("battle", "Raiders in Green",
            "The raiders are still in the forest, burning their way toward the spirit spring.",
            (HAN, "They're heading for the spring. If they burn the spring, the whole forest sickens."),
            "@F:HerbGrove",
            "@F2:SpiritSpring", (N, "Green-armoured raiders turn at the spring, torches raised. Their eyes are red at the edges."),
            "@R:Stream", (N, "The raiders fall back into the bamboo. One leaves his helmet in the mud. It's too big for him."),
            foe="iron_scale_disciple", foe2="iron_scale_disciple"),
          B("probe", "Armour Too Big",
            "The fallen raider's armour is genuine Iron Scale work, but made for a larger man. Stolen, or taken from the dead.",
            "@R:Stream", (N, "The helmet is real Iron Scale steel. The name scratched inside is not the raider's."),
            "@I:Stream", ">Read the name inside the helmet",
            (N, "Ruan Mingyu. Crimson Road. The Iron Scale's dead cousin, whose armour went into the Abyss with him."),
            "@T:Clearing",
            (RUAN, "That's my cousin's helmet. They took it off his body. They're wearing our dead to start a war."),
            (RUAN, "The Iron Scale will hunt them with you. Not for peace. For him."),
            prop="treasure_chest", thing="the fallen helmet"),
          B("hunt", "Following the Ash",
            "The raiders leave a trail of ash and red-eyed wolves. Ruan Jingtao insists on walking in front.",
            "@R:ForestPath", (N, "A trail of burned bamboo leads north. Ruan Jingtao walks ahead of you, jaw tight, sword drawn."),
            "@F:WolfDen", (RUAN, "Wolves with red eyes! Is everything in your forest trying to eat us?"),
            "@G:WolfDen", ">Gather the raiders' dropped orders",
            "@T:ForestPath",
            (RUAN, "Orders. In Blood Moon script. They're camped in the old bandit camp. Of course they are. Everyone camps there."),
            foe="corrupted_wolf", item="letter", noun="dropped orders"),
          B("rescue", "The Camp of Borrowed Armour",
            "The old bandit camp is full of green armour on red-eyed men. And in a pen at the back, three real Iron Scale disciples.",
            "@R:BanditLookout", (N, "In the camp below: green armour on red-eyed men, and in a pen at the back, three young disciples in torn green robes."),
            "@F:BanditCamp", (RUAN, "Those are ours! In the pen! Taken on the Crimson Road! Alive! Get them out!"),
            "@I:BanditCamp", ">Break open the pen",
            (N, "The pen's lock breaks. Three Iron Scale disciples stumble out, thin and dazed, and throw themselves on Ruan Jingtao."),
            "@T:Clearing",
            (RUAN, "Three of the eleven. Alive. My father thought... we all thought..."),
            (RUAN, "I owe you, Azure Cloud. The Iron Scale doesn't like owing. We're going to have to become friends to pay it off."),
            foe="demon_cultivator", prop="prison_cage", thing="the pen"),
          B("social", "What the Captives Saw",
            "The rescued Iron Scale disciples were held in the Abyss before they were brought here. They saw things.",
            (RUAN, "They were in the Abyss. Near the cages. They say someone was talking about you. By name."),
            "|",
            (N, "The eldest captive speaks haltingly. An old man in Law Hall grey, he says. He said the heir must grow strong first. Strong enough to be worth it."),
            (P, "Worth what?"),
            (N, "He didn't say. He only said it the way you'd say a crop needs to ripen."),
            "|",
            (HAN, "Gu. Waiting for you to grow. Like a farmer. I'm going to be sick."),
            (HAN, "Then we grow faster than he can plan for. That's all we can do."),
            ),
          B("cultivate", "Healing the Burned Grove",
            "The hermit asks you to help him heal the burned grove with the sutra. Fire is fast; roots are patient.",
            (LAN, "Fire is fast. Roots are patient. Sit in the ash with me and remind the roots they're still alive."),
            "@M:HerbGrove", ">Heal the burned grove with the Heart Sutra",
            (N, "You breathe the sutra into the ash. Root. Stem. Beneath your palms, something green stirs in the black."),
            "@T:Clearing",
            (LAN, "Seedlings by morning. The forest is better at forgiving than we are. We could learn."),
            ),
          B("battle", "Red Eyes Come Back",
            "The raiders who escaped come back at night for the rescued captives, and bring more wolves than men.",
            (ZHAO, "Elder Mo sent me. He said you'd need someone to complain at. Also, there are about thirty wolves behind you."),
            "@F:Clearing",
            "@F2:ForestPath",
            "@T:Clearing",
            (ZHAO, "The Iron Scale boy fought well. Don't tell him. I've just got used to one rival; I can't handle two."),
            foe="corrupted_wolf", foe2="demon_cultivator"),
          B("delve", "The Raiders' Cache",
            "Under the bandit camp's firepit the raiders buried a cache: stolen armour, Frenzy Pills and a list.",
            "@R:BanditCamp", (N, "The firepit is cold. Beneath the ash, a hatch of rotten boards, and beneath that, a pit."),
            "@G:BanditCamp", ">Dig out the raiders' buried cache",
            "@I:BanditCamp", ">Open the cache's iron box",
            (N, "Frenzy Pills, forty of them. Iron Scale armour from nine dead disciples. And a list of sects: Iron Scale, Azure Cloud, Moon-Well, Zhao."),
            "@T:Clearing",
            (RUAN, "Four names. Four sects to set against each other. We were just the first."),
            (P, "Then the other three need to know. Before the pills reach them."),
            item="rune_fragment", noun="buried cache", prop="treasure_chest", thing="the iron box"),
          B("interlude", "Letters to Four Sects",
            "Ruan Jingtao and you write to the sects on the list, together. It is the first letter the Iron Scale has co-signed in a century.",
            (RUAN, "My father will faint. An Iron Scale letter, co-signed by an Azure Cloud disciple. We'll need to invent a new seal."),
            (RUAN, "Moon-Well, Zhao clan... they'll listen to two sects where they'd laugh at one."),
            "|",
            (HAN, "Two sects writing together. That's how the Verdant Lotus and the Azure Cloud started, the hermit says."),
            (HAN, "It ended with a seal under the earth. Let's hope ours ends better."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 26
    C("The Sunken Archive", "bamboo_forest",
      "The Verdant Lotus kept an archive beneath their ruins, flooded when the sect fell. The hermit has never dared go "
      "down. With a golden core, you can hold your breath long enough, and the archive may know how the Sky Isles open.",
      cast=[LAN, BAI, HAN, ZHAO, SHI], foes=["stone_golem", "spirit_wolf", "rogue_cultivator"],
      items=["jade_slip", "rune_fragment", "spirit_stone"], props=["stone_stele", "jade_slip", "seal"],
      boss=("ancient_guardian", "The Drowned Librarian", "RuinsInner"),
      things={"seal": "the archive seal", "stone_stele": "the flooded stele"},
      beats=[
          B("orders", "What Bai Wants to Know",
            "Elder Bai needs to know how the Sky Isles open. The pagoda's books say sixty years; they don't say when the sixty began.",
            (BAI, "The Sky Isles open once in sixty years. Every book says so. No book says which sixty. We could wait a week or a lifetime."),
            (BAI, "The Verdant Lotus went to the isles for the first seal's star iron. If anyone recorded the cycle, they did. Beneath their ruins."),
            "@R:bamboo_forest/RuinsGate", (N, "The lotus archway stands open, as it has since the day it opened for you. Below the courtyard, water shines in the dark."),
            "@T:RuinsGate",
            (LAN, "The archive. Flooded when the sect fell. I never went down. Some of my masters are still down there. Their bones, at least."),
            map="sect"),
          B("gather", "Breath Stones",
            "The hermit says the Verdant Lotus used breath stones to walk the flooded halls. There are still some in the shrine.",
            (LAN, "Breath stones. Hold one under your tongue and the water forgets you're not a fish. There should be some left at the shrine."),
            "@G:AncientShrine", ">Find breath stones in the ruined shrine",
            "@T",
            (LAN, "Five stones. Enough for three of you, twice. Don't swallow them. My master swallowed one once. She was a fish for a week."),
            item="spirit_stone", noun="breath stones"),
          B("delve", "Into the Flooded Halls",
            "Under the courtyard the Verdant Lotus archive lies drowned: shelves of jade, halls of green water, and silence.",
            "@R:RuinsInner", (N, "Green water, still and clear. Shelves of jade slips glimmer on the bottom like fish scales."),
            "@G:RuinsInner", ">Gather drowned jade slips",
            "@I:RuinsInner", ">Read the flooded stele",
            (N, "The first seal's star iron came from the isles, in the sixtieth year after the Patriarch's first ascent. The isles keep his count."),
            "@F:RuinsGate", (N, "The archive's stone keepers rise from the water, streaming, to see who reads their stele."),
            "@R:RuinsGate", (N, "You surface, gasping. The breath stone tastes of mint and old tears."),
            item="jade_slip", foe="stone_golem"),
          B("probe", "The Patriarch's Count",
            "Elder Bai does the arithmetic by the ruins gate, on a flat stone, with a stick, muttering.",
            (BAI, "Sixty years after the Patriarch's first ascent. He climbed three hundred and... carry the nine... The isles open this winter."),
            (BAI, "This winter! We have months, not years! I need to sit down. I am sitting down. I need to sit down more."),
            "@I:AncientShrine", ">Check Elder Bai's arithmetic against the shrine stele",
            (N, "The shrine's stele confirms it, in a Verdant Lotus hand: they open when the Patriarch's stars are low. This winter, they will be."),
            "@T:RuinsGate",
            (HAN, "Months. We need the materials, the design, the people. And the isles are guarded, the books say. By what?"),
            prop="stone_stele", thing="the shrine stele"),
          B("social", "Bones in the Archive",
            "In the lower hall you find what the hermit feared: the Verdant Lotus elders who stayed to guard the archive.",
            "@R:RuinsInner", (N, "In the lowest hall lie seven skeletons in green-stained robes, seated in a circle, hands still joined."),
            "@T:RuinsGate",
            (LAN, "Seven. My teachers' teachers. They stayed. They held the water back so the archive would survive. I ran past this door."),
            (LAN, "I ran past this door. I heard them singing. I ran."),
            "|",
            (SHI, "I heard singing in the cages, too. Other prisoners. It helped. I don't think they minded that I didn't sing back."),
            (SHI, "I think they just wanted someone to hear."),
            ),
          B("battle", "Robbers in the Water",
            "Rogue cultivators have followed the rumour of Verdant Lotus treasure, and they're diving without breath stones.",
            (ZHAO, "Rogues again. Diving for the archive. Half of them are drowning and the other half are drowning slower."),
            "@F:RuinsGate",
            "@F2:AncientShrine",
            "@T:RuinsGate",
            (ZHAO, "I pulled three of them out of the water before I hit them. The Zhao clan has standards. Low ones, but standards."),
            foe="rogue_cultivator", foe2="rogue_cultivator"),
          B("boss", "The Drowned Librarian",
            "The archive's last guardian is a stone librarian that has been reshelving the same drowned slips for three hundred years.",
            "@R:RuinsInner", (N, "A stone figure moves through the water, slow and precise, lifting slips from the floor and placing them on shelves that are no longer there."),
            "@X", (N, "It turns. Its eyes glow green. It does not ask who carries the flower. It asks: have you returned your books?"),
            "@I:RuinsInner", ">Return the drowned slips to the librarian",
            (N, "The librarian takes the slips, places them on a shelf that isn't there, and kneels. Its work is finished."),
            "@T:RuinsGate",
            (BAI, "It asked if you'd returned your books. A librarian after my own heart. I want it carved over the pagoda door."),
            prop="jade_slip", thing="the drowned slips"),
          B("cultivate", "Song for Seven",
            "The hermit goes down to the seven skeletons at last, and asks you to sit with him while he sings the song he ran from.",
            (LAN, "They sang the Heart Sutra while the water rose. I ran. Now I'm going to sing it back to them. Sit with me. I may not finish."),
            "@M:RuinsInner", ">Sit with the hermit while he sings",
            (N, "His voice cracks on the first line, steadies on the second. By the third verse the water in the lower hall is glowing faintly green."),
            (N, "When he finishes, the seven skeletons are gone. Only seven lotus flowers float where they sat."),
            "@T:RuinsGate",
            (LAN, "They heard. I don't know how I know. They heard. Three hundred years late, and they heard."),
            ),
          B("gather", "Slips for the Sect",
            "The archive's surviving slips are Verdant Lotus lore: sealing arts, star charts, recipes. Bai wants every one dried.",
            (BAI, "Every surviving slip. Dry them in the shade, never the sun. Jade sulks in the sun. So do I."),
            "@G:RuinsInner", ">Carry the surviving slips up from the archive",
            "@T:RuinsGate",
            (BAI, "Star charts! Sealing diagrams! A recipe for turtle soup! The Verdant Lotus understood what matters."),
            item="jade_slip", noun="surviving slips"),
          B("social", "The Hermit Stops Running",
            "On the way out, the hermit says something he has not said in three hundred years.",
            (LAN, "I think I have stopped running. I don't know what to do now. Running was a very time-consuming hobby."),
            (P, "You could come to the sect. The seed you gave me is growing in the pond."),
            (LAN, "Is it? ...Not yet. But I'll come and look at it. From a distance. That's a beginning."),
            "|",
            (HAN, "Months until the isles open. We'd better go home and tell the Sect Master to start packing."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 27
    C("Tea at the Drunken Crane", "qingshi_town",
      "The four sects on the raiders' list agree to meet on neutral ground: Madam Fang's inn in Qingshi. There will be "
      "tea, and noodles, and Iron-Fang washing the dishes. There will also be an assassin, because there always is.",
      cast=[FANG, TIE, ZHOU, DU, RUAN, RUANHAI, TIANLU, HAN, LIUER, LIU, PAN], foes=["demon_cultivator", "blood_guard"],
      items=["medicine", "letter", "spirit_herb"], props=["treasure_chest", "bronze_bell", "seal"],
      boss=("demon_elder", "The Pale Assassin", "BackAlley"),
      beats=[
          B("orders", "Neutral Ground",
            "Madam Fang has agreed to host four sects at the Drunken Crane. She has also raised her prices, on principle.",
            "@R:MainStreet", (N, "Four sects' banners hang outside the Drunken Crane. The whole town has found reasons to walk past very slowly."),
            "@T:MainStreet",
            (FANG, "Four sects in my inn! Four! I've hidden the good wine and brought out the diplomatic wine. It's the same wine. The cups are nicer."),
            (FANG, "My dishwasher is very excited. Well. He's very quiet. That's excited, for him."),
            ),
          B("social", "The Dishwasher",
            "Iron-Fang is washing dishes behind the inn. He has been since the siege. He is surprisingly good at it.",
            (TIE, "Sect brat. You're here for the big meeting. I'm here for the big pile of cups. We all have our battles."),
            (TIE, "My men are working the farms. My family's still in the Abyss. Every plate I wash, I count. It's a very long count."),
            (P, "We'll bring them out, Tie Hu. I haven't forgotten."),
            (TIE, "Neither have I. Now move, you're standing in my rinse water."),
            "|",
            (LIUER, "Iron-Fang lets me dry. He says I'm the best dryer in Qingshi. I'm the only dryer in Qingshi."),
            ),
          B("probe", "Four Chairs, Five Guests",
            "The meeting table is set for four sect leaders. Someone has quietly added a fifth chair.",
            "@R:Inn", (N, "The upstairs room is set for four: Azure Cloud, Iron Scale, Zhao clan, Moon-Well. A fifth chair stands in the corner, facing the window."),
            "@I:Inn", ">Inspect the fifth chair",
            (N, "Beneath the seat, a crescent scratched into the wood, and fresh. Someone is expected who wasn't invited."),
            "@T:MainStreet",
            (HAN, "A fifth chair. A crescent. Someone thinks they're coming to this meeting. I'm going to be very rude to them."),
            prop="seal", thing="the fifth chair"),
          B("social", "The Zhao Ancestor",
            "Zhao Kang's great-grandfather arrives for the Zhao clan, and is exactly as warm as a gold bar left out in winter.",
            (TIANLU, "So you're the village child my great-grandson writes about. He writes about you more than he writes to me."),
            (TIANLU, "He says you're insufferable. From him, that's a love letter. The Zhao clan will listen. Once."),
            "|",
            (RUANHAI, "Ancestor Zhao. Still alive, I see. Still counting gold, I hear."),
            (TIANLU, "Sect Master Ruan. Still losing duels, I hear. To children."),
            (RUANHAI, "...It was a very good child."),
            ),
          B("defend", "The First Cup",
            "Madam Fang pours the first cup. Han Xue knocks it out of Sect Master Ruan's hand. It hisses on the floor.",
            (HAN, "Don't drink! The tea smells of blood lotus! Somebody's in the kitchen!"),
            "@I:Inn", ">Seal the inn's kitchen door",
            (N, "The kitchen door bangs shut under your ward. Behind it, something heavy hits the wood and snarls."),
            "@F:MainStreet", (N, "Servers throw off their aprons. Crimson robes underneath. Knives come out of the noodle baskets."),
            "@F2:MarketSquare",
            "@T:MainStreet",
            (DU, "Six of them, dressed as servers. Madam Fang hired them yesterday. She's mortified. She's hitting one with a ladle."),
            foe="demon_cultivator", foe2="blood_guard", prop="seal", thing="the kitchen door"),
          B("hunt", "Where the Poisoner Went",
            "The poisoner slipped out of the kitchen's back window. Iron-Fang saw which way. He's already running.",
            (TIE, "Pale man, no apron, out the back window. I threw a pot at him. I missed. I never miss. He's quick."),
            "@R:BackAlley", (N, "The back alley is empty. Too empty. A pot lies dented on the stones. Above, a shutter swings shut."),
            "@F:Riverside", (N, "More crimson servers wait at the docks, blocking the ferry. The poisoner's escape route."),
            "@T:Riverside",
            (PAN, "Pale fellow jumped in the river. Swam like an eel. Didn't come up. I've seen that before. The Blood Moon ones swim under."),
            (PAN, "He'll come up at the graves. They always do. Always the graves."),
            foe="blood_guard"),
          B("boss", "The Pale Assassin",
            "The poisoner comes up at the graves, as Old Pan said. He is pale as fish-belly, and he has been waiting for you, not the sect masters.",
            "@R:Graveyard", (N, "Among the tombs stands a man so pale he seems carved from candle wax. He smiles. His teeth are red."),
            "@X",
            (N, "The heir, he says. I was told to test you, not kill you. But I've always been bad at following orders."),
            "@T:MainStreet",
            (RUAN, "You chased him alone? Into a graveyard? The Iron Scale would call that brave. The Azure Cloud would call it stupid."),
            (RUAN, "I call it the reason my father is still alive. Thank you. Again. I'm running out of ways to say it."),
            arena="Graveyard"),
          B("social", "Four Seals on One Page",
            "Over a second pot of tea, one that everyone watches Madam Fang pour, four sects put their seals on one page.",
            (RUANHAI, "Four sects. One page. Mutual warning, mutual aid, against the Blood Moon. My seal first. I nearly died for this one."),
            "|",
            (TIANLU, "The Zhao seal. Gold, naturally. My great-grandson will pretend not to be proud of me. He's very bad at it."),
            "|",
            (ZHOU, "And the yamen of Qingshi as witness! My best seal! My only seal! I am a witness to history! I'm going to cry!"),
            ),
          B("festival", "Noodles for Four Sects",
            "Peace is signed. Madam Fang makes noodles for four sects, and everyone eats from the same pot, watching each other.",
            (FANG, "Noodles! From one pot! If anyone poisons this pot, they poison themselves, which is the most honest diplomacy I know."),
            "@G:MarketSquare", ">Carry bowls from the market stalls",
            "@I:Inn", ">Serve the first bowl at the Drunken Crane",
            (N, "Four sect masters eat from the same pot, watching each other over the rims. Iron-Fang washes their bowls, and nobody notices him smile."),
            "@T:MainStreet",
            (LIU, "My son dried every bowl. He's asleep in a barrel. He says it's the best day of his life. He says that every day now."),
            item="medicine", noun="noodle bowls", prop="treasure_chest", thing="the first bowl"),
          B("stage", "The Test, Not the Kill",
            "The assassin said he was sent to test you, not kill you. You sit in the clean temple and wonder who wanted to know.",
            "@M:Temple", ">Sit with the assassin's words in the temple",
            (N, "Test you, not kill you. Someone is measuring your core the way a farmer measures a crop. You let the thought pass, and your core grows anyway."),
            (N, "Late stage of Core Formation. You're stronger. That's exactly what they want. It's also exactly what you need."),
            "@T:MainStreet",
            (HAN, "Test, not kill. Gu, waiting for you to ripen. The assassin just confirmed it."),
            (HAN, "Fine. We ripen. We ripen so hard it breaks their teeth."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 28
    C("Sword Qi of the Golden Core", "sect",
      "A golden core can throw qi like a blade. Elder Mo intends to teach you how before the isles open, whether you "
      "like it or not, and whether he likes admitting he's proud of you or not. Xiao Shi, meanwhile, still dreams of "
      "cages.",
      cast=[MO, WEI, SHI, MAN, HAN, YAN, HUA, BAI], foes=["training_puppet", "stone_golem", "spirit_wolf"],
      items=["spirit_stone", "spirit_herb", "jade_slip"], props=["stone_stele", "seal", "jade_slip"],
      foe_names={"stone_golem": "sparring golems"},
      beats=[
          B("train", "Qi Like a Blade",
            "Elder Mo's first lesson in sword qi: cut a falling leaf in half without touching it. He demonstrates. Four times.",
            (MO, "Sword qi. The core throws what the hand cannot reach. Watch. Leaf falls. Qi cuts. Leaf is two leaves."),
            (MO, "...That was a gust of wind. Watch again. Leaf falls. There. Two leaves. Your turn."),
            "@M:PlumGarden", ">Cut falling plum petals with sword qi",
            (N, "A thousand petals fall. You cut none. Then one. Then, as the sun sets, every petal that falls near you drifts down in halves."),
            "@T",
            (MO, "Halves. Adequate. Tomorrow, stone."),
            ),
          B("battle", "Stone Tomorrow",
            "Tomorrow is stone: sparring golems that only sword qi can scratch.",
            (MO, "Sparring golems. Palm strikes bounce. Qi cuts. Don't punch them, you'll break your hand and I'll have to fill in a form."),
            "@F:TrainingGround",
            "@F2:TrainingGround",
            "@T:SectGate",
            (WEI, "You cut a golem in half! With your mind! I've been punching them for six years. I feel betrayed by technique."),
            foe="stone_golem", foe2="stone_golem"),
          B("social", "Xiao Shi's Nights",
            "Xiao Man comes to you at night. Her brother still wakes up counting bars. She doesn't know what to do.",
            (MAN, "He wakes up counting. Every night. One, two, three, up to forty. The cage had forty bars."),
            (MAN, "I sit with him. It doesn't help. You were in the Abyss. Maybe he'd talk to you."),
            "|",
            (SHI, "Forty bars. I know it's silly. I know I'm home. My body doesn't know. My body is still counting."),
            (P, "Mine counted too, after the Abyss. I count breaths instead now. It's the same counting, pointed somewhere better."),
            (SHI, "...Breaths. Four in, four out. Like Han Xue says. I'll try. Stay till I fall asleep? Just tonight."),
            ),
          B("cultivate", "Counting Breaths",
            "You sit with Xiao Shi on the stone bridge and count breaths until he stops counting bars.",
            "@M:StoneBridge", ">Count breaths with Xiao Shi on the bridge",
            (N, "Four in, four out. Xiao Shi's shoulders drop by the twentieth breath. By the fortieth he is asleep against the railing."),
            (N, "You keep counting. Your core counts with you, steady and gold, and settles a little deeper."),
            "@T",
            (MAN, "He slept! All night! Without counting! I'm going to make you a pill. It'll probably be a pill."),
            ),
          B("gather", "Iron From the Pines",
            "Elder Mo wants to forge you a practice blade, one that can hold core-qi without shattering. It needs iron from a lightning-struck pine.",
            (MO, "Lightning-struck pine. The iron in the sap holds qi. Find me enough and I'll forge you a practice blade. An ugly one."),
            "@G:OuterPines", ">Collect iron sap from the lightning-struck pines",
            "@T",
            (MO, "Enough. It'll be ugly. Ugly blades live longest. So do ugly elders."),
            item="spirit_stone", noun="iron sap"),
          B("hunt", "Wolves Want the Sap",
            "Iron sap draws wolves. They like the taste. So does Wei Tong, apparently.",
            "@R:OuterPines", (N, "The pines are full of grey wolves licking the sap. Wei Tong is among them, also licking the sap."),
            "@F:OuterPines", (WEI, "It tastes like pine and lightning! Don't judge me! Wolves! Wolves are judging me!"),
            "@G:OuterPines", ">Gather what's left of the sap",
            "@T:SectGate",
            (WEI, "I've learned something about myself today. I don't like it. I'm going to go and lie down."),
            foe="spirit_wolf", item="spirit_herb", noun="remaining sap"),
          B("probe", "The Ugly Blade",
            "Elder Mo forges the practice blade himself, at the formation's edge, at midnight, with a hammer older than the sect.",
            "@R:FormationArray", (N, "Sparks fly at the plaza's edge. Elder Mo works bare-armed, hammering iron sap into a blade by the formation's light."),
            "@I:FormationArray", ">Quench the blade in the formation's light",
            (N, "The blade drinks the formation's light and cools grey and plain. When you lift it, your core answers it like an old friend."),
            "@T:SectGate",
            (MO, "Ugly. Perfect. My master forged mine the same way. It's in my room. I'm too old for it. Don't argue. Take care of yours."),
            prop="seal", thing="the new blade"),
          B("social", "Mo Remembers His Master",
            "Elder Mo is in a talking mood, which happens once a decade. He tells you about his master.",
            (MO, "My master was a terrible teacher. Shouted. Threw things. Made me climb the steps on my hands."),
            (MO, "Then one day he put his hand on my head and said adequate, and I would have died for him. That's all a teacher is."),
            (P, "Elder Mo. Adequate."),
            (MO, "...Don't. Don't you dare. Hmph. Go to bed. My eyes are tired. It's the smoke."),
            ),
          B("battle", "Sword Qi in Earnest",
            "Blood Moon scouts are caught mapping the sect's walls. Your new blade gets its first real test.",
            (HAN, "Scouts on the wall, mapping it. Gu wants to know our defences. Let's teach them a few new ones."),
            "@F:OuterPines",
            "@F2:SectGate", foe="demon_cultivator", foe2="demon_cultivator"),
          B("interlude", "Winter Coming",
            "The first snow falls on the mountain. Elder Bai looks at the sky and says the isles will open soon.",
            (BAI, "First snow. The Patriarch's stars are sinking. The isles will open within the month. I've written to the Sect Master in capitals."),
            "|",
            (YAN, "Thunder Peak wants to go to the isles. All of Thunder Peak. I said you'd pick. You'll pick me. You'll pick me, right?"),
            "|",
            (MO, "The Sect Master will choose soon. Whatever she chooses, you're ready. Adequately ready. More than adequately."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 29
    C("Patrol of the Crimson Rim", "blood_abyss",
      "While the sect waits for winter, somebody has to watch the Abyss. Ye Wuming and the children he took from the Blood "
      "Moon already do. They ask for help: the Blood Moon has begun to dig, and whatever they are digging for is marked "
      "with seven dots.",
      cast=[YE, HAN, ZHAO, YAN, SHI], foes=["blood_guard", "demon_cultivator", "corrupted_wolf"],
      items=["demon_core", "rune_fragment", "thunder_crystal"], props=["treasure_chest", "demon_obelisk", "seal"],
      things={"treasure_chest": "the miners' crate"},
      beats=[
          B("orders", "A Message From the Rim",
            "A child in patched black robes climbs the nine thousand steps with a message from Ye Wuming. She has chosen her own name, too.",
            (LU, "A little girl in black robes at the gate! She says her name is Spring, she chose it herself, and Ye Wuming sent her."),
            (LU, "She's very serious. She's frightening. I gave her a bun. She saluted the bun."),
            "@R:blood_abyss/CanyonEntrance", (N, "Ye Wuming waits at the canyon mouth with three children in black. They watch you with old eyes in young faces."),
            "@T:CanyonEntrance",
            (YE, "You came. Good. The Blood Moon has begun to dig on the bone field. I don't know what for. I'd like to."),
            map="sect"),
          B("probe", "Picks on the Bone Field",
            "Blood Guards are digging on the bone field, very carefully, as if the bones might break something they want.",
            "@R:BoneField", (N, "Blood Guards dig in careful rows among the bones. Crates stand nearby, each stamped with seven small dots."),
            "@I:BoneField", ">Search the miners' crates",
            (N, "Thunder-struck bone, and chips of crystal that hum. Seven dots on every lid, arranged like a ladder."),
            "@T:CanyonEntrance",
            (YE, "Seven dots. I've seen the mark before. On the Patriarch's own door, long ago. I never knew what it meant."),
            (YE, "I was six. I thought it was stars. Maybe it was."),
            prop="treasure_chest", thing="the miners' crates"),
          B("battle", "Breaking the Dig",
            "Whatever they're digging for, they shouldn't have it. Ye Wuming's children watch from the rocks as you break the dig.",
            (YE, "Break the dig. My children will watch. They need to see that the Blood Guards can fall."),
            "@F:BoneField",
            "@F2:ObeliskRing",
            "@R:CanyonEntrance", (N, "The children cheer when the last guard falls, then stop, embarrassed, and cheer again more quietly."),
            foe="blood_guard", foe2="demon_cultivator"),
          B("social", "Children With Names",
            "Ye Wuming's children have chosen their names. They want to tell you, one by one, very formally.",
            (YE, "They want to tell you their names. They chose them. Please be... very serious about it. It matters."),
            "|",
            (N, "Spring. River. Small Mountain. Each child bows and says the name as if handing you something breakable."),
            (P, "Spring, River, Small Mountain. Thank you for telling me. I'll remember."),
            "|",
            (YE, "Nobody ever said their names back to them before. You did it without thinking. That's why I asked you."),
            (YE, "I still haven't found mine. I will. I'm told these things take time."),
            ),
          B("hunt", "Crystals in the Pools",
            "The miners hid their finds in the blood pools. The pools are guarded by wolves who drink the stolen blood.",
            "@R:BloodPools", (N, "Crates bob in the steaming pools, tied with red rope. Wolves circle them, fat and slow and red-eyed."),
            "@F:BloodPools",
            "@G:BloodPools", ">Recover the hidden crystals from the pools",
            "@T:CanyonEntrance",
            (HAN, "Thunder crystals. Why would the Blood Moon want thunder crystals? They're only good for one thing: calling lightning."),
            (HAN, "Why would anyone down here want to call lightning?"),
            foe="corrupted_wolf", item="thunder_crystal", noun="hidden crystals"),
          B("delve", "The Obelisk Stumps",
            "The obelisks you broke have stumps, and someone has been re-carving them. Not with blood runes. With stars.",
            "@R:ObeliskRing", (N, "The obelisk stumps have been re-carved. Not blood runes: seven stars, over and over, climbing each stump like a ladder."),
            "@G:ObeliskRing", ">Collect fragments of the new carvings",
            "@I:ObeliskRing", ">Break the re-carved stump",
            (N, "The stump cracks. A thin thread of red light rises from it, straight up, toward where the stars would be if the Abyss had a sky."),
            "@F:BoneField", (N, "The light draws Blood Guards from the camp, running."),
            "@T:CanyonEntrance",
            (YE, "A ladder of stars. They're building something that climbs. Your sect should know. Your old librarian especially."),
            item="rune_fragment", foe="blood_guard", prop="demon_obelisk", thing="the re-carved stump"),
          B("rescue", "The Last Cage on the Rim",
            "One cage still hangs at the rim, forgotten by everyone except the girl inside it.",
            "@R:BoneField", (N, "Near the rim hangs a single cage, rusted. Inside, a girl in Moon-Well white is singing to herself."),
            "@F:BoneField",
            "@I:BoneField", ">Open the forgotten cage",
            (N, "The lock breaks. The girl stops singing. I'm from the Moon-Well Nunnery, she says. Nobody came. I kept singing so I'd know I was here."),
            "@T:CanyonEntrance",
            (SHI, "I'll take her home. I know what it's like when the door opens. You need someone to walk with you for the first hour."),
            foe="blood_guard", prop="prison_cage", thing="the forgotten cage"),
          B("social", "Letters for the Sect",
            "Ye Wuming asks you to carry everything you found back to the sect. He also asks for something he has never asked for before.",
            (YE, "Take the crystals, the carvings, the crates. Your sect will know what they mean better than I."),
            (YE, "And... when the time comes to march on this place, send for me. My children will help. They know every path."),
            (P, "You've never asked for anything before."),
            (YE, "I've never had anything to protect before. It changes a person. Go. Winter's coming, and so is your sky."),
            ),
          B("battle", "Pursuit to the Array",
            "The Blood Guards are not letting the crystals go. They chase you all the way to the cracked teleport array.",
            (ZHAO, "Elder Mo sent me to bring you home. He didn't mention the forty Blood Guards. He never mentions the important things."),
            "@F:BoneField",
            "@F2:CanyonEntrance",
            "@T:CanyonEntrance",
            (ZHAO, "Go. I'll hold the rim with Ye Wuming's children. I've been told they bite. I respect that."),
            foe="blood_guard", foe2="demon_cultivator"),
          B("probe", "Seven Dots, Explained Badly",
            "Back at the sect, Elder Bai stares at the seven dots for an hour and declares that he has no idea, very loudly.",
            (BAI, "Seven dots! Arranged like a ladder! Thunder crystals! I have no idea! I have read ten thousand books and I have no idea!"),
            (BAI, "But the star charts from the drowned archive. There is a seven-star pattern on the one for the Sky Isles. Red. Unlabelled."),
            "@I:Pagoda", ">Compare the carvings with the drowned star chart",
            (N, "The same seven points. On the Verdant Lotus chart, drawn in red, over the highest of the Sky Isles. Someone has written beside it: never again."),
            "@T:Pagoda",
            (BAI, "Never again. Whatever it was happened before. On the isles. We're going to the isles in a month. Wonderful. Wonderful."),
            map="sect", prop="jade_slip", thing="the star chart"),
      ]),
    # ------------------------------------------------------------------ chapter 30
    C("When the Sky Stair Descends", "sect",
      "In the first week of winter a stair of cloud unrolls from the sky above the sect, and the whole mountain comes out "
      "to stare. The Sky Isles are opening. Elder Bai finishes the Great Azure Formation's design from the Law Hall "
      "archive, the Sect Master chooses her three, and the sect sends them up with dumplings.",
      cast=[YUN, MO, BAI, HAN, ZHAO, WEI, QIAN, MAN, SHI, LU, YAN, HUA], foes=["training_puppet", "demon_cultivator"],
      items=["spirit_stone", "medicine", "cloud_silk"], props=["jade_slip", "stone_stele", "seal"],
      beats=[
          B("orders", "A Stair Made of Cloud",
            "At dawn a stair of cloud unrolls from the sky above the cliff edge. The whole sect comes out in its nightclothes to stare.",
            (LU, "There's a staircase in the sky! Made of cloud! Everyone's out in their pyjamas! Elder Bai's are covered in turtles!"),
            "@R:CliffEdge", (N, "A stair of white cloud descends from the sky, step by step, stopping just above the sea of clouds. It is not solid yet."),
            "@T:SectGate",
            (BAI, "The isles are opening! In a week the stair will hold weight. In a week! I haven't finished the design!"),
            ),
          B("probe", "The Archive Copy",
            "Elder Bai must finish the Great Azure Formation's design from the only complete copy left: the Law Hall's archive.",
            (BAI, "The master diagram is gone with Gu. The Law Hall kept an archive copy, sealed and certified. It's all we have."),
            "@R:ScholarRock", (N, "The Law Hall archive is a locked room of sealed boxes, each stamped with Gu Hanshan's seal. The dust on them is thick."),
            "@I:ScholarRock", ">Unseal the Law Hall's archive copy",
            (N, "The diagram is complete, certified, beautiful. Ten thousand runes. You couldn't tell a single one was wrong. Nobody could."),
            "@T:Pagoda",
            (BAI, "Complete. Certified. I'll need a week to rebuild the formation from it, and a month of Elder Mo's life to build it."),
            prop="jade_slip", thing="the archive copy"),
          B("gather", "What the Formation Needs",
            "The design is done. The list of materials is short and impossible: star iron, thunder crystal, phoenix feathers.",
            (MO, "Star iron, thunder crystal, phoenix feathers. None of them grow on this mountain. All of them grow up there."),
            (MO, "Meanwhile, the frame. Spirit stones. Lots of them. Steward Qian has already fainted once."),
            "@G:FormationArray", ">Gather spirit stones for the formation frame",
            "@T",
            (QIAN, "Two hundred spirit stones! For a frame! A frame! I'm going to faint again. Catch me this time."),
            item="spirit_stone", noun="frame stones"),
          B("social", "Who Goes Up",
            "The Sect Master chooses three for the isles. Everyone pretends they don't want to be chosen. Everyone wants to be chosen.",
            (YUN, "The isles allow few. Three will go. You. Han Xue. And Zhao Kang, who has asked me eleven times, in writing."),
            "|",
            (ZHAO, "Eleven times. With a seal. I'm not ashamed. I'm going to the isles. Try not to fall off anything."),
            "|",
            (YAN, "Thunder Peak was not chosen. Thunder Peak will shout from the bottom of the stair. Very loudly. You'll hear us."),
            ),
          B("gather", "Cloud Silk for the Climb",
            "Elder Hua insists everyone who climbs wears cloud silk sashes, so the wind knows you're guests.",
            (HUA, "Cloud silk sashes. The wind on the isles is rude to strangers. It's polite to guests. This makes you guests."),
            "@G:HerbGarden", ">Collect cloud silk from the drying racks",
            "@T",
            (HUA, "Three sashes, one extra. For whoever falls first. It'll be Zhao Kang. Don't tell him I said that."),
            item="cloud_silk", noun="cloud silk sashes"),
          B("battle", "Visitors Before the Stair",
            "The stair has attracted more than sightseers. Blood Moon scouts try to climb it first.",
            (HAN, "Blood Moon on the stair! They want to reach the isles before us. Why does everyone always want the same things we want?"),
            "@F:CliffEdge",
            "@F2:SectGate",
            "@T:SectGate",
            (HAN, "They wanted the isles. Crystals, dots, ladders. We'll find out why up there. I'm tired of finding out after."),
            foe="demon_cultivator", foe2="demon_cultivator"),
          B("social", "Dumplings for the Sky",
            "The whole sect sends you off with gifts. Most of them are edible. One of them is a hat.",
            (WEI, "Dumplings for the sky. Wrapped in cloud silk, which Elder Hua says is a waste of cloud silk. She's wrong."),
            "|",
            (MAN, "Medicine. Also a hat. For the wind. My brother says the hat's ridiculous. He's wearing one."),
            (SHI, "It's a very good hat. Bring it back. Bring yourself back under it."),
            "|",
            (LU, "I've made a betting book on how many days you'll be gone. The Iron Scale are betting too. So is the Zhao ancestor. By letter."),
            ),
          B("cultivate", "Core at the Peak",
            "The night before the climb, Elder Mo sits with you at the cliff edge beneath the stair of cloud.",
            (MO, "Sit. Your core's full. Too full. It'll crack soon, into something new. Probably on the isles. They're good at cracking people."),
            "@M:CliffEdge", ">Cultivate beneath the stair of cloud",
            (N, "Your golden core burns at its peak, so bright it almost hums. Above you the stair of cloud solidifies, step by step, in the moonlight."),
            "@T:SectGate",
            (MO, "Great Perfection of Core Formation. Adequate. I've said that word more to you than to anyone. Don't let it go to your head."),
            (MO, "Bring me star iron. I'll build the formation while you're gone. I'll check every rune. Twice. Go."),
            ),
          B("social", "The Sect Master's Last Word",
            "Before the climb, the Sect Master says the thing she always says, and one thing she never has.",
            (YUN, "Look at the sky while you're up there. It's good for the soul. I never have time."),
            (YUN, "And... you were an orphan who climbed nine thousand steps with a letter and a pendant. Now you climb into the sky. I'm proud of you."),
            (P, "Sect Master, you've never said that."),
            (YUN, "Sect masters don't. Tell no one. Go."),
            ),
          B("orders", "The Stair Holds",
            "At dawn the stair of cloud holds weight. Three disciples stand at its foot with dumplings, silk and a hat.",
            "@R:CliffEdge", (N, "The stair of cloud is solid under your foot. Cold, and faintly springy, like fresh snow. It climbs out of sight."),
            "@T:SectGate",
            (HAN, "Well. That's a staircase to the sky. Zhao Kang is already complaining about the lack of railing."),
            (HAN, "Let's go. Before the Sect Master says anything else nice and we all start crying at the bottom of a staircase."),
            giver=HAN),
      ]),
]
