"""Volume X · Immortal Ascension — chapters 91-99, leading into the original
finale "Heavenly Tribulation" (chapter 100).

The moon turns red. The fold begins to unfold, and the black gate drifts back
toward the world. Iron-Fang washes and feeds forty bandits; Gu Hanshan asks
for his last requests; Xue Chen, the Patriarch's Shadow and last Rung, hunts
Qingshi and haunts the tribulation peak, and falls at the Heart Mirror in
front of the memory of a village by a creek. Then the Azure Cloud gathers at
the teleport array for the last blood moon.
"""

from .dsl import N, P
from .npcs import *  # noqa: F401,F403
from .saga_gen import B, C

CHAPTERS = [
    # ------------------------------------------------------------------ chapter 91
    C("The Moon Turns Red", "sect",
      "Every night the moon rises a little redder. The fold at the Abyss has begun to breathe, the forty sects' wards are "
      "straining, and Steward Qian's ledger of monthly letters has turned into a ledger of armies. The last blood moon is "
      "weeks away, and everyone knows it.",
      cast=[YUN, QIAN, BAI, SHI, HAN, WEI, LU, ZHAO, HUA, MAN], foes=["void_wraith", "training_puppet", "demon_cultivator"],
      items=["letter", "medicine", "spirit_stone"], props=["jade_slip", "seal", "stone_stele"],
      foe_names={"void_wraith": "shadow-born"},
      beats=[
          B("orders", "Redder Every Night",
            "The moon rises over the sea of clouds, and it is the colour of rust. Tomorrow it will be the colour of blood.",
            "@R:CliffEdge", (N, "The moon rises over the sea of clouds, the colour of rust. The whole sect is on the walls, watching it, not speaking."),
            "@T:SectGate",
            (YUN, "Rust tonight. Blood soon. Qing Luan's crane says weeks. The fold is breathing. The wards are straining. It's time."),
            (YUN, "Everything we've prepared for since the Heart Mirror. It's time. Go and see Steward Qian. His ledger has become a war."),
            ),
          B("probe", "A Ledger of Armies",
            "Steward Qian's ledger of monthly letters has become a ledger of armies. Forty sects. How many each. When they'll arrive.",
            (QIAN, "Forty sects. Eleven thousand fighters. Supplies for a month. I've counted it all. I've never counted anything so important."),
            "@I:IncenseBurner", ">Read Steward Qian's ledger of armies",
            (N, "Iron Scale, three thousand. Zhao clan, two thousand, in gold. Moon-Well, five hundred healers. Qingshi: forty guards, one magistrate, one very old ballista."),
            "@T:IncenseBurner",
            (QIAN, "The ballista. Qingshi's sending the ballista. It's older than me. It's never hit anything. They insist. It's for morale."),
            prop="jade_slip", thing="the ledger of armies"),
          B("social", "Xiao Shi's Last Map",
            "Xiao Shi has drawn one last map: the Abyss, as it will be when the fold opens. Every path. Every door.",
            (SHI, "The last map. The Abyss when the fold opens. Every path. Every door. Every cage. I remember them all. I drew them all."),
            (SHI, "The cages are here, past the gate. Iron-Fang's sister is in that one. I remember her. She shouted at the guards every day."),
            "|",
            (BAI, "It's beautiful. Accurate. Terrible. I've made eleven copies. One for every commander. And one for my ceiling."),
            ),
          B("gather", "Medicine for Eleven Thousand",
            "Elder Hua and Xiao Man have been making medicine for months. It's still not enough. It's never enough.",
            (HUA, "Eleven thousand fighters. I've made four thousand bundles. Xiao Man's made four thousand more. The Moon-Well brings the rest."),
            (MAN, "I've only dropped two hundred! Out of four thousand! That's a record! A good record! Help me pack the last ones!"),
            "@G:LotusPond", ">Pack the last medicine bundles",
            "@T:HerbGarden",
            (HUA, "Eight thousand bundles. Every one with a note inside. Xiao Man's idea. Most say 'come home'. Some say 'eat this, idiot'."),
            item="medicine", noun="medicine bundles"),
          B("battle", "Shadows Under the Red Moon",
            "Under the rusting moon, the shadow-born grow bold. They climb the back path in the open now, not bothering to hide.",
            (LU, "Shadows on the back path! Not even sneaking! Just walking up! Under the red moon! I'm ringing everything!"),
            "@F:OuterPines",
            "@F2:SectGate",
            "@T:SectGate",
            (ZHAO, "They're not even hiding any more. The red moon makes them brave. Or stupid. Same thing, in shadows."),
            foe="void_wraith", foe2="demon_cultivator"),
          B("train", "The Twelve Want to March",
            "Wei Tong's twelve, not new any more, want to march with the army. Wei Tong says no. They ask you.",
            (WEI, "My twelve want to march. To the Abyss. They're not ready. They're so ready. I don't know. You decide. You're scarier."),
            "@F:TrainingGround", ">Test Wei Tong's twelve on the puppets",
            "@T:WeaponRack",
            (WEI, "They're ready. Of course they're ready. I trained them. With Elder Mo's words. They'll march behind me. Right behind me."),
            foe="training_puppet", count=5),
          B("social", "Forty Hands, One Promise",
            "Forty sects' last monthly letters arrive at once. Every one says the same thing, in forty different hands.",
            (QIAN, "Forty letters. All at once. All the same. We're coming. In forty hands. The Zhao clan's is in gold ink. Of course it is."),
            "|",
            (YUN, "Forty sects. Coming. Three hundred years ago, two sects stood at the Abyss. This time, forty-one."),
            "|",
            (HAN, "Forty-one. Plus a town. Plus a bandit's army. Plus a traitor in chains. Plus a chicken. We're a very strange army."),
            ),
          B("cultivate", "Under the Rusting Moon",
            "You sit at the cliff edge under the rusting moon and carry everyone who'll march. Eleven thousand. Light.",
            "@M:CliffEdge", ">Carry eleven thousand under the red moon",
            (N, "Eleven thousand fighters, and the towns behind them, and the families behind the towns. The moon is red. You carry them, and it's light."),
            "@T:SectGate",
            (YUN, "You looked peaceful, up there. Under that moon. I've never seen anyone look peaceful under a blood moon."),
            ),
          B("probe", "The Fold Breathes",
            "A crane from Ye Wuming at the rim: the fold is breathing. In and out. Every breath, the black gate comes a little closer.",
            (LU, "A crane from Ye Wuming! He says the fold's breathing! In and out! And every time it breathes, the gate gets closer!"),
            "@I:SectGate", ">Read Ye Wuming's crane",
            (N, "The gate drifts closer with every breath. The children can see it now, from the rim, like a ship through fog. Come soon. Ye."),
            "@T:SectGate",
            (YUN, "Weeks. Maybe less. Iron-Fang has asked for time to gather his men. Go and help him. He says they need washing."),
            prop="jade_slip", thing="Ye Wuming's crane"),
          B("interlude", "Washing Bandits",
            "Iron-Fang's crane is short: forty men, mostly clean, all hungry. Help. Also bring soap.",
            (WEI, "Iron-Fang needs soap? For forty bandits? I'm bringing soap. And dumplings. Bandits need dumplings. Everybody needs dumplings."),
            "|",
            (HAN, "Go. Help him. I'll stay and watch the moon. Somebody should watch it who isn't afraid of it. I've decided I'm not."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 92
    C("Forty Bandits, Washed and Fed", "bamboo_forest",
      "Iron-Fang has gathered forty of his old men for the march on the Abyss: farmers now, mostly, with families behind "
      "the black gate. They are loyal, brave, badly armed and extremely dirty. Before they can storm a fortress, they need "
      "a bath, a meal, and a reason to believe they'll come home.",
      cast=[TIE, WEI, LAN, YE, HAN, LIUER], foes=["bandit", "rogue_cultivator", "void_wraith"],
      items=["medicine", "spirit_stone", "spirit_herb"], props=["treasure_chest", "seal", "stone_stele"],
      foe_names={"bandit": "Iron-Fang's recruits", "void_wraith": "shadow-born"},
      beats=[
          B("orders", "The Old Camp, Full Again",
            "The old bandit camp is full again, for the first time since you burned it. This time, the bandits are waiting for you.",
            "@R:BanditCamp", (N, "The old bandit camp is full: forty men, rough and grey-bearded and very dirty, sitting around fires, polishing farm tools into weapons."),
            "@T:Clearing",
            (TIE, "Forty. My old men. Farmers now, mostly. All of them have someone behind that gate. All of them want to march."),
            (TIE, "They're also filthy. A bandit camp's no place to wash. Your hermit has a spring. I'm told springs are for washing."),
            ),
          B("gather", "Soap for Forty",
            "Wei Tong has brought soap. A lot of soap. The hermit's spring has never seen so many bandits at once.",
            (WEI, "Soap! For forty! And towels! And dumplings for after! I've planned this very carefully! Everyone into the spring!"),
            "@G:SpiritSpring", ">Hand out soap at the spirit spring",
            "@T:Clearing",
            (LAN, "Forty bandits. In my spring. With soap. The lotus is very confused. So am I. But they're very clean now. Cleaner than me."),
            item="spirit_herb", noun="bars of soap"),
          B("social", "Washed",
            "Forty bandits, washed. They look at each other, clean for the first time in years, and don't recognise anyone.",
            (TIE, "They don't recognise each other. Twenty years of dirt, gone. Old Bao's got a face under there. Who knew. He's very handsome."),
            "|",
            (N, "An old bandit touches his own clean face and laughs. Then cries. Then laughs again. The others do the same. It's contagious."),
            "|",
            (TIE, "Washed. Now fed. Then trained. Then we march. Iron-Fang's army. Clean for the first time in twenty years."),
            ),
          B("festival", "Fed",
            "Wei Tong feeds forty bandits. It takes all day. It's the happiest you've ever seen him.",
            (WEI, "Forty bandits! Forty appetites! This is the best day of my life! Dumplings! Noodles! More dumplings! Nobody leaves hungry!"),
            "@G:Clearing", ">Carry Wei Tong's dumplings to the fires",
            "@I:BanditCamp", ">Serve the first bowl to Iron-Fang",
            (N, "Iron-Fang takes the first bowl. He eats slowly. Around the fires, forty washed and fed men eat, and talk about their families, and laugh."),
            "@T:Clearing",
            (TIE, "Forty of them. Clean. Full. Laughing. I've never seen them like this. Neither have they. Thank you."),
            item="medicine", noun="dumplings", prop="treasure_chest", thing="the first bowl"),
          B("train", "Trained",
            "Washed and fed, Iron-Fang's men need training. With real weapons. They've only ever fought with farm tools and desperation.",
            (TIE, "They fight like farmers. Desperate farmers. Brave, stupid, messy. Teach them to fight like people who want to come home."),
            "@F:BanditCamp", ">Train Iron-Fang's recruits",
            (LIUER, "I came to help teach! With a broom! The broom is a very good teacher! Everyone in Qingshi agrees!"),
            "@T:Clearing",
            (TIE, "Better. They're still messy. But they fight like they want to come home. That's the most important stance there is."),
            foe="bandit", count=5),
          B("battle", "Shadows in the Camp",
            "The shadow-born come for Iron-Fang's camp at night. They want the bandits scared. The bandits are fed now. It's harder.",
            (TIE, "Shadows! At the camp! Forty clean men, form a line! With farm tools! With brooms! Liu Er, show them!"),
            "@F:BanditCamp",
            "@F2:ForestPath",
            "@T:Clearing",
            (TIE, "Held. My men held. First fight in years where nobody ran. They said they didn't want to get dirty again. Best reason I've heard."),
            foe="void_wraith", foe2="void_wraith"),
          B("social", "The Names Behind the Gate",
            "Around the fire, each of Iron-Fang's men says one name: the person waiting for them behind the black gate.",
            (N, "Around the fire, forty men, one name each. A wife. A son. A mother. A brother. Iron-Fang goes last."),
            (TIE, "Tie Mei. My sister. She's mid-shout, the heir says. Frozen, mid-shout. She was always shouting. I'd give anything to hear it."),
            "|",
            (YE, "My children listened to every name. They're going to find every cage. They promised. They keep promises. I taught them that."),
            ),
          B("probe", "The Old Map",
            "Iron-Fang has an old map, from when the Blood Moon used him: the fortress, the gate, and the guard changes.",
            (TIE, "The Blood Moon used me for twenty years. I learned things. When the guards change. Where the gate's weakest. Here."),
            "@I:BanditCamp", ">Study Iron-Fang's old fortress map",
            (N, "A map drawn in charcoal on leather: the black gate, the court, the cages. A note in Iron-Fang's hand: the gate opens only from inside. Or with a token."),
            "@T:Clearing",
            (TIE, "A token. Like the blood-red one I lost. The one your Elder Gu took. Wonder what happened to it. Probably melted. The Law Hall melts everything."),
            prop="jade_slip", thing="the fortress map"),
          B("cultivate", "Forty Men by the Fire",
            "The night before Iron-Fang's army leaves the forest, you sit by their fire and carry them. Forty. Plus the forty behind the gate.",
            "@M:Clearing", ">Carry Iron-Fang's army by the fire",
            (N, "Forty washed, fed men, snoring by the fire. Forty frozen people behind a gate, mid-word, mid-shout. You carry both. They weigh the same."),
            "@T:Clearing",
            (TIE, "You're carrying my men. I can tell. They're sleeping better than they have in years. Thank you, sect brat. Sect hero. Whatever."),
            ),
          B("interlude", "March to the Rim",
            "Iron-Fang's army marches out of the bamboo toward the Abyss rim, clean, fed, and singing a very bad bandit song.",
            (TIE, "We'll camp at the rim. Near the fold. Near our families. We'll wait for your sect. Don't be late. The moon won't wait."),
            "|",
            (WEI, "They're singing! A bandit song! It's about stealing a goose! It's terrible! I'm learning it!"),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 93
    C("A Traitor's Last Requests", "sect",
      "Gu Hanshan has been a prisoner for years, and for years he has helped: advice in chains, warnings at the rim, "
      "confessions nobody asked for. Now, with the moon turning red, he asks the Sect Master for three last requests. "
      "He won't say why they're last. Everyone knows.",
      cast=[GU, YUN, HAN, ZHAO, BAI, HUA, WEI, LAN], foes=["void_wraith", "demon_cultivator", "training_puppet"],
      items=["letter", "incense", "jade_slip"], props=["jade_slip", "seal", "stone_stele"],
      foe_names={"void_wraith": "shadow-born"},
      beats=[
          B("orders", "Three Requests",
            "The Sect Master summons you. Gu Hanshan has asked for three last requests, and asked that you escort him.",
            (YUN, "Gu has asked for three last requests. He asked that you escort him. He won't say why they're last. I think we both know."),
            (YUN, "Grant them. All three. Whatever they are. He's earned three."),
            "@T:MoonGate",
            (GU, "Three. The cliff where Mo's ashes lie. The Law Hall, once more. And my daughter's letters. I'd like to burn them."),
            (GU, "Then I'll be ready. For whatever the moon brings. Thank you for escorting me. I know you'd rather not."),
            ),
          B("probe", "The First Request",
            "The first request: the cliff edge, where Elder Mo's ashes were scattered. Gu Hanshan kneels.",
            "@R:CliffEdge", (N, "Gu Hanshan kneels at the cliff edge, chains clinking. The sea of clouds is red under the rusting moon."),
            "@I:CliffEdge", ">Kneel beside Gu at the cliff",
            (N, "Mo, he says. I altered your formation. You died fixing my mistake. I don't ask you to forgive me. I just wanted you to know I know."),
            "@T:MoonGate",
            (GU, "He'd have said something grumpy. Hmph. Adequate apology. More than adequate. I can hear him. I can hear him saying it."),
            prop="seal", thing="the cliff edge"),
          B("social", "Wei Tong at the Cliff",
            "Wei Tong has followed. He's been angry at Gu for years. He's not sure what he is now.",
            (WEI, "I followed you. I don't know why. I've been angry at him for years. For Elder Mo. I wanted to hit him."),
            (WEI, "He knelt. He apologised to Elder Mo. Elder Mo would have... Elder Mo would have said adequate. I'm not going to hit him."),
            (GU, "Thank you, Wei Tong. He was proud of you. He told me once, before. He said you'd be a better teacher than him."),
            (WEI, "...He told YOU? He told the paper and he told YOU? That old man. That stubborn, stubborn old man."),
            ),
          B("probe", "The Second Request",
            "The second request: the Law Hall, empty for years. Gu Hanshan sits in his old chair, once.",
            "@R:ScholarRock", (N, "The Law Hall is empty and dusty. Gu Hanshan sits in his old chair, very straight, and looks at the empty chairs where his disciples sat."),
            "@I:ScholarRock", ">Watch Gu sit in the Law Hall one last time",
            (N, "He takes a brush and writes one line on a fresh slip, and leaves it on the desk: fill this hall with someone kinder than me."),
            "@T:MoonGate",
            (GU, "The precepts are older than my grief. I wrote that once. Now I'll write this. Kinder. Someone kinder. That's all the law needs."),
            prop="jade_slip", thing="the Law Hall desk"),
          B("battle", "Shadows at the Law Hall",
            "The shadow-born come for Gu in the Law Hall. The Patriarch knows he's planning something.",
            (ZHAO, "Shadows! Coming for Gu! The Patriarch must know he's up to something! Protect the traitor! I never thought I'd say that!"),
            "@F:OuterPines",
            "@F2:FormationArray",
            "@T:MoonGate",
            (ZHAO, "The Zhao clan protected Gu Hanshan. My brother would laugh. Or cry. Both. The Zhao clan does both at once."),
            foe="void_wraith", foe2="demon_cultivator"),
          B("social", "Zhao Kang and Gu",
            "Zhao Kang asks Gu Hanshan one last question. It's not the one anyone expected.",
            (ZHAO, "I asked you once why you sent my brother. You told me. I've got a different question now. Did he suffer?"),
            (GU, "...No. It was quick. He was brave. He was protecting a caravan. He died between them and the bandits. Standing."),
            (ZHAO, "Standing. Good. That's... good. Thank you. That's all I needed. Go and finish your requests."),
            ),
          B("gather", "Letters to a Dead Girl",
            "The third request: twenty years of unsent letters to Gu Lan. He wants to burn them, the way you burned Luo Hui's.",
            (GU, "The letters. To Lan. Twenty years. You burned the First Rung's letters. You sent them, you said. Send mine."),
            "@G:ScholarRock", ">Gather Gu's letters to his daughter",
            "@I:CliffEdge", ">Burn the letters at the cliff edge",
            (N, "The letters burn. The ash rises over the sea of clouds and goes up, and up. Gu watches it until it's gone. He doesn't cry. He smiles."),
            "@T:MoonGate",
            (GU, "Delivered. Twenty years late. She had better manners than me. She'll read them anyway."),
            item="letter", noun="unsent letters", prop="seal", thing="the letters"),
          B("social", "The Sect Master and the Traitor",
            "At the end, the Sect Master comes to the moon gate. She and Gu Hanshan talk for the first time in years.",
            (YUN, "Forty years, Hanshan. I trusted you with our law and our children."),
            (GU, "And I broke both. Qingyao. I have a way through the black gate. When the moon rises, I'll use it. Don't stop me."),
            (YUN, "...I won't. Come back, if you can. That's not a request. It's what I say to everyone. I'm saying it to you too."),
            ),
          B("cultivate", "Sitting With the Traitor",
            "On the last night of his requests, Gu Hanshan asks you to sit with him at the moon gate. He doesn't want to be alone.",
            (GU, "Sit with me. Just sit. I've been alone for twenty years, even in company. Tonight I'd like not to be."),
            "@M:MoonGate", ">Sit with Gu Hanshan at the moon gate",
            (N, "You sit with the man who betrayed everything, under a red moon, in silence. It isn't forgiveness. It's company. It might be the same thing."),
            "@T:MoonGate",
            (GU, "Thank you. For the sitting. For everything. You'd have made a good Law Hall elder. You listen twice. Go and sleep."),
            ),
          B("interlude", "The Hermit's Blessing",
            "The hermit comes to the moon gate at dawn and blesses Gu Hanshan with the Heart Sutra. Gu weeps, at last.",
            (LAN, "Root, stem, blossom. Even for you, Gu Hanshan. Especially for you. Compassion doesn't choose who deserves it."),
            (GU, "...I'm crying. I haven't cried since Lan. Thank you, Verdant Lotus. Your sect was always kinder than ours."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 94
    C("Xue Chen's Hunt", "qingshi_town",
      "The last blood moon needs blood. Xue Chen, the Seventh Rung, comes to Qingshi for it with every shadow-born he has. "
      "He doesn't want to. He does it anyway. Qingshi, which has held against bandits, beasts, rust and silk, holds again.",
      cast=[DU, ZHOU, FANG, TIE, LIU, LIUER, PAN, JIN, HAN, YE], foes=["void_wraith", "blood_guard", "demon_cultivator"],
      items=["medicine", "spirit_stone", "void_shard"], props=["bronze_bell", "seal", "treasure_chest"],
      foe_names={"void_wraith": "shadow-born"},
      beats=[
          B("orders", "Shadows Over Qingshi",
            "A crane from Constable Du: shadows over Qingshi at dusk. Hundreds. And a young man in red, standing on the watchtower.",
            (HAN, "A crane from Constable Du. Hundreds of shadows over Qingshi. And a young man in red on the watchtower. Xue Chen."),
            "@R:qingshi_town/TownGate", (N, "Qingshi's gate is shut. The sky above the town is thick with drifting shadow-born, circling like crows over a field."),
            "@T:MainStreet",
            (DU, "Hundreds of them. Circling. Not attacking. Waiting. The boy on the tower's waiting too. He hasn't moved in an hour."),
            map="sect"),
          B("social", "The Town Knows What to Do",
            "Qingshi knows what to do. It's held before. Everyone takes their place without being asked.",
            (FANG, "Children in the cellar with the wine. Again. They've never touched the wine. Well. Once. That boy. He's a guard now."),
            "|",
            (TIE, "Iron-Fang's men came back from the rim to help. Clean ones. Fed ones. They know this town. They tried to burn it once. Now they'll hold it."),
            "|",
            (ZHOU, "I've written a speech. One word. You know the word. Everyone knows the word."),
            ),
          B("probe", "The Boy on the Tower",
            "Xue Chen stands on the watchtower, looking down at the town. He isn't giving orders. He's watching the children.",
            "@R:WatchTower", (N, "Xue Chen stands on the watchtower. Below him, children run to the inn cellar. He watches them. He looks like he's trying to remember something."),
            "@I:WatchTower", ">Look at Xue Chen with your soul",
            (N, "In soul sight, the thread from him to the fold is thick and red. And somewhere in it, very small, a boy from Willow Creek, pulling the other way."),
            "@T:MainStreet",
            (YE, "He's pulling against his own thread. Very weakly. But pulling. There's a door there. A small one. Let's knock."),
            prop="seal", thing="Xue Chen"),
          B("defend", "The Shadows Fall",
            "At full dark, the Patriarch pulls the thread, and every shadow-born over Qingshi falls on the town at once.",
            (DU, "They're coming down! All of them! Everyone to your places! Magistrate, the word! Say the word!"),
            "@I:WatchTower", ">Ring the town bell",
            (N, "The bell rings. The magistrate shouts one word from the yamen steps. Hold. Every door in Qingshi slams, and every hand picks up something."),
            "@F:MainStreet",
            "@F2:MarketSquare",
            "@T:MainStreet",
            (ZHOU, "Hold! I said hold! They held! We held! I'm going to say it again! Hold!"),
            foe="void_wraith", foe2="blood_guard", prop="bronze_bell", thing="the town bell"),
          B("battle", "The River Assault",
            "The shadows come up the river too, where Old Pan's ferry is still crossing with the last farmers.",
            (PAN, "Shadows on the water! My ferry's out there! Full of farmers! Forty years! I'm not losing a passenger now!"),
            "@F:Riverside",
            "@F2:Farmland",
            "@T:MainStreet",
            (PAN, "Every farmer across. Every one. I hit a shadow with an oar. It felt the same as the wolf. Wonderful. Every time."),
            foe="void_wraith", foe2="demon_cultivator"),
          B("social", "Xue Chen Watches",
            "Through the fighting, Xue Chen doesn't move from the tower. When the shadows falter, he speaks to you, from far away.",
            (RUNG7, "They're holding. A town of mortals, holding against the shadow of the Patriarch. With brooms. Why?"),
            (P, "Because they carry each other. Come down, cousin. Carry something with us."),
            (RUNG7, "...I can't. He's pulling. He's my father. He's the only thing I've ever had. I'm sorry. I'm so sorry."),
            ),
          B("hunt", "Blood for the Moon",
            "The shadows aren't trying to win. They're trying to spill blood, anywhere, for the moon. Some of it has already soaked the graves.",
            "@R:Graveyard", (N, "On the hill graves, shadow-born are drawing a circle in blood, the old way, Hong's way. They've nearly finished."),
            "@F:Graveyard",
            "@G:Graveyard", ">Gather the blood-soaked earth before the moon drinks it",
            "@T:MainStreet",
            (LIUER, "The circle's broken! I broke it with the broom! The broom is a hero! Everybody's going to hear about the broom!"),
            foe="void_wraith", item="void_shard", noun="blood-soaked earth"),
          B("defend", "The Last Wave at the Gate",
            "The last wave of shadows hits the town gate. Constable Du holds it with his ugly new spear.",
            (DU, "Last wave! At the gate! My spear's ugly! It's the best spear in the world! Everyone with a spear, with me! For Qingshi!"),
            "@I:TownGate", ">Ward the town gate",
            (N, "Your ward rises over the gate. Constable Du's ugly spear catches the light. Behind him, forty clean bandits and a town full of brooms."),
            "@F:TownGate",
            "@F2:MainStreet",
            "@T:MainStreet",
            (DU, "Held. Qingshi held. Again. I'm going to write it down. In the good ink. Then I'm going to sleep for a week."),
            foe="blood_guard", foe2="void_wraith", prop="seal", thing="the town gate"),
          B("probe", "The Empty Tower",
            "When the last shadow falls, the watchtower is empty. Xue Chen is gone. He left something on the rail.",
            "@R:WatchTower", (N, "The watchtower is empty. On the rail, a small carved horse, very old, the kind a child might carry from a village by a creek."),
            "@I:WatchTower", ">Pick up the carved horse",
            (N, "Carved on its belly, in a child's scratches: Chen. Willow Creek. He left it for you. Or for himself. Or both."),
            "@T:MainStreet",
            (YE, "He left the only thing he brought from home. That's not a threat. That's a boy asking someone to hold his toy while he does something terrible."),
            prop="treasure_chest", thing="the carved horse"),
          B("interlude", "Qingshi Holds, Again",
            "Dawn over Qingshi. The town is scarred, tired and whole. Madam Fang opens the cellar. The children still haven't touched the wine.",
            (FANG, "The children didn't touch the wine. Not one sip. I'm so proud. I'm going to give them some. Just a thimble. For bravery."),
            "|",
            (LIU, "Heaven keeps its accounts. So do I. Qingshi owes you everything. We're square. You owe us nothing. Come back anyway."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 95
    C("The Shadow at the Stair", "sky_isles",
      "Qing Luan's crane is frantic: Xue Chen is on the tribulation peak, setting his rung early, while the moon is not "
      "yet fully red. If the seventh rung is set before the night, the Patriarch's ladder will hold. You climb the cloud "
      "stair one last time before the last time.",
      cast=[SAGE, HAN, ZHAO, YE, YUN], foes=["void_wraith", "celestial_sentinel", "thunder_wolf"],
      items=["thunder_crystal", "tribulation_jade", "cloud_silk"], props=["seal", "stone_stele", "spirit_stone"],
      foe_names={"void_wraith": "shadow-born", "thunder_wolf": "storm wolves"},
      things={"stone_stele": "the star chart"},
      beats=[
          B("orders", "Setting the Rung Early",
            "Qing Luan's crane arrives on fire: Xue Chen is on the peak, setting his rung, a week early. Come now.",
            (YUN, "Her crane was on fire. Xue Chen, on the peak, setting his rung early. Go. Han Xue and Zhao Kang are already at the stair."),
            "@R:sky_isles/CloudGate", (N, "The isles are dark. The moon is nearly red. On the tribulation peak, a thread of red light rises into the sky like smoke from a fire."),
            "@T:CloudGate",
            (SAGE, "He's on my peak. Setting his rung. Tying the ladder to the sky. If he finishes, the Patriarch has seven steps to climb your lightning."),
            (SAGE, "Break it. Before the moon. Before he finishes. Go. I'll shout. I'm shouting now. GO."),
            map="sect"),
          B("battle", "Shadows on the Bridge",
            "The shadow-born hold the jade bridge, the way to the peak. Han Xue says she'll hold it for you. Not yet. Soon.",
            (HAN, "Shadows on the bridge. I'll hold it. Not tonight, the real night. Tonight we just go through. Together."),
            "@F:JadeBridge",
            "@F2:IsleOfWinds",
            "@T:CloudGate",
            (HAN, "Through. The bridge is ours. On the night, I'll stand right here. Nothing crosses. I've decided. It's my bridge now."),
            foe="void_wraith", foe2="void_wraith"),
          B("hunt", "The Delta Holds",
            "The forty crystals you planted on the peak's lower slopes are holding off Xue Chen's thread. The shadows are trying to smash them.",
            "@R:CelestialRuins", (N, "On the lower slopes, your forty crystals glow, bending the red thread away from the summit. Shadows claw at them."),
            "@F:CelestialRuins",
            "@G:CelestialRuins", ">Plant fresh crystals to strengthen the delta",
            "@T:CloudGate",
            (ZHAO, "The delta's holding. Your founder's plan. Bai's ceiling. Thunder Peak's anvils. All holding. Now go up there and talk to your cousin."),
            foe="void_wraith", item="thunder_crystal", noun="fresh crystals"),
          B("probe", "The Rung on the Peak",
            "On the summit, Xue Chen kneels in the black rings, weaving a thread of red into the sky. He's crying.",
            "@R:IsleOfWinds", (N, "On the summit, in the black rings of old tribulations, Xue Chen kneels, weaving a red thread into the sky. His face is wet."),
            "@I:StarPavilion", ">Watch the rung through the star chart",
            (N, "The seventh star flickers. Bright, dim, bright. He's setting it. And un-setting it. Over and over. He can't decide."),
            "@T:CloudGate",
            (YE, "He can't decide. He's setting it and pulling it out. He's been doing it for hours, the star-gazer says. He's breaking himself."),
            prop="stone_stele", thing="the star chart"),
          B("social", "Talking to the Shadow",
            "You call across the gap to Xue Chen. He hears you. He doesn't stop weaving, but he answers.",
            (P, "Cousin! Xue Chen! You left me your horse. I've got it. I'll keep it safe. Come down and take it back."),
            (RUNG7, "Keep it. I can't come down. If I stop, he'll pull me. If I finish, he'll climb you. Every choice is someone falling."),
            (RUNG7, "I'm going to the mirror. The Heart Mirror. Where I can see myself before. Come find me there. When the moon's almost red."),
            ),
          B("battle", "Storm Wolves on the Peak",
            "When Xue Chen steps into a rift, his thread snaps, and the whole peak crackles. The storm wolves go wild.",
            (ZHAO, "He's gone! The thread snapped! The peak's crackling! The storm wolves are going mad! Of course they are!"),
            "@F:SpiritVein",
            "@F2:JadeBridge",
            "@T:CloudGate",
            (SAGE, "The seventh star is still lit. But it's not tied to the peak any more. He left it loose. On purpose, I think. He's giving you a chance."),
            foe="thunder_wolf", foe2="celestial_sentinel"),
          B("cultivate", "Standing on the Black Rings",
            "Qing Luan asks you to stand on the summit's black rings, where your tribulation will fall, and let the peak learn you.",
            (SAGE, "Stand on the rings. Where you'll stand on the night. Let the peak learn your weight. It should know who it's holding up."),
            "@M:CloudGate", ">Let the tribulation peak learn you",
            (N, "The black rings hum under your feet: ten thousand years of cultivators who stood here and were answered. They're curious about you."),
            (N, "Peak of Tribulation Transcendence. Nothing left but the sky."),
            "@T:CloudGate",
            (SAGE, "Peak. You're ready. The sky's ready. The moon's nearly ready. Only the Shadow isn't. Go to the mirror. Go and find your cousin."),
            ),
          B("gather", "Warm Jade for Qing Luan",
            "Before you go, you give Qing Luan a piece of tribulation jade. She has never been given anything.",
            (SAGE, "For me? Jade? Warm forever? I'm a memory. Memories don't get gifts. Nobody's given me anything in ten thousand years."),
            "@G:IsleOfWinds", ">Gather silk to wrap Qing Luan's jade",
            "@T:CloudGate",
            (SAGE, "Wrapped in silk from my own pines. It's warm. I can feel it. Memories can't feel warmth. I can. You broke a rule of the universe."),
            item="cloud_silk", noun="wrapping silk"),
          B("social", "See You on the Night",
            "At the cloud gate, Qing Luan says goodbye, of a sort. She says she'll see you on the night. She'll be the one shouting.",
            (SAGE, "On the night, I'll be here. At the gate. When his soul crosses my bridge, I'll see it. I'll shout. Loudly. Finally."),
            (SAGE, "Ten thousand years I watched and said nothing. This time I'll shout so loudly the Patriarch will hear it in the lightning."),
            "|",
            (HAN, "And I'll be on the bridge. Nothing crosses. See you on the night, star-gazer. Frown at me fondly."),
            (SAGE, "Always, sword girl. Always."),
            ),
          B("interlude", "Down to the Mirror",
            "Ye Wuming reads the snapped thread. Xue Chen has gone to the Heart Mirror, at the bottom of the world, to wait for you.",
            (YE, "The mirror. He's at the mirror. Looking at himself before. Waiting for you. Or for courage. Maybe both."),
            (YE, "The fold's opening. The gate's nearly back. When you go to the mirror, the whole Abyss will be waking. Be quick. Be kind. If you can."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 96
    C("The Last Evening", "sect",
      "One evening left before the moon turns fully red. The Sect Master declares a holiday. There will be no training, "
      "no preparations, no war. Only dumplings, lanterns, and everyone you love, all together on one mountain, for one "
      "last ordinary night.",
      cast=[YUN, WEI, HAN, ZHAO, MAN, SHI, HUA, BAI, LAN, LU, QIAN, YAN, LIUER], foes=["training_puppet", "void_wraith", "demon_cultivator"],
      items=["lantern_oil", "medicine", "tribulation_jade"], props=["seal", "stone_stele", "bronze_bell"],
      foe_names={"void_wraith": "shadow-born"},
      beats=[
          B("orders", "A Holiday",
            "The Sect Master stands on the plaza and declares one last holiday. No training. No war. Only an evening.",
            (YUN, "One evening. No training. No preparations. No war. Tomorrow the moon turns red. Tonight, we're a sect. Just a sect. Go."),
            "@R:FormationArray", (N, "Lanterns everywhere. On the pillars, the eaves, the trees. The formation glows blue beneath them. Somebody is already singing, badly."),
            "@T:WeaponRack",
            (WEI, "One evening. I've been cooking for three days. Dumplings. Every kind. Every kind that exists. Some that don't. Come and eat."),
            ),
          B("festival", "Dumplings for Everyone",
            "Wei Tong's dumplings, for the whole mountain. Every kind. The twelve serve. The chicken supervises.",
            (WEI, "Dumplings! Pork! Cabbage! Lotus root! Peach! Peach dumplings are new! Elder Mo's peaches! In dumplings! He'd hate it!"),
            "@G:TrainingGround", ">Carry Wei Tong's dumplings around the plaza",
            "@I:HallSteps", ">Leave a peach dumpling on the hall steps",
            (N, "A peach dumpling on the hall steps, beside the morning's cold tea, where Elder Mo stood. Everybody who passes bows to it."),
            "@T:WeaponRack",
            (WEI, "He'd hate the peach dumpling. He'd eat three. I'm leaving him three."),
            item="medicine", noun="dumplings", prop="seal", thing="the hall steps"),
          B("social", "Everyone Talks",
            "The whole mountain wants to talk to you tonight. Everyone has something to say. Nobody says goodbye.",
            (MAN, "I made you a pill. It's probably a pill. It's for luck. Or indigestion. Take it anyway. I only dropped it once."),
            "|",
            (SHI, "My sister's crying. I'm crying. We're both very happy. It's a strange night. Thank you. I'll keep saying it."),
            "|",
            (BAI, "I've finished copying Elder Mo's manual. Every 'no'. I've added one at the end. In my hand. It says: adequate."),
            ),
          B("gather", "Lanterns on the Cliff",
            "Lu Ping has organised a lantern release from the cliff edge, like the examination, years ago. Everyone writes a wish.",
            (LU, "Lanterns! From the cliff! Like the examination! Everyone writes a wish! I've written mine already! It says 'win the betting book'!"),
            "@G:FormationArray", ">Gather lanterns for the whole sect",
            "@I:CliffEdge", ">Release your lantern over the sea of clouds",
            (N, "A thousand lanterns over the sea of clouds. Yours says the same as it did years ago: to be strong enough to protect people."),
            (N, "Beside it, Zhao Kang's lantern. It says: to beat you. And underneath, smaller: when you come back down."),
            "@T:SectGate",
            (ZHAO, "Don't read other people's lanterns. It's still the worst manners in the sect. What did yours say? No. I know what it said."),
            item="lantern_oil", noun="paper lanterns", prop="seal", thing="the cliff edge"),
          B("social", "The Hermit's Song",
            "The hermit sings the Heart Sutra on the plaza, all three verses, and three hundred disciples who learned it in the ruins sing with him.",
            (LAN, "Root, stem, blossom. Everyone who learned it in my masters' courtyard. Sing it with me. Loudly. The whole mountain."),
            "|",
            (N, "Three hundred voices, then a thousand, then the whole mountain. The green lotus in the pond opens as wide as it can. The carp bow."),
            "|",
            (LAN, "My masters sang this while the water rose. I ran. Tonight the whole Azure Cloud sings it. They hear. I know they hear."),
            ),
          B("defend", "Uninvited to the Last Evening",
            "The shadows come on the last evening, as they always do. The sect doesn't stop singing while it fights them.",
            (YAN, "Shadows on the back path! Thunder Peak's got it! We're shouting the sutra at them! It's working! It's very loud!"),
            "@I:CliffEdge", ">Ring the cliff bell over the singing",
            (N, "The bell rings. Nobody stops singing. Thunder Peak shouts the sutra. The twelve sing it. The shadows, confused, retreat from a mountain that won't be afraid."),
            "@F:OuterPines",
            "@F2:SectGate",
            "@T:SectGate",
            (YAN, "They ran from singing! Thunder Peak has never won a fight by singing! We're adding it to the forge! Next to your name!"),
            foe="void_wraith", foe2="demon_cultivator", prop="bronze_bell", thing="the cliff bell"),
          B("social", "Han Xue on the Bridge",
            "Han Xue finds you on the stone bridge. She wants to say something. She says it very stiffly.",
            (HAN, "Tomorrow the moon. Then the gate. Then the sky. I'll hold the bridge on the isles. Nothing crosses. I promised."),
            (HAN, "And the sparring match. You still owe me. I'm going to keep saying it until you pay, so you have to come back."),
            (P, "After, Senior Sister."),
            (HAN, "After. Good. That's all. Don't make it weird. ...Thank you. For the plum garden. Both times. That's all."),
            ),
          B("cultivate", "The Main Hall, Quiet",
            "Late at night you use the key the Sect Master gave you: the main hall, quiet, with the founder's tablet and the faded green lotus.",
            "@M:StoneBridge", ">Sit in stillness beneath the lanterns",
            (N, "Silence, lanterns and the pond. You carry the whole mountain one last time as a disciple. Tomorrow you carry it as something else."),
            "@T:MainHall",
            (YUN, "You found the quiet. Good. I came to find it too. Let's share it. Say nothing. That's what it's for."),
            ),
          B("social", "Steward Qian's Account",
            "At midnight, Steward Qian finds you with the empty account he opened in your name years ago. He wants to close it.",
            (QIAN, "Your account. Opened before the descent. I said I don't open accounts for people who don't come back. It's still empty."),
            (QIAN, "I'm not closing it. I'm keeping it open. Forever. You'll fill it. When you come back down. I don't make bad investments."),
            ),
          B("interlude", "Dawn, and the Moon",
            "At dawn the whole sect is still awake. The moon sets. When it rises tonight, it will be red. Tomorrow, the Abyss.",
            (YUN, "Tonight it rises red. We go to the rim at dusk. Every sect meets us there. First, Ye Wuming asked for you. At the mirror. Go."),
            "|",
            (WEI, "Go. Find your cousin. Be kind. Come back for breakfast. I'm making more dumplings. I'm always making more dumplings."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 97
    C("The Void Unfolds", "blood_abyss",
      "The fold is opening. As the moon climbs toward red, the black fortress drifts back out of the void and settles, "
      "groaning, onto the Abyss floor where it stood before, gate shut, cages full, prisoners still mid-breath. Iron-Fang's "
      "army waits at the rim. Ye Wuming waits at the obelisks. And at the bottom of the world, a boy waits at a mirror.",
      cast=[YE, TIE, GU, HAN, ZHAO, SHI, RUAN], foes=["void_wraith", "blood_guard", "demon_cultivator"],
      items=["void_shard", "demon_core", "medicine"], props=["seal", "demon_obelisk", "treasure_chest"],
      foe_names={"void_wraith": "shadow-born"},
      beats=[
          B("orders", "The Fortress Returns",
            "At the rim, the fold is opening like a hand unclenching. Out of it, slowly, the black fortress drifts back into the world.",
            "@R:blood_abyss/CanyonEntrance", (N, "Below the rim, the fold unclenches. The black fortress drifts out of nothing and settles onto the Abyss floor with a sound like a mountain sighing."),
            "@T:CanyonEntrance",
            (YE, "It's back. The gate. The court. The cages. Exactly where it was. As if it never left. As if nobody waited years for it."),
            (TIE, "The cages. My sister. She's there. Frozen, mid-shout. I can see the cage from here. Iron-Fang is very calm. Iron-Fang is not calm."),
            map="sect"),
          B("battle", "The Fortress Wakes",
            "With the fortress back, its guards wake. They've been frozen too. They don't know how long.",
            (RUAN, "Blood Guards! Out of the fortress! They don't know how long they've been gone! They look confused! Confused is good!"),
            "@F:BoneField",
            "@F2:DemonCamp",
            "@T:CanyonEntrance",
            (RUAN, "The Iron Scale's vanguard is here. Three thousand more at the teleport array. Remembering Hill came to the Abyss. We remember."),
            foe="blood_guard", foe2="demon_cultivator"),
          B("probe", "The Gate, Shut",
            "The black gate stands shut, carved with a moon swallowing a sword. It only opens from inside, or with a token.",
            "@R:ObeliskRing", (N, "Beyond the obelisk ring, the black gate stands shut. Taller than the main hall. Silent. Carved with a moon swallowing a sword."),
            "@I:ObeliskRing", ">Look at the gate with your soul",
            (N, "The gate is sealed from inside. Nothing will open it from here. Not qi, not soul, not forty sects. Only someone the gate thinks is its own."),
            "@T:CanyonEntrance",
            (GU, "It opens from inside. I know. I have a way. Tomorrow, under the moon, I'll use it. Don't ask what. You'll see."),
            prop="demon_obelisk", thing="the black gate"),
          B("social", "Ye Wuming's Children Take Their Places",
            "Ye Wuming's children, grown now, take their places at the obelisk ring. They've been waiting for this their whole lives.",
            (YE, "Spring. River. Small Mountain. All of them. Grown. They'll hold the obelisk ring tomorrow. They know every path. They were born to them."),
            "|",
            (N, "Spring bows to you. River hums the Moon-Well song. Small Mountain, very tall now, says nothing, and salutes."),
            "|",
            (YE, "My name. It's very close. Tomorrow, maybe. When he falls. I think I'll remember it when he falls. I'll tell you."),
            ),
          B("hunt", "Shadows at the Mirror Path",
            "The path down to the Heart Mirror is thick with shadow-born, guarding the way to their master's son.",
            "@R:BloodPools", (N, "The path past the blood pools to the depths is crowded with shadow-born, standing very still, like mourners at a gate."),
            "@F:BloodPools",
            "@G:BloodPools", ">Gather void shards from the guarding shadows",
            "@T:CanyonEntrance",
            (SHI, "I know the path. I drew it. I'll lead you as far as the depths. Then you go alone. That's what he asked for. Alone."),
            foe="void_wraith", item="void_shard", noun="void shards"),
          B("social", "Iron-Fang at the Rim",
            "Iron-Fang stands at the rim looking at his sister's cage. His forty men stand behind him, washed and fed, silent.",
            (TIE, "Tomorrow. The gate opens tomorrow. Then the cages. Then my sister shouts at me for twenty years of being late."),
            (TIE, "Go and find your cousin, sect brat. Be kind to him. He's someone's sister's son too. Everyone is."),
            ),
          B("battle", "The Depths",
            "At the bottom of the Abyss, the last shadows gather in the depths, around the path to the mirror.",
            (HAN, "I came down. Obviously. I'll hold the depths while you go to the mirror. Go. Alone. That's what he wanted."),
            "@F:AbyssDepths",
            "@F2:BoneField",
            "@T:CanyonEntrance",
            (HAN, "The depths are clear. The mirror's waiting. He's waiting. Go and be kind. Or go and win. Whichever you have to."),
            foe="void_wraith", foe2="blood_guard"),
          B("cultivate", "Before the Mirror",
            "At the edge of the depths, before you go to the mirror, you sit and remember Willow Creek. You want to bring it with you.",
            "@M:AbyssDepths", ">Remember Willow Creek before the mirror",
            (N, "A creek, a willow, a woman singing. A cousin you never met, three years old, laughing. A carved horse in your hand."),
            "@T:CanyonEntrance",
            (YE, "You're taking the village with you. Good. Show it to him. Show him what the mirror shows him. Maybe it'll be enough."),
            ),
          B("gather", "Medicine at the Rim",
            "While you prepare, the Moon-Well's healers arrive at the rim with Xiao Man's medicine bundles. Eight thousand notes saying 'come home'.",
            (SHI, "My sister's bundles. Eight thousand. Every one says come home. Or eat this, idiot. Take one. For the mirror."),
            "@G:CanyonEntrance", ">Take a medicine bundle for the mirror",
            "@T:CanyonEntrance",
            (SHI, "The note in yours says: come home, cousin-finder. She knew. My sister always knows. She drops things. She knows things."),
            item="medicine", noun="medicine bundles"),
          B("interlude", "Alone to the Mirror",
            "Ye Wuming walks you to the last turn of the path. Then he stops. The rest you walk alone.",
            (YE, "This is as far as I go. He asked for you alone. Be kind to him. He's what I would have been, if nobody had stolen me back."),
            (YE, "And if you can't steal him back... end it quickly. For him. Not for the ladder. For him."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 98
    C("The Patriarch's Shadow", "blood_abyss",
      "At the Heart Mirror, at the bottom of the world, Xue Chen sits looking at a boy in a village by a creek. He is the "
      "Seventh Rung, the last step of the Patriarch's Ladder, the Patriarch's own shadow. He is also your cousin, and he "
      "has asked you to come alone.",
      cast=[YE, HAN, GU, TIE, SHI], foes=["void_wraith", "blood_guard", "demon_cultivator"],
      items=["void_shard", "demon_core", "blood_lotus"], props=["seal", "treasure_chest", "demon_obelisk"],
      boss=("rung_deacon", "Xue Chen, the Patriarch's Shadow", "HeartMirror"),
      foe_names={"void_wraith": "shadow-born"},
      beats=[
          B("orders", "The Boy at the Mirror",
            "Xue Chen sits cross-legged at the edge of the Heart Mirror, looking into it. In it, a boy of three is laughing by a creek.",
            "@R:HeartMirror", (N, "Xue Chen sits at the mirror's edge. In the black water, a boy of three holds his mother's hand by a creek, laughing, over and over."),
            "@T:HeartMirror",
            (RUNG7, "You came alone. Thank you. Sit. Look. That's me. Before. I come here every day. It's the only place I'm not his."),
            ),
          B("social", "Two Cousins",
            "You sit beside him and look into the mirror together. It shows you both: two children from the same village.",
            (P, "Willow Creek. I was born there too. My mother sang by the creek. Your mother might have heard her."),
            (RUNG7, "...The mirror's showing both of us now. Two children. Same creek. One taken at three. One not. Why you and not me?"),
            (P, "I don't know. Luck. A mother who ran. Nothing I earned. Come with me, Chen. Leave his shadow. There's still time."),
            ),
          B("probe", "The Thread",
            "In soul sight, the thread from Xue Chen to the fold is so thick it's a chain. And it's pulling.",
            "@R:HeartMirror", (N, "A red chain runs from Xue Chen's back into the dark, toward the fortress. It tightens as you speak. Something at the other end has noticed."),
            "@I:HeartMirror", ">Touch the red chain with your soul",
            (N, "At the other end of the chain, on a throne of fused bone, something that was once a man opens one eye. Mine, it says. My shadow. Mine."),
            "@T:HeartMirror",
            (RUNG7, "He felt you touch it. He's pulling. He's going to make me fight you. I'm sorry. I'm so sorry. I tried. Keep the horse."),
            prop="seal", thing="the red chain"),
          B("battle", "Shadows of the Shadow",
            "The Patriarch pulls, and Xue Chen's own shadow-born pour out of the mirror's dark edges.",
            (N, "Shadow-born pour out of the mirror's edges, faceless, silent. Xue Chen screams at them to stop. They don't. They never listened to him."),
            "@F:HeartMirror",
            "@F2:AbyssDepths",
            "@T:HeartMirror",
            (HAN, "I said I'd hold the depths. I'm holding them. Ye Wuming's here. Iron-Fang's here. You're not alone. You never were. Finish it."),
            foe="void_wraith", foe2="blood_guard"),
          B("social", "Ye Wuming Tries",
            "Ye Wuming comes to the mirror after all. He can't stay away. He tries to steal Xue Chen back.",
            (YE, "Chen. I was you. Forty years ago. A shadow's child. Someone stole me back. Let me steal you. Let go of the chain."),
            (RUNG7, "I can't. It's not a chain. It's him. He's inside it. If I let go, I let go of... everything I've ever been."),
            (YE, "Then let go of that. Be something new. I did. It hurts. It's worth it. Please."),
            "|",
            (RUNG7, "...I'm trying. I'm trying. He won't let me."),
            ),
          B("boss", "The Seventh Rung Breaks",
            "The Patriarch pulls the chain with all his strength, and Xue Chen rises, eyes red, sword drawn, weeping. The last Rung fights.",
            "@R:HeartMirror", (N, "Xue Chen rises. His eyes are red now, all the way through. His sword is drawn. His face is wet. His voice is someone else's."),
            "@X",
            (RUNG7, "I was born in his shadow. I will die in yours. Forgive me, cousin. The moon is almost full."),
            (P, "I forgive you, Chen. Now let's break his chain together."),
            "@I:HeartMirror", ">Break the red chain as Xue Chen falls",
            (N, "The chain snaps. The red drains from Xue Chen's eyes. He falls into your arms, light as a child. Willow Creek, he says. I remembered."),
            (N, "His star goes out. The Patriarch's Ladder has no rungs left. Far away, on a throne of bone, something howls."),
            "@T:AbyssDepths",
            (YE, "He died free. In your arms, not his. That's stealing him back. The only way that was left. I'm going to cry now. Let me."),
            prop="seal", thing="the red chain"),
          B("social", "Seven Stars Out",
            "Qing Luan's crane finds you at the bottom of the world. It's shouting, and crying, and shouting again.",
            (N, "A crane of cloud, burning at the edges, shouts in Qing Luan's voice: seven stars out. Seven. The ladder's gone. He'll have to jump."),
            "|",
            (GU, "No ladder. His power has no root now. Only what he carries in himself. Tomorrow, under the moon, he'll be weaker than he's been in three hundred years."),
            (GU, "And more desperate. Desperate is dangerous. I know. I was desperate once."),
            ),
          B("gather", "Lotus for a Cousin",
            "Where Xue Chen fell, blood lotus grows, pink and pale. You gather it to bury with him.",
            (SHI, "Pink lotus. Where he fell. Like where Tan was freed, at the pools. Your village grows wherever you go now."),
            "@G:HeartMirror", ">Gather the pink lotus where he fell",
            "@T:AbyssDepths",
            (TIE, "We'll bury him at the rim. Next to my men's names. He was Willow Creek. My men burned Willow Creek. I'll carry that. Iron-Fang carries two."),
            item="blood_lotus", noun="pink lotus"),
          B("cultivate", "Burying a Cousin",
            "At the rim, under a moon that is almost red, you bury Xue Chen with his carved horse and a handful of pink lotus.",
            "@M:CanyonEntrance", ">Bury Xue Chen at the rim",
            (N, "A small grave at the rim, next to Iron-Fang's eleven carved names. A carved horse. Pink lotus. Chen, of Willow Creek. Free."),
            "@T:CanyonEntrance",
            (HAN, "Tomorrow the moon. Tonight, rest. Everyone's coming. The whole sect. Forty sects. We march at dusk. Go home. Sleep. Eat something."),
            ),
          B("interlude", "Home for the Night",
            "You go home for one night. The moon is almost full, almost red. Tomorrow at dusk, the Azure Cloud marches.",
            (YE, "I'll stay at the rim. With the children. And him. Tomorrow at dusk. We'll be at the obelisks. My name's very close now."),
            "|",
            (GU, "I'll come back up with you. In chains. The Sect Master will want me at the gate tomorrow. I have a way. You'll see."),
            ),
      ]),
    # ------------------------------------------------------------------ chapter 99
    C("Eve of the Last Blood Moon", "sect",
      "The last day. Forty sects' armies climb the nine thousand steps and gather at the teleport array. The Sect Master "
      "makes her plans. Everyone you love says see you later. At dusk the moon will rise red, the black gate will be "
      "waiting, and the Azure Cloud will march into the Abyss to finish what its founders began.",
      cast=[YUN, HAN, WEI, ZHAO, GU, TIE, MAN, SHI, HUA, BAI, LAN, QIAN, LU, YAN, LIUER, RUAN, JING], foes=["void_wraith", "training_puppet", "demon_cultivator"],
      items=["medicine", "spirit_stone", "tribulation_jade"], props=["teleport_array", "seal", "stone_stele"],
      foe_names={"void_wraith": "shadow-born"},
      beats=[
          B("orders", "Forty Sects on the Steps",
            "From dawn, the nine thousand steps are full: Iron Scale green, Zhao gold, Moon-Well white, and forty more colours, climbing.",
            (LU, "Forty sects! On the steps! All at once! It's the longest line in history! I'm counting! I've lost count! I'm starting again!"),
            "@R:SectGate", (N, "The processional way is a river of banners. Eleven thousand fighters, climbing. At the gate, they bow to the two steles: the precepts, and the oath."),
            "@T:SectGate",
            (RUAN, "The Iron Scale. Three thousand. My father's leading. He brought his crooked bow. He's very proud of it."),
            (JING, "The Moon-Well. Five hundred healers. We're singing on the steps. Lian's leading. We're here."),
            ),
          B("probe", "The Battle Plan",
            "The Sect Master spreads Xiao Shi's map of the Abyss on the plaza and makes her plan in front of forty sect masters.",
            (YUN, "The war camp, the obelisk ring, the black gate. Every sect has a place. I'll give the plan at the rim, where they can all hear it."),
            "@I:FormationArray", ">Study Xiao Shi's map with the Sect Master",
            (N, "The map shows every path, every door, every cage. At the black gate, the Sect Master has drawn a single character: Gu."),
            "@T:SectGate",
            (YUN, "You go through the gate, to the throne. I'll be behind you. I'll give the full plan at the rim. Now go and say see you later."),
            prop="jade_slip", thing="Xiao Shi's map"),
          B("social", "Not Goodbye",
            "Everyone says see you later. Nobody says goodbye. It's the rule now.",
            (MAN, "See you later. I've made you a bundle. It says come home, idiot. In big letters. I didn't drop it. Not once."),
            "|",
            (HUA, "See you later. Hold out your wrist. Hm. Stubborn pulse. Good. Come back and let me take it again."),
            "|",
            (BAI, "See you later. I've written the whole saga down. Every chapter. I'm saving the last page. You'll write it."),
            ),
          B("social", "The Hermit Stays",
            "The hermit won't march. He's too old, he says. He'll stay and teach the children who are too young to go.",
            (LAN, "I won't march. I'm too old, and someone has to sing to the ones who stay. I'll be in the pagoda. With Qiu Hua. And the chicken."),
            (LAN, "Root, stem, blossom. You've grown all three. Go and finish what my masters started. And come back. The tea will be steeping."),
            ),
          B("gather", "The Treasury Opens",
            "Steward Qian opens the treasury for the march. All of it. He doesn't count what leaves. He counts who does.",
            (QIAN, "The treasury is open. All of it. I'm not counting stones tonight. I'm counting people. I'm going to count every one of you back in."),
            "@G:IncenseBurner", ">Carry the treasury's supplies to the array",
            "@T:SectGate",
            (QIAN, "Everything's at the array. Every stone. Every pill. I've never been so poor. I've never been so proud."),
            item="spirit_stone", noun="treasury supplies"),
          B("battle", "The Last Shadows",
            "The Patriarch sends everything he has left at the gathering army. It's not much, now. It's still something.",
            (YAN, "Shadows! The last ones! Thunder Peak's got the gate! We're shouting the sutra! Everyone's shouting the sutra!"),
            "@F:OuterPines",
            "@F2:SectGate",
            "@T:SectGate",
            (YAN, "The last shadows! Gone! Forty sects shouting the sutra at once! You could hear it from the isles! The star-gazer probably did!"),
            foe="void_wraith", foe2="demon_cultivator"),
          B("social", "Iron-Fang and Gu",
            "Iron-Fang and Gu Hanshan meet at the teleport array. The bandit and the traitor. Both waiting to pay a debt.",
            (TIE, "Traitor. You took my token, years ago. The blood-red one. From my strongbox. What did you do with it?"),
            (GU, "I kept it, Iron-Fang. You'll see. Tomorrow. Your sister will see too. I promise."),
            (TIE, "...A traitor's promise. I've heard worse. I've made worse. Fine. See you at the gate, traitor."),
            ),
          B("cultivate", "The Last Stillness",
            "An hour before dusk, you sit on the teleport array and carry everyone: forty sects, eleven thousand, a town, a mountain.",
            "@M:FormationArray", ">Carry the whole army in stillness",
            (N, "Eleven thousand breaths. Forty sects. A town with brooms. A mountain with lanterns. A chicken. You carry them all, and they carry you."),
            (N, "The sun touches the sea of clouds. Far to the west, the moon begins to rise. It is exactly the colour of the Patriarch's robes."),
            "@T:SectGate",
            (WEI, "The moon. It's red. Properly red. I'm not afraid. I'm terrified. It's fine. Terrified is fine. Elder Mo was always terrified. He said so once."),
            ),
          B("probe", "The Array Wakes",
            "At dusk the teleport array wakes, every rune blazing, the route to the Abyss rim open. The Azure Cloud goes to war.",
            "@R:TeleportArray", (N, "The teleport array blazes. Eleven thousand fighters wait in rows. The Sect Master stands at the front, crown on, sword drawn."),
            "@I:TeleportArray", ">Light the teleport array for the march",
            (N, "The runes catch. The air smells of rain. One by one, the sects step onto the array, and vanish, toward the Abyss and the red moon."),
            "@T:SectGate",
            (ZHAO, "Remember the wager. I'm not saying goodbye. I'm saying I'll see you up there, complaining. It's better."),
            prop="teleport_array", thing="the teleport array"),
          B("interlude", "Under the Last Blood Moon",
            "The last of the army crosses. Han Xue waits for you at the array's edge. The moon is full and red over the sea of clouds.",
            (HAN, "Everyone's crossed. The Sect Master's waiting at the rim. Iron-Fang's army. Forty sects. Ye Wuming's children. All of them."),
            (HAN, "Let's go and finish it. Together. Like the letter in the reliquary said. Not alone."),
            ),
      ]),
]
